<h1>Updated to Optimise a threshold for every feature using validation data and train only independent/leaf features and calculate inherited features deterministically.</h1>

In [4]:
#!/usr/bin/env python3
"""
Fine-tune RoBERTa for hierarchical multi-label semantic feature tagging of
NOUN/PROPN tokens.

Compatible with Python 3.9.21.

Key design changes
------------------
1. The model is trained only on independent semantic features. For each token,
   any feature that can be inherited from a more specific present feature is
   removed from the neural target. This is a per-token reduction rather than a
   global "terminal leaf only" rule, so features such as Human, Time, Shape,
   Communication, etc. can still be predicted directly when they are the most
   specific available feature for that token.

2. All inherited features are reconstructed deterministically from
   FEATURE_PARENTS for validation, testing, reporting, and later inference.

3. A separate sigmoid threshold is optimised for every neural output using the
   validation split only. The selected thresholds are frozen before the test
   split is evaluated and are saved to prediction_thresholds.json.

4. The official test corpus may contain a direct independent target that never
   occurred independently in training. Such a label is never added from test
   data. Complete test truth is read directly from the source annotations so
   held-out evaluation remains valid without test leakage.

Tagged data:
    Training/validation:
        ewt_train_wordnet_wsd_features_wordnet_fixed.jsonl
    Test:
        ewt_test_wordnet_wsd_features_wordnet_fixed.jsonl

Sentence/token sources:
    Training/validation:
        UD_English-EWT-master/
        UD_English-EWT-master/
        en_ewt-ud-train.conllu
    Test:
        UD_English-EWT-master/
        UD_English-EWT-master/
        en_ewt-ud-test.conllu

The validation split is created only from the training corpus. The official
test corpus remains untouched until final evaluation.

Loss:
    BCEWithLogitsLoss over INDEPENDENT feature labels only.

Headline metrics:
    Computed after deterministic hierarchy expansion, so they describe the
    complete semantic feature sets rather than only the neural outputs.

Requirements:
    python -m pip install torch transformers datasets accelerate conllu scikit-learn

CUDA is required.
"""

from __future__ import annotations

import json
import random
from collections import Counter, defaultdict
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Set, Tuple

import numpy as np
import torch
import torch.nn as nn

from conllu import parse_incr
from sklearn.metrics import precision_recall_fscore_support
from torch.utils.data import Dataset

from transformers import (
    AutoModelForTokenClassification,
    AutoTokenizer,
    Trainer,
    TrainingArguments,
    set_seed,
)


# =============================================================================
# Configuration
# =============================================================================

TRAIN_JSONL_PATH = Path(
    "../data/ewt_train_wordnet_wsd_features_wordnet_fixed.jsonl"
    #"ewt_train_wordnet_wsd_features_fully_tagged_llm_reviewed.jsonl"
)

TEST_JSONL_PATH = Path(
    "../data/ewt_test_wordnet_wsd_features_wordnet_fixed.jsonl"
    #"ewt_test_wordnet_wsd_features_fully_tagged_llm_reviewed.jsonl"
)

TRAIN_CONLLU_PATH = Path(
    "../data/UD_English-EWT-master/"
    "UD_English-EWT-master/"
    "en_ewt-ud-train.conllu"
)

TEST_CONLLU_PATH = Path(
    "../data/UD_English-EWT-master/"
    "UD_English-EWT-master/"
    "en_ewt-ud-test.conllu"
)

# MODEL_NAME = "FacebookAI/roberta-base"
MODEL_NAME = "FacebookAI/roberta-large"

OUTPUT_DIR = Path("../models/roberta_semantic_features")

# Validation is sampled only from the eligible training sentences.
# The separate test file is never split and is used only for final evaluation.
VALIDATION_FRACTION = 0.20

# A sentence is not moved into validation if doing so would reduce any
# independent feature to fewer than this many positive TRAINING examples.
# This prevents rare direct targets (for example Human) from disappearing
# entirely from the model's training subset merely because of the random split.
MIN_TRAIN_POSITIVES_PER_FEATURE = 1

RANDOM_SEED = 42

MAX_LENGTH = 256

LEARNING_RATE = 2e-5
WEIGHT_DECAY = 0.01

TRAIN_BATCH_SIZE = 8
EVAL_BATCH_SIZE = 16

GRADIENT_ACCUMULATION_STEPS = 2

NUM_EPOCHS = 6

# Threshold used during epoch-by-epoch Trainer evaluation. Final thresholds are
# optimised per independent feature on the validation set after training.
DEFAULT_PREDICTION_THRESHOLD = 0.5

# Validation-only threshold search grid.
THRESHOLD_MIN = 0.05
THRESHOLD_MAX = 0.95
THRESHOLD_STEP = 0.01

# Only these POS categories receive feature supervision.
TARGET_POS = {"NOUN", "PROPN"}

# A NOUN/PROPN with no features is considered a failed source annotation rather
# than a valid all-negative target.
EXCLUDE_EMPTY_FEATURE_RECORDS = True

EVAL_STRATEGY = "epoch"

SPLIT_PATH = OUTPUT_DIR / "sentence_split.json"
LABELS_PATH = OUTPUT_DIR / "semantic_features.json"
THRESHOLDS_PATH = OUTPUT_DIR / "prediction_thresholds.json"
TEST_RESULTS_PATH = OUTPUT_DIR / "test_results.json"


# =============================================================================
# Feature hierarchy
# =============================================================================

# child -> direct parent(s)
FEATURE_PARENTS: Dict[str, Set[str]] = {
    "Organisation": {
        "Internal_Control",
        "Abstract",
    },
    "Natural_Force": {
        "Internal_Control",
    },
    "Animate": {
        "Internal_Control",
        "Natural",
    },
    "Human": {
        "Animate",
    },
    "Feminine": {
        "Human",
    },
    "Masculine": {
        "Human",
    },
    "Unspecified_Gender_or_Neuter": {
        "Human",
    },
    "Animal": {
        "Animate",
    },
    "Plant": {
        "Animate",
    },
    "Body_Part": {
        "Animate",
    },
    "Machine": {
        "Internal_Control",
        "Artefact",
    },
    "Vehicle": {
        "Machine",
    },
    "Natural": {
        "Concrete",
    },
    "Artefact": {
        "Concrete",
    },
    "Comestible": {
        "Concrete",
    },
    "Substance": {
        "Concrete",
    },
    "State_of_Matter": {
        "Concrete",
    },
    "Inanimate": {
        "Concrete",
    },
    "Garment": {
        "Artefact",
    },
    "Solid": {
        "State_of_Matter",
    },
    "Fluid": {
        "State_of_Matter",
    },
    "Rigidity": {
        "Solid",
    },
    "Shape": {
        "Solid",
    },
    "Rigid": {
        "Rigidity",
    },
    "Non_Rigid": {
        "Rigidity",
    },
    "Elongated": {
        "Shape",
    },
    "Pointy": {
        "Shape",
    },
    "Point_in_Time": {
        "Time",
    },
    "Duration": {
        "Time",
    },
    "Time": {
        "Abstract",
    },
    "Language": {
        "Abstract",
    },
    "Sound": {
        "Abstract",
    },
    "Communication": {
        "Abstract",
    },
    "Eventive": {
        "Abstract",
    },
    "Statement": {
        "Communication",
    },
    "Question": {
        "Communication",
    },
}


def validate_feature_hierarchy() -> None:
    """Fail early if FEATURE_PARENTS contains a cycle or invalid name."""

    all_features: Set[str] = set(FEATURE_PARENTS)

    for parents in FEATURE_PARENTS.values():
        all_features.update(parents)

    for feature in all_features:
        if not isinstance(feature, str) or not feature.strip():
            raise ValueError(
                "FEATURE_PARENTS contains an empty or non-string feature name."
            )

    visiting: Set[str] = set()
    visited: Set[str] = set()

    def visit(feature: str) -> None:
        if feature in visited:
            return

        if feature in visiting:
            raise ValueError(
                f"Cycle detected in FEATURE_PARENTS involving {feature!r}."
            )

        visiting.add(feature)

        for parent in FEATURE_PARENTS.get(feature, set()):
            visit(parent)

        visiting.remove(feature)
        visited.add(feature)

    for feature in sorted(all_features):
        visit(feature)


@lru_cache(maxsize=None)
def get_feature_ancestors(feature: str) -> frozenset:
    """Return every direct and indirect parent of *feature*."""

    ancestors: Set[str] = set()

    for parent in FEATURE_PARENTS.get(feature, set()):
        ancestors.add(parent)
        ancestors.update(get_feature_ancestors(parent))

    return frozenset(ancestors)


def expand_feature_hierarchy(features: Iterable[str]) -> Set[str]:
    """Add every deterministic ancestor required by FEATURE_PARENTS."""

    expanded: Set[str] = set(features)

    for feature in list(expanded):
        expanded.update(get_feature_ancestors(feature))

    return expanded


def reduce_to_independent_features(features: Iterable[str]) -> Set[str]:
    """
    Reduce a complete feature set to the features that must be predicted.

    A feature is redundant when it is an ancestor of another feature present
    for the same token. Such an ancestor can be reconstructed deterministically.

    Examples:
        {Human, Animate, Natural, Concrete, Internal_Control}
            -> {Human}

        {Feminine, Human, Animate, Natural, Concrete, Internal_Control}
            -> {Feminine}

        {Statement, Communication, Abstract, Time}
            -> {Statement, Time}

    This is deliberately PER TOKEN. It is not the same as training only labels
    that are global terminal leaves in the ontology. A generic Human can still
    be a direct neural target if no more specific Human child is present.
    """

    feature_set = set(features)

    inherited_from_other_features: Set[str] = set()

    for feature in feature_set:
        inherited_from_other_features.update(
            get_feature_ancestors(feature)
        )

    return feature_set - inherited_from_other_features


def missing_hierarchy_features(features: Iterable[str]) -> Set[str]:
    """Return ancestors required by the hierarchy but absent from *features*."""

    feature_set = set(features)
    return expand_feature_hierarchy(feature_set) - feature_set


# =============================================================================
# CUDA
# =============================================================================

def check_cuda() -> None:
    """Require CUDA rather than silently falling back to the CPU."""

    if not torch.cuda.is_available():
        raise RuntimeError(
            "CUDA is not available. This script is configured to require "
            "a CUDA-capable GPU."
        )

    print("=" * 80)
    print("CUDA")
    print("=" * 80)
    print(f"PyTorch version: {torch.__version__}")
    print(f"CUDA available: {torch.cuda.is_available()}")
    print(f"CUDA runtime: {torch.version.cuda}")
    print(f"GPU: {torch.cuda.get_device_name(0)}")

    props = torch.cuda.get_device_properties(0)

    print(
        "VRAM: "
        f"{props.total_memory / (1024 ** 3):.2f} GiB"
    )
    print()


# =============================================================================
# Load CoNLL-U
# =============================================================================

def load_conllu(path: Path) -> List[Any]:
    """Load all CoNLL-U sentences."""

    if not path.exists():
        raise FileNotFoundError(
            f"Could not find CoNLL-U file:\n{path.resolve()}"
        )

    sentences: List[Any] = []

    with path.open("r", encoding="utf-8") as handle:
        for sentence in parse_incr(handle):
            sentences.append(sentence)

    return sentences


def get_sentence_words(sentence: Any) -> Tuple[List[str], List[int]]:
    """
    Return ordinary integer-ID tokens and their original CoNLL-U token IDs.

    Multiword-token placeholder rows and empty nodes are excluded.
    """

    words: List[str] = []
    token_ids: List[int] = []

    for token in sentence:
        token_id = token.get("id")

        if not isinstance(token_id, int):
            continue

        form = token.get("form")

        if form is None:
            continue

        words.append(str(form))
        token_ids.append(token_id)

    return words, token_ids


# =============================================================================
# Load tagged JSONL
# =============================================================================

def load_tagged_records(
    path: Path,
) -> Dict[int, Dict[int, Dict[str, Any]]]:
    """
    Return:

        sentence_index
            -> token_id
                -> JSONL record

    Only NOUN and PROPN records are retained.
    """

    if not path.exists():
        raise FileNotFoundError(
            f"Could not find tagged JSONL:\n{path.resolve()}"
        )

    records: Dict[int, Dict[int, Dict[str, Any]]] = defaultdict(dict)

    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            line = line.strip()

            if not line:
                continue

            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                print(
                    "Warning: invalid JSON on line "
                    f"{line_number}: {exc}"
                )
                continue

            if record.get("upos") not in TARGET_POS:
                continue

            sentence_index = record.get("sentence_index")
            token_id = record.get("token_id")

            if not isinstance(sentence_index, int):
                continue

            if not isinstance(token_id, int):
                continue

            records[sentence_index][token_id] = record

    return dict(records)


# =============================================================================
# Labels
# =============================================================================

def clean_features(record: Dict[str, Any]) -> List[str]:
    """Return unique, non-empty COMPLETE feature names from a JSONL record."""

    raw = record.get("features", [])

    if not isinstance(raw, list):
        return []

    return sorted(
        {
            str(feature).strip()
            for feature in raw
            if str(feature).strip()
        }
    )


def get_independent_record_features(record: Dict[str, Any]) -> List[str]:
    """Return the per-token minimal feature set that the model must predict."""

    return sorted(
        reduce_to_independent_features(
            clean_features(record)
        )
    )


def build_full_label_vocabulary(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    training_sentence_indices: Sequence[int],
) -> List[str]:
    """
    Build the COMPLETE evaluation vocabulary from training data only.

    Deterministic ancestors are included even if a training record omitted one,
    although hierarchy closure is separately verified and should normally make
    this addition unnecessary.
    """

    labels: Set[str] = set()

    for sentence_index in training_sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            features = clean_features(record)
            labels.update(features)
            labels.update(expand_feature_hierarchy(features))

    if not labels:
        raise RuntimeError(
            "No semantic features were found in the training split."
        )

    return sorted(labels)


def build_prediction_label_vocabulary(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    training_sentence_indices: Sequence[int],
) -> List[str]:
    """Build the neural-output vocabulary from independent training targets."""

    labels: Set[str] = set()

    for sentence_index in training_sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            labels.update(
                get_independent_record_features(record)
            )

    if not labels:
        raise RuntimeError(
            "No independent semantic features were found in the training split."
        )

    return sorted(labels)


# =============================================================================
# Sentence selection and splitting
# =============================================================================

def get_eligible_sentence_indices(
    sentences: Sequence[Any],
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> List[int]:
    """Eligible sentences contain at least one non-empty NOUN/PROPN target."""

    eligible: List[int] = []

    for sentence_index in range(len(sentences)):
        token_records = tagged_records.get(sentence_index, {})

        valid_records = [
            record
            for record in token_records.values()
            if clean_features(record)
        ]

        if valid_records:
            eligible.append(sentence_index)

    return eligible


def get_sentence_independent_feature_counts(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    sentence_index: int,
) -> Counter:
    """Count independent positive targets in one source sentence."""

    counts: Counter = Counter()

    for record in tagged_records.get(sentence_index, {}).values():
        if not clean_features(record):
            continue

        for feature in get_independent_record_features(record):
            counts[feature] += 1

    return counts


def make_train_validation_split(
    eligible_indices: Sequence[int],
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> Dict[str, List[int]]:
    """Create a label-aware train/validation split from TRAINING only.

    The validation set is sampled from the training corpus, but a candidate
    sentence is moved to validation only if every independent feature occurring
    in that sentence will still have at least
    MIN_TRAIN_POSITIVES_PER_FEATURE positive examples left in the training
    subset.

    This matters for the per-token independent-target design: an internal
    hierarchy feature such as Human can occasionally be a direct neural target.
    A purely random split can otherwise place all of its rare direct examples
    in validation, leaving no Human output head to learn.

    The official test corpus is deliberately not accepted by this function, so
    test labels cannot influence the split.
    """

    if not 0.0 < VALIDATION_FRACTION < 1.0:
        raise ValueError(
            "VALIDATION_FRACTION must be strictly between 0 and 1."
        )

    if MIN_TRAIN_POSITIVES_PER_FEATURE < 1:
        raise ValueError(
            "MIN_TRAIN_POSITIVES_PER_FEATURE must be at least 1."
        )

    if len(eligible_indices) < 2:
        raise RuntimeError(
            "Need at least two eligible training sentences to create a "
            "train/validation split."
        )

    rng = random.Random(RANDOM_SEED)

    shuffled = list(eligible_indices)
    rng.shuffle(shuffled)

    target_validation_count = int(
        round(len(shuffled) * VALIDATION_FRACTION)
    )
    target_validation_count = max(1, target_validation_count)
    target_validation_count = min(
        target_validation_count,
        len(shuffled) - 1,
    )

    sentence_feature_counts: Dict[int, Counter] = {
        sentence_index: get_sentence_independent_feature_counts(
            tagged_records,
            sentence_index,
        )
        for sentence_index in shuffled
    }

    all_training_file_counts: Counter = Counter()

    for counts in sentence_feature_counts.values():
        all_training_file_counts.update(counts)

    remaining_train_counts: Counter = Counter(all_training_file_counts)

    validation_indices: List[int] = []
    validation_set: Set[int] = set()
    blocked_by_coverage = 0

    for sentence_index in shuffled:
        if len(validation_indices) >= target_validation_count:
            break

        sentence_counts = sentence_feature_counts[sentence_index]

        can_move_to_validation = all(
            remaining_train_counts[feature] - count
            >= MIN_TRAIN_POSITIVES_PER_FEATURE
            for feature, count in sentence_counts.items()
        )

        if not can_move_to_validation:
            blocked_by_coverage += 1
            continue

        validation_indices.append(sentence_index)
        validation_set.add(sentence_index)

        for feature, count in sentence_counts.items():
            remaining_train_counts[feature] -= count

    train_indices = [
        sentence_index
        for sentence_index in shuffled
        if sentence_index not in validation_set
    ]

    if not validation_indices:
        raise RuntimeError(
            "Could not allocate any validation sentences without removing "
            "the last training example of at least one independent feature."
        )

    if len(validation_indices) < target_validation_count:
        print(
            "Warning: label-coverage constraints reduced the validation "
            f"split from {target_validation_count:,} to "
            f"{len(validation_indices):,} sentences."
        )

    protected_features = sorted(
        feature
        for feature, count in remaining_train_counts.items()
        if count <= MIN_TRAIN_POSITIVES_PER_FEATURE
    )

    print()
    print("Label-aware train/validation split:")
    print(
        f"  Target validation sentences : {target_validation_count:,}"
    )
    print(
        f"  Actual validation sentences : {len(validation_indices):,}"
    )
    print(
        f"  Training sentences retained : {len(train_indices):,}"
    )
    print(
        f"  Candidates blocked to preserve rare labels: "
        f"{blocked_by_coverage:,}"
    )

    if protected_features:
        print(
            "  Features at minimum retained training support: "
            + ", ".join(protected_features)
        )

    # Internal consistency check: every independent feature found anywhere in
    # the eligible training file must still occur in the final training subset.
    all_training_file_labels = {
        feature
        for feature, count in all_training_file_counts.items()
        if count > 0
    }

    final_train_labels: Set[str] = set()

    for sentence_index in train_indices:
        final_train_labels.update(
            sentence_feature_counts[sentence_index].keys()
        )

    missing_after_split = all_training_file_labels - final_train_labels

    if missing_after_split:
        raise RuntimeError(
            "Internal split error: independent labels disappeared from the "
            f"training subset: {sorted(missing_after_split)}"
        )

    return {
        "train": train_indices,
        "validation": validation_indices,
    }


# =============================================================================
# Dataset
# =============================================================================

class SemanticFeatureDataset(Dataset):
    """
    RoBERTa multi-label token-classification dataset.

    IMPORTANT:
        labels contain only INDEPENDENT neural targets.

    Labels have shape:
        [sequence_length, number_of_prediction_features]

    For supervised tokens:
        0 = independent feature absent
        1 = independent feature present

    For ignored tokens:
        -100 across all labels

    Only the first RoBERTa subword corresponding to each source token receives
    supervision.
    """

    def __init__(
        self,
        sentences: Sequence[Any],
        sentence_indices: Sequence[int],
        tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
        tokenizer: Any,
        label2id: Dict[str, int],
        max_length: int,
    ) -> None:
        self.sentences = sentences
        self.sentence_indices = list(sentence_indices)
        self.tagged_records = tagged_records
        self.tokenizer = tokenizer
        self.label2id = label2id
        self.num_labels = len(label2id)
        self.max_length = max_length

    def __len__(self) -> int:
        return len(self.sentence_indices)

    def __getitem__(
        self,
        dataset_index: int,
    ) -> Dict[str, Any]:
        sentence_index = self.sentence_indices[dataset_index]
        sentence = self.sentences[sentence_index]

        words, token_ids = get_sentence_words(sentence)

        encoding = self.tokenizer(
            words,
            is_split_into_words=True,
            truncation=True,
            max_length=self.max_length,
            add_special_tokens=True,
        )

        word_ids = encoding.word_ids()
        labels: List[List[float]] = []
        previous_word_id: Optional[int] = None
        sentence_records = self.tagged_records.get(sentence_index, {})

        for word_id in word_ids:
            if word_id is None:
                labels.append([-100.0] * self.num_labels)
                previous_word_id = word_id
                continue

            # Ignore all but the first subword.
            if word_id == previous_word_id:
                labels.append([-100.0] * self.num_labels)
                continue

            previous_word_id = word_id

            if not 0 <= word_id < len(token_ids):
                labels.append([-100.0] * self.num_labels)
                continue

            conllu_token_id = token_ids[word_id]
            record = sentence_records.get(conllu_token_id)

            if record is None:
                labels.append([-100.0] * self.num_labels)
                continue

            full_features = clean_features(record)

            if not full_features and EXCLUDE_EMPTY_FEATURE_RECORDS:
                labels.append([-100.0] * self.num_labels)
                continue

            independent_features = reduce_to_independent_features(
                full_features
            )

            target = [0.0] * self.num_labels

            for feature in independent_features:
                label_id = self.label2id.get(feature)

                if label_id is not None:
                    target[label_id] = 1.0

            labels.append(target)

        encoding["labels"] = labels
        encoding["sentence_index"] = sentence_index

        return encoding


# =============================================================================
# Data collator
# =============================================================================

class MultiLabelTokenCollator:
    """Dynamically pad inputs and 3-D multi-label token targets."""

    def __init__(
        self,
        tokenizer: Any,
        num_labels: int,
    ) -> None:
        self.tokenizer = tokenizer
        self.num_labels = num_labels

    def __call__(
        self,
        features: List[Dict[str, Any]],
    ) -> Dict[str, torch.Tensor]:
        clean_features_list: List[Dict[str, Any]] = []
        labels_list: List[List[List[float]]] = []

        for item in features:
            item = dict(item)
            item.pop("sentence_index", None)

            labels = item.pop("labels")
            labels_list.append(labels)
            clean_features_list.append(item)

        batch = self.tokenizer.pad(
            clean_features_list,
            padding=True,
            return_tensors="pt",
        )

        batch_size = len(labels_list)
        max_seq_length = batch["input_ids"].shape[1]

        padded_labels = torch.full(
            (
                batch_size,
                max_seq_length,
                self.num_labels,
            ),
            -100.0,
            dtype=torch.float32,
        )

        for batch_index, labels in enumerate(labels_list):
            label_tensor = torch.tensor(
                labels,
                dtype=torch.float32,
            )

            sequence_length = label_tensor.shape[0]

            padded_labels[
                batch_index,
                :sequence_length,
                :,
            ] = label_tensor

        batch["labels"] = padded_labels

        return batch


# =============================================================================
# Model
# =============================================================================

class RobertaMultiLabelModel(nn.Module):
    """RoBERTa token classifier with BCE loss for independent feature labels."""

    def __init__(
        self,
        model_name: str,
        num_labels: int,
        id2label: Dict[int, str],
        label2id: Dict[str, int],
    ) -> None:
        super().__init__()

        self.model = AutoModelForTokenClassification.from_pretrained(
            model_name,
            num_labels=num_labels,
            id2label=id2label,
            label2id=label2id,
        )

        self.config = self.model.config

        self.loss_function = nn.BCEWithLogitsLoss(
            reduction="mean"
        )

    def forward(
        self,
        input_ids=None,
        attention_mask=None,
        labels=None,
        **kwargs,
    ):
        outputs = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            **kwargs,
        )

        logits = outputs.logits
        loss = None

        if labels is not None:
            valid_mask = labels[:, :, 0] != -100.0

            valid_logits = logits[valid_mask]
            valid_labels = labels[valid_mask]

            if valid_logits.numel() == 0:
                loss = logits.sum() * 0.0
            else:
                loss = self.loss_function(
                    valid_logits,
                    valid_labels,
                )

        return {
            "loss": loss,
            "logits": logits,
        }

    def save_pretrained(
        self,
        save_directory,
        **kwargs,
    ):
        return self.model.save_pretrained(
            save_directory,
            **kwargs,
        )


# =============================================================================
# Hierarchy matrices and array helpers
# =============================================================================

def build_hierarchy_expansion_matrix(
    prediction_labels: Sequence[str],
    full_labels: Sequence[str],
) -> np.ndarray:
    """
    Build a boolean matrix mapping neural outputs to complete feature sets.

    Shape:
        [number_of_prediction_features, number_of_full_features]
    """

    full_label2id = {
        label: index
        for index, label in enumerate(full_labels)
    }

    matrix = np.zeros(
        (len(prediction_labels), len(full_labels)),
        dtype=np.int8,
    )

    for prediction_id, feature in enumerate(prediction_labels):
        expanded = expand_feature_hierarchy({feature})

        for expanded_feature in expanded:
            full_id = full_label2id.get(expanded_feature)

            if full_id is None:
                raise RuntimeError(
                    "Hierarchy expansion produced a feature absent from the "
                    f"full vocabulary: {expanded_feature!r}."
                )

            matrix[prediction_id, full_id] = 1

    return matrix


def expand_binary_feature_matrix(
    independent_matrix: np.ndarray,
    hierarchy_matrix: np.ndarray,
) -> np.ndarray:
    """Expand [tokens, independent] binary values to [tokens, complete]."""

    expanded = independent_matrix.astype(np.int32) @ hierarchy_matrix.astype(
        np.int32
    )

    return (expanded > 0).astype(np.int32)


def extract_valid_token_arrays(
    logits: np.ndarray,
    labels: np.ndarray,
) -> Tuple[np.ndarray, np.ndarray]:
    """Return probabilities and true independent labels for supervised tokens."""

    valid_token_mask = labels[:, :, 0] != -100.0

    probabilities = sigmoid_numpy(logits)[
        valid_token_mask
    ]

    true_labels = labels[
        valid_token_mask
    ].astype(np.int32)

    return probabilities, true_labels


def build_full_truth_matrix_for_dataset(
    dataset: "SemanticFeatureDataset",
    full_labels: Sequence[str],
) -> np.ndarray:
    """Build complete source truth for every supervised token in dataset order.

    This is intentionally independent of the neural-output vocabulary.  It is
    therefore safe and necessary for a held-out test corpus that may contain a
    feature such as ``Human`` as a direct independent target even when that
    feature never occurred independently in the training corpus.

    The model is still trained only on training-derived independent output
    heads.  This function merely preserves the complete gold annotations for
    fair hierarchy-expanded evaluation.
    """

    full_label2id = {
        label: index
        for index, label in enumerate(full_labels)
    }

    rows: List[np.ndarray] = []

    for sentence_index in dataset.sentence_indices:
        sentence = dataset.sentences[sentence_index]
        words, token_ids = get_sentence_words(sentence)

        encoding = dataset.tokenizer(
            words,
            is_split_into_words=True,
            truncation=True,
            max_length=dataset.max_length,
            add_special_tokens=True,
        )

        word_ids = encoding.word_ids()
        previous_word_id: Optional[int] = None
        sentence_records = dataset.tagged_records.get(sentence_index, {})

        for word_id in word_ids:
            if word_id is None:
                previous_word_id = word_id
                continue

            # Match SemanticFeatureDataset.__getitem__: only the first subword
            # for each source token receives supervision.
            if word_id == previous_word_id:
                continue

            previous_word_id = word_id

            if not 0 <= word_id < len(token_ids):
                continue

            conllu_token_id = token_ids[word_id]
            record = sentence_records.get(conllu_token_id)

            if record is None:
                continue

            features = clean_features(record)

            if not features and EXCLUDE_EMPTY_FEATURE_RECORDS:
                continue

            expanded_features = expand_feature_hierarchy(features)
            row = np.zeros(len(full_labels), dtype=np.int32)

            for feature in expanded_features:
                label_id = full_label2id.get(feature)

                if label_id is None:
                    raise RuntimeError(
                        "Complete source truth contains a feature absent from "
                        f"the training-derived full vocabulary: {feature!r}."
                    )

                row[label_id] = 1

            rows.append(row)

    if not rows:
        return np.zeros((0, len(full_labels)), dtype=np.int32)

    return np.stack(rows, axis=0)


# =============================================================================
# Metrics and thresholds
# =============================================================================

def sigmoid_numpy(x: np.ndarray) -> np.ndarray:
    """Numerically stable sigmoid."""

    x = np.clip(x, -50.0, 50.0)
    return 1.0 / (1.0 + np.exp(-x))


def make_threshold_vector(
    prediction_labels: Sequence[str],
    thresholds: Dict[str, float],
) -> np.ndarray:
    """Return thresholds in neural-output column order."""

    return np.asarray(
        [
            float(
                thresholds.get(
                    label,
                    DEFAULT_PREDICTION_THRESHOLD,
                )
            )
            for label in prediction_labels
        ],
        dtype=np.float32,
    )


def threshold_probabilities(
    probabilities: np.ndarray,
    threshold_vector: np.ndarray,
) -> np.ndarray:
    """Apply one threshold per independent feature."""

    return (
        probabilities >= threshold_vector.reshape(1, -1)
    ).astype(np.int32)


def calculate_average_metrics(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    prefix: str = "",
) -> Dict[str, float]:
    """Calculate micro and macro precision/recall/F1."""

    if y_true.shape[0] == 0:
        return {
            f"{prefix}precision_micro": 0.0,
            f"{prefix}recall_micro": 0.0,
            f"{prefix}f1_micro": 0.0,
            f"{prefix}precision_macro": 0.0,
            f"{prefix}recall_macro": 0.0,
            f"{prefix}f1_macro": 0.0,
        }

    (
        precision_micro,
        recall_micro,
        f1_micro,
        _,
    ) = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="micro",
        zero_division=0,
    )

    (
        precision_macro,
        recall_macro,
        f1_macro,
        _,
    ) = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="macro",
        zero_division=0,
    )

    return {
        f"{prefix}precision_micro": float(precision_micro),
        f"{prefix}recall_micro": float(recall_micro),
        f"{prefix}f1_micro": float(f1_micro),
        f"{prefix}precision_macro": float(precision_macro),
        f"{prefix}recall_macro": float(recall_macro),
        f"{prefix}f1_macro": float(f1_macro),
    }


def calculate_hierarchical_metrics_from_probabilities(
    probabilities: np.ndarray,
    y_true_independent: np.ndarray,
    threshold_vector: np.ndarray,
    hierarchy_matrix: np.ndarray,
    y_true_full: Optional[np.ndarray] = None,
) -> Dict[str, float]:
    """
    Report both direct neural-output metrics and complete hierarchy metrics.

    Unprefixed metrics are the COMPLETE hierarchy metrics.  During ordinary
    training/validation, complete truth can be reconstructed from the
    independent targets.  For a genuinely held-out test corpus, ``y_true_full``
    may instead be supplied directly from the source annotations so an unseen
    direct independent label is not silently erased from the gold truth.
    """

    y_pred_independent = threshold_probabilities(
        probabilities,
        threshold_vector,
    )

    if y_true_full is None:
        y_true_full = expand_binary_feature_matrix(
            y_true_independent,
            hierarchy_matrix,
        )

    if y_true_full.shape[0] != y_true_independent.shape[0]:
        raise RuntimeError(
            "Complete and independent truth matrices contain different "
            f"numbers of supervised tokens: {y_true_full.shape[0]} vs "
            f"{y_true_independent.shape[0]}."
        )

    y_pred_full = expand_binary_feature_matrix(
        y_pred_independent,
        hierarchy_matrix,
    )

    metrics = calculate_average_metrics(
        y_true_full,
        y_pred_full,
        prefix="",
    )

    metrics.update(
        calculate_average_metrics(
            y_true_independent,
            y_pred_independent,
            prefix="direct_",
        )
    )

    return metrics


def make_compute_metrics(
    prediction_labels: Sequence[str],
    hierarchy_matrix: np.ndarray,
):
    """Create Trainer metrics using the fixed default 0.5 thresholds."""

    default_thresholds = np.full(
        len(prediction_labels),
        DEFAULT_PREDICTION_THRESHOLD,
        dtype=np.float32,
    )

    def compute_metrics(eval_prediction) -> Dict[str, float]:
        logits, labels = eval_prediction

        probabilities, y_true_independent = extract_valid_token_arrays(
            logits,
            labels,
        )

        return calculate_hierarchical_metrics_from_probabilities(
            probabilities=probabilities,
            y_true_independent=y_true_independent,
            threshold_vector=default_thresholds,
            hierarchy_matrix=hierarchy_matrix,
        )

    return compute_metrics


def build_threshold_grid() -> np.ndarray:
    """Build an inclusive, stable validation threshold search grid."""

    if THRESHOLD_STEP <= 0:
        raise ValueError("THRESHOLD_STEP must be > 0.")

    if not 0.0 < THRESHOLD_MIN < 1.0:
        raise ValueError("THRESHOLD_MIN must be between 0 and 1.")

    if not 0.0 < THRESHOLD_MAX < 1.0:
        raise ValueError("THRESHOLD_MAX must be between 0 and 1.")

    if THRESHOLD_MIN > THRESHOLD_MAX:
        raise ValueError("THRESHOLD_MIN cannot exceed THRESHOLD_MAX.")

    count = int(
        round(
            (THRESHOLD_MAX - THRESHOLD_MIN)
            / THRESHOLD_STEP
        )
    ) + 1

    return np.linspace(
        THRESHOLD_MIN,
        THRESHOLD_MAX,
        count,
        dtype=np.float64,
    )


def binary_metrics_for_column(
    y_true: np.ndarray,
    y_pred: np.ndarray,
) -> Tuple[float, float, float, int]:
    """Return binary precision, recall, F1 and positive support."""

    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="binary",
        zero_division=0,
    )

    support = int(y_true.sum())

    return (
        float(precision),
        float(recall),
        float(f1),
        support,
    )


def optimise_feature_thresholds(
    probabilities: np.ndarray,
    y_true_independent: np.ndarray,
    prediction_labels: Sequence[str],
) -> Tuple[Dict[str, float], Dict[str, Dict[str, float]]]:
    """
    Optimise one sigmoid threshold per independent feature on VALIDATION ONLY.

    Objective:
        maximise that feature's binary F1.

    Stability rules:
    - If validation has no positives or no negatives for a feature, keep 0.5.
    - If several thresholds tie for best F1, choose the one closest to 0.5.
      This avoids unnecessarily extreme thresholds for flat validation curves.
    """

    grid = build_threshold_grid()

    thresholds: Dict[str, float] = {}
    diagnostics: Dict[str, Dict[str, float]] = {}

    for label_id, feature in enumerate(prediction_labels):
        y_true = y_true_independent[:, label_id]
        probs = probabilities[:, label_id]

        positive_support = int(y_true.sum())
        negative_support = int((1 - y_true).sum())

        default_pred = (
            probs >= DEFAULT_PREDICTION_THRESHOLD
        ).astype(np.int32)

        (
            default_precision,
            default_recall,
            default_f1,
            _,
        ) = binary_metrics_for_column(
            y_true,
            default_pred,
        )

        if positive_support == 0 or negative_support == 0:
            best_threshold = DEFAULT_PREDICTION_THRESHOLD
        else:
            best_f1 = -1.0
            best_candidates: List[float] = []

            for threshold in grid:
                y_pred = (probs >= threshold).astype(np.int32)

                _, _, f1, _ = binary_metrics_for_column(
                    y_true,
                    y_pred,
                )

                if f1 > best_f1 + 1e-12:
                    best_f1 = f1
                    best_candidates = [float(threshold)]
                elif abs(f1 - best_f1) <= 1e-12:
                    best_candidates.append(float(threshold))

            best_threshold = min(
                best_candidates,
                key=lambda value: (
                    abs(value - DEFAULT_PREDICTION_THRESHOLD),
                    value,
                ),
            )

        best_pred = (
            probs >= best_threshold
        ).astype(np.int32)

        (
            best_precision,
            best_recall,
            best_f1,
            _,
        ) = binary_metrics_for_column(
            y_true,
            best_pred,
        )

        thresholds[feature] = float(best_threshold)

        diagnostics[feature] = {
            "threshold": float(best_threshold),
            "support": positive_support,
            "negative_support": negative_support,
            "precision_default": default_precision,
            "recall_default": default_recall,
            "f1_default": default_f1,
            "precision_optimised": best_precision,
            "recall_optimised": best_recall,
            "f1_optimised": best_f1,
            "f1_change": best_f1 - default_f1,
        }

    return thresholds, diagnostics


def calculate_per_feature_metrics_from_binary(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    labels: Sequence[str],
) -> Dict[str, Dict[str, float]]:
    """Calculate binary precision/recall/F1 independently for each column."""

    results: Dict[str, Dict[str, float]] = {}

    for label_id, feature in enumerate(labels):
        precision, recall, f1, support = binary_metrics_for_column(
            y_true[:, label_id],
            y_pred[:, label_id],
        )

        results[feature] = {
            "precision": precision,
            "recall": recall,
            "f1": f1,
            "support": support,
        }

    return results


# =============================================================================
# Dataset diagnostics and validation
# =============================================================================

def count_feature_occurrences(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    sentence_indices: Sequence[int],
    independent_only: bool = False,
) -> Counter:
    """Count complete or independent positive labels in a split."""

    counts: Counter = Counter()

    for sentence_index in sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            if independent_only:
                features = get_independent_record_features(record)
            else:
                features = clean_features(record)

            for feature in features:
                counts[feature] += 1

    return counts


def count_empty_records(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    sentence_indices: Sequence[int],
) -> int:
    """Count NOUN/PROPN records having no complete feature tags."""

    count = 0

    for sentence_index in sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            if not clean_features(record):
                count += 1

    return count


def verify_full_label_coverage(
    full_labels: Sequence[str],
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
) -> None:
    """Ensure validation/test contain no complete label unseen in training."""

    training_labels = set(full_labels)

    for split_name in ("validation", "test"):
        tagged_records, sentence_indices = split_sources[split_name]
        observed: Set[str] = set()

        for sentence_index in sentence_indices:
            for record in tagged_records.get(sentence_index, {}).values():
                observed.update(clean_features(record))

        unknown = observed - training_labels

        if unknown:
            raise RuntimeError(
                f"{split_name} contains full labels unseen in training: "
                f"{sorted(unknown)}"
            )


def verify_prediction_label_coverage(
    prediction_labels: Sequence[str],
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
    training_file_prediction_labels: Optional[Sequence[str]] = None,
) -> Dict[str, Dict[str, int]]:
    """Check independent-target coverage without leaking test labels.

    Validation remains strict: every validation independent target must have a
    training-derived neural output head.

    Test is different.  A genuine held-out corpus may contain a direct
    independent target that never occurred independently in training.  Such a
    label must NOT be added to the model from the test set.  Instead, report it
    and let complete-feature evaluation use the source gold matrix directly.
    """

    training_labels = set(prediction_labels)
    training_file_labels = (
        set(training_file_prediction_labels)
        if training_file_prediction_labels is not None
        else set(training_labels)
    )

    unseen_test_support: Dict[str, Dict[str, int]] = {}

    for split_name in ("validation", "test"):
        tagged_records, sentence_indices = split_sources[split_name]
        observed_counts: Counter = Counter()

        for sentence_index in sentence_indices:
            for record in tagged_records.get(sentence_index, {}).values():
                for feature in get_independent_record_features(record):
                    observed_counts[feature] += 1

        observed = set(observed_counts)
        unknown = observed - training_labels

        if not unknown:
            continue

        lost_due_to_split = unknown & training_file_labels
        absent_from_training_file = unknown - training_file_labels

        if split_name == "validation":
            details: List[str] = []

            if lost_due_to_split:
                details.append(
                    "present somewhere in the training file but absent from "
                    f"the training subset: {sorted(lost_due_to_split)}"
                )

            if absent_from_training_file:
                details.append(
                    "never occur as independent targets anywhere in the "
                    f"training file: {sorted(absent_from_training_file)}"
                )

            raise RuntimeError(
                "validation contains independent labels with no learnable "
                "training output. "
                + "; ".join(details)
            )

        # For the official test set, do not modify the model vocabulary.
        unseen_test_support = {
            feature: {
                "support": int(observed_counts[feature]),
                "present_in_training_file_as_independent": int(
                    feature in training_file_labels
                ),
            }
            for feature in sorted(unknown)
        }

        print()
        print("=" * 80)
        print("HELD-OUT TEST LABEL COVERAGE WARNING")
        print("=" * 80)
        print(
            "The test corpus contains direct independent targets that have no "
            "training-derived neural output head. They will NOT be added to "
            "the model vocabulary. Complete test truth will be read directly "
            "from the source annotations instead."
        )

        for feature in sorted(unknown):
            print(
                f"  {feature:35s} support={observed_counts[feature]:,}"
            )

        print()

    return unseen_test_support


def verify_hierarchy_closure(
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
) -> None:
    """
    Ensure source feature sets already contain all ancestors required by the
    hierarchy. This prevents evaluation against inconsistent source targets.
    """

    problems: List[str] = []
    max_examples = 20

    for split_name in ("train", "validation", "test"):
        tagged_records, sentence_indices = split_sources[split_name]
        problem_count = 0

        for sentence_index in sentence_indices:
            for token_id, record in tagged_records.get(
                sentence_index,
                {},
            ).items():
                features = clean_features(record)

                if not features:
                    continue

                missing = missing_hierarchy_features(features)

                if not missing:
                    continue

                problem_count += 1

                if len(problems) < max_examples:
                    problems.append(
                        f"{split_name}: sentence={sentence_index}, "
                        f"token={token_id}, "
                        f"form={record.get('form')!r}, "
                        f"missing={sorted(missing)}"
                    )

        if problem_count:
            print(
                f"Hierarchy closure problems in {split_name}: "
                f"{problem_count:,} token(s)"
            )

    if problems:
        example_text = "\n".join(
            f"  - {problem}"
            for problem in problems
        )

        raise RuntimeError(
            "The input dataset is not hierarchy-closed. Fix the source tags "
            "before training so deterministic reduction/expansion is exact.\n"
            f"Examples:\n{example_text}"
        )


def print_split_statistics(
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
) -> None:
    print("=" * 80)
    print("DATASET SPLIT")
    print("=" * 80)

    for split_name in ("train", "validation", "test"):
        tagged_records, indices = split_sources[split_name]

        full_counts = count_feature_occurrences(
            tagged_records,
            indices,
            independent_only=False,
        )

        independent_counts = count_feature_occurrences(
            tagged_records,
            indices,
            independent_only=True,
        )

        empty_count = count_empty_records(
            tagged_records,
            indices,
        )

        noun_count = sum(
            len(tagged_records.get(index, {}))
            for index in indices
        )

        source_name = (
            "training file"
            if split_name in {"train", "validation"}
            else "test file"
        )

        print(
            f"{split_name:12s}: "
            f"{len(indices):,} sentences | "
            f"{noun_count:,} NOUN/PROPN tokens | "
            f"{sum(full_counts.values()):,} complete positives -> "
            f"{sum(independent_counts.values()):,} independent positives | "
            f"{empty_count:,} empty-feature tokens excluded | "
            f"source={source_name}"
        )

    print()


def print_prediction_label_statistics(
    prediction_labels: Sequence[str],
    full_labels: Sequence[str],
    train_tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    train_sentence_indices: Sequence[int],
) -> None:
    """Show which labels are neural outputs versus deterministic-only parents."""

    train_independent_counts = count_feature_occurrences(
        train_tagged_records,
        train_sentence_indices,
        independent_only=True,
    )

    prediction_set = set(prediction_labels)
    deterministic_only = [
        feature
        for feature in full_labels
        if feature not in prediction_set
    ]

    print("=" * 80)
    print("NEURAL OUTPUT FEATURES")
    print("=" * 80)
    print(
        f"Complete evaluation features: {len(full_labels)}"
    )
    print(
        f"Independent neural outputs: {len(prediction_labels)}"
    )
    print(
        f"Deterministic-only features in this training split: "
        f"{len(deterministic_only)}"
    )
    print()

    print(
        f"{'Feature':35s} "
        f"{'Independent train support':>26s}"
    )
    print("-" * 64)

    for feature in prediction_labels:
        print(
            f"{feature:35s} "
            f"{train_independent_counts[feature]:26d}"
        )

    if deterministic_only:
        print()
        print("Deterministic-only in this split:")

        for feature in deterministic_only:
            print(f"  - {feature}")

    print()


# =============================================================================
# Reporting helpers
# =============================================================================

def print_metric_dictionary(
    metrics: Dict[str, float],
) -> None:
    for key, value in sorted(metrics.items()):
        print(f"{key}: {value}")


def print_threshold_table(
    prediction_labels: Sequence[str],
    diagnostics: Dict[str, Dict[str, float]],
) -> None:
    print()
    print("=" * 100)
    print("VALIDATION-OPTIMISED THRESHOLDS")
    print("=" * 100)

    heading = (
        f"{'Feature':35s} "
        f"{'Threshold':>10s} "
        f"{'Support':>9s} "
        f"{'F1@0.5':>10s} "
        f"{'F1 opt':>10s} "
        f"{'Change':>10s}"
    )

    print(heading)
    print("-" * len(heading))

    for feature in prediction_labels:
        result = diagnostics[feature]

        print(
            f"{feature:35s} "
            f"{result['threshold']:10.2f} "
            f"{int(result['support']):9d} "
            f"{result['f1_default']:10.4f} "
            f"{result['f1_optimised']:10.4f} "
            f"{result['f1_change']:+10.4f}"
        )


def print_per_feature_table(
    title: str,
    labels: Sequence[str],
    results: Dict[str, Dict[str, float]],
) -> None:
    print()
    print("=" * 80)
    print(title)
    print("=" * 80)

    heading = (
        f"{'Feature':35s} "
        f"{'Precision':>10s} "
        f"{'Recall':>10s} "
        f"{'F1':>10s} "
        f"{'Support':>10s}"
    )

    print(heading)
    print("-" * len(heading))

    for feature in labels:
        result = results[feature]

        print(
            f"{feature:35s} "
            f"{result['precision']:10.4f} "
            f"{result['recall']:10.4f} "
            f"{result['f1']:10.4f} "
            f"{result['support']:10d}"
        )


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    set_seed(RANDOM_SEED)

    validate_feature_hierarchy()
    check_cuda()

    # -------------------------------------------------------------------------
    # Load the independent train and test corpora
    # -------------------------------------------------------------------------

    print("=" * 80)
    print("LOADING DATA")
    print("=" * 80)

    train_sentences = load_conllu(TRAIN_CONLLU_PATH)
    test_sentences = load_conllu(TEST_CONLLU_PATH)

    train_tagged_records = load_tagged_records(TRAIN_JSONL_PATH)
    test_tagged_records = load_tagged_records(TEST_JSONL_PATH)

    print(
        "Training CoNLL-U sentences: "
        f"{len(train_sentences):,}"
    )
    print(
        "Test CoNLL-U sentences: "
        f"{len(test_sentences):,}"
    )
    print(
        "Training sentences represented in tagged JSONL: "
        f"{len(train_tagged_records):,}"
    )
    print(
        "Test sentences represented in tagged JSONL: "
        f"{len(test_tagged_records):,}"
    )

    train_target_record_count = sum(
        len(records)
        for records in train_tagged_records.values()
    )
    test_target_record_count = sum(
        len(records)
        for records in test_tagged_records.values()
    )

    print(
        "Training tagged NOUN/PROPN records: "
        f"{train_target_record_count:,}"
    )
    print(
        "Test tagged NOUN/PROPN records: "
        f"{test_target_record_count:,}"
    )
    print()

    # -------------------------------------------------------------------------
    # Build train/validation from TRAIN only; keep TEST untouched
    # -------------------------------------------------------------------------

    eligible_train_indices = get_eligible_sentence_indices(
        train_sentences,
        train_tagged_records,
    )
    eligible_test_indices = get_eligible_sentence_indices(
        test_sentences,
        test_tagged_records,
    )

    print(
        "Eligible training-file sentences with at least one non-empty "
        "feature target: "
        f"{len(eligible_train_indices):,}"
    )
    print(
        "Eligible test-file sentences with at least one non-empty "
        "feature target: "
        f"{len(eligible_test_indices):,}"
    )

    train_validation_split = make_train_validation_split(
        eligible_train_indices,
        train_tagged_records,
    )

    train_indices = train_validation_split["train"]
    validation_indices = train_validation_split["validation"]
    test_indices = list(eligible_test_indices)

    split_sources = {
        "train": (train_tagged_records, train_indices),
        "validation": (train_tagged_records, validation_indices),
        "test": (test_tagged_records, test_indices),
    }

    split_document = {
        "random_seed": RANDOM_SEED,
        "validation_fraction": VALIDATION_FRACTION,
        "train_jsonl": str(TRAIN_JSONL_PATH),
        "test_jsonl": str(TEST_JSONL_PATH),
        "train_conllu": str(TRAIN_CONLLU_PATH),
        "test_conllu": str(TEST_CONLLU_PATH),
        "index_spaces": {
            "train": "training corpus",
            "validation": "training corpus",
            "test": "test corpus",
        },
        "train": train_indices,
        "validation": validation_indices,
        "test": test_indices,
    }

    with SPLIT_PATH.open("w", encoding="utf-8") as handle:
        json.dump(
            split_document,
            handle,
            ensure_ascii=False,
            indent=2,
        )

    # The reduction is exact only when the source data are hierarchy-closed.
    verify_hierarchy_closure(split_sources)

    # -------------------------------------------------------------------------
    # Separate complete and neural-output vocabularies
    # -------------------------------------------------------------------------

    # Inventory of independent labels in the entire TRAINING FILE. This is used
    # only as a diagnostic/consistency check; model vocabularies below are still
    # built from the actual training subset.
    training_file_prediction_labels = build_prediction_label_vocabulary(
        train_tagged_records,
        eligible_train_indices,
    )

    # IMPORTANT: both model/evaluation vocabularies are built from the TRAIN
    # subset only.
    full_labels = build_full_label_vocabulary(
        train_tagged_records,
        train_indices,
    )

    prediction_labels = build_prediction_label_vocabulary(
        train_tagged_records,
        train_indices,
    )

    verify_full_label_coverage(
        full_labels,
        split_sources,
    )

    unseen_test_independent_labels = verify_prediction_label_coverage(
        prediction_labels,
        split_sources,
        training_file_prediction_labels=training_file_prediction_labels,
    )

    prediction_label2id = {
        label: index
        for index, label in enumerate(prediction_labels)
    }

    prediction_id2label = {
        index: label
        for label, index in prediction_label2id.items()
    }

    full_label2id = {
        label: index
        for index, label in enumerate(full_labels)
    }

    hierarchy_matrix = build_hierarchy_expansion_matrix(
        prediction_labels,
        full_labels,
    )

    # Keep "labels" / "label2id" / "id2label" as aliases for the MODEL HEADS
    # so existing inference code can still discover the neural output order.
    # The complete post-inheritance vocabulary is stored separately.
    label_document = {
        "labels": prediction_labels,
        "label2id": prediction_label2id,
        "id2label": {
            str(key): value
            for key, value in prediction_id2label.items()
        },
        "prediction_labels": prediction_labels,
        "prediction_label2id": prediction_label2id,
        "full_labels": full_labels,
        "full_label2id": full_label2id,
        "feature_parents": {
            child: sorted(parents)
            for child, parents in sorted(FEATURE_PARENTS.items())
        },
        "target_representation": "per_token_independent_features",
    }

    with LABELS_PATH.open("w", encoding="utf-8") as handle:
        json.dump(
            label_document,
            handle,
            ensure_ascii=False,
            indent=2,
        )

    print_split_statistics(split_sources)

    print_prediction_label_statistics(
        prediction_labels,
        full_labels,
        train_tagged_records,
        train_indices,
    )

    # -------------------------------------------------------------------------
    # Tokeniser and datasets
    # -------------------------------------------------------------------------

    tokenizer = AutoTokenizer.from_pretrained(
        MODEL_NAME,
        use_fast=True,
        add_prefix_space=True,
    )

    train_dataset = SemanticFeatureDataset(
        sentences=train_sentences,
        sentence_indices=train_indices,
        tagged_records=train_tagged_records,
        tokenizer=tokenizer,
        label2id=prediction_label2id,
        max_length=MAX_LENGTH,
    )

    validation_dataset = SemanticFeatureDataset(
        sentences=train_sentences,
        sentence_indices=validation_indices,
        tagged_records=train_tagged_records,
        tokenizer=tokenizer,
        label2id=prediction_label2id,
        max_length=MAX_LENGTH,
    )

    test_dataset = SemanticFeatureDataset(
        sentences=test_sentences,
        sentence_indices=test_indices,
        tagged_records=test_tagged_records,
        tokenizer=tokenizer,
        label2id=prediction_label2id,
        max_length=MAX_LENGTH,
    )

    data_collator = MultiLabelTokenCollator(
        tokenizer=tokenizer,
        num_labels=len(prediction_labels),
    )

    # -------------------------------------------------------------------------
    # Model
    # -------------------------------------------------------------------------

    model = RobertaMultiLabelModel(
        model_name=MODEL_NAME,
        num_labels=len(prediction_labels),
        id2label=prediction_id2label,
        label2id=prediction_label2id,
    )

    # -------------------------------------------------------------------------
    # Training configuration
    # -------------------------------------------------------------------------

    use_bf16 = torch.cuda.is_bf16_supported()

    training_args = TrainingArguments(
        output_dir=str(OUTPUT_DIR),

        learning_rate=LEARNING_RATE,
        weight_decay=WEIGHT_DECAY,

        per_device_train_batch_size=TRAIN_BATCH_SIZE,
        per_device_eval_batch_size=EVAL_BATCH_SIZE,

        gradient_accumulation_steps=(
            GRADIENT_ACCUMULATION_STEPS
        ),

        num_train_epochs=NUM_EPOCHS,

        eval_strategy=EVAL_STRATEGY,
        save_strategy="epoch",
        logging_strategy="steps",
        logging_steps=50,

        load_best_model_at_end=True,

        # This is the COMPLETE hierarchy-expanded F1 at the fixed 0.5
        # threshold. Threshold optimisation happens only after the best model
        # has been selected, preventing test leakage.
        metric_for_best_model="f1_macro",
        greater_is_better=True,

        save_total_limit=2,

        bf16=use_bf16,
        fp16=not use_bf16,

        dataloader_num_workers=4,
        dataloader_pin_memory=True,

        optim="adamw_torch",

        report_to="none",

        seed=RANDOM_SEED,
        data_seed=RANDOM_SEED,

        remove_unused_columns=False,
        eval_accumulation_steps=16,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=validation_dataset,
        processing_class=tokenizer,
        data_collator=data_collator,
        compute_metrics=make_compute_metrics(
            prediction_labels,
            hierarchy_matrix,
        ),
    )

    # -------------------------------------------------------------------------
    # Train
    # -------------------------------------------------------------------------

    print("=" * 80)
    print("TRAINING")
    print("=" * 80)

    trainer.train()

    # -------------------------------------------------------------------------
    # Save best model
    # -------------------------------------------------------------------------

    best_model_dir = OUTPUT_DIR / "best_model"

    trainer.save_model(str(best_model_dir))
    tokenizer.save_pretrained(str(best_model_dir))

    # Save the richer semantic metadata inside best_model as well so inference
    # does not need to know the parent output directory.
    with (best_model_dir / "semantic_features.json").open(
        "w",
        encoding="utf-8",
    ) as handle:
        json.dump(
            label_document,
            handle,
            ensure_ascii=False,
            indent=2,
        )

    # -------------------------------------------------------------------------
    # Validation prediction at default threshold
    # -------------------------------------------------------------------------

    print()
    print("=" * 80)
    print("FINAL VALIDATION RESULTS AT DEFAULT THRESHOLD")
    print("=" * 80)

    validation_output = trainer.predict(
        validation_dataset,
        metric_key_prefix="validation_default",
    )

    print_metric_dictionary(validation_output.metrics)

    validation_probabilities, validation_true_independent = (
        extract_valid_token_arrays(
            validation_output.predictions,
            validation_output.label_ids,
        )
    )

    # -------------------------------------------------------------------------
    # Validation-only per-feature threshold optimisation
    # -------------------------------------------------------------------------

    optimised_thresholds, threshold_diagnostics = (
        optimise_feature_thresholds(
            probabilities=validation_probabilities,
            y_true_independent=validation_true_independent,
            prediction_labels=prediction_labels,
        )
    )

    threshold_vector = make_threshold_vector(
        prediction_labels,
        optimised_thresholds,
    )

    print_threshold_table(
        prediction_labels,
        threshold_diagnostics,
    )

    validation_optimised_metrics = (
        calculate_hierarchical_metrics_from_probabilities(
            probabilities=validation_probabilities,
            y_true_independent=validation_true_independent,
            threshold_vector=threshold_vector,
            hierarchy_matrix=hierarchy_matrix,
        )
    )

    print()
    print("=" * 80)
    print("FINAL VALIDATION RESULTS WITH OPTIMISED THRESHOLDS")
    print("=" * 80)
    print_metric_dictionary(validation_optimised_metrics)

    threshold_document = {
        "optimised_on": "validation",
        "objective": "per_feature_binary_f1",
        "default_threshold": DEFAULT_PREDICTION_THRESHOLD,
        "grid": {
            "minimum": THRESHOLD_MIN,
            "maximum": THRESHOLD_MAX,
            "step": THRESHOLD_STEP,
        },
        "thresholds": optimised_thresholds,
        "diagnostics": threshold_diagnostics,
    }

    with THRESHOLDS_PATH.open("w", encoding="utf-8") as handle:
        json.dump(
            threshold_document,
            handle,
            ensure_ascii=False,
            indent=2,
        )

    with (best_model_dir / "prediction_thresholds.json").open(
        "w",
        encoding="utf-8",
    ) as handle:
        json.dump(
            threshold_document,
            handle,
            ensure_ascii=False,
            indent=2,
        )

    # -------------------------------------------------------------------------
    # Test: thresholds are now frozen
    # -------------------------------------------------------------------------

    print()
    print("=" * 80)
    print("TEST RESULTS WITH VALIDATION-OPTIMISED THRESHOLDS")
    print("=" * 80)

    test_output = trainer.predict(
        test_dataset,
        metric_key_prefix="test_default",
    )

    test_probabilities, test_true_independent = (
        extract_valid_token_arrays(
            test_output.predictions,
            test_output.label_ids,
        )
    )

    # IMPORTANT: build complete gold truth from the held-out source records, not
    # by expanding the training-derived neural target matrix.  The latter would
    # silently erase a test-only direct independent feature such as Human.
    test_true_full = build_full_truth_matrix_for_dataset(
        test_dataset,
        full_labels,
    )

    if test_true_full.shape[0] != test_probabilities.shape[0]:
        raise RuntimeError(
            "Test source-truth alignment failed: model predictions contain "
            f"{test_probabilities.shape[0]:,} supervised tokens but source "
            f"truth contains {test_true_full.shape[0]:,}."
        )

    test_optimised_metrics = (
        calculate_hierarchical_metrics_from_probabilities(
            probabilities=test_probabilities,
            y_true_independent=test_true_independent,
            threshold_vector=threshold_vector,
            hierarchy_matrix=hierarchy_matrix,
            y_true_full=test_true_full,
        )
    )

    # Preserve test loss/runtime information from Trainer, but do not use its
    # default-threshold F1 values as the final headline scores.
    test_auxiliary_metrics = {
        key: value
        for key, value in test_output.metrics.items()
        if (
            key.endswith("loss")
            or key.endswith("runtime")
            or "samples_per_second" in key
            or "steps_per_second" in key
        )
    }

    final_test_metrics: Dict[str, float] = {}
    final_test_metrics.update(test_optimised_metrics)
    final_test_metrics.update(test_auxiliary_metrics)

    print_metric_dictionary(final_test_metrics)

    # -------------------------------------------------------------------------
    # Detailed test metrics: complete hierarchy
    # -------------------------------------------------------------------------

    test_pred_independent = threshold_probabilities(
        test_probabilities,
        threshold_vector,
    )

    test_pred_full = expand_binary_feature_matrix(
        test_pred_independent,
        hierarchy_matrix,
    )

    per_feature_full = calculate_per_feature_metrics_from_binary(
        y_true=test_true_full,
        y_pred=test_pred_full,
        labels=full_labels,
    )

    per_feature_independent = (
        calculate_per_feature_metrics_from_binary(
            y_true=test_true_independent,
            y_pred=test_pred_independent,
            labels=prediction_labels,
        )
    )

    print_per_feature_table(
        title="TEST PERFORMANCE BY COMPLETE FEATURE (AFTER INHERITANCE)",
        labels=full_labels,
        results=per_feature_full,
    )

    print_per_feature_table(
        title="TEST PERFORMANCE BY INDEPENDENT NEURAL OUTPUT",
        labels=prediction_labels,
        results=per_feature_independent,
    )

    # -------------------------------------------------------------------------
    # Save final results
    # -------------------------------------------------------------------------

    result_document = {
        "model": MODEL_NAME,
        "target_representation": "per_token_independent_features",
        "data_sources": {
            "train_jsonl": str(TRAIN_JSONL_PATH),
            "test_jsonl": str(TEST_JSONL_PATH),
            "train_conllu": str(TRAIN_CONLLU_PATH),
            "test_conllu": str(TEST_CONLLU_PATH),
        },
        "validation_fraction": VALIDATION_FRACTION,
        "split_sizes": {
            "train": len(train_indices),
            "validation": len(validation_indices),
            "test": len(test_indices),
        },
        "prediction_labels": prediction_labels,
        "full_labels": full_labels,
        "thresholds_optimised_on": "validation",
        "thresholds": optimised_thresholds,
        "unseen_test_independent_labels": unseen_test_independent_labels,
        "validation_metrics_optimised": validation_optimised_metrics,
        "test_metrics": {
            key: float(value)
            if isinstance(
                value,
                (float, int, np.floating, np.integer),
            )
            else value
            for key, value in final_test_metrics.items()
        },
        "per_feature_complete": per_feature_full,
        "per_feature_independent": per_feature_independent,
    }

    with TEST_RESULTS_PATH.open("w", encoding="utf-8") as handle:
        json.dump(
            result_document,
            handle,
            ensure_ascii=False,
            indent=2,
        )

    print()
    print(
        "Best model saved to:\n"
        f"  {best_model_dir.resolve()}"
    )
    print(
        "Semantic feature metadata saved to:\n"
        f"  {LABELS_PATH.resolve()}"
    )
    print(
        "Validation-optimised thresholds saved to:\n"
        f"  {THRESHOLDS_PATH.resolve()}"
    )
    print(
        "Test results saved to:\n"
        f"  {TEST_RESULTS_PATH.resolve()}"
    )


if __name__ == "__main__":
    main()

================================================================================
CUDA
================================================================================
PyTorch version: 2.13.0+cu130
CUDA available: True
CUDA runtime: 13.0
GPU: NVIDIA GeForce RTX 5070 Ti
VRAM: 15.92 GiB

================================================================================
LOADING DATA
================================================================================
Training CoNLL-U sentences: 12,544
Test CoNLL-U sentences: 2,077
Training sentences represented in tagged JSONL: 11,511
Test sentences represented in tagged JSONL: 1,815
Training tagged NOUN/PROPN records: 47,371
Test tagged NOUN/PROPN records: 6,198

Eligible training-file sentences with at least one non-empty feature target: 11,198
Eligible test-file sentences with at least one non-empty feature target: 1,759

Label-aware train/validation split:
  Target validation sentences : 2,240
  Actual validation sentences : 2,240
  Training sentences retained : 8,958
  Candidates blocked to preserve rare labels: 0

================================================================================
HELD-OUT TEST LABEL COVERAGE WARNING
================================================================================
The test corpus contains direct independent targets that have no training-derived neural output head. They will NOT be added to the model vocabulary. Complete test truth will be read directly from the source annotations instead.
  Human                               support=1

================================================================================
DATASET SPLIT
================================================================================
train       : 8,958 sentences | 37,399 NOUN/PROPN tokens | 138,785 complete positives -> 54,643 independent positives | 2,632 empty-feature tokens excluded | source=training file
validation  : 2,240 sentences | 9,590 NOUN/PROPN tokens | 34,931 complete positives -> 13,701 independent positives | 729 empty-feature tokens excluded | source=training file
test        : 1,759 sentences | 6,127 NOUN/PROPN tokens | 22,690 complete positives -> 8,845 independent positives | 423 empty-feature tokens excluded | source=test file

================================================================================
NEURAL OUTPUT FEATURES
================================================================================
Complete evaluation features: 43
Independent neural outputs: 38
Deterministic-only features in this training split: 5

Feature                              Independent train support
----------------------------------------------------------------
Abstract                                                  5700
Animal                                                     706
Animate                                                     51
Artefact                                                  1897
Body_Part                                                  315
Comestible                                                 666
Communication                                             2065
Currency                                                   185
Duration                                                  1395
Elongated                                                  667
Eventive                                                  4212
Feminine                                                   871
Fluid                                                       88
Garment                                                     72
Inanimate                                                 5920
Internal_Control                                            94
Language                                                    19
Location                                                  4749
Machine                                                    746
Masculine                                                 2654
Natural                                                    314
Natural_Force                                              134
Non_Rigid                                                 1393
Organisation                                              4417
Plant                                                       63
Point_in_Time                                             1262
Pointy                                                      81
Question                                                   129
Rigid                                                     2232
Solid                                                     5747
Sound                                                      167
State                                                      298
Statement                                                 1018
Substance                                                  904
Time                                                        63
Unspecified_Gender_or_Neuter                              2758
Vehicle                                                    368
Web_Location                                               223

Deterministic-only in this split:
  - Concrete
  - Human
  - Rigidity
  - Shape
  - State_of_Matter

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:01<00:00, 211.48it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

================================================================================
TRAINING
================================================================================

================================================================================
FINAL VALIDATION RESULTS AT DEFAULT THRESHOLD
================================================================================

validation_default_direct_f1_macro: 0.8331195135484581
validation_default_direct_f1_micro: 0.8868794845511788
validation_default_direct_precision_macro: 0.8615530128614457
validation_default_direct_precision_micro: 0.889680499449137
validation_default_direct_recall_macro: 0.8218884850154972
validation_default_direct_recall_micro: 0.8840960513831108
validation_default_f1_macro: 0.8844869677843514
validation_default_f1_micro: 0.9354157387318783
validation_default_loss: 0.03056052140891552
validation_default_precision_macro: 0.8930759934416468
validation_default_precision_micro: 0.9389638860043844
validation_default_recall_macro: 0.8789098638809884
validation_default_recall_micro: 0.93189430591738
validation_default_runtime: 9.6086
validation_default_samples_per_second: 233.124
validation_default_steps_per_second: 14.57

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.26      1459     0.8839     0.8864    +0.0025
Animal                                    0.50       169     0.9558     0.9558    +0.0000
Animate                                   0.50         8     0.9333     0.9333    +0.0000
Artefact                                  0.39       472     0.8725     0.8733    +0.0008
Body_Part                                 0.09        77     0.9178     0.9317    +0.0139
Comestible                                0.41       162     0.9444     0.9512    +0.0068
Communication                             0.30       510     0.8016     0.8075    +0.0059
Currency                                  0.95        39     0.9268     0.9870    +0.0602
Duration                                  0.70       338     0.8490     0.8563    +0.0072
Elongated                                 0.69       133     0.7437     0.7843    +0.0406
Eventive                                  0.34      1114     0.8739     0.8800    +0.0061
Feminine                                  0.86       200     0.9040     0.9143    +0.0102
Fluid                                     0.52        15     0.9375     0.9677    +0.0302
Garment                                   0.40         5     0.6667     0.8000    +0.1333
Inanimate                                 0.40      1442     0.9273     0.9295    +0.0022
Internal_Control                          0.50        18     0.3636     0.3636    +0.0000
Language                                  0.46         9     0.9412     1.0000    +0.0588
Location                                  0.59      1193     0.9260     0.9278    +0.0018
Machine                                   0.53       172     0.9075     0.9129    +0.0055
Masculine                                 0.86       701     0.9405     0.9436    +0.0031
Natural                                   0.70        72     0.8784     0.9065    +0.0281
Natural_Force                             0.50        31     0.8571     0.8571    +0.0000
Non_Rigid                                 0.47       320     0.8338     0.8401    +0.0062
Organisation                              0.81      1094     0.8909     0.8953    +0.0044
Plant                                     0.50        20     0.9189     0.9189    +0.0000
Point_in_Time                             0.59       331     0.8876     0.8899    +0.0023
Pointy                                    0.50        17     0.7429     0.7429    +0.0000
Question                                  0.89        34     0.8889     0.9394    +0.0505
Rigid                                     0.64       536     0.8646     0.8719    +0.0073
Solid                                     0.35      1469     0.8944     0.8952    +0.0008
Sound                                     0.44        44     0.7792     0.7949    +0.0157
State                                     0.37        77     0.5147     0.5789    +0.0642
Statement                                 0.39       284     0.7555     0.7698    +0.0143
Substance                                 0.50       226     0.8898     0.8898    +0.0000
Time                                      0.11        20     0.0690     0.3922    +0.3232
Unspecified_Gender_or_Neuter              0.44       745     0.9129     0.9158    +0.0029
Vehicle                                   0.35        91     0.9503     0.9560    +0.0058
Web_Location                              0.21        54     0.9126     0.9174    +0.0048

================================================================================
FINAL VALIDATION RESULTS WITH OPTIMISED THRESHOLDS
================================================================================
direct_f1_macro: 0.8573215420626048
direct_f1_micro: 0.8912861255876672
direct_precision_macro: 0.8796607252140141
direct_precision_micro: 0.8900858931431067
direct_recall_macro: 0.8511857546941933
direct_recall_micro: 0.8924895992993213
f1_macro: 0.8979863822216428
f1_micro: 0.9360033447226908
precision_macro: 0.9062535385442582
precision_micro: 0.942785780669145
recall_macro: 0.8913811320090368
recall_micro: 0.9293177979445192

================================================================================
TEST RESULTS WITH VALIDATION-OPTIMISED THRESHOLDS
================================================================================

direct_f1_macro: 0.7414059148033084
direct_f1_micro: 0.8567555354722096
direct_precision_macro: 0.7619784949628814
direct_precision_micro: 0.8559819413092551
direct_recall_macro: 0.7398710114973831
direct_recall_micro: 0.8575305291723202
f1_macro: 0.8188039952823036
f1_micro: 0.9128899744643055
precision_macro: 0.8363900875973416
precision_micro: 0.9199373461624525
recall_macro: 0.8085199684837404
recall_micro: 0.9059497576024681
test_default_loss: 0.04044955223798752
test_default_runtime: 11.6262
test_default_samples_per_second: 151.297
test_default_steps_per_second: 9.461

================================================================================
TEST PERFORMANCE BY COMPLETE FEATURE (AFTER INHERITANCE)
================================================================================
Feature                              Precision     Recall         F1    Support
-------------------------------------------------------------------------------
Abstract                                0.9524     0.9330     0.9426       3091
Animal                                  0.8929     0.9804     0.9346         51
Animate                                 0.9601     0.9449     0.9525       1198
Artefact                                0.8805     0.8975     0.8889        517
Body_Part                               0.8529     0.8788     0.8657         33
Comestible                              0.8817     0.9613     0.9198        155
Communication                           0.8889     0.9114     0.9000        553
Concrete                                0.9405     0.9486     0.9445       2216
Currency                                1.0000     0.9167     0.9565         24
Duration                                0.8690     0.8235     0.8456        153
Elongated                               0.8689     0.5579     0.6795         95
Eventive                                0.8322     0.8837     0.8571        679
Feminine                                0.9542     0.8865     0.9191        141
Fluid                                   0.9500     0.9500     0.9500         20
Garment                                 1.0000     0.9091     0.9524         11
Human                                   0.9649     0.9458     0.9553       1106
Inanimate                               0.9002     0.9244     0.9121       1005
Internal_Control                        0.9549     0.9054     0.9295       2336
Language                                0.0000     0.0000     0.0000          2
Location                                0.9067     0.8999     0.9033        799
Machine                                 0.8905     0.8861     0.8883        202
Masculine                               0.9302     0.8867     0.9079        556
Natural                                 0.9565     0.9403     0.9484       1240
Natural_Force                           0.8235     0.6364     0.7179         22
Non_Rigid                               0.7254     0.8157     0.7679        217
Organisation                            0.8993     0.8134     0.8542        911
Plant                                   1.0000     0.8333     0.9091          6
Point_in_Time                           0.8857     0.8908     0.8883        174
Pointy                                  0.0000     0.0000     0.0000         11
Question                                1.0000     0.8889     0.9412         18
Rigid                                   0.8743     0.8117     0.8418        377
Rigidity                                0.8528     0.8485     0.8506        594
Shape                                   0.8689     0.5521     0.6752         96
Solid                                   0.9291     0.9218     0.9254       1393
Sound                                   0.6522     0.4839     0.5556         31
State                                   0.2353     0.4211     0.3019         19
State_of_Matter                         0.9308     0.9229     0.9268       1413
Statement                               0.7171     0.6813     0.6987        160
Substance                               0.8202     0.9182     0.8665        159
Time                                    0.9610     0.9496     0.9552        337
Unspecified_Gender_or_Neuter            0.8227     0.8529     0.8375        408
Vehicle                                 0.8537     0.9459     0.8974         37
Web_Location                            0.8850     0.8065     0.8439        124

================================================================================
TEST PERFORMANCE BY INDEPENDENT NEURAL OUTPUT
================================================================================
Feature                              Precision     Recall         F1    Support
-------------------------------------------------------------------------------
Abstract                                0.8422     0.8663     0.8541        733
Animal                                  0.8929     0.9804     0.9346         51
Animate                                 0.0000     0.0000     0.0000          2
Artefact                                0.8037     0.8487     0.8256        304
Body_Part                               0.8529     0.8788     0.8657         33
Comestible                              0.8817     0.9613     0.9198        155
Communication                           0.7588     0.8640     0.8080        375
Currency                                1.0000     0.9167     0.9565         24
Duration                                0.8690     0.8235     0.8456        153
Elongated                               0.8689     0.5579     0.6795         95
Eventive                                0.8322     0.8837     0.8571        679
Feminine                                0.9542     0.8865     0.9191        141
Fluid                                   0.9500     0.9500     0.9500         20
Garment                                 1.0000     0.9091     0.9524         11
Inanimate                               0.9002     0.9244     0.9121       1005
Internal_Control                        0.6667     0.1250     0.2105         16
Language                                0.0000     0.0000     0.0000          2
Location                                0.9067     0.8999     0.9033        799
Machine                                 0.8812     0.8545     0.8677        165
Masculine                               0.9302     0.8867     0.9079        556
Natural                                 0.7561     0.7381     0.7470         42
Natural_Force                           0.8235     0.6364     0.7179         22
Non_Rigid                               0.7254     0.8157     0.7679        217
Organisation                            0.8993     0.8134     0.8542        911
Plant                                   1.0000     0.8333     0.9091          6
Point_in_Time                           0.8857     0.8908     0.8883        174
Pointy                                  0.0000     0.0000     0.0000         11
Question                                1.0000     0.8889     0.9412         18
Rigid                                   0.8743     0.8117     0.8418        377
Solid                                   0.8450     0.8598     0.8524        799
Sound                                   0.6522     0.4839     0.5556         31
State                                   0.2353     0.4211     0.3019         19
Statement                               0.7171     0.6813     0.6987        160
Substance                               0.8202     0.9182     0.8665        159
Time                                    0.3684     0.7000     0.4828         10
Unspecified_Gender_or_Neuter            0.8227     0.8529     0.8375        408
Vehicle                                 0.8537     0.9459     0.8974         37
Web_Location                            0.8850     0.8065     0.8439        124

Best model saved to:
  /home/mark/verbnet-roberta/models/roberta_semantic_features/best_model
Semantic feature metadata saved to:
  /home/mark/verbnet-roberta/models/roberta_semantic_features/semantic_features.json
Validation-optimised thresholds saved to:
  /home/mark/verbnet-roberta/models/roberta_semantic_features/prediction_thresholds.json
Test results saved to:
  /home/mark/verbnet-roberta/models/roberta_semantic_features/test_results.json

<h1>Adding stratified splitting, repetitions, feature threshold calibration, bootstrapping, k-fold cross validation, and feature switches</h1>

In [1]:
#!/usr/bin/env python3
"""
Fine-tune RoBERTa for hierarchical multi-label semantic feature tagging of
NOUN/PROPN tokens.

Compatible with Python 3.9.21.

Key design changes
------------------
1. The model is trained only on independent semantic features. For each token,
   any feature that can be inherited from a more specific present feature is
   removed from the neural target. This is a per-token reduction rather than a
   global "terminal leaf only" rule, so features such as Human, Time, Shape,
   Communication, etc. can still be predicted directly when they are the most
   specific available feature for that token.

2. All inherited features are reconstructed deterministically from
   FEATURE_PARENTS for validation, testing, reporting, and later inference.

3. A separate sigmoid threshold is optimised for every neural output using the
   validation split only. The selected thresholds are frozen before the test
   split is evaluated and are saved to prediction_thresholds.json.

4. Train/validation splitting is performed at SENTENCE level with iterative
   multilabel stratification over sentence-level independent-feature presence.
   The split is fixed across repeated fine-tuning runs.

5. Fine-tuning is repeated over a predeclared list of random seeds. The same
   split is used for every run, and results are summarised with mean and SD.

6. The official test corpus may contain a direct independent target that never
   occurred independently in training. Such a label is never added from test
   data. Complete test truth is read directly from source annotations.

7. Held-out test uncertainty is estimated with a SENTENCE-CLUSTER bootstrap.
   All supervised noun/proper-noun targets from a sampled sentence move together.

Tagged data:
    Training/validation:
        ewt_train_wordnet_wsd_features_wordnet_fixed.jsonl
    Test:
        ewt_test_wordnet_wsd_features_wordnet_fixed.jsonl

Sentence/token sources:
    Training/validation:
        UD_English-EWT-master/
        UD_English-EWT-master/
        en_ewt-ud-train.conllu
    Test:
        UD_English-EWT-master/
        UD_English-EWT-master/
        en_ewt-ud-test.conllu

The validation split is created only from the training corpus. The official
test corpus remains untouched until final evaluation.

Loss:
    BCEWithLogitsLoss over INDEPENDENT feature labels only.

Headline metrics:
    Computed after deterministic hierarchy expansion, so they describe the
    complete semantic feature sets rather than only the neural outputs.

Requirements:
    python -m pip install torch transformers datasets accelerate conllu scikit-learn iterative-stratification

CUDA is required.
"""

from __future__ import annotations

import gc
import json
import shutil
from collections import Counter, defaultdict
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Set, Tuple

import numpy as np
import torch
import torch.nn as nn

from conllu import parse_incr
from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit
from sklearn.metrics import precision_recall_fscore_support
from torch.utils.data import Dataset

from transformers import (
    AutoModelForTokenClassification,
    AutoTokenizer,
    Trainer,
    TrainingArguments,
    set_seed,
)


# =============================================================================
# Configuration
# =============================================================================

TRAIN_JSONL_PATH = Path(
    "../data/ewt_train_wordnet_wsd_features_wordnet_fixed.jsonl"
    #"ewt_train_wordnet_wsd_features_fully_tagged_llm_reviewed.jsonl"
)

TEST_JSONL_PATH = Path(
    "../data/ewt_test_wordnet_wsd_features_wordnet_fixed.jsonl"
    #"ewt_test_wordnet_wsd_features_fully_tagged_llm_reviewed.jsonl"
)

TRAIN_CONLLU_PATH = Path(
    "../data/UD_English-EWT-master/"
    "UD_English-EWT-master/"
    "en_ewt-ud-train.conllu"
)

TEST_CONLLU_PATH = Path(
    "../data/UD_English-EWT-master/"
    "UD_English-EWT-master/"
    "en_ewt-ud-test.conllu"
)

# MODEL_NAME = "FacebookAI/roberta-base"
MODEL_NAME = "FacebookAI/roberta-large"

OUTPUT_DIR = Path("../models/roberta_semantic_features")

# Validation is sampled only from eligible TRAINING sentences.
# Stratification is performed at SENTENCE level using the multilabel feature
# presence vector for each sentence. The separate official test file is never
# split and is used only for final evaluation.
VALIDATION_FRACTION = 0.20

# Fixed seed used ONLY to create the sentence-level train/validation split.
# Keeping this fixed across model runs means repeated runs measure stochastic
# fine-tuning variation rather than variation in the validation partition.
SPLIT_SEED = 42

# Repeated fine-tuning seeds. Use the same list when comparing model variants.
# Thirty runs follow the experiment-design recommendation; reduce this list if
# RoBERTa-large makes 30 runs computationally impractical, and report the actual
# number used.
RUN_SEEDS = [
    11, 23, 37, 53, 71, 89, 107, 127, 149, 173,
    197, 223, 251, 281, 313, 347, 383, 421, 461, 503,
    547, 593, 641, 691, 743, 797, 853, 911, 971, 1031,
]

# The multilabel stratifier is retried with deterministic derived seeds until
# every independent feature still has at least this many positive token targets
# in the TRAIN subset. This prevents a rare direct target from disappearing.
MIN_TRAIN_POSITIVES_PER_FEATURE = 1
MAX_STRATIFICATION_ATTEMPTS = 200

# Sentence-cluster bootstrap for uncertainty in the held-out test sample.
# The same sampled test sentences are used for every run within each bootstrap
# replicate, and the statistic is the mean metric across run seeds.
TEST_BOOTSTRAP_SAMPLES = 2000
TEST_BOOTSTRAP_CONFIDENCE = 0.95
TEST_BOOTSTRAP_SEED = 20260926

# Saving 30 RoBERTa-large models would use a great deal of disk space. The first
# run is therefore saved as a neutral REFERENCE model; it is not selected for
# having the best test result. Metrics and thresholds are saved for every run.
SAVE_REFERENCE_MODEL = True

MAX_LENGTH = 256

LEARNING_RATE = 2e-5
WEIGHT_DECAY = 0.01

TRAIN_BATCH_SIZE = 8
EVAL_BATCH_SIZE = 16

GRADIENT_ACCUMULATION_STEPS = 2

NUM_EPOCHS = 5

# Threshold used during epoch-by-epoch Trainer evaluation. Final thresholds are
# optimised per independent feature on the validation set after training.
DEFAULT_PREDICTION_THRESHOLD = 0.5

# Validation-only threshold search grid.
THRESHOLD_MIN = 0.05
THRESHOLD_MAX = 0.95
THRESHOLD_STEP = 0.01

# Only these POS categories receive feature supervision.
TARGET_POS = {"NOUN", "PROPN"}

# A NOUN/PROPN with no features is considered a failed source annotation rather
# than a valid all-negative target.
EXCLUDE_EMPTY_FEATURE_RECORDS = True

# Optional per-feature switches. Any feature not listed here is enabled.
# Set a feature to False to remove it from:
#   - sentence-level stratification,
#   - neural training targets,
#   - threshold calibration,
#   - hierarchy-expanded gold/predicted feature sets,
#   - per-feature and aggregate evaluation, and
#   - the sentence-cluster bootstrap.
#
# Disabled intermediate hierarchy nodes are skipped but their enabled ancestors
# are still inherited. For example, if Human were disabled, Feminine would still
# inherit Animate/Natural/Concrete/Internal_Control via the hierarchy.
FEATURE_SWITCHES: Dict[str, bool] = {
    "State": False,
    "State_of_Matter": False,
    "Shape": False,
    "Rigidity": False,
}

# Aggregate per-feature test tables are always printed after all repeated runs.
# Set this to True only if you also want the two full per-feature tables printed
# after EVERY run (very verbose for 30 runs).
PRINT_PER_RUN_FEATURE_TABLES = False

EVAL_STRATEGY = "epoch"

SPLIT_PATH = OUTPUT_DIR / "sentence_split.json"
LABELS_PATH = OUTPUT_DIR / "semantic_features.json"
RUNS_DIR = OUTPUT_DIR / "runs"
REFERENCE_MODEL_DIR = OUTPUT_DIR / "reference_model"
REPEATED_RESULTS_PATH = OUTPUT_DIR / "repeated_run_results.json"
BOOTSTRAP_RESULTS_PATH = OUTPUT_DIR / "test_bootstrap_confidence_intervals.json"


# =============================================================================
# Feature hierarchy
# =============================================================================

def is_feature_enabled(feature: str) -> bool:
    """Return whether *feature* participates in this experiment."""

    return bool(FEATURE_SWITCHES.get(feature, True))


def validate_feature_switches(
    train_tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    test_tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> None:
    """Fail early on misspelled feature-switch names and report disabled labels."""

    observed: Set[str] = set()

    for source in (train_tagged_records, test_tagged_records):
        for sentence_records in source.values():
            for record in sentence_records.values():
                raw = record.get("features", [])
                if isinstance(raw, list):
                    observed.update(
                        str(feature).strip()
                        for feature in raw
                        if str(feature).strip()
                    )

    known = set(observed) | set(FEATURE_PARENTS)
    for parents in FEATURE_PARENTS.values():
        known.update(parents)

    unknown = sorted(set(FEATURE_SWITCHES) - known)
    if unknown:
        raise ValueError(
            "FEATURE_SWITCHES contains unknown feature name(s): "
            + ", ".join(unknown)
        )

    disabled = sorted(
        feature for feature, enabled in FEATURE_SWITCHES.items() if not enabled
    )

    print("=" * 80)
    print("FEATURE SWITCHES")
    print("=" * 80)
    if disabled:
        print("Disabled features: " + ", ".join(disabled))
    else:
        print("Disabled features: none")
    print("All unlisted features are enabled.")
    print()


# child -> direct parent(s)
FEATURE_PARENTS: Dict[str, Set[str]] = {
    "Organisation": {
        "Internal_Control",
        "Abstract",
    },
    "Natural_Force": {
        "Internal_Control",
    },
    "Animate": {
        "Internal_Control",
        "Natural",
    },
    "Human": {
        "Animate",
    },
    "Feminine": {
        "Human",
    },
    "Masculine": {
        "Human",
    },
    "Unspecified_Gender_or_Neuter": {
        "Human",
    },
    "Animal": {
        "Animate",
    },
    "Plant": {
        "Animate",
    },
    "Body_Part": {
        "Animate",
    },
    "Machine": {
        "Internal_Control",
        "Artefact",
    },
    "Vehicle": {
        "Machine",
    },
    "Natural": {
        "Concrete",
    },
    "Artefact": {
        "Concrete",
    },
    "Comestible": {
        "Concrete",
    },
    "Substance": {
        "Concrete",
    },
    "State_of_Matter": {
        "Concrete",
    },
    "Inanimate": {
        "Concrete",
    },
    "Garment": {
        "Artefact",
    },
    "Solid": {
        "State_of_Matter",
    },
    "Fluid": {
        "State_of_Matter",
    },
    "Rigidity": {
        "Solid",
    },
    "Shape": {
        "Solid",
    },
    "Rigid": {
        "Rigidity",
    },
    "Non_Rigid": {
        "Rigidity",
    },
    "Elongated": {
        "Shape",
    },
    "Pointy": {
        "Shape",
    },
    "Point_in_Time": {
        "Time",
    },
    "Duration": {
        "Time",
    },
    "Time": {
        "Abstract",
    },
    "Language": {
        "Abstract",
    },
    "Sound": {
        "Abstract",
    },
    "Communication": {
        "Abstract",
    },
    "Eventive": {
        "Abstract",
    },
    "Statement": {
        "Communication",
    },
    "Question": {
        "Communication",
    },
}


def validate_feature_hierarchy() -> None:
    """Fail early if FEATURE_PARENTS contains a cycle or invalid name."""

    all_features: Set[str] = set(FEATURE_PARENTS)

    for parents in FEATURE_PARENTS.values():
        all_features.update(parents)

    for feature in all_features:
        if not isinstance(feature, str) or not feature.strip():
            raise ValueError(
                "FEATURE_PARENTS contains an empty or non-string feature name."
            )

    visiting: Set[str] = set()
    visited: Set[str] = set()

    def visit(feature: str) -> None:
        if feature in visited:
            return

        if feature in visiting:
            raise ValueError(
                f"Cycle detected in FEATURE_PARENTS involving {feature!r}."
            )

        visiting.add(feature)

        for parent in FEATURE_PARENTS.get(feature, set()):
            visit(parent)

        visiting.remove(feature)
        visited.add(feature)

    for feature in sorted(all_features):
        visit(feature)


@lru_cache(maxsize=None)
def get_feature_ancestors(feature: str) -> frozenset:
    """Return every direct and indirect parent of *feature*."""

    ancestors: Set[str] = set()

    for parent in FEATURE_PARENTS.get(feature, set()):
        if is_feature_enabled(parent):
            ancestors.add(parent)
        # Traverse even through a disabled intermediate node so enabled
        # grandparents remain inherited.
        ancestors.update(get_feature_ancestors(parent))

    return frozenset(ancestors)


def expand_feature_hierarchy(features: Iterable[str]) -> Set[str]:
    """Add every deterministic ancestor required by FEATURE_PARENTS."""

    expanded: Set[str] = {
        feature for feature in features if is_feature_enabled(feature)
    }

    for feature in list(expanded):
        expanded.update(get_feature_ancestors(feature))

    return expanded


def reduce_to_independent_features(features: Iterable[str]) -> Set[str]:
    """
    Reduce a complete feature set to the features that must be predicted.

    A feature is redundant when it is an ancestor of another feature present
    for the same token. Such an ancestor can be reconstructed deterministically.

    Examples:
        {Human, Animate, Natural, Concrete, Internal_Control}
            -> {Human}

        {Feminine, Human, Animate, Natural, Concrete, Internal_Control}
            -> {Feminine}

        {Statement, Communication, Abstract, Time}
            -> {Statement, Time}

    This is deliberately PER TOKEN. It is not the same as training only labels
    that are global terminal leaves in the ontology. A generic Human can still
    be a direct neural target if no more specific Human child is present.
    """

    feature_set = set(features)

    inherited_from_other_features: Set[str] = set()

    for feature in feature_set:
        inherited_from_other_features.update(
            get_feature_ancestors(feature)
        )

    return feature_set - inherited_from_other_features


def missing_hierarchy_features(features: Iterable[str]) -> Set[str]:
    """Return ancestors required by the hierarchy but absent from *features*."""

    feature_set = set(features)
    return expand_feature_hierarchy(feature_set) - feature_set


# =============================================================================
# CUDA
# =============================================================================

def check_cuda() -> None:
    """Require CUDA rather than silently falling back to the CPU."""

    if not torch.cuda.is_available():
        raise RuntimeError(
            "CUDA is not available. This script is configured to require "
            "a CUDA-capable GPU."
        )

    print("=" * 80)
    print("CUDA")
    print("=" * 80)
    print(f"PyTorch version: {torch.__version__}")
    print(f"CUDA available: {torch.cuda.is_available()}")
    print(f"CUDA runtime: {torch.version.cuda}")
    print(f"GPU: {torch.cuda.get_device_name(0)}")

    props = torch.cuda.get_device_properties(0)

    print(
        "VRAM: "
        f"{props.total_memory / (1024 ** 3):.2f} GiB"
    )
    print()


# =============================================================================
# Load CoNLL-U
# =============================================================================

def load_conllu(path: Path) -> List[Any]:
    """Load all CoNLL-U sentences."""

    if not path.exists():
        raise FileNotFoundError(
            f"Could not find CoNLL-U file:\n{path.resolve()}"
        )

    sentences: List[Any] = []

    with path.open("r", encoding="utf-8") as handle:
        for sentence in parse_incr(handle):
            sentences.append(sentence)

    return sentences


def get_sentence_words(sentence: Any) -> Tuple[List[str], List[int]]:
    """
    Return ordinary integer-ID tokens and their original CoNLL-U token IDs.

    Multiword-token placeholder rows and empty nodes are excluded.
    """

    words: List[str] = []
    token_ids: List[int] = []

    for token in sentence:
        token_id = token.get("id")

        if not isinstance(token_id, int):
            continue

        form = token.get("form")

        if form is None:
            continue

        words.append(str(form))
        token_ids.append(token_id)

    return words, token_ids


# =============================================================================
# Load tagged JSONL
# =============================================================================

def load_tagged_records(
    path: Path,
) -> Dict[int, Dict[int, Dict[str, Any]]]:
    """
    Return:

        sentence_index
            -> token_id
                -> JSONL record

    Only NOUN and PROPN records are retained.
    """

    if not path.exists():
        raise FileNotFoundError(
            f"Could not find tagged JSONL:\n{path.resolve()}"
        )

    records: Dict[int, Dict[int, Dict[str, Any]]] = defaultdict(dict)

    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            line = line.strip()

            if not line:
                continue

            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                print(
                    "Warning: invalid JSON on line "
                    f"{line_number}: {exc}"
                )
                continue

            if record.get("upos") not in TARGET_POS:
                continue

            sentence_index = record.get("sentence_index")
            token_id = record.get("token_id")

            if not isinstance(sentence_index, int):
                continue

            if not isinstance(token_id, int):
                continue

            records[sentence_index][token_id] = record

    return dict(records)


# =============================================================================
# Labels
# =============================================================================

def clean_features(record: Dict[str, Any]) -> List[str]:
    """Return unique, non-empty COMPLETE feature names from a JSONL record."""

    raw = record.get("features", [])

    if not isinstance(raw, list):
        return []

    return sorted(
        {
            str(feature).strip()
            for feature in raw
            if (
                str(feature).strip()
                and is_feature_enabled(str(feature).strip())
            )
        }
    )


def get_independent_record_features(record: Dict[str, Any]) -> List[str]:
    """Return the per-token minimal feature set that the model must predict."""

    return sorted(
        reduce_to_independent_features(
            clean_features(record)
        )
    )


def build_full_label_vocabulary(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    training_sentence_indices: Sequence[int],
) -> List[str]:
    """
    Build the COMPLETE evaluation vocabulary from training data only.

    Deterministic ancestors are included even if a training record omitted one,
    although hierarchy closure is separately verified and should normally make
    this addition unnecessary.
    """

    labels: Set[str] = set()

    for sentence_index in training_sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            features = clean_features(record)
            labels.update(features)
            labels.update(expand_feature_hierarchy(features))

    if not labels:
        raise RuntimeError(
            "No semantic features were found in the training split."
        )

    return sorted(labels)


def build_prediction_label_vocabulary(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    training_sentence_indices: Sequence[int],
) -> List[str]:
    """Build the neural-output vocabulary from independent training targets."""

    labels: Set[str] = set()

    for sentence_index in training_sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            labels.update(
                get_independent_record_features(record)
            )

    if not labels:
        raise RuntimeError(
            "No independent semantic features were found in the training split."
        )

    return sorted(labels)


# =============================================================================
# Sentence selection and splitting
# =============================================================================

def get_eligible_sentence_indices(
    sentences: Sequence[Any],
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> List[int]:
    """Eligible sentences contain at least one non-empty NOUN/PROPN target."""

    eligible: List[int] = []

    for sentence_index in range(len(sentences)):
        token_records = tagged_records.get(sentence_index, {})

        valid_records = [
            record
            for record in token_records.values()
            if clean_features(record)
        ]

        if valid_records:
            eligible.append(sentence_index)

    return eligible


def get_sentence_independent_feature_counts(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    sentence_index: int,
) -> Counter:
    """Count independent positive token targets in one source sentence."""

    counts: Counter = Counter()

    for record in tagged_records.get(sentence_index, {}).values():
        if not clean_features(record):
            continue

        for feature in get_independent_record_features(record):
            counts[feature] += 1

    return counts


def build_sentence_multilabel_matrix(
    eligible_indices: Sequence[int],
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> Tuple[np.ndarray, List[str], Dict[int, Counter]]:
    """
    Build one multilabel stratification row per SENTENCE.

    y_sentence[sentence, feature] is 1 when at least one eligible NOUN/PROPN
    token in that sentence has the independent feature. Token counts are kept
    separately for the post-split training-coverage constraint.
    """

    sentence_feature_counts: Dict[int, Counter] = {
        sentence_index: get_sentence_independent_feature_counts(
            tagged_records,
            sentence_index,
        )
        for sentence_index in eligible_indices
    }

    stratification_labels = sorted(
        {
            feature
            for counts in sentence_feature_counts.values()
            for feature, count in counts.items()
            if count > 0
        }
    )

    if not stratification_labels:
        raise RuntimeError(
            "No independent semantic features were found in eligible "
            "training sentences."
        )

    label2column = {
        label: column
        for column, label in enumerate(stratification_labels)
    }

    matrix = np.zeros(
        (len(eligible_indices), len(stratification_labels)),
        dtype=np.int8,
    )

    for row, sentence_index in enumerate(eligible_indices):
        for feature in sentence_feature_counts[sentence_index]:
            matrix[row, label2column[feature]] = 1

    return matrix, stratification_labels, sentence_feature_counts


def _sentence_prevalence_error(
    y_all: np.ndarray,
    validation_rows: np.ndarray,
    validation_fraction: float,
) -> float:
    """
    Score how closely validation sentence-level label prevalences match target.

    Lower is better. The score is used only to choose among deterministic
    iterative-stratification attempts that satisfy the training-coverage rule.
    """

    total_support = y_all.sum(axis=0).astype(np.float64)
    validation_support = y_all[validation_rows].sum(axis=0).astype(np.float64)

    target_support = total_support * float(validation_fraction)

    # Scale by at least one expected example so rare and common labels both
    # contribute without allowing extremely common labels to dominate.
    scale = np.maximum(target_support, 1.0)

    return float(
        np.mean(
            np.abs(validation_support - target_support) / scale
        )
    )


def make_train_validation_split(
    eligible_indices: Sequence[int],
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> Dict[str, Any]:
    """
    Create a SENTENCE-LEVEL multilabel-stratified split from TRAINING only.

    Each sentence receives a binary vector indicating which independent feature
    labels occur anywhere among its eligible NOUN/PROPN tokens. Iterative
    multilabel stratification then assigns whole sentences to train/validation.

    The split is retried deterministically when necessary so that every
    independent feature retains at least MIN_TRAIN_POSITIVES_PER_FEATURE
    positive TOKEN targets in the training subset.

    The official test corpus is deliberately not accepted by this function, so
    test labels cannot influence the split.
    """

    if not 0.0 < VALIDATION_FRACTION < 1.0:
        raise ValueError(
            "VALIDATION_FRACTION must be strictly between 0 and 1."
        )

    if MIN_TRAIN_POSITIVES_PER_FEATURE < 1:
        raise ValueError(
            "MIN_TRAIN_POSITIVES_PER_FEATURE must be at least 1."
        )

    if MAX_STRATIFICATION_ATTEMPTS < 1:
        raise ValueError(
            "MAX_STRATIFICATION_ATTEMPTS must be at least 1."
        )

    eligible_indices = list(eligible_indices)

    if len(eligible_indices) < 2:
        raise RuntimeError(
            "Need at least two eligible training sentences to create a "
            "train/validation split."
        )

    (
        sentence_matrix,
        stratification_labels,
        sentence_feature_counts,
    ) = build_sentence_multilabel_matrix(
        eligible_indices,
        tagged_records,
    )

    all_token_counts: Counter = Counter()

    for counts in sentence_feature_counts.values():
        all_token_counts.update(counts)

    x_dummy = np.zeros((len(eligible_indices), 1), dtype=np.int8)

    best_candidate: Optional[Dict[str, Any]] = None
    rejected_for_coverage = 0

    for attempt in range(MAX_STRATIFICATION_ATTEMPTS):
        attempt_seed = SPLIT_SEED + attempt

        splitter = MultilabelStratifiedShuffleSplit(
            n_splits=1,
            test_size=VALIDATION_FRACTION,
            random_state=attempt_seed,
        )

        train_rows, validation_rows = next(
            splitter.split(x_dummy, sentence_matrix)
        )

        train_indices = [
            eligible_indices[int(row)]
            for row in train_rows
        ]
        validation_indices = [
            eligible_indices[int(row)]
            for row in validation_rows
        ]

        train_token_counts: Counter = Counter()

        for sentence_index in train_indices:
            train_token_counts.update(
                sentence_feature_counts[sentence_index]
            )

        missing_or_undercovered = sorted(
            feature
            for feature, total_count in all_token_counts.items()
            if (
                total_count > 0
                and train_token_counts[feature]
                < MIN_TRAIN_POSITIVES_PER_FEATURE
            )
        )

        if missing_or_undercovered:
            rejected_for_coverage += 1
            continue

        prevalence_error = _sentence_prevalence_error(
            sentence_matrix,
            validation_rows,
            VALIDATION_FRACTION,
        )

        candidate = {
            "train": train_indices,
            "validation": validation_indices,
            "split_seed_used": attempt_seed,
            "attempt": attempt + 1,
            "prevalence_error": prevalence_error,
            "stratification_labels": stratification_labels,
        }

        if (
            best_candidate is None
            or prevalence_error < best_candidate["prevalence_error"]
        ):
            best_candidate = candidate

        # Iterative stratification is already designed to balance multilabel
        # prevalence. Once a valid candidate is found, further attempts are not
        # needed unless coverage forced earlier candidates to be rejected.
        if rejected_for_coverage == 0:
            break

    if best_candidate is None:
        raise RuntimeError(
            "Could not create a sentence-level multilabel-stratified "
            "train/validation split that preserved the required training "
            f"support after {MAX_STRATIFICATION_ATTEMPTS} attempts."
        )

    train_indices = best_candidate["train"]
    validation_indices = best_candidate["validation"]

    train_set = set(train_indices)
    validation_set = set(validation_indices)

    if train_set & validation_set:
        raise RuntimeError(
            "Internal split error: at least one sentence occurs in both "
            "training and validation."
        )

    if train_set | validation_set != set(eligible_indices):
        raise RuntimeError(
            "Internal split error: sentence-level split does not exactly cover "
            "the eligible training sentences."
        )

    print()
    print("Sentence-level multilabel-stratified train/validation split:")
    print(
        f"  Eligible training sentences : {len(eligible_indices):,}"
    )
    print(
        f"  Target validation sentences : "
        f"{round(len(eligible_indices) * VALIDATION_FRACTION):,}"
    )
    print(
        f"  Actual validation sentences : {len(validation_indices):,}"
    )
    print(
        f"  Training sentences retained : {len(train_indices):,}"
    )
    print(
        f"  Split seed used             : "
        f"{best_candidate['split_seed_used']}"
    )
    print(
        f"  Stratification labels       : "
        f"{len(stratification_labels):,}"
    )
    print(
        f"  Coverage-rejected attempts  : {rejected_for_coverage:,}"
    )
    print(
        f"  Mean relative prevalence error: "
        f"{best_candidate['prevalence_error']:.6f}"
    )

    # Show sentence-level prevalence agreement, which is the quantity actually
    # controlled by the stratifier.
    validation_fraction_actual = (
        len(validation_indices) / len(eligible_indices)
    )

    label2column = {
        label: column
        for column, label in enumerate(stratification_labels)
    }

    row_by_sentence = {
        sentence_index: row
        for row, sentence_index in enumerate(eligible_indices)
    }

    train_rows_lookup = [
        row_by_sentence[index]
        for index in train_indices
    ]
    validation_rows_lookup = [
        row_by_sentence[index]
        for index in validation_indices
    ]

    print()
    print(
        f"{'Feature':35s} "
        f"{'All sent.':>10s} "
        f"{'Train':>10s} "
        f"{'Valid':>10s} "
        f"{'Valid %':>10s}"
    )
    print("-" * 80)

    for feature in stratification_labels:
        column = label2column[feature]
        all_support = int(sentence_matrix[:, column].sum())
        train_support = int(
            sentence_matrix[train_rows_lookup, column].sum()
        )
        validation_support = int(
            sentence_matrix[validation_rows_lookup, column].sum()
        )

        print(
            f"{feature:35s} "
            f"{all_support:10d} "
            f"{train_support:10d} "
            f"{validation_support:10d} "
            f"{validation_support / max(all_support, 1):10.3f}"
        )

    print(
        f"\nActual validation sentence fraction: "
        f"{validation_fraction_actual:.4f}"
    )
    print()

    return best_candidate


# =============================================================================
# Dataset
# =============================================================================

class SemanticFeatureDataset(Dataset):
    """
    RoBERTa multi-label token-classification dataset.

    IMPORTANT:
        labels contain only INDEPENDENT neural targets.

    Labels have shape:
        [sequence_length, number_of_prediction_features]

    For supervised tokens:
        0 = independent feature absent
        1 = independent feature present

    For ignored tokens:
        -100 across all labels

    Only the first RoBERTa subword corresponding to each source token receives
    supervision.
    """

    def __init__(
        self,
        sentences: Sequence[Any],
        sentence_indices: Sequence[int],
        tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
        tokenizer: Any,
        label2id: Dict[str, int],
        max_length: int,
    ) -> None:
        self.sentences = sentences
        self.sentence_indices = list(sentence_indices)
        self.tagged_records = tagged_records
        self.tokenizer = tokenizer
        self.label2id = label2id
        self.num_labels = len(label2id)
        self.max_length = max_length

    def __len__(self) -> int:
        return len(self.sentence_indices)

    def __getitem__(
        self,
        dataset_index: int,
    ) -> Dict[str, Any]:
        sentence_index = self.sentence_indices[dataset_index]
        sentence = self.sentences[sentence_index]

        words, token_ids = get_sentence_words(sentence)

        encoding = self.tokenizer(
            words,
            is_split_into_words=True,
            truncation=True,
            max_length=self.max_length,
            add_special_tokens=True,
        )

        word_ids = encoding.word_ids()
        labels: List[List[float]] = []
        previous_word_id: Optional[int] = None
        sentence_records = self.tagged_records.get(sentence_index, {})

        for word_id in word_ids:
            if word_id is None:
                labels.append([-100.0] * self.num_labels)
                previous_word_id = word_id
                continue

            # Ignore all but the first subword.
            if word_id == previous_word_id:
                labels.append([-100.0] * self.num_labels)
                continue

            previous_word_id = word_id

            if not 0 <= word_id < len(token_ids):
                labels.append([-100.0] * self.num_labels)
                continue

            conllu_token_id = token_ids[word_id]
            record = sentence_records.get(conllu_token_id)

            if record is None:
                labels.append([-100.0] * self.num_labels)
                continue

            full_features = clean_features(record)

            if not full_features and EXCLUDE_EMPTY_FEATURE_RECORDS:
                labels.append([-100.0] * self.num_labels)
                continue

            independent_features = reduce_to_independent_features(
                full_features
            )

            target = [0.0] * self.num_labels

            for feature in independent_features:
                label_id = self.label2id.get(feature)

                if label_id is not None:
                    target[label_id] = 1.0

            labels.append(target)

        encoding["labels"] = labels
        encoding["sentence_index"] = sentence_index

        return encoding


# =============================================================================
# Data collator
# =============================================================================

class MultiLabelTokenCollator:
    """Dynamically pad inputs and 3-D multi-label token targets."""

    def __init__(
        self,
        tokenizer: Any,
        num_labels: int,
    ) -> None:
        self.tokenizer = tokenizer
        self.num_labels = num_labels

    def __call__(
        self,
        features: List[Dict[str, Any]],
    ) -> Dict[str, torch.Tensor]:
        clean_features_list: List[Dict[str, Any]] = []
        labels_list: List[List[List[float]]] = []

        for item in features:
            item = dict(item)
            item.pop("sentence_index", None)

            labels = item.pop("labels")
            labels_list.append(labels)
            clean_features_list.append(item)

        batch = self.tokenizer.pad(
            clean_features_list,
            padding=True,
            return_tensors="pt",
        )

        batch_size = len(labels_list)
        max_seq_length = batch["input_ids"].shape[1]

        padded_labels = torch.full(
            (
                batch_size,
                max_seq_length,
                self.num_labels,
            ),
            -100.0,
            dtype=torch.float32,
        )

        for batch_index, labels in enumerate(labels_list):
            label_tensor = torch.tensor(
                labels,
                dtype=torch.float32,
            )

            sequence_length = label_tensor.shape[0]

            padded_labels[
                batch_index,
                :sequence_length,
                :,
            ] = label_tensor

        batch["labels"] = padded_labels

        return batch


# =============================================================================
# Model
# =============================================================================

class RobertaMultiLabelModel(nn.Module):
    """RoBERTa token classifier with BCE loss for independent feature labels."""

    def __init__(
        self,
        model_name: str,
        num_labels: int,
        id2label: Dict[int, str],
        label2id: Dict[str, int],
    ) -> None:
        super().__init__()

        self.model = AutoModelForTokenClassification.from_pretrained(
            model_name,
            num_labels=num_labels,
            id2label=id2label,
            label2id=label2id,
        )

        self.config = self.model.config

        self.loss_function = nn.BCEWithLogitsLoss(
            reduction="mean"
        )

    def forward(
        self,
        input_ids=None,
        attention_mask=None,
        labels=None,
        **kwargs,
    ):
        outputs = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            **kwargs,
        )

        logits = outputs.logits
        loss = None

        if labels is not None:
            valid_mask = labels[:, :, 0] != -100.0

            valid_logits = logits[valid_mask]
            valid_labels = labels[valid_mask]

            if valid_logits.numel() == 0:
                loss = logits.sum() * 0.0
            else:
                loss = self.loss_function(
                    valid_logits,
                    valid_labels,
                )

        return {
            "loss": loss,
            "logits": logits,
        }

    def save_pretrained(
        self,
        save_directory,
        **kwargs,
    ):
        return self.model.save_pretrained(
            save_directory,
            **kwargs,
        )


# =============================================================================
# Hierarchy matrices and array helpers
# =============================================================================

def build_hierarchy_expansion_matrix(
    prediction_labels: Sequence[str],
    full_labels: Sequence[str],
) -> np.ndarray:
    """
    Build a boolean matrix mapping neural outputs to complete feature sets.

    Shape:
        [number_of_prediction_features, number_of_full_features]
    """

    full_label2id = {
        label: index
        for index, label in enumerate(full_labels)
    }

    matrix = np.zeros(
        (len(prediction_labels), len(full_labels)),
        dtype=np.int8,
    )

    for prediction_id, feature in enumerate(prediction_labels):
        expanded = expand_feature_hierarchy({feature})

        for expanded_feature in expanded:
            full_id = full_label2id.get(expanded_feature)

            if full_id is None:
                raise RuntimeError(
                    "Hierarchy expansion produced a feature absent from the "
                    f"full vocabulary: {expanded_feature!r}."
                )

            matrix[prediction_id, full_id] = 1

    return matrix


def expand_binary_feature_matrix(
    independent_matrix: np.ndarray,
    hierarchy_matrix: np.ndarray,
) -> np.ndarray:
    """Expand [tokens, independent] binary values to [tokens, complete]."""

    expanded = independent_matrix.astype(np.int32) @ hierarchy_matrix.astype(
        np.int32
    )

    return (expanded > 0).astype(np.int32)


def extract_valid_token_arrays(
    logits: np.ndarray,
    labels: np.ndarray,
) -> Tuple[np.ndarray, np.ndarray]:
    """Return probabilities and true independent labels for supervised tokens."""

    valid_token_mask = labels[:, :, 0] != -100.0

    probabilities = sigmoid_numpy(logits)[
        valid_token_mask
    ]

    true_labels = labels[
        valid_token_mask
    ].astype(np.int32)

    return probabilities, true_labels


def build_full_truth_matrix_for_dataset(
    dataset: "SemanticFeatureDataset",
    full_labels: Sequence[str],
) -> np.ndarray:
    """Build complete source truth for every supervised token in dataset order.

    This is intentionally independent of the neural-output vocabulary.  It is
    therefore safe and necessary for a held-out test corpus that may contain a
    feature such as ``Human`` as a direct independent target even when that
    feature never occurred independently in the training corpus.

    The model is still trained only on training-derived independent output
    heads.  This function merely preserves the complete gold annotations for
    fair hierarchy-expanded evaluation.
    """

    full_label2id = {
        label: index
        for index, label in enumerate(full_labels)
    }

    rows: List[np.ndarray] = []

    for sentence_index in dataset.sentence_indices:
        sentence = dataset.sentences[sentence_index]
        words, token_ids = get_sentence_words(sentence)

        encoding = dataset.tokenizer(
            words,
            is_split_into_words=True,
            truncation=True,
            max_length=dataset.max_length,
            add_special_tokens=True,
        )

        word_ids = encoding.word_ids()
        previous_word_id: Optional[int] = None
        sentence_records = dataset.tagged_records.get(sentence_index, {})

        for word_id in word_ids:
            if word_id is None:
                previous_word_id = word_id
                continue

            # Match SemanticFeatureDataset.__getitem__: only the first subword
            # for each source token receives supervision.
            if word_id == previous_word_id:
                continue

            previous_word_id = word_id

            if not 0 <= word_id < len(token_ids):
                continue

            conllu_token_id = token_ids[word_id]
            record = sentence_records.get(conllu_token_id)

            if record is None:
                continue

            features = clean_features(record)

            if not features and EXCLUDE_EMPTY_FEATURE_RECORDS:
                continue

            expanded_features = expand_feature_hierarchy(features)
            row = np.zeros(len(full_labels), dtype=np.int32)

            for feature in expanded_features:
                label_id = full_label2id.get(feature)

                if label_id is None:
                    raise RuntimeError(
                        "Complete source truth contains a feature absent from "
                        f"the training-derived full vocabulary: {feature!r}."
                    )

                row[label_id] = 1

            rows.append(row)

    if not rows:
        return np.zeros((0, len(full_labels)), dtype=np.int32)

    return np.stack(rows, axis=0)


# =============================================================================
# Metrics and thresholds
# =============================================================================

def sigmoid_numpy(x: np.ndarray) -> np.ndarray:
    """Numerically stable sigmoid."""

    x = np.clip(x, -50.0, 50.0)
    return 1.0 / (1.0 + np.exp(-x))


def make_threshold_vector(
    prediction_labels: Sequence[str],
    thresholds: Dict[str, float],
) -> np.ndarray:
    """Return thresholds in neural-output column order."""

    return np.asarray(
        [
            float(
                thresholds.get(
                    label,
                    DEFAULT_PREDICTION_THRESHOLD,
                )
            )
            for label in prediction_labels
        ],
        dtype=np.float32,
    )


def threshold_probabilities(
    probabilities: np.ndarray,
    threshold_vector: np.ndarray,
) -> np.ndarray:
    """Apply one threshold per independent feature."""

    return (
        probabilities >= threshold_vector.reshape(1, -1)
    ).astype(np.int32)


def calculate_average_metrics(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    prefix: str = "",
) -> Dict[str, float]:
    """Calculate micro and macro precision/recall/F1."""

    if y_true.shape[0] == 0:
        return {
            f"{prefix}precision_micro": 0.0,
            f"{prefix}recall_micro": 0.0,
            f"{prefix}f1_micro": 0.0,
            f"{prefix}precision_macro": 0.0,
            f"{prefix}recall_macro": 0.0,
            f"{prefix}f1_macro": 0.0,
        }

    (
        precision_micro,
        recall_micro,
        f1_micro,
        _,
    ) = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="micro",
        zero_division=0,
    )

    (
        precision_macro,
        recall_macro,
        f1_macro,
        _,
    ) = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="macro",
        zero_division=0,
    )

    return {
        f"{prefix}precision_micro": float(precision_micro),
        f"{prefix}recall_micro": float(recall_micro),
        f"{prefix}f1_micro": float(f1_micro),
        f"{prefix}precision_macro": float(precision_macro),
        f"{prefix}recall_macro": float(recall_macro),
        f"{prefix}f1_macro": float(f1_macro),
    }


def calculate_hierarchical_metrics_from_probabilities(
    probabilities: np.ndarray,
    y_true_independent: np.ndarray,
    threshold_vector: np.ndarray,
    hierarchy_matrix: np.ndarray,
    y_true_full: Optional[np.ndarray] = None,
) -> Dict[str, float]:
    """
    Report both direct neural-output metrics and complete hierarchy metrics.

    Unprefixed metrics are the COMPLETE hierarchy metrics.  During ordinary
    training/validation, complete truth can be reconstructed from the
    independent targets.  For a genuinely held-out test corpus, ``y_true_full``
    may instead be supplied directly from the source annotations so an unseen
    direct independent label is not silently erased from the gold truth.
    """

    y_pred_independent = threshold_probabilities(
        probabilities,
        threshold_vector,
    )

    if y_true_full is None:
        y_true_full = expand_binary_feature_matrix(
            y_true_independent,
            hierarchy_matrix,
        )

    if y_true_full.shape[0] != y_true_independent.shape[0]:
        raise RuntimeError(
            "Complete and independent truth matrices contain different "
            f"numbers of supervised tokens: {y_true_full.shape[0]} vs "
            f"{y_true_independent.shape[0]}."
        )

    y_pred_full = expand_binary_feature_matrix(
        y_pred_independent,
        hierarchy_matrix,
    )

    metrics = calculate_average_metrics(
        y_true_full,
        y_pred_full,
        prefix="",
    )

    metrics.update(
        calculate_average_metrics(
            y_true_independent,
            y_pred_independent,
            prefix="direct_",
        )
    )

    return metrics


def make_compute_metrics(
    prediction_labels: Sequence[str],
    hierarchy_matrix: np.ndarray,
):
    """Create Trainer metrics using the fixed default 0.5 thresholds."""

    default_thresholds = np.full(
        len(prediction_labels),
        DEFAULT_PREDICTION_THRESHOLD,
        dtype=np.float32,
    )

    def compute_metrics(eval_prediction) -> Dict[str, float]:
        logits, labels = eval_prediction

        probabilities, y_true_independent = extract_valid_token_arrays(
            logits,
            labels,
        )

        return calculate_hierarchical_metrics_from_probabilities(
            probabilities=probabilities,
            y_true_independent=y_true_independent,
            threshold_vector=default_thresholds,
            hierarchy_matrix=hierarchy_matrix,
        )

    return compute_metrics


def build_threshold_grid() -> np.ndarray:
    """Build an inclusive, stable validation threshold search grid."""

    if THRESHOLD_STEP <= 0:
        raise ValueError("THRESHOLD_STEP must be > 0.")

    if not 0.0 < THRESHOLD_MIN < 1.0:
        raise ValueError("THRESHOLD_MIN must be between 0 and 1.")

    if not 0.0 < THRESHOLD_MAX < 1.0:
        raise ValueError("THRESHOLD_MAX must be between 0 and 1.")

    if THRESHOLD_MIN > THRESHOLD_MAX:
        raise ValueError("THRESHOLD_MIN cannot exceed THRESHOLD_MAX.")

    count = int(
        round(
            (THRESHOLD_MAX - THRESHOLD_MIN)
            / THRESHOLD_STEP
        )
    ) + 1

    return np.linspace(
        THRESHOLD_MIN,
        THRESHOLD_MAX,
        count,
        dtype=np.float64,
    )


def binary_metrics_for_column(
    y_true: np.ndarray,
    y_pred: np.ndarray,
) -> Tuple[float, float, float, int]:
    """Return binary precision, recall, F1 and positive support."""

    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="binary",
        zero_division=0,
    )

    support = int(y_true.sum())

    return (
        float(precision),
        float(recall),
        float(f1),
        support,
    )


def optimise_feature_thresholds(
    probabilities: np.ndarray,
    y_true_independent: np.ndarray,
    prediction_labels: Sequence[str],
) -> Tuple[Dict[str, float], Dict[str, Dict[str, float]]]:
    """
    Optimise one sigmoid threshold per independent feature on VALIDATION ONLY.

    Objective:
        maximise that feature's binary F1.

    Stability rules:
    - If validation has no positives or no negatives for a feature, keep 0.5.
    - If several thresholds tie for best F1, choose the one closest to 0.5.
      This avoids unnecessarily extreme thresholds for flat validation curves.
    """

    grid = build_threshold_grid()

    thresholds: Dict[str, float] = {}
    diagnostics: Dict[str, Dict[str, float]] = {}

    for label_id, feature in enumerate(prediction_labels):
        y_true = y_true_independent[:, label_id]
        probs = probabilities[:, label_id]

        positive_support = int(y_true.sum())
        negative_support = int((1 - y_true).sum())

        default_pred = (
            probs >= DEFAULT_PREDICTION_THRESHOLD
        ).astype(np.int32)

        (
            default_precision,
            default_recall,
            default_f1,
            _,
        ) = binary_metrics_for_column(
            y_true,
            default_pred,
        )

        if positive_support == 0 or negative_support == 0:
            best_threshold = DEFAULT_PREDICTION_THRESHOLD
        else:
            best_f1 = -1.0
            best_candidates: List[float] = []

            for threshold in grid:
                y_pred = (probs >= threshold).astype(np.int32)

                _, _, f1, _ = binary_metrics_for_column(
                    y_true,
                    y_pred,
                )

                if f1 > best_f1 + 1e-12:
                    best_f1 = f1
                    best_candidates = [float(threshold)]
                elif abs(f1 - best_f1) <= 1e-12:
                    best_candidates.append(float(threshold))

            best_threshold = min(
                best_candidates,
                key=lambda value: (
                    abs(value - DEFAULT_PREDICTION_THRESHOLD),
                    value,
                ),
            )

        best_pred = (
            probs >= best_threshold
        ).astype(np.int32)

        (
            best_precision,
            best_recall,
            best_f1,
            _,
        ) = binary_metrics_for_column(
            y_true,
            best_pred,
        )

        thresholds[feature] = float(best_threshold)

        diagnostics[feature] = {
            "threshold": float(best_threshold),
            "support": positive_support,
            "negative_support": negative_support,
            "precision_default": default_precision,
            "recall_default": default_recall,
            "f1_default": default_f1,
            "precision_optimised": best_precision,
            "recall_optimised": best_recall,
            "f1_optimised": best_f1,
            "f1_change": best_f1 - default_f1,
        }

    return thresholds, diagnostics


def calculate_per_feature_metrics_from_binary(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    labels: Sequence[str],
) -> Dict[str, Dict[str, float]]:
    """Calculate binary precision/recall/F1 independently for each column."""

    results: Dict[str, Dict[str, float]] = {}

    for label_id, feature in enumerate(labels):
        precision, recall, f1, support = binary_metrics_for_column(
            y_true[:, label_id],
            y_pred[:, label_id],
        )

        results[feature] = {
            "precision": precision,
            "recall": recall,
            "f1": f1,
            "support": support,
        }

    return results


# =============================================================================
# Dataset diagnostics and validation
# =============================================================================

def count_feature_occurrences(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    sentence_indices: Sequence[int],
    independent_only: bool = False,
) -> Counter:
    """Count complete or independent positive labels in a split."""

    counts: Counter = Counter()

    for sentence_index in sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            if independent_only:
                features = get_independent_record_features(record)
            else:
                features = clean_features(record)

            for feature in features:
                counts[feature] += 1

    return counts


def count_empty_records(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    sentence_indices: Sequence[int],
) -> int:
    """Count NOUN/PROPN records having no complete feature tags."""

    count = 0

    for sentence_index in sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            if not clean_features(record):
                count += 1

    return count


def verify_full_label_coverage(
    full_labels: Sequence[str],
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
) -> None:
    """Ensure validation/test contain no complete label unseen in training."""

    training_labels = set(full_labels)

    for split_name in ("validation", "test"):
        tagged_records, sentence_indices = split_sources[split_name]
        observed: Set[str] = set()

        for sentence_index in sentence_indices:
            for record in tagged_records.get(sentence_index, {}).values():
                observed.update(clean_features(record))

        unknown = observed - training_labels

        if unknown:
            raise RuntimeError(
                f"{split_name} contains full labels unseen in training: "
                f"{sorted(unknown)}"
            )


def verify_prediction_label_coverage(
    prediction_labels: Sequence[str],
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
    training_file_prediction_labels: Optional[Sequence[str]] = None,
) -> Dict[str, Dict[str, int]]:
    """Check independent-target coverage without leaking test labels.

    Validation remains strict: every validation independent target must have a
    training-derived neural output head.

    Test is different.  A genuine held-out corpus may contain a direct
    independent target that never occurred independently in training.  Such a
    label must NOT be added to the model from the test set.  Instead, report it
    and let complete-feature evaluation use the source gold matrix directly.
    """

    training_labels = set(prediction_labels)
    training_file_labels = (
        set(training_file_prediction_labels)
        if training_file_prediction_labels is not None
        else set(training_labels)
    )

    unseen_test_support: Dict[str, Dict[str, int]] = {}

    for split_name in ("validation", "test"):
        tagged_records, sentence_indices = split_sources[split_name]
        observed_counts: Counter = Counter()

        for sentence_index in sentence_indices:
            for record in tagged_records.get(sentence_index, {}).values():
                for feature in get_independent_record_features(record):
                    observed_counts[feature] += 1

        observed = set(observed_counts)
        unknown = observed - training_labels

        if not unknown:
            continue

        lost_due_to_split = unknown & training_file_labels
        absent_from_training_file = unknown - training_file_labels

        if split_name == "validation":
            details: List[str] = []

            if lost_due_to_split:
                details.append(
                    "present somewhere in the training file but absent from "
                    f"the training subset: {sorted(lost_due_to_split)}"
                )

            if absent_from_training_file:
                details.append(
                    "never occur as independent targets anywhere in the "
                    f"training file: {sorted(absent_from_training_file)}"
                )

            raise RuntimeError(
                "validation contains independent labels with no learnable "
                "training output. "
                + "; ".join(details)
            )

        # For the official test set, do not modify the model vocabulary.
        unseen_test_support = {
            feature: {
                "support": int(observed_counts[feature]),
                "present_in_training_file_as_independent": int(
                    feature in training_file_labels
                ),
            }
            for feature in sorted(unknown)
        }

        print()
        print("=" * 80)
        print("HELD-OUT TEST LABEL COVERAGE WARNING")
        print("=" * 80)
        print(
            "The test corpus contains direct independent targets that have no "
            "training-derived neural output head. They will NOT be added to "
            "the model vocabulary. Complete test truth will be read directly "
            "from the source annotations instead."
        )

        for feature in sorted(unknown):
            print(
                f"  {feature:35s} support={observed_counts[feature]:,}"
            )

        print()

    return unseen_test_support


def verify_hierarchy_closure(
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
) -> None:
    """
    Ensure source feature sets already contain all ancestors required by the
    hierarchy. This prevents evaluation against inconsistent source targets.
    """

    problems: List[str] = []
    max_examples = 20

    for split_name in ("train", "validation", "test"):
        tagged_records, sentence_indices = split_sources[split_name]
        problem_count = 0

        for sentence_index in sentence_indices:
            for token_id, record in tagged_records.get(
                sentence_index,
                {},
            ).items():
                features = clean_features(record)

                if not features:
                    continue

                missing = missing_hierarchy_features(features)

                if not missing:
                    continue

                problem_count += 1

                if len(problems) < max_examples:
                    problems.append(
                        f"{split_name}: sentence={sentence_index}, "
                        f"token={token_id}, "
                        f"form={record.get('form')!r}, "
                        f"missing={sorted(missing)}"
                    )

        if problem_count:
            print(
                f"Hierarchy closure problems in {split_name}: "
                f"{problem_count:,} token(s)"
            )

    if problems:
        example_text = "\n".join(
            f"  - {problem}"
            for problem in problems
        )

        raise RuntimeError(
            "The input dataset is not hierarchy-closed. Fix the source tags "
            "before training so deterministic reduction/expansion is exact.\n"
            f"Examples:\n{example_text}"
        )


def print_split_statistics(
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
) -> None:
    print("=" * 80)
    print("DATASET SPLIT")
    print("=" * 80)

    for split_name in ("train", "validation", "test"):
        tagged_records, indices = split_sources[split_name]

        full_counts = count_feature_occurrences(
            tagged_records,
            indices,
            independent_only=False,
        )

        independent_counts = count_feature_occurrences(
            tagged_records,
            indices,
            independent_only=True,
        )

        empty_count = count_empty_records(
            tagged_records,
            indices,
        )

        noun_count = sum(
            len(tagged_records.get(index, {}))
            for index in indices
        )

        source_name = (
            "training file"
            if split_name in {"train", "validation"}
            else "test file"
        )

        print(
            f"{split_name:12s}: "
            f"{len(indices):,} sentences | "
            f"{noun_count:,} NOUN/PROPN tokens | "
            f"{sum(full_counts.values()):,} complete positives -> "
            f"{sum(independent_counts.values()):,} independent positives | "
            f"{empty_count:,} empty-feature tokens excluded | "
            f"source={source_name}"
        )

    print()


def print_prediction_label_statistics(
    prediction_labels: Sequence[str],
    full_labels: Sequence[str],
    train_tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    train_sentence_indices: Sequence[int],
) -> None:
    """Show which labels are neural outputs versus deterministic-only parents."""

    train_independent_counts = count_feature_occurrences(
        train_tagged_records,
        train_sentence_indices,
        independent_only=True,
    )

    prediction_set = set(prediction_labels)
    deterministic_only = [
        feature
        for feature in full_labels
        if feature not in prediction_set
    ]

    print("=" * 80)
    print("NEURAL OUTPUT FEATURES")
    print("=" * 80)
    print(
        f"Complete evaluation features: {len(full_labels)}"
    )
    print(
        f"Independent neural outputs: {len(prediction_labels)}"
    )
    print(
        f"Deterministic-only features in this training split: "
        f"{len(deterministic_only)}"
    )
    print()

    print(
        f"{'Feature':35s} "
        f"{'Independent train support':>26s}"
    )
    print("-" * 64)

    for feature in prediction_labels:
        print(
            f"{feature:35s} "
            f"{train_independent_counts[feature]:26d}"
        )

    if deterministic_only:
        print()
        print("Deterministic-only in this split:")

        for feature in deterministic_only:
            print(f"  - {feature}")

    print()


# =============================================================================
# Repeated-run and bootstrap helpers
# =============================================================================

def get_supervised_token_count_for_sentence(
    dataset: "SemanticFeatureDataset",
    sentence_index: int,
) -> int:
    """
    Count supervised first-subword targets for one source sentence.

    This mirrors SemanticFeatureDataset.__getitem__ exactly and is used to map
    flat prediction rows back to sentence clusters for test bootstrapping.
    """

    sentence = dataset.sentences[sentence_index]
    words, token_ids = get_sentence_words(sentence)

    encoding = dataset.tokenizer(
        words,
        is_split_into_words=True,
        truncation=True,
        max_length=dataset.max_length,
        add_special_tokens=True,
    )

    word_ids = encoding.word_ids()
    previous_word_id: Optional[int] = None
    sentence_records = dataset.tagged_records.get(sentence_index, {})

    count = 0

    for word_id in word_ids:
        if word_id is None:
            previous_word_id = word_id
            continue

        if word_id == previous_word_id:
            continue

        previous_word_id = word_id

        if not 0 <= word_id < len(token_ids):
            continue

        conllu_token_id = token_ids[word_id]
        record = sentence_records.get(conllu_token_id)

        if record is None:
            continue

        features = clean_features(record)

        if not features and EXCLUDE_EMPTY_FEATURE_RECORDS:
            continue

        count += 1

    return count


def build_sentence_row_slices(
    dataset: "SemanticFeatureDataset",
) -> List[slice]:
    """
    Map every dataset sentence to its contiguous flat supervised-token rows.
    """

    slices: List[slice] = []
    start = 0

    for sentence_index in dataset.sentence_indices:
        count = get_supervised_token_count_for_sentence(
            dataset,
            sentence_index,
        )
        stop = start + count
        slices.append(slice(start, stop))
        start = stop

    return slices


def summarise_repeated_metrics(
    metric_dicts: Sequence[Dict[str, float]],
) -> Dict[str, Dict[str, float]]:
    """Return mean/SD/min/max across repeated seeded runs."""

    if not metric_dicts:
        return {}

    common_keys = sorted(
        set.intersection(
            *[
                {
                    key
                    for key, value in metrics.items()
                    if isinstance(
                        value,
                        (float, int, np.floating, np.integer),
                    )
                }
                for metrics in metric_dicts
            ]
        )
    )

    summary: Dict[str, Dict[str, float]] = {}

    for key in common_keys:
        values = np.asarray(
            [float(metrics[key]) for metrics in metric_dicts],
            dtype=np.float64,
        )

        summary[key] = {
            "mean": float(values.mean()),
            "sd": float(values.std(ddof=1))
            if len(values) > 1
            else 0.0,
            "minimum": float(values.min()),
            "maximum": float(values.max()),
            "n_runs": int(len(values)),
        }

    return summary


def _metrics_from_confusion_counts(
    tp_by_label: np.ndarray,
    fp_by_label: np.ndarray,
    fn_by_label: np.ndarray,
) -> Dict[str, float]:
    """Calculate six headline metrics directly from labelwise counts."""

    tp_by_label = tp_by_label.astype(np.float64, copy=False)
    fp_by_label = fp_by_label.astype(np.float64, copy=False)
    fn_by_label = fn_by_label.astype(np.float64, copy=False)

    tp = float(tp_by_label.sum())
    fp = float(fp_by_label.sum())
    fn = float(fn_by_label.sum())

    precision_micro = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall_micro = tp / (tp + fn) if (tp + fn) > 0 else 0.0

    if precision_micro + recall_micro > 0:
        f1_micro = (
            2.0
            * precision_micro
            * recall_micro
            / (precision_micro + recall_micro)
        )
    else:
        f1_micro = 0.0

    precision_den = tp_by_label + fp_by_label
    recall_den = tp_by_label + fn_by_label

    precision_by_label = np.divide(
        tp_by_label,
        precision_den,
        out=np.zeros_like(tp_by_label, dtype=np.float64),
        where=precision_den > 0,
    )
    recall_by_label = np.divide(
        tp_by_label,
        recall_den,
        out=np.zeros_like(tp_by_label, dtype=np.float64),
        where=recall_den > 0,
    )

    f1_den = precision_by_label + recall_by_label
    f1_by_label = np.divide(
        2.0 * precision_by_label * recall_by_label,
        f1_den,
        out=np.zeros_like(precision_by_label, dtype=np.float64),
        where=f1_den > 0,
    )

    return {
        "precision_micro": float(precision_micro),
        "recall_micro": float(recall_micro),
        "f1_micro": float(f1_micro),
        "precision_macro": float(precision_by_label.mean()),
        "recall_macro": float(recall_by_label.mean()),
        "f1_macro": float(f1_by_label.mean()),
    }


def build_sentence_confusion_arrays(
    y_true_full: np.ndarray,
    run_predictions_full: Sequence[np.ndarray],
    sentence_slices: Sequence[slice],
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Precompute TP/FP/FN by [run, sentence, label] for fast cluster bootstrap.
    """

    n_runs = len(run_predictions_full)
    n_sentences = len(sentence_slices)
    n_labels = y_true_full.shape[1]

    tp = np.zeros(
        (n_runs, n_sentences, n_labels),
        dtype=np.int32,
    )
    fp = np.zeros_like(tp)
    fn = np.zeros_like(tp)

    for sentence_pos, row_slice in enumerate(sentence_slices):
        y_true_sentence = y_true_full[row_slice]

        for run_pos, y_pred_full in enumerate(run_predictions_full):
            y_pred_sentence = y_pred_full[row_slice]

            tp[run_pos, sentence_pos] = (
                (y_true_sentence == 1)
                & (y_pred_sentence == 1)
            ).sum(axis=0)

            fp[run_pos, sentence_pos] = (
                (y_true_sentence == 0)
                & (y_pred_sentence == 1)
            ).sum(axis=0)

            fn[run_pos, sentence_pos] = (
                (y_true_sentence == 1)
                & (y_pred_sentence == 0)
            ).sum(axis=0)

    return tp, fp, fn


def bootstrap_mean_test_metrics(
    y_true_full: np.ndarray,
    run_predictions_full: Sequence[np.ndarray],
    sentence_slices: Sequence[slice],
) -> Dict[str, Any]:
    """
    Sentence-cluster bootstrap CIs for the MEAN performance across run seeds.

    Each bootstrap replicate:
      1. samples test sentences with replacement;
      2. applies the SAME sampled sentence multiplicities to every trained run;
      3. computes each run's six hierarchy-expanded metrics;
      4. averages each metric across runs.

    Thus the interval quantifies held-out TEST-SAMPLE uncertainty around the
    mean performance of the repeated-run procedure. Training-seed variability is
    reported separately via mean and SD across runs.
    """

    if TEST_BOOTSTRAP_SAMPLES < 1:
        raise ValueError("TEST_BOOTSTRAP_SAMPLES must be at least 1.")

    if not 0.0 < TEST_BOOTSTRAP_CONFIDENCE < 1.0:
        raise ValueError(
            "TEST_BOOTSTRAP_CONFIDENCE must be strictly between 0 and 1."
        )

    if not run_predictions_full:
        raise ValueError(
            "At least one run prediction matrix is required for bootstrap."
        )

    n_sentences = len(sentence_slices)

    if n_sentences == 0:
        raise ValueError("No test sentences are available for bootstrap.")

    expected_rows = sum(
        row_slice.stop - row_slice.start
        for row_slice in sentence_slices
    )

    if expected_rows != y_true_full.shape[0]:
        raise RuntimeError(
            "Sentence slices do not cover the complete test truth matrix: "
            f"{expected_rows:,} rows vs {y_true_full.shape[0]:,}."
        )

    for run_pos, y_pred_full in enumerate(run_predictions_full):
        if y_pred_full.shape != y_true_full.shape:
            raise RuntimeError(
                f"Run {run_pos} prediction shape {y_pred_full.shape} does "
                f"not match test truth shape {y_true_full.shape}."
            )

    tp, fp, fn = build_sentence_confusion_arrays(
        y_true_full,
        run_predictions_full,
        sentence_slices,
    )

    rng = np.random.default_rng(TEST_BOOTSTRAP_SEED)

    metric_names = [
        "precision_micro",
        "recall_micro",
        "f1_micro",
        "precision_macro",
        "recall_macro",
        "f1_macro",
    ]

    bootstrap_values = {
        metric: np.empty(TEST_BOOTSTRAP_SAMPLES, dtype=np.float64)
        for metric in metric_names
    }

    for bootstrap_index in range(TEST_BOOTSTRAP_SAMPLES):
        sampled_sentences = rng.integers(
            0,
            n_sentences,
            size=n_sentences,
        )

        multiplicities = np.bincount(
            sampled_sentences,
            minlength=n_sentences,
        ).astype(np.int32)

        run_metric_values = {
            metric: []
            for metric in metric_names
        }

        for run_pos in range(len(run_predictions_full)):
            tp_by_label = np.tensordot(
                multiplicities,
                tp[run_pos],
                axes=(0, 0),
            )
            fp_by_label = np.tensordot(
                multiplicities,
                fp[run_pos],
                axes=(0, 0),
            )
            fn_by_label = np.tensordot(
                multiplicities,
                fn[run_pos],
                axes=(0, 0),
            )

            metrics = _metrics_from_confusion_counts(
                tp_by_label,
                fp_by_label,
                fn_by_label,
            )

            for metric in metric_names:
                run_metric_values[metric].append(metrics[metric])

        for metric in metric_names:
            bootstrap_values[metric][bootstrap_index] = float(
                np.mean(run_metric_values[metric])
            )

    alpha = 1.0 - TEST_BOOTSTRAP_CONFIDENCE
    lower_q = alpha / 2.0
    upper_q = 1.0 - lower_q

    intervals: Dict[str, Dict[str, float]] = {}

    for metric in metric_names:
        values = bootstrap_values[metric]

        intervals[metric] = {
            "bootstrap_mean": float(values.mean()),
            "bootstrap_sd": float(values.std(ddof=1))
            if len(values) > 1
            else 0.0,
            "ci_lower": float(np.quantile(values, lower_q)),
            "ci_upper": float(np.quantile(values, upper_q)),
            "confidence": float(TEST_BOOTSTRAP_CONFIDENCE),
            "bootstrap_samples": int(TEST_BOOTSTRAP_SAMPLES),
        }

    return {
        "bootstrap_unit": "sentence",
        "statistic": "mean_metric_across_repeated_training_runs",
        "seed": TEST_BOOTSTRAP_SEED,
        "n_test_sentences": n_sentences,
        "n_runs": len(run_predictions_full),
        "intervals": intervals,
    }


def make_json_serialisable(value: Any) -> Any:
    """Recursively convert NumPy scalars/arrays to ordinary JSON values."""

    if isinstance(value, dict):
        return {
            str(key): make_json_serialisable(item)
            for key, item in value.items()
        }

    if isinstance(value, (list, tuple)):
        return [
            make_json_serialisable(item)
            for item in value
        ]

    if isinstance(value, np.ndarray):
        return value.tolist()

    if isinstance(value, (np.floating, np.integer)):
        return value.item()

    return value


# =============================================================================
# Reporting helpers
# =============================================================================

def print_metric_dictionary(
    metrics: Dict[str, float],
) -> None:
    for key, value in sorted(metrics.items()):
        print(f"{key}: {value}")


def print_threshold_table(
    prediction_labels: Sequence[str],
    diagnostics: Dict[str, Dict[str, float]],
) -> None:
    print()
    print("=" * 100)
    print("VALIDATION-OPTIMISED THRESHOLDS")
    print("=" * 100)

    heading = (
        f"{'Feature':35s} "
        f"{'Threshold':>10s} "
        f"{'Support':>9s} "
        f"{'F1@0.5':>10s} "
        f"{'F1 opt':>10s} "
        f"{'Change':>10s}"
    )

    print(heading)
    print("-" * len(heading))

    for feature in prediction_labels:
        result = diagnostics[feature]

        print(
            f"{feature:35s} "
            f"{result['threshold']:10.2f} "
            f"{int(result['support']):9d} "
            f"{result['f1_default']:10.4f} "
            f"{result['f1_optimised']:10.4f} "
            f"{result['f1_change']:+10.4f}"
        )


def print_per_feature_table(
    title: str,
    labels: Sequence[str],
    results: Dict[str, Dict[str, float]],
) -> None:
    print()
    print("=" * 80)
    print(title)
    print("=" * 80)

    heading = (
        f"{'Feature':35s} "
        f"{'Precision':>10s} "
        f"{'Recall':>10s} "
        f"{'F1':>10s} "
        f"{'Support':>10s}"
    )

    print(heading)
    print("-" * len(heading))

    for feature in labels:
        result = results[feature]

        print(
            f"{feature:35s} "
            f"{result['precision']:10.4f} "
            f"{result['recall']:10.4f} "
            f"{result['f1']:10.4f} "
            f"{result['support']:10d}"
        )


def summarise_repeated_per_feature_metrics(
    run_documents: Sequence[Dict[str, Any]],
    result_key: str,
    labels: Sequence[str],
) -> Dict[str, Dict[str, float]]:
    """Summarise per-feature test precision/recall/F1 across repeated runs."""

    summary: Dict[str, Dict[str, float]] = {}

    for feature in labels:
        precision_values = np.asarray(
            [
                run_document[result_key][feature]["precision"]
                for run_document in run_documents
            ],
            dtype=np.float64,
        )
        recall_values = np.asarray(
            [
                run_document[result_key][feature]["recall"]
                for run_document in run_documents
            ],
            dtype=np.float64,
        )
        f1_values = np.asarray(
            [
                run_document[result_key][feature]["f1"]
                for run_document in run_documents
            ],
            dtype=np.float64,
        )
        supports = {
            int(run_document[result_key][feature]["support"])
            for run_document in run_documents
        }

        if len(supports) != 1:
            raise RuntimeError(
                f"Test support changed across runs for feature {feature!r}: "
                f"{sorted(supports)}"
            )

        summary[feature] = {
            "precision_mean": float(precision_values.mean()),
            "precision_sd": float(precision_values.std(ddof=1))
            if len(precision_values) > 1
            else 0.0,
            "recall_mean": float(recall_values.mean()),
            "recall_sd": float(recall_values.std(ddof=1))
            if len(recall_values) > 1
            else 0.0,
            "f1_mean": float(f1_values.mean()),
            "f1_sd": float(f1_values.std(ddof=1))
            if len(f1_values) > 1
            else 0.0,
            "f1_min": float(f1_values.min()),
            "f1_max": float(f1_values.max()),
            "support": int(next(iter(supports))),
        }

    return summary


def print_repeated_per_feature_table(
    title: str,
    labels: Sequence[str],
    summary: Dict[str, Dict[str, float]],
) -> None:
    """Print repeated-run mean/SD test performance for each feature."""

    print()
    print("=" * 118)
    print(title)
    print("=" * 118)

    heading = (
        f"{'Feature':35s} "
        f"{'P mean':>8s} "
        f"{'P SD':>8s} "
        f"{'R mean':>8s} "
        f"{'R SD':>8s} "
        f"{'F1 mean':>8s} "
        f"{'F1 SD':>8s} "
        f"{'F1 min':>8s} "
        f"{'F1 max':>8s} "
        f"{'Support':>8s}"
    )

    print(heading)
    print("-" * len(heading))

    for feature in labels:
        result = summary[feature]
        print(
            f"{feature:35s} "
            f"{result['precision_mean']:8.4f} "
            f"{result['precision_sd']:8.4f} "
            f"{result['recall_mean']:8.4f} "
            f"{result['recall_sd']:8.4f} "
            f"{result['f1_mean']:8.4f} "
            f"{result['f1_sd']:8.4f} "
            f"{result['f1_min']:8.4f} "
            f"{result['f1_max']:8.4f} "
            f"{int(result['support']):8d}"
        )


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )
    RUNS_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    validate_feature_hierarchy()
    check_cuda()

    if not RUN_SEEDS:
        raise ValueError("RUN_SEEDS must contain at least one integer seed.")

    if len(set(RUN_SEEDS)) != len(RUN_SEEDS):
        raise ValueError("RUN_SEEDS contains duplicate seeds.")

    # -------------------------------------------------------------------------
    # Load independent TRAIN and held-out TEST corpora
    # -------------------------------------------------------------------------

    print("=" * 80)
    print("LOADING DATA")
    print("=" * 80)

    train_sentences = load_conllu(TRAIN_CONLLU_PATH)
    test_sentences = load_conllu(TEST_CONLLU_PATH)

    train_tagged_records = load_tagged_records(TRAIN_JSONL_PATH)
    test_tagged_records = load_tagged_records(TEST_JSONL_PATH)

    validate_feature_switches(
        train_tagged_records,
        test_tagged_records,
    )

    print(
        "Training CoNLL-U sentences: "
        f"{len(train_sentences):,}"
    )
    print(
        "Test CoNLL-U sentences: "
        f"{len(test_sentences):,}"
    )
    print(
        "Training sentences represented in tagged JSONL: "
        f"{len(train_tagged_records):,}"
    )
    print(
        "Test sentences represented in tagged JSONL: "
        f"{len(test_tagged_records):,}"
    )

    train_target_record_count = sum(
        len(records)
        for records in train_tagged_records.values()
    )
    test_target_record_count = sum(
        len(records)
        for records in test_tagged_records.values()
    )

    print(
        "Training tagged NOUN/PROPN records: "
        f"{train_target_record_count:,}"
    )
    print(
        "Test tagged NOUN/PROPN records: "
        f"{test_target_record_count:,}"
    )
    print()

    # -------------------------------------------------------------------------
    # Fixed sentence-level TRAIN/VALIDATION split; TEST remains untouched
    # -------------------------------------------------------------------------

    eligible_train_indices = get_eligible_sentence_indices(
        train_sentences,
        train_tagged_records,
    )
    eligible_test_indices = get_eligible_sentence_indices(
        test_sentences,
        test_tagged_records,
    )

    print(
        "Eligible training-file sentences with at least one non-empty "
        "feature target: "
        f"{len(eligible_train_indices):,}"
    )
    print(
        "Eligible test-file sentences with at least one non-empty "
        "feature target: "
        f"{len(eligible_test_indices):,}"
    )

    train_validation_split = make_train_validation_split(
        eligible_train_indices,
        train_tagged_records,
    )

    train_indices = train_validation_split["train"]
    validation_indices = train_validation_split["validation"]
    test_indices = list(eligible_test_indices)

    split_sources = {
        "train": (train_tagged_records, train_indices),
        "validation": (train_tagged_records, validation_indices),
        "test": (test_tagged_records, test_indices),
    }

    split_document = {
        "split_unit": "sentence",
        "stratification": "iterative_multilabel_sentence_presence",
        "split_seed_requested": SPLIT_SEED,
        "split_seed_used": train_validation_split["split_seed_used"],
        "split_attempt": train_validation_split["attempt"],
        "validation_fraction": VALIDATION_FRACTION,
        "feature_switches": dict(sorted(FEATURE_SWITCHES.items())),
        "prevalence_error": train_validation_split["prevalence_error"],
        "stratification_labels": (
            train_validation_split["stratification_labels"]
        ),
        "train_jsonl": str(TRAIN_JSONL_PATH),
        "test_jsonl": str(TEST_JSONL_PATH),
        "train_conllu": str(TRAIN_CONLLU_PATH),
        "test_conllu": str(TEST_CONLLU_PATH),
        "index_spaces": {
            "train": "training corpus",
            "validation": "training corpus",
            "test": "test corpus",
        },
        "train": train_indices,
        "validation": validation_indices,
        "test": test_indices,
    }

    with SPLIT_PATH.open("w", encoding="utf-8") as handle:
        json.dump(
            make_json_serialisable(split_document),
            handle,
            ensure_ascii=False,
            indent=2,
        )

    # The reduction is exact only when source data are hierarchy-closed.
    verify_hierarchy_closure(split_sources)

    # -------------------------------------------------------------------------
    # Separate complete and neural-output vocabularies
    # -------------------------------------------------------------------------

    training_file_prediction_labels = build_prediction_label_vocabulary(
        train_tagged_records,
        eligible_train_indices,
    )

    # Vocabularies are derived from TRAIN only, never validation/test.
    full_labels = build_full_label_vocabulary(
        train_tagged_records,
        train_indices,
    )

    prediction_labels = build_prediction_label_vocabulary(
        train_tagged_records,
        train_indices,
    )

    verify_full_label_coverage(
        full_labels,
        split_sources,
    )

    unseen_test_independent_labels = verify_prediction_label_coverage(
        prediction_labels,
        split_sources,
        training_file_prediction_labels=training_file_prediction_labels,
    )

    prediction_label2id = {
        label: index
        for index, label in enumerate(prediction_labels)
    }

    prediction_id2label = {
        index: label
        for label, index in prediction_label2id.items()
    }

    full_label2id = {
        label: index
        for index, label in enumerate(full_labels)
    }

    hierarchy_matrix = build_hierarchy_expansion_matrix(
        prediction_labels,
        full_labels,
    )

    label_document = {
        "labels": prediction_labels,
        "label2id": prediction_label2id,
        "id2label": {
            str(key): value
            for key, value in prediction_id2label.items()
        },
        "prediction_labels": prediction_labels,
        "prediction_label2id": prediction_label2id,
        "full_labels": full_labels,
        "full_label2id": full_label2id,
        "feature_parents": {
            child: sorted(parents)
            for child, parents in sorted(FEATURE_PARENTS.items())
        },
        "target_representation": "per_token_independent_features",
        "split_unit": "sentence",
        "feature_switches": dict(sorted(FEATURE_SWITCHES.items())),
        "disabled_features": sorted(
            feature
            for feature, enabled in FEATURE_SWITCHES.items()
            if not enabled
        ),
    }

    with LABELS_PATH.open("w", encoding="utf-8") as handle:
        json.dump(
            label_document,
            handle,
            ensure_ascii=False,
            indent=2,
        )

    print_split_statistics(split_sources)

    print_prediction_label_statistics(
        prediction_labels,
        full_labels,
        train_tagged_records,
        train_indices,
    )

    # -------------------------------------------------------------------------
    # Tokeniser and fixed datasets
    # -------------------------------------------------------------------------

    tokenizer = AutoTokenizer.from_pretrained(
        MODEL_NAME,
        use_fast=True,
        add_prefix_space=True,
    )

    train_dataset = SemanticFeatureDataset(
        sentences=train_sentences,
        sentence_indices=train_indices,
        tagged_records=train_tagged_records,
        tokenizer=tokenizer,
        label2id=prediction_label2id,
        max_length=MAX_LENGTH,
    )

    validation_dataset = SemanticFeatureDataset(
        sentences=train_sentences,
        sentence_indices=validation_indices,
        tagged_records=train_tagged_records,
        tokenizer=tokenizer,
        label2id=prediction_label2id,
        max_length=MAX_LENGTH,
    )

    test_dataset = SemanticFeatureDataset(
        sentences=test_sentences,
        sentence_indices=test_indices,
        tagged_records=test_tagged_records,
        tokenizer=tokenizer,
        label2id=prediction_label2id,
        max_length=MAX_LENGTH,
    )

    data_collator = MultiLabelTokenCollator(
        tokenizer=tokenizer,
        num_labels=len(prediction_labels),
    )

    # Complete held-out gold truth is fixed across all training runs.
    test_true_full = build_full_truth_matrix_for_dataset(
        test_dataset,
        full_labels,
    )

    test_sentence_slices = build_sentence_row_slices(
        test_dataset,
    )

    test_slice_rows = sum(
        row_slice.stop - row_slice.start
        for row_slice in test_sentence_slices
    )

    if test_slice_rows != test_true_full.shape[0]:
        raise RuntimeError(
            "Test sentence-cluster mapping does not align with source truth: "
            f"{test_slice_rows:,} mapped rows vs "
            f"{test_true_full.shape[0]:,} truth rows."
        )

    # -------------------------------------------------------------------------
    # Repeated fine-tuning runs
    # -------------------------------------------------------------------------

    print("=" * 80)
    print("REPEATED FINE-TUNING")
    print("=" * 80)
    print(f"Runs: {len(RUN_SEEDS)}")
    print(f"Seeds: {RUN_SEEDS}")
    print(
        "Train/validation split is fixed across all runs; only the "
        "fine-tuning seed changes."
    )
    print()

    use_bf16 = torch.cuda.is_bf16_supported()

    all_run_documents: List[Dict[str, Any]] = []
    all_test_metric_dicts: List[Dict[str, float]] = []
    all_validation_metric_dicts: List[Dict[str, float]] = []
    all_test_predictions_full: List[np.ndarray] = []

    work_root = OUTPUT_DIR / "_trainer_work"
    work_root.mkdir(parents=True, exist_ok=True)

    for run_number, run_seed in enumerate(RUN_SEEDS, start=1):
        print()
        print("=" * 100)
        print(
            f"RUN {run_number}/{len(RUN_SEEDS)} | "
            f"SEED {run_seed}"
        )
        print("=" * 100)

        set_seed(run_seed)

        run_work_dir = work_root / f"seed_{run_seed}"
        run_result_path = RUNS_DIR / f"seed_{run_seed}.json"

        if run_work_dir.exists():
            shutil.rmtree(run_work_dir)

        model = RobertaMultiLabelModel(
            model_name=MODEL_NAME,
            num_labels=len(prediction_labels),
            id2label=prediction_id2label,
            label2id=prediction_label2id,
        )

        training_args = TrainingArguments(
            output_dir=str(run_work_dir),

            learning_rate=LEARNING_RATE,
            weight_decay=WEIGHT_DECAY,

            per_device_train_batch_size=TRAIN_BATCH_SIZE,
            per_device_eval_batch_size=EVAL_BATCH_SIZE,

            gradient_accumulation_steps=(
                GRADIENT_ACCUMULATION_STEPS
            ),

            num_train_epochs=NUM_EPOCHS,

            eval_strategy=EVAL_STRATEGY,
            save_strategy="epoch",
            logging_strategy="steps",
            logging_steps=50,

            load_best_model_at_end=True,

            # Model selection is performed on VALIDATION only, using complete
            # hierarchy-expanded macro F1 at the fixed 0.5 threshold.
            metric_for_best_model="f1_macro",
            greater_is_better=True,

            save_total_limit=2,

            bf16=use_bf16,
            fp16=not use_bf16,

            dataloader_num_workers=4,
            dataloader_pin_memory=True,

            optim="adamw_torch",
            report_to="none",

            seed=run_seed,
            data_seed=run_seed,

            remove_unused_columns=False,
            eval_accumulation_steps=16,
        )

        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_dataset,
            eval_dataset=validation_dataset,
            processing_class=tokenizer,
            data_collator=data_collator,
            compute_metrics=make_compute_metrics(
                prediction_labels,
                hierarchy_matrix,
            ),
        )

        trainer.train()

        # ---------------------------------------------------------------------
        # Validation: first report 0.5, then calibrate thresholds on validation
        # ---------------------------------------------------------------------

        validation_output = trainer.predict(
            validation_dataset,
            metric_key_prefix="validation_default",
        )

        (
            validation_probabilities,
            validation_true_independent,
        ) = extract_valid_token_arrays(
            validation_output.predictions,
            validation_output.label_ids,
        )

        default_threshold_vector = np.full(
            len(prediction_labels),
            DEFAULT_PREDICTION_THRESHOLD,
            dtype=np.float32,
        )

        validation_default_metrics = (
            calculate_hierarchical_metrics_from_probabilities(
                probabilities=validation_probabilities,
                y_true_independent=validation_true_independent,
                threshold_vector=default_threshold_vector,
                hierarchy_matrix=hierarchy_matrix,
            )
        )

        (
            optimised_thresholds,
            threshold_diagnostics,
        ) = optimise_feature_thresholds(
            probabilities=validation_probabilities,
            y_true_independent=validation_true_independent,
            prediction_labels=prediction_labels,
        )

        threshold_vector = make_threshold_vector(
            prediction_labels,
            optimised_thresholds,
        )

        validation_optimised_metrics = (
            calculate_hierarchical_metrics_from_probabilities(
                probabilities=validation_probabilities,
                y_true_independent=validation_true_independent,
                threshold_vector=threshold_vector,
                hierarchy_matrix=hierarchy_matrix,
            )
        )

        print_threshold_table(
            prediction_labels,
            threshold_diagnostics,
        )

        print()
        print("VALIDATION @ 0.5")
        print_metric_dictionary(validation_default_metrics)

        print()
        print("VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS")
        print_metric_dictionary(validation_optimised_metrics)

        # ---------------------------------------------------------------------
        # Held-out TEST: thresholds are frozen
        # ---------------------------------------------------------------------

        test_output = trainer.predict(
            test_dataset,
            metric_key_prefix="test_default",
        )

        test_probabilities, test_true_independent = (
            extract_valid_token_arrays(
                test_output.predictions,
                test_output.label_ids,
            )
        )

        if test_true_full.shape[0] != test_probabilities.shape[0]:
            raise RuntimeError(
                "Test source-truth alignment failed: predictions contain "
                f"{test_probabilities.shape[0]:,} supervised tokens but "
                f"source truth contains {test_true_full.shape[0]:,}."
            )

        # Explicit test-at-0.5 diagnostic.
        test_default_metrics = (
            calculate_hierarchical_metrics_from_probabilities(
                probabilities=test_probabilities,
                y_true_independent=test_true_independent,
                threshold_vector=default_threshold_vector,
                hierarchy_matrix=hierarchy_matrix,
                y_true_full=test_true_full,
            )
        )

        # Final per-run test result uses validation-calibrated thresholds.
        test_optimised_metrics = (
            calculate_hierarchical_metrics_from_probabilities(
                probabilities=test_probabilities,
                y_true_independent=test_true_independent,
                threshold_vector=threshold_vector,
                hierarchy_matrix=hierarchy_matrix,
                y_true_full=test_true_full,
            )
        )

        test_pred_independent = threshold_probabilities(
            test_probabilities,
            threshold_vector,
        )

        test_pred_full = expand_binary_feature_matrix(
            test_pred_independent,
            hierarchy_matrix,
        )

        all_test_predictions_full.append(
            test_pred_full.astype(np.int8, copy=True)
        )

        per_feature_full = calculate_per_feature_metrics_from_binary(
            y_true=test_true_full,
            y_pred=test_pred_full,
            labels=full_labels,
        )

        per_feature_independent = (
            calculate_per_feature_metrics_from_binary(
                y_true=test_true_independent,
                y_pred=test_pred_independent,
                labels=prediction_labels,
            )
        )

        print()
        print("TEST @ 0.5 (DIAGNOSTIC)")
        print_metric_dictionary(test_default_metrics)

        print()
        print("TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS")
        print_metric_dictionary(test_optimised_metrics)

        if PRINT_PER_RUN_FEATURE_TABLES:
            print_per_feature_table(
                title=(
                    f"RUN {run_number} / SEED {run_seed}: TEST PERFORMANCE "
                    "BY COMPLETE FEATURE (AFTER INHERITANCE)"
                ),
                labels=full_labels,
                results=per_feature_full,
            )
            print_per_feature_table(
                title=(
                    f"RUN {run_number} / SEED {run_seed}: TEST PERFORMANCE "
                    "BY INDEPENDENT NEURAL OUTPUT"
                ),
                labels=prediction_labels,
                results=per_feature_independent,
            )

        # ---------------------------------------------------------------------
        # Save a neutral reference model, not a cherry-picked best seed
        # ---------------------------------------------------------------------

        is_reference_run = (
            SAVE_REFERENCE_MODEL
            and run_number == 1
        )

        if is_reference_run:
            if REFERENCE_MODEL_DIR.exists():
                shutil.rmtree(REFERENCE_MODEL_DIR)

            trainer.save_model(str(REFERENCE_MODEL_DIR))
            tokenizer.save_pretrained(str(REFERENCE_MODEL_DIR))

            with (
                REFERENCE_MODEL_DIR / "semantic_features.json"
            ).open(
                "w",
                encoding="utf-8",
            ) as handle:
                json.dump(
                    label_document,
                    handle,
                    ensure_ascii=False,
                    indent=2,
                )

            reference_threshold_document = {
                "seed": run_seed,
                "selection_policy": (
                    "first_predeclared_seed_not_best_test_run"
                ),
                "optimised_on": "validation",
                "objective": "per_feature_binary_f1",
                "thresholds": optimised_thresholds,
                "diagnostics": threshold_diagnostics,
            }

            with (
                REFERENCE_MODEL_DIR / "prediction_thresholds.json"
            ).open(
                "w",
                encoding="utf-8",
            ) as handle:
                json.dump(
                    make_json_serialisable(
                        reference_threshold_document
                    ),
                    handle,
                    ensure_ascii=False,
                    indent=2,
                )

        run_document = {
            "run_number": run_number,
            "seed": run_seed,
            "is_reference_model": is_reference_run,
            "model": MODEL_NAME,
            "target_representation": (
                "per_token_independent_features"
            ),
            "feature_switches": dict(sorted(FEATURE_SWITCHES.items())),
            "disabled_features": sorted(
                feature
                for feature, enabled in FEATURE_SWITCHES.items()
                if not enabled
            ),
            "split": {
                "unit": "sentence",
                "split_seed": (
                    train_validation_split["split_seed_used"]
                ),
                "validation_fraction": VALIDATION_FRACTION,
                "train_sentences": len(train_indices),
                "validation_sentences": len(validation_indices),
                "test_sentences": len(test_indices),
            },
            "threshold_calibration": {
                "data": "validation_only",
                "objective": "per_feature_binary_f1",
                "thresholds": optimised_thresholds,
                "diagnostics": threshold_diagnostics,
            },
            "validation_metrics_at_0_5": (
                validation_default_metrics
            ),
            "validation_metrics_optimised": (
                validation_optimised_metrics
            ),
            "test_metrics_at_0_5": test_default_metrics,
            "test_metrics_optimised": test_optimised_metrics,
            "per_feature_complete": per_feature_full,
            "per_feature_independent": (
                per_feature_independent
            ),
            "unseen_test_independent_labels": (
                unseen_test_independent_labels
            ),
        }

        with run_result_path.open(
            "w",
            encoding="utf-8",
        ) as handle:
            json.dump(
                make_json_serialisable(run_document),
                handle,
                ensure_ascii=False,
                indent=2,
            )

        all_run_documents.append(run_document)
        all_test_metric_dicts.append(test_optimised_metrics)
        all_validation_metric_dicts.append(
            validation_optimised_metrics
        )

        # Release run-specific GPU state before initialising the next model.
        del test_output
        del validation_output
        del trainer
        del model

        gc.collect()
        torch.cuda.empty_cache()

        # Checkpoints were needed only to recover the best validation epoch.
        # Remove them after each run to avoid storing dozens of RoBERTa-large
        # copies. The neutral first-seed reference model was saved separately.
        if run_work_dir.exists():
            shutil.rmtree(run_work_dir)

    if work_root.exists() and not any(work_root.iterdir()):
        work_root.rmdir()

    # -------------------------------------------------------------------------
    # Repeated-run summary: stochastic training variability
    # -------------------------------------------------------------------------

    validation_summary = summarise_repeated_metrics(
        all_validation_metric_dicts
    )
    test_summary = summarise_repeated_metrics(
        all_test_metric_dicts
    )

    print()
    print("=" * 100)
    print("REPEATED-RUN TEST SUMMARY")
    print("=" * 100)

    headline_metrics = [
        "precision_micro",
        "recall_micro",
        "f1_micro",
        "precision_macro",
        "recall_macro",
        "f1_macro",
    ]

    print(
        f"{'Metric':25s} "
        f"{'Mean':>10s} "
        f"{'SD':>10s} "
        f"{'Min':>10s} "
        f"{'Max':>10s}"
    )
    print("-" * 70)

    for metric in headline_metrics:
        result = test_summary[metric]

        print(
            f"{metric:25s} "
            f"{result['mean']:10.4f} "
            f"{result['sd']:10.4f} "
            f"{result['minimum']:10.4f} "
            f"{result['maximum']:10.4f}"
        )

    # -------------------------------------------------------------------------
    # Repeated-run per-feature test summaries
    # -------------------------------------------------------------------------

    per_feature_complete_summary = summarise_repeated_per_feature_metrics(
        all_run_documents,
        result_key="per_feature_complete",
        labels=full_labels,
    )
    per_feature_independent_summary = summarise_repeated_per_feature_metrics(
        all_run_documents,
        result_key="per_feature_independent",
        labels=prediction_labels,
    )

    print_repeated_per_feature_table(
        title=(
            "REPEATED-RUN TEST PERFORMANCE BY COMPLETE FEATURE "
            "(AFTER INHERITANCE)"
        ),
        labels=full_labels,
        summary=per_feature_complete_summary,
    )

    print_repeated_per_feature_table(
        title=(
            "REPEATED-RUN TEST PERFORMANCE BY INDEPENDENT NEURAL OUTPUT"
        ),
        labels=prediction_labels,
        summary=per_feature_independent_summary,
    )

    # -------------------------------------------------------------------------
    # Sentence-cluster bootstrap: held-out test-sample uncertainty
    # -------------------------------------------------------------------------

    print()
    print("=" * 100)
    print("SENTENCE-CLUSTER BOOTSTRAP ON HELD-OUT TEST SET")
    print("=" * 100)

    bootstrap_results = bootstrap_mean_test_metrics(
        y_true_full=test_true_full,
        run_predictions_full=all_test_predictions_full,
        sentence_slices=test_sentence_slices,
    )

    print(
        f"Bootstrap samples: {TEST_BOOTSTRAP_SAMPLES:,}"
    )
    print(
        f"Confidence level : "
        f"{TEST_BOOTSTRAP_CONFIDENCE:.1%}"
    )
    print(
        "Bootstrap unit   : sentence (all eligible NOUN/PROPN targets "
        "from a sampled sentence move together)"
    )
    print()

    ci_percent = int(round(TEST_BOOTSTRAP_CONFIDENCE * 100))

    print(
        f"{'Metric':25s} "
        f"{'Run mean':>10s} "
        f"{'Run SD':>10s} "
        f"{str(ci_percent) + '% CI low':>12s} "
        f"{str(ci_percent) + '% CI high':>12s}"
    )
    print("-" * 78)

    for metric in headline_metrics:
        repeated = test_summary[metric]
        interval = bootstrap_results["intervals"][metric]

        print(
            f"{metric:25s} "
            f"{repeated['mean']:10.4f} "
            f"{repeated['sd']:10.4f} "
            f"{interval['ci_lower']:12.4f} "
            f"{interval['ci_upper']:12.4f}"
        )

    # -------------------------------------------------------------------------
    # Save experiment-level results
    # -------------------------------------------------------------------------

    bootstrap_document = {
        "model": MODEL_NAME,
        "run_seeds": RUN_SEEDS,
        "split_seed": train_validation_split["split_seed_used"],
        "test_bootstrap": bootstrap_results,
    }

    with BOOTSTRAP_RESULTS_PATH.open(
        "w",
        encoding="utf-8",
    ) as handle:
        json.dump(
            make_json_serialisable(bootstrap_document),
            handle,
            ensure_ascii=False,
            indent=2,
        )

    repeated_document = {
        "model": MODEL_NAME,
        "experimental_design": {
            "test_set": "fixed_external_held_out_file",
            "train_validation_split_unit": "sentence",
            "train_validation_stratification": (
                "iterative_multilabel_sentence_presence"
            ),
            "split_seed": (
                train_validation_split["split_seed_used"]
            ),
            "validation_fraction": VALIDATION_FRACTION,
            "number_of_runs": len(RUN_SEEDS),
            "run_seeds": RUN_SEEDS,
            "same_split_for_every_run": True,
            "threshold_calibration": (
                "per_feature_binary_f1_on_validation_only"
            ),
            "test_bootstrap_unit": "sentence",
            "test_bootstrap_samples": TEST_BOOTSTRAP_SAMPLES,
            "test_bootstrap_confidence": (
                TEST_BOOTSTRAP_CONFIDENCE
            ),
        },
        "data_sources": {
            "train_jsonl": str(TRAIN_JSONL_PATH),
            "test_jsonl": str(TEST_JSONL_PATH),
            "train_conllu": str(TRAIN_CONLLU_PATH),
            "test_conllu": str(TEST_CONLLU_PATH),
        },
        "split_sizes": {
            "train_sentences": len(train_indices),
            "validation_sentences": len(validation_indices),
            "test_sentences": len(test_indices),
        },
        "prediction_labels": prediction_labels,
        "full_labels": full_labels,
        "feature_switches": dict(sorted(FEATURE_SWITCHES.items())),
        "disabled_features": sorted(
            feature
            for feature, enabled in FEATURE_SWITCHES.items()
            if not enabled
        ),
        "unseen_test_independent_labels": (
            unseen_test_independent_labels
        ),
        "validation_repeated_run_summary": validation_summary,
        "test_repeated_run_summary": test_summary,
        "test_per_feature_complete_repeated_run_summary": (
            per_feature_complete_summary
        ),
        "test_per_feature_independent_repeated_run_summary": (
            per_feature_independent_summary
        ),
        "test_bootstrap": bootstrap_results,
        "runs": [
            {
                "run_number": run_document["run_number"],
                "seed": run_document["seed"],
                "is_reference_model": (
                    run_document["is_reference_model"]
                ),
                "result_file": str(
                    RUNS_DIR
                    / f"seed_{run_document['seed']}.json"
                ),
                "validation_metrics_optimised": (
                    run_document[
                        "validation_metrics_optimised"
                    ]
                ),
                "test_metrics_at_0_5": (
                    run_document["test_metrics_at_0_5"]
                ),
                "test_metrics_optimised": (
                    run_document["test_metrics_optimised"]
                ),
            }
            for run_document in all_run_documents
        ],
    }

    with REPEATED_RESULTS_PATH.open(
        "w",
        encoding="utf-8",
    ) as handle:
        json.dump(
            make_json_serialisable(repeated_document),
            handle,
            ensure_ascii=False,
            indent=2,
        )

    print()
    print("=" * 100)
    print("OUTPUTS")
    print("=" * 100)
    print(
        "Fixed sentence split:\n"
        f"  {SPLIT_PATH.resolve()}"
    )
    print(
        "Semantic feature metadata:\n"
        f"  {LABELS_PATH.resolve()}"
    )
    print(
        "Per-run results:\n"
        f"  {RUNS_DIR.resolve()}"
    )
    print(
        "Repeated-run summary:\n"
        f"  {REPEATED_RESULTS_PATH.resolve()}"
    )
    print(
        "Test bootstrap confidence intervals:\n"
        f"  {BOOTSTRAP_RESULTS_PATH.resolve()}"
    )

    if SAVE_REFERENCE_MODEL:
        print(
            "Neutral reference model (first predeclared seed; not "
            "best-test selected):\n"
            f"  {REFERENCE_MODEL_DIR.resolve()}"
        )


if __name__ == "__main__":
    main()

/root/.pyenv/versions/3.10.16/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

================================================================================
CUDA
================================================================================
PyTorch version: 2.13.0+cu130
CUDA available: True
CUDA runtime: 13.0
GPU: NVIDIA GeForce RTX 5070 Ti
VRAM: 15.92 GiB

================================================================================
LOADING DATA
================================================================================
================================================================================
FEATURE SWITCHES
================================================================================
Disabled features: State
All unlisted features are enabled.

Training CoNLL-U sentences: 12,544
Test CoNLL-U sentences: 2,077
Training sentences represented in tagged JSONL: 11,511
Test sentences represented in tagged JSONL: 1,815
Training tagged NOUN/PROPN records: 47,371
Test tagged NOUN/PROPN records: 6,198

Eligible training-file sentences with at least one non-empty feature target: 11,198
Eligible test-file sentences with at least one non-empty feature target: 1,759

Sentence-level multilabel-stratified train/validation split:
  Eligible training sentences : 11,198
  Target validation sentences : 2,240
  Actual validation sentences : 2,313
  Training sentences retained : 8,885
  Split seed used             : 42
  Stratification labels       : 37
  Coverage-rejected attempts  : 0
  Mean relative prevalence error: 0.008441

Feature                              All sent.      Train      Valid    Valid %
--------------------------------------------------------------------------------
Abstract                                  4469       3575        894      0.200
Animal                                     621        497        124      0.200
Animate                                     52         42         10      0.192
Artefact                                  1778       1422        356      0.200
Body_Part                                  265        212         53      0.200
Comestible                                 534        427        107      0.200
Communication                             1984       1587        397      0.200
Currency                                   197        158         39      0.198
Duration                                  1338       1070        268      0.200
Elongated                                  649        519        130      0.200
Eventive                                  3749       2999        750      0.200
Feminine                                   733        586        147      0.201
Fluid                                       87         70         17      0.195
Garment                                     62         50         12      0.194
Inanimate                                 4282       3425        857      0.200
Internal_Control                           107         86         21      0.196
Language                                    27         22          5      0.185
Location                                  3232       2585        647      0.200
Machine                                    694        555        139      0.200
Masculine                                 1829       1463        366      0.200
Natural                                    326        261         65      0.199
Natural_Force                              142        114         28      0.197
Non_Rigid                                 1200        960        240      0.200
Organisation                              3003       2402        601      0.200
Plant                                       66         53         13      0.197
Point_in_Time                             1211        969        242      0.200
Pointy                                      82         66         16      0.195
Question                                   161        129         32      0.199
Rigid                                     1965       1572        393      0.200
Solid                                     4618       3694        924      0.200
Sound                                      187        150         37      0.198
Statement                                 1115        892        223      0.200
Substance                                  826        661        165      0.200
Time                                        81         65         16      0.198
Unspecified_Gender_or_Neuter              2592       2074        518      0.200
Vehicle                                    344        275         69      0.201
Web_Location                               252        202         50      0.198

Actual validation sentence fraction: 0.2066


================================================================================
HELD-OUT TEST LABEL COVERAGE WARNING
================================================================================
The test corpus contains direct independent targets that have no training-derived neural output head. They will NOT be added to the model vocabulary. Complete test truth will be read directly from the source annotations instead.
  Human                               support=1

================================================================================
DATASET SPLIT
================================================================================
train       : 8,885 sentences | 37,581 NOUN/PROPN tokens | 138,588 complete positives -> 54,319 independent positives | 2,686 empty-feature tokens excluded | source=training file
validation  : 2,313 sentences | 9,408 NOUN/PROPN tokens | 34,753 complete positives -> 13,650 independent positives | 675 empty-feature tokens excluded | source=training file
test        : 1,759 sentences | 6,127 NOUN/PROPN tokens | 22,671 complete positives -> 8,826 independent positives | 423 empty-feature tokens excluded | source=test file

================================================================================
NEURAL OUTPUT FEATURES
================================================================================
Complete evaluation features: 42
Independent neural outputs: 37
Deterministic-only features in this training split: 5

Feature                              Independent train support
----------------------------------------------------------------
Abstract                                                  5754
Animal                                                     691
Animate                                                     46
Artefact                                                  1866
Body_Part                                                  318
Comestible                                                 671
Communication                                             2041
Currency                                                   179
Duration                                                  1393
Elongated                                                  632
Eventive                                                  4258
Feminine                                                   867
Fluid                                                       84
Garment                                                     60
Inanimate                                                 5851
Internal_Control                                            91
Language                                                    23
Location                                                  4733
Machine                                                    738
Masculine                                                 2684
Natural                                                    307
Natural_Force                                              130
Non_Rigid                                                 1378
Organisation                                              4425
Plant                                                       68
Point_in_Time                                             1257
Pointy                                                      78
Question                                                   130
Rigid                                                     2165
Solid                                                     5807
Sound                                                      169
Statement                                                 1038
Substance                                                  913
Time                                                        67
Unspecified_Gender_or_Neuter                              2826
Vehicle                                                    359
Web_Location                                               222

Deterministic-only in this split:
  - Concrete
  - Human
  - Rigidity
  - Shape
  - State_of_Matter

================================================================================
REPEATED FINE-TUNING
================================================================================
Runs: 30
Seeds: [11, 23, 37, 53, 71, 89, 107, 127, 149, 173, 197, 223, 251, 281, 313, 347, 383, 421, 461, 503, 547, 593, 641, 691, 743, 797, 853, 911, 971, 1031]
Train/validation split is fixed across all runs; only the fine-tuning seed changes.


====================================================================================================
RUN 1/30 | SEED 11
====================================================================================================

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:01<00:00, 339.04it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.57      1405     0.8888     0.8934    +0.0046
Animal                                    0.82       184     0.9389     0.9408    +0.0020
Animate                                   0.23        13     0.6957     0.7500    +0.0543
Artefact                                  0.36       503     0.8837     0.8854    +0.0017
Body_Part                                 0.16        74     0.9028     0.9189    +0.0161
Comestible                                0.53       157     0.9524     0.9554    +0.0030
Communication                             0.39       534     0.7870     0.7959    +0.0089
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.70       340     0.8567     0.8709    +0.0141
Elongated                                 0.50       168     0.7654     0.7654    +0.0000
Eventive                                  0.53      1068     0.8877     0.8891    +0.0014
Feminine                                  0.41       204     0.9479     0.9557    +0.0078
Fluid                                     0.34        19     0.8947     0.9231    +0.0283
Garment                                   0.54        17     0.9143     0.9412    +0.0269
Inanimate                                 0.47      1511     0.9320     0.9325    +0.0005
Internal_Control                          0.11        21     0.3200     0.4138    +0.0938
Language                                  0.67         5     0.9091     1.0000    +0.0909
Location                                  0.55      1209     0.9203     0.9213    +0.0011
Machine                                   0.59       180     0.8746     0.8783    +0.0037
Masculine                                 0.30       671     0.9302     0.9368    +0.0065
Natural                                   0.68        79     0.8442     0.8667    +0.0225
Natural_Force                             0.32        35     0.7812     0.8286    +0.0473
Non_Rigid                                 0.67       335     0.7930     0.8031    +0.0101
Organisation                              0.38      1086     0.8957     0.8974    +0.0016
Plant                                     0.34        15     0.8966     0.9333    +0.0368
Point_in_Time                             0.75       336     0.8656     0.8746    +0.0090
Pointy                                    0.23        20     0.3077     0.7143    +0.4066
Question                                  0.48        33     0.8333     0.8525    +0.0191
Rigid                                     0.32       603     0.8707     0.8830    +0.0123
Solid                                     0.60      1409     0.8800     0.8858    +0.0058
Sound                                     0.76        42     0.7848     0.8267    +0.0419
Statement                                 0.49       264     0.7639     0.7648    +0.0009
Substance                                 0.37       217     0.8690     0.8795    +0.0105
Time                                      0.11        16     0.1176     0.4615    +0.3439
Unspecified_Gender_or_Neuter              0.62       677     0.8796     0.8823    +0.0027
Vehicle                                   0.44       100     0.9543     0.9596    +0.0053
Web_Location                              0.90        55     0.8545     0.8952    +0.0407

VALIDATION @ 0.5
direct_f1_macro: 0.8214611949371642
direct_f1_micro: 0.8849583609698578
direct_precision_macro: 0.8862237730057522
direct_precision_micro: 0.8902728351126927
direct_recall_macro: 0.8033349291678518
direct_recall_micro: 0.8797069597069597
f1_macro: 0.8822094726616773
f1_micro: 0.9323118443390067
precision_macro: 0.9021315974944335
precision_micro: 0.9403207867470584
recall_macro: 0.8700603089458903
recall_micro: 0.9244381779990216

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8588318415913021
direct_f1_micro: 0.8902061855670103
direct_precision_macro: 0.8791988951432618
direct_precision_micro: 0.8948186528497409
direct_recall_macro: 0.8471476527577163
direct_recall_micro: 0.8856410256410256
f1_macro: 0.9025612686841494
f1_micro: 0.9341578122278349
precision_macro: 0.9149117529587143
precision_micro: 0.942558364334046
recall_macro: 0.8918080596824411
recall_micro: 0.9259056772077231

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7557739012504369
direct_f1_micro: 0.8580050102482351
direct_precision_macro: 0.7763058458332555
direct_precision_micro: 0.8622267994049663
direct_recall_macro: 0.7420445520641433
direct_recall_micro: 0.8538243626062323
f1_macro: 0.8487524077519101
f1_micro: 0.9129267697495397
precision_macro: 0.8725693945759225
precision_micro: 0.9183254485405695
recall_macro: 0.8318010864376343
recall_micro: 0.9075911958008028

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7760127140501454
direct_f1_micro: 0.8590496834179454
direct_precision_macro: 0.8053927045943666
direct_precision_micro: 0.864920744314266
direct_recall_macro: 0.7639705923218858
direct_recall_micro: 0.853257790368272
f1_macro: 0.8478386557133842
f1_micro: 0.9108597889487511
precision_macro: 0.8778955406697901
precision_micro: 0.9195397132197599
recall_macro: 0.8271899756962149
recall_micro: 0.9023421992854307

====================================================================================================
RUN 2/30 | SEED 23
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 499.49it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.32      1405     0.8884     0.8934    +0.0050
Animal                                    0.66       184     0.9359     0.9438    +0.0079
Animate                                   0.50        13     0.8182     0.8182    +0.0000
Artefact                                  0.57       503     0.8990     0.9016    +0.0026
Body_Part                                 0.71        74     0.8889     0.9014    +0.0125
Comestible                                0.49       157     0.9554     0.9587    +0.0033
Communication                             0.37       534     0.7950     0.8011    +0.0061
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.32       340     0.8430     0.8592    +0.0161
Elongated                                 0.51       168     0.7649     0.7697    +0.0048
Eventive                                  0.24      1068     0.8710     0.8736    +0.0026
Feminine                                  0.50       204     0.9363     0.9363    +0.0000
Fluid                                     0.50        19     0.8889     0.8889    +0.0000
Garment                                   0.23        17     0.9143     0.9189    +0.0046
Inanimate                                 0.55      1511     0.9330     0.9335    +0.0004
Internal_Control                          0.48        21     0.3704     0.4286    +0.0582
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.64      1209     0.9249     0.9265    +0.0016
Machine                                   0.59       180     0.8588     0.8653    +0.0066
Masculine                                 0.24       671     0.9284     0.9351    +0.0067
Natural                                   0.44        79     0.8831     0.8974    +0.0143
Natural_Force                             0.20        35     0.7692     0.8493    +0.0801
Non_Rigid                                 0.59       335     0.7926     0.7959    +0.0033
Organisation                              0.36      1086     0.8827     0.8886    +0.0059
Plant                                     0.32        15     0.8276     0.8667    +0.0391
Point_in_Time                             0.36       336     0.8593     0.8692    +0.0099
Pointy                                    0.20        20     0.3704     0.6383    +0.2679
Question                                  0.48        33     0.8333     0.8710    +0.0376
Rigid                                     0.35       603     0.8783     0.8871    +0.0088
Solid                                     0.52      1409     0.8897     0.8914    +0.0017
Sound                                     0.73        42     0.7750     0.8052    +0.0302
Statement                                 0.72       264     0.7556     0.7807    +0.0251
Substance                                 0.54       217     0.8721     0.8770    +0.0049
Time                                      0.07        16     0.0000     0.4681    +0.4681
Unspecified_Gender_or_Neuter              0.54       677     0.8828     0.8859    +0.0031
Vehicle                                   0.65       100     0.9697     0.9746    +0.0049
Web_Location                              0.89        55     0.8571     0.9126    +0.0555

VALIDATION @ 0.5
direct_f1_macro: 0.8246795536392479
direct_f1_micro: 0.884519074974223
direct_precision_macro: 0.8619371942520773
direct_precision_micro: 0.8892344143343699
direct_recall_macro: 0.8054023965656497
direct_recall_micro: 0.8798534798534798
f1_macro: 0.8827354691540124
f1_micro: 0.9315842875779099
precision_macro: 0.9027401272452804
precision_micro: 0.9386044337996904
recall_macro: 0.8695046591897431
recall_micro: 0.9246683739533278

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8571034581561853
direct_f1_micro: 0.889627465303141
direct_precision_macro: 0.8761355694328138
direct_precision_micro: 0.8870356882738529
direct_recall_macro: 0.8531106067804822
direct_recall_micro: 0.8922344322344322
f1_macro: 0.8985606046146312
f1_micro: 0.9346856920257968
precision_macro: 0.9058123682793491
precision_micro: 0.9373227617338966
recall_macro: 0.8940223215810864
recall_micro: 0.9320634189854113

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7650682107335396
direct_f1_micro: 0.8598344276334571
direct_precision_macro: 0.8366084455136402
direct_precision_micro: 0.8665132336018412
direct_recall_macro: 0.7432436251891008
direct_recall_micro: 0.853257790368272
f1_macro: 0.8439640700228337
f1_micro: 0.9119327656357694
precision_macro: 0.8762244882110133
precision_micro: 0.9193938850533488
recall_macro: 0.825281211033602
recall_micro: 0.9045917692205901

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7657825899728645
direct_f1_micro: 0.85770930100827
direct_precision_macro: 0.8174740306434675
direct_precision_micro: 0.8575150073621022
direct_recall_macro: 0.7549801188764423
direct_recall_micro: 0.8579036827195468
f1_macro: 0.840702432396775
f1_micro: 0.912149449965692
precision_macro: 0.8743860626473366
precision_micro: 0.9154522836324862
recall_macro: 0.8217244337722652
recall_micro: 0.9088703630188346

====================================================================================================
RUN 3/30 | SEED 37
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 603.52it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.71      1405     0.8899     0.8928    +0.0029
Animal                                    0.50       184     0.9451     0.9451    +0.0000
Animate                                   0.35        13     0.7826     0.8333    +0.0507
Artefact                                  0.39       503     0.8934     0.8989    +0.0055
Body_Part                                 0.13        74     0.9103     0.9481    +0.0377
Comestible                                0.79       157     0.9585     0.9613    +0.0028
Communication                             0.40       534     0.8019     0.8041    +0.0022
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.51       340     0.8550     0.8559    +0.0008
Elongated                                 0.65       168     0.7531     0.7667    +0.0136
Eventive                                  0.59      1068     0.8784     0.8833    +0.0049
Feminine                                  0.84       204     0.9264     0.9310    +0.0047
Fluid                                     0.81        19     0.8718     0.9189    +0.0471
Garment                                   0.31        17     0.9412     0.9714    +0.0303
Inanimate                                 0.68      1511     0.9344     0.9378    +0.0034
Internal_Control                          0.07        21     0.3846     0.4706    +0.0860
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.66      1209     0.9202     0.9218    +0.0016
Machine                                   0.58       180     0.8678     0.8772    +0.0094
Masculine                                 0.26       671     0.9292     0.9349    +0.0057
Natural                                   0.50        79     0.8974     0.8974    +0.0000
Natural_Force                             0.75        35     0.8286     0.8750    +0.0464
Non_Rigid                                 0.50       335     0.8065     0.8065    +0.0000
Organisation                              0.46      1086     0.8935     0.8953    +0.0017
Plant                                     0.46        15     0.8571     0.9032    +0.0461
Point_in_Time                             0.70       336     0.8588     0.8668    +0.0079
Pointy                                    0.24        20     0.3571     0.6977    +0.3405
Question                                  0.11        33     0.8333     0.8529    +0.0196
Rigid                                     0.43       603     0.8749     0.8780    +0.0032
Solid                                     0.54      1409     0.8875     0.8887    +0.0012
Sound                                     0.51        42     0.8000     0.8101    +0.0101
Statement                                 0.31       264     0.7665     0.7742    +0.0077
Substance                                 0.43       217     0.8782     0.8934    +0.0153
Time                                      0.14        16     0.2222     0.5143    +0.2921
Unspecified_Gender_or_Neuter              0.62       677     0.8753     0.8806    +0.0053
Vehicle                                   0.53       100     0.9600     0.9697    +0.0097
Web_Location                              0.84        55     0.8545     0.9126    +0.0581

VALIDATION @ 0.5
direct_f1_macro: 0.8350125634904585
direct_f1_micro: 0.8866762547479441
direct_precision_macro: 0.8922460624915163
direct_precision_micro: 0.8927006757258483
direct_recall_macro: 0.8150616194379721
direct_recall_micro: 0.8807326007326007
f1_macro: 0.8864470743779485
f1_micro: 0.9331360345853099
precision_macro: 0.9036181152883018
precision_micro: 0.940985429223477
recall_macro: 0.8742168079795395
recall_micro: 0.9254165108048226

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8667433297796534
direct_f1_micro: 0.8909433822713657
direct_precision_macro: 0.8804476440508893
direct_precision_micro: 0.8995594055709059
direct_recall_macro: 0.8573374530614504
direct_recall_micro: 0.8824908424908425
f1_macro: 0.9042370039795258
f1_micro: 0.9347348831799479
precision_macro: 0.9160584287700123
precision_micro: 0.9446926060891031
recall_macro: 0.894827509222047
recall_micro: 0.9249848933904986

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.769639188535851
direct_f1_micro: 0.862139683263074
direct_precision_macro: 0.8297584091106298
direct_precision_micro: 0.8668805132317562
direct_recall_macro: 0.745006334596528
direct_recall_micro: 0.8574504249291784
f1_macro: 0.8473241408604293
f1_micro: 0.9152910898118566
precision_macro: 0.8794062544126924
precision_micro: 0.9208071068255882
recall_macro: 0.8262206640439115
recall_micro: 0.9098407657359623

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.772970871992056
direct_f1_micro: 0.8601154747613331
direct_precision_macro: 0.8047049135195068
direct_precision_micro: 0.867904937701892
direct_recall_macro: 0.758564302035005
direct_recall_micro: 0.8524645892351275
f1_macro: 0.8447444937274746
f1_micro: 0.9130183306638192
precision_macro: 0.8796427908667687
precision_micro: 0.9210089313765092
recall_macro: 0.8233443657340392
recall_micro: 0.9051651890079838

====================================================================================================
RUN 4/30 | SEED 53
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 973.53it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.66      1405     0.8921     0.8936    +0.0015
Animal                                    0.20       184     0.9256     0.9344    +0.0088
Animate                                   0.40        13     0.7619     0.8182    +0.0563
Artefact                                  0.48       503     0.8916     0.8941    +0.0025
Body_Part                                 0.17        74     0.8857     0.9272    +0.0414
Comestible                                0.64       157     0.9524     0.9613    +0.0089
Communication                             0.48       534     0.8049     0.8075    +0.0026
Currency                                  0.55        45     0.9890     1.0000    +0.0110
Duration                                  0.88       340     0.8353     0.8495    +0.0142
Elongated                                 0.42       168     0.7421     0.7599    +0.0177
Eventive                                  0.65      1068     0.8766     0.8802    +0.0036
Feminine                                  0.94       204     0.9220     0.9246    +0.0027
Fluid                                     0.09        19     0.8889     0.9048    +0.0159
Garment                                   0.69        17     0.8824     0.9375    +0.0551
Inanimate                                 0.47      1511     0.9300     0.9318    +0.0018
Internal_Control                          0.12        21     0.3200     0.5161    +0.1961
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.49      1209     0.9156     0.9161    +0.0005
Machine                                   0.57       180     0.8889     0.8928    +0.0039
Masculine                                 0.62       671     0.9323     0.9338    +0.0015
Natural                                   0.53        79     0.8645     0.8758    +0.0113
Natural_Force                             0.33        35     0.7941     0.8451    +0.0510
Non_Rigid                                 0.66       335     0.7970     0.8086    +0.0116
Organisation                              0.43      1086     0.8931     0.8948    +0.0017
Plant                                     0.50        15     0.8966     0.8966    +0.0000
Point_in_Time                             0.91       336     0.8483     0.8608    +0.0125
Pointy                                    0.39        20     0.6486     0.7273    +0.0786
Question                                  0.18        33     0.8387     0.8788    +0.0401
Rigid                                     0.46       603     0.8767     0.8829    +0.0061
Solid                                     0.43      1409     0.8856     0.8882    +0.0026
Sound                                     0.50        42     0.7901     0.7901    +0.0000
Statement                                 0.57       264     0.7713     0.7776    +0.0063
Substance                                 0.35       217     0.8767     0.8800    +0.0033
Time                                      0.15        16     0.1176     0.5333    +0.4157
Unspecified_Gender_or_Neuter              0.42       677     0.8802     0.8866    +0.0064
Vehicle                                   0.50       100     0.9645     0.9645    +0.0000
Web_Location                              0.79        55     0.8496     0.9231    +0.0735

VALIDATION @ 0.5
direct_f1_macro: 0.8332572408196601
direct_f1_micro: 0.8845898739774486
direct_precision_macro: 0.8934458692482515
direct_precision_micro: 0.8899021352313167
direct_recall_macro: 0.8140198308004887
direct_recall_micro: 0.8793406593406593
f1_macro: 0.8891653410952911
f1_micro: 0.9312992611731236
precision_macro: 0.9025221428890214
precision_micro: 0.9396602226127709
recall_macro: 0.8770827109294863
recall_micro: 0.9230857767674733

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8647924761907765
direct_f1_micro: 0.889546497003773
direct_precision_macro: 0.8883317390175162
direct_precision_micro: 0.8983861326957562
direct_recall_macro: 0.8491299378969951
direct_recall_micro: 0.8808791208791209
f1_macro: 0.8999508064979812
f1_micro: 0.9312981546483345
precision_macro: 0.9124655031965138
precision_micro: 0.9429304547867634
recall_macro: 0.8896332940452909
recall_micro: 0.9199493568900526

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7681208659226488
direct_f1_micro: 0.8586256059309951
direct_precision_macro: 0.7981191352353578
direct_precision_micro: 0.8642939150401837
direct_recall_macro: 0.7522704476646929
direct_recall_micro: 0.8530311614730878
f1_macro: 0.8495793876162733
f1_micro: 0.911123929538093
precision_macro: 0.8740380329260078
precision_micro: 0.916573673168772
recall_macro: 0.8342511608916681
recall_micro: 0.9057386087953774

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7664556790764663
direct_f1_micro: 0.8552450755840586
direct_precision_macro: 0.790268804116644
direct_precision_micro: 0.8644519041555736
direct_recall_macro: 0.7595796115525099
direct_recall_micro: 0.8462322946175638
f1_macro: 0.8375110193100619
f1_micro: 0.9054466813814015
precision_macro: 0.8638078975658035
precision_micro: 0.9154269227301416
recall_macro: 0.823062456292401
recall_micro: 0.8956817079087821

====================================================================================================
RUN 5/30 | SEED 71
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 974.88it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.35      1405     0.8907     0.8940    +0.0033
Animal                                    0.34       184     0.9363     0.9421    +0.0059
Animate                                   0.22        13     0.6316     0.8333    +0.2018
Artefact                                  0.47       503     0.8856     0.8874    +0.0018
Body_Part                                 0.21        74     0.9078     0.9474    +0.0396
Comestible                                0.49       157     0.9487     0.9521    +0.0034
Communication                             0.54       534     0.7936     0.7969    +0.0033
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.82       340     0.8420     0.8629    +0.0209
Elongated                                 0.53       168     0.7640     0.7736    +0.0096
Eventive                                  0.41      1068     0.8794     0.8821    +0.0028
Feminine                                  0.30       204     0.9310     0.9372    +0.0062
Fluid                                     0.63        19     0.8421     0.8889    +0.0468
Garment                                   0.50        17     0.9375     0.9375    +0.0000
Inanimate                                 0.59      1511     0.9356     0.9368    +0.0012
Internal_Control                          0.06        21     0.3846     0.4516    +0.0670
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.60      1209     0.9203     0.9228    +0.0025
Machine                                   0.45       180     0.8820     0.8883    +0.0062
Masculine                                 0.80       671     0.9312     0.9376    +0.0065
Natural                                   0.59        79     0.8742     0.8919    +0.0177
Natural_Force                             0.42        35     0.8657     0.8986    +0.0329
Non_Rigid                                 0.36       335     0.7910     0.7931    +0.0021
Organisation                              0.29      1086     0.8914     0.8984    +0.0070
Plant                                     0.30        15     0.8276     0.8667    +0.0391
Point_in_Time                             0.66       336     0.8701     0.8744    +0.0043
Pointy                                    0.32        20     0.6486     0.7619    +0.1133
Question                                  0.09        33     0.8254     0.8696    +0.0442
Rigid                                     0.50       603     0.8811     0.8811    +0.0000
Solid                                     0.39      1409     0.8897     0.8913    +0.0016
Sound                                     0.57        42     0.7848     0.7895    +0.0047
Statement                                 0.40       264     0.7592     0.7767    +0.0176
Substance                                 0.40       217     0.8834     0.8869    +0.0035
Time                                      0.15        16     0.0000     0.5714    +0.5714
Unspecified_Gender_or_Neuter              0.42       677     0.8757     0.8813    +0.0056
Vehicle                                   0.81       100     0.9600     0.9694    +0.0094
Web_Location                              0.92        55     0.8807     0.9000    +0.0193

VALIDATION @ 0.5
direct_f1_macro: 0.8311451694234028
direct_f1_micro: 0.886508374746917
direct_precision_macro: 0.8705003348830995
direct_precision_micro: 0.8909359970403256
direct_recall_macro: 0.8111675399063256
direct_recall_micro: 0.8821245421245422
f1_macro: 0.8929210408980265
f1_micro: 0.9335111394570149
precision_macro: 0.9063246986111676
precision_micro: 0.9405596448183199
recall_macro: 0.8807446929055461
recall_micro: 0.9265674905763531

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8668768608393259
direct_f1_micro: 0.8914453196556146
direct_precision_macro: 0.8847806123588645
direct_precision_micro: 0.8916086478563576
direct_recall_macro: 0.8553985914684961
direct_recall_micro: 0.8912820512820513
f1_macro: 0.9040377577502515
f1_micro: 0.9358798270851707
precision_macro: 0.9155802468482619
precision_micro: 0.9404893357354565
recall_macro: 0.8945976890716741
recall_micro: 0.9313152821339165

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7710488021011459
direct_f1_micro: 0.8583319081010204
direct_precision_macro: 0.8010733693580431
direct_precision_micro: 0.8636989444699403
direct_recall_macro: 0.7541759967352355
direct_recall_micro: 0.8530311614730878
f1_macro: 0.8525062534271897
f1_micro: 0.9129420132020537
precision_macro: 0.8774602258064158
precision_micro: 0.9200788459815429
recall_macro: 0.8366097691538454
recall_micro: 0.9059150456530369

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.772363732820911
direct_f1_micro: 0.8562874251497006
direct_precision_macro: 0.7900817427429742
direct_precision_micro: 0.8537794299876085
direct_recall_macro: 0.7676619443980356
direct_recall_micro: 0.8588101983002833
f1_macro: 0.844573592549889
f1_micro: 0.9111924824634932
precision_macro: 0.8651121090055165
precision_micro: 0.9113533071526276
recall_macro: 0.8335217511989048
recall_micro: 0.9110317145251643

====================================================================================================
RUN 6/30 | SEED 89
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 932.20it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.37      1405     0.8908     0.8945    +0.0037
Animal                                    0.50       184     0.9448     0.9448    +0.0000
Animate                                   0.12        13     0.8182     0.8462    +0.0280
Artefact                                  0.62       503     0.8878     0.8927    +0.0050
Body_Part                                 0.19        74     0.9028     0.9079    +0.0051
Comestible                                0.26       157     0.9585     0.9625    +0.0040
Communication                             0.40       534     0.8037     0.8077    +0.0039
Currency                                  0.50        45     0.9890     0.9890    +0.0000
Duration                                  0.87       340     0.8547     0.8638    +0.0091
Elongated                                 0.66       168     0.7702     0.7752    +0.0051
Eventive                                  0.56      1068     0.8717     0.8771    +0.0054
Feminine                                  0.14       204     0.9363     0.9426    +0.0063
Fluid                                     0.70        19     0.8500     0.8889    +0.0389
Garment                                   0.24        17     0.9375     0.9444    +0.0069
Inanimate                                 0.62      1511     0.9358     0.9368    +0.0010
Internal_Control                          0.27        21     0.3200     0.4286    +0.1086
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.52      1209     0.9215     0.9230    +0.0015
Machine                                   0.32       180     0.8851     0.8914    +0.0063
Masculine                                 0.26       671     0.9352     0.9365    +0.0012
Natural                                   0.38        79     0.8758     0.8903    +0.0145
Natural_Force                             0.50        35     0.8358     0.8358    +0.0000
Non_Rigid                                 0.54       335     0.7811     0.7922    +0.0111
Organisation                              0.35      1086     0.8941     0.8962    +0.0021
Plant                                     0.37        15     0.8571     0.8966    +0.0394
Point_in_Time                             0.28       336     0.8652     0.8777    +0.0125
Pointy                                    0.28        20     0.2857     0.6667    +0.3810
Question                                  0.52        33     0.8387     0.8667    +0.0280
Rigid                                     0.45       603     0.8791     0.8833    +0.0042
Solid                                     0.41      1409     0.8898     0.8934    +0.0036
Sound                                     0.53        42     0.7750     0.7949    +0.0199
Statement                                 0.75       264     0.7594     0.7718    +0.0124
Substance                                 0.47       217     0.8995     0.9005    +0.0009
Time                                      0.14        16     0.1176     0.5882    +0.4706
Unspecified_Gender_or_Neuter              0.30       677     0.8822     0.8875    +0.0052
Vehicle                                   0.24       100     0.9548     0.9604    +0.0056
Web_Location                              0.82        55     0.8496     0.8932    +0.0436

VALIDATION @ 0.5
direct_f1_macro: 0.8284864427635021
direct_f1_micro: 0.8871626845341088
direct_precision_macro: 0.8907390854111435
direct_precision_micro: 0.8916598830755569
direct_recall_macro: 0.8097332584284408
direct_recall_micro: 0.8827106227106227
f1_macro: 0.8848380774697417
f1_micro: 0.9341374661118924
precision_macro: 0.900634842969484
precision_micro: 0.9413569424964937
recall_macro: 0.8732955819010525
recall_micro: 0.9270278824849654

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8634808924294364
direct_f1_micro: 0.8923494064194636
direct_precision_macro: 0.8840865980236732
direct_precision_micro: 0.8926110540976396
direct_recall_macro: 0.8534587654977506
direct_recall_micro: 0.892087912087912
f1_macro: 0.9007153276855275
f1_micro: 0.9371552346570398
precision_macro: 0.9127318006272648
precision_micro: 0.9406325187697481
recall_macro: 0.8913375450335614
recall_micro: 0.9337035651598423

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.756597016061577
direct_f1_micro: 0.8615157032316796
direct_precision_macro: 0.783899339936662
direct_precision_micro: 0.865158267626557
direct_recall_macro: 0.7432502161386221
direct_recall_micro: 0.8579036827195468
f1_macro: 0.8428272891069181
f1_micro: 0.9147685688305351
precision_macro: 0.8636154384174707
precision_micro: 0.9199304130609331
recall_macro: 0.8293571011980182
recall_micro: 0.9096643288783027

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7632601364448305
direct_f1_micro: 0.8594919482875936
direct_precision_macro: 0.8106704293173267
direct_precision_micro: 0.8601747815230961
direct_recall_macro: 0.7545007340876612
direct_recall_micro: 0.8588101983002833
f1_macro: 0.8409285187766161
f1_micro: 0.9144450098453506
precision_macro: 0.8714942817226418
precision_micro: 0.9173473011363636
recall_macro: 0.8242140835615466
recall_micro: 0.911561025098143

====================================================================================================
RUN 7/30 | SEED 107
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 972.65it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.70      1405     0.8905     0.8929    +0.0024
Animal                                    0.50       184     0.9444     0.9444    +0.0000
Animate                                   0.46        13     0.8182     0.8696    +0.0514
Artefact                                  0.36       503     0.8864     0.8952    +0.0088
Body_Part                                 0.17        74     0.8936     0.9020    +0.0083
Comestible                                0.48       157     0.9490     0.9524    +0.0033
Communication                             0.52       534     0.8061     0.8111    +0.0050
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.30       340     0.8452     0.8511    +0.0059
Elongated                                 0.59       168     0.7768     0.7848    +0.0081
Eventive                                  0.49      1068     0.8765     0.8771    +0.0006
Feminine                                  0.39       204     0.9369     0.9423    +0.0054
Fluid                                     0.17        19     0.8205     0.8780    +0.0575
Garment                                   0.16        17     0.9143     0.9444    +0.0302
Inanimate                                 0.68      1511     0.9307     0.9315    +0.0007
Internal_Control                          0.07        21     0.3200     0.4571    +0.1371
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.48      1209     0.9177     0.9183    +0.0006
Machine                                   0.61       180     0.8725     0.8761    +0.0036
Masculine                                 0.29       671     0.9297     0.9339    +0.0042
Natural                                   0.24        79     0.8742     0.8931    +0.0189
Natural_Force                             0.26        35     0.8182     0.8611    +0.0429
Non_Rigid                                 0.62       335     0.7923     0.8000    +0.0077
Organisation                              0.38      1086     0.8935     0.8936    +0.0001
Plant                                     0.43        15     0.8571     0.8966    +0.0394
Point_in_Time                             0.81       336     0.8619     0.8719    +0.0100
Pointy                                    0.13        20     0.2857     0.6809    +0.3951
Question                                  0.67        33     0.8667     0.8814    +0.0147
Rigid                                     0.39       603     0.8763     0.8841    +0.0078
Solid                                     0.44      1409     0.8915     0.8925    +0.0011
Sound                                     0.48        42     0.7792     0.8250    +0.0458
Statement                                 0.68       264     0.7495     0.7673    +0.0178
Substance                                 0.38       217     0.8796     0.8904    +0.0108
Time                                      0.24        16     0.0000     0.5000    +0.5000
Unspecified_Gender_or_Neuter              0.46       677     0.8824     0.8837    +0.0013
Vehicle                                   0.56       100     0.9552     0.9648    +0.0096
Web_Location                              0.94        55     0.8468     0.9126    +0.0658

VALIDATION @ 0.5
direct_f1_macro: 0.8226797617623152
direct_f1_micro: 0.8857048141736343
direct_precision_macro: 0.8636201870974792
direct_precision_micro: 0.8906585673012816
direct_recall_macro: 0.8033243989569758
direct_recall_micro: 0.8808058608058608
f1_macro: 0.8826046437023658
f1_micro: 0.9324422279567398
precision_macro: 0.899920832899417
precision_micro: 0.9396347699050401
recall_macro: 0.8698510351183241
recall_micro: 0.9253589618162461

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8638178032075696
direct_f1_micro: 0.8902931883312514
direct_precision_macro: 0.8771420817336282
direct_precision_micro: 0.8929834905660378
direct_recall_macro: 0.8561715726515314
direct_recall_micro: 0.8876190476190476
f1_macro: 0.9023103898429449
f1_micro: 0.9347675225537821
precision_macro: 0.9092648256118839
precision_micro: 0.9393578381519686
recall_macro: 0.8983872396531665
recall_micro: 0.9302218513509625

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7816564836978064
direct_f1_micro: 0.8630308550609131
direct_precision_macro: 0.8271771321759616
direct_precision_micro: 0.8671776684589864
direct_recall_macro: 0.7653915428935132
direct_recall_micro: 0.8589235127478754
f1_macro: 0.8570527531506642
f1_micro: 0.9138367292582235
precision_macro: 0.8750610249492299
precision_micro: 0.9197158557834071
recall_macro: 0.844612304325151
recall_micro: 0.9080322879449517

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7888531868702598
direct_f1_micro: 0.8593847728435776
direct_precision_macro: 0.8041281882752014
direct_precision_micro: 0.8624743209312943
direct_recall_macro: 0.7830622983796395
direct_recall_micro: 0.8563172804532578
f1_macro: 0.8604339739912871
f1_micro: 0.9119439703894147
precision_macro: 0.8821168762201469
precision_micro: 0.9164736279401283
recall_macro: 0.8464769836930002
recall_micro: 0.9074588681575582

====================================================================================================
RUN 8/30 | SEED 127
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 991.38it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.75      1405     0.8905     0.8960    +0.0055
Animal                                    0.58       184     0.9392     0.9418    +0.0026
Animate                                   0.24        13     0.7619     0.8696    +0.1077
Artefact                                  0.51       503     0.8965     0.8981    +0.0016
Body_Part                                 0.28        74     0.9014     0.9178    +0.0164
Comestible                                0.33       157     0.9590     0.9625    +0.0035
Communication                             0.37       534     0.7948     0.8033    +0.0085
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.74       340     0.8493     0.8545    +0.0053
Elongated                                 0.59       168     0.7750     0.7767    +0.0017
Eventive                                  0.49      1068     0.8814     0.8822    +0.0009
Feminine                                  0.50       204     0.9461     0.9461    +0.0000
Fluid                                     0.57        19     0.8780     0.9231    +0.0450
Garment                                   0.30        17     0.9091     0.9444    +0.0354
Inanimate                                 0.37      1511     0.9343     0.9357    +0.0014
Internal_Control                          0.09        21     0.3846     0.4571    +0.0725
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.39      1209     0.9225     0.9234    +0.0009
Machine                                   0.20       180     0.8902     0.8949    +0.0047
Masculine                                 0.21       671     0.9285     0.9327    +0.0042
Natural                                   0.51        79     0.8846     0.8903    +0.0057
Natural_Force                             0.34        35     0.8358     0.8406    +0.0048
Non_Rigid                                 0.55       335     0.8083     0.8138    +0.0056
Organisation                              0.63      1086     0.8921     0.8952    +0.0032
Plant                                     0.33        15     0.8148     0.9333    +0.1185
Point_in_Time                             0.38       336     0.8754     0.8808    +0.0054
Pointy                                    0.16        20     0.3077     0.6809    +0.3732
Question                                  0.06        33     0.8525     0.8824    +0.0299
Rigid                                     0.34       603     0.8676     0.8862    +0.0185
Solid                                     0.45      1409     0.8916     0.8946    +0.0031
Sound                                     0.75        42     0.7470     0.8108    +0.0638
Statement                                 0.33       264     0.7613     0.7631    +0.0018
Substance                                 0.28       217     0.8716     0.8802    +0.0086
Time                                      0.11        16     0.0000     0.5455    +0.5455
Unspecified_Gender_or_Neuter              0.38       677     0.8789     0.8861    +0.0072
Vehicle                                   0.50       100     0.9648     0.9648    +0.0000
Web_Location                              0.77        55     0.8727     0.9143    +0.0416

VALIDATION @ 0.5
direct_f1_macro: 0.8261892605701199
direct_f1_micro: 0.8876922509497289
direct_precision_macro: 0.86956191454334
direct_precision_micro: 0.8938572383569784
direct_recall_macro: 0.8064600913495217
direct_recall_micro: 0.8816117216117216
f1_macro: 0.8849900445922804
f1_micro: 0.9335578067400075
precision_macro: 0.9062153606832996
precision_micro: 0.9418138159243316
recall_macro: 0.8714038596832357
recall_micro: 0.9254452852991109

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8681878565330379
direct_f1_micro: 0.8926466820394569
direct_precision_macro: 0.8740510878912175
direct_precision_micro: 0.8919610855094726
direct_recall_macro: 0.8670712027689502
direct_recall_micro: 0.8933333333333333
f1_macro: 0.9054793514850585
f1_micro: 0.9375865650969529
precision_macro: 0.9077043314924543
precision_micro: 0.9402181776093058
recall_macro: 0.9059411655489311
recall_micro: 0.9349696429085259

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7541213507858079
direct_f1_micro: 0.8581338488656394
direct_precision_macro: 0.8061418117990666
direct_precision_micro: 0.8612188997945674
direct_recall_macro: 0.7358832028073378
direct_recall_micro: 0.855070821529745
f1_macro: 0.8450060991806535
f1_micro: 0.913550729450311
precision_macro: 0.8733839058868187
precision_micro: 0.9170222222222222
recall_macro: 0.8273010858752139
recall_micro: 0.9101054210224516

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7659180607606392
direct_f1_micro: 0.8574172409897187
direct_precision_macro: 0.7888048883472056
direct_precision_micro: 0.8549059366903233
direct_recall_macro: 0.7616259809904817
direct_recall_micro: 0.859943342776204
f1_macro: 0.8407268782824618
f1_micro: 0.9138768660012366
precision_macro: 0.868709048162011
precision_micro: 0.9150488656967232
recall_macro: 0.827019380664986
recall_micro: 0.9127078646729302

====================================================================================================
RUN 9/30 | SEED 149
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1035.09it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.63      1405     0.8909     0.8938    +0.0028
Animal                                    0.78       184     0.9389     0.9468    +0.0079
Animate                                   0.28        13     0.7000     0.8696    +0.1696
Artefact                                  0.35       503     0.8931     0.8957    +0.0025
Body_Part                                 0.17        74     0.9091     0.9281    +0.0190
Comestible                                0.50       157     0.9524     0.9524    +0.0000
Communication                             0.49       534     0.7939     0.7985    +0.0046
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.26       340     0.8468     0.8543    +0.0075
Elongated                                 0.33       168     0.7438     0.7580    +0.0143
Eventive                                  0.52      1068     0.8861     0.8876    +0.0016
Feminine                                  0.71       204     0.9317     0.9356    +0.0039
Fluid                                     0.18        19     0.8947     0.9231    +0.0283
Garment                                   0.17        17     0.9091     0.9444    +0.0354
Inanimate                                 0.49      1511     0.9364     0.9371    +0.0007
Internal_Control                          0.17        21     0.3846     0.4516    +0.0670
Language                                  0.49         5     0.8000     0.9091    +0.1091
Location                                  0.60      1209     0.9168     0.9192    +0.0024
Machine                                   0.44       180     0.8646     0.8676    +0.0031
Masculine                                 0.33       671     0.9293     0.9359    +0.0066
Natural                                   0.49        79     0.8774     0.8790    +0.0016
Natural_Force                             0.18        35     0.8000     0.8493    +0.0493
Non_Rigid                                 0.45       335     0.8030     0.8058    +0.0029
Organisation                              0.59      1086     0.8927     0.8938    +0.0011
Plant                                     0.33        15     0.8571     0.9333    +0.0762
Point_in_Time                             0.70       336     0.8723     0.8802    +0.0079
Pointy                                    0.15        20     0.2759     0.6275    +0.3516
Question                                  0.10        33     0.8387     0.8657    +0.0270
Rigid                                     0.44       603     0.8820     0.8845    +0.0025
Solid                                     0.56      1409     0.8928     0.8940    +0.0012
Sound                                     0.61        42     0.7500     0.8000    +0.0500
Statement                                 0.29       264     0.7742     0.7818    +0.0077
Substance                                 0.39       217     0.8782     0.8879    +0.0097
Time                                      0.17        16     0.3158     0.5294    +0.2136
Unspecified_Gender_or_Neuter              0.74       677     0.8815     0.8872    +0.0058
Vehicle                                   0.65       100     0.9596     0.9694    +0.0098
Web_Location                              0.65        55     0.8649     0.9057    +0.0408

VALIDATION @ 0.5
direct_f1_macro: 0.8253529968756825
direct_f1_micro: 0.8875547861957203
direct_precision_macro: 0.8849546316543585
direct_precision_micro: 0.8924524109325235
direct_recall_macro: 0.8009056636266884
direct_recall_micro: 0.8827106227106227
f1_macro: 0.8780254905503246
f1_micro: 0.9338396208640705
precision_macro: 0.8950767199348406
precision_micro: 0.9407522046370379
recall_macro: 0.8643761439958052
recall_micro: 0.9270278824849654

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8616997045330311
direct_f1_micro: 0.8913147351784467
direct_precision_macro: 0.8668492808674012
direct_precision_micro: 0.8943719111897912
direct_recall_macro: 0.8647657483287207
direct_recall_micro: 0.8882783882783882
f1_macro: 0.8996007799261343
f1_micro: 0.9350709527946713
precision_macro: 0.8969644929351143
precision_micro: 0.9411490366397528
recall_macro: 0.9056269367063712
recall_micro: 0.929070871579432

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7677235345883279
direct_f1_micro: 0.8599430199430199
direct_precision_macro: 0.8136444812445264
direct_precision_micro: 0.8648710601719197
direct_recall_macro: 0.7461379879861688
direct_recall_micro: 0.855070821529745
f1_macro: 0.8433780058913491
f1_micro: 0.9140169081589633
precision_macro: 0.8734153332535141
precision_micro: 0.9196285050901947
recall_macro: 0.8247453666781859
recall_micro: 0.9084733800891006

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7660781402772222
direct_f1_micro: 0.857110391455031
direct_precision_macro: 0.7804540861853273
direct_precision_micro: 0.8595031905195989
direct_recall_macro: 0.7649024140846946
direct_recall_micro: 0.8547308781869688
f1_macro: 0.8398411589825786
f1_micro: 0.9124792013311148
precision_macro: 0.8542933012724608
precision_micro: 0.9179164434922336
recall_macro: 0.8326414653250376
recall_micro: 0.9071059944422389

====================================================================================================
RUN 10/30 | SEED 173
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1017.08it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.50      1405     0.8937     0.8937    +0.0000
Animal                                    0.85       184     0.9359     0.9408    +0.0049
Animate                                   0.26        13     0.6316     0.8182    +0.1866
Artefact                                  0.46       503     0.8916     0.8959    +0.0044
Body_Part                                 0.69        74     0.9028     0.9220    +0.0192
Comestible                                0.52       157     0.9595     0.9625    +0.0030
Communication                             0.40       534     0.8012     0.8049    +0.0038
Currency                                  0.40        45     0.9888     1.0000    +0.0112
Duration                                  0.77       340     0.8513     0.8602    +0.0090
Elongated                                 0.48       168     0.7679     0.7683    +0.0005
Eventive                                  0.49      1068     0.8727     0.8753    +0.0026
Feminine                                  0.84       204     0.9386     0.9403    +0.0017
Fluid                                     0.50        19     0.9231     0.9231    +0.0000
Garment                                   0.73        17     0.9091     0.9375    +0.0284
Inanimate                                 0.69      1511     0.9343     0.9352    +0.0009
Internal_Control                          0.23        21     0.3846     0.4444    +0.0598
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.57      1209     0.9149     0.9175    +0.0026
Machine                                   0.41       180     0.8739     0.8786    +0.0047
Masculine                                 0.31       671     0.9287     0.9339    +0.0052
Natural                                   0.52        79     0.8917     0.8974    +0.0057
Natural_Force                             0.23        35     0.8169     0.8649    +0.0480
Non_Rigid                                 0.69       335     0.7876     0.8041    +0.0165
Organisation                              0.27      1086     0.8914     0.8941    +0.0027
Plant                                     0.35        15     0.8462     0.9333    +0.0872
Point_in_Time                             0.59       336     0.8722     0.8737    +0.0015
Pointy                                    0.45        20     0.7027     0.8000    +0.0973
Question                                  0.51        33     0.8438     0.8571    +0.0134
Rigid                                     0.49       603     0.8771     0.8780    +0.0009
Solid                                     0.51      1409     0.8871     0.8877    +0.0006
Sound                                     0.81        42     0.7586     0.8267    +0.0680
Statement                                 0.35       264     0.7378     0.7469    +0.0091
Substance                                 0.52       217     0.8933     0.8953    +0.0020
Time                                      0.14        16     0.0000     0.6061    +0.6061
Unspecified_Gender_or_Neuter              0.31       677     0.8773     0.8813    +0.0040
Vehicle                                   0.51       100     0.9495     0.9543    +0.0048
Web_Location                              0.59        55     0.8868     0.9126    +0.0258

VALIDATION @ 0.5
direct_f1_macro: 0.833085151857625
direct_f1_micro: 0.8855648073097045
direct_precision_macro: 0.8693024498872327
direct_precision_micro: 0.8907500741179959
direct_recall_macro: 0.8171034464419366
direct_recall_micro: 0.8804395604395604
f1_macro: 0.8934634135219762
f1_micro: 0.9318330119049345
precision_macro: 0.9032542854943273
precision_micro: 0.9392282958199357
recall_macro: 0.8855770710129353
recall_micro: 0.9245532759761748

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8693555273166329
direct_f1_micro: 0.8893211009174312
direct_precision_macro: 0.8968190826463419
direct_precision_micro: 0.8909558823529412
direct_recall_macro: 0.8563375635770261
direct_recall_micro: 0.8876923076923077
f1_macro: 0.9055029738949004
f1_micro: 0.9348146435898177
precision_macro: 0.9136881741578846
precision_micro: 0.9387204410271289
recall_macro: 0.8992545010051978
recall_micro: 0.9309412137081691

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7386702186934997
direct_f1_micro: 0.8575500199509776
direct_precision_macro: 0.7736184423960453
direct_precision_micro: 0.8628125716907548
direct_recall_macro: 0.7260040145968889
direct_recall_micro: 0.8523512747875354
f1_macro: 0.8257635030577569
f1_micro: 0.9108206632879879
precision_macro: 0.8454726508202687
precision_micro: 0.9180445400367433
recall_macro: 0.8138361325276351
recall_micro: 0.9037095849322924

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7514454356408645
direct_f1_micro: 0.8581640757971178
direct_precision_macro: 0.7820236816786558
direct_precision_micro: 0.8593341665719805
direct_recall_macro: 0.7404192109010584
direct_recall_micro: 0.8569971671388102
f1_macro: 0.827884332112964
f1_micro: 0.9110879819297119
precision_macro: 0.8511296481314452
precision_micro: 0.9148358978920217
recall_macro: 0.8131100118303342
recall_micro: 0.9073706497287284

====================================================================================================
RUN 11/30 | SEED 197
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1021.92it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.67      1405     0.8918     0.8957    +0.0038
Animal                                    0.76       184     0.9307     0.9382    +0.0075
Animate                                   0.27        13     0.8182     0.8696    +0.0514
Artefact                                  0.40       503     0.8769     0.8845    +0.0076
Body_Part                                 0.50        74     0.9459     0.9459    +0.0000
Comestible                                0.62       157     0.9524     0.9613    +0.0089
Communication                             0.41       534     0.7963     0.8011    +0.0048
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.44       340     0.8439     0.8514    +0.0075
Elongated                                 0.46       168     0.7622     0.7642    +0.0020
Eventive                                  0.45      1068     0.8833     0.8850    +0.0017
Feminine                                  0.76       204     0.9336     0.9417    +0.0081
Fluid                                     0.50        19     0.9231     0.9231    +0.0000
Garment                                   0.14        17     0.9375     0.9444    +0.0069
Inanimate                                 0.30      1511     0.9347     0.9365    +0.0018
Internal_Control                          0.29        21     0.3200     0.4286    +0.1086
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.44      1209     0.9243     0.9258    +0.0014
Machine                                   0.66       180     0.8764     0.8812    +0.0048
Masculine                                 0.16       671     0.9275     0.9338    +0.0063
Natural                                   0.47        79     0.8696     0.8765    +0.0070
Natural_Force                             0.46        35     0.7941     0.8286    +0.0345
Non_Rigid                                 0.62       335     0.7932     0.8048    +0.0116
Organisation                              0.44      1086     0.8950     0.8965    +0.0015
Plant                                     0.36        15     0.8148     0.9333    +0.1185
Point_in_Time                             0.45       336     0.8639     0.8693    +0.0054
Pointy                                    0.15        20     0.3200     0.6122    +0.2922
Question                                  0.20        33     0.8197     0.8485    +0.0288
Rigid                                     0.36       603     0.8709     0.8825    +0.0117
Solid                                     0.34      1409     0.8864     0.8879    +0.0015
Sound                                     0.66        42     0.7955     0.8049    +0.0094
Statement                                 0.38       264     0.7592     0.7664    +0.0073
Substance                                 0.51       217     0.8814     0.8854    +0.0040
Time                                      0.21        16     0.1176     0.6207    +0.5030
Unspecified_Gender_or_Neuter              0.46       677     0.8840     0.8845    +0.0005
Vehicle                                   0.22       100     0.9645     0.9652    +0.0007
Web_Location                              0.90        55     0.8421     0.9126    +0.0705

VALIDATION @ 0.5
direct_f1_macro: 0.8283913121177318
direct_f1_micro: 0.886217008797654
direct_precision_macro: 0.8924719528832357
direct_precision_micro: 0.8868672046955246
direct_recall_macro: 0.8143704836187974
direct_recall_micro: 0.8855677655677656
f1_macro: 0.8848832980284387
f1_micro: 0.9334470249880769
precision_macro: 0.9025629039446573
precision_micro: 0.9376887340301975
recall_macro: 0.8772265026436911
recall_micro: 0.9292435185451615

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8646418885928264
direct_f1_micro: 0.8907611853573504
direct_precision_macro: 0.8759007339699367
direct_precision_micro: 0.8831917038744059
direct_recall_macro: 0.8643316324840091
direct_recall_micro: 0.8984615384615384
f1_macro: 0.9012386962502082
f1_micro: 0.9364475516444394
precision_macro: 0.897127850684516
precision_micro: 0.9343952329112474
recall_macro: 0.9070287284659151
recall_micro: 0.9385089057059822

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7696715834850919
direct_f1_micro: 0.8579387186629527
direct_precision_macro: 0.8231788086950987
direct_precision_micro: 0.8608259183207848
direct_recall_macro: 0.7547151003976917
direct_recall_micro: 0.855070821529745
f1_macro: 0.8475025659739502
f1_micro: 0.9143616432288784
precision_macro: 0.8650421392110452
precision_micro: 0.9181640277530688
recall_macro: 0.8365143455704045
recall_micro: 0.9105906223810154

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7791534234062485
direct_f1_micro: 0.8572876774048209
direct_precision_macro: 0.7959050245543876
direct_precision_micro: 0.8522002015451797
direct_recall_macro: 0.7754978508683508
direct_recall_micro: 0.8624362606232294
f1_macro: 0.8517062200022184
f1_micro: 0.9140301401251432
precision_macro: 0.8671380215218735
precision_micro: 0.9131047233349474
recall_macro: 0.8429645383037222
recall_micro: 0.9149574346080896

====================================================================================================
RUN 12/30 | SEED 223
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1074.07it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.51      1405     0.8950     0.8953    +0.0002
Animal                                    0.89       184     0.9264     0.9348    +0.0084
Animate                                   0.29        13     0.7619     0.8696    +0.1077
Artefact                                  0.42       503     0.8898     0.8942    +0.0044
Body_Part                                 0.16        74     0.9014     0.9272    +0.0257
Comestible                                0.69       157     0.9560     0.9582    +0.0022
Communication                             0.54       534     0.7970     0.8030    +0.0060
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.22       340     0.8450     0.8511    +0.0061
Elongated                                 0.61       168     0.7568     0.7658    +0.0091
Eventive                                  0.56      1068     0.8776     0.8784    +0.0007
Feminine                                  0.52       204     0.9353     0.9400    +0.0047
Fluid                                     0.53        19     0.9000     0.9231    +0.0231
Garment                                   0.52        17     0.9091     0.9375    +0.0284
Inanimate                                 0.63      1511     0.9303     0.9324    +0.0020
Internal_Control                          0.05        21     0.3200     0.5128    +0.1928
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.35      1209     0.9188     0.9213    +0.0025
Machine                                   0.64       180     0.8701     0.8754    +0.0053
Masculine                                 0.38       671     0.9390     0.9416    +0.0027
Natural                                   0.40        79     0.8684     0.8750    +0.0066
Natural_Force                             0.42        35     0.8406     0.8451    +0.0045
Non_Rigid                                 0.59       335     0.7869     0.7889    +0.0020
Organisation                              0.47      1086     0.8972     0.8977    +0.0005
Plant                                     0.29        15     0.7407     0.8667    +0.1259
Point_in_Time                             0.61       336     0.8713     0.8737    +0.0024
Pointy                                    0.19        20     0.2857     0.6250    +0.3393
Question                                  0.41        33     0.8475     0.8852    +0.0378
Rigid                                     0.40       603     0.8783     0.8828    +0.0045
Solid                                     0.58      1409     0.8887     0.8903    +0.0017
Sound                                     0.71        42     0.7857     0.8312    +0.0455
Statement                                 0.42       264     0.7538     0.7617    +0.0079
Substance                                 0.34       217     0.8784     0.8904    +0.0120
Time                                      0.17        16     0.2000     0.4762    +0.2762
Unspecified_Gender_or_Neuter              0.50       677     0.8977     0.8977    +0.0000
Vehicle                                   0.75       100     0.9543     0.9592    +0.0049
Web_Location                              0.85        55     0.8545     0.9020    +0.0474

VALIDATION @ 0.5
direct_f1_macro: 0.8259251828091179
direct_f1_micro: 0.8868305950674459
direct_precision_macro: 0.8731895243689707
direct_precision_micro: 0.8898723906468983
direct_recall_macro: 0.8073191471713139
direct_recall_micro: 0.8838095238095238
f1_macro: 0.882142054879562
f1_micro: 0.934394443640573
precision_macro: 0.8963976479142065
precision_micro: 0.9397793753820182
recall_macro: 0.8724632694267491
recall_micro: 0.929070871579432

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8624382657040778
direct_f1_micro: 0.8902842035690681
direct_precision_macro: 0.8719103454660858
direct_precision_micro: 0.8924469964664311
direct_recall_macro: 0.8584039543003396
direct_recall_micro: 0.8881318681318682
f1_macro: 0.9004771796413874
f1_micro: 0.935826013977919
precision_macro: 0.9098780153725944
precision_micro: 0.9412329724065666
recall_macro: 0.8937850949846992
recall_micro: 0.9304808217995568

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7696736948986499
direct_f1_micro: 0.8584889595277289
direct_precision_macro: 0.7931424424558359
direct_precision_micro: 0.8601000909918107
direct_recall_macro: 0.7583704563760972
direct_recall_micro: 0.8568838526912181
f1_macro: 0.8518466680623534
f1_micro: 0.9139559054421619
precision_macro: 0.8696756279555138
precision_micro: 0.9164079822616408
recall_macro: 0.8411344355327331
recall_micro: 0.9115169158837281

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7795748677993594
direct_f1_micro: 0.8570454932697222
direct_precision_macro: 0.7944518782535006
direct_precision_micro: 0.8591437030289228
direct_recall_macro: 0.7767302074842263
direct_recall_micro: 0.854957507082153
f1_macro: 0.85116049811285
f1_micro: 0.9112908587257618
precision_macro: 0.8739043994808497
precision_micro: 0.915694308363766
recall_macro: 0.8381493257514302
recall_micro: 0.9069295575845794

====================================================================================================
RUN 13/30 | SEED 251
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1043.11it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.68      1405     0.8931     0.8936    +0.0005
Animal                                    0.48       184     0.9474     0.9503    +0.0029
Animate                                   0.39        13     0.7000     0.7826    +0.0826
Artefact                                  0.31       503     0.8918     0.8968    +0.0049
Body_Part                                 0.66        74     0.8951     0.9014    +0.0063
Comestible                                0.79       157     0.9460     0.9511    +0.0051
Communication                             0.47       534     0.7996     0.8063    +0.0066
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.92       340     0.8484     0.8604    +0.0120
Elongated                                 0.47       168     0.7485     0.7576    +0.0091
Eventive                                  0.58      1068     0.8833     0.8868    +0.0035
Feminine                                  0.21       204     0.9272     0.9356    +0.0084
Fluid                                     0.60        19     0.8718     0.8947    +0.0229
Garment                                   0.80        17     0.8571     0.9375    +0.0804
Inanimate                                 0.59      1511     0.9337     0.9354    +0.0017
Internal_Control                          0.09        21     0.3200     0.4000    +0.0800
Language                                  0.56         5     0.9091     1.0000    +0.0909
Location                                  0.45      1209     0.9238     0.9254    +0.0016
Machine                                   0.53       180     0.9014     0.9054    +0.0040
Masculine                                 0.50       671     0.9351     0.9351    +0.0000
Natural                                   0.57        79     0.8571     0.8627    +0.0056
Natural_Force                             0.30        35     0.7941     0.8451    +0.0510
Non_Rigid                                 0.67       335     0.7856     0.8037    +0.0181
Organisation                              0.36      1086     0.8914     0.8919    +0.0006
Plant                                     0.40        15     0.8571     0.9333    +0.0762
Point_in_Time                             0.59       336     0.8692     0.8720    +0.0028
Pointy                                    0.25        20     0.2963     0.7500    +0.4537
Question                                  0.17        33     0.8254     0.8485    +0.0231
Rigid                                     0.34       603     0.8762     0.8827    +0.0065
Solid                                     0.56      1409     0.8930     0.8959    +0.0029
Sound                                     0.37        42     0.7436     0.8046    +0.0610
Statement                                 0.49       264     0.7678     0.7686    +0.0009
Substance                                 0.41       217     0.8796     0.9005    +0.0208
Time                                      0.14        16     0.0000     0.5517    +0.5517
Unspecified_Gender_or_Neuter              0.51       677     0.8843     0.8861    +0.0018
Vehicle                                   0.11       100     0.9596     0.9604    +0.0008
Web_Location                              0.84        55     0.8727     0.9143    +0.0416

VALIDATION @ 0.5
direct_f1_macro: 0.8158242750106215
direct_f1_micro: 0.8875473920565392
direct_precision_macro: 0.855354075523233
direct_precision_micro: 0.8919138862173559
direct_recall_macro: 0.8011254464274071
direct_recall_micro: 0.8832234432234433
f1_macro: 0.8788773102568529
f1_micro: 0.9337152446257558
precision_macro: 0.89204571276321
precision_micro: 0.9388764437203619
recall_macro: 0.8712275186823429
recall_micro: 0.9286104796708198

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.862918142436049
direct_f1_micro: 0.892462015046467
direct_precision_macro: 0.8834171735339014
direct_precision_micro: 0.8985593346205257
direct_recall_macro: 0.8487990105871455
direct_recall_micro: 0.8864468864468864
f1_macro: 0.9026388237406224
f1_micro: 0.9345314877889702
precision_macro: 0.912168261477428
precision_micro: 0.9415045850125576
recall_macro: 0.8942680393161572
recall_micro: 0.9276609213593071

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7356842910676923
direct_f1_micro: 0.8611491108071135
direct_precision_macro: 0.7798660752732977
direct_precision_micro: 0.8663837596054593
direct_recall_macro: 0.720885346149824
direct_recall_micro: 0.8559773371104816
f1_macro: 0.8294667180159424
f1_micro: 0.9142198172624856
precision_macro: 0.8528356396658562
precision_micro: 0.919316712011061
recall_macro: 0.8134814636769551
recall_micro: 0.9091791275197388

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7487992768235402
direct_f1_micro: 0.857664650154092
direct_precision_macro: 0.772068261522453
direct_precision_micro: 0.8639760837070254
direct_recall_macro: 0.736637090845977
direct_recall_micro: 0.8514447592067989
f1_macro: 0.8279802055628926
f1_micro: 0.9102213932005419
precision_macro: 0.8542606884296078
precision_micro: 0.916510151149271
recall_macro: 0.8105225024720829
recall_micro: 0.9040183494331966

====================================================================================================
RUN 14/30 | SEED 281
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1008.43it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.67      1405     0.8861     0.8917    +0.0056
Animal                                    0.65       184     0.9363     0.9415    +0.0052
Animate                                   0.45        13     0.8182     0.8696    +0.0514
Artefact                                  0.54       503     0.8898     0.8912    +0.0014
Body_Part                                 0.22        74     0.8951     0.9041    +0.0090
Comestible                                0.59       157     0.9554     0.9585    +0.0031
Communication                             0.50       534     0.8065     0.8065    +0.0000
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.30       340     0.8370     0.8506    +0.0136
Elongated                                 0.41       168     0.7692     0.7771    +0.0079
Eventive                                  0.42      1068     0.8744     0.8758    +0.0014
Feminine                                  0.85       204     0.9386     0.9400    +0.0014
Fluid                                     0.41        19     0.8571     0.8947    +0.0376
Garment                                   0.14        17     0.9412     0.9444    +0.0033
Inanimate                                 0.51      1511     0.9327     0.9332    +0.0006
Internal_Control                          0.33        21     0.3200     0.4286    +0.1086
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.50      1209     0.9220     0.9220    +0.0000
Machine                                   0.42       180     0.8620     0.8736    +0.0117
Masculine                                 0.48       671     0.9351     0.9359    +0.0008
Natural                                   0.25        79     0.8477     0.8712    +0.0235
Natural_Force                             0.68        35     0.7576     0.8065    +0.0489
Non_Rigid                                 0.64       335     0.8017     0.8073    +0.0056
Organisation                              0.38      1086     0.8875     0.8913    +0.0038
Plant                                     0.49        15     0.8667     0.9032    +0.0366
Point_in_Time                             0.77       336     0.8696     0.8744    +0.0049
Pointy                                    0.30        20     0.4828     0.8000    +0.3172
Question                                  0.19        33     0.8136     0.8657    +0.0521
Rigid                                     0.54       603     0.8735     0.8766    +0.0031
Solid                                     0.55      1409     0.8864     0.8892    +0.0028
Sound                                     0.77        42     0.7805     0.8108    +0.0303
Statement                                 0.60       264     0.7675     0.7762    +0.0088
Substance                                 0.45       217     0.8758     0.8820    +0.0061
Time                                      0.23        16     0.1176     0.6207    +0.5030
Unspecified_Gender_or_Neuter              0.41       677     0.8791     0.8833    +0.0043
Vehicle                                   0.43       100     0.9596     0.9648    +0.0052
Web_Location                              0.93        55     0.8496     0.9126    +0.0631

VALIDATION @ 0.5
direct_f1_macro: 0.8295466294144535
direct_f1_micro: 0.8849127457477358
direct_precision_macro: 0.8953309555755188
direct_precision_micro: 0.8894316163410302
direct_recall_macro: 0.8084655370517939
direct_recall_micro: 0.8804395604395604
f1_macro: 0.8863484274266258
f1_micro: 0.9322986042740488
precision_macro: 0.9042150077867885
precision_micro: 0.9382485793384817
recall_macro: 0.8737246213473313
recall_micro: 0.9264236181049118

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8668902685865144
direct_f1_micro: 0.8895854845847471
direct_precision_macro: 0.8938454849438197
direct_precision_micro: 0.8956631516411704
direct_recall_macro: 0.8513797208289442
direct_recall_micro: 0.8835897435897436
f1_macro: 0.9026655946325457
f1_micro: 0.9332637560155389
precision_macro: 0.9141587686693669
precision_micro: 0.9403242295896013
recall_macro: 0.8934236533462843
recall_micro: 0.9263085201277588

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7672528240940966
direct_f1_micro: 0.85666933363813
direct_precision_macro: 0.8298419011007333
direct_precision_micro: 0.8641761789461547
direct_recall_macro: 0.7447478110283682
direct_recall_micro: 0.8492917847025496
f1_macro: 0.8447266373189249
f1_micro: 0.9113794560455445
precision_macro: 0.8715753968731463
precision_micro: 0.9190437746681019
recall_macro: 0.8253791634292048
recall_micro: 0.903841912575537

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7710134786653672
direct_f1_micro: 0.8553595968850206
direct_precision_macro: 0.81909973761694
direct_precision_micro: 0.864567658293784
direct_recall_macro: 0.7558391027304623
direct_recall_micro: 0.8463456090651558
f1_macro: 0.8469000685873761
f1_micro: 0.9080306267806267
precision_macro: 0.8744130432073712
precision_micro: 0.9164757155052343
recall_macro: 0.8286757587694427
recall_micro: 0.8997397556349521

====================================================================================================
RUN 15/30 | SEED 313
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 985.65it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.63      1405     0.8935     0.8957    +0.0021
Animal                                    0.50       184     0.9448     0.9448    +0.0000
Animate                                   0.37        13     0.6667     0.8333    +0.1667
Artefact                                  0.50       503     0.9025     0.9025    +0.0000
Body_Part                                 0.61        74     0.8904     0.9155    +0.0251
Comestible                                0.48       157     0.9551     0.9585    +0.0033
Communication                             0.46       534     0.8049     0.8070    +0.0022
Currency                                  0.53        45     0.9783     0.9890    +0.0108
Duration                                  0.24       340     0.8427     0.8508    +0.0081
Elongated                                 0.60       168     0.7730     0.7823    +0.0093
Eventive                                  0.63      1068     0.8811     0.8842    +0.0031
Feminine                                  0.43       204     0.9343     0.9395    +0.0052
Fluid                                     0.50        19     0.8889     0.8889    +0.0000
Garment                                   0.52        17     0.9412     0.9697    +0.0285
Inanimate                                 0.63      1511     0.9379     0.9395    +0.0016
Internal_Control                          0.05        21     0.3077     0.5000    +0.1923
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.64      1209     0.9148     0.9167    +0.0020
Machine                                   0.61       180     0.8851     0.8947    +0.0097
Masculine                                 0.55       671     0.9350     0.9364    +0.0014
Natural                                   0.36        79     0.8758     0.8861    +0.0103
Natural_Force                             0.75        35     0.7826     0.8254    +0.0428
Non_Rigid                                 0.32       335     0.7906     0.7910    +0.0004
Organisation                              0.30      1086     0.8867     0.8895    +0.0028
Plant                                     0.35        15     0.8667     0.9032    +0.0366
Point_in_Time                             0.63       336     0.8571     0.8654    +0.0082
Pointy                                    0.16        20     0.2963     0.6275    +0.3312
Question                                  0.05        33     0.8000     0.8615    +0.0615
Rigid                                     0.45       603     0.8710     0.8763    +0.0053
Solid                                     0.43      1409     0.8907     0.8964    +0.0057
Sound                                     0.56        42     0.7654     0.7949    +0.0294
Statement                                 0.57       264     0.7562     0.7628    +0.0066
Substance                                 0.39       217     0.8625     0.8809    +0.0184
Time                                      0.11        16     0.0000     0.5366    +0.5366
Unspecified_Gender_or_Neuter              0.09       677     0.8759     0.8790    +0.0031
Vehicle                                   0.65       100     0.9500     0.9645    +0.0145
Web_Location                              0.87        55     0.8596     0.9038    +0.0442

VALIDATION @ 0.5
direct_f1_macro: 0.8179718401234768
direct_f1_micro: 0.8859015910430171
direct_precision_macro: 0.851997826547498
direct_precision_micro: 0.8907569249000148
direct_recall_macro: 0.8020560080443436
direct_recall_micro: 0.8810989010989011
f1_macro: 0.8817046583245343
f1_micro: 0.9325132014158881
precision_macro: 0.8974206518067254
precision_micro: 0.9403434857661137
recall_macro: 0.8711396849762314
recall_micro: 0.9248122464247691

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8619950282065612
direct_f1_micro: 0.8902649030887041
direct_precision_macro: 0.871333333655239
direct_precision_micro: 0.8904932932639449
direct_recall_macro: 0.8591233323048684
direct_recall_micro: 0.89003663003663
f1_macro: 0.8996598570220494
f1_micro: 0.9360978632047606
precision_macro: 0.90713514845219
precision_micro: 0.9374891774891775
recall_macro: 0.8956909352130302
recall_micro: 0.9347106724599316

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7634067922902394
direct_f1_micro: 0.8589473684210527
direct_precision_macro: 0.7871681984335052
direct_precision_micro: 0.8626285714285714
direct_recall_macro: 0.7523270439563838
direct_recall_micro: 0.8552974504249292
f1_macro: 0.8535759189733341
f1_micro: 0.9138879035118836
precision_macro: 0.8701584410671985
precision_micro: 0.9187357910221549
recall_macro: 0.8423427551126178
recall_micro: 0.9090909090909091

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7750867261273897
direct_f1_micro: 0.8559796437659033
direct_precision_macro: 0.7888444713498355
direct_precision_micro: 0.8542889390519187
direct_recall_macro: 0.7751864028226624
direct_recall_micro: 0.8576770538243627
f1_macro: 0.8521288196357693
f1_micro: 0.9126401406902616
precision_macro: 0.868666633548863
precision_micro: 0.9096805293834086
recall_macro: 0.8453532071902627
recall_micro: 0.915619072824313

====================================================================================================
RUN 16/30 | SEED 347
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 946.67it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.52      1405     0.8920     0.8940    +0.0020
Animal                                    0.65       184     0.9396     0.9471    +0.0075
Animate                                   0.19        13     0.7619     0.8696    +0.1077
Artefact                                  0.46       503     0.8875     0.8882    +0.0007
Body_Part                                 0.22        74     0.9014     0.9324    +0.0310
Comestible                                0.50       157     0.9585     0.9585    +0.0000
Communication                             0.46       534     0.8027     0.8087    +0.0060
Currency                                  0.37        45     0.9773     0.9890    +0.0117
Duration                                  0.25       340     0.8501     0.8624    +0.0123
Elongated                                 0.62       168     0.7613     0.7640    +0.0026
Eventive                                  0.58      1068     0.8754     0.8776    +0.0023
Feminine                                  0.94       204     0.9412     0.9436    +0.0024
Fluid                                     0.28        19     0.8649     0.8947    +0.0299
Garment                                   0.50        17     0.9412     0.9412    +0.0000
Inanimate                                 0.40      1511     0.9300     0.9325    +0.0025
Internal_Control                          0.07        21     0.3704     0.4242    +0.0539
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.41      1209     0.9253     0.9273    +0.0020
Machine                                   0.24       180     0.8653     0.8798    +0.0145
Masculine                                 0.62       671     0.9405     0.9423    +0.0018
Natural                                   0.50        79     0.9020     0.9020    +0.0000
Natural_Force                             0.41        35     0.8529     0.8571    +0.0042
Non_Rigid                                 0.51       335     0.8012     0.8047    +0.0035
Organisation                              0.48      1086     0.9016     0.9024    +0.0008
Plant                                     0.35        15     0.8462     0.8966    +0.0504
Point_in_Time                             0.84       336     0.8627     0.8730    +0.0103
Pointy                                    0.32        20     0.5333     0.8205    +0.2872
Question                                  0.23        33     0.8475     0.8923    +0.0449
Rigid                                     0.33       603     0.8728     0.8792    +0.0065
Solid                                     0.62      1409     0.8873     0.8895    +0.0021
Sound                                     0.58        42     0.7848     0.7895    +0.0047
Statement                                 0.42       264     0.7481     0.7584    +0.0103
Substance                                 0.38       217     0.8741     0.8864    +0.0123
Time                                      0.16        16     0.2222     0.5625    +0.3403
Unspecified_Gender_or_Neuter              0.39       677     0.8906     0.8927    +0.0021
Vehicle                                   0.33       100     0.9600     0.9652    +0.0052
Web_Location                              0.84        55     0.8727     0.9231    +0.0503

VALIDATION @ 0.5
direct_f1_macro: 0.8390872370789754
direct_f1_micro: 0.887994683992912
direct_precision_macro: 0.9022067849090447
direct_precision_micro: 0.8949992558416431
direct_recall_macro: 0.8117609908309076
direct_recall_micro: 0.8810989010989011
f1_macro: 0.8910741477560284
f1_micro: 0.9339397814461753
precision_macro: 0.913677177802112
precision_micro: 0.9433989959780407
recall_macro: 0.8737602856790743
recall_micro: 0.9246683739533278

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8695143202411154
direct_f1_micro: 0.8922521726321991
direct_precision_macro: 0.886733769257374
direct_precision_micro: 0.8970087368576929
direct_recall_macro: 0.8564475665547923
direct_recall_micro: 0.8875457875457875
f1_macro: 0.906089791601695
f1_micro: 0.9356111143337781
precision_macro: 0.9165467216493317
precision_micro: 0.9431336432476684
recall_macro: 0.8970277744443598
recall_micro: 0.9282076367507841

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7572370850300146
direct_f1_micro: 0.8571917417588685
direct_precision_macro: 0.8019921250086391
direct_precision_micro: 0.8629004478126077
direct_recall_macro: 0.7373639148163925
direct_recall_micro: 0.851558073654391
f1_macro: 0.8416339012227806
f1_micro: 0.9121630623029442
precision_macro: 0.8701066371056101
precision_micro: 0.9183618724013055
recall_macro: 0.8231934623803651
recall_micro: 0.9060473732962816

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7714412948925581
direct_f1_micro: 0.855762124054807
direct_precision_macro: 0.8178492306158095
direct_precision_micro: 0.858740301232314
direct_recall_macro: 0.7625231758659545
direct_recall_micro: 0.8528045325779037
f1_macro: 0.8417747005617299
f1_micro: 0.9104858200847026
precision_macro: 0.8918612653382988
precision_micro: 0.91541822721598
recall_macro: 0.8235721334580746
recall_micro: 0.9056062811521327

====================================================================================================
RUN 17/30 | SEED 383
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 989.31it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.60      1405     0.8924     0.8949    +0.0025
Animal                                    0.74       184     0.9311     0.9412    +0.0100
Animate                                   0.21        13     0.7619     0.8696    +0.1077
Artefact                                  0.47       503     0.8950     0.8984    +0.0034
Body_Part                                 0.18        74     0.9028     0.9128    +0.0100
Comestible                                0.60       157     0.9557     0.9618    +0.0061
Communication                             0.47       534     0.8027     0.8049    +0.0022
Currency                                  0.59        45     0.9890     1.0000    +0.0110
Duration                                  0.78       340     0.8471     0.8585    +0.0114
Elongated                                 0.31       168     0.7470     0.7645    +0.0176
Eventive                                  0.42      1068     0.8780     0.8803    +0.0022
Feminine                                  0.92       204     0.9249     0.9426    +0.0177
Fluid                                     0.50        19     0.9231     0.9231    +0.0000
Garment                                   0.11        17     0.9091     0.9444    +0.0354
Inanimate                                 0.58      1511     0.9336     0.9348    +0.0012
Internal_Control                          0.07        21     0.3200     0.4571    +0.1371
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.60      1209     0.9235     0.9265    +0.0031
Machine                                   0.61       180     0.8782     0.8934    +0.0152
Masculine                                 0.41       671     0.9388     0.9413    +0.0025
Natural                                   0.35        79     0.8774     0.8846    +0.0072
Natural_Force                             0.48        35     0.8235     0.8406    +0.0171
Non_Rigid                                 0.58       335     0.7818     0.7916    +0.0098
Organisation                              0.37      1086     0.8872     0.8906    +0.0034
Plant                                     0.45        15     0.8667     0.9032    +0.0366
Point_in_Time                             0.22       336     0.8601     0.8734    +0.0133
Pointy                                    0.25        20     0.4667     0.7111    +0.2444
Question                                  0.67        33     0.8525     0.8814    +0.0289
Rigid                                     0.50       603     0.8779     0.8779    +0.0000
Solid                                     0.41      1409     0.8935     0.8948    +0.0012
Sound                                     0.59        42     0.8250     0.8354    +0.0104
Statement                                 0.55       264     0.7748     0.7814    +0.0066
Substance                                 0.37       217     0.8732     0.8798    +0.0066
Time                                      0.21        16     0.3158     0.5517    +0.2359
Unspecified_Gender_or_Neuter              0.47       677     0.8952     0.8962    +0.0010
Vehicle                                   0.24       100     0.9548     0.9655    +0.0107
Web_Location                              0.92        55     0.8545     0.9126    +0.0581

VALIDATION @ 0.5
direct_f1_macro: 0.8387721328391065
direct_f1_micro: 0.8879738225670062
direct_precision_macro: 0.8952722109729028
direct_precision_micro: 0.8912834895564248
direct_recall_macro: 0.8185584027420943
direct_recall_micro: 0.8846886446886447
f1_macro: 0.8894486927077516
f1_micro: 0.9330920671685002
precision_macro: 0.9026851208920845
precision_micro: 0.9388819296763481
recall_macro: 0.8796790097220478
recall_micro: 0.9273731764164245

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8681615265903423
direct_f1_micro: 0.8923324907498993
direct_precision_macro: 0.8798964705564574
direct_precision_micro: 0.892430570821426
direct_recall_macro: 0.8610620071652632
direct_recall_micro: 0.8922344322344322
f1_macro: 0.9041112119539344
f1_micro: 0.9352146034313442
precision_macro: 0.9073087708144876
precision_micro: 0.9387666347742889
recall_macro: 0.9032085628605564
recall_micro: 0.931689350559664

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7700675641838789
direct_f1_micro: 0.8586839266450917
direct_precision_macro: 0.8137739673561604
direct_precision_micro: 0.8604915794264907
direct_recall_macro: 0.7569009045962393
direct_recall_micro: 0.8568838526912181
f1_macro: 0.8512126544093513
f1_micro: 0.9148587620649961
precision_macro: 0.869130660096974
precision_micro: 0.9183147415670415
recall_macro: 0.8400613310665954
recall_micro: 0.9114286974548983

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7777676022334307
direct_f1_micro: 0.8592315538932336
direct_precision_macro: 0.7964796045360548
direct_precision_micro: 0.8594263688924159
direct_recall_macro: 0.7691520724026392
direct_recall_micro: 0.8590368271954674
f1_macro: 0.8557833598343795
f1_micro: 0.9143412651068249
precision_macro: 0.8758521352635268
precision_micro: 0.9159805223550244
recall_macro: 0.8439222694973869
recall_micro: 0.9127078646729302

====================================================================================================
RUN 18/30 | SEED 421
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1030.80it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.45      1405     0.8925     0.8937    +0.0012
Animal                                    0.87       184     0.9392     0.9497    +0.0105
Animate                                   0.48        13     0.6957     0.7500    +0.0543
Artefact                                  0.50       503     0.8984     0.8984    +0.0000
Body_Part                                 0.59        74     0.8889     0.9014    +0.0125
Comestible                                0.67       157     0.9430     0.9518    +0.0087
Communication                             0.43       534     0.7960     0.8039    +0.0080
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.80       340     0.8571     0.8629    +0.0058
Elongated                                 0.54       168     0.7901     0.7975    +0.0074
Eventive                                  0.44      1068     0.8802     0.8813    +0.0011
Feminine                                  0.79       204     0.9253     0.9386    +0.0133
Fluid                                     0.37        19     0.8947     0.9231    +0.0283
Garment                                   0.67        17     0.9091     0.9375    +0.0284
Inanimate                                 0.44      1511     0.9317     0.9323    +0.0007
Internal_Control                          0.26        21     0.3200     0.4667    +0.1467
Language                                  0.37         5     0.8889     1.0000    +0.1111
Location                                  0.44      1209     0.9271     0.9301    +0.0030
Machine                                   0.60       180     0.8661     0.8812    +0.0151
Masculine                                 0.45       671     0.9358     0.9367    +0.0009
Natural                                   0.51        79     0.8903     0.8961    +0.0058
Natural_Force                             0.43        35     0.8451     0.8611    +0.0160
Non_Rigid                                 0.49       335     0.7988     0.7994    +0.0006
Organisation                              0.49      1086     0.8913     0.8919    +0.0006
Plant                                     0.28        15     0.8966     0.9032    +0.0067
Point_in_Time                             0.70       336     0.8820     0.8848    +0.0028
Pointy                                    0.32        20     0.5806     0.8421    +0.2615
Question                                  0.48        33     0.8667     0.8852    +0.0186
Rigid                                     0.51       603     0.8783     0.8790    +0.0007
Solid                                     0.55      1409     0.8863     0.8902    +0.0040
Sound                                     0.63        42     0.8000     0.8267    +0.0267
Statement                                 0.42       264     0.7548     0.7647    +0.0099
Substance                                 0.42       217     0.8773     0.8854    +0.0081
Time                                      0.11        16     0.0000     0.5263    +0.5263
Unspecified_Gender_or_Neuter              0.50       677     0.8844     0.8844    +0.0000
Vehicle                                   0.66       100     0.9505     0.9552    +0.0047
Web_Location                              0.83        55     0.8348     0.9126    +0.0778

VALIDATION @ 0.5
direct_f1_macro: 0.8296638411664453
direct_f1_micro: 0.8878979952830188
direct_precision_macro: 0.867571835462225
direct_precision_micro: 0.8932967521874536
direct_recall_macro: 0.811868941186584
direct_recall_micro: 0.8825641025641026
f1_macro: 0.8914773051587782
f1_micro: 0.9334164841699177
precision_macro: 0.9087630367962269
precision_micro: 0.9409907012105971
recall_macro: 0.8782802556439181
recall_micro: 0.9259632261962996

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8682540302209301
direct_f1_micro: 0.8916123808472268
direct_precision_macro: 0.8902674600244488
direct_precision_micro: 0.8958656904075143
direct_recall_macro: 0.8544935902449299
direct_recall_micro: 0.8873992673992674
f1_macro: 0.9075158158792901
f1_micro: 0.9343769513381642
precision_macro: 0.9232004087403782
precision_micro: 0.943183817062445
recall_macro: 0.8940522984864889
recall_micro: 0.9257330302419935

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7583167853291863
direct_f1_micro: 0.8585293445992236
direct_precision_macro: 0.799545084616212
direct_precision_micro: 0.8651478541019445
direct_recall_macro: 0.7361995107602473
direct_recall_micro: 0.8520113314447592
f1_macro: 0.8460804118776182
f1_micro: 0.9135451170442167
precision_macro: 0.8773870205891884
precision_micro: 0.9208945858730728
recall_macro: 0.8260493351163244
recall_micro: 0.9063120285827709

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7640657074963902
direct_f1_micro: 0.8580711354309165
direct_precision_macro: 0.8039471716057331
direct_precision_micro: 0.8632870742057576
direct_recall_macro: 0.7455384369915962
direct_recall_micro: 0.8529178470254958
f1_macro: 0.84251412587892
f1_micro: 0.9117660152250368
precision_macro: 0.8797298719700977
precision_micro: 0.9202875758256571
recall_macro: 0.8181115844698197
recall_micro: 0.9034008204313881

====================================================================================================
RUN 19/30 | SEED 461
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 975.73it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.26      1405     0.8873     0.8907    +0.0034
Animal                                    0.56       184     0.9421     0.9448    +0.0026
Animate                                   0.26        13     0.7619     0.8696    +0.1077
Artefact                                  0.50       503     0.8896     0.8896    +0.0000
Body_Part                                 0.13        74     0.8951     0.9150    +0.0199
Comestible                                0.32       157     0.9490     0.9590    +0.0099
Communication                             0.49       534     0.7932     0.7939    +0.0007
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.31       340     0.8519     0.8532    +0.0013
Elongated                                 0.59       168     0.7508     0.7658    +0.0151
Eventive                                  0.63      1068     0.8800     0.8838    +0.0037
Feminine                                  0.70       204     0.9307     0.9373    +0.0067
Fluid                                     0.11        19     0.8889     0.9048    +0.0159
Garment                                   0.29        17     0.9091     0.9412    +0.0321
Inanimate                                 0.44      1511     0.9323     0.9338    +0.0015
Internal_Control                          0.38        21     0.3846     0.4444    +0.0598
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.27      1209     0.9199     0.9241    +0.0041
Machine                                   0.71       180     0.8736     0.8810    +0.0074
Masculine                                 0.48       671     0.9355     0.9371    +0.0016
Natural                                   0.54        79     0.8734     0.8790    +0.0056
Natural_Force                             0.45        35     0.8308     0.8485    +0.0177
Non_Rigid                                 0.46       335     0.7895     0.7994    +0.0099
Organisation                              0.45      1086     0.8924     0.8939    +0.0015
Plant                                     0.34        15     0.8571     0.8667    +0.0095
Point_in_Time                             0.80       336     0.8545     0.8708    +0.0163
Pointy                                    0.32        20     0.5333     0.7317    +0.1984
Question                                  0.27        33     0.8254     0.8657    +0.0403
Rigid                                     0.25       603     0.8685     0.8716    +0.0031
Solid                                     0.43      1409     0.8898     0.8940    +0.0041
Sound                                     0.59        42     0.7778     0.7907    +0.0129
Statement                                 0.50       264     0.7559     0.7559    +0.0000
Substance                                 0.51       217     0.8833     0.8874    +0.0041
Time                                      0.18        16     0.1176     0.5294    +0.4118
Unspecified_Gender_or_Neuter              0.50       677     0.8874     0.8874    +0.0000
Vehicle                                   0.10       100     0.9648     0.9703    +0.0055
Web_Location                              0.84        55     0.8596     0.9038    +0.0442

VALIDATION @ 0.5
direct_f1_macro: 0.8334279633863501
direct_f1_micro: 0.8853882959146117
direct_precision_macro: 0.8961583608905697
direct_precision_micro: 0.8896449704142012
direct_recall_macro: 0.8133116205665156
direct_recall_micro: 0.8811721611721611
f1_macro: 0.8886245572489936
f1_micro: 0.9325046720848363
precision_macro: 0.9054148355029464
precision_micro: 0.9390208321176402
recall_macro: 0.8763375122252668
recall_micro: 0.9260783241734527

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8625692316919961
direct_f1_micro: 0.8896340574427759
direct_precision_macro: 0.8812671151084889
direct_precision_micro: 0.8852459016393442
direct_recall_macro: 0.857565914267624
direct_recall_micro: 0.894065934065934
f1_macro: 0.9010053574850891
f1_micro: 0.9356288719204725
precision_macro: 0.904104112385656
precision_micro: 0.9369247193929077
recall_macro: 0.8996862644776646
recall_micro: 0.9343366040341841

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7620194855389751
direct_f1_micro: 0.8548872607485659
direct_precision_macro: 0.7893502343742714
direct_precision_micro: 0.856980186745616
direct_recall_macro: 0.75111054635589
direct_recall_micro: 0.8528045325779037
f1_macro: 0.8473164083907776
f1_micro: 0.9100208121153079
precision_macro: 0.8688402376449416
precision_micro: 0.9135807957323849
recall_macro: 0.8358139139307257
recall_micro: 0.9064884654404305

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7687520978668484
direct_f1_micro: 0.8545188190218617
direct_precision_macro: 0.7828748628318403
direct_precision_micro: 0.8498262916059621
direct_recall_macro: 0.7703368252781292
direct_recall_micro: 0.8592634560906516
f1_macro: 0.8462055646085469
f1_micro: 0.9112394726398871
precision_macro: 0.8686496401664107
precision_micro: 0.9109181469564067
recall_macro: 0.8374691484241068
recall_micro: 0.911561025098143

====================================================================================================
RUN 20/30 | SEED 503
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 939.78it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.55      1405     0.8878     0.8901    +0.0023
Animal                                    0.41       184     0.9477     0.9511    +0.0034
Animate                                   0.13        13     0.7619     0.8696    +0.1077
Artefact                                  0.31       503     0.8753     0.8800    +0.0047
Body_Part                                 0.36        74     0.9167     0.9459    +0.0293
Comestible                                0.41       157     0.9587     0.9620    +0.0033
Communication                             0.52       534     0.7776     0.7782    +0.0006
Currency                                  0.53        45     0.9890     1.0000    +0.0110
Duration                                  0.40       340     0.8406     0.8506    +0.0101
Elongated                                 0.61       168     0.7378     0.7597    +0.0219
Eventive                                  0.71      1068     0.8800     0.8828    +0.0027
Feminine                                  0.47       204     0.9463     0.9489    +0.0026
Fluid                                     0.63        19     0.9231     0.9474    +0.0243
Garment                                   0.60        17     0.9143     0.9412    +0.0269
Inanimate                                 0.39      1511     0.9304     0.9340    +0.0036
Internal_Control                          0.05        21     0.3200     0.4516    +0.1316
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.64      1209     0.9147     0.9195    +0.0048
Machine                                   0.43       180     0.8718     0.8739    +0.0022
Masculine                                 0.47       671     0.9398     0.9422    +0.0024
Natural                                   0.61        79     0.8627     0.8667    +0.0039
Natural_Force                             0.50        35     0.8485     0.8485    +0.0000
Non_Rigid                                 0.48       335     0.8000     0.8042    +0.0042
Organisation                              0.32      1086     0.8835     0.8960    +0.0125
Plant                                     0.45        15     0.8966     0.9333    +0.0368
Point_in_Time                             0.81       336     0.8724     0.8754    +0.0030
Pointy                                    0.32        20     0.6471     0.7619    +0.1148
Question                                  0.38        33     0.8387     0.8750    +0.0363
Rigid                                     0.29       603     0.8676     0.8768    +0.0093
Solid                                     0.42      1409     0.8852     0.8872    +0.0021
Sound                                     0.75        42     0.7586     0.8000    +0.0414
Statement                                 0.60       264     0.7598     0.7645    +0.0047
Substance                                 0.46       217     0.8798     0.8849    +0.0051
Time                                      0.25        16     0.1176     0.5517    +0.4341
Unspecified_Gender_or_Neuter              0.59       677     0.8808     0.8823    +0.0015
Vehicle                                   0.15       100     0.9548     0.9655    +0.0107
Web_Location                              0.83        55     0.8468     0.8932    +0.0464

VALIDATION @ 0.5
direct_f1_macro: 0.836050547280081
direct_f1_micro: 0.8830130555963034
direct_precision_macro: 0.8918900677437297
direct_precision_micro: 0.8840505213687766
direct_recall_macro: 0.8219163850012569
direct_recall_micro: 0.881978021978022
f1_macro: 0.8927229905293966
f1_micro: 0.9313014660125327
precision_macro: 0.9012759303775123
precision_micro: 0.9368194258428929
recall_macro: 0.8859004900629097
recall_micro: 0.9258481282191465

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.867457841373702
direct_f1_micro: 0.8886857978431731
direct_precision_macro: 0.8851973655959045
direct_precision_micro: 0.8869025902955125
direct_recall_macro: 0.8558913106416145
direct_recall_micro: 0.8904761904761904
f1_macro: 0.9054942581685911
f1_micro: 0.935430845541585
precision_macro: 0.9129787939599381
precision_micro: 0.9375126448741293
recall_macro: 0.8994491656606245
recall_micro: 0.9333582712283831

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7767944412989901
direct_f1_micro: 0.8570455319632111
direct_precision_macro: 0.8281951889599111
direct_precision_micro: 0.8588007736943907
direct_recall_macro: 0.762004345756343
direct_recall_micro: 0.8552974504249292
f1_macro: 0.8516327765761288
f1_micro: 0.9123779946761313
precision_macro: 0.8712630494095637
precision_micro: 0.9177116337185952
recall_macro: 0.8393420488980994
recall_micro: 0.9071059944422389

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7764394380247688
direct_f1_micro: 0.8549255084121679
direct_precision_macro: 0.800571912520949
direct_precision_micro: 0.8547802446760309
direct_recall_macro: 0.7652499480034065
direct_recall_micro: 0.855070821529745
f1_macro: 0.8464690517635389
f1_micro: 0.9116665561669871
precision_macro: 0.8678061907841268
precision_micro: 0.9135441580299406
recall_macro: 0.8351611361256608
recall_micro: 0.9097966565215474

====================================================================================================
RUN 21/30 | SEED 547
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 931.88it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.40      1405     0.8880     0.8907    +0.0027
Animal                                    0.61       184     0.9418     0.9468    +0.0050
Animate                                   0.13        13     0.7000     0.8696    +0.1696
Artefact                                  0.54       503     0.8867     0.8891    +0.0025
Body_Part                                 0.26        74     0.9014     0.9103    +0.0089
Comestible                                0.38       157     0.9551     0.9651    +0.0100
Communication                             0.51       534     0.7889     0.7911    +0.0023
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.44       340     0.8521     0.8571    +0.0050
Elongated                                 0.53       168     0.7764     0.7837    +0.0073
Eventive                                  0.43      1068     0.8773     0.8800    +0.0027
Feminine                                  0.92       204     0.9310     0.9442    +0.0131
Fluid                                     0.75        19     0.8947     0.9189    +0.0242
Garment                                   0.16        17     0.8750     0.9444    +0.0694
Inanimate                                 0.49      1511     0.9351     0.9355    +0.0004
Internal_Control                          0.10        21     0.3704     0.4118    +0.0414
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.38      1209     0.9193     0.9200    +0.0008
Machine                                   0.42       180     0.8775     0.8840    +0.0065
Masculine                                 0.61       671     0.9355     0.9375    +0.0019
Natural                                   0.74        79     0.8774     0.8844    +0.0069
Natural_Force                             0.28        35     0.8182     0.8451    +0.0269
Non_Rigid                                 0.54       335     0.7970     0.8006    +0.0036
Organisation                              0.57      1086     0.8902     0.8917    +0.0015
Plant                                     0.35        15     0.8889     0.8966    +0.0077
Point_in_Time                             0.40       336     0.8661     0.8776    +0.0115
Pointy                                    0.21        20     0.2308     0.7556    +0.5248
Question                                  0.10        33     0.8254     0.8824    +0.0570
Rigid                                     0.53       603     0.8791     0.8805    +0.0014
Solid                                     0.65      1409     0.8921     0.8946    +0.0025
Sound                                     0.56        42     0.7857     0.8250    +0.0393
Statement                                 0.44       264     0.7595     0.7626    +0.0031
Substance                                 0.38       217     0.8767     0.8820    +0.0052
Time                                      0.11        16     0.0000     0.4706    +0.4706
Unspecified_Gender_or_Neuter              0.23       677     0.8838     0.8886    +0.0047
Vehicle                                   0.50       100     0.9645     0.9645    +0.0000
Web_Location                              0.91        55     0.8727     0.8846    +0.0119

VALIDATION @ 0.5
direct_f1_macro: 0.8220131592730088
direct_f1_micro: 0.886443921106859
direct_precision_macro: 0.8618599378624234
direct_precision_micro: 0.8905071713736508
direct_recall_macro: 0.8012892169236577
direct_recall_micro: 0.8824175824175824
f1_macro: 0.8839893616495834
f1_micro: 0.9338489839076464
precision_macro: 0.9034190698810928
precision_micro: 0.94020883159307
recall_macro: 0.8703405988668393
recall_micro: 0.9275745978764424

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8639589734880566
direct_f1_micro: 0.8902090209020902
direct_precision_macro: 0.87462555040409
direct_precision_micro: 0.8911894273127753
direct_recall_macro: 0.8573642488927795
direct_recall_micro: 0.8892307692307693
f1_macro: 0.9046233151331906
f1_micro: 0.9354862045517022
precision_macro: 0.9095752161750961
precision_micro: 0.9407810499359796
recall_macro: 0.9011685612223469
recall_micro: 0.9302506258452508

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7713214002846838
direct_f1_micro: 0.8571266067569104
direct_precision_macro: 0.8095311884234743
direct_precision_micro: 0.8604544935480187
direct_recall_macro: 0.7568322338664543
direct_recall_micro: 0.8538243626062323
f1_macro: 0.8534853605709913
f1_micro: 0.9124220029207417
precision_macro: 0.8817916329937067
precision_micro: 0.9154197931003862
recall_macro: 0.8403990231903529
recall_micro: 0.9094437828062282

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7849307410876658
direct_f1_micro: 0.8547755518983031
direct_precision_macro: 0.796819116961696
direct_precision_micro: 0.8561846293769896
direct_recall_macro: 0.7843187703293639
direct_recall_micro: 0.853371104815864
f1_macro: 0.8548416361534039
f1_micro: 0.9108687476494923
precision_macro: 0.8703623355500647
precision_micro: 0.913678324161193
recall_macro: 0.8472064991465506
recall_micro: 0.9080763971593666

====================================================================================================
RUN 22/30 | SEED 593
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 938.32it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.77      1405     0.8874     0.8909    +0.0035
Animal                                    0.30       184     0.9500     0.9505    +0.0005
Animate                                   0.37        13     0.7619     0.8696    +0.1077
Artefact                                  0.45       503     0.8962     0.9002    +0.0040
Body_Part                                 0.48        74     0.9091     0.9167    +0.0076
Comestible                                0.47       157     0.9518     0.9551    +0.0034
Communication                             0.51       534     0.8064     0.8071    +0.0008
Currency                                  0.56        45     0.9783     1.0000    +0.0217
Duration                                  0.91       340     0.8538     0.8686    +0.0148
Elongated                                 0.47       168     0.7805     0.7831    +0.0026
Eventive                                  0.53      1068     0.8826     0.8844    +0.0018
Feminine                                  0.50       204     0.9378     0.9378    +0.0000
Fluid                                     0.50        19     0.9189     0.9189    +0.0000
Garment                                   0.67        17     0.8824     0.9375    +0.0551
Inanimate                                 0.23      1511     0.9317     0.9361    +0.0044
Internal_Control                          0.09        21     0.3846     0.4375    +0.0529
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.70      1209     0.9170     0.9191    +0.0021
Machine                                   0.32       180     0.8706     0.8864    +0.0158
Masculine                                 0.69       671     0.9301     0.9366    +0.0065
Natural                                   0.27        79     0.8571     0.8805    +0.0234
Natural_Force                             0.59        35     0.8286     0.8529    +0.0244
Non_Rigid                                 0.54       335     0.7883     0.7970    +0.0087
Organisation                              0.38      1086     0.8900     0.8930    +0.0030
Plant                                     0.50        15     0.9333     0.9333    +0.0000
Point_in_Time                             0.46       336     0.8776     0.8812    +0.0036
Pointy                                    0.41        20     0.5143     0.7442    +0.2299
Question                                  0.32        33     0.8387     0.8615    +0.0228
Rigid                                     0.35       603     0.8721     0.8791    +0.0069
Solid                                     0.48      1409     0.8924     0.8932    +0.0008
Sound                                     0.70        42     0.7750     0.8056    +0.0306
Statement                                 0.37       264     0.7641     0.7729    +0.0088
Substance                                 0.53       217     0.8805     0.8844    +0.0039
Time                                      0.18        16     0.1176     0.5000    +0.3824
Unspecified_Gender_or_Neuter              0.39       677     0.8851     0.8882    +0.0032
Vehicle                                   0.86       100     0.9596     0.9641    +0.0045
Web_Location                              0.88        55     0.8319     0.8952    +0.0634

VALIDATION @ 0.5
direct_f1_macro: 0.836142503547281
direct_f1_micro: 0.8870604730103678
direct_precision_macro: 0.8924693141690712
direct_precision_micro: 0.8935553408161748
direct_recall_macro: 0.818909777393922
direct_recall_micro: 0.8806593406593407
f1_macro: 0.8917176317719188
f1_micro: 0.9332325669273028
precision_macro: 0.902584551306816
precision_micro: 0.9428244207558806
recall_macro: 0.8822822745270535
recall_micro: 0.9238339136189682

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8665561419726234
direct_f1_micro: 0.8916685115489632
direct_precision_macro: 0.8844507640995207
direct_precision_micro: 0.898230746357419
direct_recall_macro: 0.8557499618798547
direct_recall_micro: 0.8852014652014653
f1_macro: 0.9051706937699109
f1_micro: 0.9355339298922423
precision_macro: 0.9176234008250593
precision_micro: 0.9431253289666063
recall_macro: 0.8950833944423683
recall_micro: 0.9280637642793428

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7556956800926262
direct_f1_micro: 0.8577158902068649
direct_precision_macro: 0.8303033462569982
direct_precision_micro: 0.8676095525156503
direct_recall_macro: 0.734460758505141
direct_recall_micro: 0.8480453257790368
f1_macro: 0.8418405272231941
f1_micro: 0.9120182216068956
precision_macro: 0.8741727380606467
precision_micro: 0.9235674551128398
recall_macro: 0.8208005882144017
recall_micro: 0.9007542675664947

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7622452556379632
direct_f1_micro: 0.8567336884917225
direct_precision_macro: 0.7947169764776894
direct_precision_micro: 0.8663113994439295
direct_recall_macro: 0.7465151077229993
direct_recall_micro: 0.8473654390934844
f1_macro: 0.8389057925590782
f1_micro: 0.9104344729344729
precision_macro: 0.8751731466139906
precision_micro: 0.9189019184975513
recall_macro: 0.8159795977754349
recall_micro: 0.9021216532133562

====================================================================================================
RUN 23/30 | SEED 641
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1000.78it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.67      1405     0.8892     0.8949    +0.0056
Animal                                    0.80       184     0.9425     0.9474    +0.0049
Animate                                   0.20        13     0.7619     0.8696    +0.1077
Artefact                                  0.45       503     0.8909     0.8927    +0.0018
Body_Part                                 0.44        74     0.9388     0.9459    +0.0072
Comestible                                0.47       157     0.9649     0.9682    +0.0033
Communication                             0.37       534     0.7894     0.8026    +0.0132
Currency                                  0.52        45     0.9783     0.9890    +0.0108
Duration                                  0.64       340     0.8555     0.8640    +0.0085
Elongated                                 0.45       168     0.7649     0.7818    +0.0169
Eventive                                  0.43      1068     0.8880     0.8891    +0.0011
Feminine                                  0.80       204     0.9242     0.9438    +0.0196
Fluid                                     0.27        19     0.8947     0.9231    +0.0283
Garment                                   0.25        17     0.9091     0.9714    +0.0623
Inanimate                                 0.38      1511     0.9359     0.9380    +0.0020
Internal_Control                          0.30        21     0.3846     0.4138    +0.0292
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.54      1209     0.9212     0.9229    +0.0017
Machine                                   0.57       180     0.8708     0.8883    +0.0175
Masculine                                 0.71       671     0.9340     0.9380    +0.0039
Natural                                   0.44        79     0.8608     0.8750    +0.0142
Natural_Force                             0.25        35     0.7941     0.8378    +0.0437
Non_Rigid                                 0.62       335     0.7948     0.8000    +0.0052
Organisation                              0.31      1086     0.8902     0.8976    +0.0074
Plant                                     0.50        15     0.8966     0.8966    +0.0000
Point_in_Time                             0.84       336     0.8588     0.8683    +0.0095
Pointy                                    0.18        20     0.4667     0.6667    +0.2000
Question                                  0.46        33     0.8525     0.8710    +0.0185
Rigid                                     0.49       603     0.8744     0.8746    +0.0002
Solid                                     0.48      1409     0.8935     0.8955    +0.0020
Sound                                     0.48        42     0.7792     0.8101    +0.0309
Statement                                 0.65       264     0.7529     0.7724    +0.0195
Substance                                 0.42       217     0.8733     0.8761    +0.0028
Time                                      0.23        16     0.3000     0.4667    +0.1667
Unspecified_Gender_or_Neuter              0.47       677     0.8892     0.8905    +0.0013
Vehicle                                   0.33       100     0.9543     0.9548    +0.0005
Web_Location                              0.92        55     0.8496     0.9143    +0.0647

VALIDATION @ 0.5
direct_f1_macro: 0.8383622416013993
direct_f1_micro: 0.8877025036818851
direct_precision_macro: 0.8879106155673411
direct_precision_micro: 0.8923019985196151
direct_recall_macro: 0.8174344196609343
direct_recall_micro: 0.8831501831501831
f1_macro: 0.8894892196801067
f1_micro: 0.9342530467923544
precision_macro: 0.9052314643615285
precision_micro: 0.941057978630233
recall_macro: 0.8777414625312009
recall_micro: 0.9275458233821541

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8635715315509094
direct_f1_micro: 0.8931160086831745
direct_precision_macro: 0.8816061320019175
direct_precision_micro: 0.8971099120408013
direct_recall_macro: 0.854520454287372
direct_recall_micro: 0.8891575091575091
f1_macro: 0.9030478739244744
f1_micro: 0.9348141274720176
precision_macro: 0.9104097648160918
precision_micro: 0.9421081855109734
recall_macro: 0.897883243699538
recall_micro: 0.9276321468650188

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7759152091306779
direct_f1_micro: 0.8585732165206508
direct_precision_macro: 0.825203362009079
direct_precision_micro: 0.8621044213412544
direct_recall_macro: 0.7608385893189487
direct_recall_micro: 0.855070821529745
f1_macro: 0.8492329745979204
f1_micro: 0.911722975968786
precision_macro: 0.8710864039012982
precision_micro: 0.9164772474038418
recall_macro: 0.8364714657000425
recall_micro: 0.9070177760134092

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7768231284087282
direct_f1_micro: 0.8574351978171897
direct_precision_macro: 0.8034445968787071
direct_precision_micro: 0.860271472567583
direct_recall_macro: 0.7657535002372484
direct_recall_micro: 0.8546175637393768
f1_macro: 0.8491473860952012
f1_micro: 0.9100702679937047
precision_macro: 0.8734382199395456
precision_micro: 0.9147134836467338
recall_macro: 0.8331959790232849
recall_micro: 0.905473953508888

====================================================================================================
RUN 24/30 | SEED 691
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 965.87it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.67      1405     0.8912     0.8981    +0.0069
Animal                                    0.37       184     0.9448     0.9451    +0.0003
Animate                                   0.41        13     0.7619     0.8182    +0.0563
Artefact                                  0.50       503     0.8916     0.8916    +0.0000
Body_Part                                 0.41        74     0.9167     0.9241    +0.0075
Comestible                                0.38       157     0.9587     0.9620    +0.0033
Communication                             0.46       534     0.8083     0.8115    +0.0032
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.71       340     0.8488     0.8597    +0.0109
Elongated                                 0.64       168     0.7546     0.7707    +0.0161
Eventive                                  0.60      1068     0.8852     0.8870    +0.0018
Feminine                                  0.25       204     0.9392     0.9420    +0.0029
Fluid                                     0.50        19     0.8947     0.8947    +0.0000
Garment                                   0.17        17     0.9091     0.9714    +0.0623
Inanimate                                 0.53      1511     0.9348     0.9353    +0.0005
Internal_Control                          0.23        21     0.3846     0.4286    +0.0440
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.37      1209     0.9211     0.9244    +0.0033
Machine                                   0.59       180     0.8750     0.8772    +0.0022
Masculine                                 0.19       671     0.9329     0.9388    +0.0058
Natural                                   0.40        79     0.8553     0.8774    +0.0222
Natural_Force                             0.17        35     0.7812     0.8267    +0.0454
Non_Rigid                                 0.46       335     0.8023     0.8058    +0.0034
Organisation                              0.44      1086     0.8994     0.9003    +0.0009
Plant                                     0.41        15     0.8966     0.9333    +0.0368
Point_in_Time                             0.80       336     0.8713     0.8728    +0.0016
Pointy                                    0.33        20     0.3750     0.7143    +0.3393
Question                                  0.20        33     0.8387     0.8657    +0.0270
Rigid                                     0.40       603     0.8709     0.8747    +0.0038
Solid                                     0.43      1409     0.8879     0.8908    +0.0029
Sound                                     0.79        42     0.7674     0.8493    +0.0819
Statement                                 0.39       264     0.7784     0.7828    +0.0044
Substance                                 0.54       217     0.8864     0.8899    +0.0035
Time                                      0.11        16     0.1176     0.5128    +0.3952
Unspecified_Gender_or_Neuter              0.52       677     0.8859     0.8873    +0.0013
Vehicle                                   0.69       100     0.9543     0.9641    +0.0098
Web_Location                              0.85        55     0.8571     0.9126    +0.0555

VALIDATION @ 0.5
direct_f1_macro: 0.8318643520972462
direct_f1_micro: 0.8887825350660825
direct_precision_macro: 0.8906988557857076
direct_precision_micro: 0.8932879449419078
direct_recall_macro: 0.8128863623835089
direct_recall_micro: 0.8843223443223444
f1_macro: 0.8876889682585453
f1_micro: 0.9349707839754092
precision_macro: 0.9004765052594786
precision_micro: 0.9423076923076923
recall_macro: 0.8770221172962732
recall_micro: 0.9277472448421719

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8659722214240181
direct_f1_micro: 0.8932452276064611
direct_precision_macro: 0.8874339172022006
direct_precision_micro: 0.8952170713760118
direct_recall_macro: 0.8570580147318781
direct_recall_micro: 0.8912820512820513
f1_macro: 0.9055881524664677
f1_micro: 0.9367476851851851
precision_macro: 0.9146424869499529
precision_micro: 0.9420083219367417
recall_macro: 0.8988319586478033
recall_micro: 0.9315454780882226

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7729859261783958
direct_f1_micro: 0.8587396635300827
direct_precision_macro: 0.8319602830307322
direct_precision_micro: 0.8644087256027555
direct_recall_macro: 0.7572861515413996
direct_recall_micro: 0.8531444759206799
f1_macro: 0.8522816490434548
f1_micro: 0.9110459433040078
precision_macro: 0.8729277140806118
precision_micro: 0.9177744953225012
recall_macro: 0.8386039133693328
recall_micro: 0.9044153323629306

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7756970093721639
direct_f1_micro: 0.8578920367097987
direct_precision_macro: 0.8002010806910748
direct_precision_micro: 0.8631566873136041
direct_recall_macro: 0.768845021805018
direct_recall_micro: 0.8526912181303116
f1_macro: 0.8461291949714297
f1_micro: 0.9111111111111111
precision_macro: 0.869871685203088
precision_micro: 0.9162317676970427
recall_macro: 0.8318306712943216
recall_micro: 0.9060473732962816

====================================================================================================
RUN 25/30 | SEED 743
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 968.11it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.56      1405     0.8893     0.8926    +0.0033
Animal                                    0.24       184     0.9415     0.9451    +0.0036
Animate                                   0.38        13     0.7619     0.8696    +0.1077
Artefact                                  0.45       503     0.8884     0.8940    +0.0056
Body_Part                                 0.25        74     0.9014     0.9103    +0.0089
Comestible                                0.50       157     0.9615     0.9615    +0.0000
Communication                             0.59       534     0.8072     0.8093    +0.0021
Currency                                  0.57        45     0.9890     1.0000    +0.0110
Duration                                  0.90       340     0.8394     0.8549    +0.0155
Elongated                                 0.66       168     0.7584     0.7638    +0.0053
Eventive                                  0.41      1068     0.8802     0.8850    +0.0048
Feminine                                  0.52       204     0.9372     0.9395    +0.0023
Fluid                                     0.08        19     0.8421     0.8837    +0.0416
Garment                                   0.22        17     0.9412     0.9444    +0.0033
Inanimate                                 0.38      1511     0.9310     0.9323    +0.0013
Internal_Control                          0.33        21     0.3846     0.4444    +0.0598
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.49      1209     0.9247     0.9249    +0.0001
Machine                                   0.50       180     0.8883     0.8883    +0.0000
Masculine                                 0.23       671     0.9279     0.9314    +0.0035
Natural                                   0.62        79     0.8627     0.8800    +0.0173
Natural_Force                             0.29        35     0.8235     0.8732    +0.0497
Non_Rigid                                 0.48       335     0.8023     0.8046    +0.0023
Organisation                              0.39      1086     0.8923     0.8996    +0.0073
Plant                                     0.50        15     0.8966     0.8966    +0.0000
Point_in_Time                             0.80       336     0.8648     0.8678    +0.0030
Pointy                                    0.36        20     0.5625     0.8205    +0.2580
Question                                  0.06        33     0.8525     0.8696    +0.0171
Rigid                                     0.42       603     0.8696     0.8777    +0.0082
Solid                                     0.53      1409     0.8891     0.8906    +0.0015
Sound                                     0.76        42     0.8312     0.8493    +0.0181
Statement                                 0.47       264     0.7743     0.7778    +0.0035
Substance                                 0.26       217     0.8822     0.8904    +0.0081
Time                                      0.17        16     0.3158     0.6000    +0.2842
Unspecified_Gender_or_Neuter              0.42       677     0.8824     0.8861    +0.0037
Vehicle                                   0.71       100     0.9645     0.9694    +0.0049
Web_Location                              0.89        55     0.8727     0.9020    +0.0292

VALIDATION @ 0.5
direct_f1_macro: 0.8441697720068072
direct_f1_micro: 0.8873385012919897
direct_precision_macro: 0.9025608341775201
direct_precision_micro: 0.8942708333333333
direct_recall_macro: 0.8192170811303434
direct_recall_micro: 0.8805128205128205
f1_macro: 0.893334295473359
f1_micro: 0.9329808558231415
precision_macro: 0.9104242736384317
precision_micro: 0.9420115566245271
recall_macro: 0.8791653247704413
recall_micro: 0.9241216585618508

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8710841048474078
direct_f1_micro: 0.8922250432350884
direct_precision_macro: 0.9004422252561134
direct_precision_micro: 0.8962815110519702
direct_recall_macro: 0.8569485035149097
direct_recall_micro: 0.8882051282051282
f1_macro: 0.9059930471789434
f1_micro: 0.9357572245962194
precision_macro: 0.9173362095969766
precision_micro: 0.9421854034187037
recall_macro: 0.8981110379586228
recall_micro: 0.9294161655108911

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.772479902882041
direct_f1_micro: 0.861317201232736
direct_precision_macro: 0.8058161330940835
direct_precision_micro: 0.8676555133954237
direct_recall_macro: 0.7517926705726893
direct_recall_micro: 0.855070821529745
f1_macro: 0.8461247242128226
f1_micro: 0.9138575113403896
precision_macro: 0.8775263303401983
precision_micro: 0.9214385005156719
recall_macro: 0.8261882423146515
recall_micro: 0.9064002470116007

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7604802219900282
direct_f1_micro: 0.8583152855351647
direct_precision_macro: 0.8153736418264109
direct_precision_micro: 0.8634330925352597
direct_recall_macro: 0.748268894277076
direct_recall_micro: 0.853257790368272
f1_macro: 0.8355747683890042
f1_micro: 0.9119566665186698
precision_macro: 0.8725428120311847
precision_micro: 0.9179888268156424
recall_macro: 0.8156585977947564
recall_micro: 0.9060032640818667

====================================================================================================
RUN 26/30 | SEED 797
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 969.95it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.66      1405     0.8976     0.8992    +0.0016
Animal                                    0.80       184     0.9311     0.9412    +0.0100
Animate                                   0.30        13     0.7619     0.8696    +0.1077
Artefact                                  0.50       503     0.8936     0.8936    +0.0000
Body_Part                                 0.13        74     0.8904     0.9299    +0.0395
Comestible                                0.42       157     0.9560     0.9595    +0.0035
Communication                             0.42       534     0.7973     0.8015    +0.0042
Currency                                  0.52        45     0.9890     1.0000    +0.0110
Duration                                  0.89       340     0.8516     0.8594    +0.0078
Elongated                                 0.55       168     0.7545     0.7692    +0.0147
Eventive                                  0.64      1068     0.8843     0.8849    +0.0007
Feminine                                  0.85       204     0.9386     0.9474    +0.0088
Fluid                                     0.50        19     0.9189     0.9189    +0.0000
Garment                                   0.50        17     0.9412     0.9412    +0.0000
Inanimate                                 0.42      1511     0.9320     0.9337    +0.0017
Internal_Control                          0.12        21     0.3704     0.4706    +0.1002
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.42      1209     0.9197     0.9198    +0.0001
Machine                                   0.60       180     0.8612     0.8786    +0.0174
Masculine                                 0.46       671     0.9318     0.9335    +0.0017
Natural                                   0.52        79     0.8645     0.8701    +0.0056
Natural_Force                             0.50        35     0.8571     0.8571    +0.0000
Non_Rigid                                 0.59       335     0.7919     0.7976    +0.0057
Organisation                              0.47      1086     0.8940     0.8952    +0.0012
Plant                                     0.40        15     0.9286     0.9333    +0.0048
Point_in_Time                             0.34       336     0.8571     0.8694    +0.0123
Pointy                                    0.19        20     0.3704     0.5769    +0.2066
Question                                  0.48        33     0.8333     0.8525    +0.0191
Rigid                                     0.34       603     0.8766     0.8814    +0.0049
Solid                                     0.49      1409     0.8893     0.8894    +0.0002
Sound                                     0.55        42     0.8000     0.8101    +0.0101
Statement                                 0.60       264     0.7724     0.7793    +0.0069
Substance                                 0.44       217     0.8778     0.8820    +0.0041
Time                                      0.22        16     0.0000     0.4828    +0.4828
Unspecified_Gender_or_Neuter              0.62       677     0.8835     0.8881    +0.0046
Vehicle                                   0.31       100     0.9495     0.9652    +0.0157
Web_Location                              0.73        55     0.8522     0.9159    +0.0637

VALIDATION @ 0.5
direct_f1_macro: 0.8302492436992469
direct_f1_micro: 0.887361728712653
direct_precision_macro: 0.8651764078849142
direct_precision_micro: 0.8902735786446427
direct_recall_macro: 0.8139148409986293
direct_recall_micro: 0.8844688644688645
f1_macro: 0.8889992461372226
f1_micro: 0.9333275407651983
precision_macro: 0.9050237378948848
precision_micro: 0.939476983178333
recall_macro: 0.879336690355359
recall_micro: 0.9272580784392714

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8621115851243077
direct_f1_micro: 0.8911532094905279
direct_precision_macro: 0.8764534009399481
direct_precision_micro: 0.8949390469154045
direct_recall_macro: 0.8536518190167225
direct_recall_micro: 0.8873992673992674
f1_macro: 0.900151736707487
f1_micro: 0.9341820976465641
precision_macro: 0.9069442999142117
precision_micro: 0.9415960245542239
recall_macro: 0.8962900327370281
recall_micro: 0.926884010013524

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7637362808021223
direct_f1_micro: 0.8565247096333409
direct_precision_macro: 0.805048509070682
direct_precision_micro: 0.8607392150131594
direct_recall_macro: 0.7497233176575147
direct_recall_micro: 0.8523512747875354
f1_macro: 0.8519493673897478
f1_micro: 0.9118962234913889
precision_macro: 0.872993961680669
precision_micro: 0.9153001821979292
recall_macro: 0.8385554327313752
recall_micro: 0.9085174893035155

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7831815743829842
direct_f1_micro: 0.8554134307903152
direct_precision_macro: 0.8085909654881545
direct_precision_micro: 0.8622078968573731
direct_recall_macro: 0.7677257079738946
direct_recall_micro: 0.8487252124645892
f1_macro: 0.8506068314098612
f1_micro: 0.9094789258402988
precision_macro: 0.8772885175413462
precision_micro: 0.9167749742302693
recall_macro: 0.8331023186363703
recall_micro: 0.9022980900710158

====================================================================================================
RUN 27/30 | SEED 853
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 943.64it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.41      1405     0.8928     0.8940    +0.0012
Animal                                    0.48       184     0.9441     0.9471    +0.0029
Animate                                   0.11        13     0.7619     0.8182    +0.0563
Artefact                                  0.41       503     0.8864     0.8876    +0.0011
Body_Part                                 0.29        74     0.8857     0.9315    +0.0458
Comestible                                0.36       157     0.9557     0.9560    +0.0003
Communication                             0.55       534     0.7942     0.8004    +0.0061
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.75       340     0.8493     0.8541    +0.0049
Elongated                                 0.66       168     0.7544     0.7631    +0.0087
Eventive                                  0.60      1068     0.8795     0.8821    +0.0026
Feminine                                  0.26       204     0.9301     0.9356    +0.0054
Fluid                                     0.24        19     0.8889     0.8947    +0.0058
Garment                                   0.29        17     0.9091     0.9412    +0.0321
Inanimate                                 0.39      1511     0.9319     0.9326    +0.0007
Internal_Control                          0.14        21     0.3846     0.5333    +0.1487
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.44      1209     0.9199     0.9202    +0.0004
Machine                                   0.25       180     0.8678     0.8719    +0.0041
Masculine                                 0.27       671     0.9270     0.9336    +0.0067
Natural                                   0.46        79     0.8947     0.8961    +0.0014
Natural_Force                             0.29        35     0.8116     0.8611    +0.0495
Non_Rigid                                 0.45       335     0.7994     0.8080    +0.0086
Organisation                              0.35      1086     0.8901     0.8946    +0.0045
Plant                                     0.30        15     0.8148     0.8750    +0.0602
Point_in_Time                             0.25       336     0.8631     0.8718    +0.0087
Pointy                                    0.32        20     0.6667     0.7273    +0.0606
Question                                  0.12        33     0.8136     0.8788    +0.0652
Rigid                                     0.35       603     0.8812     0.8841    +0.0030
Solid                                     0.49      1409     0.8899     0.8917    +0.0018
Sound                                     0.59        42     0.7711     0.7750    +0.0039
Statement                                 0.46       264     0.7557     0.7575    +0.0017
Substance                                 0.37       217     0.8758     0.8830    +0.0072
Time                                      0.16        16     0.1176     0.5333    +0.4157
Unspecified_Gender_or_Neuter              0.31       677     0.8809     0.8830    +0.0021
Vehicle                                   0.77       100     0.9652     0.9697    +0.0045
Web_Location                              0.81        55     0.8246     0.9038    +0.0793

VALIDATION @ 0.5
direct_f1_macro: 0.8345786197928724
direct_f1_micro: 0.8855527822639847
direct_precision_macro: 0.893908869289159
direct_precision_micro: 0.8873767838752391
direct_recall_macro: 0.8152322720423311
direct_recall_micro: 0.8837362637362637
f1_macro: 0.8890840846012629
f1_micro: 0.9316418992388547
precision_macro: 0.901908559945137
precision_micro: 0.9388697329203436
recall_macro: 0.8783528213635369
recall_micro: 0.9245245014818865

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8646231933797401
direct_f1_micro: 0.8898012571304
direct_precision_macro: 0.8757491244372841
direct_precision_micro: 0.8826497513155049
direct_recall_macro: 0.8620027803337521
direct_recall_micro: 0.8970695970695971
f1_macro: 0.901912926816364
f1_micro: 0.935942037319226
precision_macro: 0.8998898508528402
precision_micro: 0.9351891752133069
recall_macro: 0.9051449061422842
recall_micro: 0.9366961125658216

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7644671801884247
direct_f1_micro: 0.8541996830427893
direct_precision_macro: 0.7971795479545741
direct_precision_micro: 0.8533303177654642
direct_recall_macro: 0.7538021583101782
direct_recall_micro: 0.855070821529745
f1_macro: 0.8500172427975149
f1_micro: 0.9079961037811033
precision_macro: 0.8663562718226494
precision_micro: 0.911426158837385
recall_macro: 0.8389550713934087
recall_micro: 0.9045917692205901

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7778895446061089
direct_f1_micro: 0.8513664874551972
direct_precision_macro: 0.7868302436283926
direct_precision_micro: 0.8416565164433617
direct_recall_macro: 0.7816566241734332
direct_recall_micro: 0.8613031161473088
f1_macro: 0.8496376720437534
f1_micro: 0.9090190741675629
precision_macro: 0.859420043605567
precision_micro: 0.9047098916462776
recall_macro: 0.8476770767022618
recall_micro: 0.9133695028891535

====================================================================================================
RUN 28/30 | SEED 911
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 967.37it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.74      1405     0.8909     0.8935    +0.0026
Animal                                    0.41       184     0.9389     0.9448    +0.0059
Animate                                   0.15        13     0.7000     0.8148    +0.1148
Artefact                                  0.46       503     0.8905     0.8909    +0.0004
Body_Part                                 0.17        74     0.8936     0.9221    +0.0285
Comestible                                0.64       157     0.9437     0.9554    +0.0117
Communication                             0.36       534     0.7854     0.7964    +0.0110
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.81       340     0.8497     0.8606    +0.0109
Elongated                                 0.42       168     0.7515     0.7679    +0.0163
Eventive                                  0.44      1068     0.8799     0.8800    +0.0002
Feminine                                  0.93       204     0.9317     0.9391    +0.0074
Fluid                                     0.34        19     0.8649     0.8947    +0.0299
Garment                                   0.74        17     0.9143     0.9375    +0.0232
Inanimate                                 0.64      1511     0.9327     0.9343    +0.0016
Internal_Control                          0.26        21     0.2963     0.3871    +0.0908
Language                                  0.32         5     0.8889     0.9091    +0.0202
Location                                  0.48      1209     0.9239     0.9244    +0.0005
Machine                                   0.73       180     0.8725     0.8935    +0.0210
Masculine                                 0.76       671     0.9317     0.9347    +0.0029
Natural                                   0.67        79     0.8421     0.8767    +0.0346
Natural_Force                             0.12        35     0.7761     0.8219    +0.0458
Non_Rigid                                 0.64       335     0.8047     0.8103    +0.0057
Organisation                              0.41      1086     0.8939     0.8973    +0.0034
Plant                                     0.19        15     0.7692     0.8125    +0.0433
Point_in_Time                             0.78       336     0.8614     0.8721    +0.0107
Pointy                                    0.36        20     0.6471     0.7805    +0.1334
Question                                  0.19        33     0.8438     0.8824    +0.0386
Rigid                                     0.61       603     0.8775     0.8798    +0.0023
Solid                                     0.46      1409     0.8916     0.8934    +0.0018
Sound                                     0.60        42     0.7711     0.7949    +0.0238
Statement                                 0.66       264     0.7505     0.7659    +0.0154
Substance                                 0.53       217     0.8904     0.8919    +0.0015
Time                                      0.11        16     0.0000     0.5714    +0.5714
Unspecified_Gender_or_Neuter              0.20       677     0.8814     0.8854    +0.0041
Vehicle                                   0.26       100     0.9645     0.9700    +0.0055
Web_Location                              0.94        55     0.8727     0.9126    +0.0399

VALIDATION @ 0.5
direct_f1_macro: 0.8221290115807174
direct_f1_micro: 0.886049926578561
direct_precision_macro: 0.8548570516572784
direct_precision_micro: 0.8880058866813834
direct_recall_macro: 0.8036393305336336
direct_recall_micro: 0.884102564102564
f1_macro: 0.8855917545534081
f1_micro: 0.9325598889017475
precision_macro: 0.8999472854948862
precision_micro: 0.9376872727272727
recall_macro: 0.8741742648959694
recall_micro: 0.9274882743935775

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8594506498290713
direct_f1_micro: 0.890958621705198
direct_precision_macro: 0.8697263077469173
direct_precision_micro: 0.8954417640964926
direct_recall_macro: 0.8550404114606011
direct_recall_micro: 0.8865201465201465
f1_macro: 0.8989099763291142
f1_micro: 0.933907046824293
precision_macro: 0.9051714814848927
precision_micro: 0.9404744536196784
recall_macro: 0.894534774744052
recall_micro: 0.927430725405001

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7629113162070038
direct_f1_micro: 0.8613579403053088
direct_precision_macro: 0.7800592736624581
direct_precision_micro: 0.8659947314167907
direct_recall_macro: 0.7520920699655579
direct_recall_micro: 0.856770538243626
f1_macro: 0.8557772219766474
f1_micro: 0.9154039003394493
precision_macro: 0.87543313672244
precision_micro: 0.9208999196500313
recall_macro: 0.8424752219920913
recall_micro: 0.909973093379207

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7757784804629517
direct_f1_micro: 0.857566596315099
direct_precision_macro: 0.7952254961867201
direct_precision_micro: 0.8634275212497129
direct_recall_macro: 0.7689422123469839
direct_recall_micro: 0.8517847025495751
f1_macro: 0.850355967021136
f1_micro: 0.9120401189366707
precision_macro: 0.8718280339337406
precision_micro: 0.9176601920071444
recall_macro: 0.835277428820036
recall_micro: 0.9064884654404305

====================================================================================================
RUN 29/30 | SEED 971
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 922.46it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.55      1405     0.8909     0.8916    +0.0007
Animal                                    0.43       184     0.9389     0.9418    +0.0029
Animate                                   0.26        13     0.7000     0.8696    +0.1696
Artefact                                  0.29       503     0.8907     0.8956    +0.0049
Body_Part                                 0.16        74     0.9143     0.9272    +0.0129
Comestible                                0.39       157     0.9557     0.9625    +0.0068
Communication                             0.54       534     0.8089     0.8095    +0.0006
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.86       340     0.8328     0.8454    +0.0126
Elongated                                 0.40       168     0.7547     0.7781    +0.0234
Eventive                                  0.53      1068     0.8827     0.8827    +0.0001
Feminine                                  0.10       204     0.9298     0.9333    +0.0036
Fluid                                     0.35        19     0.8947     0.9231    +0.0283
Garment                                   0.17        17     0.9091     0.9444    +0.0354
Inanimate                                 0.47      1511     0.9370     0.9373    +0.0004
Internal_Control                          0.37        21     0.3846     0.4444    +0.0598
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.72      1209     0.9214     0.9226    +0.0012
Machine                                   0.21       180     0.8711     0.8824    +0.0113
Masculine                                 0.20       671     0.9272     0.9303    +0.0031
Natural                                   0.69        79     0.8571     0.8667    +0.0095
Natural_Force                             0.37        35     0.7761     0.8451    +0.0690
Non_Rigid                                 0.55       335     0.8036     0.8054    +0.0019
Organisation                              0.36      1086     0.8964     0.9040    +0.0076
Plant                                     0.39        15     0.8667     0.9032    +0.0366
Point_in_Time                             0.26       336     0.8640     0.8674    +0.0035
Pointy                                    0.32        20     0.6250     0.8205    +0.1955
Question                                  0.44        33     0.8197     0.8387    +0.0190
Rigid                                     0.38       603     0.8780     0.8801    +0.0020
Solid                                     0.36      1409     0.8893     0.8936    +0.0043
Sound                                     0.78        42     0.7654     0.8000    +0.0346
Statement                                 0.56       264     0.7675     0.7814    +0.0139
Substance                                 0.36       217     0.8818     0.8879    +0.0061
Time                                      0.17        16     0.2222     0.5161    +0.2939
Unspecified_Gender_or_Neuter              0.64       677     0.8806     0.8816    +0.0010
Vehicle                                   0.14       100     0.9592     0.9652    +0.0060
Web_Location                              0.93        55     0.8421     0.9126    +0.0705

VALIDATION @ 0.5
direct_f1_macro: 0.8361935406728114
direct_f1_micro: 0.8875382178509595
direct_precision_macro: 0.8971014797492397
direct_precision_micro: 0.8925687189745869
direct_recall_macro: 0.8134153373766159
direct_recall_micro: 0.8825641025641026
f1_macro: 0.8905330621210117
f1_micro: 0.9346049441855739
precision_macro: 0.9071047476144348
precision_micro: 0.9430513241153035
recall_macro: 0.8770469192669539
recall_micro: 0.9263085201277588

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8673393862552601
direct_f1_micro: 0.8922388497652582
direct_precision_macro: 0.8929353665201718
direct_precision_micro: 0.8934185397385045
direct_recall_macro: 0.8566178764618225
direct_recall_micro: 0.8910622710622711
f1_macro: 0.9061458554811749
f1_micro: 0.9375767824365144
precision_macro: 0.9138896435660671
precision_micro: 0.941892205831107
recall_macro: 0.9012156877484114
recall_micro: 0.9333007222398066

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7782294293233665
direct_f1_micro: 0.8606902836313931
direct_precision_macro: 0.8229572422714615
direct_precision_micro: 0.8652238635062407
direct_recall_macro: 0.7627515266551811
direct_recall_micro: 0.8562039660056657
f1_macro: 0.8523023629544918
f1_micro: 0.9135588705380927
precision_macro: 0.8747249094851296
precision_micro: 0.9195602627698083
recall_macro: 0.8370260484550888
recall_micro: 0.9076353050152177

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7745598556550345
direct_f1_micro: 0.8583229602806383
direct_precision_macro: 0.8041237758876258
direct_precision_micro: 0.8571590010170641
direct_recall_macro: 0.7705902965169668
direct_recall_micro: 0.8594900849858357
f1_macro: 0.8478144167648416
f1_micro: 0.9126723282232271
precision_macro: 0.868233016995317
precision_micro: 0.9128132721496647
recall_macro: 0.8382502804657206
recall_micro: 0.9125314278152706

====================================================================================================
RUN 30/30 | SEED 1031
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 958.03it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.70      1405     0.8887     0.8938    +0.0050
Animal                                    0.74       184     0.9474     0.9524    +0.0050
Animate                                   0.21        13     0.7000     0.9167    +0.2167
Artefact                                  0.54       503     0.8965     0.8990    +0.0025
Body_Part                                 0.16        74     0.9028     0.9139    +0.0111
Comestible                                0.50       157     0.9651     0.9651    +0.0000
Communication                             0.48       534     0.7993     0.8004    +0.0011
Currency                                  0.73        45     0.9783     0.9890    +0.0108
Duration                                  0.66       340     0.8382     0.8529    +0.0146
Elongated                                 0.64       168     0.7576     0.7673    +0.0097
Eventive                                  0.55      1068     0.8854     0.8856    +0.0003
Feminine                                  0.59       204     0.9458     0.9479    +0.0021
Fluid                                     0.41        19     0.9189     0.9231    +0.0042
Garment                                   0.73        17     0.9091     0.9375    +0.0284
Inanimate                                 0.68      1511     0.9331     0.9353    +0.0022
Internal_Control                          0.11        21     0.3846     0.4516    +0.0670
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.47      1209     0.9224     0.9235    +0.0011
Machine                                   0.59       180     0.8629     0.8830    +0.0202
Masculine                                 0.35       671     0.9302     0.9363    +0.0061
Natural                                   0.49        79     0.8889     0.8961    +0.0072
Natural_Force                             0.50        35     0.8824     0.8824    +0.0000
Non_Rigid                                 0.62       335     0.7953     0.8006    +0.0054
Organisation                              0.32      1086     0.8953     0.9008    +0.0055
Plant                                     0.64        15     0.8148     0.8462    +0.0313
Point_in_Time                             0.48       336     0.8635     0.8669    +0.0034
Pointy                                    0.28        20     0.3704     0.7805    +0.4101
Question                                  0.09        33     0.8571     0.8824    +0.0252
Rigid                                     0.32       603     0.8778     0.8796    +0.0018
Solid                                     0.69      1409     0.8870     0.8903    +0.0033
Sound                                     0.72        42     0.7750     0.8267    +0.0517
Statement                                 0.60       264     0.7617     0.7683    +0.0066
Substance                                 0.47       217     0.8955     0.9009    +0.0054
Time                                      0.18        16     0.1176     0.5333    +0.4157
Unspecified_Gender_or_Neuter              0.23       677     0.8803     0.8826    +0.0023
Vehicle                                   0.25       100     0.9596     0.9700    +0.0104
Web_Location                              0.74        55     0.8649     0.8932    +0.0283

VALIDATION @ 0.5
direct_f1_macro: 0.8311644872943318
direct_f1_micro: 0.8875643855776306
direct_precision_macro: 0.8998456875365435
direct_precision_micro: 0.89150036954915
direct_recall_macro: 0.8084730499186675
direct_recall_micro: 0.8836630036630037
f1_macro: 0.8876398905953131
f1_micro: 0.9331494519851927
precision_macro: 0.9082567930355797
precision_micro: 0.9416383452478613
recall_macro: 0.8734281059046293
recall_micro: 0.9248122464247691

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8695907631876179
direct_f1_micro: 0.8925369830671044
direct_precision_macro: 0.8948095361937038
direct_precision_micro: 0.8989373560228877
direct_recall_macro: 0.8515902589800701
direct_recall_micro: 0.8862271062271062
f1_macro: 0.9052369688205145
f1_micro: 0.9361221356354471
precision_macro: 0.9202087241953214
precision_micro: 0.9425113023187983
recall_macro: 0.8931490474788097
recall_micro: 0.9298190084309268

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7671789154532318
direct_f1_micro: 0.8606426618049225
direct_precision_macro: 0.8584839600832023
direct_precision_micro: 0.8654749627592528
direct_recall_macro: 0.7388069680634745
direct_recall_micro: 0.8558640226628895
f1_macro: 0.8491299303625598
f1_micro: 0.9136465522980981
precision_macro: 0.9055152211366365
precision_micro: 0.9194211184563159
recall_macro: 0.8238549037098073
recall_micro: 0.9079440695161219

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.764976315755845
direct_f1_micro: 0.8579905288982712
direct_precision_macro: 0.8069887816537362
direct_precision_micro: 0.8640542404045047
direct_recall_macro: 0.7472435576494125
direct_recall_micro: 0.8520113314447592
f1_macro: 0.8416102672649476
f1_micro: 0.9108191345578623
precision_macro: 0.8847283867831143
precision_micro: 0.915056539934111
recall_macro: 0.818811561303086
recall_micro: 0.9066207930836752

====================================================================================================
REPEATED-RUN TEST SUMMARY
====================================================================================================
Metric                          Mean         SD        Min        Max
----------------------------------------------------------------------
precision_micro               0.9154     0.0033     0.9047     0.9210
recall_micro                  0.9074     0.0046     0.8957     0.9156
f1_micro                      0.9114     0.0019     0.9054     0.9144
precision_macro               0.8711     0.0089     0.8511     0.8919
recall_macro                  0.8304     0.0107     0.8105     0.8477
f1_macro                      0.8451     0.0074     0.8279     0.8604

======================================================================================================================
REPEATED-RUN TEST PERFORMANCE BY COMPLETE FEATURE (AFTER INHERITANCE)
======================================================================================================================
Feature                               P mean     P SD   R mean     R SD  F1 mean    F1 SD   F1 min   F1 max  Support
--------------------------------------------------------------------------------------------------------------------
Abstract                              0.9406   0.0044   0.9308   0.0082   0.9357   0.0038   0.9267   0.9410     3091
Animal                                0.8612   0.0226   0.9399   0.0262   0.8985   0.0172   0.8654   0.9259       51
Animate                               0.9575   0.0042   0.9510   0.0064   0.9542   0.0028   0.9455   0.9578     1198
Artefact                              0.8901   0.0146   0.8878   0.0129   0.8888   0.0067   0.8682   0.9017      517
Body_Part                             0.8884   0.0345   0.8889   0.0393   0.8874   0.0165   0.8485   0.9118       33
Comestible                            0.8796   0.0115   0.9563   0.0118   0.9163   0.0054   0.9046   0.9288      155
Communication                         0.8856   0.0116   0.8831   0.0160   0.8842   0.0067   0.8714   0.8968      553
Concrete                              0.9397   0.0041   0.9474   0.0039   0.9435   0.0024   0.9370   0.9478     2216
Currency                              0.9943   0.0147   0.9681   0.0358   0.9807   0.0221   0.9362   1.0000       24
Duration                              0.8737   0.0433   0.8179   0.0678   0.8414   0.0193   0.8029   0.8704      153
Elongated                             0.8092   0.0391   0.5337   0.0573   0.6403   0.0347   0.5734   0.7303       95
Eventive                              0.8462   0.0145   0.8707   0.0159   0.8581   0.0061   0.8473   0.8722      679
Feminine                              0.9271   0.0386   0.9128   0.0291   0.9189   0.0168   0.8733   0.9462      141
Fluid                                 0.9141   0.0746   0.9300   0.0337   0.9198   0.0450   0.7308   0.9744       20
Garment                               0.9879   0.0314   0.8636   0.0572   0.9201   0.0325   0.8421   0.9524       11
Human                                 0.9622   0.0045   0.9544   0.0065   0.9583   0.0028   0.9489   0.9620     1106
Inanimate                             0.9073   0.0092   0.9178   0.0071   0.9125   0.0040   0.9032   0.9208     1005
Internal_Control                      0.9349   0.0049   0.9283   0.0067   0.9315   0.0029   0.9239   0.9366     2336
Language                              0.9167   0.2653   0.7667   0.3144   0.8167   0.2780   0.0000   1.0000        2
Location                              0.8980   0.0115   0.9016   0.0074   0.8997   0.0044   0.8918   0.9077      799
Machine                               0.9029   0.0228   0.8802   0.0228   0.8910   0.0125   0.8571   0.9141      202
Masculine                             0.9094   0.0095   0.9039   0.0098   0.9066   0.0045   0.8962   0.9154      556
Natural                               0.9524   0.0046   0.9454   0.0065   0.9488   0.0029   0.9388   0.9528     1240
Natural_Force                         0.8804   0.0530   0.6076   0.0438   0.7168   0.0278   0.6667   0.7692       22
Non_Rigid                             0.7468   0.0308   0.8002   0.0276   0.7717   0.0118   0.7495   0.8067      217
Organisation                          0.8517   0.0132   0.8651   0.0127   0.8582   0.0049   0.8460   0.8684      911
Plant                                 0.9733   0.0691   0.7000   0.0678   0.8121   0.0551   0.7273   0.9091        6
Point_in_Time                         0.8753   0.0403   0.8722   0.0381   0.8721   0.0069   0.8537   0.8848      174
Pointy                                0.1383   0.2088   0.0727   0.1024   0.0865   0.1077   0.0000   0.4000       11
Question                              0.8447   0.0587   0.9333   0.0306   0.8851   0.0308   0.8293   0.9444       18
Rigid                                 0.8704   0.0136   0.8419   0.0114   0.8558   0.0065   0.8404   0.8656      377
Rigidity                              0.8510   0.0130   0.8526   0.0162   0.8516   0.0059   0.8398   0.8642      594
Shape                                 0.7869   0.0366   0.5288   0.0568   0.6298   0.0351   0.5616   0.7182       96
Solid                                 0.9335   0.0066   0.9072   0.0133   0.9201   0.0056   0.9067   0.9304     1393
Sound                                 0.7591   0.0571   0.5538   0.0795   0.6351   0.0482   0.5306   0.7143       31
State_of_Matter                       0.9353   0.0064   0.9091   0.0130   0.9219   0.0054   0.9088   0.9321     1413
Statement                             0.7710   0.0431   0.6681   0.0439   0.7135   0.0145   0.6836   0.7452      160
Substance                             0.7822   0.0219   0.8899   0.0283   0.8320   0.0118   0.8119   0.8555      159
Time                                  0.9645   0.0090   0.9310   0.0354   0.9469   0.0157   0.9065   0.9643      337
Unspecified_Gender_or_Neuter          0.8189   0.0209   0.8446   0.0153   0.8312   0.0075   0.8163   0.8461      408
Vehicle                               0.8801   0.0411   0.9306   0.0323   0.9036   0.0207   0.8611   0.9459       37
Web_Location                          0.9450   0.0141   0.6895   0.0431   0.7964   0.0273   0.7363   0.8468      124

======================================================================================================================
REPEATED-RUN TEST PERFORMANCE BY INDEPENDENT NEURAL OUTPUT
======================================================================================================================
Feature                               P mean     P SD   R mean     R SD  F1 mean    F1 SD   F1 min   F1 max  Support
--------------------------------------------------------------------------------------------------------------------
Abstract                              0.8817   0.0181   0.8309   0.0156   0.8553   0.0064   0.8437   0.8736      733
Animal                                0.8612   0.0226   0.9399   0.0262   0.8985   0.0172   0.8654   0.9259       51
Animate                               0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000   0.0000        2
Artefact                              0.8211   0.0237   0.8436   0.0191   0.8318   0.0111   0.8057   0.8557      304
Body_Part                             0.8884   0.0345   0.8889   0.0393   0.8874   0.0165   0.8485   0.9118       33
Comestible                            0.8796   0.0115   0.9563   0.0118   0.9163   0.0054   0.9046   0.9288      155
Communication                         0.7758   0.0195   0.8364   0.0238   0.8045   0.0091   0.7840   0.8310      375
Currency                              0.9943   0.0147   0.9681   0.0358   0.9807   0.0221   0.9362   1.0000       24
Duration                              0.8737   0.0433   0.8179   0.0678   0.8414   0.0193   0.8029   0.8704      153
Elongated                             0.8092   0.0391   0.5337   0.0573   0.6403   0.0347   0.5734   0.7303       95
Eventive                              0.8462   0.0145   0.8707   0.0159   0.8581   0.0061   0.8473   0.8722      679
Feminine                              0.9271   0.0386   0.9128   0.0291   0.9189   0.0168   0.8733   0.9462      141
Fluid                                 0.9141   0.0746   0.9300   0.0337   0.9198   0.0450   0.7308   0.9744       20
Garment                               0.9879   0.0314   0.8636   0.0572   0.9201   0.0325   0.8421   0.9524       11
Inanimate                             0.9073   0.0092   0.9178   0.0071   0.9125   0.0040   0.9032   0.9208     1005
Internal_Control                      0.4153   0.2770   0.1375   0.0601   0.1822   0.0635   0.0000   0.2727       16
Language                              0.9167   0.2653   0.7667   0.3144   0.8167   0.2780   0.0000   1.0000        2
Location                              0.8980   0.0115   0.9016   0.0074   0.8997   0.0044   0.8918   0.9077      799
Machine                               0.8881   0.0290   0.8588   0.0288   0.8724   0.0124   0.8454   0.8951      165
Masculine                             0.9094   0.0095   0.9039   0.0098   0.9066   0.0045   0.8962   0.9154      556
Natural                               0.7352   0.0520   0.7270   0.0285   0.7296   0.0239   0.6905   0.7949       42
Natural_Force                         0.8804   0.0530   0.6076   0.0438   0.7168   0.0278   0.6667   0.7692       22
Non_Rigid                             0.7468   0.0308   0.8002   0.0276   0.7717   0.0118   0.7495   0.8067      217
Organisation                          0.8517   0.0132   0.8651   0.0127   0.8582   0.0049   0.8460   0.8684      911
Plant                                 0.9733   0.0691   0.7000   0.0678   0.8121   0.0551   0.7273   0.9091        6
Point_in_Time                         0.8753   0.0403   0.8722   0.0381   0.8721   0.0069   0.8537   0.8848      174
Pointy                                0.1383   0.2088   0.0727   0.1024   0.0865   0.1077   0.0000   0.4000       11
Question                              0.8447   0.0587   0.9333   0.0306   0.8851   0.0308   0.8293   0.9444       18
Rigid                                 0.8704   0.0136   0.8419   0.0114   0.8558   0.0065   0.8404   0.8656      377
Solid                                 0.8605   0.0187   0.8343   0.0176   0.8468   0.0060   0.8354   0.8595      799
Sound                                 0.7591   0.0571   0.5538   0.0795   0.6351   0.0482   0.5306   0.7143       31
Statement                             0.7710   0.0431   0.6681   0.0439   0.7135   0.0145   0.6836   0.7452      160
Substance                             0.7822   0.0219   0.8899   0.0283   0.8320   0.0118   0.8119   0.8555      159
Time                                  0.4206   0.0637   0.7233   0.0774   0.5269   0.0433   0.4375   0.6667       10
Unspecified_Gender_or_Neuter          0.8189   0.0209   0.8446   0.0153   0.8312   0.0075   0.8163   0.8461      408
Vehicle                               0.8801   0.0411   0.9306   0.0323   0.9036   0.0207   0.8611   0.9459       37
Web_Location                          0.9450   0.0141   0.6895   0.0431   0.7964   0.0273   0.7363   0.8468      124

====================================================================================================
SENTENCE-CLUSTER BOOTSTRAP ON HELD-OUT TEST SET
====================================================================================================
Bootstrap samples: 2,000
Confidence level : 95.0%
Bootstrap unit   : sentence (all eligible NOUN/PROPN targets from a sampled sentence move together)

Metric                      Run mean     Run SD   95% CI low  95% CI high
------------------------------------------------------------------------------
precision_micro               0.9154     0.0033       0.9084       0.9221
recall_micro                  0.9074     0.0046       0.9000       0.9143
f1_micro                      0.9114     0.0019       0.9052       0.9172
precision_macro               0.8711     0.0089       0.8435       0.8806
recall_macro                  0.8304     0.0107       0.8046       0.8460
f1_macro                      0.8451     0.0074       0.8185       0.8555

====================================================================================================
OUTPUTS
====================================================================================================
Fixed sentence split:
  /home/mark/verbnet-roberta/models/roberta_semantic_features/sentence_split.json
Semantic feature metadata:
  /home/mark/verbnet-roberta/models/roberta_semantic_features/semantic_features.json
Per-run results:
  /home/mark/verbnet-roberta/models/roberta_semantic_features/runs
Repeated-run summary:
  /home/mark/verbnet-roberta/models/roberta_semantic_features/repeated_run_results.json
Test bootstrap confidence intervals:
  /home/mark/verbnet-roberta/models/roberta_semantic_features/test_bootstrap_confidence_intervals.json
Neutral reference model (first predeclared seed; not best-test selected):
  /home/mark/verbnet-roberta/models/roberta_semantic_features/reference_model

<h1>Using learning_rate scheduler</h1>

In [1]:
#!/usr/bin/env python3
"""
Fine-tune RoBERTa for hierarchical multi-label semantic feature tagging of
NOUN/PROPN tokens.

Compatible with Python 3.9.21.

Key design changes
------------------
1. The model is trained only on independent semantic features. For each token,
   any feature that can be inherited from a more specific present feature is
   removed from the neural target. This is a per-token reduction rather than a
   global "terminal leaf only" rule, so features such as Human, Time, Shape,
   Communication, etc. can still be predicted directly when they are the most
   specific available feature for that token.

2. All inherited features are reconstructed deterministically from
   FEATURE_PARENTS for validation, testing, reporting, and later inference.

3. A separate sigmoid threshold is optimised for every neural output using the
   validation split only. The selected thresholds are frozen before the test
   split is evaluated and are saved to prediction_thresholds.json.

4. Train/validation splitting is performed at SENTENCE level with iterative
   multilabel stratification over sentence-level independent-feature presence.
   The split is fixed across repeated fine-tuning runs.

5. Fine-tuning is repeated over a predeclared list of random seeds. The same
   split is used for every run, and results are summarised with mean and SD.

6. The official test corpus may contain a direct independent target that never
   occurred independently in training. Such a label is never added from test
   data. Complete test truth is read directly from source annotations.

7. Held-out test uncertainty is estimated with a SENTENCE-CLUSTER bootstrap.
   All supervised noun/proper-noun targets from a sampled sentence move together.

Tagged data:
    Training/validation:
        ewt_train_wordnet_wsd_features_wordnet_fixed.jsonl
    Test:
        ewt_test_wordnet_wsd_features_wordnet_fixed.jsonl

Sentence/token sources:
    Training/validation:
        UD_English-EWT-master/
        UD_English-EWT-master/
        en_ewt-ud-train.conllu
    Test:
        UD_English-EWT-master/
        UD_English-EWT-master/
        en_ewt-ud-test.conllu

The validation split is created only from the training corpus. The official
test corpus remains untouched until final evaluation.

Loss:
    BCEWithLogitsLoss over INDEPENDENT feature labels only.

Headline metrics:
    Computed after deterministic hierarchy expansion, so they describe the
    complete semantic feature sets rather than only the neural outputs.

Requirements:
    python -m pip install torch transformers datasets accelerate conllu scikit-learn iterative-stratification

CUDA is required.
"""

from __future__ import annotations

import gc
import json
import shutil
from collections import Counter, defaultdict
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Set, Tuple

import numpy as np
import torch
import torch.nn as nn

from conllu import parse_incr
from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit
from sklearn.metrics import precision_recall_fscore_support
from torch.utils.data import Dataset

from transformers import (
    AutoModelForTokenClassification,
    AutoTokenizer,
    Trainer,
    TrainingArguments,
    set_seed,
)


# =============================================================================
# Configuration
# =============================================================================

TRAIN_JSONL_PATH = Path(
    "../data/ewt_train_wordnet_wsd_features_wordnet_fixed.jsonl"
    #"ewt_train_wordnet_wsd_features_fully_tagged_llm_reviewed.jsonl"
)

TEST_JSONL_PATH = Path(
    "../data/ewt_test_wordnet_wsd_features_wordnet_fixed.jsonl"
    #"ewt_test_wordnet_wsd_features_fully_tagged_llm_reviewed.jsonl"
)

TRAIN_CONLLU_PATH = Path(
    "../data/UD_English-EWT-master/"
    "UD_English-EWT-master/"
    "en_ewt-ud-train.conllu"
)

TEST_CONLLU_PATH = Path(
    "../data/UD_English-EWT-master/"
    "UD_English-EWT-master/"
    "en_ewt-ud-test.conllu"
)

# MODEL_NAME = "FacebookAI/roberta-base"
MODEL_NAME = "FacebookAI/roberta-large"

OUTPUT_DIR = Path("../models/roberta_semantic_features")

# Validation is sampled only from eligible TRAINING sentences.
# Stratification is performed at SENTENCE level using the multilabel feature
# presence vector for each sentence. The separate official test file is never
# split and is used only for final evaluation.
VALIDATION_FRACTION = 0.20

# Fixed seed used ONLY to create the sentence-level train/validation split.
# Keeping this fixed across model runs means repeated runs measure stochastic
# fine-tuning variation rather than variation in the validation partition.
SPLIT_SEED = 42

# Repeated fine-tuning seeds. Use the same list when comparing model variants.
# Thirty runs follow the experiment-design recommendation; reduce this list if
# RoBERTa-large makes 30 runs computationally impractical, and report the actual
# number used.
RUN_SEEDS = [
    11, 23, 37, 53, 71, 89, 107, 127, 149, 173,
    197, 223, 251, 281, 313, 347, 383, 421, 461, 503,
    547, 593, 641, 691, 743, 797, 853, 911, 971, 1031,
]

# The multilabel stratifier is retried with deterministic derived seeds until
# every independent feature still has at least this many positive token targets
# in the TRAIN subset. This prevents a rare direct target from disappearing.
MIN_TRAIN_POSITIVES_PER_FEATURE = 1
MAX_STRATIFICATION_ATTEMPTS = 200

# Sentence-cluster bootstrap for uncertainty in the held-out test sample.
# The same sampled test sentences are used for every run within each bootstrap
# replicate, and the statistic is the mean metric across run seeds.
TEST_BOOTSTRAP_SAMPLES = 2000
TEST_BOOTSTRAP_CONFIDENCE = 0.95
TEST_BOOTSTRAP_SEED = 20260926

# Saving 30 RoBERTa-large models would use a great deal of disk space. The first
# run is therefore saved as a neutral REFERENCE model; it is not selected for
# having the best test result. Metrics and thresholds are saved for every run.
SAVE_REFERENCE_MODEL = True

MAX_LENGTH = 256

LEARNING_RATE = 3.5e-5
WEIGHT_DECAY = 0.01

TRAIN_BATCH_SIZE = 8
EVAL_BATCH_SIZE = 16

GRADIENT_ACCUMULATION_STEPS = 2

NUM_EPOCHS = 5

# Threshold used during epoch-by-epoch Trainer evaluation. Final thresholds are
# optimised per independent feature on the validation set after training.
DEFAULT_PREDICTION_THRESHOLD = 0.5

# Validation-only threshold search grid.
THRESHOLD_MIN = 0.05
THRESHOLD_MAX = 0.95
THRESHOLD_STEP = 0.01

# Only these POS categories receive feature supervision.
TARGET_POS = {"NOUN", "PROPN"}

# A NOUN/PROPN with no features is considered a failed source annotation rather
# than a valid all-negative target.
EXCLUDE_EMPTY_FEATURE_RECORDS = True

# Optional per-feature switches. Any feature not listed here is enabled.
# Set a feature to False to remove it from:
#   - sentence-level stratification,
#   - neural training targets,
#   - threshold calibration,
#   - hierarchy-expanded gold/predicted feature sets,
#   - per-feature and aggregate evaluation, and
#   - the sentence-cluster bootstrap.
#
# Disabled intermediate hierarchy nodes are skipped but their enabled ancestors
# are still inherited. For example, if Human were disabled, Feminine would still
# inherit Animate/Natural/Concrete/Internal_Control via the hierarchy.
FEATURE_SWITCHES: Dict[str, bool] = {
    "State": False,
    "State_of_Matter": False,
    "Shape": False,
    "Rigidity": False,
}

# Aggregate per-feature test tables are always printed after all repeated runs.
# Set this to True only if you also want the two full per-feature tables printed
# after EVERY run (very verbose for 30 runs).
PRINT_PER_RUN_FEATURE_TABLES = False

EVAL_STRATEGY = "epoch"

SPLIT_PATH = OUTPUT_DIR / "sentence_split.json"
LABELS_PATH = OUTPUT_DIR / "semantic_features.json"
RUNS_DIR = OUTPUT_DIR / "runs"
REFERENCE_MODEL_DIR = OUTPUT_DIR / "reference_model"
REPEATED_RESULTS_PATH = OUTPUT_DIR / "repeated_run_results.json"
BOOTSTRAP_RESULTS_PATH = OUTPUT_DIR / "test_bootstrap_confidence_intervals.json"


# =============================================================================
# Feature hierarchy
# =============================================================================

def is_feature_enabled(feature: str) -> bool:
    """Return whether *feature* participates in this experiment."""

    return bool(FEATURE_SWITCHES.get(feature, True))


def validate_feature_switches(
    train_tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    test_tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> None:
    """Fail early on misspelled feature-switch names and report disabled labels."""

    observed: Set[str] = set()

    for source in (train_tagged_records, test_tagged_records):
        for sentence_records in source.values():
            for record in sentence_records.values():
                raw = record.get("features", [])
                if isinstance(raw, list):
                    observed.update(
                        str(feature).strip()
                        for feature in raw
                        if str(feature).strip()
                    )

    known = set(observed) | set(FEATURE_PARENTS)
    for parents in FEATURE_PARENTS.values():
        known.update(parents)

    unknown = sorted(set(FEATURE_SWITCHES) - known)
    if unknown:
        raise ValueError(
            "FEATURE_SWITCHES contains unknown feature name(s): "
            + ", ".join(unknown)
        )

    disabled = sorted(
        feature for feature, enabled in FEATURE_SWITCHES.items() if not enabled
    )

    print("=" * 80)
    print("FEATURE SWITCHES")
    print("=" * 80)
    if disabled:
        print("Disabled features: " + ", ".join(disabled))
    else:
        print("Disabled features: none")
    print("All unlisted features are enabled.")
    print()


# child -> direct parent(s)
FEATURE_PARENTS: Dict[str, Set[str]] = {
    "Organisation": {
        "Internal_Control",
        "Abstract",
    },
    "Natural_Force": {
        "Internal_Control",
    },
    "Animate": {
        "Internal_Control",
        "Natural",
    },
    "Human": {
        "Animate",
    },
    "Feminine": {
        "Human",
    },
    "Masculine": {
        "Human",
    },
    "Unspecified_Gender_or_Neuter": {
        "Human",
    },
    "Animal": {
        "Animate",
    },
    "Plant": {
        "Animate",
    },
    "Body_Part": {
        "Animate",
    },
    "Machine": {
        "Internal_Control",
        "Artefact",
    },
    "Vehicle": {
        "Machine",
    },
    "Natural": {
        "Concrete",
    },
    "Artefact": {
        "Concrete",
    },
    "Comestible": {
        "Concrete",
    },
    "Substance": {
        "Concrete",
    },
    "State_of_Matter": {
        "Concrete",
    },
    "Inanimate": {
        "Concrete",
    },
    "Garment": {
        "Artefact",
    },
    "Solid": {
        "State_of_Matter",
    },
    "Fluid": {
        "State_of_Matter",
    },
    "Rigidity": {
        "Solid",
    },
    "Shape": {
        "Solid",
    },
    "Rigid": {
        "Rigidity",
    },
    "Non_Rigid": {
        "Rigidity",
    },
    "Elongated": {
        "Shape",
    },
    "Pointy": {
        "Shape",
    },
    "Point_in_Time": {
        "Time",
    },
    "Duration": {
        "Time",
    },
    "Time": {
        "Abstract",
    },
    "Language": {
        "Abstract",
    },
    "Sound": {
        "Abstract",
    },
    "Communication": {
        "Abstract",
    },
    "Eventive": {
        "Abstract",
    },
    "Statement": {
        "Communication",
    },
    "Question": {
        "Communication",
    },
}


def validate_feature_hierarchy() -> None:
    """Fail early if FEATURE_PARENTS contains a cycle or invalid name."""

    all_features: Set[str] = set(FEATURE_PARENTS)

    for parents in FEATURE_PARENTS.values():
        all_features.update(parents)

    for feature in all_features:
        if not isinstance(feature, str) or not feature.strip():
            raise ValueError(
                "FEATURE_PARENTS contains an empty or non-string feature name."
            )

    visiting: Set[str] = set()
    visited: Set[str] = set()

    def visit(feature: str) -> None:
        if feature in visited:
            return

        if feature in visiting:
            raise ValueError(
                f"Cycle detected in FEATURE_PARENTS involving {feature!r}."
            )

        visiting.add(feature)

        for parent in FEATURE_PARENTS.get(feature, set()):
            visit(parent)

        visiting.remove(feature)
        visited.add(feature)

    for feature in sorted(all_features):
        visit(feature)


@lru_cache(maxsize=None)
def get_feature_ancestors(feature: str) -> frozenset:
    """Return every direct and indirect parent of *feature*."""

    ancestors: Set[str] = set()

    for parent in FEATURE_PARENTS.get(feature, set()):
        if is_feature_enabled(parent):
            ancestors.add(parent)
        # Traverse even through a disabled intermediate node so enabled
        # grandparents remain inherited.
        ancestors.update(get_feature_ancestors(parent))

    return frozenset(ancestors)


def expand_feature_hierarchy(features: Iterable[str]) -> Set[str]:
    """Add every deterministic ancestor required by FEATURE_PARENTS."""

    expanded: Set[str] = {
        feature for feature in features if is_feature_enabled(feature)
    }

    for feature in list(expanded):
        expanded.update(get_feature_ancestors(feature))

    return expanded


def reduce_to_independent_features(features: Iterable[str]) -> Set[str]:
    """
    Reduce a complete feature set to the features that must be predicted.

    A feature is redundant when it is an ancestor of another feature present
    for the same token. Such an ancestor can be reconstructed deterministically.

    Examples:
        {Human, Animate, Natural, Concrete, Internal_Control}
            -> {Human}

        {Feminine, Human, Animate, Natural, Concrete, Internal_Control}
            -> {Feminine}

        {Statement, Communication, Abstract, Time}
            -> {Statement, Time}

    This is deliberately PER TOKEN. It is not the same as training only labels
    that are global terminal leaves in the ontology. A generic Human can still
    be a direct neural target if no more specific Human child is present.
    """

    feature_set = set(features)

    inherited_from_other_features: Set[str] = set()

    for feature in feature_set:
        inherited_from_other_features.update(
            get_feature_ancestors(feature)
        )

    return feature_set - inherited_from_other_features


def missing_hierarchy_features(features: Iterable[str]) -> Set[str]:
    """Return ancestors required by the hierarchy but absent from *features*."""

    feature_set = set(features)
    return expand_feature_hierarchy(feature_set) - feature_set


# =============================================================================
# CUDA
# =============================================================================

def check_cuda() -> None:
    """Require CUDA rather than silently falling back to the CPU."""

    if not torch.cuda.is_available():
        raise RuntimeError(
            "CUDA is not available. This script is configured to require "
            "a CUDA-capable GPU."
        )

    print("=" * 80)
    print("CUDA")
    print("=" * 80)
    print(f"PyTorch version: {torch.__version__}")
    print(f"CUDA available: {torch.cuda.is_available()}")
    print(f"CUDA runtime: {torch.version.cuda}")
    print(f"GPU: {torch.cuda.get_device_name(0)}")

    props = torch.cuda.get_device_properties(0)

    print(
        "VRAM: "
        f"{props.total_memory / (1024 ** 3):.2f} GiB"
    )
    print()


# =============================================================================
# Load CoNLL-U
# =============================================================================

def load_conllu(path: Path) -> List[Any]:
    """Load all CoNLL-U sentences."""

    if not path.exists():
        raise FileNotFoundError(
            f"Could not find CoNLL-U file:\n{path.resolve()}"
        )

    sentences: List[Any] = []

    with path.open("r", encoding="utf-8") as handle:
        for sentence in parse_incr(handle):
            sentences.append(sentence)

    return sentences


def get_sentence_words(sentence: Any) -> Tuple[List[str], List[int]]:
    """
    Return ordinary integer-ID tokens and their original CoNLL-U token IDs.

    Multiword-token placeholder rows and empty nodes are excluded.
    """

    words: List[str] = []
    token_ids: List[int] = []

    for token in sentence:
        token_id = token.get("id")

        if not isinstance(token_id, int):
            continue

        form = token.get("form")

        if form is None:
            continue

        words.append(str(form))
        token_ids.append(token_id)

    return words, token_ids


# =============================================================================
# Load tagged JSONL
# =============================================================================

def load_tagged_records(
    path: Path,
) -> Dict[int, Dict[int, Dict[str, Any]]]:
    """
    Return:

        sentence_index
            -> token_id
                -> JSONL record

    Only NOUN and PROPN records are retained.
    """

    if not path.exists():
        raise FileNotFoundError(
            f"Could not find tagged JSONL:\n{path.resolve()}"
        )

    records: Dict[int, Dict[int, Dict[str, Any]]] = defaultdict(dict)

    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            line = line.strip()

            if not line:
                continue

            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                print(
                    "Warning: invalid JSON on line "
                    f"{line_number}: {exc}"
                )
                continue

            if record.get("upos") not in TARGET_POS:
                continue

            sentence_index = record.get("sentence_index")
            token_id = record.get("token_id")

            if not isinstance(sentence_index, int):
                continue

            if not isinstance(token_id, int):
                continue

            records[sentence_index][token_id] = record

    return dict(records)


# =============================================================================
# Labels
# =============================================================================

def clean_features(record: Dict[str, Any]) -> List[str]:
    """Return unique, non-empty COMPLETE feature names from a JSONL record."""

    raw = record.get("features", [])

    if not isinstance(raw, list):
        return []

    return sorted(
        {
            str(feature).strip()
            for feature in raw
            if (
                str(feature).strip()
                and is_feature_enabled(str(feature).strip())
            )
        }
    )


def get_independent_record_features(record: Dict[str, Any]) -> List[str]:
    """Return the per-token minimal feature set that the model must predict."""

    return sorted(
        reduce_to_independent_features(
            clean_features(record)
        )
    )


def build_full_label_vocabulary(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    training_sentence_indices: Sequence[int],
) -> List[str]:
    """
    Build the COMPLETE evaluation vocabulary from training data only.

    Deterministic ancestors are included even if a training record omitted one,
    although hierarchy closure is separately verified and should normally make
    this addition unnecessary.
    """

    labels: Set[str] = set()

    for sentence_index in training_sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            features = clean_features(record)
            labels.update(features)
            labels.update(expand_feature_hierarchy(features))

    if not labels:
        raise RuntimeError(
            "No semantic features were found in the training split."
        )

    return sorted(labels)


def build_prediction_label_vocabulary(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    training_sentence_indices: Sequence[int],
) -> List[str]:
    """Build the neural-output vocabulary from independent training targets."""

    labels: Set[str] = set()

    for sentence_index in training_sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            labels.update(
                get_independent_record_features(record)
            )

    if not labels:
        raise RuntimeError(
            "No independent semantic features were found in the training split."
        )

    return sorted(labels)


# =============================================================================
# Sentence selection and splitting
# =============================================================================

def get_eligible_sentence_indices(
    sentences: Sequence[Any],
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> List[int]:
    """Eligible sentences contain at least one non-empty NOUN/PROPN target."""

    eligible: List[int] = []

    for sentence_index in range(len(sentences)):
        token_records = tagged_records.get(sentence_index, {})

        valid_records = [
            record
            for record in token_records.values()
            if clean_features(record)
        ]

        if valid_records:
            eligible.append(sentence_index)

    return eligible


def get_sentence_independent_feature_counts(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    sentence_index: int,
) -> Counter:
    """Count independent positive token targets in one source sentence."""

    counts: Counter = Counter()

    for record in tagged_records.get(sentence_index, {}).values():
        if not clean_features(record):
            continue

        for feature in get_independent_record_features(record):
            counts[feature] += 1

    return counts


def build_sentence_multilabel_matrix(
    eligible_indices: Sequence[int],
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> Tuple[np.ndarray, List[str], Dict[int, Counter]]:
    """
    Build one multilabel stratification row per SENTENCE.

    y_sentence[sentence, feature] is 1 when at least one eligible NOUN/PROPN
    token in that sentence has the independent feature. Token counts are kept
    separately for the post-split training-coverage constraint.
    """

    sentence_feature_counts: Dict[int, Counter] = {
        sentence_index: get_sentence_independent_feature_counts(
            tagged_records,
            sentence_index,
        )
        for sentence_index in eligible_indices
    }

    stratification_labels = sorted(
        {
            feature
            for counts in sentence_feature_counts.values()
            for feature, count in counts.items()
            if count > 0
        }
    )

    if not stratification_labels:
        raise RuntimeError(
            "No independent semantic features were found in eligible "
            "training sentences."
        )

    label2column = {
        label: column
        for column, label in enumerate(stratification_labels)
    }

    matrix = np.zeros(
        (len(eligible_indices), len(stratification_labels)),
        dtype=np.int8,
    )

    for row, sentence_index in enumerate(eligible_indices):
        for feature in sentence_feature_counts[sentence_index]:
            matrix[row, label2column[feature]] = 1

    return matrix, stratification_labels, sentence_feature_counts


def _sentence_prevalence_error(
    y_all: np.ndarray,
    validation_rows: np.ndarray,
    validation_fraction: float,
) -> float:
    """
    Score how closely validation sentence-level label prevalences match target.

    Lower is better. The score is used only to choose among deterministic
    iterative-stratification attempts that satisfy the training-coverage rule.
    """

    total_support = y_all.sum(axis=0).astype(np.float64)
    validation_support = y_all[validation_rows].sum(axis=0).astype(np.float64)

    target_support = total_support * float(validation_fraction)

    # Scale by at least one expected example so rare and common labels both
    # contribute without allowing extremely common labels to dominate.
    scale = np.maximum(target_support, 1.0)

    return float(
        np.mean(
            np.abs(validation_support - target_support) / scale
        )
    )


def make_train_validation_split(
    eligible_indices: Sequence[int],
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> Dict[str, Any]:
    """
    Create a SENTENCE-LEVEL multilabel-stratified split from TRAINING only.

    Each sentence receives a binary vector indicating which independent feature
    labels occur anywhere among its eligible NOUN/PROPN tokens. Iterative
    multilabel stratification then assigns whole sentences to train/validation.

    The split is retried deterministically when necessary so that every
    independent feature retains at least MIN_TRAIN_POSITIVES_PER_FEATURE
    positive TOKEN targets in the training subset.

    The official test corpus is deliberately not accepted by this function, so
    test labels cannot influence the split.
    """

    if not 0.0 < VALIDATION_FRACTION < 1.0:
        raise ValueError(
            "VALIDATION_FRACTION must be strictly between 0 and 1."
        )

    if MIN_TRAIN_POSITIVES_PER_FEATURE < 1:
        raise ValueError(
            "MIN_TRAIN_POSITIVES_PER_FEATURE must be at least 1."
        )

    if MAX_STRATIFICATION_ATTEMPTS < 1:
        raise ValueError(
            "MAX_STRATIFICATION_ATTEMPTS must be at least 1."
        )

    eligible_indices = list(eligible_indices)

    if len(eligible_indices) < 2:
        raise RuntimeError(
            "Need at least two eligible training sentences to create a "
            "train/validation split."
        )

    (
        sentence_matrix,
        stratification_labels,
        sentence_feature_counts,
    ) = build_sentence_multilabel_matrix(
        eligible_indices,
        tagged_records,
    )

    all_token_counts: Counter = Counter()

    for counts in sentence_feature_counts.values():
        all_token_counts.update(counts)

    x_dummy = np.zeros((len(eligible_indices), 1), dtype=np.int8)

    best_candidate: Optional[Dict[str, Any]] = None
    rejected_for_coverage = 0

    for attempt in range(MAX_STRATIFICATION_ATTEMPTS):
        attempt_seed = SPLIT_SEED + attempt

        splitter = MultilabelStratifiedShuffleSplit(
            n_splits=1,
            test_size=VALIDATION_FRACTION,
            random_state=attempt_seed,
        )

        train_rows, validation_rows = next(
            splitter.split(x_dummy, sentence_matrix)
        )

        train_indices = [
            eligible_indices[int(row)]
            for row in train_rows
        ]
        validation_indices = [
            eligible_indices[int(row)]
            for row in validation_rows
        ]

        train_token_counts: Counter = Counter()

        for sentence_index in train_indices:
            train_token_counts.update(
                sentence_feature_counts[sentence_index]
            )

        missing_or_undercovered = sorted(
            feature
            for feature, total_count in all_token_counts.items()
            if (
                total_count > 0
                and train_token_counts[feature]
                < MIN_TRAIN_POSITIVES_PER_FEATURE
            )
        )

        if missing_or_undercovered:
            rejected_for_coverage += 1
            continue

        prevalence_error = _sentence_prevalence_error(
            sentence_matrix,
            validation_rows,
            VALIDATION_FRACTION,
        )

        candidate = {
            "train": train_indices,
            "validation": validation_indices,
            "split_seed_used": attempt_seed,
            "attempt": attempt + 1,
            "prevalence_error": prevalence_error,
            "stratification_labels": stratification_labels,
        }

        if (
            best_candidate is None
            or prevalence_error < best_candidate["prevalence_error"]
        ):
            best_candidate = candidate

        # Iterative stratification is already designed to balance multilabel
        # prevalence. Once a valid candidate is found, further attempts are not
        # needed unless coverage forced earlier candidates to be rejected.
        if rejected_for_coverage == 0:
            break

    if best_candidate is None:
        raise RuntimeError(
            "Could not create a sentence-level multilabel-stratified "
            "train/validation split that preserved the required training "
            f"support after {MAX_STRATIFICATION_ATTEMPTS} attempts."
        )

    train_indices = best_candidate["train"]
    validation_indices = best_candidate["validation"]

    train_set = set(train_indices)
    validation_set = set(validation_indices)

    if train_set & validation_set:
        raise RuntimeError(
            "Internal split error: at least one sentence occurs in both "
            "training and validation."
        )

    if train_set | validation_set != set(eligible_indices):
        raise RuntimeError(
            "Internal split error: sentence-level split does not exactly cover "
            "the eligible training sentences."
        )

    print()
    print("Sentence-level multilabel-stratified train/validation split:")
    print(
        f"  Eligible training sentences : {len(eligible_indices):,}"
    )
    print(
        f"  Target validation sentences : "
        f"{round(len(eligible_indices) * VALIDATION_FRACTION):,}"
    )
    print(
        f"  Actual validation sentences : {len(validation_indices):,}"
    )
    print(
        f"  Training sentences retained : {len(train_indices):,}"
    )
    print(
        f"  Split seed used             : "
        f"{best_candidate['split_seed_used']}"
    )
    print(
        f"  Stratification labels       : "
        f"{len(stratification_labels):,}"
    )
    print(
        f"  Coverage-rejected attempts  : {rejected_for_coverage:,}"
    )
    print(
        f"  Mean relative prevalence error: "
        f"{best_candidate['prevalence_error']:.6f}"
    )

    # Show sentence-level prevalence agreement, which is the quantity actually
    # controlled by the stratifier.
    validation_fraction_actual = (
        len(validation_indices) / len(eligible_indices)
    )

    label2column = {
        label: column
        for column, label in enumerate(stratification_labels)
    }

    row_by_sentence = {
        sentence_index: row
        for row, sentence_index in enumerate(eligible_indices)
    }

    train_rows_lookup = [
        row_by_sentence[index]
        for index in train_indices
    ]
    validation_rows_lookup = [
        row_by_sentence[index]
        for index in validation_indices
    ]

    print()
    print(
        f"{'Feature':35s} "
        f"{'All sent.':>10s} "
        f"{'Train':>10s} "
        f"{'Valid':>10s} "
        f"{'Valid %':>10s}"
    )
    print("-" * 80)

    for feature in stratification_labels:
        column = label2column[feature]
        all_support = int(sentence_matrix[:, column].sum())
        train_support = int(
            sentence_matrix[train_rows_lookup, column].sum()
        )
        validation_support = int(
            sentence_matrix[validation_rows_lookup, column].sum()
        )

        print(
            f"{feature:35s} "
            f"{all_support:10d} "
            f"{train_support:10d} "
            f"{validation_support:10d} "
            f"{validation_support / max(all_support, 1):10.3f}"
        )

    print(
        f"\nActual validation sentence fraction: "
        f"{validation_fraction_actual:.4f}"
    )
    print()

    return best_candidate


# =============================================================================
# Dataset
# =============================================================================

class SemanticFeatureDataset(Dataset):
    """
    RoBERTa multi-label token-classification dataset.

    IMPORTANT:
        labels contain only INDEPENDENT neural targets.

    Labels have shape:
        [sequence_length, number_of_prediction_features]

    For supervised tokens:
        0 = independent feature absent
        1 = independent feature present

    For ignored tokens:
        -100 across all labels

    Only the first RoBERTa subword corresponding to each source token receives
    supervision.
    """

    def __init__(
        self,
        sentences: Sequence[Any],
        sentence_indices: Sequence[int],
        tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
        tokenizer: Any,
        label2id: Dict[str, int],
        max_length: int,
    ) -> None:
        self.sentences = sentences
        self.sentence_indices = list(sentence_indices)
        self.tagged_records = tagged_records
        self.tokenizer = tokenizer
        self.label2id = label2id
        self.num_labels = len(label2id)
        self.max_length = max_length

    def __len__(self) -> int:
        return len(self.sentence_indices)

    def __getitem__(
        self,
        dataset_index: int,
    ) -> Dict[str, Any]:
        sentence_index = self.sentence_indices[dataset_index]
        sentence = self.sentences[sentence_index]

        words, token_ids = get_sentence_words(sentence)

        encoding = self.tokenizer(
            words,
            is_split_into_words=True,
            truncation=True,
            max_length=self.max_length,
            add_special_tokens=True,
        )

        word_ids = encoding.word_ids()
        labels: List[List[float]] = []
        previous_word_id: Optional[int] = None
        sentence_records = self.tagged_records.get(sentence_index, {})

        for word_id in word_ids:
            if word_id is None:
                labels.append([-100.0] * self.num_labels)
                previous_word_id = word_id
                continue

            # Ignore all but the first subword.
            if word_id == previous_word_id:
                labels.append([-100.0] * self.num_labels)
                continue

            previous_word_id = word_id

            if not 0 <= word_id < len(token_ids):
                labels.append([-100.0] * self.num_labels)
                continue

            conllu_token_id = token_ids[word_id]
            record = sentence_records.get(conllu_token_id)

            if record is None:
                labels.append([-100.0] * self.num_labels)
                continue

            full_features = clean_features(record)

            if not full_features and EXCLUDE_EMPTY_FEATURE_RECORDS:
                labels.append([-100.0] * self.num_labels)
                continue

            independent_features = reduce_to_independent_features(
                full_features
            )

            target = [0.0] * self.num_labels

            for feature in independent_features:
                label_id = self.label2id.get(feature)

                if label_id is not None:
                    target[label_id] = 1.0

            labels.append(target)

        encoding["labels"] = labels
        encoding["sentence_index"] = sentence_index

        return encoding


# =============================================================================
# Data collator
# =============================================================================

class MultiLabelTokenCollator:
    """Dynamically pad inputs and 3-D multi-label token targets."""

    def __init__(
        self,
        tokenizer: Any,
        num_labels: int,
    ) -> None:
        self.tokenizer = tokenizer
        self.num_labels = num_labels

    def __call__(
        self,
        features: List[Dict[str, Any]],
    ) -> Dict[str, torch.Tensor]:
        clean_features_list: List[Dict[str, Any]] = []
        labels_list: List[List[List[float]]] = []

        for item in features:
            item = dict(item)
            item.pop("sentence_index", None)

            labels = item.pop("labels")
            labels_list.append(labels)
            clean_features_list.append(item)

        batch = self.tokenizer.pad(
            clean_features_list,
            padding=True,
            return_tensors="pt",
        )

        batch_size = len(labels_list)
        max_seq_length = batch["input_ids"].shape[1]

        padded_labels = torch.full(
            (
                batch_size,
                max_seq_length,
                self.num_labels,
            ),
            -100.0,
            dtype=torch.float32,
        )

        for batch_index, labels in enumerate(labels_list):
            label_tensor = torch.tensor(
                labels,
                dtype=torch.float32,
            )

            sequence_length = label_tensor.shape[0]

            padded_labels[
                batch_index,
                :sequence_length,
                :,
            ] = label_tensor

        batch["labels"] = padded_labels

        return batch


# =============================================================================
# Model
# =============================================================================

class RobertaMultiLabelModel(nn.Module):
    """RoBERTa token classifier with BCE loss for independent feature labels."""

    def __init__(
        self,
        model_name: str,
        num_labels: int,
        id2label: Dict[int, str],
        label2id: Dict[str, int],
    ) -> None:
        super().__init__()

        self.model = AutoModelForTokenClassification.from_pretrained(
            model_name,
            num_labels=num_labels,
            id2label=id2label,
            label2id=label2id,
        )

        self.config = self.model.config

        self.loss_function = nn.BCEWithLogitsLoss(
            reduction="mean"
        )

    def forward(
        self,
        input_ids=None,
        attention_mask=None,
        labels=None,
        **kwargs,
    ):
        outputs = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            **kwargs,
        )

        logits = outputs.logits
        loss = None

        if labels is not None:
            valid_mask = labels[:, :, 0] != -100.0

            valid_logits = logits[valid_mask]
            valid_labels = labels[valid_mask]

            if valid_logits.numel() == 0:
                loss = logits.sum() * 0.0
            else:
                loss = self.loss_function(
                    valid_logits,
                    valid_labels,
                )

        return {
            "loss": loss,
            "logits": logits,
        }

    def save_pretrained(
        self,
        save_directory,
        **kwargs,
    ):
        return self.model.save_pretrained(
            save_directory,
            **kwargs,
        )


# =============================================================================
# Hierarchy matrices and array helpers
# =============================================================================

def build_hierarchy_expansion_matrix(
    prediction_labels: Sequence[str],
    full_labels: Sequence[str],
) -> np.ndarray:
    """
    Build a boolean matrix mapping neural outputs to complete feature sets.

    Shape:
        [number_of_prediction_features, number_of_full_features]
    """

    full_label2id = {
        label: index
        for index, label in enumerate(full_labels)
    }

    matrix = np.zeros(
        (len(prediction_labels), len(full_labels)),
        dtype=np.int8,
    )

    for prediction_id, feature in enumerate(prediction_labels):
        expanded = expand_feature_hierarchy({feature})

        for expanded_feature in expanded:
            full_id = full_label2id.get(expanded_feature)

            if full_id is None:
                raise RuntimeError(
                    "Hierarchy expansion produced a feature absent from the "
                    f"full vocabulary: {expanded_feature!r}."
                )

            matrix[prediction_id, full_id] = 1

    return matrix


def expand_binary_feature_matrix(
    independent_matrix: np.ndarray,
    hierarchy_matrix: np.ndarray,
) -> np.ndarray:
    """Expand [tokens, independent] binary values to [tokens, complete]."""

    expanded = independent_matrix.astype(np.int32) @ hierarchy_matrix.astype(
        np.int32
    )

    return (expanded > 0).astype(np.int32)


def extract_valid_token_arrays(
    logits: np.ndarray,
    labels: np.ndarray,
) -> Tuple[np.ndarray, np.ndarray]:
    """Return probabilities and true independent labels for supervised tokens."""

    valid_token_mask = labels[:, :, 0] != -100.0

    probabilities = sigmoid_numpy(logits)[
        valid_token_mask
    ]

    true_labels = labels[
        valid_token_mask
    ].astype(np.int32)

    return probabilities, true_labels


def build_full_truth_matrix_for_dataset(
    dataset: "SemanticFeatureDataset",
    full_labels: Sequence[str],
) -> np.ndarray:
    """Build complete source truth for every supervised token in dataset order.

    This is intentionally independent of the neural-output vocabulary.  It is
    therefore safe and necessary for a held-out test corpus that may contain a
    feature such as ``Human`` as a direct independent target even when that
    feature never occurred independently in the training corpus.

    The model is still trained only on training-derived independent output
    heads.  This function merely preserves the complete gold annotations for
    fair hierarchy-expanded evaluation.
    """

    full_label2id = {
        label: index
        for index, label in enumerate(full_labels)
    }

    rows: List[np.ndarray] = []

    for sentence_index in dataset.sentence_indices:
        sentence = dataset.sentences[sentence_index]
        words, token_ids = get_sentence_words(sentence)

        encoding = dataset.tokenizer(
            words,
            is_split_into_words=True,
            truncation=True,
            max_length=dataset.max_length,
            add_special_tokens=True,
        )

        word_ids = encoding.word_ids()
        previous_word_id: Optional[int] = None
        sentence_records = dataset.tagged_records.get(sentence_index, {})

        for word_id in word_ids:
            if word_id is None:
                previous_word_id = word_id
                continue

            # Match SemanticFeatureDataset.__getitem__: only the first subword
            # for each source token receives supervision.
            if word_id == previous_word_id:
                continue

            previous_word_id = word_id

            if not 0 <= word_id < len(token_ids):
                continue

            conllu_token_id = token_ids[word_id]
            record = sentence_records.get(conllu_token_id)

            if record is None:
                continue

            features = clean_features(record)

            if not features and EXCLUDE_EMPTY_FEATURE_RECORDS:
                continue

            expanded_features = expand_feature_hierarchy(features)
            row = np.zeros(len(full_labels), dtype=np.int32)

            for feature in expanded_features:
                label_id = full_label2id.get(feature)

                if label_id is None:
                    raise RuntimeError(
                        "Complete source truth contains a feature absent from "
                        f"the training-derived full vocabulary: {feature!r}."
                    )

                row[label_id] = 1

            rows.append(row)

    if not rows:
        return np.zeros((0, len(full_labels)), dtype=np.int32)

    return np.stack(rows, axis=0)


# =============================================================================
# Metrics and thresholds
# =============================================================================

def sigmoid_numpy(x: np.ndarray) -> np.ndarray:
    """Numerically stable sigmoid."""

    x = np.clip(x, -50.0, 50.0)
    return 1.0 / (1.0 + np.exp(-x))


def make_threshold_vector(
    prediction_labels: Sequence[str],
    thresholds: Dict[str, float],
) -> np.ndarray:
    """Return thresholds in neural-output column order."""

    return np.asarray(
        [
            float(
                thresholds.get(
                    label,
                    DEFAULT_PREDICTION_THRESHOLD,
                )
            )
            for label in prediction_labels
        ],
        dtype=np.float32,
    )


def threshold_probabilities(
    probabilities: np.ndarray,
    threshold_vector: np.ndarray,
) -> np.ndarray:
    """Apply one threshold per independent feature."""

    return (
        probabilities >= threshold_vector.reshape(1, -1)
    ).astype(np.int32)


def calculate_average_metrics(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    prefix: str = "",
) -> Dict[str, float]:
    """Calculate micro and macro precision/recall/F1."""

    if y_true.shape[0] == 0:
        return {
            f"{prefix}precision_micro": 0.0,
            f"{prefix}recall_micro": 0.0,
            f"{prefix}f1_micro": 0.0,
            f"{prefix}precision_macro": 0.0,
            f"{prefix}recall_macro": 0.0,
            f"{prefix}f1_macro": 0.0,
        }

    (
        precision_micro,
        recall_micro,
        f1_micro,
        _,
    ) = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="micro",
        zero_division=0,
    )

    (
        precision_macro,
        recall_macro,
        f1_macro,
        _,
    ) = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="macro",
        zero_division=0,
    )

    return {
        f"{prefix}precision_micro": float(precision_micro),
        f"{prefix}recall_micro": float(recall_micro),
        f"{prefix}f1_micro": float(f1_micro),
        f"{prefix}precision_macro": float(precision_macro),
        f"{prefix}recall_macro": float(recall_macro),
        f"{prefix}f1_macro": float(f1_macro),
    }


def calculate_hierarchical_metrics_from_probabilities(
    probabilities: np.ndarray,
    y_true_independent: np.ndarray,
    threshold_vector: np.ndarray,
    hierarchy_matrix: np.ndarray,
    y_true_full: Optional[np.ndarray] = None,
) -> Dict[str, float]:
    """
    Report both direct neural-output metrics and complete hierarchy metrics.

    Unprefixed metrics are the COMPLETE hierarchy metrics.  During ordinary
    training/validation, complete truth can be reconstructed from the
    independent targets.  For a genuinely held-out test corpus, ``y_true_full``
    may instead be supplied directly from the source annotations so an unseen
    direct independent label is not silently erased from the gold truth.
    """

    y_pred_independent = threshold_probabilities(
        probabilities,
        threshold_vector,
    )

    if y_true_full is None:
        y_true_full = expand_binary_feature_matrix(
            y_true_independent,
            hierarchy_matrix,
        )

    if y_true_full.shape[0] != y_true_independent.shape[0]:
        raise RuntimeError(
            "Complete and independent truth matrices contain different "
            f"numbers of supervised tokens: {y_true_full.shape[0]} vs "
            f"{y_true_independent.shape[0]}."
        )

    y_pred_full = expand_binary_feature_matrix(
        y_pred_independent,
        hierarchy_matrix,
    )

    metrics = calculate_average_metrics(
        y_true_full,
        y_pred_full,
        prefix="",
    )

    metrics.update(
        calculate_average_metrics(
            y_true_independent,
            y_pred_independent,
            prefix="direct_",
        )
    )

    return metrics


def make_compute_metrics(
    prediction_labels: Sequence[str],
    hierarchy_matrix: np.ndarray,
):
    """Create Trainer metrics using the fixed default 0.5 thresholds."""

    default_thresholds = np.full(
        len(prediction_labels),
        DEFAULT_PREDICTION_THRESHOLD,
        dtype=np.float32,
    )

    def compute_metrics(eval_prediction) -> Dict[str, float]:
        logits, labels = eval_prediction

        probabilities, y_true_independent = extract_valid_token_arrays(
            logits,
            labels,
        )

        return calculate_hierarchical_metrics_from_probabilities(
            probabilities=probabilities,
            y_true_independent=y_true_independent,
            threshold_vector=default_thresholds,
            hierarchy_matrix=hierarchy_matrix,
        )

    return compute_metrics


def build_threshold_grid() -> np.ndarray:
    """Build an inclusive, stable validation threshold search grid."""

    if THRESHOLD_STEP <= 0:
        raise ValueError("THRESHOLD_STEP must be > 0.")

    if not 0.0 < THRESHOLD_MIN < 1.0:
        raise ValueError("THRESHOLD_MIN must be between 0 and 1.")

    if not 0.0 < THRESHOLD_MAX < 1.0:
        raise ValueError("THRESHOLD_MAX must be between 0 and 1.")

    if THRESHOLD_MIN > THRESHOLD_MAX:
        raise ValueError("THRESHOLD_MIN cannot exceed THRESHOLD_MAX.")

    count = int(
        round(
            (THRESHOLD_MAX - THRESHOLD_MIN)
            / THRESHOLD_STEP
        )
    ) + 1

    return np.linspace(
        THRESHOLD_MIN,
        THRESHOLD_MAX,
        count,
        dtype=np.float64,
    )


def binary_metrics_for_column(
    y_true: np.ndarray,
    y_pred: np.ndarray,
) -> Tuple[float, float, float, int]:
    """Return binary precision, recall, F1 and positive support."""

    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="binary",
        zero_division=0,
    )

    support = int(y_true.sum())

    return (
        float(precision),
        float(recall),
        float(f1),
        support,
    )


def optimise_feature_thresholds(
    probabilities: np.ndarray,
    y_true_independent: np.ndarray,
    prediction_labels: Sequence[str],
) -> Tuple[Dict[str, float], Dict[str, Dict[str, float]]]:
    """
    Optimise one sigmoid threshold per independent feature on VALIDATION ONLY.

    Objective:
        maximise that feature's binary F1.

    Stability rules:
    - If validation has no positives or no negatives for a feature, keep 0.5.
    - If several thresholds tie for best F1, choose the one closest to 0.5.
      This avoids unnecessarily extreme thresholds for flat validation curves.
    """

    grid = build_threshold_grid()

    thresholds: Dict[str, float] = {}
    diagnostics: Dict[str, Dict[str, float]] = {}

    for label_id, feature in enumerate(prediction_labels):
        y_true = y_true_independent[:, label_id]
        probs = probabilities[:, label_id]

        positive_support = int(y_true.sum())
        negative_support = int((1 - y_true).sum())

        default_pred = (
            probs >= DEFAULT_PREDICTION_THRESHOLD
        ).astype(np.int32)

        (
            default_precision,
            default_recall,
            default_f1,
            _,
        ) = binary_metrics_for_column(
            y_true,
            default_pred,
        )

        if positive_support == 0 or negative_support == 0:
            best_threshold = DEFAULT_PREDICTION_THRESHOLD
        else:
            best_f1 = -1.0
            best_candidates: List[float] = []

            for threshold in grid:
                y_pred = (probs >= threshold).astype(np.int32)

                _, _, f1, _ = binary_metrics_for_column(
                    y_true,
                    y_pred,
                )

                if f1 > best_f1 + 1e-12:
                    best_f1 = f1
                    best_candidates = [float(threshold)]
                elif abs(f1 - best_f1) <= 1e-12:
                    best_candidates.append(float(threshold))

            best_threshold = min(
                best_candidates,
                key=lambda value: (
                    abs(value - DEFAULT_PREDICTION_THRESHOLD),
                    value,
                ),
            )

        best_pred = (
            probs >= best_threshold
        ).astype(np.int32)

        (
            best_precision,
            best_recall,
            best_f1,
            _,
        ) = binary_metrics_for_column(
            y_true,
            best_pred,
        )

        thresholds[feature] = float(best_threshold)

        diagnostics[feature] = {
            "threshold": float(best_threshold),
            "support": positive_support,
            "negative_support": negative_support,
            "precision_default": default_precision,
            "recall_default": default_recall,
            "f1_default": default_f1,
            "precision_optimised": best_precision,
            "recall_optimised": best_recall,
            "f1_optimised": best_f1,
            "f1_change": best_f1 - default_f1,
        }

    return thresholds, diagnostics


def calculate_per_feature_metrics_from_binary(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    labels: Sequence[str],
) -> Dict[str, Dict[str, float]]:
    """Calculate binary precision/recall/F1 independently for each column."""

    results: Dict[str, Dict[str, float]] = {}

    for label_id, feature in enumerate(labels):
        precision, recall, f1, support = binary_metrics_for_column(
            y_true[:, label_id],
            y_pred[:, label_id],
        )

        results[feature] = {
            "precision": precision,
            "recall": recall,
            "f1": f1,
            "support": support,
        }

    return results


# =============================================================================
# Dataset diagnostics and validation
# =============================================================================

def count_feature_occurrences(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    sentence_indices: Sequence[int],
    independent_only: bool = False,
) -> Counter:
    """Count complete or independent positive labels in a split."""

    counts: Counter = Counter()

    for sentence_index in sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            if independent_only:
                features = get_independent_record_features(record)
            else:
                features = clean_features(record)

            for feature in features:
                counts[feature] += 1

    return counts


def count_empty_records(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    sentence_indices: Sequence[int],
) -> int:
    """Count NOUN/PROPN records having no complete feature tags."""

    count = 0

    for sentence_index in sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            if not clean_features(record):
                count += 1

    return count


def verify_full_label_coverage(
    full_labels: Sequence[str],
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
) -> None:
    """Ensure validation/test contain no complete label unseen in training."""

    training_labels = set(full_labels)

    for split_name in ("validation", "test"):
        tagged_records, sentence_indices = split_sources[split_name]
        observed: Set[str] = set()

        for sentence_index in sentence_indices:
            for record in tagged_records.get(sentence_index, {}).values():
                observed.update(clean_features(record))

        unknown = observed - training_labels

        if unknown:
            raise RuntimeError(
                f"{split_name} contains full labels unseen in training: "
                f"{sorted(unknown)}"
            )


def verify_prediction_label_coverage(
    prediction_labels: Sequence[str],
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
    training_file_prediction_labels: Optional[Sequence[str]] = None,
) -> Dict[str, Dict[str, int]]:
    """Check independent-target coverage without leaking test labels.

    Validation remains strict: every validation independent target must have a
    training-derived neural output head.

    Test is different.  A genuine held-out corpus may contain a direct
    independent target that never occurred independently in training.  Such a
    label must NOT be added to the model from the test set.  Instead, report it
    and let complete-feature evaluation use the source gold matrix directly.
    """

    training_labels = set(prediction_labels)
    training_file_labels = (
        set(training_file_prediction_labels)
        if training_file_prediction_labels is not None
        else set(training_labels)
    )

    unseen_test_support: Dict[str, Dict[str, int]] = {}

    for split_name in ("validation", "test"):
        tagged_records, sentence_indices = split_sources[split_name]
        observed_counts: Counter = Counter()

        for sentence_index in sentence_indices:
            for record in tagged_records.get(sentence_index, {}).values():
                for feature in get_independent_record_features(record):
                    observed_counts[feature] += 1

        observed = set(observed_counts)
        unknown = observed - training_labels

        if not unknown:
            continue

        lost_due_to_split = unknown & training_file_labels
        absent_from_training_file = unknown - training_file_labels

        if split_name == "validation":
            details: List[str] = []

            if lost_due_to_split:
                details.append(
                    "present somewhere in the training file but absent from "
                    f"the training subset: {sorted(lost_due_to_split)}"
                )

            if absent_from_training_file:
                details.append(
                    "never occur as independent targets anywhere in the "
                    f"training file: {sorted(absent_from_training_file)}"
                )

            raise RuntimeError(
                "validation contains independent labels with no learnable "
                "training output. "
                + "; ".join(details)
            )

        # For the official test set, do not modify the model vocabulary.
        unseen_test_support = {
            feature: {
                "support": int(observed_counts[feature]),
                "present_in_training_file_as_independent": int(
                    feature in training_file_labels
                ),
            }
            for feature in sorted(unknown)
        }

        print()
        print("=" * 80)
        print("HELD-OUT TEST LABEL COVERAGE WARNING")
        print("=" * 80)
        print(
            "The test corpus contains direct independent targets that have no "
            "training-derived neural output head. They will NOT be added to "
            "the model vocabulary. Complete test truth will be read directly "
            "from the source annotations instead."
        )

        for feature in sorted(unknown):
            print(
                f"  {feature:35s} support={observed_counts[feature]:,}"
            )

        print()

    return unseen_test_support


def verify_hierarchy_closure(
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
) -> None:
    """
    Ensure source feature sets already contain all ancestors required by the
    hierarchy. This prevents evaluation against inconsistent source targets.
    """

    problems: List[str] = []
    max_examples = 20

    for split_name in ("train", "validation", "test"):
        tagged_records, sentence_indices = split_sources[split_name]
        problem_count = 0

        for sentence_index in sentence_indices:
            for token_id, record in tagged_records.get(
                sentence_index,
                {},
            ).items():
                features = clean_features(record)

                if not features:
                    continue

                missing = missing_hierarchy_features(features)

                if not missing:
                    continue

                problem_count += 1

                if len(problems) < max_examples:
                    problems.append(
                        f"{split_name}: sentence={sentence_index}, "
                        f"token={token_id}, "
                        f"form={record.get('form')!r}, "
                        f"missing={sorted(missing)}"
                    )

        if problem_count:
            print(
                f"Hierarchy closure problems in {split_name}: "
                f"{problem_count:,} token(s)"
            )

    if problems:
        example_text = "\n".join(
            f"  - {problem}"
            for problem in problems
        )

        raise RuntimeError(
            "The input dataset is not hierarchy-closed. Fix the source tags "
            "before training so deterministic reduction/expansion is exact.\n"
            f"Examples:\n{example_text}"
        )


def print_split_statistics(
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
) -> None:
    print("=" * 80)
    print("DATASET SPLIT")
    print("=" * 80)

    for split_name in ("train", "validation", "test"):
        tagged_records, indices = split_sources[split_name]

        full_counts = count_feature_occurrences(
            tagged_records,
            indices,
            independent_only=False,
        )

        independent_counts = count_feature_occurrences(
            tagged_records,
            indices,
            independent_only=True,
        )

        empty_count = count_empty_records(
            tagged_records,
            indices,
        )

        noun_count = sum(
            len(tagged_records.get(index, {}))
            for index in indices
        )

        source_name = (
            "training file"
            if split_name in {"train", "validation"}
            else "test file"
        )

        print(
            f"{split_name:12s}: "
            f"{len(indices):,} sentences | "
            f"{noun_count:,} NOUN/PROPN tokens | "
            f"{sum(full_counts.values()):,} complete positives -> "
            f"{sum(independent_counts.values()):,} independent positives | "
            f"{empty_count:,} empty-feature tokens excluded | "
            f"source={source_name}"
        )

    print()


def print_prediction_label_statistics(
    prediction_labels: Sequence[str],
    full_labels: Sequence[str],
    train_tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    train_sentence_indices: Sequence[int],
) -> None:
    """Show which labels are neural outputs versus deterministic-only parents."""

    train_independent_counts = count_feature_occurrences(
        train_tagged_records,
        train_sentence_indices,
        independent_only=True,
    )

    prediction_set = set(prediction_labels)
    deterministic_only = [
        feature
        for feature in full_labels
        if feature not in prediction_set
    ]

    print("=" * 80)
    print("NEURAL OUTPUT FEATURES")
    print("=" * 80)
    print(
        f"Complete evaluation features: {len(full_labels)}"
    )
    print(
        f"Independent neural outputs: {len(prediction_labels)}"
    )
    print(
        f"Deterministic-only features in this training split: "
        f"{len(deterministic_only)}"
    )
    print()

    print(
        f"{'Feature':35s} "
        f"{'Independent train support':>26s}"
    )
    print("-" * 64)

    for feature in prediction_labels:
        print(
            f"{feature:35s} "
            f"{train_independent_counts[feature]:26d}"
        )

    if deterministic_only:
        print()
        print("Deterministic-only in this split:")

        for feature in deterministic_only:
            print(f"  - {feature}")

    print()


# =============================================================================
# Repeated-run and bootstrap helpers
# =============================================================================

def get_supervised_token_count_for_sentence(
    dataset: "SemanticFeatureDataset",
    sentence_index: int,
) -> int:
    """
    Count supervised first-subword targets for one source sentence.

    This mirrors SemanticFeatureDataset.__getitem__ exactly and is used to map
    flat prediction rows back to sentence clusters for test bootstrapping.
    """

    sentence = dataset.sentences[sentence_index]
    words, token_ids = get_sentence_words(sentence)

    encoding = dataset.tokenizer(
        words,
        is_split_into_words=True,
        truncation=True,
        max_length=dataset.max_length,
        add_special_tokens=True,
    )

    word_ids = encoding.word_ids()
    previous_word_id: Optional[int] = None
    sentence_records = dataset.tagged_records.get(sentence_index, {})

    count = 0

    for word_id in word_ids:
        if word_id is None:
            previous_word_id = word_id
            continue

        if word_id == previous_word_id:
            continue

        previous_word_id = word_id

        if not 0 <= word_id < len(token_ids):
            continue

        conllu_token_id = token_ids[word_id]
        record = sentence_records.get(conllu_token_id)

        if record is None:
            continue

        features = clean_features(record)

        if not features and EXCLUDE_EMPTY_FEATURE_RECORDS:
            continue

        count += 1

    return count


def build_sentence_row_slices(
    dataset: "SemanticFeatureDataset",
) -> List[slice]:
    """
    Map every dataset sentence to its contiguous flat supervised-token rows.
    """

    slices: List[slice] = []
    start = 0

    for sentence_index in dataset.sentence_indices:
        count = get_supervised_token_count_for_sentence(
            dataset,
            sentence_index,
        )
        stop = start + count
        slices.append(slice(start, stop))
        start = stop

    return slices


def summarise_repeated_metrics(
    metric_dicts: Sequence[Dict[str, float]],
) -> Dict[str, Dict[str, float]]:
    """Return mean/SD/min/max across repeated seeded runs."""

    if not metric_dicts:
        return {}

    common_keys = sorted(
        set.intersection(
            *[
                {
                    key
                    for key, value in metrics.items()
                    if isinstance(
                        value,
                        (float, int, np.floating, np.integer),
                    )
                }
                for metrics in metric_dicts
            ]
        )
    )

    summary: Dict[str, Dict[str, float]] = {}

    for key in common_keys:
        values = np.asarray(
            [float(metrics[key]) for metrics in metric_dicts],
            dtype=np.float64,
        )

        summary[key] = {
            "mean": float(values.mean()),
            "sd": float(values.std(ddof=1))
            if len(values) > 1
            else 0.0,
            "minimum": float(values.min()),
            "maximum": float(values.max()),
            "n_runs": int(len(values)),
        }

    return summary


def _metrics_from_confusion_counts(
    tp_by_label: np.ndarray,
    fp_by_label: np.ndarray,
    fn_by_label: np.ndarray,
) -> Dict[str, float]:
    """Calculate six headline metrics directly from labelwise counts."""

    tp_by_label = tp_by_label.astype(np.float64, copy=False)
    fp_by_label = fp_by_label.astype(np.float64, copy=False)
    fn_by_label = fn_by_label.astype(np.float64, copy=False)

    tp = float(tp_by_label.sum())
    fp = float(fp_by_label.sum())
    fn = float(fn_by_label.sum())

    precision_micro = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall_micro = tp / (tp + fn) if (tp + fn) > 0 else 0.0

    if precision_micro + recall_micro > 0:
        f1_micro = (
            2.0
            * precision_micro
            * recall_micro
            / (precision_micro + recall_micro)
        )
    else:
        f1_micro = 0.0

    precision_den = tp_by_label + fp_by_label
    recall_den = tp_by_label + fn_by_label

    precision_by_label = np.divide(
        tp_by_label,
        precision_den,
        out=np.zeros_like(tp_by_label, dtype=np.float64),
        where=precision_den > 0,
    )
    recall_by_label = np.divide(
        tp_by_label,
        recall_den,
        out=np.zeros_like(tp_by_label, dtype=np.float64),
        where=recall_den > 0,
    )

    f1_den = precision_by_label + recall_by_label
    f1_by_label = np.divide(
        2.0 * precision_by_label * recall_by_label,
        f1_den,
        out=np.zeros_like(precision_by_label, dtype=np.float64),
        where=f1_den > 0,
    )

    return {
        "precision_micro": float(precision_micro),
        "recall_micro": float(recall_micro),
        "f1_micro": float(f1_micro),
        "precision_macro": float(precision_by_label.mean()),
        "recall_macro": float(recall_by_label.mean()),
        "f1_macro": float(f1_by_label.mean()),
    }


def build_sentence_confusion_arrays(
    y_true_full: np.ndarray,
    run_predictions_full: Sequence[np.ndarray],
    sentence_slices: Sequence[slice],
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Precompute TP/FP/FN by [run, sentence, label] for fast cluster bootstrap.
    """

    n_runs = len(run_predictions_full)
    n_sentences = len(sentence_slices)
    n_labels = y_true_full.shape[1]

    tp = np.zeros(
        (n_runs, n_sentences, n_labels),
        dtype=np.int32,
    )
    fp = np.zeros_like(tp)
    fn = np.zeros_like(tp)

    for sentence_pos, row_slice in enumerate(sentence_slices):
        y_true_sentence = y_true_full[row_slice]

        for run_pos, y_pred_full in enumerate(run_predictions_full):
            y_pred_sentence = y_pred_full[row_slice]

            tp[run_pos, sentence_pos] = (
                (y_true_sentence == 1)
                & (y_pred_sentence == 1)
            ).sum(axis=0)

            fp[run_pos, sentence_pos] = (
                (y_true_sentence == 0)
                & (y_pred_sentence == 1)
            ).sum(axis=0)

            fn[run_pos, sentence_pos] = (
                (y_true_sentence == 1)
                & (y_pred_sentence == 0)
            ).sum(axis=0)

    return tp, fp, fn


def bootstrap_mean_test_metrics(
    y_true_full: np.ndarray,
    run_predictions_full: Sequence[np.ndarray],
    sentence_slices: Sequence[slice],
) -> Dict[str, Any]:
    """
    Sentence-cluster bootstrap CIs for the MEAN performance across run seeds.

    Each bootstrap replicate:
      1. samples test sentences with replacement;
      2. applies the SAME sampled sentence multiplicities to every trained run;
      3. computes each run's six hierarchy-expanded metrics;
      4. averages each metric across runs.

    Thus the interval quantifies held-out TEST-SAMPLE uncertainty around the
    mean performance of the repeated-run procedure. Training-seed variability is
    reported separately via mean and SD across runs.
    """

    if TEST_BOOTSTRAP_SAMPLES < 1:
        raise ValueError("TEST_BOOTSTRAP_SAMPLES must be at least 1.")

    if not 0.0 < TEST_BOOTSTRAP_CONFIDENCE < 1.0:
        raise ValueError(
            "TEST_BOOTSTRAP_CONFIDENCE must be strictly between 0 and 1."
        )

    if not run_predictions_full:
        raise ValueError(
            "At least one run prediction matrix is required for bootstrap."
        )

    n_sentences = len(sentence_slices)

    if n_sentences == 0:
        raise ValueError("No test sentences are available for bootstrap.")

    expected_rows = sum(
        row_slice.stop - row_slice.start
        for row_slice in sentence_slices
    )

    if expected_rows != y_true_full.shape[0]:
        raise RuntimeError(
            "Sentence slices do not cover the complete test truth matrix: "
            f"{expected_rows:,} rows vs {y_true_full.shape[0]:,}."
        )

    for run_pos, y_pred_full in enumerate(run_predictions_full):
        if y_pred_full.shape != y_true_full.shape:
            raise RuntimeError(
                f"Run {run_pos} prediction shape {y_pred_full.shape} does "
                f"not match test truth shape {y_true_full.shape}."
            )

    tp, fp, fn = build_sentence_confusion_arrays(
        y_true_full,
        run_predictions_full,
        sentence_slices,
    )

    rng = np.random.default_rng(TEST_BOOTSTRAP_SEED)

    metric_names = [
        "precision_micro",
        "recall_micro",
        "f1_micro",
        "precision_macro",
        "recall_macro",
        "f1_macro",
    ]

    bootstrap_values = {
        metric: np.empty(TEST_BOOTSTRAP_SAMPLES, dtype=np.float64)
        for metric in metric_names
    }

    for bootstrap_index in range(TEST_BOOTSTRAP_SAMPLES):
        sampled_sentences = rng.integers(
            0,
            n_sentences,
            size=n_sentences,
        )

        multiplicities = np.bincount(
            sampled_sentences,
            minlength=n_sentences,
        ).astype(np.int32)

        run_metric_values = {
            metric: []
            for metric in metric_names
        }

        for run_pos in range(len(run_predictions_full)):
            tp_by_label = np.tensordot(
                multiplicities,
                tp[run_pos],
                axes=(0, 0),
            )
            fp_by_label = np.tensordot(
                multiplicities,
                fp[run_pos],
                axes=(0, 0),
            )
            fn_by_label = np.tensordot(
                multiplicities,
                fn[run_pos],
                axes=(0, 0),
            )

            metrics = _metrics_from_confusion_counts(
                tp_by_label,
                fp_by_label,
                fn_by_label,
            )

            for metric in metric_names:
                run_metric_values[metric].append(metrics[metric])

        for metric in metric_names:
            bootstrap_values[metric][bootstrap_index] = float(
                np.mean(run_metric_values[metric])
            )

    alpha = 1.0 - TEST_BOOTSTRAP_CONFIDENCE
    lower_q = alpha / 2.0
    upper_q = 1.0 - lower_q

    intervals: Dict[str, Dict[str, float]] = {}

    for metric in metric_names:
        values = bootstrap_values[metric]

        intervals[metric] = {
            "bootstrap_mean": float(values.mean()),
            "bootstrap_sd": float(values.std(ddof=1))
            if len(values) > 1
            else 0.0,
            "ci_lower": float(np.quantile(values, lower_q)),
            "ci_upper": float(np.quantile(values, upper_q)),
            "confidence": float(TEST_BOOTSTRAP_CONFIDENCE),
            "bootstrap_samples": int(TEST_BOOTSTRAP_SAMPLES),
        }

    return {
        "bootstrap_unit": "sentence",
        "statistic": "mean_metric_across_repeated_training_runs",
        "seed": TEST_BOOTSTRAP_SEED,
        "n_test_sentences": n_sentences,
        "n_runs": len(run_predictions_full),
        "intervals": intervals,
    }


def make_json_serialisable(value: Any) -> Any:
    """Recursively convert NumPy scalars/arrays to ordinary JSON values."""

    if isinstance(value, dict):
        return {
            str(key): make_json_serialisable(item)
            for key, item in value.items()
        }

    if isinstance(value, (list, tuple)):
        return [
            make_json_serialisable(item)
            for item in value
        ]

    if isinstance(value, np.ndarray):
        return value.tolist()

    if isinstance(value, (np.floating, np.integer)):
        return value.item()

    return value


# =============================================================================
# Reporting helpers
# =============================================================================

def print_metric_dictionary(
    metrics: Dict[str, float],
) -> None:
    for key, value in sorted(metrics.items()):
        print(f"{key}: {value}")


def print_threshold_table(
    prediction_labels: Sequence[str],
    diagnostics: Dict[str, Dict[str, float]],
) -> None:
    print()
    print("=" * 100)
    print("VALIDATION-OPTIMISED THRESHOLDS")
    print("=" * 100)

    heading = (
        f"{'Feature':35s} "
        f"{'Threshold':>10s} "
        f"{'Support':>9s} "
        f"{'F1@0.5':>10s} "
        f"{'F1 opt':>10s} "
        f"{'Change':>10s}"
    )

    print(heading)
    print("-" * len(heading))

    for feature in prediction_labels:
        result = diagnostics[feature]

        print(
            f"{feature:35s} "
            f"{result['threshold']:10.2f} "
            f"{int(result['support']):9d} "
            f"{result['f1_default']:10.4f} "
            f"{result['f1_optimised']:10.4f} "
            f"{result['f1_change']:+10.4f}"
        )


def print_per_feature_table(
    title: str,
    labels: Sequence[str],
    results: Dict[str, Dict[str, float]],
) -> None:
    print()
    print("=" * 80)
    print(title)
    print("=" * 80)

    heading = (
        f"{'Feature':35s} "
        f"{'Precision':>10s} "
        f"{'Recall':>10s} "
        f"{'F1':>10s} "
        f"{'Support':>10s}"
    )

    print(heading)
    print("-" * len(heading))

    for feature in labels:
        result = results[feature]

        print(
            f"{feature:35s} "
            f"{result['precision']:10.4f} "
            f"{result['recall']:10.4f} "
            f"{result['f1']:10.4f} "
            f"{result['support']:10d}"
        )


def summarise_repeated_per_feature_metrics(
    run_documents: Sequence[Dict[str, Any]],
    result_key: str,
    labels: Sequence[str],
) -> Dict[str, Dict[str, float]]:
    """Summarise per-feature test precision/recall/F1 across repeated runs."""

    summary: Dict[str, Dict[str, float]] = {}

    for feature in labels:
        precision_values = np.asarray(
            [
                run_document[result_key][feature]["precision"]
                for run_document in run_documents
            ],
            dtype=np.float64,
        )
        recall_values = np.asarray(
            [
                run_document[result_key][feature]["recall"]
                for run_document in run_documents
            ],
            dtype=np.float64,
        )
        f1_values = np.asarray(
            [
                run_document[result_key][feature]["f1"]
                for run_document in run_documents
            ],
            dtype=np.float64,
        )
        supports = {
            int(run_document[result_key][feature]["support"])
            for run_document in run_documents
        }

        if len(supports) != 1:
            raise RuntimeError(
                f"Test support changed across runs for feature {feature!r}: "
                f"{sorted(supports)}"
            )

        summary[feature] = {
            "precision_mean": float(precision_values.mean()),
            "precision_sd": float(precision_values.std(ddof=1))
            if len(precision_values) > 1
            else 0.0,
            "recall_mean": float(recall_values.mean()),
            "recall_sd": float(recall_values.std(ddof=1))
            if len(recall_values) > 1
            else 0.0,
            "f1_mean": float(f1_values.mean()),
            "f1_sd": float(f1_values.std(ddof=1))
            if len(f1_values) > 1
            else 0.0,
            "f1_min": float(f1_values.min()),
            "f1_max": float(f1_values.max()),
            "support": int(next(iter(supports))),
        }

    return summary


def print_repeated_per_feature_table(
    title: str,
    labels: Sequence[str],
    summary: Dict[str, Dict[str, float]],
) -> None:
    """Print repeated-run mean/SD test performance for each feature."""

    print()
    print("=" * 118)
    print(title)
    print("=" * 118)

    heading = (
        f"{'Feature':35s} "
        f"{'P mean':>8s} "
        f"{'P SD':>8s} "
        f"{'R mean':>8s} "
        f"{'R SD':>8s} "
        f"{'F1 mean':>8s} "
        f"{'F1 SD':>8s} "
        f"{'F1 min':>8s} "
        f"{'F1 max':>8s} "
        f"{'Support':>8s}"
    )

    print(heading)
    print("-" * len(heading))

    for feature in labels:
        result = summary[feature]
        print(
            f"{feature:35s} "
            f"{result['precision_mean']:8.4f} "
            f"{result['precision_sd']:8.4f} "
            f"{result['recall_mean']:8.4f} "
            f"{result['recall_sd']:8.4f} "
            f"{result['f1_mean']:8.4f} "
            f"{result['f1_sd']:8.4f} "
            f"{result['f1_min']:8.4f} "
            f"{result['f1_max']:8.4f} "
            f"{int(result['support']):8d}"
        )


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )
    RUNS_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    validate_feature_hierarchy()
    check_cuda()

    if not RUN_SEEDS:
        raise ValueError("RUN_SEEDS must contain at least one integer seed.")

    if len(set(RUN_SEEDS)) != len(RUN_SEEDS):
        raise ValueError("RUN_SEEDS contains duplicate seeds.")

    # -------------------------------------------------------------------------
    # Load independent TRAIN and held-out TEST corpora
    # -------------------------------------------------------------------------

    print("=" * 80)
    print("LOADING DATA")
    print("=" * 80)

    train_sentences = load_conllu(TRAIN_CONLLU_PATH)
    test_sentences = load_conllu(TEST_CONLLU_PATH)

    train_tagged_records = load_tagged_records(TRAIN_JSONL_PATH)
    test_tagged_records = load_tagged_records(TEST_JSONL_PATH)

    validate_feature_switches(
        train_tagged_records,
        test_tagged_records,
    )

    print(
        "Training CoNLL-U sentences: "
        f"{len(train_sentences):,}"
    )
    print(
        "Test CoNLL-U sentences: "
        f"{len(test_sentences):,}"
    )
    print(
        "Training sentences represented in tagged JSONL: "
        f"{len(train_tagged_records):,}"
    )
    print(
        "Test sentences represented in tagged JSONL: "
        f"{len(test_tagged_records):,}"
    )

    train_target_record_count = sum(
        len(records)
        for records in train_tagged_records.values()
    )
    test_target_record_count = sum(
        len(records)
        for records in test_tagged_records.values()
    )

    print(
        "Training tagged NOUN/PROPN records: "
        f"{train_target_record_count:,}"
    )
    print(
        "Test tagged NOUN/PROPN records: "
        f"{test_target_record_count:,}"
    )
    print()

    # -------------------------------------------------------------------------
    # Fixed sentence-level TRAIN/VALIDATION split; TEST remains untouched
    # -------------------------------------------------------------------------

    eligible_train_indices = get_eligible_sentence_indices(
        train_sentences,
        train_tagged_records,
    )
    eligible_test_indices = get_eligible_sentence_indices(
        test_sentences,
        test_tagged_records,
    )

    print(
        "Eligible training-file sentences with at least one non-empty "
        "feature target: "
        f"{len(eligible_train_indices):,}"
    )
    print(
        "Eligible test-file sentences with at least one non-empty "
        "feature target: "
        f"{len(eligible_test_indices):,}"
    )

    train_validation_split = make_train_validation_split(
        eligible_train_indices,
        train_tagged_records,
    )

    train_indices = train_validation_split["train"]
    validation_indices = train_validation_split["validation"]
    test_indices = list(eligible_test_indices)

    split_sources = {
        "train": (train_tagged_records, train_indices),
        "validation": (train_tagged_records, validation_indices),
        "test": (test_tagged_records, test_indices),
    }

    split_document = {
        "split_unit": "sentence",
        "stratification": "iterative_multilabel_sentence_presence",
        "split_seed_requested": SPLIT_SEED,
        "split_seed_used": train_validation_split["split_seed_used"],
        "split_attempt": train_validation_split["attempt"],
        "validation_fraction": VALIDATION_FRACTION,
        "feature_switches": dict(sorted(FEATURE_SWITCHES.items())),
        "prevalence_error": train_validation_split["prevalence_error"],
        "stratification_labels": (
            train_validation_split["stratification_labels"]
        ),
        "train_jsonl": str(TRAIN_JSONL_PATH),
        "test_jsonl": str(TEST_JSONL_PATH),
        "train_conllu": str(TRAIN_CONLLU_PATH),
        "test_conllu": str(TEST_CONLLU_PATH),
        "index_spaces": {
            "train": "training corpus",
            "validation": "training corpus",
            "test": "test corpus",
        },
        "train": train_indices,
        "validation": validation_indices,
        "test": test_indices,
    }

    with SPLIT_PATH.open("w", encoding="utf-8") as handle:
        json.dump(
            make_json_serialisable(split_document),
            handle,
            ensure_ascii=False,
            indent=2,
        )

    # The reduction is exact only when source data are hierarchy-closed.
    verify_hierarchy_closure(split_sources)

    # -------------------------------------------------------------------------
    # Separate complete and neural-output vocabularies
    # -------------------------------------------------------------------------

    training_file_prediction_labels = build_prediction_label_vocabulary(
        train_tagged_records,
        eligible_train_indices,
    )

    # Vocabularies are derived from TRAIN only, never validation/test.
    full_labels = build_full_label_vocabulary(
        train_tagged_records,
        train_indices,
    )

    prediction_labels = build_prediction_label_vocabulary(
        train_tagged_records,
        train_indices,
    )

    verify_full_label_coverage(
        full_labels,
        split_sources,
    )

    unseen_test_independent_labels = verify_prediction_label_coverage(
        prediction_labels,
        split_sources,
        training_file_prediction_labels=training_file_prediction_labels,
    )

    prediction_label2id = {
        label: index
        for index, label in enumerate(prediction_labels)
    }

    prediction_id2label = {
        index: label
        for label, index in prediction_label2id.items()
    }

    full_label2id = {
        label: index
        for index, label in enumerate(full_labels)
    }

    hierarchy_matrix = build_hierarchy_expansion_matrix(
        prediction_labels,
        full_labels,
    )

    label_document = {
        "labels": prediction_labels,
        "label2id": prediction_label2id,
        "id2label": {
            str(key): value
            for key, value in prediction_id2label.items()
        },
        "prediction_labels": prediction_labels,
        "prediction_label2id": prediction_label2id,
        "full_labels": full_labels,
        "full_label2id": full_label2id,
        "feature_parents": {
            child: sorted(parents)
            for child, parents in sorted(FEATURE_PARENTS.items())
        },
        "target_representation": "per_token_independent_features",
        "split_unit": "sentence",
        "feature_switches": dict(sorted(FEATURE_SWITCHES.items())),
        "disabled_features": sorted(
            feature
            for feature, enabled in FEATURE_SWITCHES.items()
            if not enabled
        ),
    }

    with LABELS_PATH.open("w", encoding="utf-8") as handle:
        json.dump(
            label_document,
            handle,
            ensure_ascii=False,
            indent=2,
        )

    print_split_statistics(split_sources)

    print_prediction_label_statistics(
        prediction_labels,
        full_labels,
        train_tagged_records,
        train_indices,
    )

    # -------------------------------------------------------------------------
    # Tokeniser and fixed datasets
    # -------------------------------------------------------------------------

    tokenizer = AutoTokenizer.from_pretrained(
        MODEL_NAME,
        use_fast=True,
        add_prefix_space=True,
    )

    train_dataset = SemanticFeatureDataset(
        sentences=train_sentences,
        sentence_indices=train_indices,
        tagged_records=train_tagged_records,
        tokenizer=tokenizer,
        label2id=prediction_label2id,
        max_length=MAX_LENGTH,
    )

    validation_dataset = SemanticFeatureDataset(
        sentences=train_sentences,
        sentence_indices=validation_indices,
        tagged_records=train_tagged_records,
        tokenizer=tokenizer,
        label2id=prediction_label2id,
        max_length=MAX_LENGTH,
    )

    test_dataset = SemanticFeatureDataset(
        sentences=test_sentences,
        sentence_indices=test_indices,
        tagged_records=test_tagged_records,
        tokenizer=tokenizer,
        label2id=prediction_label2id,
        max_length=MAX_LENGTH,
    )

    data_collator = MultiLabelTokenCollator(
        tokenizer=tokenizer,
        num_labels=len(prediction_labels),
    )

    # Complete held-out gold truth is fixed across all training runs.
    test_true_full = build_full_truth_matrix_for_dataset(
        test_dataset,
        full_labels,
    )

    test_sentence_slices = build_sentence_row_slices(
        test_dataset,
    )

    test_slice_rows = sum(
        row_slice.stop - row_slice.start
        for row_slice in test_sentence_slices
    )

    if test_slice_rows != test_true_full.shape[0]:
        raise RuntimeError(
            "Test sentence-cluster mapping does not align with source truth: "
            f"{test_slice_rows:,} mapped rows vs "
            f"{test_true_full.shape[0]:,} truth rows."
        )

    # -------------------------------------------------------------------------
    # Repeated fine-tuning runs
    # -------------------------------------------------------------------------

    print("=" * 80)
    print("REPEATED FINE-TUNING")
    print("=" * 80)
    print(f"Runs: {len(RUN_SEEDS)}")
    print(f"Seeds: {RUN_SEEDS}")
    print(
        "Train/validation split is fixed across all runs; only the "
        "fine-tuning seed changes."
    )
    print()

    use_bf16 = torch.cuda.is_bf16_supported()

    all_run_documents: List[Dict[str, Any]] = []
    all_test_metric_dicts: List[Dict[str, float]] = []
    all_validation_metric_dicts: List[Dict[str, float]] = []
    all_test_predictions_full: List[np.ndarray] = []

    work_root = OUTPUT_DIR / "_trainer_work"
    work_root.mkdir(parents=True, exist_ok=True)

    for run_number, run_seed in enumerate(RUN_SEEDS, start=1):
        print()
        print("=" * 100)
        print(
            f"RUN {run_number}/{len(RUN_SEEDS)} | "
            f"SEED {run_seed}"
        )
        print("=" * 100)

        set_seed(run_seed)

        run_work_dir = work_root / f"seed_{run_seed}"
        run_result_path = RUNS_DIR / f"seed_{run_seed}.json"

        if run_work_dir.exists():
            shutil.rmtree(run_work_dir)

        model = RobertaMultiLabelModel(
            model_name=MODEL_NAME,
            num_labels=len(prediction_labels),
            id2label=prediction_id2label,
            label2id=prediction_label2id,
        )

        training_args = TrainingArguments(
            output_dir=str(run_work_dir),

            learning_rate=LEARNING_RATE,
            lr_scheduler_type="linear",
            weight_decay=WEIGHT_DECAY,

            per_device_train_batch_size=TRAIN_BATCH_SIZE,
            per_device_eval_batch_size=EVAL_BATCH_SIZE,

            gradient_accumulation_steps=(
                GRADIENT_ACCUMULATION_STEPS
            ),

            num_train_epochs=NUM_EPOCHS,

            eval_strategy=EVAL_STRATEGY,
            save_strategy="epoch",
            logging_strategy="steps",
            logging_steps=50,

            load_best_model_at_end=True,

            # Model selection is performed on VALIDATION only, using complete
            # hierarchy-expanded macro F1 at the fixed 0.5 threshold.
            metric_for_best_model="f1_macro",
            greater_is_better=True,

            save_total_limit=2,

            bf16=use_bf16,
            fp16=not use_bf16,

            dataloader_num_workers=4,
            dataloader_pin_memory=True,

            optim="adamw_torch",
            report_to="none",

            seed=run_seed,
            data_seed=run_seed,

            remove_unused_columns=False,
            eval_accumulation_steps=16,
        )

        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_dataset,
            eval_dataset=validation_dataset,
            processing_class=tokenizer,
            data_collator=data_collator,
            compute_metrics=make_compute_metrics(
                prediction_labels,
                hierarchy_matrix,
            ),
        )

        trainer.train()

        # ---------------------------------------------------------------------
        # Validation: first report 0.5, then calibrate thresholds on validation
        # ---------------------------------------------------------------------

        validation_output = trainer.predict(
            validation_dataset,
            metric_key_prefix="validation_default",
        )

        (
            validation_probabilities,
            validation_true_independent,
        ) = extract_valid_token_arrays(
            validation_output.predictions,
            validation_output.label_ids,
        )

        default_threshold_vector = np.full(
            len(prediction_labels),
            DEFAULT_PREDICTION_THRESHOLD,
            dtype=np.float32,
        )

        validation_default_metrics = (
            calculate_hierarchical_metrics_from_probabilities(
                probabilities=validation_probabilities,
                y_true_independent=validation_true_independent,
                threshold_vector=default_threshold_vector,
                hierarchy_matrix=hierarchy_matrix,
            )
        )

        (
            optimised_thresholds,
            threshold_diagnostics,
        ) = optimise_feature_thresholds(
            probabilities=validation_probabilities,
            y_true_independent=validation_true_independent,
            prediction_labels=prediction_labels,
        )

        threshold_vector = make_threshold_vector(
            prediction_labels,
            optimised_thresholds,
        )

        validation_optimised_metrics = (
            calculate_hierarchical_metrics_from_probabilities(
                probabilities=validation_probabilities,
                y_true_independent=validation_true_independent,
                threshold_vector=threshold_vector,
                hierarchy_matrix=hierarchy_matrix,
            )
        )

        print_threshold_table(
            prediction_labels,
            threshold_diagnostics,
        )

        print()
        print("VALIDATION @ 0.5")
        print_metric_dictionary(validation_default_metrics)

        print()
        print("VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS")
        print_metric_dictionary(validation_optimised_metrics)

        # ---------------------------------------------------------------------
        # Held-out TEST: thresholds are frozen
        # ---------------------------------------------------------------------

        test_output = trainer.predict(
            test_dataset,
            metric_key_prefix="test_default",
        )

        test_probabilities, test_true_independent = (
            extract_valid_token_arrays(
                test_output.predictions,
                test_output.label_ids,
            )
        )

        if test_true_full.shape[0] != test_probabilities.shape[0]:
            raise RuntimeError(
                "Test source-truth alignment failed: predictions contain "
                f"{test_probabilities.shape[0]:,} supervised tokens but "
                f"source truth contains {test_true_full.shape[0]:,}."
            )

        # Explicit test-at-0.5 diagnostic.
        test_default_metrics = (
            calculate_hierarchical_metrics_from_probabilities(
                probabilities=test_probabilities,
                y_true_independent=test_true_independent,
                threshold_vector=default_threshold_vector,
                hierarchy_matrix=hierarchy_matrix,
                y_true_full=test_true_full,
            )
        )

        # Final per-run test result uses validation-calibrated thresholds.
        test_optimised_metrics = (
            calculate_hierarchical_metrics_from_probabilities(
                probabilities=test_probabilities,
                y_true_independent=test_true_independent,
                threshold_vector=threshold_vector,
                hierarchy_matrix=hierarchy_matrix,
                y_true_full=test_true_full,
            )
        )

        test_pred_independent = threshold_probabilities(
            test_probabilities,
            threshold_vector,
        )

        test_pred_full = expand_binary_feature_matrix(
            test_pred_independent,
            hierarchy_matrix,
        )

        all_test_predictions_full.append(
            test_pred_full.astype(np.int8, copy=True)
        )

        per_feature_full = calculate_per_feature_metrics_from_binary(
            y_true=test_true_full,
            y_pred=test_pred_full,
            labels=full_labels,
        )

        per_feature_independent = (
            calculate_per_feature_metrics_from_binary(
                y_true=test_true_independent,
                y_pred=test_pred_independent,
                labels=prediction_labels,
            )
        )

        print()
        print("TEST @ 0.5 (DIAGNOSTIC)")
        print_metric_dictionary(test_default_metrics)

        print()
        print("TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS")
        print_metric_dictionary(test_optimised_metrics)

        if PRINT_PER_RUN_FEATURE_TABLES:
            print_per_feature_table(
                title=(
                    f"RUN {run_number} / SEED {run_seed}: TEST PERFORMANCE "
                    "BY COMPLETE FEATURE (AFTER INHERITANCE)"
                ),
                labels=full_labels,
                results=per_feature_full,
            )
            print_per_feature_table(
                title=(
                    f"RUN {run_number} / SEED {run_seed}: TEST PERFORMANCE "
                    "BY INDEPENDENT NEURAL OUTPUT"
                ),
                labels=prediction_labels,
                results=per_feature_independent,
            )

        # ---------------------------------------------------------------------
        # Save a neutral reference model, not a cherry-picked best seed
        # ---------------------------------------------------------------------

        is_reference_run = (
            SAVE_REFERENCE_MODEL
            and run_number == 1
        )

        if is_reference_run:
            if REFERENCE_MODEL_DIR.exists():
                shutil.rmtree(REFERENCE_MODEL_DIR)

            trainer.save_model(str(REFERENCE_MODEL_DIR))
            tokenizer.save_pretrained(str(REFERENCE_MODEL_DIR))

            with (
                REFERENCE_MODEL_DIR / "semantic_features.json"
            ).open(
                "w",
                encoding="utf-8",
            ) as handle:
                json.dump(
                    label_document,
                    handle,
                    ensure_ascii=False,
                    indent=2,
                )

            reference_threshold_document = {
                "seed": run_seed,
                "selection_policy": (
                    "first_predeclared_seed_not_best_test_run"
                ),
                "optimised_on": "validation",
                "objective": "per_feature_binary_f1",
                "thresholds": optimised_thresholds,
                "diagnostics": threshold_diagnostics,
            }

            with (
                REFERENCE_MODEL_DIR / "prediction_thresholds.json"
            ).open(
                "w",
                encoding="utf-8",
            ) as handle:
                json.dump(
                    make_json_serialisable(
                        reference_threshold_document
                    ),
                    handle,
                    ensure_ascii=False,
                    indent=2,
                )

        run_document = {
            "run_number": run_number,
            "seed": run_seed,
            "is_reference_model": is_reference_run,
            "model": MODEL_NAME,
            "target_representation": (
                "per_token_independent_features"
            ),
            "feature_switches": dict(sorted(FEATURE_SWITCHES.items())),
            "disabled_features": sorted(
                feature
                for feature, enabled in FEATURE_SWITCHES.items()
                if not enabled
            ),
            "split": {
                "unit": "sentence",
                "split_seed": (
                    train_validation_split["split_seed_used"]
                ),
                "validation_fraction": VALIDATION_FRACTION,
                "train_sentences": len(train_indices),
                "validation_sentences": len(validation_indices),
                "test_sentences": len(test_indices),
            },
            "threshold_calibration": {
                "data": "validation_only",
                "objective": "per_feature_binary_f1",
                "thresholds": optimised_thresholds,
                "diagnostics": threshold_diagnostics,
            },
            "validation_metrics_at_0_5": (
                validation_default_metrics
            ),
            "validation_metrics_optimised": (
                validation_optimised_metrics
            ),
            "test_metrics_at_0_5": test_default_metrics,
            "test_metrics_optimised": test_optimised_metrics,
            "per_feature_complete": per_feature_full,
            "per_feature_independent": (
                per_feature_independent
            ),
            "unseen_test_independent_labels": (
                unseen_test_independent_labels
            ),
        }

        with run_result_path.open(
            "w",
            encoding="utf-8",
        ) as handle:
            json.dump(
                make_json_serialisable(run_document),
                handle,
                ensure_ascii=False,
                indent=2,
            )

        all_run_documents.append(run_document)
        all_test_metric_dicts.append(test_optimised_metrics)
        all_validation_metric_dicts.append(
            validation_optimised_metrics
        )

        # Release run-specific GPU state before initialising the next model.
        del test_output
        del validation_output
        del trainer
        del model

        gc.collect()
        torch.cuda.empty_cache()

        # Checkpoints were needed only to recover the best validation epoch.
        # Remove them after each run to avoid storing dozens of RoBERTa-large
        # copies. The neutral first-seed reference model was saved separately.
        if run_work_dir.exists():
            shutil.rmtree(run_work_dir)

    if work_root.exists() and not any(work_root.iterdir()):
        work_root.rmdir()

    # -------------------------------------------------------------------------
    # Repeated-run summary: stochastic training variability
    # -------------------------------------------------------------------------

    validation_summary = summarise_repeated_metrics(
        all_validation_metric_dicts
    )
    test_summary = summarise_repeated_metrics(
        all_test_metric_dicts
    )

    print()
    print("=" * 100)
    print("REPEATED-RUN TEST SUMMARY")
    print("=" * 100)

    headline_metrics = [
        "precision_micro",
        "recall_micro",
        "f1_micro",
        "precision_macro",
        "recall_macro",
        "f1_macro",
    ]

    print(
        f"{'Metric':25s} "
        f"{'Mean':>10s} "
        f"{'SD':>10s} "
        f"{'Min':>10s} "
        f"{'Max':>10s}"
    )
    print("-" * 70)

    for metric in headline_metrics:
        result = test_summary[metric]

        print(
            f"{metric:25s} "
            f"{result['mean']:10.4f} "
            f"{result['sd']:10.4f} "
            f"{result['minimum']:10.4f} "
            f"{result['maximum']:10.4f}"
        )

    # -------------------------------------------------------------------------
    # Repeated-run per-feature test summaries
    # -------------------------------------------------------------------------

    per_feature_complete_summary = summarise_repeated_per_feature_metrics(
        all_run_documents,
        result_key="per_feature_complete",
        labels=full_labels,
    )
    per_feature_independent_summary = summarise_repeated_per_feature_metrics(
        all_run_documents,
        result_key="per_feature_independent",
        labels=prediction_labels,
    )

    print_repeated_per_feature_table(
        title=(
            "REPEATED-RUN TEST PERFORMANCE BY COMPLETE FEATURE "
            "(AFTER INHERITANCE)"
        ),
        labels=full_labels,
        summary=per_feature_complete_summary,
    )

    print_repeated_per_feature_table(
        title=(
            "REPEATED-RUN TEST PERFORMANCE BY INDEPENDENT NEURAL OUTPUT"
        ),
        labels=prediction_labels,
        summary=per_feature_independent_summary,
    )

    # -------------------------------------------------------------------------
    # Sentence-cluster bootstrap: held-out test-sample uncertainty
    # -------------------------------------------------------------------------

    print()
    print("=" * 100)
    print("SENTENCE-CLUSTER BOOTSTRAP ON HELD-OUT TEST SET")
    print("=" * 100)

    bootstrap_results = bootstrap_mean_test_metrics(
        y_true_full=test_true_full,
        run_predictions_full=all_test_predictions_full,
        sentence_slices=test_sentence_slices,
    )

    print(
        f"Bootstrap samples: {TEST_BOOTSTRAP_SAMPLES:,}"
    )
    print(
        f"Confidence level : "
        f"{TEST_BOOTSTRAP_CONFIDENCE:.1%}"
    )
    print(
        "Bootstrap unit   : sentence (all eligible NOUN/PROPN targets "
        "from a sampled sentence move together)"
    )
    print()

    ci_percent = int(round(TEST_BOOTSTRAP_CONFIDENCE * 100))

    print(
        f"{'Metric':25s} "
        f"{'Run mean':>10s} "
        f"{'Run SD':>10s} "
        f"{str(ci_percent) + '% CI low':>12s} "
        f"{str(ci_percent) + '% CI high':>12s}"
    )
    print("-" * 78)

    for metric in headline_metrics:
        repeated = test_summary[metric]
        interval = bootstrap_results["intervals"][metric]

        print(
            f"{metric:25s} "
            f"{repeated['mean']:10.4f} "
            f"{repeated['sd']:10.4f} "
            f"{interval['ci_lower']:12.4f} "
            f"{interval['ci_upper']:12.4f}"
        )

    # -------------------------------------------------------------------------
    # Save experiment-level results
    # -------------------------------------------------------------------------

    bootstrap_document = {
        "model": MODEL_NAME,
        "run_seeds": RUN_SEEDS,
        "split_seed": train_validation_split["split_seed_used"],
        "test_bootstrap": bootstrap_results,
    }

    with BOOTSTRAP_RESULTS_PATH.open(
        "w",
        encoding="utf-8",
    ) as handle:
        json.dump(
            make_json_serialisable(bootstrap_document),
            handle,
            ensure_ascii=False,
            indent=2,
        )

    repeated_document = {
        "model": MODEL_NAME,
        "experimental_design": {
            "test_set": "fixed_external_held_out_file",
            "train_validation_split_unit": "sentence",
            "train_validation_stratification": (
                "iterative_multilabel_sentence_presence"
            ),
            "split_seed": (
                train_validation_split["split_seed_used"]
            ),
            "validation_fraction": VALIDATION_FRACTION,
            "number_of_runs": len(RUN_SEEDS),
            "run_seeds": RUN_SEEDS,
            "same_split_for_every_run": True,
            "threshold_calibration": (
                "per_feature_binary_f1_on_validation_only"
            ),
            "test_bootstrap_unit": "sentence",
            "test_bootstrap_samples": TEST_BOOTSTRAP_SAMPLES,
            "test_bootstrap_confidence": (
                TEST_BOOTSTRAP_CONFIDENCE
            ),
        },
        "data_sources": {
            "train_jsonl": str(TRAIN_JSONL_PATH),
            "test_jsonl": str(TEST_JSONL_PATH),
            "train_conllu": str(TRAIN_CONLLU_PATH),
            "test_conllu": str(TEST_CONLLU_PATH),
        },
        "split_sizes": {
            "train_sentences": len(train_indices),
            "validation_sentences": len(validation_indices),
            "test_sentences": len(test_indices),
        },
        "prediction_labels": prediction_labels,
        "full_labels": full_labels,
        "feature_switches": dict(sorted(FEATURE_SWITCHES.items())),
        "disabled_features": sorted(
            feature
            for feature, enabled in FEATURE_SWITCHES.items()
            if not enabled
        ),
        "unseen_test_independent_labels": (
            unseen_test_independent_labels
        ),
        "validation_repeated_run_summary": validation_summary,
        "test_repeated_run_summary": test_summary,
        "test_per_feature_complete_repeated_run_summary": (
            per_feature_complete_summary
        ),
        "test_per_feature_independent_repeated_run_summary": (
            per_feature_independent_summary
        ),
        "test_bootstrap": bootstrap_results,
        "runs": [
            {
                "run_number": run_document["run_number"],
                "seed": run_document["seed"],
                "is_reference_model": (
                    run_document["is_reference_model"]
                ),
                "result_file": str(
                    RUNS_DIR
                    / f"seed_{run_document['seed']}.json"
                ),
                "validation_metrics_optimised": (
                    run_document[
                        "validation_metrics_optimised"
                    ]
                ),
                "test_metrics_at_0_5": (
                    run_document["test_metrics_at_0_5"]
                ),
                "test_metrics_optimised": (
                    run_document["test_metrics_optimised"]
                ),
            }
            for run_document in all_run_documents
        ],
    }

    with REPEATED_RESULTS_PATH.open(
        "w",
        encoding="utf-8",
    ) as handle:
        json.dump(
            make_json_serialisable(repeated_document),
            handle,
            ensure_ascii=False,
            indent=2,
        )

    print()
    print("=" * 100)
    print("OUTPUTS")
    print("=" * 100)
    print(
        "Fixed sentence split:\n"
        f"  {SPLIT_PATH.resolve()}"
    )
    print(
        "Semantic feature metadata:\n"
        f"  {LABELS_PATH.resolve()}"
    )
    print(
        "Per-run results:\n"
        f"  {RUNS_DIR.resolve()}"
    )
    print(
        "Repeated-run summary:\n"
        f"  {REPEATED_RESULTS_PATH.resolve()}"
    )
    print(
        "Test bootstrap confidence intervals:\n"
        f"  {BOOTSTRAP_RESULTS_PATH.resolve()}"
    )

    if SAVE_REFERENCE_MODEL:
        print(
            "Neutral reference model (first predeclared seed; not "
            "best-test selected):\n"
            f"  {REFERENCE_MODEL_DIR.resolve()}"
        )


if __name__ == "__main__":
    main()

/root/.pyenv/versions/3.10.16/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

================================================================================
CUDA
================================================================================
PyTorch version: 2.13.0+cu130
CUDA available: True
CUDA runtime: 13.0
GPU: NVIDIA GeForce RTX 5070 Ti
VRAM: 15.92 GiB

================================================================================
LOADING DATA
================================================================================
================================================================================
FEATURE SWITCHES
================================================================================
Disabled features: Rigidity, Shape, State, State_of_Matter
All unlisted features are enabled.

Training CoNLL-U sentences: 12,544
Test CoNLL-U sentences: 2,077
Training sentences represented in tagged JSONL: 11,511
Test sentences represented in tagged JSONL: 1,815
Training tagged NOUN/PROPN records: 47,371
Test tagged NOUN/PROPN records: 6,198

Eligible training-file sentences with at least one non-empty feature target: 11,198
Eligible test-file sentences with at least one non-empty feature target: 1,759

Sentence-level multilabel-stratified train/validation split:
  Eligible training sentences : 11,198
  Target validation sentences : 2,240
  Actual validation sentences : 2,313
  Training sentences retained : 8,885
  Split seed used             : 42
  Stratification labels       : 37
  Coverage-rejected attempts  : 0
  Mean relative prevalence error: 0.008441

Feature                              All sent.      Train      Valid    Valid %
--------------------------------------------------------------------------------
Abstract                                  4469       3575        894      0.200
Animal                                     621        497        124      0.200
Animate                                     52         42         10      0.192
Artefact                                  1778       1422        356      0.200
Body_Part                                  265        212         53      0.200
Comestible                                 534        427        107      0.200
Communication                             1984       1587        397      0.200
Currency                                   197        158         39      0.198
Duration                                  1338       1070        268      0.200
Elongated                                  649        519        130      0.200
Eventive                                  3749       2999        750      0.200
Feminine                                   733        586        147      0.201
Fluid                                       87         70         17      0.195
Garment                                     62         50         12      0.194
Inanimate                                 4282       3425        857      0.200
Internal_Control                           107         86         21      0.196
Language                                    27         22          5      0.185
Location                                  3232       2585        647      0.200
Machine                                    694        555        139      0.200
Masculine                                 1829       1463        366      0.200
Natural                                    326        261         65      0.199
Natural_Force                              142        114         28      0.197
Non_Rigid                                 1200        960        240      0.200
Organisation                              3003       2402        601      0.200
Plant                                       66         53         13      0.197
Point_in_Time                             1211        969        242      0.200
Pointy                                      82         66         16      0.195
Question                                   161        129         32      0.199
Rigid                                     1965       1572        393      0.200
Solid                                     4618       3694        924      0.200
Sound                                      187        150         37      0.198
Statement                                 1115        892        223      0.200
Substance                                  826        661        165      0.200
Time                                        81         65         16      0.198
Unspecified_Gender_or_Neuter              2592       2074        518      0.200
Vehicle                                    344        275         69      0.201
Web_Location                               252        202         50      0.198

Actual validation sentence fraction: 0.2066


================================================================================
HELD-OUT TEST LABEL COVERAGE WARNING
================================================================================
The test corpus contains direct independent targets that have no training-derived neural output head. They will NOT be added to the model vocabulary. Complete test truth will be read directly from the source annotations instead.
  Human                               support=1

================================================================================
DATASET SPLIT
================================================================================
train       : 8,885 sentences | 37,581 NOUN/PROPN tokens | 124,956 complete positives -> 54,319 independent positives | 2,686 empty-feature tokens excluded | source=training file
validation  : 2,313 sentences | 9,408 NOUN/PROPN tokens | 31,274 complete positives -> 13,650 independent positives | 675 empty-feature tokens excluded | source=training file
test        : 1,759 sentences | 6,127 NOUN/PROPN tokens | 20,568 complete positives -> 8,826 independent positives | 423 empty-feature tokens excluded | source=test file

================================================================================
NEURAL OUTPUT FEATURES
================================================================================
Complete evaluation features: 39
Independent neural outputs: 37
Deterministic-only features in this training split: 2

Feature                              Independent train support
----------------------------------------------------------------
Abstract                                                  5754
Animal                                                     691
Animate                                                     46
Artefact                                                  1866
Body_Part                                                  318
Comestible                                                 671
Communication                                             2041
Currency                                                   179
Duration                                                  1393
Elongated                                                  632
Eventive                                                  4258
Feminine                                                   867
Fluid                                                       84
Garment                                                     60
Inanimate                                                 5851
Internal_Control                                            91
Language                                                    23
Location                                                  4733
Machine                                                    738
Masculine                                                 2684
Natural                                                    307
Natural_Force                                              130
Non_Rigid                                                 1378
Organisation                                              4425
Plant                                                       68
Point_in_Time                                             1257
Pointy                                                      78
Question                                                   130
Rigid                                                     2165
Solid                                                     5807
Sound                                                      169
Statement                                                 1038
Substance                                                  913
Time                                                        67
Unspecified_Gender_or_Neuter                              2826
Vehicle                                                    359
Web_Location                                               222

Deterministic-only in this split:
  - Concrete
  - Human

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

================================================================================
REPEATED FINE-TUNING
================================================================================
Runs: 30
Seeds: [11, 23, 37, 53, 71, 89, 107, 127, 149, 173, 197, 223, 251, 281, 313, 347, 383, 421, 461, 503, 547, 593, 641, 691, 743, 797, 853, 911, 971, 1031]
Train/validation split is fixed across all runs; only the fine-tuning seed changes.


====================================================================================================
RUN 1/30 | SEED 11
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:01<00:00, 231.37it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.83      1405     0.8930     0.8949    +0.0019
Animal                                    0.83       184     0.9421     0.9500    +0.0079
Animate                                   0.16        13     0.8696     0.8800    +0.0104
Artefact                                  0.64       503     0.9026     0.9040    +0.0014
Body_Part                                 0.20        74     0.9054     0.9419    +0.0365
Comestible                                0.61       157     0.9554     0.9585    +0.0031
Communication                             0.48       534     0.8056     0.8097    +0.0040
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.19       340     0.8488     0.8559    +0.0072
Elongated                                 0.50       168     0.7927     0.7927    +0.0000
Eventive                                  0.38      1068     0.8852     0.8863    +0.0011
Feminine                                  0.25       204     0.9429     0.9507    +0.0078
Fluid                                     0.48        19     0.8889     0.9189    +0.0300
Garment                                   0.21        17     0.9412     0.9714    +0.0303
Inanimate                                 0.46      1511     0.9379     0.9397    +0.0018
Internal_Control                          0.16        21     0.4444     0.5455    +0.1010
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.41      1209     0.9253     0.9281    +0.0028
Machine                                   0.47       180     0.9029     0.9034    +0.0006
Masculine                                 0.33       671     0.9321     0.9350    +0.0029
Natural                                   0.50        79     0.8774     0.8774    +0.0000
Natural_Force                             0.27        35     0.8824     0.8857    +0.0034
Non_Rigid                                 0.42       335     0.7853     0.7920    +0.0067
Organisation                              0.54      1086     0.9036     0.9052    +0.0016
Plant                                     0.50        15     0.9333     0.9333    +0.0000
Point_in_Time                             0.81       336     0.8627     0.8664    +0.0037
Pointy                                    0.48        20     0.7500     0.7805    +0.0305
Question                                  0.13        33     0.8254     0.8485    +0.0231
Rigid                                     0.16       603     0.8676     0.8817    +0.0141
Solid                                     0.49      1409     0.8941     0.8944    +0.0004
Sound                                     0.50        42     0.8193     0.8193    +0.0000
Statement                                 0.65       264     0.7558     0.7611    +0.0053
Substance                                 0.49       217     0.8879     0.8956    +0.0077
Time                                      0.07        16     0.2857     0.5714    +0.2857
Unspecified_Gender_or_Neuter              0.29       677     0.8920     0.8952    +0.0032
Vehicle                                   0.64       100     0.9596     0.9694    +0.0098
Web_Location                              0.89        55     0.8624     0.9126    +0.0502

VALIDATION @ 0.5
direct_f1_macro: 0.8583917149373657
direct_f1_micro: 0.8919932357914859
direct_precision_macro: 0.8932801660354701
direct_precision_micro: 0.8952184179456907
direct_recall_macro: 0.8414128011069223
direct_recall_micro: 0.8887912087912088
f1_macro: 0.9061109862907876
f1_micro: 0.9394178065677592
precision_macro: 0.9148608616154085
precision_micro: 0.9445037008306668
recall_macro: 0.897852441932904
recall_micro: 0.9343863912515188

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8772009861334609
direct_f1_micro: 0.8955606877084937
direct_precision_macro: 0.8844443601299837
direct_precision_micro: 0.8962506420133539
direct_recall_macro: 0.8754233280245372
direct_recall_micro: 0.8948717948717949
f1_macro: 0.9142566962433125
f1_micro: 0.9418397911294069
precision_macro: 0.9174219825703849
precision_micro: 0.9436081779375421
recall_macro: 0.9121409532198508
recall_micro: 0.9400780200805782

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.771994511163575
direct_f1_micro: 0.8642227905655016
direct_precision_macro: 0.8232657759035853
direct_precision_micro: 0.8669327251995439
direct_recall_macro: 0.7538538993720512
direct_recall_micro: 0.8615297450424929
f1_macro: 0.8549544117513351
f1_micro: 0.91631288732738
precision_macro: 0.8800223591582534
precision_micro: 0.9196787148594378
recall_macro: 0.8387123531325201
recall_micro: 0.9129716063788409

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8008842886335391
direct_f1_micro: 0.8625007081751742
direct_precision_macro: 0.836618958389421
direct_precision_micro: 0.8624518468162248
direct_recall_macro: 0.7883123211095494
direct_recall_micro: 0.8625495750708215
f1_macro: 0.8528452046769146
f1_micro: 0.916557321281042
precision_macro: 0.8745198545750407
precision_micro: 0.9161566112892257
recall_macro: 0.8416569649613075
recall_micro: 0.9169583819525476

====================================================================================================
RUN 2/30 | SEED 23
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 837.09it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.64      1405     0.8973     0.9022    +0.0049
Animal                                    0.25       184     0.9363     0.9396    +0.0033
Animate                                   0.26        13     0.8182     0.9167    +0.0985
Artefact                                  0.54       503     0.9045     0.9082    +0.0037
Body_Part                                 0.35        74     0.8966     0.9041    +0.0076
Comestible                                0.50       157     0.9620     0.9620    +0.0000
Communication                             0.47       534     0.8064     0.8105    +0.0041
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.12       340     0.8493     0.8579    +0.0086
Elongated                                 0.55       168     0.7938     0.7975    +0.0036
Eventive                                  0.56      1068     0.8873     0.8899    +0.0026
Feminine                                  0.86       204     0.9242     0.9397    +0.0155
Fluid                                     0.39        19     0.8333     0.8947    +0.0614
Garment                                   0.71        17     0.9143     0.9697    +0.0554
Inanimate                                 0.43      1511     0.9340     0.9348    +0.0008
Internal_Control                          0.16        21     0.5517     0.6286    +0.0768
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.53      1209     0.9238     0.9256    +0.0019
Machine                                   0.53       180     0.8793     0.8895    +0.0102
Masculine                                 0.16       671     0.9237     0.9317    +0.0080
Natural                                   0.62        79     0.8903     0.8961    +0.0058
Natural_Force                             0.44        35     0.8824     0.8986    +0.0162
Non_Rigid                                 0.73       335     0.7994     0.8031    +0.0036
Organisation                              0.21      1086     0.8873     0.8913    +0.0039
Plant                                     0.50        15     0.9333     0.9333    +0.0000
Point_in_Time                             0.90       336     0.8666     0.8748    +0.0082
Pointy                                    0.47        20     0.7027     0.7692    +0.0665
Question                                  0.21        33     0.8387     0.8923    +0.0536
Rigid                                     0.30       603     0.8684     0.8729    +0.0046
Solid                                     0.32      1409     0.8882     0.8914    +0.0033
Sound                                     0.25        42     0.7952     0.8276    +0.0324
Statement                                 0.70       264     0.7716     0.7748    +0.0033
Substance                                 0.44       217     0.8950     0.8984    +0.0034
Time                                      0.28        16     0.4000     0.6000    +0.2000
Unspecified_Gender_or_Neuter              0.78       677     0.8858     0.8869    +0.0011
Vehicle                                   0.22       100     0.9592     0.9648    +0.0056
Web_Location                              0.91        55     0.8829     0.9216    +0.0387

VALIDATION @ 0.5
direct_f1_macro: 0.8589971767198961
direct_f1_micro: 0.8898217705111209
direct_precision_macro: 0.901024130540711
direct_precision_micro: 0.8945653783503628
direct_recall_macro: 0.8391711828242915
direct_recall_micro: 0.8851282051282051
f1_macro: 0.9010084022458336
f1_micro: 0.9352221506761108
precision_macro: 0.910498648562561
precision_micro: 0.9417104324709848
recall_macro: 0.8925029131550648
recall_micro: 0.9288226641938991

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8810811241690285
direct_f1_micro: 0.8945921173235564
direct_precision_macro: 0.8979411695483552
direct_precision_micro: 0.8954128440366973
direct_recall_macro: 0.867795154267676
direct_recall_micro: 0.8937728937728938
f1_macro: 0.9118408933160966
f1_micro: 0.9371390065460147
precision_macro: 0.92129341304133
precision_micro: 0.940458556063631
recall_macro: 0.9039148759836534
recall_micro: 0.9338428087229008

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7787917956014584
direct_f1_micro: 0.8646684831970936
direct_precision_macro: 0.8192696415722234
direct_precision_micro: 0.8663405755886703
direct_recall_macro: 0.7687182461283595
direct_recall_micro: 0.8630028328611898
f1_macro: 0.8556183762298512
f1_micro: 0.9200029240478569
precision_macro: 0.8726419796588403
precision_micro: 0.9221825997752918
recall_macro: 0.8461673823960538
recall_micro: 0.9178335278101906

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7809798090996164
direct_f1_micro: 0.8647058823529412
direct_precision_macro: 0.8066698188520961
direct_precision_micro: 0.8632411067193676
direct_recall_macro: 0.7711696857570929
direct_recall_micro: 0.8661756373937677
f1_macro: 0.8529939256448491
f1_micro: 0.9170717480069998
precision_macro: 0.8736284840079305
precision_micro: 0.9168934681181959
recall_macro: 0.8433552512919648
recall_micro: 0.9172500972384287

====================================================================================================
RUN 3/30 | SEED 37
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1018.52it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.64      1405     0.8990     0.9009    +0.0019
Animal                                    0.48       184     0.9421     0.9451    +0.0029
Animate                                   0.50        13     0.9167     0.9167    +0.0000
Artefact                                  0.57       503     0.9139     0.9154    +0.0015
Body_Part                                 0.23        74     0.9241     0.9412    +0.0170
Comestible                                0.48       157     0.9557     0.9590    +0.0033
Communication                             0.31       534     0.8094     0.8142    +0.0048
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.58       340     0.8596     0.8643    +0.0047
Elongated                                 0.52       168     0.7988     0.8036    +0.0048
Eventive                                  0.65      1068     0.8903     0.8941    +0.0038
Feminine                                  0.16       204     0.9261     0.9324    +0.0063
Fluid                                     0.17        19     0.8571     0.9268    +0.0697
Garment                                   0.16        17     0.9375     0.9714    +0.0339
Inanimate                                 0.34      1511     0.9388     0.9399    +0.0011
Internal_Control                          0.32        21     0.5000     0.6452    +0.1452
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.58      1209     0.9211     0.9231    +0.0020
Machine                                   0.56       180     0.8927     0.8966    +0.0039
Masculine                                 0.58       671     0.9299     0.9347    +0.0049
Natural                                   0.50        79     0.9032     0.9032    +0.0000
Natural_Force                             0.63        35     0.8857     0.8955    +0.0098
Non_Rigid                                 0.42       335     0.7882     0.7954    +0.0072
Organisation                              0.48      1086     0.8916     0.8928    +0.0012
Plant                                     0.50        15     0.8966     0.8966    +0.0000
Point_in_Time                             0.82       336     0.8665     0.8717    +0.0052
Pointy                                    0.42        20     0.7568     0.7805    +0.0237
Question                                  0.25        33     0.8387     0.8615    +0.0228
Rigid                                     0.50       603     0.8809     0.8809    +0.0000
Solid                                     0.41      1409     0.8932     0.8968    +0.0035
Sound                                     0.51        42     0.8090     0.8276    +0.0186
Statement                                 0.69       264     0.7588     0.7664    +0.0076
Substance                                 0.19       217     0.8817     0.8899    +0.0082
Time                                      0.17        16     0.4348     0.5263    +0.0915
Unspecified_Gender_or_Neuter              0.17       677     0.8844     0.8911    +0.0067
Vehicle                                   0.77       100     0.9500     0.9592    +0.0092
Web_Location                              0.86        55     0.8246     0.9126    +0.0881

VALIDATION @ 0.5
direct_f1_macro: 0.8637155046646224
direct_f1_micro: 0.8925449871465295
direct_precision_macro: 0.896075166336613
direct_precision_micro: 0.8948453608247423
direct_recall_macro: 0.8463551410988747
direct_recall_micro: 0.8902564102564102
f1_macro: 0.9028563268002545
f1_micro: 0.9372317682799415
precision_macro: 0.9125593508248026
precision_micro: 0.9423058275962377
recall_macro: 0.8944863517281536
recall_micro: 0.9322120611370468

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8803401624230455
direct_f1_micro: 0.8964074712854574
direct_precision_macro: 0.8930187863678033
direct_precision_micro: 0.8980222042496875
direct_recall_macro: 0.8753619077380658
direct_recall_micro: 0.8947985347985348
f1_macro: 0.912570778122735
f1_micro: 0.9394897811742419
precision_macro: 0.916245370395095
precision_micro: 0.94344307226002
recall_macro: 0.9103744649374678
recall_micro: 0.9355694826373345

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7761233995898293
direct_f1_micro: 0.8637268847795163
direct_precision_macro: 0.8128778962100159
direct_precision_micro: 0.8674285714285714
direct_recall_macro: 0.7661772655794841
direct_recall_micro: 0.860056657223796
f1_macro: 0.8526927837828211
f1_micro: 0.9156156229416214
precision_macro: 0.865982831514579
precision_micro: 0.9188659844293199
recall_macro: 0.8465012577806076
recall_micro: 0.912388175807079

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7800317543447489
direct_f1_micro: 0.8611111111111112
direct_precision_macro: 0.8094348553784495
direct_precision_micro: 0.8615995462280204
direct_recall_macro: 0.7735377073847151
direct_recall_micro: 0.8606232294617564
f1_macro: 0.8508584959323598
f1_micro: 0.9140940249890612
precision_macro: 0.866063800673972
precision_micro: 0.9140495867768595
recall_macro: 0.8448607110702431
recall_micro: 0.9141384675223648

====================================================================================================
RUN 4/30 | SEED 53
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 997.18it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.72      1405     0.8952     0.8964    +0.0012
Animal                                    0.14       184     0.9421     0.9459    +0.0038
Animate                                   0.50        13     0.8696     0.8696    +0.0000
Artefact                                  0.16       503     0.8966     0.9006    +0.0040
Body_Part                                 0.21        74     0.8936     0.9459    +0.0523
Comestible                                0.39       157     0.9554     0.9653    +0.0099
Communication                             0.52       534     0.8116     0.8131    +0.0016
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.61       340     0.8592     0.8650    +0.0058
Elongated                                 0.50       168     0.8013     0.8013    +0.0000
Eventive                                  0.52      1068     0.8882     0.8914    +0.0032
Feminine                                  0.81       204     0.9275     0.9363    +0.0087
Fluid                                     0.50        19     0.9231     0.9231    +0.0000
Garment                                   0.75        17     0.9143     0.9697    +0.0554
Inanimate                                 0.52      1511     0.9376     0.9382    +0.0006
Internal_Control                          0.09        21     0.3704     0.5714    +0.2011
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.41      1209     0.9200     0.9209    +0.0010
Machine                                   0.27       180     0.8989     0.9027    +0.0038
Masculine                                 0.69       671     0.9326     0.9366    +0.0039
Natural                                   0.48        79     0.8861     0.8931    +0.0070
Natural_Force                             0.38        35     0.8529     0.8732    +0.0203
Non_Rigid                                 0.61       335     0.7905     0.7988    +0.0083
Organisation                              0.68      1086     0.8963     0.8971    +0.0008
Plant                                     0.50        15     0.8966     0.8966    +0.0000
Point_in_Time                             0.58       336     0.8683     0.8731    +0.0048
Pointy                                    0.32        20     0.7317     0.8000    +0.0683
Question                                  0.10        33     0.8333     0.8615    +0.0282
Rigid                                     0.32       603     0.8823     0.8869    +0.0046
Solid                                     0.41      1409     0.8898     0.8927    +0.0029
Sound                                     0.36        42     0.7857     0.8000    +0.0143
Statement                                 0.45       264     0.7608     0.7713    +0.0105
Substance                                 0.46       217     0.8904     0.8939    +0.0035
Time                                      0.24        16     0.3810     0.6207    +0.2397
Unspecified_Gender_or_Neuter              0.34       677     0.8869     0.8907    +0.0037
Vehicle                                   0.50       100     0.9694     0.9694    +0.0000
Web_Location                              0.90        55     0.8785     0.9020    +0.0235

VALIDATION @ 0.5
direct_f1_macro: 0.8572313038199505
direct_f1_micro: 0.8917685171550581
direct_precision_macro: 0.8924074392553288
direct_precision_micro: 0.8962557347935475
direct_recall_macro: 0.8407564994758003
direct_recall_micro: 0.8873260073260073
f1_macro: 0.9044263489178789
f1_micro: 0.9390143902242946
precision_macro: 0.9132742345377053
precision_micro: 0.9443743734031887
recall_macro: 0.8967039271977015
recall_micro: 0.9337149069514613

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8787642459602079
direct_f1_micro: 0.8954061006982726
direct_precision_macro: 0.8855663037966602
direct_precision_micro: 0.8983775811209439
direct_recall_macro: 0.8747480888422101
direct_recall_micro: 0.8924542124542124
f1_macro: 0.9135264975237651
f1_micro: 0.9408813929932311
precision_macro: 0.9167012428859811
precision_micro: 0.9462212592568638
recall_macro: 0.9118529498771257
recall_micro: 0.9356014580801945

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7883849869550071
direct_f1_micro: 0.8666249217282405
direct_precision_macro: 0.8282147921979934
direct_precision_micro: 0.8707389613360788
direct_recall_macro: 0.7764474727409325
direct_recall_micro: 0.8625495750708215
f1_macro: 0.8631289577777548
f1_micro: 0.9204014029618083
precision_macro: 0.8801146953001651
precision_micro: 0.922198360015619
recall_macro: 0.8546471641057184
recall_micro: 0.9186114352392065

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7875820570834566
direct_f1_micro: 0.8623842789799512
direct_precision_macro: 0.7965316875937762
direct_precision_micro: 0.8644955590981553
direct_recall_macro: 0.7913982479713632
direct_recall_micro: 0.8602832861189802
f1_macro: 0.8621304688574076
f1_micro: 0.9174651939628898
precision_macro: 0.8734773077907184
precision_micro: 0.9202249938860357
recall_macro: 0.8596602145640148
recall_micro: 0.9147218980941269

====================================================================================================
RUN 5/30 | SEED 71
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 956.80it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.55      1405     0.8960     0.8984    +0.0024
Animal                                    0.48       184     0.9474     0.9503    +0.0029
Animate                                   0.66        13     0.8000     0.8696    +0.0696
Artefact                                  0.57       503     0.9020     0.9034    +0.0014
Body_Part                                 0.21        74     0.9231     0.9404    +0.0173
Comestible                                0.77       157     0.9494     0.9548    +0.0055
Communication                             0.65       534     0.7967     0.7992    +0.0026
Currency                                  0.57        45     0.9890     1.0000    +0.0110
Duration                                  0.55       340     0.8526     0.8542    +0.0016
Elongated                                 0.52       168     0.7734     0.7768    +0.0033
Eventive                                  0.41      1068     0.8871     0.8880    +0.0008
Feminine                                  0.85       204     0.9294     0.9400    +0.0106
Fluid                                     0.20        19     0.8421     0.8718    +0.0297
Garment                                   0.41        17     0.9697     1.0000    +0.0303
Inanimate                                 0.48      1511     0.9366     0.9369    +0.0004
Internal_Control                          0.31        21     0.3704     0.6250    +0.2546
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.62      1209     0.9266     0.9317    +0.0051
Machine                                   0.50       180     0.9043     0.9043    +0.0000
Masculine                                 0.79       671     0.9332     0.9351    +0.0018
Natural                                   0.61        79     0.8790     0.8889    +0.0099
Natural_Force                             0.58        35     0.8571     0.8696    +0.0124
Non_Rigid                                 0.20       335     0.7976     0.8027    +0.0051
Organisation                              0.57      1086     0.8956     0.8967    +0.0011
Plant                                     0.48        15     0.9286     0.9655    +0.0369
Point_in_Time                             0.27       336     0.8798     0.8857    +0.0059
Pointy                                    0.62        20     0.8205     0.8421    +0.0216
Question                                  0.51        33     0.8571     0.8710    +0.0138
Rigid                                     0.52       603     0.8782     0.8795    +0.0013
Solid                                     0.45      1409     0.8907     0.8920    +0.0013
Sound                                     0.34        42     0.7654     0.8046    +0.0392
Statement                                 0.27       264     0.7613     0.7715    +0.0101
Substance                                 0.24       217     0.8750     0.8991    +0.0241
Time                                      0.09        16     0.3000     0.5000    +0.2000
Unspecified_Gender_or_Neuter              0.34       677     0.8864     0.8934    +0.0070
Vehicle                                   0.32       100     0.9394     0.9500    +0.0106
Web_Location                              0.93        55     0.8571     0.9038    +0.0467

VALIDATION @ 0.5
direct_f1_macro: 0.8539974770891072
direct_f1_micro: 0.891303549796263
direct_precision_macro: 0.8876290421653865
direct_precision_micro: 0.8932381723199176
direct_recall_macro: 0.8393374367576758
direct_recall_micro: 0.8893772893772893
f1_macro: 0.9046845268390277
f1_micro: 0.9380175255245599
precision_macro: 0.9141888497132007
precision_micro: 0.943371818505223
recall_macro: 0.8959651149027116
recall_micro: 0.9327236682228048

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8782687061389085
direct_f1_micro: 0.8947002160934696
direct_precision_macro: 0.8916598759589086
direct_precision_micro: 0.8946019189921629
direct_recall_macro: 0.8731469712473333
direct_recall_micro: 0.8947985347985348
f1_macro: 0.914148161664834
f1_micro: 0.9395097818754217
precision_macro: 0.9191985439229131
precision_micro: 0.9439065324038213
recall_macro: 0.9105530025348176
recall_micro: 0.9351538018801561

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7683746132790791
direct_f1_micro: 0.8645227505987
direct_precision_macro: 0.8181868689062539
direct_precision_micro: 0.8700791920119362
direct_recall_macro: 0.7483567699474405
direct_recall_micro: 0.8590368271954674
f1_macro: 0.8451310572236721
f1_micro: 0.9191016189473169
precision_macro: 0.8731262749429487
precision_micro: 0.9260648536597403
recall_macro: 0.8274651770396665
recall_micro: 0.9122423181641385

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7708296971747756
direct_f1_micro: 0.8621707538601272
direct_precision_macro: 0.7985724847261605
direct_precision_micro: 0.8638380161528836
direct_recall_macro: 0.7662691790962767
direct_recall_micro: 0.8605099150141643
f1_macro: 0.8458441222029243
f1_micro: 0.9176579789442829
precision_macro: 0.8653828860137451
precision_micro: 0.9220951352412744
recall_macro: 0.8375338701162716
recall_micro: 0.9132633216647219

====================================================================================================
RUN 6/30 | SEED 89
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 934.62it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.59      1405     0.9013     0.9023    +0.0010
Animal                                    0.19       184     0.9415     0.9479    +0.0064
Animate                                   0.25        13     0.8182     0.9167    +0.0985
Artefact                                  0.29       503     0.9065     0.9154    +0.0088
Body_Part                                 0.09        74     0.9296     0.9342    +0.0046
Comestible                                0.52       157     0.9587     0.9618    +0.0031
Communication                             0.57       534     0.8101     0.8133    +0.0032
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.59       340     0.8469     0.8605    +0.0135
Elongated                                 0.66       168     0.7706     0.7908    +0.0202
Eventive                                  0.71      1068     0.8903     0.8934    +0.0030
Feminine                                  0.87       204     0.9375     0.9440    +0.0065
Fluid                                     0.38        19     0.8947     0.9000    +0.0053
Garment                                   0.45        17     0.9697     1.0000    +0.0303
Inanimate                                 0.52      1511     0.9373     0.9376    +0.0003
Internal_Control                          0.10        21     0.5000     0.6316    +0.1316
Language                                  0.78         5     0.8333     1.0000    +0.1667
Location                                  0.55      1209     0.9236     0.9250    +0.0014
Machine                                   0.49       180     0.8902     0.8934    +0.0032
Masculine                                 0.37       671     0.9404     0.9430    +0.0026
Natural                                   0.63        79     0.8861     0.9091    +0.0230
Natural_Force                             0.50        35     0.9014     0.9014    +0.0000
Non_Rigid                                 0.66       335     0.7989     0.8097    +0.0109
Organisation                              0.42      1086     0.8917     0.8921    +0.0004
Plant                                     0.50        15     0.9333     0.9333    +0.0000
Point_in_Time                             0.11       336     0.8580     0.8698    +0.0118
Pointy                                    0.47        20     0.8108     0.8205    +0.0097
Question                                  0.17        33     0.8387     0.8657    +0.0270
Rigid                                     0.44       603     0.8720     0.8782    +0.0062
Solid                                     0.35      1409     0.8882     0.8888    +0.0006
Sound                                     0.62        42     0.7765     0.8205    +0.0440
Statement                                 0.55       264     0.7784     0.7867    +0.0083
Substance                                 0.35       217     0.8848     0.8993    +0.0145
Time                                      0.32        16     0.3000     0.5385    +0.2385
Unspecified_Gender_or_Neuter              0.58       677     0.8882     0.8891    +0.0008
Vehicle                                   0.41       100     0.9645     0.9697    +0.0052
Web_Location                              0.93        55     0.8496     0.9020    +0.0524

VALIDATION @ 0.5
direct_f1_macro: 0.8573371843496076
direct_f1_micro: 0.8923574130522605
direct_precision_macro: 0.8910292486321022
direct_precision_micro: 0.8946903306576331
direct_recall_macro: 0.8456017236991064
direct_recall_micro: 0.89003663003663
f1_macro: 0.903703842721468
f1_micro: 0.9377712063257369
precision_macro: 0.9082931523887862
precision_micro: 0.9427103528499419
recall_macro: 0.9013167104499388
recall_micro: 0.9328835454371043

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8833811376077265
direct_f1_micro: 0.8968935888962326
direct_precision_macro: 0.8978404711997838
direct_precision_micro: 0.8990724381625441
direct_recall_macro: 0.8730221018868078
direct_recall_micro: 0.8947252747252747
f1_macro: 0.9156166649206827
f1_micro: 0.9392751574347771
precision_macro: 0.9218204205166833
precision_micro: 0.9438238522631884
recall_macro: 0.9109923052889707
recall_micro: 0.9347700965658374

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7785042802207405
direct_f1_micro: 0.8587314194939294
direct_precision_macro: 0.8183532741123503
direct_precision_micro: 0.8599022838313828
direct_recall_macro: 0.7668999307713046
direct_recall_micro: 0.8575637393767706
f1_macro: 0.8570937721818738
f1_micro: 0.9159074299634592
precision_macro: 0.8711545171380445
precision_micro: 0.9178302900107411
recall_macro: 0.8481946476520843
recall_micro: 0.9139926098794243

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.772292797971926
direct_f1_micro: 0.8564449241606544
direct_precision_macro: 0.8046137482339147
direct_precision_micro: 0.8587377534745956
direct_recall_macro: 0.7569615782034563
direct_recall_micro: 0.8541643059490085
f1_macro: 0.8448909469288296
f1_micro: 0.9135760296701152
precision_macro: 0.8710574276749846
precision_micro: 0.916976880877743
recall_macro: 0.8318947835401238
recall_micro: 0.9102003111629716

====================================================================================================
RUN 7/30 | SEED 107
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 964.39it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.52      1405     0.8968     0.8972    +0.0003
Animal                                    0.50       184     0.9532     0.9532    +0.0000
Animate                                   0.41        13     0.8182     0.8696    +0.0514
Artefact                                  0.47       503     0.9107     0.9131    +0.0024
Body_Part                                 0.15        74     0.9155     0.9481    +0.0326
Comestible                                0.24       157     0.9363     0.9470    +0.0107
Communication                             0.55       534     0.8176     0.8197    +0.0021
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.26       340     0.8497     0.8555    +0.0058
Elongated                                 0.67       168     0.7744     0.7923    +0.0179
Eventive                                  0.60      1068     0.8840     0.8877    +0.0037
Feminine                                  0.75       204     0.9327     0.9417    +0.0091
Fluid                                     0.38        19     0.8649     0.8947    +0.0299
Garment                                   0.17        17     0.9412     0.9714    +0.0303
Inanimate                                 0.55      1511     0.9362     0.9377    +0.0014
Internal_Control                          0.18        21     0.3704     0.6471    +0.2767
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.59      1209     0.9174     0.9232    +0.0058
Machine                                   0.49       180     0.9023     0.9054    +0.0031
Masculine                                 0.63       671     0.9305     0.9336    +0.0031
Natural                                   0.45        79     0.8645     0.8734    +0.0089
Natural_Force                             0.37        35     0.8358     0.8529    +0.0171
Non_Rigid                                 0.65       335     0.7946     0.7975    +0.0029
Organisation                              0.48      1086     0.8921     0.8929    +0.0008
Plant                                     0.50        15     0.8966     0.8966    +0.0000
Point_in_Time                             0.91       336     0.8550     0.8640    +0.0090
Pointy                                    0.59        20     0.7368     0.7568    +0.0199
Question                                  0.10        33     0.8571     0.8788    +0.0216
Rigid                                     0.28       603     0.8700     0.8824    +0.0123
Solid                                     0.46      1409     0.8897     0.8908    +0.0011
Sound                                     0.55        42     0.8250     0.8354    +0.0104
Statement                                 0.71       264     0.7592     0.7762    +0.0170
Substance                                 0.29       217     0.8811     0.8953    +0.0142
Time                                      0.19        16     0.2857     0.5714    +0.2857
Unspecified_Gender_or_Neuter              0.23       677     0.8829     0.8875    +0.0046
Vehicle                                   0.50       100     0.9641     0.9641    +0.0000
Web_Location                              0.30        55     0.8649     0.8850    +0.0201

VALIDATION @ 0.5
direct_f1_macro: 0.8515432495889701
direct_f1_micro: 0.8897461332157683
direct_precision_macro: 0.8878756630884876
direct_precision_micro: 0.892401798216523
direct_recall_macro: 0.8323637810864581
direct_recall_micro: 0.8871062271062271
f1_macro: 0.9022915576043868
f1_micro: 0.9365505489735881
precision_macro: 0.9136611309157376
precision_micro: 0.9417127339734265
recall_macro: 0.891746962897133
recall_micro: 0.9314446505084095

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.876735827501475
direct_f1_micro: 0.8946594085626012
direct_precision_macro: 0.8929371161806561
direct_precision_micro: 0.8983601713694785
direct_recall_macro: 0.8656146102583925
direct_recall_micro: 0.890989010989011
f1_macro: 0.910400471732969
f1_micro: 0.9392735984050677
precision_macro: 0.9201494558706488
precision_micro: 0.9446043398117906
recall_macro: 0.9025955512447766
recall_micro: 0.9340026859372003

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.78821512525199
direct_f1_micro: 0.8607148945843042
direct_precision_macro: 0.8190560206162933
direct_precision_micro: 0.8633150934792522
direct_recall_macro: 0.774826484950096
direct_recall_micro: 0.8581303116147309
f1_macro: 0.8589302316636992
f1_micro: 0.9154090354090354
precision_macro: 0.873364630764737
precision_micro: 0.9195859091355117
recall_macro: 0.8489957931095825
recall_micro: 0.9112699338778686

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7847122594730506
direct_f1_micro: 0.8604704010907851
direct_precision_macro: 0.7989288197960757
direct_precision_micro: 0.8628232881394554
direct_recall_macro: 0.7811633330212933
direct_recall_micro: 0.8581303116147309
f1_macro: 0.8585081414972675
f1_micro: 0.9143191629472451
precision_macro: 0.8725611359101985
precision_micro: 0.9173395977095874
recall_macro: 0.8504517461791509
recall_micro: 0.911318553092182

====================================================================================================
RUN 8/30 | SEED 127
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1005.63it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.43      1405     0.9000     0.9021    +0.0021
Animal                                    0.60       184     0.9396     0.9448    +0.0052
Animate                                   0.25        13     0.8182     0.8696    +0.0514
Artefact                                  0.60       503     0.9080     0.9108    +0.0028
Body_Part                                 0.07        74     0.8811     0.9150    +0.0339
Comestible                                0.68       157     0.9464     0.9615    +0.0152
Communication                             0.37       534     0.8011     0.8099    +0.0087
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.76       340     0.8518     0.8576    +0.0058
Elongated                                 0.52       168     0.7761     0.7927    +0.0166
Eventive                                  0.62      1068     0.8867     0.8902    +0.0035
Feminine                                  0.50       204     0.9484     0.9484    +0.0000
Fluid                                     0.71        19     0.9000     0.9231    +0.0231
Garment                                   0.53        17     0.9714     1.0000    +0.0286
Inanimate                                 0.43      1511     0.9400     0.9402    +0.0002
Internal_Control                          0.12        21     0.3846     0.6286    +0.2440
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.49      1209     0.9297     0.9301    +0.0004
Machine                                   0.22       180     0.8983     0.8997    +0.0014
Masculine                                 0.21       671     0.9269     0.9342    +0.0073
Natural                                   0.59        79     0.8861     0.8974    +0.0114
Natural_Force                             0.47        35     0.8571     0.8732    +0.0161
Non_Rigid                                 0.52       335     0.8141     0.8147    +0.0007
Organisation                              0.45      1086     0.8977     0.8996    +0.0019
Plant                                     0.50        15     0.9333     0.9333    +0.0000
Point_in_Time                             0.49       336     0.8735     0.8752    +0.0017
Pointy                                    0.19        20     0.4516     0.7556    +0.3039
Question                                  0.06        33     0.8197     0.8788    +0.0591
Rigid                                     0.42       603     0.8831     0.8865    +0.0034
Solid                                     0.48      1409     0.8946     0.8952    +0.0006
Sound                                     0.85        42     0.8049     0.8056    +0.0007
Statement                                 0.62       264     0.7592     0.7600    +0.0008
Substance                                 0.32       217     0.8920     0.9013    +0.0094
Time                                      0.12        16     0.2727     0.5238    +0.2511
Unspecified_Gender_or_Neuter              0.21       677     0.8881     0.8909    +0.0029
Vehicle                                   0.50       100     0.9645     0.9645    +0.0000
Web_Location                              0.93        55     0.8571     0.8911    +0.0339

VALIDATION @ 0.5
direct_f1_macro: 0.8475013083003781
direct_f1_micro: 0.8935904499540863
direct_precision_macro: 0.8826614377812734
direct_precision_micro: 0.8960589318600368
direct_recall_macro: 0.8333030651034169
direct_recall_micro: 0.8911355311355311
f1_macro: 0.8982769869566218
f1_micro: 0.9392800950454355
precision_macro: 0.9066603171570389
precision_micro: 0.9432477750548175
recall_macro: 0.892715457432092
recall_micro: 0.9353456545373153

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8785198899766626
direct_f1_micro: 0.8974237164260918
direct_precision_macro: 0.887380361075617
direct_precision_micro: 0.8952971199416697
direct_recall_macro: 0.8762305080747577
direct_recall_micro: 0.8995604395604395
f1_macro: 0.9135547237869048
f1_micro: 0.94210012951918
precision_macro: 0.918077038241721
precision_micro: 0.9422357268511115
recall_macro: 0.9114850946351624
recall_micro: 0.9419645712093112

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7724800458518524
direct_f1_micro: 0.8638764268271907
direct_precision_macro: 0.8183772806290364
direct_precision_micro: 0.8658925318761385
direct_recall_macro: 0.7544658440063791
direct_recall_micro: 0.8618696883852691
f1_macro: 0.8482644802105187
f1_micro: 0.9192367753269569
precision_macro: 0.8718322901213841
precision_micro: 0.9226586990595611
recall_macro: 0.8332298326022919
recall_micro: 0.9158401400233372

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7717206758869195
direct_f1_micro: 0.8617261635788522
direct_precision_macro: 0.8060717375855755
direct_precision_micro: 0.8591057551526072
direct_recall_macro: 0.7572956780436566
direct_recall_micro: 0.8643626062322947
f1_macro: 0.8453833954691222
f1_micro: 0.9184341291964611
precision_macro: 0.8747107390126602
precision_micro: 0.9157925267075941
recall_macro: 0.8300677165804089
recall_micro: 0.9210910151691949

====================================================================================================
RUN 9/30 | SEED 149
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 953.53it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.53      1405     0.8850     0.8860    +0.0010
Animal                                    0.52       184     0.9373     0.9399    +0.0026
Animate                                   0.50        13     0.7000     0.7000    +0.0000
Artefact                                  0.49       503     0.8509     0.8532    +0.0023
Body_Part                                 0.16        74     0.8828     0.9211    +0.0383
Comestible                                0.77       157     0.9404     0.9484    +0.0079
Communication                             0.38       534     0.7621     0.7724    +0.0103
Currency                                  0.74        45     0.9677     0.9890    +0.0213
Duration                                  0.56       340     0.8389     0.8475    +0.0086
Elongated                                 0.21       168     0.6205     0.6601    +0.0396
Eventive                                  0.44      1068     0.8644     0.8650    +0.0006
Feminine                                  0.79       204     0.9305     0.9386    +0.0081
Fluid                                     0.27        19     0.8649     0.9000    +0.0351
Garment                                   0.50        17     0.9143     0.9143    +0.0000
Inanimate                                 0.39      1511     0.9242     0.9283    +0.0041
Internal_Control                          0.11        21     0.0909     0.5143    +0.4234
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.59      1209     0.9104     0.9138    +0.0034
Machine                                   0.62       180     0.8539     0.8653    +0.0114
Masculine                                 0.24       671     0.9278     0.9311    +0.0033
Natural                                   0.89        79     0.8481     0.8671    +0.0190
Natural_Force                             0.72        35     0.8406     0.8529    +0.0124
Non_Rigid                                 0.70       335     0.7679     0.7763    +0.0084
Organisation                              0.43      1086     0.8722     0.8747    +0.0025
Plant                                     0.69        15     0.6286     0.7692    +0.1407
Point_in_Time                             0.49       336     0.8667     0.8684    +0.0017
Pointy                                    0.11        20     0.1739     0.4286    +0.2547
Question                                  0.24        33     0.8000     0.8387    +0.0387
Rigid                                     0.42       603     0.8517     0.8605    +0.0088
Solid                                     0.66      1409     0.8742     0.8831    +0.0089
Sound                                     0.71        42     0.6750     0.7200    +0.0450
Statement                                 0.62       264     0.7342     0.7433    +0.0091
Substance                                 0.45       217     0.8578     0.8656    +0.0078
Time                                      0.30        16     0.1176     0.3333    +0.2157
Unspecified_Gender_or_Neuter              0.36       677     0.8719     0.8755    +0.0036
Vehicle                                   0.67       100     0.9406     0.9596    +0.0190
Web_Location                              0.93        55     0.8519     0.8932    +0.0414

VALIDATION @ 0.5
direct_f1_macro: 0.7902602106004852
direct_f1_micro: 0.8697602588615972
direct_precision_macro: 0.863015331596822
direct_precision_micro: 0.873099069836114
direct_recall_macro: 0.7804436683831805
direct_recall_micro: 0.8664468864468865
f1_macro: 0.8599547420666903
f1_micro: 0.925822984110663
precision_macro: 0.8769820349398575
precision_micro: 0.9303819948981239
recall_macro: 0.855697566906567
recall_micro: 0.9213084351218265

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8296822806718752
direct_f1_micro: 0.8749862561847169
direct_precision_macro: 0.8536772395202121
direct_precision_micro: 0.8754675467546754
direct_recall_macro: 0.8193066932786691
direct_recall_micro: 0.8745054945054945
f1_macro: 0.880244811401487
f1_micro: 0.9281054133337608
precision_macro: 0.8866933064516155
precision_micro: 0.9305667170272268
recall_macro: 0.8793369098049021
recall_micro: 0.9256570953507706

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7466601660261152
direct_f1_micro: 0.8456132396282022
direct_precision_macro: 0.766960560056015
direct_precision_micro: 0.8459008957931738
direct_recall_macro: 0.7424745911395025
direct_recall_micro: 0.8453257790368272
f1_macro: 0.8371327941200198
f1_micro: 0.908194252119622
precision_macro: 0.8470621018342671
precision_micro: 0.9075989317795582
recall_macro: 0.8360141858935796
recall_micro: 0.9087903539478802

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7594587162163721
direct_f1_micro: 0.8446179082527292
direct_precision_macro: 0.781818946324693
direct_precision_micro: 0.8432346961825163
direct_recall_macro: 0.7549505293884882
direct_recall_micro: 0.8460056657223796
f1_macro: 0.8407487757246158
f1_micro: 0.9066052599684886
precision_macro: 0.848571700398792
precision_micro: 0.9039976797022284
recall_macro: 0.8430487035125879
recall_micro: 0.9092279268767016

====================================================================================================
RUN 10/30 | SEED 173
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 945.55it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.37      1405     0.8933     0.8961    +0.0028
Animal                                    0.51       184     0.9451     0.9477    +0.0026
Animate                                   0.39        13     0.8182     0.8333    +0.0152
Artefact                                  0.50       503     0.9002     0.9002    +0.0000
Body_Part                                 0.16        74     0.9252     0.9281    +0.0029
Comestible                                0.44       157     0.9548     0.9649    +0.0100
Communication                             0.63       534     0.8159     0.8233    +0.0074
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.30       340     0.8443     0.8559    +0.0117
Elongated                                 0.70       168     0.7802     0.8000    +0.0198
Eventive                                  0.66      1068     0.8850     0.8865    +0.0015
Feminine                                  0.85       204     0.9458     0.9500    +0.0042
Fluid                                     0.15        19     0.8649     0.9048    +0.0399
Garment                                   0.46        17     0.9697     0.9714    +0.0017
Inanimate                                 0.51      1511     0.9386     0.9389    +0.0003
Internal_Control                          0.09        21     0.3846     0.4848    +0.1002
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.36      1209     0.9206     0.9234    +0.0028
Machine                                   0.68       180     0.8889     0.8947    +0.0058
Masculine                                 0.64       671     0.9337     0.9363    +0.0025
Natural                                   0.23        79     0.8805     0.8862    +0.0057
Natural_Force                             0.50        35     0.8611     0.8611    +0.0000
Non_Rigid                                 0.36       335     0.7947     0.8006    +0.0058
Organisation                              0.45      1086     0.8955     0.8969    +0.0014
Plant                                     0.50        15     0.9333     0.9333    +0.0000
Point_in_Time                             0.56       336     0.8757     0.8763    +0.0006
Pointy                                    0.58        20     0.8000     0.8421    +0.0421
Question                                  0.57        33     0.8571     0.8710    +0.0138
Rigid                                     0.49       603     0.8870     0.8872    +0.0002
Solid                                     0.50      1409     0.8920     0.8920    +0.0000
Sound                                     0.75        42     0.8471     0.8493    +0.0023
Statement                                 0.34       264     0.7417     0.7570    +0.0152
Substance                                 0.14       217     0.8785     0.9039    +0.0254
Time                                      0.12        16     0.2727     0.5641    +0.2914
Unspecified_Gender_or_Neuter              0.22       677     0.8933     0.8978    +0.0045
Vehicle                                   0.61       100     0.9648     0.9697    +0.0049
Web_Location                              0.58        55     0.9143     0.9231    +0.0088

VALIDATION @ 0.5
direct_f1_macro: 0.8594157985255528
direct_f1_micro: 0.892317866196407
direct_precision_macro: 0.8932426518036667
direct_precision_micro: 0.8949812071633871
direct_recall_macro: 0.8441571784127586
direct_recall_micro: 0.8896703296703297
f1_macro: 0.9098732061091298
f1_micro: 0.9383965431384833
precision_macro: 0.9174007170267344
precision_micro: 0.9428645211272152
recall_macro: 0.9028809265217871
recall_micro: 0.9339707104943403

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8770797545192581
direct_f1_micro: 0.8956992393212405
direct_precision_macro: 0.886400480849843
direct_precision_micro: 0.8942602599678692
direct_recall_macro: 0.8744812495572866
direct_recall_micro: 0.8971428571428571
f1_macro: 0.916345444497128
f1_micro: 0.9409127301841473
precision_macro: 0.9222346959814561
precision_micro: 0.9423915832691814
recall_macro: 0.9133641669639374
recall_micro: 0.9394385112233804

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7862940348683565
direct_f1_micro: 0.8619692761181339
direct_precision_macro: 0.8272768304580032
direct_precision_micro: 0.8624092558983666
direct_recall_macro: 0.7756380137458055
direct_recall_micro: 0.8615297450424929
f1_macro: 0.863034944837384
f1_micro: 0.9170386632516161
precision_macro: 0.8825813193947875
precision_micro: 0.9202036520291771
recall_macro: 0.8506185480560566
recall_micro: 0.9138953714507974

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7818582116536924
direct_f1_micro: 0.8591557233838697
direct_precision_macro: 0.8047831717136885
direct_precision_micro: 0.8546759363085894
direct_recall_macro: 0.7770028349636992
direct_recall_micro: 0.8636827195467423
f1_macro: 0.8569861207191614
f1_micro: 0.9173844474099235
precision_macro: 0.8796248397497681
precision_micro: 0.9156293892575192
recall_macro: 0.8465292493540159
recall_micro: 0.919146246596655

====================================================================================================
RUN 11/30 | SEED 197
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 946.87it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.60      1405     0.8985     0.9020    +0.0035
Animal                                    0.34       184     0.9330     0.9418    +0.0089
Animate                                   0.50        13     0.8696     0.8696    +0.0000
Artefact                                  0.56       503     0.8905     0.8939    +0.0034
Body_Part                                 0.16        74     0.8767     0.9290    +0.0523
Comestible                                0.65       157     0.9620     0.9649    +0.0028
Communication                             0.43       534     0.8011     0.8037    +0.0025
Currency                                  0.80        45     0.9890     1.0000    +0.0110
Duration                                  0.70       340     0.8441     0.8606    +0.0165
Elongated                                 0.58       168     0.7938     0.8013    +0.0074
Eventive                                  0.47      1068     0.8833     0.8843    +0.0011
Feminine                                  0.56       204     0.9392     0.9438    +0.0046
Fluid                                     0.84        19     0.8718     0.8889    +0.0171
Garment                                   0.50        17     0.9714     0.9714    +0.0000
Inanimate                                 0.30      1511     0.9346     0.9362    +0.0016
Internal_Control                          0.09        21     0.3704     0.5946    +0.2242
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.45      1209     0.9216     0.9223    +0.0008
Machine                                   0.67       180     0.8997     0.9123    +0.0126
Masculine                                 0.50       671     0.9312     0.9312    +0.0000
Natural                                   0.40        79     0.8662     0.8875    +0.0213
Natural_Force                             0.63        35     0.8696     0.8824    +0.0128
Non_Rigid                                 0.39       335     0.7917     0.8006    +0.0089
Organisation                              0.39      1086     0.8912     0.8944    +0.0031
Plant                                     0.50        15     0.9333     0.9333    +0.0000
Point_in_Time                             0.56       336     0.8665     0.8729    +0.0065
Pointy                                    0.49        20     0.7692     0.8000    +0.0308
Question                                  0.27        33     0.8387     0.8750    +0.0363
Rigid                                     0.50       603     0.8864     0.8864    +0.0000
Solid                                     0.51      1409     0.8902     0.8916    +0.0014
Sound                                     0.63        42     0.8049     0.8101    +0.0052
Statement                                 0.27       264     0.7595     0.7633    +0.0037
Substance                                 0.30       217     0.8868     0.9002    +0.0134
Time                                      0.12        16     0.3810     0.5366    +0.1556
Unspecified_Gender_or_Neuter              0.40       677     0.8889     0.8903    +0.0015
Vehicle                                   0.61       100     0.9543     0.9641    +0.0098
Web_Location                              0.94        55     0.8704     0.9126    +0.0423

VALIDATION @ 0.5
direct_f1_macro: 0.8575763386354373
direct_f1_micro: 0.890137741046832
direct_precision_macro: 0.8904103565003512
direct_precision_micro: 0.8925966850828729
direct_recall_macro: 0.84286027119841
direct_recall_micro: 0.8876923076923077
f1_macro: 0.9045803784268025
f1_micro: 0.9369013179042108
precision_macro: 0.9112660220650389
precision_micro: 0.941866477089123
recall_macro: 0.898458082736852
recall_micro: 0.9319882330370276

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8771117284049932
direct_f1_micro: 0.8936668129296476
direct_precision_macro: 0.8865385014484872
direct_precision_micro: 0.8921010366476858
direct_recall_macro: 0.8721711998834263
direct_recall_micro: 0.8952380952380953
f1_macro: 0.912937676670371
f1_micro: 0.9390710864027428
precision_macro: 0.9200013238481645
precision_micro: 0.9410461419901743
recall_macro: 0.9073613060809976
recall_micro: 0.937104303894609

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7836166948860298
direct_f1_micro: 0.8623114438017466
direct_precision_macro: 0.8124929485925861
direct_precision_micro: 0.8630945623793848
direct_recall_macro: 0.7701582508409363
direct_recall_micro: 0.8615297450424929
f1_macro: 0.8568201731532212
f1_micro: 0.9179896756598812
precision_macro: 0.8724464015272375
precision_micro: 0.9195121951219513
recall_macro: 0.8466981651784269
recall_micro: 0.9164721898094127

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7779803909375428
direct_f1_micro: 0.859736159657233
direct_precision_macro: 0.7928554165015893
direct_precision_micro: 0.8554919780096488
direct_recall_macro: 0.7758882531978493
direct_recall_micro: 0.8640226628895185
f1_macro: 0.8544660868320921
f1_micro: 0.9175792227929063
precision_macro: 0.8706988817255632
precision_micro: 0.9144774966196639
recall_macro: 0.846259118670257
recall_micro: 0.9207020614546869

====================================================================================================
RUN 12/30 | SEED 223
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 961.95it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.30      1405     0.8958     0.8993    +0.0035
Animal                                    0.68       184     0.9399     0.9503    +0.0104
Animate                                   0.49        13     0.8696     0.9167    +0.0471
Artefact                                  0.52       503     0.9091     0.9109    +0.0018
Body_Part                                 0.50        74     0.9103     0.9103    +0.0000
Comestible                                0.27       157     0.9460     0.9530    +0.0069
Communication                             0.36       534     0.8147     0.8179    +0.0031
Currency                                  0.66        45     0.9890     1.0000    +0.0110
Duration                                  0.85       340     0.8496     0.8527    +0.0031
Elongated                                 0.65       168     0.7674     0.7962    +0.0288
Eventive                                  0.49      1068     0.8874     0.8891    +0.0017
Feminine                                  0.87       204     0.9330     0.9415    +0.0084
Fluid                                     0.60        19     0.9000     0.9231    +0.0231
Garment                                   0.50        17     1.0000     1.0000    +0.0000
Inanimate                                 0.41      1511     0.9353     0.9370    +0.0017
Internal_Control                          0.31        21     0.3846     0.5517    +0.1671
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.27      1209     0.9182     0.9203    +0.0022
Machine                                   0.48       180     0.8939     0.8969    +0.0031
Masculine                                 0.37       671     0.9372     0.9393    +0.0022
Natural                                   0.57        79     0.8790     0.8903    +0.0113
Natural_Force                             0.86        35     0.8571     0.8657    +0.0085
Non_Rigid                                 0.74       335     0.8006     0.8043    +0.0038
Organisation                              0.35      1086     0.8927     0.8975    +0.0048
Plant                                     0.42        15     0.8276     0.8667    +0.0391
Point_in_Time                             0.66       336     0.8683     0.8720    +0.0037
Pointy                                    0.29        20     0.2963     0.7000    +0.4037
Question                                  0.29        33     0.8387     0.8615    +0.0228
Rigid                                     0.42       603     0.8823     0.8829    +0.0006
Solid                                     0.71      1409     0.8891     0.8934    +0.0043
Sound                                     0.75        42     0.8235     0.8421    +0.0186
Statement                                 0.35       264     0.7564     0.7698    +0.0134
Substance                                 0.49       217     0.8894     0.8919    +0.0025
Time                                      0.27        16     0.1739     0.4848    +0.3109
Unspecified_Gender_or_Neuter              0.62       677     0.8833     0.8900    +0.0067
Vehicle                                   0.89       100     0.9447     0.9588    +0.0140
Web_Location                              0.92        55     0.8348     0.9038    +0.0691

VALIDATION @ 0.5
direct_f1_macro: 0.8383495617195226
direct_f1_micro: 0.8902035716910414
direct_precision_macro: 0.8704208022598958
direct_precision_micro: 0.8930256561486287
direct_recall_macro: 0.8270329268615035
direct_recall_micro: 0.8873992673992674
f1_macro: 0.8903482611891709
f1_micro: 0.9365444285461648
precision_macro: 0.9004979064643936
precision_micro: 0.941798428557571
recall_macro: 0.8854907477812096
recall_micro: 0.93134872417983

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8724829774308478
direct_f1_micro: 0.89529045262965
direct_precision_macro: 0.8961138788284141
direct_precision_micro: 0.8957829116244957
direct_recall_macro: 0.8583276172986826
direct_recall_micro: 0.8947985347985348
f1_macro: 0.9082574107494708
f1_micro: 0.9376055047346505
precision_macro: 0.9202692999553898
precision_micro: 0.942865457367349
recall_macro: 0.8977312652529534
recall_micro: 0.9324039137942061

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7708551294572714
direct_f1_micro: 0.8591893581945313
direct_precision_macro: 0.8187189957674869
direct_precision_micro: 0.8620807665982204
direct_recall_macro: 0.7537611780411712
direct_recall_micro: 0.8563172804532578
f1_macro: 0.8475756116961748
f1_micro: 0.9154148652939595
precision_macro: 0.8745431280741204
precision_micro: 0.9197958081774898
recall_macro: 0.8320774768354301
recall_micro: 0.9110754570206145

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.763708980076625
direct_f1_micro: 0.8557970603257476
direct_precision_macro: 0.815948502400066
direct_precision_micro: 0.8572078217371533
direct_recall_macro: 0.7442492751976486
direct_recall_micro: 0.8543909348441926
f1_macro: 0.8401988397664945
f1_micro: 0.9117567865273052
precision_macro: 0.8764684247052735
precision_micro: 0.9181168350998274
recall_macro: 0.8166061946679505
recall_micro: 0.9054842473745625

====================================================================================================
RUN 13/30 | SEED 251
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 978.68it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.53      1405     0.8990     0.8995    +0.0006
Animal                                    0.50       184     0.9477     0.9477    +0.0000
Animate                                   0.50        13     0.8696     0.8696    +0.0000
Artefact                                  0.57       503     0.9093     0.9122    +0.0029
Body_Part                                 0.21        74     0.9041     0.9281    +0.0240
Comestible                                0.33       157     0.9427     0.9565    +0.0138
Communication                             0.48       534     0.8140     0.8173    +0.0034
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.72       340     0.8452     0.8584    +0.0133
Elongated                                 0.65       168     0.7674     0.7771    +0.0097
Eventive                                  0.45      1068     0.8886     0.8897    +0.0011
Feminine                                  0.17       204     0.9363     0.9471    +0.0108
Fluid                                     0.52        19     0.8718     0.8947    +0.0229
Garment                                   0.50        17     0.9444     0.9444    +0.0000
Inanimate                                 0.58      1511     0.9349     0.9366    +0.0017
Internal_Control                          0.27        21     0.3571     0.5455    +0.1883
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.58      1209     0.9183     0.9211    +0.0028
Machine                                   0.88       180     0.8587     0.8783    +0.0196
Masculine                                 0.35       671     0.9360     0.9395    +0.0035
Natural                                   0.45        79     0.8734     0.8750    +0.0016
Natural_Force                             0.50        35     0.8696     0.8696    +0.0000
Non_Rigid                                 0.43       335     0.7971     0.8023    +0.0052
Organisation                              0.64      1086     0.8943     0.8993    +0.0051
Plant                                     0.23        15     0.8966     0.9032    +0.0067
Point_in_Time                             0.36       336     0.8716     0.8821    +0.0105
Pointy                                    0.54        20     0.8000     0.8205    +0.0205
Question                                  0.06        33     0.8308     0.8857    +0.0549
Rigid                                     0.50       603     0.8837     0.8837    +0.0000
Solid                                     0.48      1409     0.8887     0.8901    +0.0015
Sound                                     0.33        42     0.7952     0.8046    +0.0094
Statement                                 0.63       264     0.7556     0.7686    +0.0130
Substance                                 0.31       217     0.8945     0.9055    +0.0110
Time                                      0.22        16     0.1000     0.5143    +0.4143
Unspecified_Gender_or_Neuter              0.60       677     0.8850     0.8904    +0.0054
Vehicle                                   0.20       100     0.9543     0.9600    +0.0057
Web_Location                              0.94        55     0.8034     0.9020    +0.0985

VALIDATION @ 0.5
direct_f1_macro: 0.8469923238349816
direct_f1_micro: 0.8904456262607738
direct_precision_macro: 0.8636572890069857
direct_precision_micro: 0.8915901579140654
direct_recall_macro: 0.8411541970305826
direct_recall_micro: 0.8893040293040293
f1_macro: 0.9014833700489253
f1_micro: 0.9360761318850331
precision_macro: 0.9019650694827822
precision_micro: 0.9380297970716671
recall_macro: 0.9015366161834185
recall_micro: 0.9341305877086398

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8735259099521678
direct_f1_micro: 0.895350119463334
direct_precision_macro: 0.8819939106582606
direct_precision_micro: 0.8984876429361859
direct_recall_macro: 0.8700711234437303
direct_recall_micro: 0.8922344322344322
f1_macro: 0.9111083882060885
f1_micro: 0.939094689853397
precision_macro: 0.9122130461288759
precision_micro: 0.9431990452536851
recall_macro: 0.9114453901423707
recall_micro: 0.9350259001087166

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7707627689808294
direct_f1_micro: 0.8622584848999943
direct_precision_macro: 0.8096380564841622
direct_precision_micro: 0.8623073436083409
direct_recall_macro: 0.7597437576690688
direct_recall_micro: 0.8622096317280453
f1_macro: 0.8526874972004159
f1_micro: 0.917471721928249
precision_macro: 0.869013101976498
precision_micro: 0.9160930683470674
recall_macro: 0.8449946776439995
recall_micro: 0.918854531310774

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7737759499681337
direct_f1_micro: 0.8615944501307858
direct_precision_macro: 0.806972388216569
direct_precision_micro: 0.8647414678689648
direct_recall_macro: 0.7685416104033284
direct_recall_micro: 0.8584702549575071
f1_macro: 0.8464383505796218
f1_micro: 0.9171114523165411
precision_macro: 0.8659672549296251
precision_micro: 0.9194643991594585
recall_macro: 0.8394204912727548
recall_micro: 0.9147705173084403

====================================================================================================
RUN 14/30 | SEED 281
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 951.89it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.85      1405     0.8868     0.8932    +0.0064
Animal                                    0.19       184     0.9418     0.9428    +0.0010
Animate                                   0.23        13     0.8696     0.8800    +0.0104
Artefact                                  0.41       503     0.9002     0.9047    +0.0045
Body_Part                                 0.05        74     0.9028     0.9161    +0.0134
Comestible                                0.51       157     0.9620     0.9651    +0.0031
Communication                             0.51       534     0.8071     0.8098    +0.0027
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.55       340     0.8496     0.8542    +0.0046
Elongated                                 0.54       168     0.7660     0.7754    +0.0094
Eventive                                  0.50      1068     0.8785     0.8785    +0.0000
Feminine                                  0.25       204     0.9412     0.9466    +0.0054
Fluid                                     0.60        19     0.8947     0.9189    +0.0242
Garment                                   0.60        17     0.9412     0.9697    +0.0285
Inanimate                                 0.54      1511     0.9353     0.9364    +0.0011
Internal_Control                          0.25        21     0.3846     0.5625    +0.1779
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.58      1209     0.9273     0.9284    +0.0011
Machine                                   0.52       180     0.8940     0.8966    +0.0026
Masculine                                 0.61       671     0.9371     0.9390    +0.0019
Natural                                   0.71        79     0.8627     0.8919    +0.0291
Natural_Force                             0.45        35     0.8529     0.8571    +0.0042
Non_Rigid                                 0.35       335     0.8054     0.8127    +0.0073
Organisation                              0.44      1086     0.8924     0.8986    +0.0063
Plant                                     0.50        15     0.9333     0.9333    +0.0000
Point_in_Time                             0.37       336     0.8692     0.8728    +0.0036
Pointy                                    0.24        20     0.6667     0.7500    +0.0833
Question                                  0.28        33     0.8525     0.8750    +0.0225
Rigid                                     0.36       603     0.8740     0.8766    +0.0026
Solid                                     0.39      1409     0.8834     0.8870    +0.0036
Sound                                     0.67        42     0.8095     0.8250    +0.0155
Statement                                 0.53       264     0.7510     0.7574    +0.0064
Substance                                 0.27       217     0.8904     0.8947    +0.0043
Time                                      0.14        16     0.4348     0.5366    +0.1018
Unspecified_Gender_or_Neuter              0.32       677     0.8904     0.8962    +0.0058
Vehicle                                   0.29       100     0.9641     0.9694    +0.0053
Web_Location                              0.80        55     0.8571     0.9126    +0.0555

VALIDATION @ 0.5
direct_f1_macro: 0.8570158094386069
direct_f1_micro: 0.8891913766463101
direct_precision_macro: 0.8928615594334398
direct_precision_micro: 0.8930682825894177
direct_recall_macro: 0.8396102352387124
direct_recall_micro: 0.8853479853479853
f1_macro: 0.9025539806522342
f1_micro: 0.9366310504634398
precision_macro: 0.9116414194860113
precision_micro: 0.9427599611273081
recall_macro: 0.8941280286901838
recall_micro: 0.9305813135511927

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8747241804142849
direct_f1_micro: 0.8932188463232056
direct_precision_macro: 0.8842433481975076
direct_precision_micro: 0.8947948831054257
direct_recall_macro: 0.8724684785799329
direct_recall_micro: 0.8916483516483517
f1_macro: 0.9111934870055791
f1_micro: 0.938383611707755
precision_macro: 0.9139618395825017
precision_micro: 0.940826690665981
recall_macro: 0.9104856522370255
recall_micro: 0.9359531879516532

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7768004400160308
direct_f1_micro: 0.8643044320382819
direct_precision_macro: 0.8105807331867597
direct_precision_micro: 0.8690571657692748
direct_recall_macro: 0.7600819868508792
direct_recall_micro: 0.8596033994334278
f1_macro: 0.8544046775703044
f1_micro: 0.9186813186813186
precision_macro: 0.8738909872578787
precision_micro: 0.9228731233441272
recall_macro: 0.8407227703681039
recall_micro: 0.9145274212368728

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7886993049096568
direct_f1_micro: 0.8624425662261047
direct_precision_macro: 0.8140739669492134
direct_precision_micro: 0.8634711494775102
direct_recall_macro: 0.7835529327963037
direct_recall_micro: 0.8614164305949008
f1_macro: 0.8618478972330357
f1_micro: 0.9180806067382955
precision_macro: 0.877625544565301
precision_micro: 0.9180359747204667
recall_macro: 0.8549872867070678
recall_micro: 0.9181252430960716

====================================================================================================
RUN 15/30 | SEED 313
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 987.91it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.48      1405     0.8947     0.8959    +0.0012
Animal                                    0.74       184     0.9373     0.9503    +0.0129
Animate                                   0.29        13     0.8696     0.9167    +0.0471
Artefact                                  0.58       503     0.9113     0.9130    +0.0017
Body_Part                                 0.13        74     0.9041     0.9139    +0.0098
Comestible                                0.45       157     0.9457     0.9524    +0.0067
Communication                             0.35       534     0.7962     0.7982    +0.0019
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.44       340     0.8588     0.8600    +0.0012
Elongated                                 0.57       168     0.8075     0.8150    +0.0076
Eventive                                  0.65      1068     0.8830     0.8869    +0.0039
Feminine                                  0.38       204     0.9440     0.9474    +0.0033
Fluid                                     0.50        19     0.8649     0.8649    +0.0000
Garment                                   0.50        17     1.0000     1.0000    +0.0000
Inanimate                                 0.39      1511     0.9375     0.9396    +0.0021
Internal_Control                          0.08        21     0.3846     0.6500    +0.2654
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.34      1209     0.9164     0.9186    +0.0022
Machine                                   0.28       180     0.8940     0.9016    +0.0077
Masculine                                 0.49       671     0.9435     0.9442    +0.0008
Natural                                   0.72        79     0.8662     0.8774    +0.0112
Natural_Force                             0.69        35     0.8000     0.8235    +0.0235
Non_Rigid                                 0.45       335     0.8164     0.8208    +0.0044
Organisation                              0.49      1086     0.8939     0.8944    +0.0005
Plant                                     0.44        15     0.8462     0.8889    +0.0427
Point_in_Time                             0.54       336     0.8733     0.8812    +0.0079
Pointy                                    0.47        20     0.7568     0.8205    +0.0638
Question                                  0.12        33     0.8254     0.8485    +0.0231
Rigid                                     0.30       603     0.8805     0.8871    +0.0066
Solid                                     0.60      1409     0.8927     0.8933    +0.0006
Sound                                     0.63        42     0.8000     0.8250    +0.0250
Statement                                 0.41       264     0.7529     0.7610    +0.0082
Substance                                 0.38       217     0.8744     0.8864    +0.0120
Time                                      0.13        16     0.2857     0.5263    +0.2406
Unspecified_Gender_or_Neuter              0.63       677     0.8891     0.8936    +0.0045
Vehicle                                   0.37       100     0.9694     0.9697    +0.0003
Web_Location                              0.95        55     0.8673     0.8972    +0.0299

VALIDATION @ 0.5
direct_f1_macro: 0.8535956730183566
direct_f1_micro: 0.8917309812568909
direct_precision_macro: 0.8925068850208365
direct_precision_micro: 0.8946902654867257
direct_recall_macro: 0.8357777608771568
direct_recall_micro: 0.8887912087912088
f1_macro: 0.9031598137089798
f1_micro: 0.9383811590708142
precision_macro: 0.9145134859141677
precision_micro: 0.9435841065597621
recall_macro: 0.8935100789602524
recall_micro: 0.933235275308563

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8773876162207411
direct_f1_micro: 0.8950854466278771
direct_precision_macro: 0.8845005123601868
direct_precision_micro: 0.8942019448709513
direct_recall_macro: 0.8728234639153992
direct_recall_micro: 0.895970695970696
f1_macro: 0.9116327496502237
f1_micro: 0.9405367254294926
precision_macro: 0.9183742270723028
precision_micro: 0.9436701322947179
recall_macro: 0.9061330352779524
recall_micro: 0.9374240583232077

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7762704998276426
direct_f1_micro: 0.8645300602341175
direct_precision_macro: 0.8223618440495362
direct_precision_micro: 0.8670922147498005
direct_recall_macro: 0.7632624533299585
direct_recall_micro: 0.8619830028328612
f1_macro: 0.8519779454765242
f1_micro: 0.9187277428167228
precision_macro: 0.8735342697829699
precision_micro: 0.9218306412139011
recall_macro: 0.8404394834196449
recall_micro: 0.9156456631660832

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7756857955332512
direct_f1_micro: 0.8630935536815892
direct_precision_macro: 0.7954371239123568
direct_precision_micro: 0.8621664405246495
direct_recall_macro: 0.7720007226784062
direct_recall_micro: 0.8640226628895185
f1_macro: 0.8503509456765315
f1_micro: 0.9188189187215501
precision_macro: 0.8713177305826105
precision_micro: 0.9200506995563789
recall_macro: 0.8412407177222528
recall_micro: 0.9175904317386231

====================================================================================================
RUN 16/30 | SEED 347
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1048.28it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.59      1405     0.8994     0.9008    +0.0014
Animal                                    0.67       184     0.9396     0.9418    +0.0023
Animate                                   0.10        13     0.7826     0.8462    +0.0635
Artefact                                  0.32       503     0.9093     0.9098    +0.0005
Body_Part                                 0.17        74     0.9116     0.9342    +0.0226
Comestible                                0.66       157     0.9401     0.9487    +0.0087
Communication                             0.40       534     0.8064     0.8107    +0.0043
Currency                                  0.48        45     0.9888     1.0000    +0.0112
Duration                                  0.70       340     0.8584     0.8674    +0.0090
Elongated                                 0.69       168     0.7781     0.8026    +0.0245
Eventive                                  0.60      1068     0.8913     0.8947    +0.0035
Feminine                                  0.87       204     0.9435     0.9502    +0.0068
Fluid                                     0.08        19     0.8571     0.9048    +0.0476
Garment                                   0.22        17     0.9697     0.9714    +0.0017
Inanimate                                 0.61      1511     0.9350     0.9372    +0.0022
Internal_Control                          0.14        21     0.3846     0.5806    +0.1960
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.52      1209     0.9247     0.9254    +0.0007
Machine                                   0.34       180     0.8977     0.9111    +0.0134
Masculine                                 0.55       671     0.9343     0.9363    +0.0020
Natural                                   0.31        79     0.8718     0.8944    +0.0226
Natural_Force                             0.50        35     0.8824     0.8824    +0.0000
Non_Rigid                                 0.51       335     0.8041     0.8052    +0.0012
Organisation                              0.29      1086     0.8910     0.8974    +0.0064
Plant                                     0.17        15     0.8571     0.9032    +0.0461
Point_in_Time                             0.30       336     0.8726     0.8737    +0.0012
Pointy                                    0.50        20     0.8000     0.8000    +0.0000
Question                                  0.09        33     0.8387     0.8788    +0.0401
Rigid                                     0.29       603     0.8762     0.8801    +0.0040
Solid                                     0.61      1409     0.8930     0.8942    +0.0012
Sound                                     0.38        42     0.7949     0.8395    +0.0446
Statement                                 0.71       264     0.7543     0.7746    +0.0203
Substance                                 0.36       217     0.8879     0.8918    +0.0040
Time                                      0.25        16     0.3636     0.5333    +0.1697
Unspecified_Gender_or_Neuter              0.27       677     0.8907     0.8944    +0.0036
Vehicle                                   0.50       100     0.9746     0.9746    +0.0000
Web_Location                              0.72        55     0.8727     0.9057    +0.0329

VALIDATION @ 0.5
direct_f1_macro: 0.8561502822141515
direct_f1_micro: 0.8927401847150164
direct_precision_macro: 0.8963203286668094
direct_precision_micro: 0.8967989946033859
direct_recall_macro: 0.835827944917406
direct_recall_micro: 0.8887179487179487
f1_macro: 0.9051821859345797
f1_micro: 0.938092940987297
precision_macro: 0.9179311515151227
precision_micro: 0.9435243886660629
recall_macro: 0.8937050190257179
recall_micro: 0.9327236682228048

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8783078990388193
direct_f1_micro: 0.8972600227414445
direct_precision_macro: 0.8892084465960468
direct_precision_micro: 0.8984793946962463
direct_recall_macro: 0.8738618770095672
direct_recall_micro: 0.896043956043956
f1_macro: 0.9148938682792525
f1_micro: 0.9409392106021319
precision_macro: 0.917255176598604
precision_micro: 0.9419946160748622
recall_macro: 0.9142311354696386
recall_micro: 0.9398861674234188

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7826216821566426
direct_f1_micro: 0.8616348618627172
direct_precision_macro: 0.8459148935858265
direct_precision_micro: 0.8663230240549828
direct_recall_macro: 0.7684805229088731
direct_recall_micro: 0.8569971671388102
f1_macro: 0.8599247724375323
f1_micro: 0.915907035851316
precision_macro: 0.8999799696453096
precision_micro: 0.9207901331629895
recall_macro: 0.8450481324040745
recall_micro: 0.9110754570206145

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7846131502913609
direct_f1_micro: 0.8614041057048882
direct_precision_macro: 0.8169719886713885
direct_precision_micro: 0.8621864002724486
direct_recall_macro: 0.7860968980478585
direct_recall_micro: 0.8606232294617564
f1_macro: 0.855474194312481
f1_micro: 0.9160290509849645
precision_macro: 0.8848132254637224
precision_micro: 0.9152953740109704
recall_macro: 0.85322007999824
recall_micro: 0.9167639050952937

====================================================================================================
RUN 17/30 | SEED 383
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 965.01it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.39      1405     0.8970     0.9002    +0.0032
Animal                                    0.58       184     0.9370     0.9421    +0.0052
Animate                                   0.50        13     0.8182     0.8182    +0.0000
Artefact                                  0.52       503     0.9021     0.9039    +0.0018
Body_Part                                 0.55        74     0.9189     0.9315    +0.0126
Comestible                                0.70       157     0.9527     0.9551    +0.0024
Communication                             0.39       534     0.8057     0.8107    +0.0050
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.46       340     0.8567     0.8618    +0.0050
Elongated                                 0.38       168     0.7939     0.8070    +0.0131
Eventive                                  0.48      1068     0.8889     0.8902    +0.0013
Feminine                                  0.82       204     0.9320     0.9383    +0.0062
Fluid                                     0.22        19     0.8718     0.8780    +0.0063
Garment                                   0.50        17     1.0000     1.0000    +0.0000
Inanimate                                 0.66      1511     0.9355     0.9361    +0.0006
Internal_Control                          0.12        21     0.3846     0.5946    +0.2100
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.39      1209     0.9212     0.9233    +0.0021
Machine                                   0.28       180     0.8789     0.8907    +0.0118
Masculine                                 0.45       671     0.9345     0.9370    +0.0025
Natural                                   0.37        79     0.8608     0.8750    +0.0142
Natural_Force                             0.72        35     0.8732     0.9118    +0.0385
Non_Rigid                                 0.39       335     0.7982     0.8103    +0.0121
Organisation                              0.56      1086     0.8952     0.8971    +0.0019
Plant                                     0.50        15     0.8966     0.8966    +0.0000
Point_in_Time                             0.66       336     0.8702     0.8752    +0.0050
Pointy                                    0.60        20     0.8205     0.8421    +0.0216
Question                                  0.05        33     0.8525     0.8657    +0.0132
Rigid                                     0.49       603     0.8823     0.8832    +0.0010
Solid                                     0.45      1409     0.8894     0.8918    +0.0024
Sound                                     0.55        42     0.8095     0.8193    +0.0098
Statement                                 0.46       264     0.7725     0.7816    +0.0091
Substance                                 0.19       217     0.8753     0.8826    +0.0073
Time                                      0.27        16     0.3636     0.5185    +0.1549
Unspecified_Gender_or_Neuter              0.64       677     0.8921     0.8945    +0.0024
Vehicle                                   0.16       100     0.9596     0.9648    +0.0052
Web_Location                              0.95        55     0.8571     0.9020    +0.0448

VALIDATION @ 0.5
direct_f1_macro: 0.8594130887523385
direct_f1_micro: 0.8920577750009188
direct_precision_macro: 0.8942651311379682
direct_precision_micro: 0.8950512574673648
direct_recall_macro: 0.8445107911561676
direct_recall_micro: 0.8890842490842491
f1_macro: 0.90797992611025
f1_micro: 0.9378104254737756
precision_macro: 0.9144827456396788
precision_micro: 0.9428876175700572
recall_macro: 0.9021302466805625
recall_micro: 0.9327876191085247

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8765092372527153
direct_f1_micro: 0.8954219686997221
direct_precision_macro: 0.8893929851971702
direct_precision_micro: 0.8938531172433932
direct_recall_macro: 0.8679310994581803
direct_recall_micro: 0.896996336996337
f1_macro: 0.9142920411549892
f1_micro: 0.939210361395446
precision_macro: 0.9195607853196902
precision_micro: 0.9440191233000613
recall_macro: 0.9101390110937885
recall_micro: 0.9344503421372387

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7773941418228499
direct_f1_micro: 0.8635072167291737
direct_precision_macro: 0.8226773683540414
direct_precision_micro: 0.8660663399065314
direct_recall_macro: 0.7639848039118731
direct_recall_micro: 0.8609631728045326
f1_macro: 0.8573932414066863
f1_micro: 0.9169673330082886
precision_macro: 0.8761077573331062
precision_micro: 0.919567768433405
recall_macro: 0.8468069998967834
recall_micro: 0.9143815635939323

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7847303416550536
direct_f1_micro: 0.8627206880941602
direct_precision_macro: 0.8189543082357854
direct_precision_micro: 0.861648016276704
direct_recall_macro: 0.7792591357062009
direct_recall_micro: 0.8637960339943342
f1_macro: 0.859486528357531
f1_micro: 0.9165630712979891
precision_macro: 0.8938312280204938
precision_micro: 0.9190497140343159
recall_macro: 0.8518768839184389
recall_micro: 0.9140898483080513

====================================================================================================
RUN 18/30 | SEED 421
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 953.41it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.51      1405     0.9004     0.9009    +0.0006
Animal                                    0.50       184     0.9451     0.9451    +0.0000
Animate                                   0.27        13     0.8182     0.8800    +0.0618
Artefact                                  0.26       503     0.9073     0.9110    +0.0038
Body_Part                                 0.07        74     0.8811     0.9114    +0.0303
Comestible                                0.67       157     0.9427     0.9518    +0.0091
Communication                             0.44       534     0.8018     0.8065    +0.0047
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.79       340     0.8521     0.8598    +0.0077
Elongated                                 0.55       168     0.7927     0.8063    +0.0136
Eventive                                  0.43      1068     0.8868     0.8882    +0.0014
Feminine                                  0.75       204     0.9305     0.9343    +0.0039
Fluid                                     0.28        19     0.8889     0.9231    +0.0342
Garment                                   0.12        17     0.9091     0.9444    +0.0354
Inanimate                                 0.63      1511     0.9349     0.9354    +0.0005
Internal_Control                          0.16        21     0.3846     0.6111    +0.2265
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.59      1209     0.9212     0.9240    +0.0027
Machine                                   0.51       180     0.8920     0.8946    +0.0025
Masculine                                 0.81       671     0.9383     0.9399    +0.0016
Natural                                   0.69        79     0.9032     0.9079    +0.0047
Natural_Force                             0.50        35     0.8857     0.8857    +0.0000
Non_Rigid                                 0.63       335     0.7882     0.7926    +0.0044
Organisation                              0.29      1086     0.8917     0.8972    +0.0055
Plant                                     0.34        15     0.8571     0.9333    +0.0762
Point_in_Time                             0.73       336     0.8648     0.8763    +0.0116
Pointy                                    0.60        20     0.7619     0.8205    +0.0586
Question                                  0.31        33     0.8197     0.8750    +0.0553
Rigid                                     0.33       603     0.8774     0.8807    +0.0032
Solid                                     0.65      1409     0.8879     0.8908    +0.0029
Sound                                     0.31        42     0.8095     0.8315    +0.0219
Statement                                 0.66       264     0.7495     0.7635    +0.0140
Substance                                 0.33       217     0.8838     0.8958    +0.0120
Time                                      0.24        16     0.3810     0.5294    +0.1485
Unspecified_Gender_or_Neuter              0.37       677     0.8930     0.8950    +0.0019
Vehicle                                   0.14       100     0.9495     0.9561    +0.0066
Web_Location                              0.91        55     0.8829     0.9216    +0.0387

VALIDATION @ 0.5
direct_f1_macro: 0.8544482178034366
direct_f1_micro: 0.8908649959579629
direct_precision_macro: 0.8953834876748827
direct_precision_micro: 0.8936891772338543
direct_recall_macro: 0.836616615724501
direct_recall_micro: 0.888058608058608
f1_macro: 0.9013903915498637
f1_micro: 0.9370357269189954
precision_macro: 0.9106200995377108
precision_micro: 0.9423997412677878
recall_macro: 0.8932235536037134
recall_micro: 0.9317324294941485

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8789362338004039
direct_f1_micro: 0.8952401971603031
direct_precision_macro: 0.8869724216386888
direct_precision_micro: 0.8990100472813238
direct_recall_macro: 0.8739328859844951
direct_recall_micro: 0.8915018315018315
f1_macro: 0.9127780833638267
f1_micro: 0.9382318877879294
precision_macro: 0.9185639090564788
precision_micro: 0.9440020715996633
recall_macro: 0.9087459491257857
recall_micro: 0.9325318155656456

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7807635071841632
direct_f1_micro: 0.8643633672946668
direct_precision_macro: 0.8212318908949836
direct_precision_micro: 0.8683668801463861
direct_recall_macro: 0.7696286442360517
direct_recall_micro: 0.8603966005665722
f1_macro: 0.8574022782421394
f1_micro: 0.9178403755868545
precision_macro: 0.8715947474623874
precision_micro: 0.9232585596221959
recall_macro: 0.8487297384267214
recall_micro: 0.912485414235706

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7804420741726179
direct_f1_micro: 0.861655587750696
direct_precision_macro: 0.7985502717932331
direct_precision_micro: 0.8640610756608933
direct_recall_macro: 0.7742884753040252
direct_recall_micro: 0.8592634560906516
f1_macro: 0.8539088780221968
f1_micro: 0.9152129422083618
precision_macro: 0.8681112559176167
precision_micro: 0.9172689978511428
recall_macro: 0.8483395838217095
recall_micro: 0.9131660832360949

====================================================================================================
RUN 19/30 | SEED 461
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1004.55it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.69      1405     0.8927     0.8946    +0.0019
Animal                                    0.66       184     0.9421     0.9474    +0.0052
Animate                                   0.50        13     0.9167     0.9167    +0.0000
Artefact                                  0.27       503     0.9000     0.9034    +0.0034
Body_Part                                 0.34        74     0.8936     0.9167    +0.0230
Comestible                                0.26       157     0.9554     0.9620    +0.0066
Communication                             0.60       534     0.7943     0.7996    +0.0053
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.67       340     0.8504     0.8554    +0.0050
Elongated                                 0.56       168     0.7976     0.8085    +0.0109
Eventive                                  0.50      1068     0.8839     0.8839    +0.0000
Feminine                                  0.42       204     0.9291     0.9320    +0.0029
Fluid                                     0.38        19     0.8649     0.8947    +0.0299
Garment                                   0.44        17     0.9412     0.9714    +0.0303
Inanimate                                 0.59      1511     0.9379     0.9396    +0.0017
Internal_Control                          0.10        21     0.3704     0.6111    +0.2407
Language                                  0.91         5     0.9091     1.0000    +0.0909
Location                                  0.72      1209     0.9188     0.9217    +0.0030
Machine                                   0.50       180     0.9029     0.9029    +0.0000
Masculine                                 0.30       671     0.9301     0.9333    +0.0032
Natural                                   0.51        79     0.8974     0.9032    +0.0058
Natural_Force                             0.75        35     0.8824     0.8923    +0.0100
Non_Rigid                                 0.57       335     0.8030     0.8055    +0.0025
Organisation                              0.58      1086     0.8949     0.8974    +0.0026
Plant                                     0.24        15     0.8571     0.9333    +0.0762
Point_in_Time                             0.26       336     0.8614     0.8732    +0.0118
Pointy                                    0.38        20     0.8108     0.8500    +0.0392
Question                                  0.26        33     0.8571     0.8923    +0.0352
Rigid                                     0.54       603     0.8820     0.8832    +0.0013
Solid                                     0.55      1409     0.8959     0.8981    +0.0022
Sound                                     0.52        42     0.8333     0.8434    +0.0100
Statement                                 0.53       264     0.7519     0.7548    +0.0029
Substance                                 0.24       217     0.8765     0.8889    +0.0124
Time                                      0.15        16     0.3000     0.5143    +0.2143
Unspecified_Gender_or_Neuter              0.39       677     0.8912     0.8942    +0.0030
Vehicle                                   0.81       100     0.9543     0.9592    +0.0049
Web_Location                              0.95        55     0.8793     0.9038    +0.0245

VALIDATION @ 0.5
direct_f1_macro: 0.8556625300540268
direct_f1_micro: 0.8908402836462505
direct_precision_macro: 0.8899128439972085
direct_precision_micro: 0.8935652686666176
direct_recall_macro: 0.84133189993641
direct_recall_micro: 0.8881318681318682
f1_macro: 0.9026659397266841
f1_micro: 0.93681278876958
precision_macro: 0.911585582859686
precision_micro: 0.9433582984793957
recall_macro: 0.8952103041537939
recall_micro: 0.9303574854511735

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8805975607700979
direct_f1_micro: 0.8945990783410138
direct_precision_macro: 0.8925877855705437
direct_precision_micro: 0.9004081632653061
direct_recall_macro: 0.8711592596167985
direct_recall_micro: 0.8888644688644689
f1_macro: 0.9146280132846117
f1_micro: 0.9389483855382881
precision_macro: 0.9224796118149603
precision_micro: 0.945848609714156
recall_macro: 0.9077594078737621
recall_micro: 0.9321481102513269

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7688369069070835
direct_f1_micro: 0.862482249360977
direct_precision_macro: 0.7934862084393313
direct_precision_micro: 0.8646924829157175
direct_recall_macro: 0.7544086715357614
direct_recall_micro: 0.8602832861189802
f1_macro: 0.8527749641084119
f1_micro: 0.9176418851237449
precision_macro: 0.8759561777675645
precision_micro: 0.9222609635122526
recall_macro: 0.8384529280115461
recall_micro: 0.9130688448074679

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7671529670857946
direct_f1_micro: 0.8618015963511972
direct_precision_macro: 0.7840422012425632
direct_precision_micro: 0.8672403901319564
direct_recall_macro: 0.7617833372616839
direct_recall_micro: 0.8564305949008498
f1_macro: 0.8393677361286871
f1_micro: 0.9162180679260057
precision_macro: 0.8588477205957832
precision_micro: 0.9222660098522167
recall_macro: 0.8272736448767142
recall_micro: 0.910248930377285

====================================================================================================
RUN 20/30 | SEED 503
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1008.21it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.58      1405     0.8912     0.8934    +0.0022
Animal                                    0.45       184     0.9363     0.9392    +0.0029
Animate                                   0.34        13     0.7619     0.8696    +0.1077
Artefact                                  0.49       503     0.9032     0.9043    +0.0011
Body_Part                                 0.34        74     0.9241     0.9404    +0.0163
Comestible                                0.42       157     0.9460     0.9530    +0.0069
Communication                             0.59       534     0.7966     0.7984    +0.0019
Currency                                  0.77        45     0.9890     1.0000    +0.0110
Duration                                  0.88       340     0.8571     0.8629    +0.0057
Elongated                                 0.47       168     0.7829     0.7879    +0.0050
Eventive                                  0.53      1068     0.8815     0.8815    +0.0000
Feminine                                  0.93       204     0.9249     0.9377    +0.0127
Fluid                                     0.50        19     0.8947     0.8947    +0.0000
Garment                                   0.50        17     0.9697     0.9697    +0.0000
Inanimate                                 0.37      1511     0.9360     0.9381    +0.0021
Internal_Control                          0.12        21     0.5517     0.6286    +0.0768
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.56      1209     0.9193     0.9217    +0.0023
Machine                                   0.56       180     0.8844     0.8895    +0.0051
Masculine                                 0.46       671     0.9377     0.9385    +0.0008
Natural                                   0.29        79     0.8645     0.8875    +0.0230
Natural_Force                             0.61        35     0.8451     0.8788    +0.0337
Non_Rigid                                 0.59       335     0.8029     0.8072    +0.0043
Organisation                              0.47      1086     0.8974     0.9000    +0.0026
Plant                                     0.25        15     0.8966     0.9333    +0.0368
Point_in_Time                             0.50       336     0.8852     0.8852    +0.0000
Pointy                                    0.51        20     0.8000     0.8205    +0.0205
Question                                  0.87        33     0.8615     0.8852    +0.0237
Rigid                                     0.40       603     0.8809     0.8836    +0.0027
Solid                                     0.46      1409     0.8936     0.8943    +0.0008
Sound                                     0.80        42     0.8049     0.8108    +0.0059
Statement                                 0.34       264     0.7643     0.7745    +0.0103
Substance                                 0.46       217     0.8802     0.8833    +0.0031
Time                                      0.08        16     0.4762     0.5333    +0.0571
Unspecified_Gender_or_Neuter              0.49       677     0.8910     0.8920    +0.0010
Vehicle                                   0.93       100     0.9552     0.9641    +0.0089
Web_Location                              0.86        55     0.8496     0.8952    +0.0457

VALIDATION @ 0.5
direct_f1_macro: 0.8631730614039912
direct_f1_micro: 0.8911757139181888
direct_precision_macro: 0.9004072799259675
direct_precision_micro: 0.8941662364481157
direct_recall_macro: 0.8460908754297958
direct_recall_micro: 0.8882051282051282
f1_macro: 0.9058749534088176
f1_micro: 0.9372095640848355
precision_macro: 0.9110264760800905
precision_micro: 0.9426205647378465
recall_macro: 0.9011060706343292
recall_micro: 0.931860331265588

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8777865889687295
direct_f1_micro: 0.8940665488810365
direct_precision_macro: 0.8958281542661904
direct_precision_micro: 0.898431720668738
direct_recall_macro: 0.8665947442244676
direct_recall_micro: 0.8897435897435897
f1_macro: 0.9123104726352705
f1_micro: 0.9377305901496722
precision_macro: 0.927050994876687
precision_micro: 0.9450235427829193
recall_macro: 0.8994502083251166
recall_micro: 0.9305493381083328

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.778979315910413
direct_f1_micro: 0.8633780404637418
direct_precision_macro: 0.8155021331733069
direct_precision_micro: 0.8660357997947783
direct_recall_macro: 0.7641185348313659
direct_recall_micro: 0.8607365439093484
f1_macro: 0.8510546310149206
f1_micro: 0.9194040041944058
precision_macro: 0.8701392955424924
precision_micro: 0.9223053965458192
recall_macro: 0.8405606841758837
recall_micro: 0.9165208090237261

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7725124155101869
direct_f1_micro: 0.8625419773464625
direct_precision_macro: 0.8042320205327431
direct_precision_micro: 0.8665370539798719
direct_recall_macro: 0.7591461587464925
direct_recall_micro: 0.8585835694050992
f1_macro: 0.8471799427519155
f1_micro: 0.917072454547679
precision_macro: 0.8778287807155015
precision_micro: 0.9231489235922952
recall_macro: 0.8263445835289895
recall_micro: 0.9110754570206145

====================================================================================================
RUN 21/30 | SEED 547
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 951.18it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.36      1405     0.8980     0.8998    +0.0018
Animal                                    0.52       184     0.9448     0.9474    +0.0026
Animate                                   0.28        13     0.8182     0.8696    +0.0514
Artefact                                  0.57       503     0.8989     0.9039    +0.0050
Body_Part                                 0.48        74     0.9231     0.9306    +0.0075
Comestible                                0.71       157     0.9554     0.9615    +0.0061
Communication                             0.63       534     0.7914     0.7985    +0.0070
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.79       340     0.8601     0.8619    +0.0019
Elongated                                 0.53       168     0.7951     0.8050    +0.0098
Eventive                                  0.39      1068     0.8867     0.8893    +0.0026
Feminine                                  0.54       204     0.9324     0.9346    +0.0023
Fluid                                     0.54        19     0.8421     0.8649    +0.0228
Garment                                   0.34        17     0.8750     0.9412    +0.0662
Inanimate                                 0.64      1511     0.9322     0.9356    +0.0034
Internal_Control                          0.24        21     0.3704     0.5714    +0.2011
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.44      1209     0.9212     0.9233    +0.0022
Machine                                   0.49       180     0.8960     0.8991    +0.0032
Masculine                                 0.21       671     0.9282     0.9307    +0.0025
Natural                                   0.64        79     0.8645     0.8874    +0.0229
Natural_Force                             0.50        35     0.8696     0.8696    +0.0000
Non_Rigid                                 0.46       335     0.8052     0.8081    +0.0028
Organisation                              0.56      1086     0.9025     0.9047    +0.0022
Plant                                     0.48        15     0.8966     0.9333    +0.0368
Point_in_Time                             0.66       336     0.8743     0.8792    +0.0049
Pointy                                    0.35        20     0.4000     0.7027    +0.3027
Question                                  0.12        33     0.8387     0.8955    +0.0568
Rigid                                     0.25       603     0.8736     0.8787    +0.0051
Solid                                     0.54      1409     0.8938     0.8946    +0.0008
Sound                                     0.72        42     0.8293     0.8462    +0.0169
Statement                                 0.44       264     0.7563     0.7721    +0.0158
Substance                                 0.39       217     0.8796     0.8964    +0.0168
Time                                      0.09        16     0.3810     0.4878    +0.1069
Unspecified_Gender_or_Neuter              0.57       677     0.8847     0.8892    +0.0045
Vehicle                                   0.50       100     0.9749     0.9749    +0.0000
Web_Location                              0.74        55     0.8772     0.8991    +0.0219

VALIDATION @ 0.5
direct_f1_macro: 0.8451534802336915
direct_f1_micro: 0.8908897137187167
direct_precision_macro: 0.8873144861018208
direct_precision_micro: 0.8938131406238478
direct_recall_macro: 0.8247962201064626
direct_recall_micro: 0.887985347985348
f1_macro: 0.8946793738312834
f1_micro: 0.9382354832486657
precision_macro: 0.908811157073697
precision_micro: 0.9434529582929195
recall_macro: 0.8839124956629062
recall_micro: 0.9330753980942637

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8726404375794683
direct_f1_micro: 0.8951125755079626
direct_precision_macro: 0.8856431614507987
direct_precision_micro: 0.8946212952799122
direct_recall_macro: 0.864249692228191
direct_recall_micro: 0.8956043956043956
f1_macro: 0.911081653671615
f1_micro: 0.9410763872168986
precision_macro: 0.919028011456481
precision_micro: 0.9448222515873271
recall_macro: 0.9041232670754542
recall_micro: 0.937360107437488

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7731013860907925
direct_f1_micro: 0.8607594936708861
direct_precision_macro: 0.7989455231286228
direct_precision_micro: 0.8623748862602366
direct_recall_macro: 0.7623313600106608
direct_recall_micro: 0.8591501416430595
f1_macro: 0.8516319503743092
f1_micro: 0.9154180291863927
precision_macro: 0.8653550148784083
precision_micro: 0.9189612934835865
recall_macro: 0.8422833707452915
recall_micro: 0.911901983663944

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7771711984516353
direct_f1_micro: 0.858908225157304
direct_precision_macro: 0.7918381776534024
direct_precision_micro: 0.8593466424682396
direct_recall_macro: 0.7739590148013039
direct_recall_micro: 0.8584702549575071
f1_macro: 0.8511547450927395
f1_micro: 0.9143708479874951
precision_macro: 0.865838382838439
precision_micro: 0.9186788378484492
recall_macro: 0.8426258134560363
recall_micro: 0.9101030727343447

====================================================================================================
RUN 22/30 | SEED 593
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 948.31it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.29      1405     0.8897     0.8945    +0.0048
Animal                                    0.28       184     0.9471     0.9534    +0.0063
Animate                                   0.33        13     0.8333     0.8800    +0.0467
Artefact                                  0.65       503     0.8989     0.9022    +0.0033
Body_Part                                 0.21        74     0.8966     0.9342    +0.0377
Comestible                                0.50       157     0.9615     0.9615    +0.0000
Communication                             0.49       534     0.8196     0.8214    +0.0018
Currency                                  0.50        45     0.9890     0.9890    +0.0000
Duration                                  0.61       340     0.8518     0.8563    +0.0045
Elongated                                 0.58       168     0.7937     0.8063    +0.0126
Eventive                                  0.65      1068     0.8877     0.8918    +0.0042
Feminine                                  0.31       204     0.9584     0.9588    +0.0004
Fluid                                     0.50        19     0.8947     0.8947    +0.0000
Garment                                   0.54        17     0.9412     0.9697    +0.0285
Inanimate                                 0.40      1511     0.9363     0.9380    +0.0017
Internal_Control                          0.17        21     0.5517     0.6250    +0.0733
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.68      1209     0.9217     0.9235    +0.0018
Machine                                   0.63       180     0.8997     0.9017    +0.0020
Masculine                                 0.30       671     0.9331     0.9339    +0.0008
Natural                                   0.50        79     0.8861     0.8861    +0.0000
Natural_Force                             0.58        35     0.8611     0.8732    +0.0121
Non_Rigid                                 0.62       335     0.7893     0.7951    +0.0058
Organisation                              0.31      1086     0.8844     0.8880    +0.0036
Plant                                     0.50        15     0.8966     0.8966    +0.0000
Point_in_Time                             0.41       336     0.8667     0.8756    +0.0089
Pointy                                    0.32        20     0.8108     0.8500    +0.0392
Question                                  0.23        33     0.8254     0.8788    +0.0534
Rigid                                     0.27       603     0.8755     0.8791    +0.0036
Solid                                     0.51      1409     0.8965     0.8970    +0.0006
Sound                                     0.60        42     0.7952     0.8354    +0.0403
Statement                                 0.42       264     0.7686     0.7753    +0.0066
Substance                                 0.50       217     0.8935     0.8935    +0.0000
Time                                      0.10        16     0.3000     0.4878    +0.1878
Unspecified_Gender_or_Neuter              0.71       677     0.8886     0.8947    +0.0061
Vehicle                                   0.50       100     0.9600     0.9600    +0.0000
Web_Location                              0.91        55     0.8571     0.9038    +0.0467

VALIDATION @ 0.5
direct_f1_macro: 0.8611125309054729
direct_f1_micro: 0.8916096771821458
direct_precision_macro: 0.8944615254290997
direct_precision_micro: 0.8949660466489519
direct_recall_macro: 0.8455235961345494
direct_recall_micro: 0.8882783882783882
f1_macro: 0.9056114922784735
f1_micro: 0.9376909962363689
precision_macro: 0.9138516623565448
precision_micro: 0.9433656957928802
recall_macro: 0.898162254648814
recall_micro: 0.9320841593656072

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8785456595019139
direct_f1_micro: 0.895429388263754
direct_precision_macro: 0.891661383995876
direct_precision_micro: 0.8959876769603169
direct_recall_macro: 0.8714316759702343
direct_recall_micro: 0.8948717948717949
f1_macro: 0.9142662593630846
f1_micro: 0.9400474998395276
precision_macro: 0.9219639674258897
precision_micro: 0.943560337607113
recall_macro: 0.9074004963810862
recall_micro: 0.9365607213659909

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7905942243928894
direct_f1_micro: 0.8624488868696047
direct_precision_macro: 0.8184993534626626
direct_precision_micro: 0.8645109871342366
direct_recall_macro: 0.7802000483666299
direct_recall_micro: 0.8603966005665722
f1_macro: 0.8601110274823979
f1_micro: 0.9180119672731714
precision_macro: 0.8696326962084081
precision_micro: 0.922314374049173
recall_macro: 0.8545988032694833
recall_micro: 0.9137495138078569

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8075151406880081
direct_f1_micro: 0.8610953622859735
direct_precision_macro: 0.8385644049200685
direct_precision_micro: 0.8616816067173494
direct_recall_macro: 0.799466658049244
direct_recall_micro: 0.8605099150141643
f1_macro: 0.8623302305126037
f1_micro: 0.9172983644916762
precision_macro: 0.8737904313894979
precision_micro: 0.9197419228701305
recall_macro: 0.8562019101270304
recall_micro: 0.9148677557370672

====================================================================================================
RUN 23/30 | SEED 641
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 987.57it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.38      1405     0.8946     0.8961    +0.0015
Animal                                    0.88       184     0.9392     0.9441    +0.0049
Animate                                   0.61        13     0.8000     0.8696    +0.0696
Artefact                                  0.36       503     0.8958     0.9037    +0.0079
Body_Part                                 0.48        74     0.9306     0.9379    +0.0074
Comestible                                0.20       157     0.9542     0.9557    +0.0014
Communication                             0.41       534     0.8004     0.8124    +0.0121
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.52       340     0.8465     0.8514    +0.0049
Elongated                                 0.46       168     0.7799     0.7802    +0.0003
Eventive                                  0.58      1068     0.8883     0.8915    +0.0032
Feminine                                  0.84       204     0.9429     0.9515    +0.0086
Fluid                                     0.59        19     0.8947     0.9189    +0.0242
Garment                                   0.50        17     0.9697     0.9697    +0.0000
Inanimate                                 0.41      1511     0.9346     0.9360    +0.0013
Internal_Control                          0.18        21     0.3846     0.5882    +0.2036
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.62      1209     0.9184     0.9247    +0.0063
Machine                                   0.67       180     0.8991     0.9038    +0.0047
Masculine                                 0.50       671     0.9366     0.9366    +0.0000
Natural                                   0.70        79     0.8696     0.8846    +0.0151
Natural_Force                             0.74        35     0.8571     0.8824    +0.0252
Non_Rigid                                 0.33       335     0.7834     0.7971    +0.0138
Organisation                              0.35      1086     0.8981     0.9003    +0.0022
Plant                                     0.50        15     0.9032     0.9032    +0.0000
Point_in_Time                             0.70       336     0.8609     0.8677    +0.0067
Pointy                                    0.34        20     0.7222     0.7619    +0.0397
Question                                  0.27        33     0.8197     0.8438    +0.0241
Rigid                                     0.60       603     0.8794     0.8810    +0.0016
Solid                                     0.54      1409     0.8928     0.8939    +0.0010
Sound                                     0.55        42     0.8000     0.8205    +0.0205
Statement                                 0.61       264     0.7675     0.7774    +0.0098
Substance                                 0.38       217     0.8793     0.8884    +0.0091
Time                                      0.50        16     0.5714     0.5714    +0.0000
Unspecified_Gender_or_Neuter              0.33       677     0.8913     0.8928    +0.0014
Vehicle                                   0.41       100     0.9592     0.9596    +0.0004
Web_Location                              0.75        55     0.8704     0.8911    +0.0207

VALIDATION @ 0.5
direct_f1_macro: 0.8604230748135233
direct_f1_micro: 0.8907439953134153
direct_precision_macro: 0.8851400613977103
direct_precision_micro: 0.8903528033962816
direct_recall_macro: 0.8502486568014248
direct_recall_micro: 0.8911355311355311
f1_macro: 0.9038754875898822
f1_micro: 0.9375752806462492
precision_macro: 0.9136378141752127
precision_micro: 0.9418255735166006
recall_macro: 0.8955853482591406
recall_micro: 0.9333631770800026

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8753756854410008
direct_f1_micro: 0.8948233660906733
direct_precision_macro: 0.8896681540738935
direct_precision_micro: 0.892443343292283
direct_recall_macro: 0.8655094186294473
direct_recall_micro: 0.8972161172161173
f1_macro: 0.9107418819049524
f1_micro: 0.9402112077944971
precision_macro: 0.9187670855389414
precision_micro: 0.9424009765813229
recall_macro: 0.9041070448411975
recall_micro: 0.9380315917375456

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7734309731548276
direct_f1_micro: 0.8606835672249887
direct_precision_macro: 0.8003978901011692
direct_precision_micro: 0.8596134282807731
direct_recall_macro: 0.7743421193439115
direct_recall_micro: 0.861756373937677
f1_macro: 0.8546917367574712
f1_micro: 0.9172423859102851
precision_macro: 0.8603398539544985
precision_micro: 0.9178675754625122
recall_macro: 0.852572471143611
recall_micro: 0.9166180474523532

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.777254761569834
direct_f1_micro: 0.8588334742180896
direct_precision_macro: 0.7918768328089241
direct_precision_micro: 0.8542600896860987
direct_recall_macro: 0.7762054433665478
direct_recall_micro: 0.863456090651558
f1_macro: 0.8545810761147894
f1_micro: 0.9171010838202847
precision_macro: 0.8628431513762441
precision_micro: 0.9147279322853687
recall_macro: 0.8517851698968116
recall_micro: 0.9194865810968494

====================================================================================================
RUN 24/30 | SEED 691
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 891.20it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.55      1405     0.8962     0.8974    +0.0012
Animal                                    0.73       184     0.9479     0.9503    +0.0023
Animate                                   0.35        13     0.8182     0.8333    +0.0152
Artefact                                  0.50       503     0.9038     0.9038    +0.0000
Body_Part                                 0.35        74     0.9396     0.9467    +0.0071
Comestible                                0.61       157     0.9427     0.9548    +0.0122
Communication                             0.52       534     0.8127     0.8179    +0.0052
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.73       340     0.8413     0.8523    +0.0110
Elongated                                 0.72       168     0.7638     0.8013    +0.0375
Eventive                                  0.39      1068     0.8831     0.8846    +0.0015
Feminine                                  0.62       204     0.9227     0.9294    +0.0067
Fluid                                     0.08        19     0.8649     0.9048    +0.0399
Garment                                   0.50        17     0.9697     0.9697    +0.0000
Inanimate                                 0.43      1511     0.9346     0.9381    +0.0035
Internal_Control                          0.39        21     0.4444     0.5517    +0.1073
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.48      1209     0.9173     0.9183    +0.0010
Machine                                   0.66       180     0.8940     0.8994    +0.0054
Masculine                                 0.34       671     0.9274     0.9326    +0.0053
Natural                                   0.46        79     0.9045     0.9114    +0.0069
Natural_Force                             0.50        35     0.9143     0.9143    +0.0000
Non_Rigid                                 0.45       335     0.7889     0.7942    +0.0053
Organisation                              0.43      1086     0.8996     0.9004    +0.0008
Plant                                     0.32        15     0.8966     0.9032    +0.0067
Point_in_Time                             0.88       336     0.8696     0.8740    +0.0045
Pointy                                    0.50        20     0.8421     0.8421    +0.0000
Question                                  0.48        33     0.8710     0.8889    +0.0179
Rigid                                     0.47       603     0.8718     0.8750    +0.0032
Solid                                     0.47      1409     0.8912     0.8930    +0.0019
Sound                                     0.54        42     0.8293     0.8395    +0.0102
Statement                                 0.30       264     0.7667     0.7733    +0.0067
Substance                                 0.22       217     0.8884     0.8923    +0.0039
Time                                      0.22        16     0.4000     0.6452    +0.2452
Unspecified_Gender_or_Neuter              0.41       677     0.8836     0.8868    +0.0031
Vehicle                                   0.88       100     0.9442     0.9534    +0.0092
Web_Location                              0.92        55     0.8421     0.8952    +0.0531

VALIDATION @ 0.5
direct_f1_macro: 0.8629169197189653
direct_f1_micro: 0.8902133922001472
direct_precision_macro: 0.9064484941147762
direct_precision_micro: 0.8941611234294161
direct_recall_macro: 0.8449905517324716
direct_recall_micro: 0.8863003663003663
f1_macro: 0.9065864602532724
f1_micro: 0.935545710833669
precision_macro: 0.9159528063834106
precision_micro: 0.9427291321710334
recall_macro: 0.8983604952782617
recall_micro: 0.9284709343224403

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8802362714246073
direct_f1_micro: 0.8941470404526582
direct_precision_macro: 0.9029968536903095
direct_precision_micro: 0.8968821404879487
direct_recall_macro: 0.8674101522797659
direct_recall_micro: 0.8914285714285715
f1_macro: 0.9132550315182519
f1_micro: 0.9377434411717367
precision_macro: 0.9237517715775186
precision_micro: 0.9440951516722842
recall_macro: 0.9048006589658041
recall_micro: 0.9314766259512695

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7817768155375338
direct_f1_micro: 0.8652643547470154
direct_precision_macro: 0.830717328121908
direct_precision_micro: 0.8682258984597833
direct_recall_macro: 0.7624533721304676
direct_recall_micro: 0.8623229461756374
f1_macro: 0.8556608490759882
f1_micro: 0.9192094398162851
precision_macro: 0.8790998611279756
precision_micro: 0.9237908175791799
recall_macro: 0.8424734039061724
recall_micro: 0.9146732788798133

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7795596018407807
direct_f1_micro: 0.8631543129359723
direct_precision_macro: 0.8256654234097067
direct_precision_micro: 0.8639872842870118
direct_recall_macro: 0.7632375176552163
direct_recall_micro: 0.8623229461756374
f1_macro: 0.8503726071875999
f1_micro: 0.916605705925384
precision_macro: 0.8810868010199453
precision_micro: 0.9194305840915762
recall_macro: 0.8327581360640668
recall_micro: 0.9137981330221704

====================================================================================================
RUN 25/30 | SEED 743
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 949.29it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.76      1405     0.8954     0.9001    +0.0047
Animal                                    0.58       184     0.9587     0.9613    +0.0026
Animate                                   0.39        13     0.8333     0.8800    +0.0467
Artefact                                  0.56       503     0.9106     0.9130    +0.0024
Body_Part                                 0.61        74     0.9241     0.9371    +0.0129
Comestible                                0.48       157     0.9615     0.9682    +0.0066
Communication                             0.38       534     0.8053     0.8142    +0.0089
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.31       340     0.8441     0.8486    +0.0045
Elongated                                 0.65       168     0.7834     0.8078    +0.0244
Eventive                                  0.70      1068     0.8873     0.8909    +0.0036
Feminine                                  0.40       204     0.9438     0.9463    +0.0026
Fluid                                     0.18        19     0.8947     0.9268    +0.0321
Garment                                   0.40        17     0.9697     1.0000    +0.0303
Inanimate                                 0.43      1511     0.9386     0.9389    +0.0002
Internal_Control                          0.15        21     0.5517     0.6061    +0.0543
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.55      1209     0.9258     0.9263    +0.0005
Machine                                   0.70       180     0.8818     0.8889    +0.0070
Masculine                                 0.44       671     0.9339     0.9356    +0.0017
Natural                                   0.75        79     0.8846     0.9067    +0.0221
Natural_Force                             0.54        35     0.8696     0.8824    +0.0128
Non_Rigid                                 0.54       335     0.7982     0.8006    +0.0024
Organisation                              0.50      1086     0.8971     0.8971    +0.0000
Plant                                     0.41        15     0.8571     0.8966    +0.0394
Point_in_Time                             0.87       336     0.8674     0.8705    +0.0032
Pointy                                    0.57        20     0.8205     0.8421    +0.0216
Question                                  0.11        33     0.8000     0.8657    +0.0657
Rigid                                     0.43       603     0.8792     0.8833    +0.0041
Solid                                     0.48      1409     0.8919     0.8921    +0.0002
Sound                                     0.58        42     0.8642     0.8974    +0.0332
Statement                                 0.55       264     0.7543     0.7665    +0.0123
Substance                                 0.19       217     0.8776     0.8913    +0.0137
Time                                      0.15        16     0.4800     0.5128    +0.0328
Unspecified_Gender_or_Neuter              0.53       677     0.8855     0.8873    +0.0018
Vehicle                                   0.50       100     0.9641     0.9641    +0.0000
Web_Location                              0.65        55     0.8649     0.8889    +0.0240

VALIDATION @ 0.5
direct_f1_macro: 0.8675690786001929
direct_f1_micro: 0.8927126994631959
direct_precision_macro: 0.897161617987005
direct_precision_micro: 0.8960732211396516
direct_recall_macro: 0.849025609202945
direct_recall_micro: 0.8893772893772893
f1_macro: 0.9075208428259524
f1_micro: 0.9386408267070148
precision_macro: 0.9191554629935705
precision_micro: 0.9450602878257487
recall_macro: 0.8968883784232702
recall_micro: 0.9323079874656264

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8820362069060547
direct_f1_micro: 0.8962716869693614
direct_precision_macro: 0.8985734207550469
direct_precision_micro: 0.9032738095238095
direct_recall_macro: 0.8711647726838329
direct_recall_micro: 0.8893772893772893
f1_macro: 0.9167249261995126
f1_micro: 0.9392668129598555
precision_macro: 0.928224835982671
precision_micro: 0.948016415868673
recall_macro: 0.9069848262429162
recall_micro: 0.9306772398797724

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7887230960635432
direct_f1_micro: 0.8638331814038286
direct_precision_macro: 0.8371685020523538
direct_precision_micro: 0.8686833963561361
direct_recall_macro: 0.764943834369042
direct_recall_micro: 0.8590368271954674
f1_macro: 0.8576346548386522
f1_micro: 0.9163766482035194
precision_macro: 0.8873657244866615
precision_micro: 0.92393990313334
recall_macro: 0.8386936029905749
recall_micro: 0.9089362115908207

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7811528295189067
direct_f1_micro: 0.8627944203064258
direct_precision_macro: 0.8053664083192256
direct_precision_micro: 0.870658820814584
direct_recall_macro: 0.7725176936462363
direct_recall_micro: 0.855070821529745
f1_macro: 0.852879632865207
f1_micro: 0.9154299754299754
precision_macro: 0.8725296940674969
precision_micro: 0.9253427379296643
recall_macro: 0.840176716526588
recall_micro: 0.9057273434461299

====================================================================================================
RUN 26/30 | SEED 797
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1004.00it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.75      1405     0.8962     0.9019    +0.0057
Animal                                    0.86       184     0.9366     0.9412    +0.0045
Animate                                   0.50        13     0.8696     0.8696    +0.0000
Artefact                                  0.37       503     0.9012     0.9037    +0.0025
Body_Part                                 0.41        74     0.9452     0.9524    +0.0072
Comestible                                0.50       157     0.9682     0.9682    +0.0000
Communication                             0.56       534     0.8053     0.8061    +0.0008
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.53       340     0.8567     0.8592    +0.0025
Elongated                                 0.50       168     0.8012     0.8012    +0.0000
Eventive                                  0.49      1068     0.8836     0.8852    +0.0016
Feminine                                  0.44       204     0.9455     0.9458    +0.0003
Fluid                                     0.22        19     0.8649     0.9231    +0.0582
Garment                                   0.73        17     0.9143     0.9697    +0.0554
Inanimate                                 0.27      1511     0.9339     0.9376    +0.0036
Internal_Control                          0.07        21     0.3846     0.5106    +0.1260
Language                                  0.55         5     0.9091     1.0000    +0.0909
Location                                  0.39      1209     0.9220     0.9235    +0.0015
Machine                                   0.80       180     0.8833     0.8949    +0.0116
Masculine                                 0.50       671     0.9332     0.9332    +0.0000
Natural                                   0.63        79     0.8805     0.8917    +0.0112
Natural_Force                             0.55        35     0.8611     0.8857    +0.0246
Non_Rigid                                 0.56       335     0.8012     0.8065    +0.0054
Organisation                              0.47      1086     0.8945     0.8961    +0.0016
Plant                                     0.50        15     0.9333     0.9333    +0.0000
Point_in_Time                             0.41       336     0.8763     0.8837    +0.0073
Pointy                                    0.33        20     0.5789     0.6957    +0.1167
Question                                  0.16        33     0.8136     0.8788    +0.0652
Rigid                                     0.32       603     0.8799     0.8858    +0.0059
Solid                                     0.63      1409     0.8867     0.8880    +0.0013
Sound                                     0.50        42     0.8395     0.8395    +0.0000
Statement                                 0.33       264     0.7538     0.7604    +0.0065
Substance                                 0.21       217     0.8767     0.8898    +0.0131
Time                                      0.50        16     0.4762     0.4762    +0.0000
Unspecified_Gender_or_Neuter              0.57       677     0.8858     0.8917    +0.0059
Vehicle                                   0.55       100     0.9604     0.9652    +0.0048
Web_Location                              0.76        55     0.8571     0.9057    +0.0485

VALIDATION @ 0.5
direct_f1_macro: 0.85433614989062
direct_f1_micro: 0.890856324161493
direct_precision_macro: 0.89221463408441
direct_precision_micro: 0.8934492668189522
direct_recall_macro: 0.8411657479641451
direct_recall_micro: 0.8882783882783882
f1_macro: 0.8984316831974102
f1_micro: 0.9374809295154892
precision_macro: 0.9032934483235662
precision_micro: 0.9417002742377802
recall_macro: 0.895008410137097
recall_micro: 0.9332992261942827

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8729956950237752
direct_f1_micro: 0.8945881489634929
direct_precision_macro: 0.8913531818016507
direct_precision_micro: 0.8960676221977214
direct_recall_macro: 0.8672006484335153
direct_recall_micro: 0.8931135531135531
f1_macro: 0.9125197687494246
f1_micro: 0.9388632971124986
precision_macro: 0.9144623872143628
precision_micro: 0.9425698540075413
recall_macro: 0.9119986939818255
recall_micro: 0.9351857773230159

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7754486802915956
direct_f1_micro: 0.8621687567383532
direct_precision_macro: 0.8054689091482393
direct_precision_micro: 0.8634917026596954
direct_recall_macro: 0.7629244025686643
direct_recall_micro: 0.8608498583569405
f1_macro: 0.8557802092355198
f1_micro: 0.9161058334750601
precision_macro: 0.8722586373691809
precision_micro: 0.915594191637123
recall_macro: 0.8462600531554016
recall_micro: 0.9166180474523532

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7817947167265902
direct_f1_micro: 0.8613990370999717
direct_precision_macro: 0.8038893798306379
direct_precision_micro: 0.8611551528878822
direct_recall_macro: 0.7707146837710729
direct_recall_micro: 0.861643059490085
f1_macro: 0.8538625884086074
f1_micro: 0.9147550544323484
precision_macro: 0.8680492631311785
precision_micro: 0.9143995336183444
recall_macro: 0.847299507462437
recall_micro: 0.9151108518086347

====================================================================================================
RUN 27/30 | SEED 853
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 959.12it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.72      1405     0.8952     0.8996    +0.0044
Animal                                    0.50       184     0.9532     0.9532    +0.0000
Animate                                   0.40        13     0.8696     0.8800    +0.0104
Artefact                                  0.34       503     0.8996     0.9086    +0.0090
Body_Part                                 0.13        74     0.8966     0.9079    +0.0113
Comestible                                0.39       157     0.9457     0.9494    +0.0037
Communication                             0.48       534     0.8023     0.8049    +0.0026
Currency                                  0.31        45     0.9888     1.0000    +0.0112
Duration                                  0.61       340     0.8496     0.8559    +0.0063
Elongated                                 0.59       168     0.7853     0.7950    +0.0097
Eventive                                  0.59      1068     0.8869     0.8912    +0.0043
Feminine                                  0.44       204     0.9386     0.9412    +0.0026
Fluid                                     0.18        19     0.8889     0.9231    +0.0342
Garment                                   0.50        17     0.9697     0.9697    +0.0000
Inanimate                                 0.57      1511     0.9376     0.9396    +0.0021
Internal_Control                          0.36        21     0.5000     0.6000    +0.1000
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.59      1209     0.9241     0.9256    +0.0015
Machine                                   0.44       180     0.8946     0.8958    +0.0012
Masculine                                 0.41       671     0.9368     0.9371    +0.0003
Natural                                   0.78        79     0.8718     0.8980    +0.0262
Natural_Force                             0.61        35     0.8358     0.8615    +0.0257
Non_Rigid                                 0.66       335     0.8012     0.8104    +0.0092
Organisation                              0.23      1086     0.8945     0.8986    +0.0041
Plant                                     0.50        15     0.9333     0.9333    +0.0000
Point_in_Time                             0.30       336     0.8653     0.8725    +0.0072
Pointy                                    0.50        20     0.8000     0.8000    +0.0000
Question                                  0.41        33     0.8571     0.8923    +0.0352
Rigid                                     0.41       603     0.8838     0.8846    +0.0008
Solid                                     0.56      1409     0.8898     0.8913    +0.0015
Sound                                     0.61        42     0.8250     0.8354    +0.0104
Statement                                 0.74       264     0.7380     0.7588    +0.0207
Substance                                 0.27       217     0.8690     0.8860    +0.0170
Time                                      0.16        16     0.3000     0.4865    +0.1865
Unspecified_Gender_or_Neuter              0.36       677     0.8938     0.9010    +0.0072
Vehicle                                   0.51       100     0.9648     0.9697    +0.0049
Web_Location                              0.94        55     0.8727     0.9126    +0.0399

VALIDATION @ 0.5
direct_f1_macro: 0.8610460602588342
direct_f1_micro: 0.8915689230429826
direct_precision_macro: 0.8997097045285356
direct_precision_micro: 0.894958293349081
direct_recall_macro: 0.8420092566132483
direct_recall_micro: 0.8882051282051282
f1_macro: 0.9067744958834444
f1_micro: 0.9384593130715698
precision_macro: 0.9169858620784185
precision_micro: 0.9434480529972532
recall_macro: 0.8972300304170222
recall_micro: 0.9335230542943019

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8775703360038509
direct_f1_micro: 0.8964350097494573
direct_precision_macro: 0.8984194190216659
direct_precision_micro: 0.9003769122755155
direct_recall_macro: 0.8653109080323702
direct_recall_micro: 0.8925274725274726
f1_macro: 0.9139954564191805
f1_micro: 0.9404389719910858
precision_macro: 0.9228537267777188
precision_micro: 0.9430849866555194
recall_macro: 0.90667767625683
recall_micro: 0.9378077636375264

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7772876440789291
direct_f1_micro: 0.8644663717817852
direct_precision_macro: 0.8218845739916093
direct_precision_micro: 0.8652514473833579
direct_recall_macro: 0.7634710465687968
direct_recall_micro: 0.8636827195467423
f1_macro: 0.8569504196221198
f1_micro: 0.919638727268301
precision_macro: 0.8732120323584363
precision_micro: 0.920961529084792
recall_macro: 0.8469058772990402
recall_micro: 0.9183197199533255

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7769096560966476
direct_f1_micro: 0.8635514018691589
direct_precision_macro: 0.8084124725604408
direct_precision_micro: 0.8633069082672706
direct_recall_macro: 0.7694186452939682
direct_recall_micro: 0.8637960339943342
f1_macro: 0.8545349503546472
f1_micro: 0.9180844360428482
precision_macro: 0.8741662505966724
precision_micro: 0.9152894558809317
recall_macro: 0.8453008728434123
recall_micro: 0.9208965383119408

====================================================================================================
RUN 28/30 | SEED 911
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 980.81it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.48      1405     0.8986     0.8991    +0.0005
Animal                                    0.50       184     0.9558     0.9558    +0.0000
Animate                                   0.50        13     0.9167     0.9167    +0.0000
Artefact                                  0.42       503     0.9027     0.9055    +0.0028
Body_Part                                 0.06        74     0.8811     0.9231    +0.0420
Comestible                                0.79       157     0.9527     0.9646    +0.0119
Communication                             0.53       534     0.8059     0.8060    +0.0001
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.56       340     0.8522     0.8584    +0.0062
Elongated                                 0.47       168     0.7890     0.7903    +0.0013
Eventive                                  0.66      1068     0.8860     0.8910    +0.0050
Feminine                                  0.90       204     0.9320     0.9347    +0.0026
Fluid                                     0.26        19     0.8649     0.9231    +0.0582
Garment                                   0.62        17     0.9714     1.0000    +0.0286
Inanimate                                 0.47      1511     0.9373     0.9381    +0.0007
Internal_Control                          0.21        21     0.3846     0.6061    +0.2214
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.42      1209     0.9202     0.9228    +0.0025
Machine                                   0.53       180     0.8895     0.8946    +0.0051
Masculine                                 0.13       671     0.9309     0.9381    +0.0072
Natural                                   0.37        79     0.8861     0.8944    +0.0083
Natural_Force                             0.50        35     0.9167     0.9167    +0.0000
Non_Rigid                                 0.44       335     0.8076     0.8110    +0.0034
Organisation                              0.53      1086     0.8900     0.8917    +0.0017
Plant                                     0.37        15     0.8571     0.8966    +0.0394
Point_in_Time                             0.60       336     0.8692     0.8723    +0.0032
Pointy                                    0.44        20     0.7027     0.7805    +0.0778
Question                                  0.50        33     0.8485     0.8485    +0.0000
Rigid                                     0.28       603     0.8859     0.8902    +0.0043
Solid                                     0.55      1409     0.8938     0.8959    +0.0021
Sound                                     0.76        42     0.7901     0.8219    +0.0318
Statement                                 0.45       264     0.7644     0.7707    +0.0064
Substance                                 0.56       217     0.8853     0.8941    +0.0088
Time                                      0.27        16     0.4000     0.6667    +0.2667
Unspecified_Gender_or_Neuter              0.27       677     0.8851     0.8894    +0.0042
Vehicle                                   0.67       100     0.9548     0.9645    +0.0097
Web_Location                              0.92        55     0.8421     0.9057    +0.0636

VALIDATION @ 0.5
direct_f1_macro: 0.8581312487165125
direct_f1_micro: 0.8919236417033773
direct_precision_macro: 0.8986658728495863
direct_precision_micro: 0.8938925680647535
direct_recall_macro: 0.843794118893769
direct_recall_micro: 0.88996336996337
f1_macro: 0.902253138879031
f1_micro: 0.9372398386396875
precision_macro: 0.9094055373715545
precision_micro: 0.9421914886741849
recall_macro: 0.8960823918707386
recall_micro: 0.9323399629084863

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8831961365288574
direct_f1_micro: 0.895915002747756
direct_precision_macro: 0.895630006966628
direct_precision_micro: 0.8960791498717479
direct_recall_macro: 0.8754997493953093
direct_recall_micro: 0.8957509157509157
f1_macro: 0.9137262063127344
f1_micro: 0.9399858865794201
precision_macro: 0.9197262291520898
precision_micro: 0.9429499967822897
recall_macro: 0.9093530182215063
recall_micro: 0.9370403530088892

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7678006392498397
direct_f1_micro: 0.8615506777834496
direct_precision_macro: 0.7778158954346492
direct_precision_micro: 0.8624801271860095
direct_recall_macro: 0.7658807834920737
direct_recall_micro: 0.8606232294617564
f1_macro: 0.8519519241082133
f1_micro: 0.9162136466687794
precision_macro: 0.8613479407252853
precision_micro: 0.9187894196450398
recall_macro: 0.8497892076122957
recall_micro: 0.9136522753792299

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7744833344582486
direct_f1_micro: 0.8601980198019802
direct_precision_macro: 0.7924805391929614
direct_precision_micro: 0.8589830508474576
direct_recall_macro: 0.7738606405521065
direct_recall_micro: 0.8614164305949008
f1_macro: 0.849616995473773
f1_micro: 0.9152410575427683
precision_macro: 0.8624950394371623
precision_micro: 0.9148853478429848
recall_macro: 0.8459841526209232
recall_micro: 0.9155970439517698

====================================================================================================
RUN 29/30 | SEED 971
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 917.39it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.50      1405     0.8996     0.8996    +0.0000
Animal                                    0.40       184     0.9474     0.9477    +0.0003
Animate                                   0.34        13     0.8696     0.9167    +0.0471
Artefact                                  0.72       503     0.9041     0.9097    +0.0055
Body_Part                                 0.53        74     0.9324     0.9452    +0.0128
Comestible                                0.46       157     0.9585     0.9618    +0.0033
Communication                             0.40       534     0.8081     0.8122    +0.0041
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.38       340     0.8592     0.8613    +0.0020
Elongated                                 0.60       168     0.7900     0.7950    +0.0050
Eventive                                  0.54      1068     0.8851     0.8874    +0.0023
Feminine                                  0.50       204     0.9484     0.9484    +0.0000
Fluid                                     0.30        19     0.8947     0.9231    +0.0283
Garment                                   0.24        17     0.9375     1.0000    +0.0625
Inanimate                                 0.41      1511     0.9379     0.9405    +0.0026
Internal_Control                          0.11        21     0.3704     0.5641    +0.1937
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.43      1209     0.9157     0.9175    +0.0017
Machine                                   0.32       180     0.8908     0.8950    +0.0042
Masculine                                 0.65       671     0.9357     0.9374    +0.0017
Natural                                   0.55        79     0.8608     0.8701    +0.0094
Natural_Force                             0.47        35     0.8406     0.8571    +0.0166
Non_Rigid                                 0.47       335     0.7982     0.8023    +0.0041
Organisation                              0.46      1086     0.8988     0.8994    +0.0007
Plant                                     0.50        15     0.8966     0.8966    +0.0000
Point_in_Time                             0.70       336     0.8640     0.8717    +0.0077
Pointy                                    0.66        20     0.8000     0.8205    +0.0205
Question                                  0.19        33     0.8571     0.8615    +0.0044
Rigid                                     0.40       603     0.8855     0.8911    +0.0056
Solid                                     0.46      1409     0.8944     0.8966    +0.0022
Sound                                     0.50        42     0.8354     0.8354    +0.0000
Statement                                 0.54       264     0.7680     0.7738    +0.0058
Substance                                 0.45       217     0.8904     0.8984    +0.0080
Time                                      0.25        16     0.3810     0.6061    +0.2251
Unspecified_Gender_or_Neuter              0.59       677     0.8958     0.9003    +0.0044
Vehicle                                   0.58       100     0.9592     0.9641    +0.0049
Web_Location                              0.92        55     0.8649     0.9038    +0.0390

VALIDATION @ 0.5
direct_f1_macro: 0.8615063997684784
direct_f1_micro: 0.8937497706169486
direct_precision_macro: 0.897793048538842
direct_precision_micro: 0.89549165257042
direct_recall_macro: 0.8436491363853876
direct_recall_micro: 0.892014652014652
f1_macro: 0.9086246586142349
f1_micro: 0.9393637532133676
precision_macro: 0.9191895643090439
precision_micro: 0.94403539365756
recall_macro: 0.8989017904275437
recall_micro: 0.9347381211229776

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8813930966711628
direct_f1_micro: 0.8969230769230769
direct_precision_macro: 0.8927444458887098
direct_precision_micro: 0.8969230769230769
direct_recall_macro: 0.8717582401103635
direct_recall_micro: 0.8969230769230769
f1_macro: 0.9153058897109299
f1_micro: 0.940904270702786
precision_macro: 0.9251597935268007
precision_micro: 0.9456142617232915
recall_macro: 0.9064232582372691
recall_micro: 0.9362409669373921

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7819406501163559
direct_f1_micro: 0.865407520843968
direct_precision_macro: 0.8177276620943066
direct_precision_micro: 0.8663411310470134
direct_recall_macro: 0.7671059876167511
direct_recall_micro: 0.8644759206798867
f1_macro: 0.8551713742253025
f1_micro: 0.9187225743539736
precision_macro: 0.87135120857051
precision_micro: 0.9213279874828868
recall_macro: 0.844117372216991
recall_micro: 0.9161318553092183

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8001702939389782
direct_f1_micro: 0.8635823093040376
direct_precision_macro: 0.8264341525552478
direct_precision_micro: 0.8631424043468418
direct_recall_macro: 0.7901697102994928
direct_recall_micro: 0.8640226628895185
f1_macro: 0.8534493249650104
f1_micro: 0.9174692185785688
precision_macro: 0.8686021466148441
precision_micro: 0.9201838900572211
recall_macro: 0.8449182477348212
recall_micro: 0.9147705173084403

====================================================================================================
RUN 30/30 | SEED 1031
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1020.39it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.64      1405     0.8939     0.8963    +0.0024
Animal                                    0.29       184     0.9448     0.9505    +0.0058
Animate                                   0.38        13     0.8696     0.8800    +0.0104
Artefact                                  0.55       503     0.9178     0.9215    +0.0037
Body_Part                                 0.14        74     0.9262     0.9351    +0.0089
Comestible                                0.50       157     0.9557     0.9557    +0.0000
Communication                             0.58       534     0.8147     0.8207    +0.0060
Currency                                  0.74        45     0.9783     1.0000    +0.0217
Duration                                  0.71       340     0.8488     0.8545    +0.0057
Elongated                                 0.54       168     0.7791     0.7888    +0.0097
Eventive                                  0.43      1068     0.8858     0.8880    +0.0022
Feminine                                  0.08       204     0.9163     0.9260    +0.0098
Fluid                                     0.59        19     0.9231     0.9474    +0.0243
Garment                                   0.49        17     0.9412     0.9714    +0.0303
Inanimate                                 0.43      1511     0.9406     0.9418    +0.0013
Internal_Control                          0.06        21     0.3846     0.6512    +0.2665
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.50      1209     0.9198     0.9198    +0.0000
Machine                                   0.71       180     0.8852     0.8870    +0.0019
Masculine                                 0.54       671     0.9335     0.9341    +0.0006
Natural                                   0.28        79     0.8662     0.8848    +0.0186
Natural_Force                             0.55        35     0.8571     0.8824    +0.0252
Non_Rigid                                 0.49       335     0.8052     0.8087    +0.0035
Organisation                              0.40      1086     0.8917     0.8955    +0.0038
Plant                                     0.53        15     0.8667     0.8966    +0.0299
Point_in_Time                             0.33       336     0.8703     0.8741    +0.0038
Pointy                                    0.50        20     0.8205     0.8205    +0.0000
Question                                  0.50        33     0.8438     0.8438    +0.0000
Rigid                                     0.47       603     0.8827     0.8839    +0.0011
Solid                                     0.61      1409     0.8903     0.8920    +0.0017
Sound                                     0.43        42     0.7529     0.7955    +0.0425
Statement                                 0.43       264     0.7692     0.7737    +0.0045
Substance                                 0.39       217     0.8914     0.8993    +0.0079
Time                                      0.19        16     0.2000     0.5405    +0.3405
Unspecified_Gender_or_Neuter              0.31       677     0.8841     0.8878    +0.0036
Vehicle                                   0.38       100     0.9495     0.9548    +0.0053
Web_Location                              0.87        55     0.8649     0.9038    +0.0390

VALIDATION @ 0.5
direct_f1_macro: 0.8531209056237546
direct_f1_micro: 0.8918165137614679
direct_precision_macro: 0.8829658973502911
direct_precision_micro: 0.8934558823529412
direct_recall_macro: 0.8432049448589106
direct_recall_micro: 0.8901831501831502
f1_macro: 0.9041789892657511
f1_micro: 0.9376274997992129
precision_macro: 0.9073157435653086
precision_micro: 0.9420612633549595
recall_macro: 0.9014268715405714
recall_micro: 0.933235275308563

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8785786062491778
direct_f1_micro: 0.8952917917551438
direct_precision_macro: 0.8790746668194805
direct_precision_micro: 0.8948331381733021
direct_recall_macro: 0.8797653533767547
direct_recall_micro: 0.8957509157509157
f1_macro: 0.9123495039551687
f1_micro: 0.9400486524550284
precision_macro: 0.9149855102958401
precision_micro: 0.9410124959948735
recall_macro: 0.9106297389555027
recall_micro: 0.9390867813519217

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7818946881242113
direct_f1_micro: 0.8616030881017257
direct_precision_macro: 0.8052136441312748
direct_precision_micro: 0.8632692526447503
direct_recall_macro: 0.7716057971203792
direct_recall_micro: 0.859943342776204
f1_macro: 0.8604670067296107
f1_micro: 0.917260220509318
precision_macro: 0.8735361670580911
precision_micro: 0.9204033679263756
recall_macro: 0.8509011968739413
recall_micro: 0.9141384675223648

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7862741408496535
direct_f1_micro: 0.8601858146385679
direct_precision_macro: 0.7929065044531706
direct_precision_micro: 0.8600883652430045
direct_recall_macro: 0.7866523849937622
direct_recall_micro: 0.8602832861189802
f1_macro: 0.8603603170999846
f1_micro: 0.9167294374924068
precision_macro: 0.8696026526805029
precision_micro: 0.916306406955846
recall_macro: 0.8553639242906623
recall_micro: 0.9171528588098017

====================================================================================================
REPEATED-RUN TEST SUMMARY
====================================================================================================
Metric                          Mean         SD        Min        Max
----------------------------------------------------------------------
precision_micro               0.9175     0.0038     0.9040     0.9253
recall_micro                  0.9146     0.0041     0.9055     0.9211
f1_micro                      0.9160     0.0024     0.9066     0.9188
precision_macro               0.8715     0.0083     0.8486     0.8938
recall_macro                  0.8432     0.0099     0.8166     0.8597
f1_macro                      0.8521     0.0063     0.8394     0.8623

======================================================================================================================
REPEATED-RUN TEST PERFORMANCE BY COMPLETE FEATURE (AFTER INHERITANCE)
======================================================================================================================
Feature                               P mean     P SD   R mean     R SD  F1 mean    F1 SD   F1 min   F1 max  Support
--------------------------------------------------------------------------------------------------------------------
Abstract                              0.9420   0.0055   0.9362   0.0068   0.9391   0.0031   0.9337   0.9453     3091
Animal                                0.8659   0.0282   0.9353   0.0273   0.8987   0.0154   0.8673   0.9333       51
Animate                               0.9574   0.0057   0.9542   0.0083   0.9557   0.0033   0.9502   0.9622     1198
Artefact                              0.8982   0.0167   0.8920   0.0171   0.8948   0.0064   0.8833   0.9043      517
Body_Part                             0.8785   0.0365   0.8960   0.0419   0.8860   0.0232   0.8387   0.9375       33
Comestible                            0.8861   0.0118   0.9570   0.0099   0.9201   0.0068   0.9102   0.9342      155
Communication                         0.8941   0.0137   0.8922   0.0175   0.8929   0.0087   0.8742   0.9052      553
Concrete                              0.9410   0.0040   0.9504   0.0045   0.9457   0.0021   0.9383   0.9490     2216
Currency                              0.9987   0.0073   0.9569   0.0371   0.9770   0.0189   0.9565   1.0000       24
Duration                              0.8402   0.0350   0.8281   0.0457   0.8324   0.0146   0.8082   0.8647      153
Elongated                             0.8233   0.0687   0.5832   0.0401   0.6800   0.0309   0.5842   0.7403       95
Eventive                              0.8509   0.0148   0.8832   0.0129   0.8666   0.0064   0.8454   0.8769      679
Feminine                              0.9283   0.0225   0.9106   0.0282   0.9189   0.0144   0.8927   0.9466      141
Fluid                                 0.9116   0.0479   0.9267   0.0430   0.9176   0.0279   0.8649   0.9744       20
Garment                               0.9967   0.0183   0.8788   0.0551   0.9331   0.0352   0.8421   0.9524       11
Human                                 0.9617   0.0059   0.9574   0.0080   0.9595   0.0031   0.9547   0.9653     1106
Inanimate                             0.9103   0.0100   0.9224   0.0071   0.9162   0.0038   0.9037   0.9221     1005
Internal_Control                      0.9377   0.0066   0.9280   0.0080   0.9328   0.0028   0.9261   0.9376     2336
Language                              0.9333   0.2034   0.8167   0.2780   0.8467   0.2209   0.0000   1.0000        2
Location                              0.8962   0.0161   0.9025   0.0090   0.8992   0.0069   0.8795   0.9110      799
Machine                               0.9122   0.0216   0.8822   0.0268   0.8964   0.0127   0.8731   0.9216      202
Masculine                             0.9079   0.0110   0.9063   0.0171   0.9069   0.0047   0.8966   0.9144      556
Natural                               0.9512   0.0055   0.9483   0.0083   0.9497   0.0032   0.9439   0.9563     1240
Natural_Force                         0.8890   0.0452   0.6152   0.0286   0.7262   0.0242   0.6667   0.7568       22
Non_Rigid                             0.7402   0.0311   0.8080   0.0310   0.7715   0.0104   0.7466   0.7921      217
Organisation                          0.8551   0.0171   0.8592   0.0156   0.8569   0.0054   0.8441   0.8661      911
Plant                                 0.9521   0.1019   0.7000   0.0678   0.8006   0.0419   0.6667   0.9091        6
Point_in_Time                         0.8683   0.0352   0.8701   0.0369   0.8678   0.0084   0.8519   0.8871      174
Pointy                                0.1308   0.2632   0.0545   0.0973   0.0623   0.0987   0.0000   0.3158       11
Question                              0.8513   0.0681   0.9278   0.0259   0.8859   0.0338   0.7907   0.9412       18
Rigid                                 0.8651   0.0172   0.8390   0.0182   0.8516   0.0087   0.8331   0.8660      377
Solid                                 0.9356   0.0060   0.9133   0.0134   0.9243   0.0068   0.8998   0.9320     1393
Sound                                 0.7073   0.0876   0.6484   0.0918   0.6669   0.0475   0.5600   0.7458       31
Statement                             0.7895   0.0434   0.6585   0.0462   0.7157   0.0185   0.6861   0.7559      160
Substance                             0.7956   0.0347   0.9254   0.0259   0.8547   0.0142   0.8238   0.8791      159
Time                                  0.9571   0.0097   0.9470   0.0276   0.9517   0.0127   0.9088   0.9721      337
Unspecified_Gender_or_Neuter          0.8217   0.0297   0.8473   0.0170   0.8338   0.0116   0.8134   0.8642      408
Vehicle                               0.8723   0.0396   0.9279   0.0473   0.8979   0.0259   0.8205   0.9600       37
Web_Location                          0.9332   0.0280   0.7000   0.0530   0.7982   0.0291   0.7317   0.8448      124

======================================================================================================================
REPEATED-RUN TEST PERFORMANCE BY INDEPENDENT NEURAL OUTPUT
======================================================================================================================
Feature                               P mean     P SD   R mean     R SD  F1 mean    F1 SD   F1 min   F1 max  Support
--------------------------------------------------------------------------------------------------------------------
Abstract                              0.8817   0.0198   0.8447   0.0156   0.8625   0.0061   0.8447   0.8773      733
Animal                                0.8659   0.0282   0.9353   0.0273   0.8987   0.0154   0.8673   0.9333       51
Animate                               0.1000   0.3051   0.0500   0.1526   0.0667   0.2034   0.0000   0.6667        2
Artefact                              0.8347   0.0276   0.8533   0.0219   0.8433   0.0121   0.8084   0.8599      304
Body_Part                             0.8785   0.0365   0.8960   0.0419   0.8860   0.0232   0.8387   0.9375       33
Comestible                            0.8861   0.0118   0.9570   0.0099   0.9201   0.0068   0.9102   0.9342      155
Communication                         0.7834   0.0232   0.8506   0.0275   0.8150   0.0117   0.7810   0.8335      375
Currency                              0.9987   0.0073   0.9569   0.0371   0.9770   0.0189   0.9565   1.0000       24
Duration                              0.8402   0.0350   0.8281   0.0457   0.8324   0.0146   0.8082   0.8647      153
Elongated                             0.8233   0.0687   0.5832   0.0401   0.6800   0.0309   0.5842   0.7403       95
Eventive                              0.8509   0.0148   0.8832   0.0129   0.8666   0.0064   0.8454   0.8769      679
Feminine                              0.9283   0.0225   0.9106   0.0282   0.9189   0.0144   0.8927   0.9466      141
Fluid                                 0.9116   0.0479   0.9267   0.0430   0.9176   0.0279   0.8649   0.9744       20
Garment                               0.9967   0.0183   0.8788   0.0551   0.9331   0.0352   0.8421   0.9524       11
Inanimate                             0.9103   0.0100   0.9224   0.0071   0.9162   0.0038   0.9037   0.9221     1005
Internal_Control                      0.6193   0.2190   0.2583   0.0651   0.3497   0.0765   0.1667   0.4762       16
Language                              0.9333   0.2034   0.8167   0.2780   0.8467   0.2209   0.0000   1.0000        2
Location                              0.8962   0.0161   0.9025   0.0090   0.8992   0.0069   0.8795   0.9110      799
Machine                               0.9043   0.0295   0.8614   0.0304   0.8816   0.0146   0.8494   0.9069      165
Masculine                             0.9079   0.0110   0.9063   0.0171   0.9069   0.0047   0.8966   0.9144      556
Natural                               0.7177   0.0463   0.7302   0.0275   0.7223   0.0164   0.6947   0.7500       42
Natural_Force                         0.8890   0.0452   0.6152   0.0286   0.7262   0.0242   0.6667   0.7568       22
Non_Rigid                             0.7402   0.0311   0.8080   0.0310   0.7715   0.0104   0.7466   0.7921      217
Organisation                          0.8551   0.0171   0.8592   0.0156   0.8569   0.0054   0.8441   0.8661      911
Plant                                 0.9521   0.1019   0.7000   0.0678   0.8006   0.0419   0.6667   0.9091        6
Point_in_Time                         0.8683   0.0352   0.8701   0.0369   0.8678   0.0084   0.8519   0.8871      174
Pointy                                0.1308   0.2632   0.0545   0.0973   0.0623   0.0987   0.0000   0.3158       11
Question                              0.8513   0.0681   0.9278   0.0259   0.8859   0.0338   0.7907   0.9412       18
Rigid                                 0.8651   0.0172   0.8390   0.0182   0.8516   0.0087   0.8331   0.8660      377
Solid                                 0.8649   0.0151   0.8387   0.0177   0.8513   0.0069   0.8225   0.8579      799
Sound                                 0.7073   0.0876   0.6484   0.0918   0.6669   0.0475   0.5600   0.7458       31
Statement                             0.7895   0.0434   0.6585   0.0462   0.7157   0.0185   0.6861   0.7559      160
Substance                             0.7956   0.0347   0.9254   0.0259   0.8547   0.0142   0.8238   0.8791      159
Time                                  0.4040   0.0905   0.6400   0.1102   0.4807   0.0480   0.3871   0.5833       10
Unspecified_Gender_or_Neuter          0.8217   0.0297   0.8473   0.0170   0.8338   0.0116   0.8134   0.8642      408
Vehicle                               0.8723   0.0396   0.9279   0.0473   0.8979   0.0259   0.8205   0.9600       37
Web_Location                          0.9332   0.0280   0.7000   0.0530   0.7982   0.0291   0.7317   0.8448      124

====================================================================================================
SENTENCE-CLUSTER BOOTSTRAP ON HELD-OUT TEST SET
====================================================================================================
Bootstrap samples: 2,000
Confidence level : 95.0%
Bootstrap unit   : sentence (all eligible NOUN/PROPN targets from a sampled sentence move together)

Metric                      Run mean     Run SD   95% CI low  95% CI high
------------------------------------------------------------------------------
precision_micro               0.9175     0.0038       0.9110       0.9237
recall_micro                  0.9146     0.0041       0.9076       0.9211
f1_micro                      0.9160     0.0024       0.9101       0.9216
precision_macro               0.8715     0.0083       0.8414       0.8798
recall_macro                  0.8432     0.0099       0.8150       0.8574
f1_macro                      0.8521     0.0063       0.8231       0.8611

====================================================================================================
OUTPUTS
====================================================================================================
Fixed sentence split:
  /home/mark/verbnet-roberta/models/roberta_semantic_features/sentence_split.json
Semantic feature metadata:
  /home/mark/verbnet-roberta/models/roberta_semantic_features/semantic_features.json
Per-run results:
  /home/mark/verbnet-roberta/models/roberta_semantic_features/runs
Repeated-run summary:
  /home/mark/verbnet-roberta/models/roberta_semantic_features/repeated_run_results.json
Test bootstrap confidence intervals:
  /home/mark/verbnet-roberta/models/roberta_semantic_features/test_bootstrap_confidence_intervals.json
Neutral reference model (first predeclared seed; not best-test selected):
  /home/mark/verbnet-roberta/models/roberta_semantic_features/reference_model

<h1>Hyperparameter tuning</h1>

In [6]:
#!/usr/bin/env python3
"""
Fine-tune RoBERTa for hierarchical multi-label semantic feature tagging of
NOUN/PROPN tokens.

Compatible with Python 3.9.21.

Key design changes
------------------
1. The model is trained only on independent semantic features. For each token,
   any feature that can be inherited from a more specific present feature is
   removed from the neural target. This is a per-token reduction rather than a
   global "terminal leaf only" rule, so features such as Human, Time, Shape,
   Communication, etc. can still be predicted directly when they are the most
   specific available feature for that token.

2. All inherited features are reconstructed deterministically from
   FEATURE_PARENTS for validation, testing, reporting, and later inference.

3. A separate sigmoid threshold is optimised for every neural output using the
   validation split only. The selected thresholds are frozen before the test
   split is evaluated and are saved to prediction_thresholds.json.

4. Train/validation splitting is performed at SENTENCE level with iterative
   multilabel stratification over sentence-level independent-feature presence.
   The split is fixed across repeated fine-tuning runs.

5. A single fixed training seed is used for a validation-only grid search over
   learning rate and effective batch size. This selects a candidate setting
   for the later repeated-seed experiment, not a final performance estimate.

6. The official test corpus is not loaded or evaluated during tuning.

Tagged data:
    Training/validation:
        ewt_train_wordnet_wsd_features_wordnet_fixed.jsonl

Sentence/token sources:
    Training/validation:
        UD_English-EWT-master/
        UD_English-EWT-master/
        en_ewt-ud-train.conllu

The validation split is created only from the training corpus. The official
test corpus remains untouched until final evaluation.

Loss:
    BCEWithLogitsLoss over INDEPENDENT feature labels only.

Headline metrics:
    Computed after deterministic hierarchy expansion, so they describe the
    complete semantic feature sets rather than only the neural outputs.

Requirements:
    python -m pip install torch transformers datasets accelerate conllu scikit-learn iterative-stratification

CUDA is required.
"""

from __future__ import annotations

import csv
import gc
import json
import shutil
from itertools import product
from collections import Counter, defaultdict
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Set, Tuple

import numpy as np
import torch
import torch.nn as nn

from conllu import parse_incr
from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit
from sklearn.metrics import precision_recall_fscore_support
from torch.utils.data import Dataset

from transformers import (
    AutoModelForTokenClassification,
    AutoTokenizer,
    Trainer,
    TrainingArguments,
    set_seed,
)


# =============================================================================
# Configuration
# =============================================================================

TRAIN_JSONL_PATH = Path(
    "../data/ewt_train_wordnet_wsd_features_wordnet_fixed.jsonl"
    #"ewt_train_wordnet_wsd_features_fully_tagged_llm_reviewed.jsonl"
)

TRAIN_CONLLU_PATH = Path(
    "../data/UD_English-EWT-master/"
    "UD_English-EWT-master/"
    "en_ewt-ud-train.conllu"
)

# MODEL_NAME = "FacebookAI/roberta-base"
MODEL_NAME = "FacebookAI/roberta-large"

OUTPUT_DIR = Path("../models/roberta_semantic_features_grid_search")

# Validation is sampled only from eligible training sentences.
VALIDATION_FRACTION = 0.20

# Fixed seed for the sentence-level train/validation split.
SPLIT_SEED = 42

# All grid candidates use the same random seed and split.
TUNING_SEED = 11

# 3 learning rates x 4 batch configurations = 12 training runs.
LEARNING_RATES = [2.5e-5, 3e-5, 3.5e-5, 4e-5]
PER_DEVICE_TRAIN_BATCH_SIZES = [4, 8]
EFFECTIVE_BATCH_SIZES = [16, 32]
# Gradient accumulation is effective_batch_size // per_device_train_batch_size.
# For a single GPU, the four configurations are (4, 4), (8, 2),
# (4, 8), and (8, 4), where pairs mean (device batch, accumulation).

# The multilabel stratifier is retried with deterministic derived seeds until
# every independent feature still has at least this many positive token targets
# in the TRAIN subset. This prevents a rare direct target from disappearing.
MIN_TRAIN_POSITIVES_PER_FEATURE = 1
MAX_STRATIFICATION_ATTEMPTS = 200

MAX_LENGTH = 256

WEIGHT_DECAY = 0.01

EVAL_BATCH_SIZE = 16

NUM_EPOCHS = 5

# Threshold used during epoch-by-epoch Trainer evaluation. Final thresholds are
# optimised per independent feature on the validation set after training.
DEFAULT_PREDICTION_THRESHOLD = 0.5

# Validation-only threshold search grid.
THRESHOLD_MIN = 0.05
THRESHOLD_MAX = 0.95
THRESHOLD_STEP = 0.01

# Only these POS categories receive feature supervision.
TARGET_POS = {"NOUN", "PROPN"}

# A NOUN/PROPN with no features is considered a failed source annotation rather
# than a valid all-negative target.
EXCLUDE_EMPTY_FEATURE_RECORDS = True

# Optional per-feature switches. Any feature not listed here is enabled.
# Set a feature to False to remove it from:
#   - sentence-level stratification,
#   - neural training targets,
#   - threshold calibration,
#   - hierarchy-expanded gold/predicted feature sets,
#   - per-feature and aggregate evaluation, and
#   - the sentence-cluster bootstrap.
#
# Disabled intermediate hierarchy nodes are skipped but their enabled ancestors
# are still inherited. For example, if Human were disabled, Feminine would still
# inherit Animate/Natural/Concrete/Internal_Control via the hierarchy.
FEATURE_SWITCHES: Dict[str, bool] = {
    "State": False,
    "State_of_Matter": False,
    "Shape": False,
    "Rigidity": False,
}

EVAL_STRATEGY = "epoch"

SPLIT_PATH = OUTPUT_DIR / "sentence_split.json"
LABELS_PATH = OUTPUT_DIR / "semantic_features.json"
GRID_RESULTS_PATH = OUTPUT_DIR / "hyperparameter_grid_results.json"
GRID_CSV_PATH = OUTPUT_DIR / "hyperparameter_grid_results.csv"


# =============================================================================
# Feature hierarchy
# =============================================================================

def is_feature_enabled(feature: str) -> bool:
    """Return whether *feature* participates in this experiment."""

    return bool(FEATURE_SWITCHES.get(feature, True))


def validate_feature_switches(
    train_tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> None:
    """Fail early on misspelled feature-switch names and report disabled labels."""

    observed: Set[str] = set()

    for source in (train_tagged_records,):
        for sentence_records in source.values():
            for record in sentence_records.values():
                raw = record.get("features", [])
                if isinstance(raw, list):
                    observed.update(
                        str(feature).strip()
                        for feature in raw
                        if str(feature).strip()
                    )

    known = set(observed) | set(FEATURE_PARENTS)
    for parents in FEATURE_PARENTS.values():
        known.update(parents)

    unknown = sorted(set(FEATURE_SWITCHES) - known)
    if unknown:
        raise ValueError(
            "FEATURE_SWITCHES contains unknown feature name(s): "
            + ", ".join(unknown)
        )

    disabled = sorted(
        feature for feature, enabled in FEATURE_SWITCHES.items() if not enabled
    )

    print("=" * 80)
    print("FEATURE SWITCHES")
    print("=" * 80)
    if disabled:
        print("Disabled features: " + ", ".join(disabled))
    else:
        print("Disabled features: none")
    print("All unlisted features are enabled.")
    print()


# child -> direct parent(s)
FEATURE_PARENTS: Dict[str, Set[str]] = {
    "Organisation": {
        "Internal_Control",
        "Abstract",
    },
    "Natural_Force": {
        "Internal_Control",
    },
    "Animate": {
        "Internal_Control",
        "Natural",
    },
    "Human": {
        "Animate",
    },
    "Feminine": {
        "Human",
    },
    "Masculine": {
        "Human",
    },
    "Unspecified_Gender_or_Neuter": {
        "Human",
    },
    "Animal": {
        "Animate",
    },
    "Plant": {
        "Animate",
    },
    "Body_Part": {
        "Animate",
    },
    "Machine": {
        "Internal_Control",
        "Artefact",
    },
    "Vehicle": {
        "Machine",
    },
    "Natural": {
        "Concrete",
    },
    "Artefact": {
        "Concrete",
    },
    "Comestible": {
        "Concrete",
    },
    "Substance": {
        "Concrete",
    },
    "State_of_Matter": {
        "Concrete",
    },
    "Inanimate": {
        "Concrete",
    },
    "Garment": {
        "Artefact",
    },
    "Solid": {
        "State_of_Matter",
    },
    "Fluid": {
        "State_of_Matter",
    },
    "Rigidity": {
        "Solid",
    },
    "Shape": {
        "Solid",
    },
    "Rigid": {
        "Rigidity",
    },
    "Non_Rigid": {
        "Rigidity",
    },
    "Elongated": {
        "Shape",
    },
    "Pointy": {
        "Shape",
    },
    "Point_in_Time": {
        "Time",
    },
    "Duration": {
        "Time",
    },
    "Time": {
        "Abstract",
    },
    "Language": {
        "Abstract",
    },
    "Sound": {
        "Abstract",
    },
    "Communication": {
        "Abstract",
    },
    "Eventive": {
        "Abstract",
    },
    "Statement": {
        "Communication",
    },
    "Question": {
        "Communication",
    },
}


def validate_feature_hierarchy() -> None:
    """Fail early if FEATURE_PARENTS contains a cycle or invalid name."""

    all_features: Set[str] = set(FEATURE_PARENTS)

    for parents in FEATURE_PARENTS.values():
        all_features.update(parents)

    for feature in all_features:
        if not isinstance(feature, str) or not feature.strip():
            raise ValueError(
                "FEATURE_PARENTS contains an empty or non-string feature name."
            )

    visiting: Set[str] = set()
    visited: Set[str] = set()

    def visit(feature: str) -> None:
        if feature in visited:
            return

        if feature in visiting:
            raise ValueError(
                f"Cycle detected in FEATURE_PARENTS involving {feature!r}."
            )

        visiting.add(feature)

        for parent in FEATURE_PARENTS.get(feature, set()):
            visit(parent)

        visiting.remove(feature)
        visited.add(feature)

    for feature in sorted(all_features):
        visit(feature)


@lru_cache(maxsize=None)
def get_feature_ancestors(feature: str) -> frozenset:
    """Return every direct and indirect parent of *feature*."""

    ancestors: Set[str] = set()

    for parent in FEATURE_PARENTS.get(feature, set()):
        if is_feature_enabled(parent):
            ancestors.add(parent)
        # Traverse even through a disabled intermediate node so enabled
        # grandparents remain inherited.
        ancestors.update(get_feature_ancestors(parent))

    return frozenset(ancestors)


def expand_feature_hierarchy(features: Iterable[str]) -> Set[str]:
    """Add every deterministic ancestor required by FEATURE_PARENTS."""

    expanded: Set[str] = {
        feature for feature in features if is_feature_enabled(feature)
    }

    for feature in list(expanded):
        expanded.update(get_feature_ancestors(feature))

    return expanded


def reduce_to_independent_features(features: Iterable[str]) -> Set[str]:
    """
    Reduce a complete feature set to the features that must be predicted.

    A feature is redundant when it is an ancestor of another feature present
    for the same token. Such an ancestor can be reconstructed deterministically.

    Examples:
        {Human, Animate, Natural, Concrete, Internal_Control}
            -> {Human}

        {Feminine, Human, Animate, Natural, Concrete, Internal_Control}
            -> {Feminine}

        {Statement, Communication, Abstract, Time}
            -> {Statement, Time}

    This is deliberately PER TOKEN. It is not the same as training only labels
    that are global terminal leaves in the ontology. A generic Human can still
    be a direct neural target if no more specific Human child is present.
    """

    feature_set = set(features)

    inherited_from_other_features: Set[str] = set()

    for feature in feature_set:
        inherited_from_other_features.update(
            get_feature_ancestors(feature)
        )

    return feature_set - inherited_from_other_features


def missing_hierarchy_features(features: Iterable[str]) -> Set[str]:
    """Return ancestors required by the hierarchy but absent from *features*."""

    feature_set = set(features)
    return expand_feature_hierarchy(feature_set) - feature_set


# =============================================================================
# CUDA
# =============================================================================

def check_cuda() -> None:
    """Require CUDA rather than silently falling back to the CPU."""

    if not torch.cuda.is_available():
        raise RuntimeError(
            "CUDA is not available. This script is configured to require "
            "a CUDA-capable GPU."
        )

    print("=" * 80)
    print("CUDA")
    print("=" * 80)
    print(f"PyTorch version: {torch.__version__}")
    print(f"CUDA available: {torch.cuda.is_available()}")
    print(f"CUDA runtime: {torch.version.cuda}")
    print(f"GPU: {torch.cuda.get_device_name(0)}")

    props = torch.cuda.get_device_properties(0)

    print(
        "VRAM: "
        f"{props.total_memory / (1024 ** 3):.2f} GiB"
    )
    print()


# =============================================================================
# Load CoNLL-U
# =============================================================================

def load_conllu(path: Path) -> List[Any]:
    """Load all CoNLL-U sentences."""

    if not path.exists():
        raise FileNotFoundError(
            f"Could not find CoNLL-U file:\n{path.resolve()}"
        )

    sentences: List[Any] = []

    with path.open("r", encoding="utf-8") as handle:
        for sentence in parse_incr(handle):
            sentences.append(sentence)

    return sentences


def get_sentence_words(sentence: Any) -> Tuple[List[str], List[int]]:
    """
    Return ordinary integer-ID tokens and their original CoNLL-U token IDs.

    Multiword-token placeholder rows and empty nodes are excluded.
    """

    words: List[str] = []
    token_ids: List[int] = []

    for token in sentence:
        token_id = token.get("id")

        if not isinstance(token_id, int):
            continue

        form = token.get("form")

        if form is None:
            continue

        words.append(str(form))
        token_ids.append(token_id)

    return words, token_ids


# =============================================================================
# Load tagged JSONL
# =============================================================================

def load_tagged_records(
    path: Path,
) -> Dict[int, Dict[int, Dict[str, Any]]]:
    """
    Return:

        sentence_index
            -> token_id
                -> JSONL record

    Only NOUN and PROPN records are retained.
    """

    if not path.exists():
        raise FileNotFoundError(
            f"Could not find tagged JSONL:\n{path.resolve()}"
        )

    records: Dict[int, Dict[int, Dict[str, Any]]] = defaultdict(dict)

    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            line = line.strip()

            if not line:
                continue

            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                print(
                    "Warning: invalid JSON on line "
                    f"{line_number}: {exc}"
                )
                continue

            if record.get("upos") not in TARGET_POS:
                continue

            sentence_index = record.get("sentence_index")
            token_id = record.get("token_id")

            if not isinstance(sentence_index, int):
                continue

            if not isinstance(token_id, int):
                continue

            records[sentence_index][token_id] = record

    return dict(records)


# =============================================================================
# Labels
# =============================================================================

def clean_features(record: Dict[str, Any]) -> List[str]:
    """Return unique, non-empty COMPLETE feature names from a JSONL record."""

    raw = record.get("features", [])

    if not isinstance(raw, list):
        return []

    return sorted(
        {
            str(feature).strip()
            for feature in raw
            if (
                str(feature).strip()
                and is_feature_enabled(str(feature).strip())
            )
        }
    )


def get_independent_record_features(record: Dict[str, Any]) -> List[str]:
    """Return the per-token minimal feature set that the model must predict."""

    return sorted(
        reduce_to_independent_features(
            clean_features(record)
        )
    )


def build_full_label_vocabulary(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    training_sentence_indices: Sequence[int],
) -> List[str]:
    """
    Build the COMPLETE evaluation vocabulary from training data only.

    Deterministic ancestors are included even if a training record omitted one,
    although hierarchy closure is separately verified and should normally make
    this addition unnecessary.
    """

    labels: Set[str] = set()

    for sentence_index in training_sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            features = clean_features(record)
            labels.update(features)
            labels.update(expand_feature_hierarchy(features))

    if not labels:
        raise RuntimeError(
            "No semantic features were found in the training split."
        )

    return sorted(labels)


def build_prediction_label_vocabulary(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    training_sentence_indices: Sequence[int],
) -> List[str]:
    """Build the neural-output vocabulary from independent training targets."""

    labels: Set[str] = set()

    for sentence_index in training_sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            labels.update(
                get_independent_record_features(record)
            )

    if not labels:
        raise RuntimeError(
            "No independent semantic features were found in the training split."
        )

    return sorted(labels)


# =============================================================================
# Sentence selection and splitting
# =============================================================================

def get_eligible_sentence_indices(
    sentences: Sequence[Any],
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> List[int]:
    """Eligible sentences contain at least one non-empty NOUN/PROPN target."""

    eligible: List[int] = []

    for sentence_index in range(len(sentences)):
        token_records = tagged_records.get(sentence_index, {})

        valid_records = [
            record
            for record in token_records.values()
            if clean_features(record)
        ]

        if valid_records:
            eligible.append(sentence_index)

    return eligible


def get_sentence_independent_feature_counts(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    sentence_index: int,
) -> Counter:
    """Count independent positive token targets in one source sentence."""

    counts: Counter = Counter()

    for record in tagged_records.get(sentence_index, {}).values():
        if not clean_features(record):
            continue

        for feature in get_independent_record_features(record):
            counts[feature] += 1

    return counts


def build_sentence_multilabel_matrix(
    eligible_indices: Sequence[int],
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> Tuple[np.ndarray, List[str], Dict[int, Counter]]:
    """
    Build one multilabel stratification row per SENTENCE.

    y_sentence[sentence, feature] is 1 when at least one eligible NOUN/PROPN
    token in that sentence has the independent feature. Token counts are kept
    separately for the post-split training-coverage constraint.
    """

    sentence_feature_counts: Dict[int, Counter] = {
        sentence_index: get_sentence_independent_feature_counts(
            tagged_records,
            sentence_index,
        )
        for sentence_index in eligible_indices
    }

    stratification_labels = sorted(
        {
            feature
            for counts in sentence_feature_counts.values()
            for feature, count in counts.items()
            if count > 0
        }
    )

    if not stratification_labels:
        raise RuntimeError(
            "No independent semantic features were found in eligible "
            "training sentences."
        )

    label2column = {
        label: column
        for column, label in enumerate(stratification_labels)
    }

    matrix = np.zeros(
        (len(eligible_indices), len(stratification_labels)),
        dtype=np.int8,
    )

    for row, sentence_index in enumerate(eligible_indices):
        for feature in sentence_feature_counts[sentence_index]:
            matrix[row, label2column[feature]] = 1

    return matrix, stratification_labels, sentence_feature_counts


def _sentence_prevalence_error(
    y_all: np.ndarray,
    validation_rows: np.ndarray,
    validation_fraction: float,
) -> float:
    """
    Score how closely validation sentence-level label prevalences match target.

    Lower is better. The score is used only to choose among deterministic
    iterative-stratification attempts that satisfy the training-coverage rule.
    """

    total_support = y_all.sum(axis=0).astype(np.float64)
    validation_support = y_all[validation_rows].sum(axis=0).astype(np.float64)

    target_support = total_support * float(validation_fraction)

    # Scale by at least one expected example so rare and common labels both
    # contribute without allowing extremely common labels to dominate.
    scale = np.maximum(target_support, 1.0)

    return float(
        np.mean(
            np.abs(validation_support - target_support) / scale
        )
    )


def make_train_validation_split(
    eligible_indices: Sequence[int],
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> Dict[str, Any]:
    """
    Create a SENTENCE-LEVEL multilabel-stratified split from TRAINING only.

    Each sentence receives a binary vector indicating which independent feature
    labels occur anywhere among its eligible NOUN/PROPN tokens. Iterative
    multilabel stratification then assigns whole sentences to train/validation.

    The split is retried deterministically when necessary so that every
    independent feature retains at least MIN_TRAIN_POSITIVES_PER_FEATURE
    positive TOKEN targets in the training subset.

    The official test corpus is deliberately not accepted by this function, so
    test labels cannot influence the split.
    """

    if not 0.0 < VALIDATION_FRACTION < 1.0:
        raise ValueError(
            "VALIDATION_FRACTION must be strictly between 0 and 1."
        )

    if MIN_TRAIN_POSITIVES_PER_FEATURE < 1:
        raise ValueError(
            "MIN_TRAIN_POSITIVES_PER_FEATURE must be at least 1."
        )

    if MAX_STRATIFICATION_ATTEMPTS < 1:
        raise ValueError(
            "MAX_STRATIFICATION_ATTEMPTS must be at least 1."
        )

    eligible_indices = list(eligible_indices)

    if len(eligible_indices) < 2:
        raise RuntimeError(
            "Need at least two eligible training sentences to create a "
            "train/validation split."
        )

    (
        sentence_matrix,
        stratification_labels,
        sentence_feature_counts,
    ) = build_sentence_multilabel_matrix(
        eligible_indices,
        tagged_records,
    )

    all_token_counts: Counter = Counter()

    for counts in sentence_feature_counts.values():
        all_token_counts.update(counts)

    x_dummy = np.zeros((len(eligible_indices), 1), dtype=np.int8)

    best_candidate: Optional[Dict[str, Any]] = None
    rejected_for_coverage = 0

    for attempt in range(MAX_STRATIFICATION_ATTEMPTS):
        attempt_seed = SPLIT_SEED + attempt

        splitter = MultilabelStratifiedShuffleSplit(
            n_splits=1,
            test_size=VALIDATION_FRACTION,
            random_state=attempt_seed,
        )

        train_rows, validation_rows = next(
            splitter.split(x_dummy, sentence_matrix)
        )

        train_indices = [
            eligible_indices[int(row)]
            for row in train_rows
        ]
        validation_indices = [
            eligible_indices[int(row)]
            for row in validation_rows
        ]

        train_token_counts: Counter = Counter()

        for sentence_index in train_indices:
            train_token_counts.update(
                sentence_feature_counts[sentence_index]
            )

        missing_or_undercovered = sorted(
            feature
            for feature, total_count in all_token_counts.items()
            if (
                total_count > 0
                and train_token_counts[feature]
                < MIN_TRAIN_POSITIVES_PER_FEATURE
            )
        )

        if missing_or_undercovered:
            rejected_for_coverage += 1
            continue

        prevalence_error = _sentence_prevalence_error(
            sentence_matrix,
            validation_rows,
            VALIDATION_FRACTION,
        )

        candidate = {
            "train": train_indices,
            "validation": validation_indices,
            "split_seed_used": attempt_seed,
            "attempt": attempt + 1,
            "prevalence_error": prevalence_error,
            "stratification_labels": stratification_labels,
        }

        if (
            best_candidate is None
            or prevalence_error < best_candidate["prevalence_error"]
        ):
            best_candidate = candidate

        # Iterative stratification is already designed to balance multilabel
        # prevalence. Once a valid candidate is found, further attempts are not
        # needed unless coverage forced earlier candidates to be rejected.
        if rejected_for_coverage == 0:
            break

    if best_candidate is None:
        raise RuntimeError(
            "Could not create a sentence-level multilabel-stratified "
            "train/validation split that preserved the required training "
            f"support after {MAX_STRATIFICATION_ATTEMPTS} attempts."
        )

    train_indices = best_candidate["train"]
    validation_indices = best_candidate["validation"]

    train_set = set(train_indices)
    validation_set = set(validation_indices)

    if train_set & validation_set:
        raise RuntimeError(
            "Internal split error: at least one sentence occurs in both "
            "training and validation."
        )

    if train_set | validation_set != set(eligible_indices):
        raise RuntimeError(
            "Internal split error: sentence-level split does not exactly cover "
            "the eligible training sentences."
        )

    print()
    print("Sentence-level multilabel-stratified train/validation split:")
    print(
        f"  Eligible training sentences : {len(eligible_indices):,}"
    )
    print(
        f"  Target validation sentences : "
        f"{round(len(eligible_indices) * VALIDATION_FRACTION):,}"
    )
    print(
        f"  Actual validation sentences : {len(validation_indices):,}"
    )
    print(
        f"  Training sentences retained : {len(train_indices):,}"
    )
    print(
        f"  Split seed used             : "
        f"{best_candidate['split_seed_used']}"
    )
    print(
        f"  Stratification labels       : "
        f"{len(stratification_labels):,}"
    )
    print(
        f"  Coverage-rejected attempts  : {rejected_for_coverage:,}"
    )
    print(
        f"  Mean relative prevalence error: "
        f"{best_candidate['prevalence_error']:.6f}"
    )

    # Show sentence-level prevalence agreement, which is the quantity actually
    # controlled by the stratifier.
    validation_fraction_actual = (
        len(validation_indices) / len(eligible_indices)
    )

    label2column = {
        label: column
        for column, label in enumerate(stratification_labels)
    }

    row_by_sentence = {
        sentence_index: row
        for row, sentence_index in enumerate(eligible_indices)
    }

    train_rows_lookup = [
        row_by_sentence[index]
        for index in train_indices
    ]
    validation_rows_lookup = [
        row_by_sentence[index]
        for index in validation_indices
    ]

    print()
    print(
        f"{'Feature':35s} "
        f"{'All sent.':>10s} "
        f"{'Train':>10s} "
        f"{'Valid':>10s} "
        f"{'Valid %':>10s}"
    )
    print("-" * 80)

    for feature in stratification_labels:
        column = label2column[feature]
        all_support = int(sentence_matrix[:, column].sum())
        train_support = int(
            sentence_matrix[train_rows_lookup, column].sum()
        )
        validation_support = int(
            sentence_matrix[validation_rows_lookup, column].sum()
        )

        print(
            f"{feature:35s} "
            f"{all_support:10d} "
            f"{train_support:10d} "
            f"{validation_support:10d} "
            f"{validation_support / max(all_support, 1):10.3f}"
        )

    print(
        f"\nActual validation sentence fraction: "
        f"{validation_fraction_actual:.4f}"
    )
    print()

    return best_candidate


# =============================================================================
# Dataset
# =============================================================================

class SemanticFeatureDataset(Dataset):
    """
    RoBERTa multi-label token-classification dataset.

    IMPORTANT:
        labels contain only INDEPENDENT neural targets.

    Labels have shape:
        [sequence_length, number_of_prediction_features]

    For supervised tokens:
        0 = independent feature absent
        1 = independent feature present

    For ignored tokens:
        -100 across all labels

    Only the first RoBERTa subword corresponding to each source token receives
    supervision.
    """

    def __init__(
        self,
        sentences: Sequence[Any],
        sentence_indices: Sequence[int],
        tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
        tokenizer: Any,
        label2id: Dict[str, int],
        max_length: int,
    ) -> None:
        self.sentences = sentences
        self.sentence_indices = list(sentence_indices)
        self.tagged_records = tagged_records
        self.tokenizer = tokenizer
        self.label2id = label2id
        self.num_labels = len(label2id)
        self.max_length = max_length

    def __len__(self) -> int:
        return len(self.sentence_indices)

    def __getitem__(
        self,
        dataset_index: int,
    ) -> Dict[str, Any]:
        sentence_index = self.sentence_indices[dataset_index]
        sentence = self.sentences[sentence_index]

        words, token_ids = get_sentence_words(sentence)

        encoding = self.tokenizer(
            words,
            is_split_into_words=True,
            truncation=True,
            max_length=self.max_length,
            add_special_tokens=True,
        )

        word_ids = encoding.word_ids()
        labels: List[List[float]] = []
        previous_word_id: Optional[int] = None
        sentence_records = self.tagged_records.get(sentence_index, {})

        for word_id in word_ids:
            if word_id is None:
                labels.append([-100.0] * self.num_labels)
                previous_word_id = word_id
                continue

            # Ignore all but the first subword.
            if word_id == previous_word_id:
                labels.append([-100.0] * self.num_labels)
                continue

            previous_word_id = word_id

            if not 0 <= word_id < len(token_ids):
                labels.append([-100.0] * self.num_labels)
                continue

            conllu_token_id = token_ids[word_id]
            record = sentence_records.get(conllu_token_id)

            if record is None:
                labels.append([-100.0] * self.num_labels)
                continue

            full_features = clean_features(record)

            if not full_features and EXCLUDE_EMPTY_FEATURE_RECORDS:
                labels.append([-100.0] * self.num_labels)
                continue

            independent_features = reduce_to_independent_features(
                full_features
            )

            target = [0.0] * self.num_labels

            for feature in independent_features:
                label_id = self.label2id.get(feature)

                if label_id is not None:
                    target[label_id] = 1.0

            labels.append(target)

        encoding["labels"] = labels
        encoding["sentence_index"] = sentence_index

        return encoding


# =============================================================================
# Data collator
# =============================================================================

class MultiLabelTokenCollator:
    """Dynamically pad inputs and 3-D multi-label token targets."""

    def __init__(
        self,
        tokenizer: Any,
        num_labels: int,
    ) -> None:
        self.tokenizer = tokenizer
        self.num_labels = num_labels

    def __call__(
        self,
        features: List[Dict[str, Any]],
    ) -> Dict[str, torch.Tensor]:
        clean_features_list: List[Dict[str, Any]] = []
        labels_list: List[List[List[float]]] = []

        for item in features:
            item = dict(item)
            item.pop("sentence_index", None)

            labels = item.pop("labels")
            labels_list.append(labels)
            clean_features_list.append(item)

        batch = self.tokenizer.pad(
            clean_features_list,
            padding=True,
            return_tensors="pt",
        )

        batch_size = len(labels_list)
        max_seq_length = batch["input_ids"].shape[1]

        padded_labels = torch.full(
            (
                batch_size,
                max_seq_length,
                self.num_labels,
            ),
            -100.0,
            dtype=torch.float32,
        )

        for batch_index, labels in enumerate(labels_list):
            label_tensor = torch.tensor(
                labels,
                dtype=torch.float32,
            )

            sequence_length = label_tensor.shape[0]

            padded_labels[
                batch_index,
                :sequence_length,
                :,
            ] = label_tensor

        batch["labels"] = padded_labels

        return batch


# =============================================================================
# Model
# =============================================================================

class RobertaMultiLabelModel(nn.Module):
    """RoBERTa token classifier with BCE loss for independent feature labels."""

    def __init__(
        self,
        model_name: str,
        num_labels: int,
        id2label: Dict[int, str],
        label2id: Dict[str, int],
    ) -> None:
        super().__init__()

        self.model = AutoModelForTokenClassification.from_pretrained(
            model_name,
            num_labels=num_labels,
            id2label=id2label,
            label2id=label2id,
        )

        self.config = self.model.config

        self.loss_function = nn.BCEWithLogitsLoss(
            reduction="mean"
        )

    def forward(
        self,
        input_ids=None,
        attention_mask=None,
        labels=None,
        **kwargs,
    ):
        outputs = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            **kwargs,
        )

        logits = outputs.logits
        loss = None

        if labels is not None:
            valid_mask = labels[:, :, 0] != -100.0

            valid_logits = logits[valid_mask]
            valid_labels = labels[valid_mask]

            if valid_logits.numel() == 0:
                loss = logits.sum() * 0.0
            else:
                loss = self.loss_function(
                    valid_logits,
                    valid_labels,
                )

        return {
            "loss": loss,
            "logits": logits,
        }

    def save_pretrained(
        self,
        save_directory,
        **kwargs,
    ):
        return self.model.save_pretrained(
            save_directory,
            **kwargs,
        )


# =============================================================================
# Hierarchy matrices and array helpers
# =============================================================================

def build_hierarchy_expansion_matrix(
    prediction_labels: Sequence[str],
    full_labels: Sequence[str],
) -> np.ndarray:
    """
    Build a boolean matrix mapping neural outputs to complete feature sets.

    Shape:
        [number_of_prediction_features, number_of_full_features]
    """

    full_label2id = {
        label: index
        for index, label in enumerate(full_labels)
    }

    matrix = np.zeros(
        (len(prediction_labels), len(full_labels)),
        dtype=np.int8,
    )

    for prediction_id, feature in enumerate(prediction_labels):
        expanded = expand_feature_hierarchy({feature})

        for expanded_feature in expanded:
            full_id = full_label2id.get(expanded_feature)

            if full_id is None:
                raise RuntimeError(
                    "Hierarchy expansion produced a feature absent from the "
                    f"full vocabulary: {expanded_feature!r}."
                )

            matrix[prediction_id, full_id] = 1

    return matrix


def expand_binary_feature_matrix(
    independent_matrix: np.ndarray,
    hierarchy_matrix: np.ndarray,
) -> np.ndarray:
    """Expand [tokens, independent] binary values to [tokens, complete]."""

    expanded = independent_matrix.astype(np.int32) @ hierarchy_matrix.astype(
        np.int32
    )

    return (expanded > 0).astype(np.int32)


def extract_valid_token_arrays(
    logits: np.ndarray,
    labels: np.ndarray,
) -> Tuple[np.ndarray, np.ndarray]:
    """Return probabilities and true independent labels for supervised tokens."""

    valid_token_mask = labels[:, :, 0] != -100.0

    probabilities = sigmoid_numpy(logits)[
        valid_token_mask
    ]

    true_labels = labels[
        valid_token_mask
    ].astype(np.int32)

    return probabilities, true_labels


# =============================================================================
# Metrics and thresholds
# =============================================================================

def sigmoid_numpy(x: np.ndarray) -> np.ndarray:
    """Numerically stable sigmoid."""

    x = np.clip(x, -50.0, 50.0)
    return 1.0 / (1.0 + np.exp(-x))


def make_threshold_vector(
    prediction_labels: Sequence[str],
    thresholds: Dict[str, float],
) -> np.ndarray:
    """Return thresholds in neural-output column order."""

    return np.asarray(
        [
            float(
                thresholds.get(
                    label,
                    DEFAULT_PREDICTION_THRESHOLD,
                )
            )
            for label in prediction_labels
        ],
        dtype=np.float32,
    )


def threshold_probabilities(
    probabilities: np.ndarray,
    threshold_vector: np.ndarray,
) -> np.ndarray:
    """Apply one threshold per independent feature."""

    return (
        probabilities >= threshold_vector.reshape(1, -1)
    ).astype(np.int32)


def calculate_average_metrics(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    prefix: str = "",
) -> Dict[str, float]:
    """Calculate micro and macro precision/recall/F1."""

    if y_true.shape[0] == 0:
        return {
            f"{prefix}precision_micro": 0.0,
            f"{prefix}recall_micro": 0.0,
            f"{prefix}f1_micro": 0.0,
            f"{prefix}precision_macro": 0.0,
            f"{prefix}recall_macro": 0.0,
            f"{prefix}f1_macro": 0.0,
        }

    (
        precision_micro,
        recall_micro,
        f1_micro,
        _,
    ) = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="micro",
        zero_division=0,
    )

    (
        precision_macro,
        recall_macro,
        f1_macro,
        _,
    ) = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="macro",
        zero_division=0,
    )

    return {
        f"{prefix}precision_micro": float(precision_micro),
        f"{prefix}recall_micro": float(recall_micro),
        f"{prefix}f1_micro": float(f1_micro),
        f"{prefix}precision_macro": float(precision_macro),
        f"{prefix}recall_macro": float(recall_macro),
        f"{prefix}f1_macro": float(f1_macro),
    }


def calculate_hierarchical_metrics_from_probabilities(
    probabilities: np.ndarray,
    y_true_independent: np.ndarray,
    threshold_vector: np.ndarray,
    hierarchy_matrix: np.ndarray,
    y_true_full: Optional[np.ndarray] = None,
) -> Dict[str, float]:
    """
    Report both direct neural-output metrics and complete hierarchy metrics.

    Unprefixed metrics are the COMPLETE hierarchy metrics.  During ordinary
    training/validation, complete truth can be reconstructed from the
    independent targets.  For a genuinely held-out test corpus, ``y_true_full``
    may instead be supplied directly from the source annotations so an unseen
    direct independent label is not silently erased from the gold truth.
    """

    y_pred_independent = threshold_probabilities(
        probabilities,
        threshold_vector,
    )

    if y_true_full is None:
        y_true_full = expand_binary_feature_matrix(
            y_true_independent,
            hierarchy_matrix,
        )

    if y_true_full.shape[0] != y_true_independent.shape[0]:
        raise RuntimeError(
            "Complete and independent truth matrices contain different "
            f"numbers of supervised tokens: {y_true_full.shape[0]} vs "
            f"{y_true_independent.shape[0]}."
        )

    y_pred_full = expand_binary_feature_matrix(
        y_pred_independent,
        hierarchy_matrix,
    )

    metrics = calculate_average_metrics(
        y_true_full,
        y_pred_full,
        prefix="",
    )

    metrics.update(
        calculate_average_metrics(
            y_true_independent,
            y_pred_independent,
            prefix="direct_",
        )
    )

    return metrics


def make_compute_metrics(
    prediction_labels: Sequence[str],
    hierarchy_matrix: np.ndarray,
):
    """Create Trainer metrics using the fixed default 0.5 thresholds."""

    default_thresholds = np.full(
        len(prediction_labels),
        DEFAULT_PREDICTION_THRESHOLD,
        dtype=np.float32,
    )

    def compute_metrics(eval_prediction) -> Dict[str, float]:
        logits, labels = eval_prediction

        probabilities, y_true_independent = extract_valid_token_arrays(
            logits,
            labels,
        )

        return calculate_hierarchical_metrics_from_probabilities(
            probabilities=probabilities,
            y_true_independent=y_true_independent,
            threshold_vector=default_thresholds,
            hierarchy_matrix=hierarchy_matrix,
        )

    return compute_metrics


def build_threshold_grid() -> np.ndarray:
    """Build an inclusive, stable validation threshold search grid."""

    if THRESHOLD_STEP <= 0:
        raise ValueError("THRESHOLD_STEP must be > 0.")

    if not 0.0 < THRESHOLD_MIN < 1.0:
        raise ValueError("THRESHOLD_MIN must be between 0 and 1.")

    if not 0.0 < THRESHOLD_MAX < 1.0:
        raise ValueError("THRESHOLD_MAX must be between 0 and 1.")

    if THRESHOLD_MIN > THRESHOLD_MAX:
        raise ValueError("THRESHOLD_MIN cannot exceed THRESHOLD_MAX.")

    count = int(
        round(
            (THRESHOLD_MAX - THRESHOLD_MIN)
            / THRESHOLD_STEP
        )
    ) + 1

    return np.linspace(
        THRESHOLD_MIN,
        THRESHOLD_MAX,
        count,
        dtype=np.float64,
    )


def binary_metrics_for_column(
    y_true: np.ndarray,
    y_pred: np.ndarray,
) -> Tuple[float, float, float, int]:
    """Return binary precision, recall, F1 and positive support."""

    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="binary",
        zero_division=0,
    )

    support = int(y_true.sum())

    return (
        float(precision),
        float(recall),
        float(f1),
        support,
    )


def optimise_feature_thresholds(
    probabilities: np.ndarray,
    y_true_independent: np.ndarray,
    prediction_labels: Sequence[str],
) -> Tuple[Dict[str, float], Dict[str, Dict[str, float]]]:
    """
    Optimise one sigmoid threshold per independent feature on VALIDATION ONLY.

    Objective:
        maximise that feature's binary F1.

    Stability rules:
    - If validation has no positives or no negatives for a feature, keep 0.5.
    - If several thresholds tie for best F1, choose the one closest to 0.5.
      This avoids unnecessarily extreme thresholds for flat validation curves.
    """

    grid = build_threshold_grid()

    thresholds: Dict[str, float] = {}
    diagnostics: Dict[str, Dict[str, float]] = {}

    for label_id, feature in enumerate(prediction_labels):
        y_true = y_true_independent[:, label_id]
        probs = probabilities[:, label_id]

        positive_support = int(y_true.sum())
        negative_support = int((1 - y_true).sum())

        default_pred = (
            probs >= DEFAULT_PREDICTION_THRESHOLD
        ).astype(np.int32)

        (
            default_precision,
            default_recall,
            default_f1,
            _,
        ) = binary_metrics_for_column(
            y_true,
            default_pred,
        )

        if positive_support == 0 or negative_support == 0:
            best_threshold = DEFAULT_PREDICTION_THRESHOLD
        else:
            best_f1 = -1.0
            best_candidates: List[float] = []

            for threshold in grid:
                y_pred = (probs >= threshold).astype(np.int32)

                _, _, f1, _ = binary_metrics_for_column(
                    y_true,
                    y_pred,
                )

                if f1 > best_f1 + 1e-12:
                    best_f1 = f1
                    best_candidates = [float(threshold)]
                elif abs(f1 - best_f1) <= 1e-12:
                    best_candidates.append(float(threshold))

            best_threshold = min(
                best_candidates,
                key=lambda value: (
                    abs(value - DEFAULT_PREDICTION_THRESHOLD),
                    value,
                ),
            )

        best_pred = (
            probs >= best_threshold
        ).astype(np.int32)

        (
            best_precision,
            best_recall,
            best_f1,
            _,
        ) = binary_metrics_for_column(
            y_true,
            best_pred,
        )

        thresholds[feature] = float(best_threshold)

        diagnostics[feature] = {
            "threshold": float(best_threshold),
            "support": positive_support,
            "negative_support": negative_support,
            "precision_default": default_precision,
            "recall_default": default_recall,
            "f1_default": default_f1,
            "precision_optimised": best_precision,
            "recall_optimised": best_recall,
            "f1_optimised": best_f1,
            "f1_change": best_f1 - default_f1,
        }

    return thresholds, diagnostics


# =============================================================================
# Dataset diagnostics and validation
# =============================================================================

def count_feature_occurrences(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    sentence_indices: Sequence[int],
    independent_only: bool = False,
) -> Counter:
    """Count complete or independent positive labels in a split."""

    counts: Counter = Counter()

    for sentence_index in sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            if independent_only:
                features = get_independent_record_features(record)
            else:
                features = clean_features(record)

            for feature in features:
                counts[feature] += 1

    return counts


def count_empty_records(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    sentence_indices: Sequence[int],
) -> int:
    """Count NOUN/PROPN records having no complete feature tags."""

    count = 0

    for sentence_index in sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            if not clean_features(record):
                count += 1

    return count


def verify_full_label_coverage(
    full_labels: Sequence[str],
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
) -> None:
    """Ensure validation contains no complete label unseen in training."""

    training_labels = set(full_labels)

    for split_name in ("validation",):
        tagged_records, sentence_indices = split_sources[split_name]
        observed: Set[str] = set()

        for sentence_index in sentence_indices:
            for record in tagged_records.get(sentence_index, {}).values():
                observed.update(clean_features(record))

        unknown = observed - training_labels

        if unknown:
            raise RuntimeError(
                f"{split_name} contains full labels unseen in training: "
                f"{sorted(unknown)}"
            )


def verify_prediction_label_coverage(
    prediction_labels: Sequence[str],
    split_sources: Dict[
        str, Tuple[Dict[int, Dict[int, Dict[str, Any]]], Sequence[int]]
    ],
) -> None:
    """Require every validation independent target to occur in training."""

    training_labels = set(prediction_labels)
    records, indices = split_sources["validation"]
    observed = {
        feature
        for sentence_index in indices
        for record in records.get(sentence_index, {}).values()
        for feature in get_independent_record_features(record)
    }
    unknown = observed - training_labels
    if unknown:
        raise RuntimeError(
            "Validation contains independent targets without a training "
            f"output head: {sorted(unknown)}"
        )


def verify_hierarchy_closure(
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
) -> None:
    """
    Ensure source feature sets already contain all ancestors required by the
    hierarchy. This prevents evaluation against inconsistent source targets.
    """

    problems: List[str] = []
    max_examples = 20

    for split_name in ("train", "validation"):
        tagged_records, sentence_indices = split_sources[split_name]
        problem_count = 0

        for sentence_index in sentence_indices:
            for token_id, record in tagged_records.get(
                sentence_index,
                {},
            ).items():
                features = clean_features(record)

                if not features:
                    continue

                missing = missing_hierarchy_features(features)

                if not missing:
                    continue

                problem_count += 1

                if len(problems) < max_examples:
                    problems.append(
                        f"{split_name}: sentence={sentence_index}, "
                        f"token={token_id}, "
                        f"form={record.get('form')!r}, "
                        f"missing={sorted(missing)}"
                    )

        if problem_count:
            print(
                f"Hierarchy closure problems in {split_name}: "
                f"{problem_count:,} token(s)"
            )

    if problems:
        example_text = "\n".join(
            f"  - {problem}"
            for problem in problems
        )

        raise RuntimeError(
            "The input dataset is not hierarchy-closed. Fix the source tags "
            "before training so deterministic reduction/expansion is exact.\n"
            f"Examples:\n{example_text}"
        )


def print_split_statistics(
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
) -> None:
    print("=" * 80)
    print("DATASET SPLIT")
    print("=" * 80)

    for split_name in ("train", "validation"):
        tagged_records, indices = split_sources[split_name]

        full_counts = count_feature_occurrences(
            tagged_records,
            indices,
            independent_only=False,
        )

        independent_counts = count_feature_occurrences(
            tagged_records,
            indices,
            independent_only=True,
        )

        empty_count = count_empty_records(
            tagged_records,
            indices,
        )

        noun_count = sum(
            len(tagged_records.get(index, {}))
            for index in indices
        )

        source_name = (
            "training file"
            if split_name in {"train", "validation"}
            else "test file"
        )

        print(
            f"{split_name:12s}: "
            f"{len(indices):,} sentences | "
            f"{noun_count:,} NOUN/PROPN tokens | "
            f"{sum(full_counts.values()):,} complete positives -> "
            f"{sum(independent_counts.values()):,} independent positives | "
            f"{empty_count:,} empty-feature tokens excluded | "
            f"source={source_name}"
        )

    print()


def print_prediction_label_statistics(
    prediction_labels: Sequence[str],
    full_labels: Sequence[str],
    train_tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    train_sentence_indices: Sequence[int],
) -> None:
    """Show which labels are neural outputs versus deterministic-only parents."""

    train_independent_counts = count_feature_occurrences(
        train_tagged_records,
        train_sentence_indices,
        independent_only=True,
    )

    prediction_set = set(prediction_labels)
    deterministic_only = [
        feature
        for feature in full_labels
        if feature not in prediction_set
    ]

    print("=" * 80)
    print("NEURAL OUTPUT FEATURES")
    print("=" * 80)
    print(
        f"Complete evaluation features: {len(full_labels)}"
    )
    print(
        f"Independent neural outputs: {len(prediction_labels)}"
    )
    print(
        f"Deterministic-only features in this training split: "
        f"{len(deterministic_only)}"
    )
    print()

    print(
        f"{'Feature':35s} "
        f"{'Independent train support':>26s}"
    )
    print("-" * 64)

    for feature in prediction_labels:
        print(
            f"{feature:35s} "
            f"{train_independent_counts[feature]:26d}"
        )

    if deterministic_only:
        print()
        print("Deterministic-only in this split:")

        for feature in deterministic_only:
            print(f"  - {feature}")

    print()


def make_json_serialisable(value: Any) -> Any:
    """Recursively convert NumPy scalars/arrays to ordinary JSON values."""

    if isinstance(value, dict):
        return {
            str(key): make_json_serialisable(item)
            for key, item in value.items()
        }

    if isinstance(value, (list, tuple)):
        return [
            make_json_serialisable(item)
            for item in value
        ]

    if isinstance(value, np.ndarray):
        return value.tolist()

    if isinstance(value, (np.floating, np.integer)):
        return value.item()

    return value


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    validate_feature_hierarchy()
    check_cuda()

    if not LEARNING_RATES or not PER_DEVICE_TRAIN_BATCH_SIZES or not EFFECTIVE_BATCH_SIZES:
        raise ValueError("All hyperparameter grid lists must be non-empty.")
    if any(lr <= 0 for lr in LEARNING_RATES):
        raise ValueError("Learning rates must be positive.")

    n_devices = torch.cuda.device_count()
    if n_devices < 1:
        raise RuntimeError("At least one CUDA device is required.")

    grid = []
    for lr, device_batch, effective_batch in product(
        LEARNING_RATES, PER_DEVICE_TRAIN_BATCH_SIZES, EFFECTIVE_BATCH_SIZES
    ):
        denominator = device_batch * n_devices
        if device_batch <= 0 or effective_batch <= 0 or effective_batch % denominator:
            raise ValueError(
                "Each effective batch size must be a positive multiple of "
                "per-device batch size times the number of CUDA devices: "
                f"device_batch={device_batch}, effective_batch={effective_batch}, "
                f"CUDA devices={n_devices}."
            )
        grid.append((lr, device_batch, effective_batch,
                     effective_batch // denominator))
    if len(grid) != len(set(grid)):
        raise ValueError("The hyperparameter grid contains duplicate configurations.")

    print("=" * 80)
    print("VALIDATION-ONLY HYPERPARAMETER GRID SEARCH")
    print("=" * 80)
    print(f"Configurations: {len(grid)} | fine-tuning seed: {TUNING_SEED}")
    print(f"CUDA devices: {n_devices}")
    print("Selection metric: hierarchy-expanded validation macro F1 at threshold 0.5")
    print("The official test corpus is not read during this search.\n")

    train_sentences = load_conllu(TRAIN_CONLLU_PATH)
    train_tagged_records = load_tagged_records(TRAIN_JSONL_PATH)
    validate_feature_switches(train_tagged_records)

    eligible_indices = get_eligible_sentence_indices(
        train_sentences, train_tagged_records
    )
    split = make_train_validation_split(eligible_indices, train_tagged_records)
    train_indices = split["train"]
    validation_indices = split["validation"]
    sources = {
        "train": (train_tagged_records, train_indices),
        "validation": (train_tagged_records, validation_indices),
    }
    split_document = {
        "split_unit": "sentence",
        "stratification": "iterative_multilabel_sentence_presence",
        "split_seed_requested": SPLIT_SEED,
        "split_seed_used": split["split_seed_used"],
        "split_attempt": split["attempt"],
        "validation_fraction": VALIDATION_FRACTION,
        "feature_switches": dict(sorted(FEATURE_SWITCHES.items())),
        "prevalence_error": split["prevalence_error"],
        "stratification_labels": split["stratification_labels"],
        "train_jsonl": str(TRAIN_JSONL_PATH),
        "train_conllu": str(TRAIN_CONLLU_PATH),
        "index_spaces": {"train": "training corpus", "validation": "training corpus"},
        "train": train_indices,
        "validation": validation_indices,
    }
    with SPLIT_PATH.open("w", encoding="utf-8") as handle:
        json.dump(make_json_serialisable(split_document), handle,
                  ensure_ascii=False, indent=2)

    verify_hierarchy_closure(sources)
    full_labels = build_full_label_vocabulary(train_tagged_records, train_indices)
    prediction_labels = build_prediction_label_vocabulary(
        train_tagged_records, train_indices
    )
    verify_full_label_coverage(full_labels, sources)
    verify_prediction_label_coverage(prediction_labels, sources)

    label2id = {label: index for index, label in enumerate(prediction_labels)}
    id2label = {index: label for label, index in label2id.items()}
    hierarchy_matrix = build_hierarchy_expansion_matrix(
        prediction_labels, full_labels
    )
    label_document = {
        "labels": prediction_labels,
        "label2id": label2id,
        "id2label": {str(key): value for key, value in id2label.items()},
        "prediction_labels": prediction_labels,
        "prediction_label2id": label2id,
        "full_labels": full_labels,
        "full_label2id": {label: index for index, label in enumerate(full_labels)},
        "feature_parents": {
            child: sorted(parents) for child, parents in sorted(FEATURE_PARENTS.items())
        },
        "target_representation": "per_token_independent_features",
        "split_unit": "sentence",
        "feature_switches": dict(sorted(FEATURE_SWITCHES.items())),
        "disabled_features": sorted(
            feature for feature, enabled in FEATURE_SWITCHES.items() if not enabled
        ),
    }
    with LABELS_PATH.open("w", encoding="utf-8") as handle:
        json.dump(label_document, handle, ensure_ascii=False, indent=2)

    print_split_statistics(sources)
    print_prediction_label_statistics(
        prediction_labels, full_labels, train_tagged_records, train_indices
    )

    tokenizer = AutoTokenizer.from_pretrained(
        MODEL_NAME, use_fast=True, add_prefix_space=True
    )
    train_dataset = SemanticFeatureDataset(
        sentences=train_sentences,
        sentence_indices=train_indices,
        tagged_records=train_tagged_records,
        tokenizer=tokenizer,
        label2id=label2id,
        max_length=MAX_LENGTH,
    )
    validation_dataset = SemanticFeatureDataset(
        sentences=train_sentences,
        sentence_indices=validation_indices,
        tagged_records=train_tagged_records,
        tokenizer=tokenizer,
        label2id=label2id,
        max_length=MAX_LENGTH,
    )
    collator = MultiLabelTokenCollator(
        tokenizer=tokenizer, num_labels=len(prediction_labels)
    )
    use_bf16 = torch.cuda.is_bf16_supported()
    results = []
    work_root = OUTPUT_DIR / "_grid_trainer_work"
    work_root.mkdir(parents=True, exist_ok=True)

    def save_results() -> None:
        # A partial result survives a later interrupted or out-of-memory trial.
        ranked = sorted(
            results,
            key=lambda row: (-row["validation_f1_macro_at_0_5"],
                             -row["validation_f1_micro_at_0_5"], row["trial"]),
        )
        document = {
            "model": MODEL_NAME,
            "selection_data": "validation_only",
            "official_test_evaluated": False,
            "selection_metric": "hierarchy_expanded_validation_f1_macro_at_0_5",
            "tie_breaker": "validation_f1_micro_at_0_5_then_grid_order",
            "training_seed": TUNING_SEED,
            "split_seed": split["split_seed_used"],
            "epochs": NUM_EPOCHS,
            "cuda_devices": n_devices,
            "feature_switches": dict(sorted(FEATURE_SWITCHES.items())),
            "grid_size": len(grid),
            "completed_trials": len(results),
            "best": ranked[0] if ranked else None,
            "results_ranked": ranked,
        }
        with GRID_RESULTS_PATH.open("w", encoding="utf-8") as handle:
            json.dump(make_json_serialisable(document), handle,
                      ensure_ascii=False, indent=2)
        columns = [
            "rank", "trial", "learning_rate", "per_device_train_batch_size",
            "gradient_accumulation_steps", "effective_batch_size",
            "training_seed", "best_epoch",
            "best_epoch_validation_f1_macro_at_0_5",
            "validation_f1_macro_at_0_5", "validation_f1_micro_at_0_5",
            "validation_f1_macro_calibrated_diagnostic",
            "validation_f1_micro_calibrated_diagnostic",
        ]
        with GRID_CSV_PATH.open("w", encoding="utf-8", newline="") as handle:
            writer = csv.DictWriter(handle, fieldnames=columns)
            writer.writeheader()
            for rank, row in enumerate(ranked, start=1):
                writer.writerow({name: rank if name == "rank" else row.get(name)
                                 for name in columns})

    for trial, (lr, device_batch, effective_batch, accumulation) in enumerate(
        grid, start=1
    ):
        print("\n" + "=" * 80)
        print(f"TRIAL {trial}/{len(grid)}: LR={lr:g}, device batch={device_batch}, "
              f"accumulation={accumulation}, effective batch={effective_batch}")
        print("=" * 80)
        set_seed(TUNING_SEED)
        work_dir = work_root / f"trial_{trial:02d}"
        if work_dir.exists():
            shutil.rmtree(work_dir)

        model = RobertaMultiLabelModel(
            model_name=MODEL_NAME,
            num_labels=len(prediction_labels),
            id2label=id2label,
            label2id=label2id,
        )
        args = TrainingArguments(
            output_dir=str(work_dir),
            learning_rate=lr,
            lr_scheduler_type="linear",
            weight_decay=WEIGHT_DECAY,
            per_device_train_batch_size=device_batch,
            per_device_eval_batch_size=EVAL_BATCH_SIZE,
            gradient_accumulation_steps=accumulation,
            num_train_epochs=NUM_EPOCHS,
            eval_strategy=EVAL_STRATEGY,
            save_strategy="epoch",
            logging_strategy="steps",
            logging_steps=50,
            load_best_model_at_end=True,
            metric_for_best_model="f1_macro",
            greater_is_better=True,
            save_total_limit=2,
            bf16=use_bf16,
            fp16=not use_bf16,
            dataloader_num_workers=4,
            dataloader_pin_memory=True,
            optim="adamw_torch",
            report_to="none",
            seed=TUNING_SEED,
            data_seed=TUNING_SEED,
            remove_unused_columns=False,
            eval_accumulation_steps=16,
        )
        trainer = Trainer(
            model=model,
            args=args,
            train_dataset=train_dataset,
            eval_dataset=validation_dataset,
            processing_class=tokenizer,
            data_collator=collator,
            compute_metrics=make_compute_metrics(
                prediction_labels, hierarchy_matrix
            ),
        )
        trainer.train()
        validation_output = trainer.predict(
            validation_dataset, metric_key_prefix="validation"
        )
        probabilities, true_independent = extract_valid_token_arrays(
            validation_output.predictions, validation_output.label_ids
        )
        default_thresholds = np.full(
            len(prediction_labels), DEFAULT_PREDICTION_THRESHOLD,
            dtype=np.float32,
        )
        default_metrics = calculate_hierarchical_metrics_from_probabilities(
            probabilities=probabilities,
            y_true_independent=true_independent,
            threshold_vector=default_thresholds,
            hierarchy_matrix=hierarchy_matrix,
        )
        calibrated_thresholds, _ = optimise_feature_thresholds(
            probabilities=probabilities,
            y_true_independent=true_independent,
            prediction_labels=prediction_labels,
        )
        calibrated_metrics = calculate_hierarchical_metrics_from_probabilities(
            probabilities=probabilities,
            y_true_independent=true_independent,
            threshold_vector=make_threshold_vector(
                prediction_labels, calibrated_thresholds
            ),
            hierarchy_matrix=hierarchy_matrix,
        )
        best_metric = trainer.state.best_metric
        best_checkpoint = trainer.state.best_model_checkpoint
        best_epoch = None
        if best_checkpoint:
            for entry in trainer.state.log_history:
                if "eval_f1_macro" in entry and "step" in entry:
                    # The best checkpoint's step is encoded in its directory.
                    if best_checkpoint.endswith(f"checkpoint-{entry['step']}"):
                        best_epoch = entry.get("epoch")
                        break

        row = {
            "trial": trial,
            "learning_rate": lr,
            "per_device_train_batch_size": device_batch,
            "gradient_accumulation_steps": accumulation,
            "effective_batch_size": effective_batch,
            "training_seed": TUNING_SEED,
            "best_epoch": best_epoch,
            "best_epoch_validation_f1_macro_at_0_5": best_metric,
            "validation_f1_macro_at_0_5": default_metrics["f1_macro"],
            "validation_f1_micro_at_0_5": default_metrics["f1_micro"],
            "validation_f1_macro_calibrated_diagnostic": calibrated_metrics["f1_macro"],
            "validation_f1_micro_calibrated_diagnostic": calibrated_metrics["f1_micro"],
            "validation_metrics_at_0_5": default_metrics,
            "validation_metrics_calibrated_diagnostic": calibrated_metrics,
            "calibrated_thresholds_diagnostic": calibrated_thresholds,
        }
        results.append(row)
        save_results()
        print(f"Validation macro F1 @ 0.5: {row['validation_f1_macro_at_0_5']:.4f}")
        print(f"Validation micro F1 @ 0.5: {row['validation_f1_micro_at_0_5']:.4f}")
        print(f"Results saved: {GRID_RESULTS_PATH.resolve()}")

        del validation_output, trainer, model
        gc.collect()
        torch.cuda.empty_cache()
        if work_dir.exists():
            shutil.rmtree(work_dir)

    if work_root.exists() and not any(work_root.iterdir()):
        work_root.rmdir()

    print("\n" + "=" * 80)
    print("GRID SEARCH RANKING (VALIDATION ONLY)")
    print("=" * 80)
    ranked = sorted(
        results,
        key=lambda row: (-row["validation_f1_macro_at_0_5"],
                         -row["validation_f1_micro_at_0_5"], row["trial"]),
    )
    print(f"{'Rank':>4} {'LR':>10} {'Device':>7} {'Accum':>7} "
          f"{'Effective':>9} {'Macro F1':>10} {'Micro F1':>10}")
    for rank, row in enumerate(ranked, start=1):
        print(f"{rank:4d} {row['learning_rate']:10.1e} "
              f"{row['per_device_train_batch_size']:7d} "
              f"{row['gradient_accumulation_steps']:7d} "
              f"{row['effective_batch_size']:9d} "
              f"{row['validation_f1_macro_at_0_5']:10.4f} "
              f"{row['validation_f1_micro_at_0_5']:10.4f}")
    print(f"\nBest candidate: LR={ranked[0]['learning_rate']:g}, "
          f"device batch={ranked[0]['per_device_train_batch_size']}, "
          f"accumulation={ranked[0]['gradient_accumulation_steps']}, "
          f"effective batch={ranked[0]['effective_batch_size']}")
    print("Use these settings for the separate 30-seed experiment; "
          "this single-seed ranking is provisional.")
    print(f"JSON: {GRID_RESULTS_PATH.resolve()}")
    print(f"CSV:  {GRID_CSV_PATH.resolve()}")


if __name__ == "__main__":
    main()

================================================================================
CUDA
================================================================================
PyTorch version: 2.13.0+cu130
CUDA available: True
CUDA runtime: 13.0
GPU: NVIDIA GeForce RTX 5070 Ti
VRAM: 15.92 GiB

================================================================================
VALIDATION-ONLY HYPERPARAMETER GRID SEARCH
================================================================================
Configurations: 16 | fine-tuning seed: 11
CUDA devices: 1
Selection metric: hierarchy-expanded validation macro F1 at threshold 0.5
The official test corpus is not read during this search.

================================================================================
FEATURE SWITCHES
================================================================================
Disabled features: Rigidity, Shape, State, State_of_Matter
All unlisted features are enabled.


Sentence-level multilabel-stratified train/validation split:
  Eligible training sentences : 11,198
  Target validation sentences : 2,240
  Actual validation sentences : 2,313
  Training sentences retained : 8,885
  Split seed used             : 42
  Stratification labels       : 37
  Coverage-rejected attempts  : 0
  Mean relative prevalence error: 0.008441

Feature                              All sent.      Train      Valid    Valid %
--------------------------------------------------------------------------------
Abstract                                  4469       3575        894      0.200
Animal                                     621        497        124      0.200
Animate                                     52         42         10      0.192
Artefact                                  1778       1422        356      0.200
Body_Part                                  265        212         53      0.200
Comestible                                 534        427        107      0.200
Communication                             1984       1587        397      0.200
Currency                                   197        158         39      0.198
Duration                                  1338       1070        268      0.200
Elongated                                  649        519        130      0.200
Eventive                                  3749       2999        750      0.200
Feminine                                   733        586        147      0.201
Fluid                                       87         70         17      0.195
Garment                                     62         50         12      0.194
Inanimate                                 4282       3425        857      0.200
Internal_Control                           107         86         21      0.196
Language                                    27         22          5      0.185
Location                                  3232       2585        647      0.200
Machine                                    694        555        139      0.200
Masculine                                 1829       1463        366      0.200
Natural                                    326        261         65      0.199
Natural_Force                              142        114         28      0.197
Non_Rigid                                 1200        960        240      0.200
Organisation                              3003       2402        601      0.200
Plant                                       66         53         13      0.197
Point_in_Time                             1211        969        242      0.200
Pointy                                      82         66         16      0.195
Question                                   161        129         32      0.199
Rigid                                     1965       1572        393      0.200
Solid                                     4618       3694        924      0.200
Sound                                      187        150         37      0.198
Statement                                 1115        892        223      0.200
Substance                                  826        661        165      0.200
Time                                        81         65         16      0.198
Unspecified_Gender_or_Neuter              2592       2074        518      0.200
Vehicle                                    344        275         69      0.201
Web_Location                               252        202         50      0.198

Actual validation sentence fraction: 0.2066

================================================================================
DATASET SPLIT
================================================================================
train       : 8,885 sentences | 37,581 NOUN/PROPN tokens | 124,956 complete positives -> 54,319 independent positives | 2,686 empty-feature tokens excluded | source=training file
validation  : 2,313 sentences | 9,408 NOUN/PROPN tokens | 31,274 complete positives -> 13,650 independent positives | 675 empty-feature tokens excluded | source=training file

================================================================================
NEURAL OUTPUT FEATURES
================================================================================
Complete evaluation features: 39
Independent neural outputs: 37
Deterministic-only features in this training split: 2

Feature                              Independent train support
----------------------------------------------------------------
Abstract                                                  5754
Animal                                                     691
Animate                                                     46
Artefact                                                  1866
Body_Part                                                  318
Comestible                                                 671
Communication                                             2041
Currency                                                   179
Duration                                                  1393
Elongated                                                  632
Eventive                                                  4258
Feminine                                                   867
Fluid                                                       84
Garment                                                     60
Inanimate                                                 5851
Internal_Control                                            91
Language                                                    23
Location                                                  4733
Machine                                                    738
Masculine                                                 2684
Natural                                                    307
Natural_Force                                              130
Non_Rigid                                                 1378
Organisation                                              4425
Plant                                                       68
Point_in_Time                                             1257
Pointy                                                      78
Question                                                   130
Rigid                                                     2165
Solid                                                     5807
Sound                                                      169
Statement                                                 1038
Substance                                                  913
Time                                                        67
Unspecified_Gender_or_Neuter                              2826
Vehicle                                                    359
Web_Location                                               222

Deterministic-only in this split:
  - Concrete
  - Human


================================================================================
TRIAL 1/16: LR=2.5e-05, device batch=4, accumulation=4, effective batch=16
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 953.48it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8877
Validation micro F1 @ 0.5: 0.9352
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 2/16: LR=2.5e-05, device batch=4, accumulation=8, effective batch=32
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 958.34it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8655
Validation micro F1 @ 0.5: 0.9300
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 3/16: LR=2.5e-05, device batch=8, accumulation=2, effective batch=16
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 917.13it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8880
Validation micro F1 @ 0.5: 0.9352
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 4/16: LR=2.5e-05, device batch=8, accumulation=4, effective batch=32
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 931.25it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8815
Validation micro F1 @ 0.5: 0.9335
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 5/16: LR=3e-05, device batch=4, accumulation=4, effective batch=16
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 995.80it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8897
Validation micro F1 @ 0.5: 0.9339
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 6/16: LR=3e-05, device batch=4, accumulation=8, effective batch=32
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 982.56it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8775
Validation micro F1 @ 0.5: 0.9319
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 7/16: LR=3e-05, device batch=8, accumulation=2, effective batch=16
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 952.91it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.9001
Validation micro F1 @ 0.5: 0.9365
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 8/16: LR=3e-05, device batch=8, accumulation=4, effective batch=32
================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1005.93it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8799
Validation micro F1 @ 0.5: 0.9343
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 9/16: LR=3.5e-05, device batch=4, accumulation=4, effective batch=16
================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1006.39it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8951
Validation micro F1 @ 0.5: 0.9341
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 10/16: LR=3.5e-05, device batch=4, accumulation=8, effective batch=32
================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1015.64it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8842
Validation micro F1 @ 0.5: 0.9330
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 11/16: LR=3.5e-05, device batch=8, accumulation=2, effective batch=16
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 936.55it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.9061
Validation micro F1 @ 0.5: 0.9394
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 12/16: LR=3.5e-05, device batch=8, accumulation=4, effective batch=32
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 971.20it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8832
Validation micro F1 @ 0.5: 0.9341
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 13/16: LR=4e-05, device batch=4, accumulation=4, effective batch=16
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 898.98it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.9039
Validation micro F1 @ 0.5: 0.9376
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 14/16: LR=4e-05, device batch=4, accumulation=8, effective batch=32
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 955.18it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8909
Validation micro F1 @ 0.5: 0.9353
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 15/16: LR=4e-05, device batch=8, accumulation=2, effective batch=16
================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1040.93it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.0000
Validation micro F1 @ 0.5: 0.0000
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 16/16: LR=4e-05, device batch=8, accumulation=4, effective batch=32
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 911.92it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8931
Validation micro F1 @ 0.5: 0.9363
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
GRID SEARCH RANKING (VALIDATION ONLY)
================================================================================
Rank         LR  Device   Accum Effective   Macro F1   Micro F1
   1    3.5e-05       8       2        16     0.9061     0.9394
   2    4.0e-05       4       4        16     0.9039     0.9376
   3    3.0e-05       8       2        16     0.9001     0.9365
   4    3.5e-05       4       4        16     0.8951     0.9341
   5    4.0e-05       8       4        32     0.8931     0.9363
   6    4.0e-05       4       8        32     0.8909     0.9353
   7    3.0e-05       4       4        16     0.8897     0.9339
   8    2.5e-05       8       2        16     0.8880     0.9352
   9    2.5e-05       4       4        16     0.8877     0.9352
  10    3.5e-05       4       8        32     0.8842     0.9330
  11    3.5e-05       8       4        32     0.8832     0.9341
  12    2.5e-05       8       4        32     0.8815     0.9335
  13    3.0e-05       8       4        32     0.8799     0.9343
  14    3.0e-05       4       8        32     0.8775     0.9319
  15    2.5e-05       4       8        32     0.8655     0.9300
  16    4.0e-05       8       2        16     0.0000     0.0000

Best candidate: LR=3.5e-05, device batch=8, accumulation=2, effective batch=16
Use these settings for the separate 30-seed experiment; this single-seed ranking is provisional.
JSON: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json
CSV:  /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.csv