<h1>Fine tuning</h1>

In [1]:
#!/usr/bin/env python3
"""
Fine-tune RoBERTa for hierarchical multi-label semantic feature tagging of
NOUN/PROPN tokens.

Compatible with Python 3.9.21.

Key design changes
------------------
1. The model is trained only on independent semantic features. For each token,
   any feature that can be inherited from a more specific present feature is
   removed from the neural target. This is a per-token reduction rather than a
   global "terminal leaf only" rule, so features such as Human, Time, Shape,
   Communication, etc. can still be predicted directly when they are the most
   specific available feature for that token.

2. All inherited features are reconstructed deterministically from
   FEATURE_PARENTS for validation, testing, reporting, and later inference.

3. A separate sigmoid threshold is optimised for every neural output using the
   validation split only. The selected thresholds are frozen before the test
   split is evaluated and are saved to prediction_thresholds.json.

4. Train/validation splitting is performed at SENTENCE level with iterative
   multilabel stratification over sentence-level independent-feature presence.
   The split is fixed across repeated fine-tuning runs.

5. Fine-tuning is repeated over a predeclared list of random seeds. The same
   split is used for every run, and results are summarised with mean and SD.

6. The official test corpus may contain a direct independent target that never
   occurred independently in training. Such a label is never added from test
   data. Complete test truth is read directly from source annotations.

7. Held-out test uncertainty is estimated with a SENTENCE-CLUSTER bootstrap.
   All supervised noun/proper-noun targets from a sampled sentence move together.

Tagged data:
    Training/validation:
        ewt_train_wordnet_wsd_features_wordnet_fixed.jsonl
    Test:
        ewt_test_wordnet_wsd_features_wordnet_fixed.jsonl

Sentence/token sources:
    Training/validation:
        UD_English-EWT-master/
        UD_English-EWT-master/
        en_ewt-ud-train.conllu
    Test:
        UD_English-EWT-master/
        UD_English-EWT-master/
        en_ewt-ud-test.conllu

The validation split is created only from the training corpus. The official
test corpus remains untouched until final evaluation.

Loss:
    BCEWithLogitsLoss over INDEPENDENT feature labels only.

Headline metrics:
    Computed after deterministic hierarchy expansion, so they describe the
    complete semantic feature sets rather than only the neural outputs.

Requirements:
    python -m pip install torch transformers datasets accelerate conllu scikit-learn iterative-stratification

CUDA is required.
"""

from __future__ import annotations

import gc
import json
import shutil
from collections import Counter, defaultdict
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Set, Tuple

import numpy as np
import torch
import torch.nn as nn

from conllu import parse_incr
from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit
from sklearn.metrics import precision_recall_fscore_support
from torch.utils.data import Dataset

from transformers import (
    AutoModelForTokenClassification,
    AutoTokenizer,
    Trainer,
    TrainingArguments,
    set_seed,
)


# =============================================================================
# Configuration
# =============================================================================

TRAIN_JSONL_PATH = Path(
    "../data/ewt_train_wordnet_wsd_features_wordnet_fixed.jsonl"
    #"ewt_train_wordnet_wsd_features_fully_tagged_llm_reviewed.jsonl"
)

TEST_JSONL_PATH = Path(
    "../data/ewt_test_wordnet_wsd_features_wordnet_fixed.jsonl"
    #"ewt_test_wordnet_wsd_features_fully_tagged_llm_reviewed.jsonl"
)

TRAIN_CONLLU_PATH = Path(
    "../data/UD_English-EWT-master/"
    "UD_English-EWT-master/"
    "en_ewt-ud-train.conllu"
)

TEST_CONLLU_PATH = Path(
    "../data/UD_English-EWT-master/"
    "UD_English-EWT-master/"
    "en_ewt-ud-test.conllu"
)

# MODEL_NAME = "FacebookAI/roberta-base"
MODEL_NAME = "FacebookAI/roberta-large"

OUTPUT_DIR = Path("../models/roberta_semantic_features")

# Validation is sampled only from eligible TRAINING sentences.
# Stratification is performed at SENTENCE level using the multilabel feature
# presence vector for each sentence. The separate official test file is never
# split and is used only for final evaluation.
VALIDATION_FRACTION = 0.20

# Fixed seed used ONLY to create the sentence-level train/validation split.
# Keeping this fixed across model runs means repeated runs measure stochastic
# fine-tuning variation rather than variation in the validation partition.
SPLIT_SEED = 42

# Repeated fine-tuning seeds. Use the same list when comparing model variants.
# Thirty runs follow the experiment-design recommendation; reduce this list if
# RoBERTa-large makes 30 runs computationally impractical, and report the actual
# number used.
RUN_SEEDS = [
    11, 23, 37, 53, 71, 89, 107, 127, 149, 173,
    197, 223, 251, 281, 313, 347, 383, 421, 461, 503,
    547, 593, 641, 691, 743, 797, 853, 911, 971, 1031,
]

# RUN_SEEDS = [
#     11
# ]

# The multilabel stratifier is retried with deterministic derived seeds until
# every independent feature still has at least this many positive token targets
# in the TRAIN subset. This prevents a rare direct target from disappearing.
MIN_TRAIN_POSITIVES_PER_FEATURE = 1
MAX_STRATIFICATION_ATTEMPTS = 200

# Sentence-cluster bootstrap for uncertainty in the held-out test sample.
# The same sampled test sentences are used for every run within each bootstrap
# replicate, and the statistic is the mean metric across run seeds.
TEST_BOOTSTRAP_SAMPLES = 1700
TEST_BOOTSTRAP_CONFIDENCE = 0.95
TEST_BOOTSTRAP_SEED = 20260926

# Saving 30 RoBERTa-large models would use a great deal of disk space. The first
# run is therefore saved as a neutral REFERENCE model; it is not selected for
# having the best test result. Metrics and thresholds are saved for every run.
SAVE_REFERENCE_MODEL = True

MAX_LENGTH = 256

LEARNING_RATE = 4.0e-05
LEARNING_RATE_SCHEDULER = "linear"
WEIGHT_DECAY = 0.01
# WARMUP_STEPS=166
WARMUP_STEPS=278
TRAIN_BATCH_SIZE = 4
EVAL_BATCH_SIZE = 16

GRADIENT_ACCUMULATION_STEPS = 4

NUM_EPOCHS = 5

# Threshold used during epoch-by-epoch Trainer evaluation. Final thresholds are
# optimised per independent feature on the validation set after training.
DEFAULT_PREDICTION_THRESHOLD = 0.5

# Validation-only threshold search grid.
THRESHOLD_MIN = 0.05
THRESHOLD_MAX = 0.95
THRESHOLD_STEP = 0.01

# Only these POS categories receive feature supervision.
TARGET_POS = {"NOUN", "PROPN"}

# A NOUN/PROPN with no features is considered a failed source annotation rather
# than a valid all-negative target.
EXCLUDE_EMPTY_FEATURE_RECORDS = True

# Optional per-feature switches. Any feature not listed here is enabled.
# Set a feature to False to remove it from:
#   - sentence-level stratification,
#   - neural training targets,
#   - threshold calibration,
#   - hierarchy-expanded gold/predicted feature sets,
#   - per-feature and aggregate evaluation, and
#   - the sentence-cluster bootstrap.
#
# Disabled intermediate hierarchy nodes are skipped but their enabled ancestors
# are still inherited. For example, if Human were disabled, Feminine would still
# inherit Animate/Natural/Concrete/Internal_Control via the hierarchy.
FEATURE_SWITCHES: Dict[str, bool] = {
    "State": False,
    "State_of_Matter": False,
    "Shape": False,
    "Rigidity": False,
}

# Aggregate per-feature test tables are always printed after all repeated runs.
# Set this to True only if you also want the two full per-feature tables printed
# after EVERY run (very verbose for 30 runs).
PRINT_PER_RUN_FEATURE_TABLES = False

EVAL_STRATEGY = "epoch"

SPLIT_PATH = OUTPUT_DIR / "sentence_split.json"
LABELS_PATH = OUTPUT_DIR / "semantic_features.json"
RUNS_DIR = OUTPUT_DIR / "runs"
REFERENCE_MODEL_DIR = OUTPUT_DIR / "reference_model"
REPEATED_RESULTS_PATH = OUTPUT_DIR / "repeated_run_results.json"
BOOTSTRAP_RESULTS_PATH = OUTPUT_DIR / "test_bootstrap_confidence_intervals.json"


# =============================================================================
# Feature hierarchy
# =============================================================================

def is_feature_enabled(feature: str) -> bool:
    """Return whether *feature* participates in this experiment."""

    return bool(FEATURE_SWITCHES.get(feature, True))


def validate_feature_switches(
    train_tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    test_tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> None:
    """Fail early on misspelled feature-switch names and report disabled labels."""

    observed: Set[str] = set()

    for source in (train_tagged_records, test_tagged_records):
        for sentence_records in source.values():
            for record in sentence_records.values():
                raw = record.get("features", [])
                if isinstance(raw, list):
                    observed.update(
                        str(feature).strip()
                        for feature in raw
                        if str(feature).strip()
                    )

    known = set(observed) | set(FEATURE_PARENTS)
    for parents in FEATURE_PARENTS.values():
        known.update(parents)

    unknown = sorted(set(FEATURE_SWITCHES) - known)
    if unknown:
        raise ValueError(
            "FEATURE_SWITCHES contains unknown feature name(s): "
            + ", ".join(unknown)
        )

    disabled = sorted(
        feature for feature, enabled in FEATURE_SWITCHES.items() if not enabled
    )

    print("=" * 80)
    print("FEATURE SWITCHES")
    print("=" * 80)
    if disabled:
        print("Disabled features: " + ", ".join(disabled))
    else:
        print("Disabled features: none")
    print("All unlisted features are enabled.")
    print()


# child -> direct parent(s)
FEATURE_PARENTS: Dict[str, Set[str]] = {
    "Organisation": {
        "Internal_Control",
        "Abstract",
    },
    "Natural_Force": {
        "Internal_Control",
    },
    "Animate": {
        "Internal_Control",
        "Natural",
    },
    "Human": {
        "Animate",
    },
    "Feminine": {
        "Human",
    },
    "Masculine": {
        "Human",
    },
    "Unspecified_Gender_or_Neuter": {
        "Human",
    },
    "Animal": {
        "Animate",
    },
    "Plant": {
        "Animate",
    },
    "Body_Part": {
        "Animate",
    },
    "Machine": {
        "Internal_Control",
        "Artefact",
    },
    "Vehicle": {
        "Machine",
    },
    "Natural": {
        "Concrete",
    },
    "Artefact": {
        "Concrete",
    },
    "Comestible": {
        "Concrete",
    },
    "Substance": {
        "Concrete",
    },
    "State_of_Matter": {
        "Concrete",
    },
    "Inanimate": {
        "Concrete",
    },
    "Garment": {
        "Artefact",
    },
    "Solid": {
        "State_of_Matter",
    },
    "Fluid": {
        "State_of_Matter",
    },
    "Rigidity": {
        "Solid",
    },
    "Shape": {
        "Solid",
    },
    "Rigid": {
        "Rigidity",
    },
    "Non_Rigid": {
        "Rigidity",
    },
    "Elongated": {
        "Shape",
    },
    "Pointy": {
        "Shape",
    },
    "Point_in_Time": {
        "Time",
    },
    "Duration": {
        "Time",
    },
    "Time": {
        "Abstract",
    },
    "Language": {
        "Abstract",
    },
    "Sound": {
        "Abstract",
    },
    "Communication": {
        "Abstract",
    },
    "Eventive": {
        "Abstract",
    },
    "Statement": {
        "Communication",
    },
    "Question": {
        "Communication",
    },
}


def validate_feature_hierarchy() -> None:
    """Fail early if FEATURE_PARENTS contains a cycle or invalid name."""

    all_features: Set[str] = set(FEATURE_PARENTS)

    for parents in FEATURE_PARENTS.values():
        all_features.update(parents)

    for feature in all_features:
        if not isinstance(feature, str) or not feature.strip():
            raise ValueError(
                "FEATURE_PARENTS contains an empty or non-string feature name."
            )

    visiting: Set[str] = set()
    visited: Set[str] = set()

    def visit(feature: str) -> None:
        if feature in visited:
            return

        if feature in visiting:
            raise ValueError(
                f"Cycle detected in FEATURE_PARENTS involving {feature!r}."
            )

        visiting.add(feature)

        for parent in FEATURE_PARENTS.get(feature, set()):
            visit(parent)

        visiting.remove(feature)
        visited.add(feature)

    for feature in sorted(all_features):
        visit(feature)


@lru_cache(maxsize=None)
def get_feature_ancestors(feature: str) -> frozenset:
    """Return every direct and indirect parent of *feature*."""

    ancestors: Set[str] = set()

    for parent in FEATURE_PARENTS.get(feature, set()):
        if is_feature_enabled(parent):
            ancestors.add(parent)
        # Traverse even through a disabled intermediate node so enabled
        # grandparents remain inherited.
        ancestors.update(get_feature_ancestors(parent))

    return frozenset(ancestors)


def expand_feature_hierarchy(features: Iterable[str]) -> Set[str]:
    """Add every deterministic ancestor required by FEATURE_PARENTS."""

    expanded: Set[str] = {
        feature for feature in features if is_feature_enabled(feature)
    }

    for feature in list(expanded):
        expanded.update(get_feature_ancestors(feature))

    return expanded


def reduce_to_independent_features(features: Iterable[str]) -> Set[str]:
    """
    Reduce a complete feature set to the features that must be predicted.

    A feature is redundant when it is an ancestor of another feature present
    for the same token. Such an ancestor can be reconstructed deterministically.

    Examples:
        {Human, Animate, Natural, Concrete, Internal_Control}
            -> {Human}

        {Feminine, Human, Animate, Natural, Concrete, Internal_Control}
            -> {Feminine}

        {Statement, Communication, Abstract, Time}
            -> {Statement, Time}

    This is deliberately PER TOKEN. It is not the same as training only labels
    that are global terminal leaves in the ontology. A generic Human can still
    be a direct neural target if no more specific Human child is present.
    """

    feature_set = set(features)

    inherited_from_other_features: Set[str] = set()

    for feature in feature_set:
        inherited_from_other_features.update(
            get_feature_ancestors(feature)
        )

    return feature_set - inherited_from_other_features


def missing_hierarchy_features(features: Iterable[str]) -> Set[str]:
    """Return ancestors required by the hierarchy but absent from *features*."""

    feature_set = set(features)
    return expand_feature_hierarchy(feature_set) - feature_set


# =============================================================================
# CUDA
# =============================================================================

def check_cuda() -> None:
    """Require CUDA rather than silently falling back to the CPU."""

    if not torch.cuda.is_available():
        raise RuntimeError(
            "CUDA is not available. This script is configured to require "
            "a CUDA-capable GPU."
        )

    print("=" * 80)
    print("CUDA")
    print("=" * 80)
    print(f"PyTorch version: {torch.__version__}")
    print(f"CUDA available: {torch.cuda.is_available()}")
    print(f"CUDA runtime: {torch.version.cuda}")
    print(f"GPU: {torch.cuda.get_device_name(0)}")

    props = torch.cuda.get_device_properties(0)

    print(
        "VRAM: "
        f"{props.total_memory / (1024 ** 3):.2f} GiB"
    )
    print()


# =============================================================================
# Load CoNLL-U
# =============================================================================

def load_conllu(path: Path) -> List[Any]:
    """Load all CoNLL-U sentences."""

    if not path.exists():
        raise FileNotFoundError(
            f"Could not find CoNLL-U file:\n{path.resolve()}"
        )

    sentences: List[Any] = []

    with path.open("r", encoding="utf-8") as handle:
        for sentence in parse_incr(handle):
            sentences.append(sentence)

    return sentences


def get_sentence_words(sentence: Any) -> Tuple[List[str], List[int]]:
    """
    Return ordinary integer-ID tokens and their original CoNLL-U token IDs.

    Multiword-token placeholder rows and empty nodes are excluded.
    """

    words: List[str] = []
    token_ids: List[int] = []

    for token in sentence:
        token_id = token.get("id")

        if not isinstance(token_id, int):
            continue

        form = token.get("form")

        if form is None:
            continue

        words.append(str(form))
        token_ids.append(token_id)

    return words, token_ids


# =============================================================================
# Load tagged JSONL
# =============================================================================

def load_tagged_records(
    path: Path,
) -> Dict[int, Dict[int, Dict[str, Any]]]:
    """
    Return:

        sentence_index
            -> token_id
                -> JSONL record

    Only NOUN and PROPN records are retained.
    """

    if not path.exists():
        raise FileNotFoundError(
            f"Could not find tagged JSONL:\n{path.resolve()}"
        )

    records: Dict[int, Dict[int, Dict[str, Any]]] = defaultdict(dict)

    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            line = line.strip()

            if not line:
                continue

            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                print(
                    "Warning: invalid JSON on line "
                    f"{line_number}: {exc}"
                )
                continue

            if record.get("upos") not in TARGET_POS:
                continue

            sentence_index = record.get("sentence_index")
            token_id = record.get("token_id")

            if not isinstance(sentence_index, int):
                continue

            if not isinstance(token_id, int):
                continue

            records[sentence_index][token_id] = record

    return dict(records)


# =============================================================================
# Labels
# =============================================================================

def clean_features(record: Dict[str, Any]) -> List[str]:
    """Return unique, non-empty COMPLETE feature names from a JSONL record."""

    raw = record.get("features", [])

    if not isinstance(raw, list):
        return []

    return sorted(
        {
            str(feature).strip()
            for feature in raw
            if (
                str(feature).strip()
                and is_feature_enabled(str(feature).strip())
            )
        }
    )


def get_independent_record_features(record: Dict[str, Any]) -> List[str]:
    """Return the per-token minimal feature set that the model must predict."""

    return sorted(
        reduce_to_independent_features(
            clean_features(record)
        )
    )


def build_full_label_vocabulary(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    training_sentence_indices: Sequence[int],
) -> List[str]:
    """
    Build the COMPLETE evaluation vocabulary from training data only.

    Deterministic ancestors are included even if a training record omitted one,
    although hierarchy closure is separately verified and should normally make
    this addition unnecessary.
    """

    labels: Set[str] = set()

    for sentence_index in training_sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            features = clean_features(record)
            labels.update(features)
            labels.update(expand_feature_hierarchy(features))

    if not labels:
        raise RuntimeError(
            "No semantic features were found in the training split."
        )

    return sorted(labels)


def build_prediction_label_vocabulary(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    training_sentence_indices: Sequence[int],
) -> List[str]:
    """Build the neural-output vocabulary from independent training targets."""

    labels: Set[str] = set()

    for sentence_index in training_sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            labels.update(
                get_independent_record_features(record)
            )

    if not labels:
        raise RuntimeError(
            "No independent semantic features were found in the training split."
        )

    return sorted(labels)


# =============================================================================
# Sentence selection and splitting
# =============================================================================

def get_eligible_sentence_indices(
    sentences: Sequence[Any],
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> List[int]:
    """Eligible sentences contain at least one non-empty NOUN/PROPN target."""

    eligible: List[int] = []

    for sentence_index in range(len(sentences)):
        token_records = tagged_records.get(sentence_index, {})

        valid_records = [
            record
            for record in token_records.values()
            if clean_features(record)
        ]

        if valid_records:
            eligible.append(sentence_index)

    return eligible


def get_sentence_independent_feature_counts(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    sentence_index: int,
) -> Counter:
    """Count independent positive token targets in one source sentence."""

    counts: Counter = Counter()

    for record in tagged_records.get(sentence_index, {}).values():
        if not clean_features(record):
            continue

        for feature in get_independent_record_features(record):
            counts[feature] += 1

    return counts


def build_sentence_multilabel_matrix(
    eligible_indices: Sequence[int],
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> Tuple[np.ndarray, List[str], Dict[int, Counter]]:
    """
    Build one multilabel stratification row per SENTENCE.

    y_sentence[sentence, feature] is 1 when at least one eligible NOUN/PROPN
    token in that sentence has the independent feature. Token counts are kept
    separately for the post-split training-coverage constraint.
    """

    sentence_feature_counts: Dict[int, Counter] = {
        sentence_index: get_sentence_independent_feature_counts(
            tagged_records,
            sentence_index,
        )
        for sentence_index in eligible_indices
    }

    stratification_labels = sorted(
        {
            feature
            for counts in sentence_feature_counts.values()
            for feature, count in counts.items()
            if count > 0
        }
    )

    if not stratification_labels:
        raise RuntimeError(
            "No independent semantic features were found in eligible "
            "training sentences."
        )

    label2column = {
        label: column
        for column, label in enumerate(stratification_labels)
    }

    matrix = np.zeros(
        (len(eligible_indices), len(stratification_labels)),
        dtype=np.int8,
    )

    for row, sentence_index in enumerate(eligible_indices):
        for feature in sentence_feature_counts[sentence_index]:
            matrix[row, label2column[feature]] = 1

    return matrix, stratification_labels, sentence_feature_counts


def _sentence_prevalence_error(
    y_all: np.ndarray,
    validation_rows: np.ndarray,
    validation_fraction: float,
) -> float:
    """
    Score how closely validation sentence-level label prevalences match target.

    Lower is better. The score is used only to choose among deterministic
    iterative-stratification attempts that satisfy the training-coverage rule.
    """

    total_support = y_all.sum(axis=0).astype(np.float64)
    validation_support = y_all[validation_rows].sum(axis=0).astype(np.float64)

    target_support = total_support * float(validation_fraction)

    # Scale by at least one expected example so rare and common labels both
    # contribute without allowing extremely common labels to dominate.
    scale = np.maximum(target_support, 1.0)

    return float(
        np.mean(
            np.abs(validation_support - target_support) / scale
        )
    )


def make_train_validation_split(
    eligible_indices: Sequence[int],
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> Dict[str, Any]:
    """
    Create a SENTENCE-LEVEL multilabel-stratified split from TRAINING only.

    Each sentence receives a binary vector indicating which independent feature
    labels occur anywhere among its eligible NOUN/PROPN tokens. Iterative
    multilabel stratification then assigns whole sentences to train/validation.

    The split is retried deterministically when necessary so that every
    independent feature retains at least MIN_TRAIN_POSITIVES_PER_FEATURE
    positive TOKEN targets in the training subset.

    The official test corpus is deliberately not accepted by this function, so
    test labels cannot influence the split.
    """

    if not 0.0 < VALIDATION_FRACTION < 1.0:
        raise ValueError(
            "VALIDATION_FRACTION must be strictly between 0 and 1."
        )

    if MIN_TRAIN_POSITIVES_PER_FEATURE < 1:
        raise ValueError(
            "MIN_TRAIN_POSITIVES_PER_FEATURE must be at least 1."
        )

    if MAX_STRATIFICATION_ATTEMPTS < 1:
        raise ValueError(
            "MAX_STRATIFICATION_ATTEMPTS must be at least 1."
        )

    eligible_indices = list(eligible_indices)

    if len(eligible_indices) < 2:
        raise RuntimeError(
            "Need at least two eligible training sentences to create a "
            "train/validation split."
        )

    (
        sentence_matrix,
        stratification_labels,
        sentence_feature_counts,
    ) = build_sentence_multilabel_matrix(
        eligible_indices,
        tagged_records,
    )

    all_token_counts: Counter = Counter()

    for counts in sentence_feature_counts.values():
        all_token_counts.update(counts)

    x_dummy = np.zeros((len(eligible_indices), 1), dtype=np.int8)

    best_candidate: Optional[Dict[str, Any]] = None
    rejected_for_coverage = 0

    for attempt in range(MAX_STRATIFICATION_ATTEMPTS):
        attempt_seed = SPLIT_SEED + attempt

        splitter = MultilabelStratifiedShuffleSplit(
            n_splits=1,
            test_size=VALIDATION_FRACTION,
            random_state=attempt_seed,
        )

        train_rows, validation_rows = next(
            splitter.split(x_dummy, sentence_matrix)
        )

        train_indices = [
            eligible_indices[int(row)]
            for row in train_rows
        ]
        validation_indices = [
            eligible_indices[int(row)]
            for row in validation_rows
        ]

        train_token_counts: Counter = Counter()

        for sentence_index in train_indices:
            train_token_counts.update(
                sentence_feature_counts[sentence_index]
            )

        missing_or_undercovered = sorted(
            feature
            for feature, total_count in all_token_counts.items()
            if (
                total_count > 0
                and train_token_counts[feature]
                < MIN_TRAIN_POSITIVES_PER_FEATURE
            )
        )

        if missing_or_undercovered:
            rejected_for_coverage += 1
            continue

        prevalence_error = _sentence_prevalence_error(
            sentence_matrix,
            validation_rows,
            VALIDATION_FRACTION,
        )

        candidate = {
            "train": train_indices,
            "validation": validation_indices,
            "split_seed_used": attempt_seed,
            "attempt": attempt + 1,
            "prevalence_error": prevalence_error,
            "stratification_labels": stratification_labels,
        }

        if (
            best_candidate is None
            or prevalence_error < best_candidate["prevalence_error"]
        ):
            best_candidate = candidate

        # Iterative stratification is already designed to balance multilabel
        # prevalence. Once a valid candidate is found, further attempts are not
        # needed unless coverage forced earlier candidates to be rejected.
        if rejected_for_coverage == 0:
            break

    if best_candidate is None:
        raise RuntimeError(
            "Could not create a sentence-level multilabel-stratified "
            "train/validation split that preserved the required training "
            f"support after {MAX_STRATIFICATION_ATTEMPTS} attempts."
        )

    train_indices = best_candidate["train"]
    validation_indices = best_candidate["validation"]

    train_set = set(train_indices)
    validation_set = set(validation_indices)

    if train_set & validation_set:
        raise RuntimeError(
            "Internal split error: at least one sentence occurs in both "
            "training and validation."
        )

    if train_set | validation_set != set(eligible_indices):
        raise RuntimeError(
            "Internal split error: sentence-level split does not exactly cover "
            "the eligible training sentences."
        )

    print()
    print("Sentence-level multilabel-stratified train/validation split:")
    print(
        f"  Eligible training sentences : {len(eligible_indices):,}"
    )
    print(
        f"  Target validation sentences : "
        f"{round(len(eligible_indices) * VALIDATION_FRACTION):,}"
    )
    print(
        f"  Actual validation sentences : {len(validation_indices):,}"
    )
    print(
        f"  Training sentences retained : {len(train_indices):,}"
    )
    print(
        f"  Split seed used             : "
        f"{best_candidate['split_seed_used']}"
    )
    print(
        f"  Stratification labels       : "
        f"{len(stratification_labels):,}"
    )
    print(
        f"  Coverage-rejected attempts  : {rejected_for_coverage:,}"
    )
    print(
        f"  Mean relative prevalence error: "
        f"{best_candidate['prevalence_error']:.6f}"
    )

    # Show sentence-level prevalence agreement, which is the quantity actually
    # controlled by the stratifier.
    validation_fraction_actual = (
        len(validation_indices) / len(eligible_indices)
    )

    label2column = {
        label: column
        for column, label in enumerate(stratification_labels)
    }

    row_by_sentence = {
        sentence_index: row
        for row, sentence_index in enumerate(eligible_indices)
    }

    train_rows_lookup = [
        row_by_sentence[index]
        for index in train_indices
    ]
    validation_rows_lookup = [
        row_by_sentence[index]
        for index in validation_indices
    ]

    print()
    print(
        f"{'Feature':35s} "
        f"{'All sent.':>10s} "
        f"{'Train':>10s} "
        f"{'Valid':>10s} "
        f"{'Valid %':>10s}"
    )
    print("-" * 80)

    for feature in stratification_labels:
        column = label2column[feature]
        all_support = int(sentence_matrix[:, column].sum())
        train_support = int(
            sentence_matrix[train_rows_lookup, column].sum()
        )
        validation_support = int(
            sentence_matrix[validation_rows_lookup, column].sum()
        )

        print(
            f"{feature:35s} "
            f"{all_support:10d} "
            f"{train_support:10d} "
            f"{validation_support:10d} "
            f"{validation_support / max(all_support, 1):10.3f}"
        )

    print(
        f"\nActual validation sentence fraction: "
        f"{validation_fraction_actual:.4f}"
    )
    print()

    return best_candidate


# =============================================================================
# Dataset
# =============================================================================

class SemanticFeatureDataset(Dataset):
    """
    RoBERTa multi-label token-classification dataset.

    IMPORTANT:
        labels contain only INDEPENDENT neural targets.

    Labels have shape:
        [sequence_length, number_of_prediction_features]

    For supervised tokens:
        0 = independent feature absent
        1 = independent feature present

    For ignored tokens:
        -100 across all labels

    Only the first RoBERTa subword corresponding to each source token receives
    supervision.
    """

    def __init__(
        self,
        sentences: Sequence[Any],
        sentence_indices: Sequence[int],
        tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
        tokenizer: Any,
        label2id: Dict[str, int],
        max_length: int,
    ) -> None:
        self.sentences = sentences
        self.sentence_indices = list(sentence_indices)
        self.tagged_records = tagged_records
        self.tokenizer = tokenizer
        self.label2id = label2id
        self.num_labels = len(label2id)
        self.max_length = max_length

    def __len__(self) -> int:
        return len(self.sentence_indices)

    def __getitem__(
        self,
        dataset_index: int,
    ) -> Dict[str, Any]:
        sentence_index = self.sentence_indices[dataset_index]
        sentence = self.sentences[sentence_index]

        words, token_ids = get_sentence_words(sentence)

        encoding = self.tokenizer(
            words,
            is_split_into_words=True,
            truncation=True,
            max_length=self.max_length,
            add_special_tokens=True,
        )

        word_ids = encoding.word_ids()
        labels: List[List[float]] = []
        previous_word_id: Optional[int] = None
        sentence_records = self.tagged_records.get(sentence_index, {})

        for word_id in word_ids:
            if word_id is None:
                labels.append([-100.0] * self.num_labels)
                previous_word_id = word_id
                continue

            # Ignore all but the first subword.
            if word_id == previous_word_id:
                labels.append([-100.0] * self.num_labels)
                continue

            previous_word_id = word_id

            if not 0 <= word_id < len(token_ids):
                labels.append([-100.0] * self.num_labels)
                continue

            conllu_token_id = token_ids[word_id]
            record = sentence_records.get(conllu_token_id)

            if record is None:
                labels.append([-100.0] * self.num_labels)
                continue

            full_features = clean_features(record)

            if not full_features and EXCLUDE_EMPTY_FEATURE_RECORDS:
                labels.append([-100.0] * self.num_labels)
                continue

            independent_features = reduce_to_independent_features(
                full_features
            )

            target = [0.0] * self.num_labels

            for feature in independent_features:
                label_id = self.label2id.get(feature)

                if label_id is not None:
                    target[label_id] = 1.0

            labels.append(target)

        encoding["labels"] = labels
        encoding["sentence_index"] = sentence_index

        return encoding


# =============================================================================
# Data collator
# =============================================================================

class MultiLabelTokenCollator:
    """Dynamically pad inputs and 3-D multi-label token targets."""

    def __init__(
        self,
        tokenizer: Any,
        num_labels: int,
    ) -> None:
        self.tokenizer = tokenizer
        self.num_labels = num_labels

    def __call__(
        self,
        features: List[Dict[str, Any]],
    ) -> Dict[str, torch.Tensor]:
        clean_features_list: List[Dict[str, Any]] = []
        labels_list: List[List[List[float]]] = []

        for item in features:
            item = dict(item)
            item.pop("sentence_index", None)

            labels = item.pop("labels")
            labels_list.append(labels)
            clean_features_list.append(item)

        batch = self.tokenizer.pad(
            clean_features_list,
            padding=True,
            return_tensors="pt",
        )

        batch_size = len(labels_list)
        max_seq_length = batch["input_ids"].shape[1]

        padded_labels = torch.full(
            (
                batch_size,
                max_seq_length,
                self.num_labels,
            ),
            -100.0,
            dtype=torch.float32,
        )

        for batch_index, labels in enumerate(labels_list):
            label_tensor = torch.tensor(
                labels,
                dtype=torch.float32,
            )

            sequence_length = label_tensor.shape[0]

            padded_labels[
                batch_index,
                :sequence_length,
                :,
            ] = label_tensor

        batch["labels"] = padded_labels

        return batch


# =============================================================================
# Model
# =============================================================================

class RobertaMultiLabelModel(nn.Module):
    """RoBERTa token classifier with BCE loss for independent feature labels."""

    def __init__(
        self,
        model_name: str,
        num_labels: int,
        id2label: Dict[int, str],
        label2id: Dict[str, int],
    ) -> None:
        super().__init__()

        self.model = AutoModelForTokenClassification.from_pretrained(
            model_name,
            num_labels=num_labels,
            id2label=id2label,
            label2id=label2id,
        )

        self.config = self.model.config

        self.loss_function = nn.BCEWithLogitsLoss(
            reduction="mean"
        )

    def forward(
        self,
        input_ids=None,
        attention_mask=None,
        labels=None,
        **kwargs,
    ):
        outputs = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            **kwargs,
        )

        logits = outputs.logits
        loss = None

        if labels is not None:
            valid_mask = labels[:, :, 0] != -100.0

            valid_logits = logits[valid_mask]
            valid_labels = labels[valid_mask]

            if valid_logits.numel() == 0:
                loss = logits.sum() * 0.0
            else:
                loss = self.loss_function(
                    valid_logits,
                    valid_labels,
                )

        return {
            "loss": loss,
            "logits": logits,
        }

    def save_pretrained(
        self,
        save_directory,
        **kwargs,
    ):
        return self.model.save_pretrained(
            save_directory,
            **kwargs,
        )


# =============================================================================
# Hierarchy matrices and array helpers
# =============================================================================

def build_hierarchy_expansion_matrix(
    prediction_labels: Sequence[str],
    full_labels: Sequence[str],
) -> np.ndarray:
    """
    Build a boolean matrix mapping neural outputs to complete feature sets.

    Shape:
        [number_of_prediction_features, number_of_full_features]
    """

    full_label2id = {
        label: index
        for index, label in enumerate(full_labels)
    }

    matrix = np.zeros(
        (len(prediction_labels), len(full_labels)),
        dtype=np.int8,
    )

    for prediction_id, feature in enumerate(prediction_labels):
        expanded = expand_feature_hierarchy({feature})

        for expanded_feature in expanded:
            full_id = full_label2id.get(expanded_feature)

            if full_id is None:
                raise RuntimeError(
                    "Hierarchy expansion produced a feature absent from the "
                    f"full vocabulary: {expanded_feature!r}."
                )

            matrix[prediction_id, full_id] = 1

    return matrix


def expand_binary_feature_matrix(
    independent_matrix: np.ndarray,
    hierarchy_matrix: np.ndarray,
) -> np.ndarray:
    """Expand [tokens, independent] binary values to [tokens, complete]."""

    expanded = independent_matrix.astype(np.int32) @ hierarchy_matrix.astype(
        np.int32
    )

    return (expanded > 0).astype(np.int32)


def extract_valid_token_arrays(
    logits: np.ndarray,
    labels: np.ndarray,
) -> Tuple[np.ndarray, np.ndarray]:
    """Return probabilities and true independent labels for supervised tokens."""

    valid_token_mask = labels[:, :, 0] != -100.0

    probabilities = sigmoid_numpy(logits)[
        valid_token_mask
    ]

    true_labels = labels[
        valid_token_mask
    ].astype(np.int32)

    return probabilities, true_labels


def build_full_truth_matrix_for_dataset(
    dataset: "SemanticFeatureDataset",
    full_labels: Sequence[str],
) -> np.ndarray:
    """Build complete source truth for every supervised token in dataset order.

    This is intentionally independent of the neural-output vocabulary.  It is
    therefore safe and necessary for a held-out test corpus that may contain a
    feature such as ``Human`` as a direct independent target even when that
    feature never occurred independently in the training corpus.

    The model is still trained only on training-derived independent output
    heads.  This function merely preserves the complete gold annotations for
    fair hierarchy-expanded evaluation.
    """

    full_label2id = {
        label: index
        for index, label in enumerate(full_labels)
    }

    rows: List[np.ndarray] = []

    for sentence_index in dataset.sentence_indices:
        sentence = dataset.sentences[sentence_index]
        words, token_ids = get_sentence_words(sentence)

        encoding = dataset.tokenizer(
            words,
            is_split_into_words=True,
            truncation=True,
            max_length=dataset.max_length,
            add_special_tokens=True,
        )

        word_ids = encoding.word_ids()
        previous_word_id: Optional[int] = None
        sentence_records = dataset.tagged_records.get(sentence_index, {})

        for word_id in word_ids:
            if word_id is None:
                previous_word_id = word_id
                continue

            # Match SemanticFeatureDataset.__getitem__: only the first subword
            # for each source token receives supervision.
            if word_id == previous_word_id:
                continue

            previous_word_id = word_id

            if not 0 <= word_id < len(token_ids):
                continue

            conllu_token_id = token_ids[word_id]
            record = sentence_records.get(conllu_token_id)

            if record is None:
                continue

            features = clean_features(record)

            if not features and EXCLUDE_EMPTY_FEATURE_RECORDS:
                continue

            expanded_features = expand_feature_hierarchy(features)
            row = np.zeros(len(full_labels), dtype=np.int32)

            for feature in expanded_features:
                label_id = full_label2id.get(feature)

                if label_id is None:
                    raise RuntimeError(
                        "Complete source truth contains a feature absent from "
                        f"the training-derived full vocabulary: {feature!r}."
                    )

                row[label_id] = 1

            rows.append(row)

    if not rows:
        return np.zeros((0, len(full_labels)), dtype=np.int32)

    return np.stack(rows, axis=0)


# =============================================================================
# Metrics and thresholds
# =============================================================================

def sigmoid_numpy(x: np.ndarray) -> np.ndarray:
    """Numerically stable sigmoid."""

    x = np.clip(x, -50.0, 50.0)
    return 1.0 / (1.0 + np.exp(-x))


def make_threshold_vector(
    prediction_labels: Sequence[str],
    thresholds: Dict[str, float],
) -> np.ndarray:
    """Return thresholds in neural-output column order."""

    return np.asarray(
        [
            float(
                thresholds.get(
                    label,
                    DEFAULT_PREDICTION_THRESHOLD,
                )
            )
            for label in prediction_labels
        ],
        dtype=np.float32,
    )


def threshold_probabilities(
    probabilities: np.ndarray,
    threshold_vector: np.ndarray,
) -> np.ndarray:
    """Apply one threshold per independent feature."""

    return (
        probabilities >= threshold_vector.reshape(1, -1)
    ).astype(np.int32)


def calculate_average_metrics(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    prefix: str = "",
) -> Dict[str, float]:
    """Calculate micro and macro precision/recall/F1."""

    if y_true.shape[0] == 0:
        return {
            f"{prefix}precision_micro": 0.0,
            f"{prefix}recall_micro": 0.0,
            f"{prefix}f1_micro": 0.0,
            f"{prefix}precision_macro": 0.0,
            f"{prefix}recall_macro": 0.0,
            f"{prefix}f1_macro": 0.0,
        }

    (
        precision_micro,
        recall_micro,
        f1_micro,
        _,
    ) = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="micro",
        zero_division=0,
    )

    (
        precision_macro,
        recall_macro,
        f1_macro,
        _,
    ) = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="macro",
        zero_division=0,
    )

    return {
        f"{prefix}precision_micro": float(precision_micro),
        f"{prefix}recall_micro": float(recall_micro),
        f"{prefix}f1_micro": float(f1_micro),
        f"{prefix}precision_macro": float(precision_macro),
        f"{prefix}recall_macro": float(recall_macro),
        f"{prefix}f1_macro": float(f1_macro),
    }


def calculate_hierarchical_metrics_from_probabilities(
    probabilities: np.ndarray,
    y_true_independent: np.ndarray,
    threshold_vector: np.ndarray,
    hierarchy_matrix: np.ndarray,
    y_true_full: Optional[np.ndarray] = None,
) -> Dict[str, float]:
    """
    Report both direct neural-output metrics and complete hierarchy metrics.

    Unprefixed metrics are the COMPLETE hierarchy metrics.  During ordinary
    training/validation, complete truth can be reconstructed from the
    independent targets.  For a genuinely held-out test corpus, ``y_true_full``
    may instead be supplied directly from the source annotations so an unseen
    direct independent label is not silently erased from the gold truth.
    """

    y_pred_independent = threshold_probabilities(
        probabilities,
        threshold_vector,
    )

    if y_true_full is None:
        y_true_full = expand_binary_feature_matrix(
            y_true_independent,
            hierarchy_matrix,
        )

    if y_true_full.shape[0] != y_true_independent.shape[0]:
        raise RuntimeError(
            "Complete and independent truth matrices contain different "
            f"numbers of supervised tokens: {y_true_full.shape[0]} vs "
            f"{y_true_independent.shape[0]}."
        )

    y_pred_full = expand_binary_feature_matrix(
        y_pred_independent,
        hierarchy_matrix,
    )

    metrics = calculate_average_metrics(
        y_true_full,
        y_pred_full,
        prefix="",
    )

    metrics.update(
        calculate_average_metrics(
            y_true_independent,
            y_pred_independent,
            prefix="direct_",
        )
    )

    return metrics


def make_compute_metrics(
    prediction_labels: Sequence[str],
    hierarchy_matrix: np.ndarray,
):
    """Create Trainer metrics using the fixed default 0.5 thresholds."""

    default_thresholds = np.full(
        len(prediction_labels),
        DEFAULT_PREDICTION_THRESHOLD,
        dtype=np.float32,
    )

    def compute_metrics(eval_prediction) -> Dict[str, float]:
        logits, labels = eval_prediction

        probabilities, y_true_independent = extract_valid_token_arrays(
            logits,
            labels,
        )

        return calculate_hierarchical_metrics_from_probabilities(
            probabilities=probabilities,
            y_true_independent=y_true_independent,
            threshold_vector=default_thresholds,
            hierarchy_matrix=hierarchy_matrix,
        )

    return compute_metrics


def build_threshold_grid() -> np.ndarray:
    """Build an inclusive, stable validation threshold search grid."""

    if THRESHOLD_STEP <= 0:
        raise ValueError("THRESHOLD_STEP must be > 0.")

    if not 0.0 < THRESHOLD_MIN < 1.0:
        raise ValueError("THRESHOLD_MIN must be between 0 and 1.")

    if not 0.0 < THRESHOLD_MAX < 1.0:
        raise ValueError("THRESHOLD_MAX must be between 0 and 1.")

    if THRESHOLD_MIN > THRESHOLD_MAX:
        raise ValueError("THRESHOLD_MIN cannot exceed THRESHOLD_MAX.")

    count = int(
        round(
            (THRESHOLD_MAX - THRESHOLD_MIN)
            / THRESHOLD_STEP
        )
    ) + 1

    return np.linspace(
        THRESHOLD_MIN,
        THRESHOLD_MAX,
        count,
        dtype=np.float64,
    )


def binary_metrics_for_column(
    y_true: np.ndarray,
    y_pred: np.ndarray,
) -> Tuple[float, float, float, int]:
    """Return binary precision, recall, F1 and positive support."""

    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="binary",
        zero_division=0,
    )

    support = int(y_true.sum())

    return (
        float(precision),
        float(recall),
        float(f1),
        support,
    )


def optimise_feature_thresholds(
    probabilities: np.ndarray,
    y_true_independent: np.ndarray,
    prediction_labels: Sequence[str],
) -> Tuple[Dict[str, float], Dict[str, Dict[str, float]]]:
    """
    Optimise one sigmoid threshold per independent feature on VALIDATION ONLY.

    Objective:
        maximise that feature's binary F1.

    Stability rules:
    - If validation has no positives or no negatives for a feature, keep 0.5.
    - If several thresholds tie for best F1, choose the one closest to 0.5.
      This avoids unnecessarily extreme thresholds for flat validation curves.
    """

    grid = build_threshold_grid()

    thresholds: Dict[str, float] = {}
    diagnostics: Dict[str, Dict[str, float]] = {}

    for label_id, feature in enumerate(prediction_labels):
        y_true = y_true_independent[:, label_id]
        probs = probabilities[:, label_id]

        positive_support = int(y_true.sum())
        negative_support = int((1 - y_true).sum())

        default_pred = (
            probs >= DEFAULT_PREDICTION_THRESHOLD
        ).astype(np.int32)

        (
            default_precision,
            default_recall,
            default_f1,
            _,
        ) = binary_metrics_for_column(
            y_true,
            default_pred,
        )

        if positive_support == 0 or negative_support == 0:
            best_threshold = DEFAULT_PREDICTION_THRESHOLD
        else:
            best_f1 = -1.0
            best_candidates: List[float] = []

            for threshold in grid:
                y_pred = (probs >= threshold).astype(np.int32)

                _, _, f1, _ = binary_metrics_for_column(
                    y_true,
                    y_pred,
                )

                if f1 > best_f1 + 1e-12:
                    best_f1 = f1
                    best_candidates = [float(threshold)]
                elif abs(f1 - best_f1) <= 1e-12:
                    best_candidates.append(float(threshold))

            best_threshold = min(
                best_candidates,
                key=lambda value: (
                    abs(value - DEFAULT_PREDICTION_THRESHOLD),
                    value,
                ),
            )

        best_pred = (
            probs >= best_threshold
        ).astype(np.int32)

        (
            best_precision,
            best_recall,
            best_f1,
            _,
        ) = binary_metrics_for_column(
            y_true,
            best_pred,
        )

        thresholds[feature] = float(best_threshold)

        diagnostics[feature] = {
            "threshold": float(best_threshold),
            "support": positive_support,
            "negative_support": negative_support,
            "precision_default": default_precision,
            "recall_default": default_recall,
            "f1_default": default_f1,
            "precision_optimised": best_precision,
            "recall_optimised": best_recall,
            "f1_optimised": best_f1,
            "f1_change": best_f1 - default_f1,
        }

    return thresholds, diagnostics


def calculate_per_feature_metrics_from_binary(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    labels: Sequence[str],
) -> Dict[str, Dict[str, float]]:
    """Calculate binary precision/recall/F1 independently for each column."""

    results: Dict[str, Dict[str, float]] = {}

    for label_id, feature in enumerate(labels):
        precision, recall, f1, support = binary_metrics_for_column(
            y_true[:, label_id],
            y_pred[:, label_id],
        )

        results[feature] = {
            "precision": precision,
            "recall": recall,
            "f1": f1,
            "support": support,
        }

    return results


# =============================================================================
# Dataset diagnostics and validation
# =============================================================================

def count_feature_occurrences(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    sentence_indices: Sequence[int],
    independent_only: bool = False,
) -> Counter:
    """Count complete or independent positive labels in a split."""

    counts: Counter = Counter()

    for sentence_index in sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            if independent_only:
                features = get_independent_record_features(record)
            else:
                features = clean_features(record)

            for feature in features:
                counts[feature] += 1

    return counts


def count_empty_records(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    sentence_indices: Sequence[int],
) -> int:
    """Count NOUN/PROPN records having no complete feature tags."""

    count = 0

    for sentence_index in sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            if not clean_features(record):
                count += 1

    return count


def verify_full_label_coverage(
    full_labels: Sequence[str],
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
) -> None:
    """Ensure validation/test contain no complete label unseen in training."""

    training_labels = set(full_labels)

    for split_name in ("validation", "test"):
        tagged_records, sentence_indices = split_sources[split_name]
        observed: Set[str] = set()

        for sentence_index in sentence_indices:
            for record in tagged_records.get(sentence_index, {}).values():
                observed.update(clean_features(record))

        unknown = observed - training_labels

        if unknown:
            raise RuntimeError(
                f"{split_name} contains full labels unseen in training: "
                f"{sorted(unknown)}"
            )


def verify_prediction_label_coverage(
    prediction_labels: Sequence[str],
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
    training_file_prediction_labels: Optional[Sequence[str]] = None,
) -> Dict[str, Dict[str, int]]:
    """Check independent-target coverage without leaking test labels.

    Validation remains strict: every validation independent target must have a
    training-derived neural output head.

    Test is different.  A genuine held-out corpus may contain a direct
    independent target that never occurred independently in training.  Such a
    label must NOT be added to the model from the test set.  Instead, report it
    and let complete-feature evaluation use the source gold matrix directly.
    """

    training_labels = set(prediction_labels)
    training_file_labels = (
        set(training_file_prediction_labels)
        if training_file_prediction_labels is not None
        else set(training_labels)
    )

    unseen_test_support: Dict[str, Dict[str, int]] = {}

    for split_name in ("validation", "test"):
        tagged_records, sentence_indices = split_sources[split_name]
        observed_counts: Counter = Counter()

        for sentence_index in sentence_indices:
            for record in tagged_records.get(sentence_index, {}).values():
                for feature in get_independent_record_features(record):
                    observed_counts[feature] += 1

        observed = set(observed_counts)
        unknown = observed - training_labels

        if not unknown:
            continue

        lost_due_to_split = unknown & training_file_labels
        absent_from_training_file = unknown - training_file_labels

        if split_name == "validation":
            details: List[str] = []

            if lost_due_to_split:
                details.append(
                    "present somewhere in the training file but absent from "
                    f"the training subset: {sorted(lost_due_to_split)}"
                )

            if absent_from_training_file:
                details.append(
                    "never occur as independent targets anywhere in the "
                    f"training file: {sorted(absent_from_training_file)}"
                )

            raise RuntimeError(
                "validation contains independent labels with no learnable "
                "training output. "
                + "; ".join(details)
            )

        # For the official test set, do not modify the model vocabulary.
        unseen_test_support = {
            feature: {
                "support": int(observed_counts[feature]),
                "present_in_training_file_as_independent": int(
                    feature in training_file_labels
                ),
            }
            for feature in sorted(unknown)
        }

        print()
        print("=" * 80)
        print("HELD-OUT TEST LABEL COVERAGE WARNING")
        print("=" * 80)
        print(
            "The test corpus contains direct independent targets that have no "
            "training-derived neural output head. They will NOT be added to "
            "the model vocabulary. Complete test truth will be read directly "
            "from the source annotations instead."
        )

        for feature in sorted(unknown):
            print(
                f"  {feature:35s} support={observed_counts[feature]:,}"
            )

        print()

    return unseen_test_support


def verify_hierarchy_closure(
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
) -> None:
    """
    Ensure source feature sets already contain all ancestors required by the
    hierarchy. This prevents evaluation against inconsistent source targets.
    """

    problems: List[str] = []
    max_examples = 20

    for split_name in ("train", "validation", "test"):
        tagged_records, sentence_indices = split_sources[split_name]
        problem_count = 0

        for sentence_index in sentence_indices:
            for token_id, record in tagged_records.get(
                sentence_index,
                {},
            ).items():
                features = clean_features(record)

                if not features:
                    continue

                missing = missing_hierarchy_features(features)

                if not missing:
                    continue

                problem_count += 1

                if len(problems) < max_examples:
                    problems.append(
                        f"{split_name}: sentence={sentence_index}, "
                        f"token={token_id}, "
                        f"form={record.get('form')!r}, "
                        f"missing={sorted(missing)}"
                    )

        if problem_count:
            print(
                f"Hierarchy closure problems in {split_name}: "
                f"{problem_count:,} token(s)"
            )

    if problems:
        example_text = "\n".join(
            f"  - {problem}"
            for problem in problems
        )

        raise RuntimeError(
            "The input dataset is not hierarchy-closed. Fix the source tags "
            "before training so deterministic reduction/expansion is exact.\n"
            f"Examples:\n{example_text}"
        )


def print_split_statistics(
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
) -> None:
    print("=" * 80)
    print("DATASET SPLIT")
    print("=" * 80)

    for split_name in ("train", "validation", "test"):
        tagged_records, indices = split_sources[split_name]

        full_counts = count_feature_occurrences(
            tagged_records,
            indices,
            independent_only=False,
        )

        independent_counts = count_feature_occurrences(
            tagged_records,
            indices,
            independent_only=True,
        )

        empty_count = count_empty_records(
            tagged_records,
            indices,
        )

        noun_count = sum(
            len(tagged_records.get(index, {}))
            for index in indices
        )

        source_name = (
            "training file"
            if split_name in {"train", "validation"}
            else "test file"
        )

        print(
            f"{split_name:12s}: "
            f"{len(indices):,} sentences | "
            f"{noun_count:,} NOUN/PROPN tokens | "
            f"{sum(full_counts.values()):,} complete positives -> "
            f"{sum(independent_counts.values()):,} independent positives | "
            f"{empty_count:,} empty-feature tokens excluded | "
            f"source={source_name}"
        )

    print()


def print_prediction_label_statistics(
    prediction_labels: Sequence[str],
    full_labels: Sequence[str],
    train_tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    train_sentence_indices: Sequence[int],
) -> None:
    """Show which labels are neural outputs versus deterministic-only parents."""

    train_independent_counts = count_feature_occurrences(
        train_tagged_records,
        train_sentence_indices,
        independent_only=True,
    )

    prediction_set = set(prediction_labels)
    deterministic_only = [
        feature
        for feature in full_labels
        if feature not in prediction_set
    ]

    print("=" * 80)
    print("NEURAL OUTPUT FEATURES")
    print("=" * 80)
    print(
        f"Complete evaluation features: {len(full_labels)}"
    )
    print(
        f"Independent neural outputs: {len(prediction_labels)}"
    )
    print(
        f"Deterministic-only features in this training split: "
        f"{len(deterministic_only)}"
    )
    print()

    print(
        f"{'Feature':35s} "
        f"{'Independent train support':>26s}"
    )
    print("-" * 64)

    for feature in prediction_labels:
        print(
            f"{feature:35s} "
            f"{train_independent_counts[feature]:26d}"
        )

    if deterministic_only:
        print()
        print("Deterministic-only in this split:")

        for feature in deterministic_only:
            print(f"  - {feature}")

    print()


# =============================================================================
# Repeated-run and bootstrap helpers
# =============================================================================

def get_supervised_token_count_for_sentence(
    dataset: "SemanticFeatureDataset",
    sentence_index: int,
) -> int:
    """
    Count supervised first-subword targets for one source sentence.

    This mirrors SemanticFeatureDataset.__getitem__ exactly and is used to map
    flat prediction rows back to sentence clusters for test bootstrapping.
    """

    sentence = dataset.sentences[sentence_index]
    words, token_ids = get_sentence_words(sentence)

    encoding = dataset.tokenizer(
        words,
        is_split_into_words=True,
        truncation=True,
        max_length=dataset.max_length,
        add_special_tokens=True,
    )

    word_ids = encoding.word_ids()
    previous_word_id: Optional[int] = None
    sentence_records = dataset.tagged_records.get(sentence_index, {})

    count = 0

    for word_id in word_ids:
        if word_id is None:
            previous_word_id = word_id
            continue

        if word_id == previous_word_id:
            continue

        previous_word_id = word_id

        if not 0 <= word_id < len(token_ids):
            continue

        conllu_token_id = token_ids[word_id]
        record = sentence_records.get(conllu_token_id)

        if record is None:
            continue

        features = clean_features(record)

        if not features and EXCLUDE_EMPTY_FEATURE_RECORDS:
            continue

        count += 1

    return count


def build_sentence_row_slices(
    dataset: "SemanticFeatureDataset",
) -> List[slice]:
    """
    Map every dataset sentence to its contiguous flat supervised-token rows.
    """

    slices: List[slice] = []
    start = 0

    for sentence_index in dataset.sentence_indices:
        count = get_supervised_token_count_for_sentence(
            dataset,
            sentence_index,
        )
        stop = start + count
        slices.append(slice(start, stop))
        start = stop

    return slices


def summarise_repeated_metrics(
    metric_dicts: Sequence[Dict[str, float]],
) -> Dict[str, Dict[str, float]]:
    """Return mean/SD/min/max across repeated seeded runs."""

    if not metric_dicts:
        return {}

    common_keys = sorted(
        set.intersection(
            *[
                {
                    key
                    for key, value in metrics.items()
                    if isinstance(
                        value,
                        (float, int, np.floating, np.integer),
                    )
                }
                for metrics in metric_dicts
            ]
        )
    )

    summary: Dict[str, Dict[str, float]] = {}

    for key in common_keys:
        values = np.asarray(
            [float(metrics[key]) for metrics in metric_dicts],
            dtype=np.float64,
        )

        summary[key] = {
            "mean": float(values.mean()),
            "sd": float(values.std(ddof=1))
            if len(values) > 1
            else 0.0,
            "minimum": float(values.min()),
            "maximum": float(values.max()),
            "n_runs": int(len(values)),
        }

    return summary


def _metrics_from_confusion_counts(
    tp_by_label: np.ndarray,
    fp_by_label: np.ndarray,
    fn_by_label: np.ndarray,
) -> Dict[str, float]:
    """Calculate six headline metrics directly from labelwise counts."""

    tp_by_label = tp_by_label.astype(np.float64, copy=False)
    fp_by_label = fp_by_label.astype(np.float64, copy=False)
    fn_by_label = fn_by_label.astype(np.float64, copy=False)

    tp = float(tp_by_label.sum())
    fp = float(fp_by_label.sum())
    fn = float(fn_by_label.sum())

    precision_micro = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall_micro = tp / (tp + fn) if (tp + fn) > 0 else 0.0

    if precision_micro + recall_micro > 0:
        f1_micro = (
            2.0
            * precision_micro
            * recall_micro
            / (precision_micro + recall_micro)
        )
    else:
        f1_micro = 0.0

    precision_den = tp_by_label + fp_by_label
    recall_den = tp_by_label + fn_by_label

    precision_by_label = np.divide(
        tp_by_label,
        precision_den,
        out=np.zeros_like(tp_by_label, dtype=np.float64),
        where=precision_den > 0,
    )
    recall_by_label = np.divide(
        tp_by_label,
        recall_den,
        out=np.zeros_like(tp_by_label, dtype=np.float64),
        where=recall_den > 0,
    )

    f1_den = precision_by_label + recall_by_label
    f1_by_label = np.divide(
        2.0 * precision_by_label * recall_by_label,
        f1_den,
        out=np.zeros_like(precision_by_label, dtype=np.float64),
        where=f1_den > 0,
    )

    return {
        "precision_micro": float(precision_micro),
        "recall_micro": float(recall_micro),
        "f1_micro": float(f1_micro),
        "precision_macro": float(precision_by_label.mean()),
        "recall_macro": float(recall_by_label.mean()),
        "f1_macro": float(f1_by_label.mean()),
    }


def build_sentence_confusion_arrays(
    y_true_full: np.ndarray,
    run_predictions_full: Sequence[np.ndarray],
    sentence_slices: Sequence[slice],
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Precompute TP/FP/FN by [run, sentence, label] for fast cluster bootstrap.
    """

    n_runs = len(run_predictions_full)
    n_sentences = len(sentence_slices)
    n_labels = y_true_full.shape[1]

    tp = np.zeros(
        (n_runs, n_sentences, n_labels),
        dtype=np.int32,
    )
    fp = np.zeros_like(tp)
    fn = np.zeros_like(tp)

    for sentence_pos, row_slice in enumerate(sentence_slices):
        y_true_sentence = y_true_full[row_slice]

        for run_pos, y_pred_full in enumerate(run_predictions_full):
            y_pred_sentence = y_pred_full[row_slice]

            tp[run_pos, sentence_pos] = (
                (y_true_sentence == 1)
                & (y_pred_sentence == 1)
            ).sum(axis=0)

            fp[run_pos, sentence_pos] = (
                (y_true_sentence == 0)
                & (y_pred_sentence == 1)
            ).sum(axis=0)

            fn[run_pos, sentence_pos] = (
                (y_true_sentence == 1)
                & (y_pred_sentence == 0)
            ).sum(axis=0)

    return tp, fp, fn


def bootstrap_mean_test_metrics(
    y_true_full: np.ndarray,
    run_predictions_full: Sequence[np.ndarray],
    sentence_slices: Sequence[slice],
) -> Dict[str, Any]:
    """
    Sentence-cluster bootstrap CIs for the MEAN performance across run seeds.

    Each bootstrap replicate:
      1. samples test sentences with replacement;
      2. applies the SAME sampled sentence multiplicities to every trained run;
      3. computes each run's six hierarchy-expanded metrics;
      4. averages each metric across runs.

    Thus the interval quantifies held-out TEST-SAMPLE uncertainty around the
    mean performance of the repeated-run procedure. Training-seed variability is
    reported separately via mean and SD across runs.
    """

    if TEST_BOOTSTRAP_SAMPLES < 1:
        raise ValueError("TEST_BOOTSTRAP_SAMPLES must be at least 1.")

    if not 0.0 < TEST_BOOTSTRAP_CONFIDENCE < 1.0:
        raise ValueError(
            "TEST_BOOTSTRAP_CONFIDENCE must be strictly between 0 and 1."
        )

    if not run_predictions_full:
        raise ValueError(
            "At least one run prediction matrix is required for bootstrap."
        )

    n_sentences = len(sentence_slices)

    if n_sentences == 0:
        raise ValueError("No test sentences are available for bootstrap.")

    expected_rows = sum(
        row_slice.stop - row_slice.start
        for row_slice in sentence_slices
    )

    if expected_rows != y_true_full.shape[0]:
        raise RuntimeError(
            "Sentence slices do not cover the complete test truth matrix: "
            f"{expected_rows:,} rows vs {y_true_full.shape[0]:,}."
        )

    for run_pos, y_pred_full in enumerate(run_predictions_full):
        if y_pred_full.shape != y_true_full.shape:
            raise RuntimeError(
                f"Run {run_pos} prediction shape {y_pred_full.shape} does "
                f"not match test truth shape {y_true_full.shape}."
            )

    tp, fp, fn = build_sentence_confusion_arrays(
        y_true_full,
        run_predictions_full,
        sentence_slices,
    )

    rng = np.random.default_rng(TEST_BOOTSTRAP_SEED)

    metric_names = [
        "precision_micro",
        "recall_micro",
        "f1_micro",
        "precision_macro",
        "recall_macro",
        "f1_macro",
    ]

    bootstrap_values = {
        metric: np.empty(TEST_BOOTSTRAP_SAMPLES, dtype=np.float64)
        for metric in metric_names
    }

    for bootstrap_index in range(TEST_BOOTSTRAP_SAMPLES):
        sampled_sentences = rng.integers(
            0,
            n_sentences,
            size=n_sentences,
        )

        multiplicities = np.bincount(
            sampled_sentences,
            minlength=n_sentences,
        ).astype(np.int32)

        run_metric_values = {
            metric: []
            for metric in metric_names
        }

        for run_pos in range(len(run_predictions_full)):
            tp_by_label = np.tensordot(
                multiplicities,
                tp[run_pos],
                axes=(0, 0),
            )
            fp_by_label = np.tensordot(
                multiplicities,
                fp[run_pos],
                axes=(0, 0),
            )
            fn_by_label = np.tensordot(
                multiplicities,
                fn[run_pos],
                axes=(0, 0),
            )

            metrics = _metrics_from_confusion_counts(
                tp_by_label,
                fp_by_label,
                fn_by_label,
            )

            for metric in metric_names:
                run_metric_values[metric].append(metrics[metric])

        for metric in metric_names:
            bootstrap_values[metric][bootstrap_index] = float(
                np.mean(run_metric_values[metric])
            )

    alpha = 1.0 - TEST_BOOTSTRAP_CONFIDENCE
    lower_q = alpha / 2.0
    upper_q = 1.0 - lower_q

    intervals: Dict[str, Dict[str, float]] = {}

    for metric in metric_names:
        values = bootstrap_values[metric]

        intervals[metric] = {
            "bootstrap_mean": float(values.mean()),
            "bootstrap_sd": float(values.std(ddof=1))
            if len(values) > 1
            else 0.0,
            "ci_lower": float(np.quantile(values, lower_q)),
            "ci_upper": float(np.quantile(values, upper_q)),
            "confidence": float(TEST_BOOTSTRAP_CONFIDENCE),
            "bootstrap_samples": int(TEST_BOOTSTRAP_SAMPLES),
        }

    return {
        "bootstrap_unit": "sentence",
        "statistic": "mean_metric_across_repeated_training_runs",
        "seed": TEST_BOOTSTRAP_SEED,
        "n_test_sentences": n_sentences,
        "n_runs": len(run_predictions_full),
        "intervals": intervals,
    }


def make_json_serialisable(value: Any) -> Any:
    """Recursively convert NumPy scalars/arrays to ordinary JSON values."""

    if isinstance(value, dict):
        return {
            str(key): make_json_serialisable(item)
            for key, item in value.items()
        }

    if isinstance(value, (list, tuple)):
        return [
            make_json_serialisable(item)
            for item in value
        ]

    if isinstance(value, np.ndarray):
        return value.tolist()

    if isinstance(value, (np.floating, np.integer)):
        return value.item()

    return value


# =============================================================================
# Reporting helpers
# =============================================================================

def print_metric_dictionary(
    metrics: Dict[str, float],
) -> None:
    for key, value in sorted(metrics.items()):
        print(f"{key}: {value}")


def print_threshold_table(
    prediction_labels: Sequence[str],
    diagnostics: Dict[str, Dict[str, float]],
) -> None:
    print()
    print("=" * 100)
    print("VALIDATION-OPTIMISED THRESHOLDS")
    print("=" * 100)

    heading = (
        f"{'Feature':35s} "
        f"{'Threshold':>10s} "
        f"{'Support':>9s} "
        f"{'F1@0.5':>10s} "
        f"{'F1 opt':>10s} "
        f"{'Change':>10s}"
    )

    print(heading)
    print("-" * len(heading))

    for feature in prediction_labels:
        result = diagnostics[feature]

        print(
            f"{feature:35s} "
            f"{result['threshold']:10.2f} "
            f"{int(result['support']):9d} "
            f"{result['f1_default']:10.4f} "
            f"{result['f1_optimised']:10.4f} "
            f"{result['f1_change']:+10.4f}"
        )


def print_per_feature_table(
    title: str,
    labels: Sequence[str],
    results: Dict[str, Dict[str, float]],
) -> None:
    print()
    print("=" * 80)
    print(title)
    print("=" * 80)

    heading = (
        f"{'Feature':35s} "
        f"{'Precision':>10s} "
        f"{'Recall':>10s} "
        f"{'F1':>10s} "
        f"{'Support':>10s}"
    )

    print(heading)
    print("-" * len(heading))

    for feature in labels:
        result = results[feature]

        print(
            f"{feature:35s} "
            f"{result['precision']:10.4f} "
            f"{result['recall']:10.4f} "
            f"{result['f1']:10.4f} "
            f"{result['support']:10d}"
        )


def summarise_repeated_per_feature_metrics(
    run_documents: Sequence[Dict[str, Any]],
    result_key: str,
    labels: Sequence[str],
) -> Dict[str, Dict[str, float]]:
    """Summarise per-feature test precision/recall/F1 across repeated runs."""

    summary: Dict[str, Dict[str, float]] = {}

    for feature in labels:
        precision_values = np.asarray(
            [
                run_document[result_key][feature]["precision"]
                for run_document in run_documents
            ],
            dtype=np.float64,
        )
        recall_values = np.asarray(
            [
                run_document[result_key][feature]["recall"]
                for run_document in run_documents
            ],
            dtype=np.float64,
        )
        f1_values = np.asarray(
            [
                run_document[result_key][feature]["f1"]
                for run_document in run_documents
            ],
            dtype=np.float64,
        )
        supports = {
            int(run_document[result_key][feature]["support"])
            for run_document in run_documents
        }

        if len(supports) != 1:
            raise RuntimeError(
                f"Test support changed across runs for feature {feature!r}: "
                f"{sorted(supports)}"
            )

        summary[feature] = {
            "precision_mean": float(precision_values.mean()),
            "precision_sd": float(precision_values.std(ddof=1))
            if len(precision_values) > 1
            else 0.0,
            "recall_mean": float(recall_values.mean()),
            "recall_sd": float(recall_values.std(ddof=1))
            if len(recall_values) > 1
            else 0.0,
            "f1_mean": float(f1_values.mean()),
            "f1_sd": float(f1_values.std(ddof=1))
            if len(f1_values) > 1
            else 0.0,
            "f1_min": float(f1_values.min()),
            "f1_max": float(f1_values.max()),
            "support": int(next(iter(supports))),
        }

    return summary


def print_repeated_per_feature_table(
    title: str,
    labels: Sequence[str],
    summary: Dict[str, Dict[str, float]],
) -> None:
    """Print repeated-run mean/SD test performance for each feature."""

    print()
    print("=" * 118)
    print(title)
    print("=" * 118)

    heading = (
        f"{'Feature':35s} "
        f"{'P mean':>8s} "
        f"{'P SD':>8s} "
        f"{'R mean':>8s} "
        f"{'R SD':>8s} "
        f"{'F1 mean':>8s} "
        f"{'F1 SD':>8s} "
        f"{'F1 min':>8s} "
        f"{'F1 max':>8s} "
        f"{'Support':>8s}"
    )

    print(heading)
    print("-" * len(heading))

    for feature in labels:
        result = summary[feature]
        print(
            f"{feature:35s} "
            f"{result['precision_mean']:8.4f} "
            f"{result['precision_sd']:8.4f} "
            f"{result['recall_mean']:8.4f} "
            f"{result['recall_sd']:8.4f} "
            f"{result['f1_mean']:8.4f} "
            f"{result['f1_sd']:8.4f} "
            f"{result['f1_min']:8.4f} "
            f"{result['f1_max']:8.4f} "
            f"{int(result['support']):8d}"
        )


# =============================================================================
# Main
# =============================================================================

def main() -> None:
    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )
    RUNS_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    validate_feature_hierarchy()
    check_cuda()

    if not RUN_SEEDS:
        raise ValueError("RUN_SEEDS must contain at least one integer seed.")

    if len(set(RUN_SEEDS)) != len(RUN_SEEDS):
        raise ValueError("RUN_SEEDS contains duplicate seeds.")

    # -------------------------------------------------------------------------
    # Load independent TRAIN and held-out TEST corpora
    # -------------------------------------------------------------------------

    print("=" * 80)
    print("LOADING DATA")
    print("=" * 80)

    train_sentences = load_conllu(TRAIN_CONLLU_PATH)
    test_sentences = load_conllu(TEST_CONLLU_PATH)

    train_tagged_records = load_tagged_records(TRAIN_JSONL_PATH)
    test_tagged_records = load_tagged_records(TEST_JSONL_PATH)

    validate_feature_switches(
        train_tagged_records,
        test_tagged_records,
    )

    print(
        "Training CoNLL-U sentences: "
        f"{len(train_sentences):,}"
    )
    print(
        "Test CoNLL-U sentences: "
        f"{len(test_sentences):,}"
    )
    print(
        "Training sentences represented in tagged JSONL: "
        f"{len(train_tagged_records):,}"
    )
    print(
        "Test sentences represented in tagged JSONL: "
        f"{len(test_tagged_records):,}"
    )

    train_target_record_count = sum(
        len(records)
        for records in train_tagged_records.values()
    )
    test_target_record_count = sum(
        len(records)
        for records in test_tagged_records.values()
    )

    print(
        "Training tagged NOUN/PROPN records: "
        f"{train_target_record_count:,}"
    )
    print(
        "Test tagged NOUN/PROPN records: "
        f"{test_target_record_count:,}"
    )
    print()

    # -------------------------------------------------------------------------
    # Fixed sentence-level TRAIN/VALIDATION split; TEST remains untouched
    # -------------------------------------------------------------------------

    eligible_train_indices = get_eligible_sentence_indices(
        train_sentences,
        train_tagged_records,
    )
    eligible_test_indices = get_eligible_sentence_indices(
        test_sentences,
        test_tagged_records,
    )

    print(
        "Eligible training-file sentences with at least one non-empty "
        "feature target: "
        f"{len(eligible_train_indices):,}"
    )
    print(
        "Eligible test-file sentences with at least one non-empty "
        "feature target: "
        f"{len(eligible_test_indices):,}"
    )

    train_validation_split = make_train_validation_split(
        eligible_train_indices,
        train_tagged_records,
    )

    train_indices = train_validation_split["train"]
    validation_indices = train_validation_split["validation"]
    test_indices = list(eligible_test_indices)

    split_sources = {
        "train": (train_tagged_records, train_indices),
        "validation": (train_tagged_records, validation_indices),
        "test": (test_tagged_records, test_indices),
    }

    split_document = {
        "split_unit": "sentence",
        "stratification": "iterative_multilabel_sentence_presence",
        "split_seed_requested": SPLIT_SEED,
        "split_seed_used": train_validation_split["split_seed_used"],
        "split_attempt": train_validation_split["attempt"],
        "validation_fraction": VALIDATION_FRACTION,
        "feature_switches": dict(sorted(FEATURE_SWITCHES.items())),
        "prevalence_error": train_validation_split["prevalence_error"],
        "stratification_labels": (
            train_validation_split["stratification_labels"]
        ),
        "train_jsonl": str(TRAIN_JSONL_PATH),
        "test_jsonl": str(TEST_JSONL_PATH),
        "train_conllu": str(TRAIN_CONLLU_PATH),
        "test_conllu": str(TEST_CONLLU_PATH),
        "index_spaces": {
            "train": "training corpus",
            "validation": "training corpus",
            "test": "test corpus",
        },
        "train": train_indices,
        "validation": validation_indices,
        "test": test_indices,
    }

    with SPLIT_PATH.open("w", encoding="utf-8") as handle:
        json.dump(
            make_json_serialisable(split_document),
            handle,
            ensure_ascii=False,
            indent=2,
        )

    # The reduction is exact only when source data are hierarchy-closed.
    verify_hierarchy_closure(split_sources)

    # -------------------------------------------------------------------------
    # Separate complete and neural-output vocabularies
    # -------------------------------------------------------------------------

    training_file_prediction_labels = build_prediction_label_vocabulary(
        train_tagged_records,
        eligible_train_indices,
    )

    # Vocabularies are derived from TRAIN only, never validation/test.
    full_labels = build_full_label_vocabulary(
        train_tagged_records,
        train_indices,
    )

    prediction_labels = build_prediction_label_vocabulary(
        train_tagged_records,
        train_indices,
    )

    verify_full_label_coverage(
        full_labels,
        split_sources,
    )

    unseen_test_independent_labels = verify_prediction_label_coverage(
        prediction_labels,
        split_sources,
        training_file_prediction_labels=training_file_prediction_labels,
    )

    prediction_label2id = {
        label: index
        for index, label in enumerate(prediction_labels)
    }

    prediction_id2label = {
        index: label
        for label, index in prediction_label2id.items()
    }

    full_label2id = {
        label: index
        for index, label in enumerate(full_labels)
    }

    hierarchy_matrix = build_hierarchy_expansion_matrix(
        prediction_labels,
        full_labels,
    )

    label_document = {
        "labels": prediction_labels,
        "label2id": prediction_label2id,
        "id2label": {
            str(key): value
            for key, value in prediction_id2label.items()
        },
        "prediction_labels": prediction_labels,
        "prediction_label2id": prediction_label2id,
        "full_labels": full_labels,
        "full_label2id": full_label2id,
        "feature_parents": {
            child: sorted(parents)
            for child, parents in sorted(FEATURE_PARENTS.items())
        },
        "target_representation": "per_token_independent_features",
        "split_unit": "sentence",
        "feature_switches": dict(sorted(FEATURE_SWITCHES.items())),
        "disabled_features": sorted(
            feature
            for feature, enabled in FEATURE_SWITCHES.items()
            if not enabled
        ),
    }

    with LABELS_PATH.open("w", encoding="utf-8") as handle:
        json.dump(
            label_document,
            handle,
            ensure_ascii=False,
            indent=2,
        )

    print_split_statistics(split_sources)

    print_prediction_label_statistics(
        prediction_labels,
        full_labels,
        train_tagged_records,
        train_indices,
    )

    # -------------------------------------------------------------------------
    # Tokeniser and fixed datasets
    # -------------------------------------------------------------------------

    tokenizer = AutoTokenizer.from_pretrained(
        MODEL_NAME,
        use_fast=True,
        add_prefix_space=True,
    )

    train_dataset = SemanticFeatureDataset(
        sentences=train_sentences,
        sentence_indices=train_indices,
        tagged_records=train_tagged_records,
        tokenizer=tokenizer,
        label2id=prediction_label2id,
        max_length=MAX_LENGTH,
    )

    validation_dataset = SemanticFeatureDataset(
        sentences=train_sentences,
        sentence_indices=validation_indices,
        tagged_records=train_tagged_records,
        tokenizer=tokenizer,
        label2id=prediction_label2id,
        max_length=MAX_LENGTH,
    )

    test_dataset = SemanticFeatureDataset(
        sentences=test_sentences,
        sentence_indices=test_indices,
        tagged_records=test_tagged_records,
        tokenizer=tokenizer,
        label2id=prediction_label2id,
        max_length=MAX_LENGTH,
    )

    data_collator = MultiLabelTokenCollator(
        tokenizer=tokenizer,
        num_labels=len(prediction_labels),
    )

    # Complete held-out gold truth is fixed across all training runs.
    test_true_full = build_full_truth_matrix_for_dataset(
        test_dataset,
        full_labels,
    )

    test_sentence_slices = build_sentence_row_slices(
        test_dataset,
    )

    test_slice_rows = sum(
        row_slice.stop - row_slice.start
        for row_slice in test_sentence_slices
    )

    if test_slice_rows != test_true_full.shape[0]:
        raise RuntimeError(
            "Test sentence-cluster mapping does not align with source truth: "
            f"{test_slice_rows:,} mapped rows vs "
            f"{test_true_full.shape[0]:,} truth rows."
        )

    # -------------------------------------------------------------------------
    # Repeated fine-tuning runs
    # -------------------------------------------------------------------------

    print("=" * 80)
    print("REPEATED FINE-TUNING")
    print("=" * 80)
    print(f"Runs: {len(RUN_SEEDS)}")
    print(f"Seeds: {RUN_SEEDS}")
    print(
        "Train/validation split is fixed across all runs; only the "
        "fine-tuning seed changes."
    )
    print()

    use_bf16 = torch.cuda.is_bf16_supported()

    all_run_documents: List[Dict[str, Any]] = []
    all_test_metric_dicts: List[Dict[str, float]] = []
    all_validation_metric_dicts: List[Dict[str, float]] = []
    all_test_predictions_full: List[np.ndarray] = []

    work_root = OUTPUT_DIR / "_trainer_work"
    work_root.mkdir(parents=True, exist_ok=True)

    for run_number, run_seed in enumerate(RUN_SEEDS, start=1):
        print()
        print("=" * 100)
        print(
            f"RUN {run_number}/{len(RUN_SEEDS)} | "
            f"SEED {run_seed}"
        )
        print("=" * 100)

        set_seed(run_seed)

        run_work_dir = work_root / f"seed_{run_seed}"
        run_result_path = RUNS_DIR / f"seed_{run_seed}.json"

        if run_work_dir.exists():
            shutil.rmtree(run_work_dir)

        model = RobertaMultiLabelModel(
            model_name=MODEL_NAME,
            num_labels=len(prediction_labels),
            id2label=prediction_id2label,
            label2id=prediction_label2id,
        )

        training_args = TrainingArguments(
            output_dir=str(run_work_dir),

            learning_rate=LEARNING_RATE,
            lr_scheduler_type=LEARNING_RATE_SCHEDULER,
            weight_decay=WEIGHT_DECAY,

            per_device_train_batch_size=TRAIN_BATCH_SIZE,
            per_device_eval_batch_size=EVAL_BATCH_SIZE,

            gradient_accumulation_steps=(
                GRADIENT_ACCUMULATION_STEPS
            ),

            num_train_epochs=NUM_EPOCHS,

            eval_strategy=EVAL_STRATEGY,
            save_strategy="epoch",
            logging_strategy="steps",
            logging_steps=50,

            load_best_model_at_end=True,

            # Model selection is performed on VALIDATION only, using complete
            # hierarchy-expanded macro F1 at the fixed 0.5 threshold.
            metric_for_best_model="f1_macro",
            greater_is_better=True,

            save_total_limit=2,

            bf16=use_bf16,
            fp16=not use_bf16,

            dataloader_num_workers=4,
            dataloader_pin_memory=True,

            optim="adamw_torch",
            report_to="none",

            seed=run_seed,
            data_seed=run_seed,

            remove_unused_columns=False,
            eval_accumulation_steps=16,
            warmup_steps = WARMUP_STEPS,
        )

        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_dataset,
            eval_dataset=validation_dataset,
            processing_class=tokenizer,
            data_collator=data_collator,
            compute_metrics=make_compute_metrics(
                prediction_labels,
                hierarchy_matrix,
            ),
        )

        trainer.train()

        # ---------------------------------------------------------------------
        # Validation: first report 0.5, then calibrate thresholds on validation
        # ---------------------------------------------------------------------

        validation_output = trainer.predict(
            validation_dataset,
            metric_key_prefix="validation_default",
        )

        (
            validation_probabilities,
            validation_true_independent,
        ) = extract_valid_token_arrays(
            validation_output.predictions,
            validation_output.label_ids,
        )

        default_threshold_vector = np.full(
            len(prediction_labels),
            DEFAULT_PREDICTION_THRESHOLD,
            dtype=np.float32,
        )

        validation_default_metrics = (
            calculate_hierarchical_metrics_from_probabilities(
                probabilities=validation_probabilities,
                y_true_independent=validation_true_independent,
                threshold_vector=default_threshold_vector,
                hierarchy_matrix=hierarchy_matrix,
            )
        )

        (
            optimised_thresholds,
            threshold_diagnostics,
        ) = optimise_feature_thresholds(
            probabilities=validation_probabilities,
            y_true_independent=validation_true_independent,
            prediction_labels=prediction_labels,
        )

        threshold_vector = make_threshold_vector(
            prediction_labels,
            optimised_thresholds,
        )

        validation_optimised_metrics = (
            calculate_hierarchical_metrics_from_probabilities(
                probabilities=validation_probabilities,
                y_true_independent=validation_true_independent,
                threshold_vector=threshold_vector,
                hierarchy_matrix=hierarchy_matrix,
            )
        )

        print_threshold_table(
            prediction_labels,
            threshold_diagnostics,
        )

        print()
        print("VALIDATION @ 0.5")
        print_metric_dictionary(validation_default_metrics)

        print()
        print("VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS")
        print_metric_dictionary(validation_optimised_metrics)

        # ---------------------------------------------------------------------
        # Held-out TEST: thresholds are frozen
        # ---------------------------------------------------------------------

        test_output = trainer.predict(
            test_dataset,
            metric_key_prefix="test_default",
        )

        test_probabilities, test_true_independent = (
            extract_valid_token_arrays(
                test_output.predictions,
                test_output.label_ids,
            )
        )

        if test_true_full.shape[0] != test_probabilities.shape[0]:
            raise RuntimeError(
                "Test source-truth alignment failed: predictions contain "
                f"{test_probabilities.shape[0]:,} supervised tokens but "
                f"source truth contains {test_true_full.shape[0]:,}."
            )

        # Explicit test-at-0.5 diagnostic.
        test_default_metrics = (
            calculate_hierarchical_metrics_from_probabilities(
                probabilities=test_probabilities,
                y_true_independent=test_true_independent,
                threshold_vector=default_threshold_vector,
                hierarchy_matrix=hierarchy_matrix,
                y_true_full=test_true_full,
            )
        )

        # Final per-run test result uses validation-calibrated thresholds.
        test_optimised_metrics = (
            calculate_hierarchical_metrics_from_probabilities(
                probabilities=test_probabilities,
                y_true_independent=test_true_independent,
                threshold_vector=threshold_vector,
                hierarchy_matrix=hierarchy_matrix,
                y_true_full=test_true_full,
            )
        )

        test_pred_independent = threshold_probabilities(
            test_probabilities,
            threshold_vector,
        )

        test_pred_full = expand_binary_feature_matrix(
            test_pred_independent,
            hierarchy_matrix,
        )

        all_test_predictions_full.append(
            test_pred_full.astype(np.int8, copy=True)
        )

        per_feature_full = calculate_per_feature_metrics_from_binary(
            y_true=test_true_full,
            y_pred=test_pred_full,
            labels=full_labels,
        )

        per_feature_independent = (
            calculate_per_feature_metrics_from_binary(
                y_true=test_true_independent,
                y_pred=test_pred_independent,
                labels=prediction_labels,
            )
        )

        print()
        print("TEST @ 0.5 (DIAGNOSTIC)")
        print_metric_dictionary(test_default_metrics)

        print()
        print("TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS")
        print_metric_dictionary(test_optimised_metrics)

        if PRINT_PER_RUN_FEATURE_TABLES:
            print_per_feature_table(
                title=(
                    f"RUN {run_number} / SEED {run_seed}: TEST PERFORMANCE "
                    "BY COMPLETE FEATURE (AFTER INHERITANCE)"
                ),
                labels=full_labels,
                results=per_feature_full,
            )
            print_per_feature_table(
                title=(
                    f"RUN {run_number} / SEED {run_seed}: TEST PERFORMANCE "
                    "BY INDEPENDENT NEURAL OUTPUT"
                ),
                labels=prediction_labels,
                results=per_feature_independent,
            )

        # ---------------------------------------------------------------------
        # Save a neutral reference model, not a cherry-picked best seed
        # ---------------------------------------------------------------------

        is_reference_run = (
            SAVE_REFERENCE_MODEL
            and run_number == 1
        )

        if is_reference_run:
            if REFERENCE_MODEL_DIR.exists():
                shutil.rmtree(REFERENCE_MODEL_DIR)

            trainer.save_model(str(REFERENCE_MODEL_DIR))
            tokenizer.save_pretrained(str(REFERENCE_MODEL_DIR))

            with (
                REFERENCE_MODEL_DIR / "semantic_features.json"
            ).open(
                "w",
                encoding="utf-8",
            ) as handle:
                json.dump(
                    label_document,
                    handle,
                    ensure_ascii=False,
                    indent=2,
                )

            reference_threshold_document = {
                "seed": run_seed,
                "selection_policy": (
                    "first_predeclared_seed_not_best_test_run"
                ),
                "optimised_on": "validation",
                "objective": "per_feature_binary_f1",
                "thresholds": optimised_thresholds,
                "diagnostics": threshold_diagnostics,
            }

            with (
                REFERENCE_MODEL_DIR / "prediction_thresholds.json"
            ).open(
                "w",
                encoding="utf-8",
            ) as handle:
                json.dump(
                    make_json_serialisable(
                        reference_threshold_document
                    ),
                    handle,
                    ensure_ascii=False,
                    indent=2,
                )

        run_document = {
            "run_number": run_number,
            "seed": run_seed,
            "is_reference_model": is_reference_run,
            "model": MODEL_NAME,
            "target_representation": (
                "per_token_independent_features"
            ),
            "feature_switches": dict(sorted(FEATURE_SWITCHES.items())),
            "disabled_features": sorted(
                feature
                for feature, enabled in FEATURE_SWITCHES.items()
                if not enabled
            ),
            "split": {
                "unit": "sentence",
                "split_seed": (
                    train_validation_split["split_seed_used"]
                ),
                "validation_fraction": VALIDATION_FRACTION,
                "train_sentences": len(train_indices),
                "validation_sentences": len(validation_indices),
                "test_sentences": len(test_indices),
            },
            "threshold_calibration": {
                "data": "validation_only",
                "objective": "per_feature_binary_f1",
                "thresholds": optimised_thresholds,
                "diagnostics": threshold_diagnostics,
            },
            "validation_metrics_at_0_5": (
                validation_default_metrics
            ),
            "validation_metrics_optimised": (
                validation_optimised_metrics
            ),
            "test_metrics_at_0_5": test_default_metrics,
            "test_metrics_optimised": test_optimised_metrics,
            "per_feature_complete": per_feature_full,
            "per_feature_independent": (
                per_feature_independent
            ),
            "unseen_test_independent_labels": (
                unseen_test_independent_labels
            ),
        }

        with run_result_path.open(
            "w",
            encoding="utf-8",
        ) as handle:
            json.dump(
                make_json_serialisable(run_document),
                handle,
                ensure_ascii=False,
                indent=2,
            )

        all_run_documents.append(run_document)
        all_test_metric_dicts.append(test_optimised_metrics)
        all_validation_metric_dicts.append(
            validation_optimised_metrics
        )

        # Release run-specific GPU state before initialising the next model.
        del test_output
        del validation_output
        del trainer
        del model

        gc.collect()
        torch.cuda.empty_cache()

        # Checkpoints were needed only to recover the best validation epoch.
        # Remove them after each run to avoid storing dozens of RoBERTa-large
        # copies. The neutral first-seed reference model was saved separately.
        if run_work_dir.exists():
            shutil.rmtree(run_work_dir)

    if work_root.exists() and not any(work_root.iterdir()):
        work_root.rmdir()

    # -------------------------------------------------------------------------
    # Repeated-run summary: stochastic training variability
    # -------------------------------------------------------------------------

    validation_summary = summarise_repeated_metrics(
        all_validation_metric_dicts
    )
    test_summary = summarise_repeated_metrics(
        all_test_metric_dicts
    )

    print()
    print("=" * 100)
    print("REPEATED-RUN TEST SUMMARY")
    print("=" * 100)

    headline_metrics = [
        "precision_micro",
        "recall_micro",
        "f1_micro",
        "precision_macro",
        "recall_macro",
        "f1_macro",
    ]

    print(
        f"{'Metric':25s} "
        f"{'Mean':>10s} "
        f"{'SD':>10s} "
        f"{'Min':>10s} "
        f"{'Max':>10s}"
    )
    print("-" * 70)

    for metric in headline_metrics:
        result = test_summary[metric]

        print(
            f"{metric:25s} "
            f"{result['mean']:10.4f} "
            f"{result['sd']:10.4f} "
            f"{result['minimum']:10.4f} "
            f"{result['maximum']:10.4f}"
        )

    # -------------------------------------------------------------------------
    # Repeated-run per-feature test summaries
    # -------------------------------------------------------------------------

    per_feature_complete_summary = summarise_repeated_per_feature_metrics(
        all_run_documents,
        result_key="per_feature_complete",
        labels=full_labels,
    )
    per_feature_independent_summary = summarise_repeated_per_feature_metrics(
        all_run_documents,
        result_key="per_feature_independent",
        labels=prediction_labels,
    )

    print_repeated_per_feature_table(
        title=(
            "REPEATED-RUN TEST PERFORMANCE BY COMPLETE FEATURE "
            "(AFTER INHERITANCE)"
        ),
        labels=full_labels,
        summary=per_feature_complete_summary,
    )

    print_repeated_per_feature_table(
        title=(
            "REPEATED-RUN TEST PERFORMANCE BY INDEPENDENT NEURAL OUTPUT"
        ),
        labels=prediction_labels,
        summary=per_feature_independent_summary,
    )

    # -------------------------------------------------------------------------
    # Sentence-cluster bootstrap: held-out test-sample uncertainty
    # -------------------------------------------------------------------------

    print()
    print("=" * 100)
    print("SENTENCE-CLUSTER BOOTSTRAP ON HELD-OUT TEST SET")
    print("=" * 100)

    bootstrap_results = bootstrap_mean_test_metrics(
        y_true_full=test_true_full,
        run_predictions_full=all_test_predictions_full,
        sentence_slices=test_sentence_slices,
    )

    print(
        f"Bootstrap samples: {TEST_BOOTSTRAP_SAMPLES:,}"
    )
    print(
        f"Confidence level : "
        f"{TEST_BOOTSTRAP_CONFIDENCE:.1%}"
    )
    print(
        "Bootstrap unit   : sentence (all eligible NOUN/PROPN targets "
        "from a sampled sentence move together)"
    )
    print()

    ci_percent = int(round(TEST_BOOTSTRAP_CONFIDENCE * 100))

    print(
        f"{'Metric':25s} "
        f"{'Run mean':>10s} "
        f"{'Run SD':>10s} "
        f"{str(ci_percent) + '% CI low':>12s} "
        f"{str(ci_percent) + '% CI high':>12s}"
    )
    print("-" * 78)

    for metric in headline_metrics:
        repeated = test_summary[metric]
        interval = bootstrap_results["intervals"][metric]

        print(
            f"{metric:25s} "
            f"{repeated['mean']:10.4f} "
            f"{repeated['sd']:10.4f} "
            f"{interval['ci_lower']:12.4f} "
            f"{interval['ci_upper']:12.4f}"
        )

    # -------------------------------------------------------------------------
    # Save experiment-level results
    # -------------------------------------------------------------------------

    bootstrap_document = {
        "model": MODEL_NAME,
        "run_seeds": RUN_SEEDS,
        "split_seed": train_validation_split["split_seed_used"],
        "test_bootstrap": bootstrap_results,
    }

    with BOOTSTRAP_RESULTS_PATH.open(
        "w",
        encoding="utf-8",
    ) as handle:
        json.dump(
            make_json_serialisable(bootstrap_document),
            handle,
            ensure_ascii=False,
            indent=2,
        )

    repeated_document = {
        "model": MODEL_NAME,
        "experimental_design": {
            "test_set": "fixed_external_held_out_file",
            "train_validation_split_unit": "sentence",
            "train_validation_stratification": (
                "iterative_multilabel_sentence_presence"
            ),
            "split_seed": (
                train_validation_split["split_seed_used"]
            ),
            "validation_fraction": VALIDATION_FRACTION,
            "number_of_runs": len(RUN_SEEDS),
            "run_seeds": RUN_SEEDS,
            "same_split_for_every_run": True,
            "threshold_calibration": (
                "per_feature_binary_f1_on_validation_only"
            ),
            "test_bootstrap_unit": "sentence",
            "test_bootstrap_samples": TEST_BOOTSTRAP_SAMPLES,
            "test_bootstrap_confidence": (
                TEST_BOOTSTRAP_CONFIDENCE
            ),
        },
        "data_sources": {
            "train_jsonl": str(TRAIN_JSONL_PATH),
            "test_jsonl": str(TEST_JSONL_PATH),
            "train_conllu": str(TRAIN_CONLLU_PATH),
            "test_conllu": str(TEST_CONLLU_PATH),
        },
        "split_sizes": {
            "train_sentences": len(train_indices),
            "validation_sentences": len(validation_indices),
            "test_sentences": len(test_indices),
        },
        "prediction_labels": prediction_labels,
        "full_labels": full_labels,
        "feature_switches": dict(sorted(FEATURE_SWITCHES.items())),
        "disabled_features": sorted(
            feature
            for feature, enabled in FEATURE_SWITCHES.items()
            if not enabled
        ),
        "unseen_test_independent_labels": (
            unseen_test_independent_labels
        ),
        "validation_repeated_run_summary": validation_summary,
        "test_repeated_run_summary": test_summary,
        "test_per_feature_complete_repeated_run_summary": (
            per_feature_complete_summary
        ),
        "test_per_feature_independent_repeated_run_summary": (
            per_feature_independent_summary
        ),
        "test_bootstrap": bootstrap_results,
        "runs": [
            {
                "run_number": run_document["run_number"],
                "seed": run_document["seed"],
                "is_reference_model": (
                    run_document["is_reference_model"]
                ),
                "result_file": str(
                    RUNS_DIR
                    / f"seed_{run_document['seed']}.json"
                ),
                "validation_metrics_optimised": (
                    run_document[
                        "validation_metrics_optimised"
                    ]
                ),
                "test_metrics_at_0_5": (
                    run_document["test_metrics_at_0_5"]
                ),
                "test_metrics_optimised": (
                    run_document["test_metrics_optimised"]
                ),
            }
            for run_document in all_run_documents
        ],
    }

    with REPEATED_RESULTS_PATH.open(
        "w",
        encoding="utf-8",
    ) as handle:
        json.dump(
            make_json_serialisable(repeated_document),
            handle,
            ensure_ascii=False,
            indent=2,
        )

    print()
    print("=" * 100)
    print("OUTPUTS")
    print("=" * 100)
    print(
        "Fixed sentence split:\n"
        f"  {SPLIT_PATH.resolve()}"
    )
    print(
        "Semantic feature metadata:\n"
        f"  {LABELS_PATH.resolve()}"
    )
    print(
        "Per-run results:\n"
        f"  {RUNS_DIR.resolve()}"
    )
    print(
        "Repeated-run summary:\n"
        f"  {REPEATED_RESULTS_PATH.resolve()}"
    )
    print(
        "Test bootstrap confidence intervals:\n"
        f"  {BOOTSTRAP_RESULTS_PATH.resolve()}"
    )

    if SAVE_REFERENCE_MODEL:
        print(
            "Neutral reference model (first predeclared seed; not "
            "best-test selected):\n"
            f"  {REFERENCE_MODEL_DIR.resolve()}"
        )


if __name__ == "__main__":
    main()

/root/.pyenv/versions/3.10.16/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

================================================================================
CUDA
================================================================================
PyTorch version: 2.13.0+cu130
CUDA available: True
CUDA runtime: 13.0
GPU: NVIDIA GeForce RTX 5070 Ti
VRAM: 15.92 GiB

================================================================================
LOADING DATA
================================================================================
================================================================================
FEATURE SWITCHES
================================================================================
Disabled features: Rigidity, Shape, State, State_of_Matter
All unlisted features are enabled.

Training CoNLL-U sentences: 12,544
Test CoNLL-U sentences: 2,077
Training sentences represented in tagged JSONL: 11,511
Test sentences represented in tagged JSONL: 1,815
Training tagged NOUN/PROPN records: 47,371
Test tagged NOUN/PROPN records: 6,198

Eligible training-file sentences with at least one non-empty feature target: 11,198
Eligible test-file sentences with at least one non-empty feature target: 1,759

Sentence-level multilabel-stratified train/validation split:
  Eligible training sentences : 11,198
  Target validation sentences : 2,240
  Actual validation sentences : 2,313
  Training sentences retained : 8,885
  Split seed used             : 42
  Stratification labels       : 37
  Coverage-rejected attempts  : 0
  Mean relative prevalence error: 0.008441

Feature                              All sent.      Train      Valid    Valid %
--------------------------------------------------------------------------------
Abstract                                  4469       3575        894      0.200
Animal                                     621        497        124      0.200
Animate                                     52         42         10      0.192
Artefact                                  1778       1422        356      0.200
Body_Part                                  265        212         53      0.200
Comestible                                 534        427        107      0.200
Communication                             1984       1587        397      0.200
Currency                                   197        158         39      0.198
Duration                                  1338       1070        268      0.200
Elongated                                  649        519        130      0.200
Eventive                                  3749       2999        750      0.200
Feminine                                   733        586        147      0.201
Fluid                                       87         70         17      0.195
Garment                                     62         50         12      0.194
Inanimate                                 4282       3425        857      0.200
Internal_Control                           107         86         21      0.196
Language                                    27         22          5      0.185
Location                                  3232       2585        647      0.200
Machine                                    694        555        139      0.200
Masculine                                 1829       1463        366      0.200
Natural                                    326        261         65      0.199
Natural_Force                              142        114         28      0.197
Non_Rigid                                 1200        960        240      0.200
Organisation                              3003       2402        601      0.200
Plant                                       66         53         13      0.197
Point_in_Time                             1211        969        242      0.200
Pointy                                      82         66         16      0.195
Question                                   161        129         32      0.199
Rigid                                     1965       1572        393      0.200
Solid                                     4618       3694        924      0.200
Sound                                      187        150         37      0.198
Statement                                 1115        892        223      0.200
Substance                                  826        661        165      0.200
Time                                        81         65         16      0.198
Unspecified_Gender_or_Neuter              2592       2074        518      0.200
Vehicle                                    344        275         69      0.201
Web_Location                               252        202         50      0.198

Actual validation sentence fraction: 0.2066


================================================================================
HELD-OUT TEST LABEL COVERAGE WARNING
================================================================================
The test corpus contains direct independent targets that have no training-derived neural output head. They will NOT be added to the model vocabulary. Complete test truth will be read directly from the source annotations instead.
  Human                               support=1

================================================================================
DATASET SPLIT
================================================================================
train       : 8,885 sentences | 37,581 NOUN/PROPN tokens | 124,956 complete positives -> 54,319 independent positives | 2,686 empty-feature tokens excluded | source=training file
validation  : 2,313 sentences | 9,408 NOUN/PROPN tokens | 31,274 complete positives -> 13,650 independent positives | 675 empty-feature tokens excluded | source=training file
test        : 1,759 sentences | 6,127 NOUN/PROPN tokens | 20,568 complete positives -> 8,826 independent positives | 423 empty-feature tokens excluded | source=test file

================================================================================
NEURAL OUTPUT FEATURES
================================================================================
Complete evaluation features: 39
Independent neural outputs: 37
Deterministic-only features in this training split: 2

Feature                              Independent train support
----------------------------------------------------------------
Abstract                                                  5754
Animal                                                     691
Animate                                                     46
Artefact                                                  1866
Body_Part                                                  318
Comestible                                                 671
Communication                                             2041
Currency                                                   179
Duration                                                  1393
Elongated                                                  632
Eventive                                                  4258
Feminine                                                   867
Fluid                                                       84
Garment                                                     60
Inanimate                                                 5851
Internal_Control                                            91
Language                                                    23
Location                                                  4733
Machine                                                    738
Masculine                                                 2684
Natural                                                    307
Natural_Force                                              130
Non_Rigid                                                 1378
Organisation                                              4425
Plant                                                       68
Point_in_Time                                             1257
Pointy                                                      78
Question                                                   130
Rigid                                                     2165
Solid                                                     5807
Sound                                                      169
Statement                                                 1038
Substance                                                  913
Time                                                        67
Unspecified_Gender_or_Neuter                              2826
Vehicle                                                    359
Web_Location                                               222

Deterministic-only in this split:
  - Concrete
  - Human

================================================================================
REPEATED FINE-TUNING
================================================================================
Runs: 30
Seeds: [11, 23, 37, 53, 71, 89, 107, 127, 149, 173, 197, 223, 251, 281, 313, 347, 383, 421, 461, 503, 547, 593, 641, 691, 743, 797, 853, 911, 971, 1031]
Train/validation split is fixed across all runs; only the fine-tuning seed changes.


====================================================================================================
RUN 1/30 | SEED 11
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1004.37it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.62      1405     0.8932     0.8978    +0.0046
Animal                                    0.39       184     0.9503     0.9532    +0.0029
Animate                                   0.46        13     0.8696     0.9167    +0.0471
Artefact                                  0.61       503     0.8998     0.9063    +0.0065
Body_Part                                 0.31        74     0.9167     0.9262    +0.0095
Comestible                                0.27       157     0.9712     0.9745    +0.0033
Communication                             0.44       534     0.8116     0.8145    +0.0028
Currency                                  0.76        45     0.9890     1.0000    +0.0110
Duration                                  0.69       340     0.8571     0.8619    +0.0047
Elongated                                 0.54       168     0.7877     0.7926    +0.0049
Eventive                                  0.55      1068     0.8851     0.8867    +0.0016
Feminine                                  0.88       204     0.9412     0.9466    +0.0054
Fluid                                     0.55        19     0.8947     0.9189    +0.0242
Garment                                   0.31        17     0.9412     0.9714    +0.0303
Inanimate                                 0.43      1511     0.9342     0.9350    +0.0009
Internal_Control                          0.18        21     0.5000     0.6061    +0.1061
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.61      1209     0.9193     0.9228    +0.0035
Machine                                   0.74       180     0.8958     0.9012    +0.0054
Masculine                                 0.53       671     0.9367     0.9382    +0.0014
Natural                                   0.49        79     0.8701     0.8790    +0.0089
Natural_Force                             0.45        35     0.8182     0.8358    +0.0176
Non_Rigid                                 0.29       335     0.8169     0.8212    +0.0044
Organisation                              0.57      1086     0.8907     0.8950    +0.0042
Plant                                     0.44        15     0.8966     0.9333    +0.0368
Point_in_Time                             0.47       336     0.8837     0.8853    +0.0016
Pointy                                    0.48        20     0.7368     0.7500    +0.0132
Question                                  0.05        33     0.8710     0.8955    +0.0246
Rigid                                     0.38       603     0.8746     0.8848    +0.0103
Solid                                     0.49      1409     0.8893     0.8904    +0.0011
Sound                                     0.72        42     0.7857     0.8108    +0.0251
Statement                                 0.24       264     0.7490     0.7560    +0.0070
Substance                                 0.22       217     0.8759     0.8962    +0.0204
Time                                      0.45        16     0.4545     0.5833    +0.1288
Unspecified_Gender_or_Neuter              0.23       677     0.8925     0.9006    +0.0081
Vehicle                                   0.54       100     0.9697     0.9746    +0.0049
Web_Location                              0.87        55     0.8673     0.9143    +0.0470

VALIDATION @ 0.5
direct_f1_macro: 0.8631548362832536
direct_f1_micro: 0.8916017061332548
direct_precision_macro: 0.8991761895085194
direct_precision_micro: 0.89502436143511
direct_recall_macro: 0.8442731727856373
direct_recall_micro: 0.8882051282051282
f1_macro: 0.9048001643187796
f1_micro: 0.9380590771606925
precision_macro: 0.9145845651032993
precision_micro: 0.9440126934784017
recall_macro: 0.8958959742401026
recall_micro: 0.9321800856941869

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8804473667080931
direct_f1_micro: 0.8956690747735524
direct_precision_macro: 0.9028992100582734
direct_precision_micro: 0.8966884499596153
direct_recall_macro: 0.8670387470364683
direct_recall_micro: 0.8946520146520146
f1_macro: 0.9138125217341662
f1_micro: 0.9402299588900308
precision_macro: 0.9208117232418772
precision_micro: 0.9444157687592748
recall_macro: 0.908809077876169
recall_micro: 0.9360810897230927

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.787368913277453
direct_f1_micro: 0.8620552686829711
direct_precision_macro: 0.8258373536393971
direct_precision_micro: 0.8633780404637418
direct_recall_macro: 0.7738710313374321
direct_recall_micro: 0.8607365439093484
f1_macro: 0.8617003887659053
f1_micro: 0.9174405850091407
precision_macro: 0.8769699692514202
precision_micro: 0.9199296084469863
recall_macro: 0.8516184931315299
recall_micro: 0.9149649941656943

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7884559203253825
direct_f1_micro: 0.8612147947064812
direct_precision_macro: 0.8110880751811085
direct_precision_micro: 0.8596590267584961
direct_recall_macro: 0.7792182216898121
direct_recall_micro: 0.8627762039660056
f1_macro: 0.8587057752213477
f1_micro: 0.9169099046507102
precision_macro: 0.870356704899127
precision_micro: 0.9174454828660437
recall_macro: 0.8537023685538767
recall_micro: 0.9163749513807857

====================================================================================================
RUN 2/30 | SEED 23
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 960.90it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.47      1405     0.9017     0.9030    +0.0013
Animal                                    0.64       184     0.9366     0.9418    +0.0052
Animate                                   0.16        13     0.8182     0.8800    +0.0618
Artefact                                  0.34       503     0.9067     0.9100    +0.0033
Body_Part                                 0.09        74     0.8951     0.9404    +0.0453
Comestible                                0.49       157     0.9585     0.9618    +0.0033
Communication                             0.53       534     0.8068     0.8099    +0.0031
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.75       340     0.8473     0.8542    +0.0069
Elongated                                 0.58       168     0.7866     0.7987    +0.0122
Eventive                                  0.36      1068     0.8790     0.8821    +0.0031
Feminine                                  0.89       204     0.9324     0.9380    +0.0056
Fluid                                     0.51        19     0.8947     0.9189    +0.0242
Garment                                   0.50        17     1.0000     1.0000    +0.0000
Inanimate                                 0.63      1511     0.9338     0.9363    +0.0025
Internal_Control                          0.21        21     0.5517     0.6452    +0.0934
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.59      1209     0.9248     0.9262    +0.0014
Machine                                   0.54       180     0.9003     0.9080    +0.0078
Masculine                                 0.62       671     0.9281     0.9295    +0.0014
Natural                                   0.36        79     0.8701     0.8917    +0.0216
Natural_Force                             0.40        35     0.8485     0.8529    +0.0045
Non_Rigid                                 0.49       335     0.7897     0.7920    +0.0023
Organisation                              0.38      1086     0.8960     0.8999    +0.0038
Plant                                     0.50        15     0.9333     0.9333    +0.0000
Point_in_Time                             0.20       336     0.8688     0.8702    +0.0014
Pointy                                    0.21        20     0.4375     0.7556    +0.3181
Question                                  0.60        33     0.8750     0.8889    +0.0139
Rigid                                     0.15       603     0.8671     0.8775    +0.0103
Solid                                     0.37      1409     0.8898     0.8909    +0.0011
Sound                                     0.75        42     0.8046     0.8354    +0.0308
Statement                                 0.58       264     0.7623     0.7722    +0.0099
Substance                                 0.17       217     0.8791     0.8894    +0.0103
Time                                      0.09        16     0.3478     0.4545    +0.1067
Unspecified_Gender_or_Neuter              0.60       677     0.8798     0.8827    +0.0029
Vehicle                                   0.78       100     0.9596     0.9694    +0.0098
Web_Location                              0.62        55     0.8750     0.8829    +0.0079

VALIDATION @ 0.5
direct_f1_macro: 0.853686498991339
direct_f1_micro: 0.8897394376564111
direct_precision_macro: 0.8856508795378623
direct_precision_micro: 0.893950599023813
direct_recall_macro: 0.8363421110423069
direct_recall_micro: 0.8855677655677656
f1_macro: 0.8981094418948254
f1_micro: 0.93662175632657
precision_macro: 0.9070278473629441
precision_micro: 0.9419221316776614
recall_macro: 0.8912681579909029
recall_micro: 0.9313806996226898

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8763104954200706
direct_f1_micro: 0.8937117011963817
direct_precision_macro: 0.8855332954829059
direct_precision_micro: 0.8899462443701874
direct_recall_macro: 0.8758701450942201
direct_recall_micro: 0.8975091575091575
f1_macro: 0.9119864603750499
f1_micro: 0.9383075814586502
precision_macro: 0.9143829958319123
precision_micro: 0.9397068727750874
recall_macro: 0.9112022919676173
recall_micro: 0.9369124512374496

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7823862942633927
direct_f1_micro: 0.8643529545196779
direct_precision_macro: 0.8269753025878851
direct_precision_micro: 0.8651379271199909
direct_recall_macro: 0.7661575933619923
direct_recall_micro: 0.8635694050991501
f1_macro: 0.8549669479883233
f1_micro: 0.9185174361971556
precision_macro: 0.8768894409700868
precision_micro: 0.9201307572209212
recall_macro: 0.8423070961602835
recall_micro: 0.9169097627382341

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7863911979059006
direct_f1_micro: 0.8629698297657171
direct_precision_macro: 0.8161155893115849
direct_precision_micro: 0.8558056607978605
direct_recall_macro: 0.7829176015290424
direct_recall_micro: 0.8702549575070821
f1_macro: 0.8622949198467313
f1_micro: 0.9164968461911693
precision_macro: 0.884336024220675
precision_micro: 0.9146329653302344
recall_macro: 0.8512903732869799
recall_micro: 0.918368339167639

====================================================================================================
RUN 3/30 | SEED 37
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 932.17it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.65      1405     0.9001     0.9020    +0.0019
Animal                                    0.70       184     0.9418     0.9524    +0.0106
Animate                                   0.33        13     0.8182     0.9167    +0.0985
Artefact                                  0.52       503     0.9100     0.9107    +0.0007
Body_Part                                 0.53        74     0.9200     0.9262    +0.0062
Comestible                                0.59       157     0.9521     0.9582    +0.0061
Communication                             0.49       534     0.8060     0.8071    +0.0011
Currency                                  0.61        45     0.9890     1.0000    +0.0110
Duration                                  0.89       340     0.8542     0.8580    +0.0038
Elongated                                 0.57       168     0.7866     0.7950    +0.0084
Eventive                                  0.47      1068     0.8941     0.8943    +0.0002
Feminine                                  0.74       204     0.9272     0.9409    +0.0137
Fluid                                     0.50        19     0.8889     0.8889    +0.0000
Garment                                   0.30        17     0.9697     0.9714    +0.0017
Inanimate                                 0.40      1511     0.9404     0.9416    +0.0012
Internal_Control                          0.15        21     0.3846     0.6452    +0.2605
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.75      1209     0.9204     0.9245    +0.0041
Machine                                   0.36       180     0.8946     0.9056    +0.0110
Masculine                                 0.61       671     0.9318     0.9344    +0.0026
Natural                                   0.43        79     0.8947     0.9020    +0.0072
Natural_Force                             0.56        35     0.8451     0.8696    +0.0245
Non_Rigid                                 0.42       335     0.7918     0.8023    +0.0104
Organisation                              0.51      1086     0.8966     0.8974    +0.0008
Plant                                     0.32        15     0.8966     0.9032    +0.0067
Point_in_Time                             0.62       336     0.8707     0.8739    +0.0031
Pointy                                    0.36        20     0.7179     0.7442    +0.0262
Question                                  0.48        33     0.8387     0.8750    +0.0363
Rigid                                     0.45       603     0.8943     0.8959    +0.0016
Solid                                     0.54      1409     0.8914     0.8924    +0.0010
Sound                                     0.65        42     0.7294     0.7949    +0.0655
Statement                                 0.29       264     0.7515     0.7565    +0.0050
Substance                                 0.21       217     0.8940     0.9075    +0.0135
Time                                      0.17        16     0.3636     0.4878    +0.1242
Unspecified_Gender_or_Neuter              0.21       677     0.8803     0.8879    +0.0076
Vehicle                                   0.34       100     0.9592     0.9697    +0.0105
Web_Location                              0.95        55     0.8545     0.9126    +0.0581

VALIDATION @ 0.5
direct_f1_macro: 0.8540565058681058
direct_f1_micro: 0.8930605047573564
direct_precision_macro: 0.8918379820049159
direct_precision_micro: 0.8956598629430403
direct_recall_macro: 0.8364044579749708
direct_recall_micro: 0.8904761904761904
f1_macro: 0.9011976198241363
f1_micro: 0.9371571954769908
precision_macro: 0.9101040062108123
precision_micro: 0.9428747127552837
recall_macro: 0.8930484475962585
recall_micro: 0.9315086013941293

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8769116871624705
direct_f1_micro: 0.8966937589643632
direct_precision_macro: 0.8934436034737508
direct_precision_micro: 0.9003027841370652
direct_recall_macro: 0.868881246875915
direct_recall_micro: 0.8931135531135531
f1_macro: 0.9103071725974322
f1_micro: 0.9392542133251932
precision_macro: 0.9176779639119698
precision_micro: 0.943879363234202
recall_macro: 0.9046615168330041
recall_micro: 0.9346741702372577

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7720128015694333
direct_f1_micro: 0.8638380161528836
direct_precision_macro: 0.8266988128184007
direct_precision_micro: 0.8671919607171406
direct_recall_macro: 0.750291711570539
direct_recall_micro: 0.8605099150141643
f1_macro: 0.8516098011987351
f1_micro: 0.9164715066354411
precision_macro: 0.8797296522505865
precision_micro: 0.9197023110066588
recall_macro: 0.8327464264496414
recall_micro: 0.9132633216647219

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7858337635265036
direct_f1_micro: 0.8595933204589344
direct_precision_macro: 0.8214820871326596
direct_precision_micro: 0.8617469536499259
direct_recall_macro: 0.7699354002642038
direct_recall_micro: 0.8574504249291784
f1_macro: 0.8573116394895777
f1_micro: 0.9143427264320826
precision_macro: 0.887040204593773
precision_micro: 0.9152781837669297
recall_macro: 0.8391496378124921
recall_micro: 0.9134091793076624

====================================================================================================
RUN 4/30 | SEED 53
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 995.41it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.53      1405     0.8964     0.8980    +0.0016
Animal                                    0.20       184     0.9418     0.9479    +0.0061
Animate                                   0.37        13     0.8182     0.9167    +0.0985
Artefact                                  0.42       503     0.8963     0.9023    +0.0060
Body_Part                                 0.18        74     0.9078     0.9467    +0.0389
Comestible                                0.31       157     0.9457     0.9527    +0.0070
Communication                             0.47       534     0.8038     0.8071    +0.0033
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.63       340     0.8559     0.8584    +0.0025
Elongated                                 0.40       168     0.7707     0.7774    +0.0067
Eventive                                  0.66      1068     0.8807     0.8857    +0.0050
Feminine                                  0.41       204     0.9284     0.9337    +0.0053
Fluid                                     0.20        19     0.8889     0.8947    +0.0058
Garment                                   0.16        17     0.9091     0.9444    +0.0354
Inanimate                                 0.38      1511     0.9372     0.9388    +0.0017
Internal_Control                          0.19        21     0.4444     0.6471    +0.2026
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.30      1209     0.9198     0.9232    +0.0034
Machine                                   0.43       180     0.8800     0.8895    +0.0095
Masculine                                 0.34       671     0.9358     0.9403    +0.0044
Natural                                   0.78        79     0.8875     0.9139    +0.0264
Natural_Force                             0.59        35     0.9143     0.9275    +0.0133
Non_Rigid                                 0.54       335     0.8147     0.8190    +0.0043
Organisation                              0.53      1086     0.8974     0.8981    +0.0006
Plant                                     0.50        15     0.9333     0.9333    +0.0000
Point_in_Time                             0.12       336     0.8690     0.8745    +0.0054
Pointy                                    0.31        20     0.6316     0.7442    +0.1126
Question                                  0.07        33     0.7931     0.8657    +0.0726
Rigid                                     0.29       603     0.8740     0.8770    +0.0029
Solid                                     0.47      1409     0.8983     0.9000    +0.0017
Sound                                     0.72        42     0.7529     0.8000    +0.0471
Statement                                 0.75       264     0.7538     0.7689    +0.0151
Substance                                 0.38       217     0.8782     0.8894    +0.0112
Time                                      0.10        16     0.3000     0.5238    +0.2238
Unspecified_Gender_or_Neuter              0.67       677     0.8937     0.8971    +0.0034
Vehicle                                   0.77       100     0.9697     0.9746    +0.0049
Web_Location                              0.74        55     0.8889     0.9057    +0.0168

VALIDATION @ 0.5
direct_f1_macro: 0.8516638532451981
direct_f1_micro: 0.8914508821687723
direct_precision_macro: 0.8960708360560488
direct_precision_micro: 0.8964367730943033
direct_recall_macro: 0.8302869315103946
direct_recall_micro: 0.8865201465201465
f1_macro: 0.9001140074218205
f1_micro: 0.9379961036242734
precision_macro: 0.9138027917557187
precision_micro: 0.944673260904816
recall_macro: 0.8880259009839275
recall_micro: 0.9314126750655497

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8788466024903311
direct_f1_micro: 0.896069165109719
direct_precision_macro: 0.8874628681586866
direct_precision_micro: 0.8961676558950685
direct_recall_macro: 0.8763076047710212
direct_recall_micro: 0.895970695970696
f1_macro: 0.9117450821494879
f1_micro: 0.94041117892708
precision_macro: 0.9157389670537591
precision_micro: 0.9447815142322339
recall_macro: 0.9095746432182543
recall_micro: 0.9360810897230927

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7698775501810159
direct_f1_micro: 0.8647848850443888
direct_precision_macro: 0.8159388008518154
direct_precision_micro: 0.8686406768034755
direct_recall_macro: 0.7534070398145702
direct_recall_micro: 0.8609631728045326
f1_macro: 0.8479634981285471
f1_micro: 0.9182386863454208
precision_macro: 0.8724930641351372
precision_micro: 0.9230202397327569
recall_macro: 0.8335983933222769
recall_micro: 0.9135064177362894

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7732433453079486
direct_f1_micro: 0.8641569338927316
direct_precision_macro: 0.7957384978671681
direct_precision_micro: 0.8647452626801316
direct_recall_macro: 0.7658968037283163
direct_recall_micro: 0.8635694050991501
f1_macro: 0.8504113289058046
f1_micro: 0.9165383581396486
precision_macro: 0.8726109059765063
precision_micro: 0.9214703425229741
recall_macro: 0.8389492064048191
recall_micro: 0.9116588875923765

====================================================================================================
RUN 5/30 | SEED 71
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 876.74it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.39      1405     0.8951     0.8975    +0.0024
Animal                                    0.60       184     0.9532     0.9558    +0.0026
Animate                                   0.26        13     0.8696     0.9600    +0.0904
Artefact                                  0.63       503     0.9091     0.9111    +0.0020
Body_Part                                 0.06        74     0.9028     0.9419    +0.0392
Comestible                                0.24       157     0.9457     0.9557    +0.0100
Communication                             0.62       534     0.7992     0.8054    +0.0062
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.62       340     0.8522     0.8584    +0.0062
Elongated                                 0.61       168     0.7853     0.7885    +0.0032
Eventive                                  0.45      1068     0.8836     0.8866    +0.0030
Feminine                                  0.79       204     0.9320     0.9435    +0.0115
Fluid                                     0.78        19     0.8718     0.8889    +0.0171
Garment                                   0.11        17     0.9091     0.9714    +0.0623
Inanimate                                 0.37      1511     0.9376     0.9398    +0.0021
Internal_Control                          0.14        21     0.3846     0.5882    +0.2036
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.70      1209     0.9207     0.9241    +0.0034
Machine                                   0.41       180     0.8980     0.8997    +0.0018
Masculine                                 0.44       671     0.9333     0.9366    +0.0033
Natural                                   0.30        79     0.8590     0.8712    +0.0122
Natural_Force                             0.53        35     0.8571     0.8696    +0.0124
Non_Rigid                                 0.34       335     0.7893     0.7989    +0.0095
Organisation                              0.36      1086     0.8888     0.8926    +0.0038
Plant                                     0.50        15     0.8667     0.8667    +0.0000
Point_in_Time                             0.47       336     0.8705     0.8743    +0.0038
Pointy                                    0.37        20     0.7368     0.7619    +0.0251
Question                                  0.18        33     0.8571     0.8955    +0.0384
Rigid                                     0.28       603     0.8784     0.8827    +0.0043
Solid                                     0.63      1409     0.8944     0.8967    +0.0023
Sound                                     0.71        42     0.8095     0.8312    +0.0216
Statement                                 0.57       264     0.7588     0.7634    +0.0047
Substance                                 0.53       217     0.8924     0.8981    +0.0057
Time                                      0.21        16     0.3810     0.4828    +0.1018
Unspecified_Gender_or_Neuter              0.38       677     0.8920     0.8946    +0.0026
Vehicle                                   0.50       100     0.9588     0.9588    +0.0000
Web_Location                              0.91        55     0.8972     0.9038    +0.0066

VALIDATION @ 0.5
direct_f1_macro: 0.8559633631102254
direct_f1_micro: 0.8911437079519136
direct_precision_macro: 0.895403403782657
direct_precision_micro: 0.8943989373477972
direct_recall_macro: 0.8384692158694803
direct_recall_micro: 0.8879120879120879
f1_macro: 0.9028353473233107
f1_micro: 0.937701016338608
precision_macro: 0.9120570140729535
precision_micro: 0.9432222581688774
recall_macro: 0.8942661411098246
recall_micro: 0.9322440365799066

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8755650224042119
direct_f1_micro: 0.8954742169735201
direct_precision_macro: 0.8892873343927772
direct_precision_micro: 0.8965922444183314
direct_recall_macro: 0.86578038191274
direct_recall_micro: 0.8943589743589744
f1_macro: 0.9110834272789656
f1_micro: 0.9403810103664301
precision_macro: 0.9184476162569006
precision_micro: 0.9424194739715469
recall_macro: 0.9053050696033816
recall_micro: 0.9383513461661444

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7742312085577522
direct_f1_micro: 0.8641440620013677
direct_precision_macro: 0.8207277660284114
direct_precision_micro: 0.8691963773930987
direct_recall_macro: 0.7555525736452335
direct_recall_micro: 0.8591501416430595
f1_macro: 0.849787404948151
f1_micro: 0.9172105301752584
precision_macro: 0.8734554217258289
precision_micro: 0.9222828491372954
recall_macro: 0.8346612949691987
recall_micro: 0.9121936989498249

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.774967585445926
direct_f1_micro: 0.8635198997893299
direct_precision_macro: 0.8071824250232714
direct_precision_micro: 0.8678187228198673
direct_recall_macro: 0.7582859430407543
direct_recall_micro: 0.8592634560906516
f1_macro: 0.8476538516467429
f1_micro: 0.9173434794273311
precision_macro: 0.8750187567468485
precision_micro: 0.9203739049576665
recall_macro: 0.831259844452255
recall_micro: 0.9143329443796189

====================================================================================================
RUN 6/30 | SEED 89
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1045.79it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.57      1405     0.8963     0.8972    +0.0009
Animal                                    0.51       184     0.9418     0.9444    +0.0026
Animate                                   0.16        13     0.8696     0.8800    +0.0104
Artefact                                  0.73       503     0.8977     0.9044    +0.0067
Body_Part                                 0.18        74     0.9014     0.9536    +0.0522
Comestible                                0.50       157     0.9682     0.9682    +0.0000
Communication                             0.65       534     0.8093     0.8146    +0.0053
Currency                                  0.64        45     0.9890     1.0000    +0.0110
Duration                                  0.92       340     0.8455     0.8509    +0.0055
Elongated                                 0.62       168     0.7914     0.8050    +0.0136
Eventive                                  0.68      1068     0.8924     0.8946    +0.0022
Feminine                                  0.28       204     0.9310     0.9340    +0.0030
Fluid                                     0.55        19     0.8718     0.8947    +0.0229
Garment                                   0.43        17     0.9697     1.0000    +0.0303
Inanimate                                 0.35      1511     0.9383     0.9391    +0.0008
Internal_Control                          0.10        21     0.3846     0.5556    +0.1709
Language                                  0.60         5     0.9091     1.0000    +0.0909
Location                                  0.59      1209     0.9240     0.9262    +0.0023
Machine                                   0.32       180     0.8940     0.9070    +0.0131
Masculine                                 0.29       671     0.9348     0.9387    +0.0038
Natural                                   0.44        79     0.8961     0.8974    +0.0013
Natural_Force                             0.50        35     0.9143     0.9143    +0.0000
Non_Rigid                                 0.44       335     0.7959     0.7988    +0.0030
Organisation                              0.42      1086     0.8910     0.8937    +0.0028
Plant                                     0.50        15     0.9333     0.9333    +0.0000
Point_in_Time                             0.66       336     0.8584     0.8649    +0.0065
Pointy                                    0.50        20     0.8205     0.8205    +0.0000
Question                                  0.11        33     0.8197     0.8788    +0.0591
Rigid                                     0.37       603     0.8795     0.8859    +0.0065
Solid                                     0.33      1409     0.8904     0.8932    +0.0028
Sound                                     0.59        42     0.7805     0.8101    +0.0296
Statement                                 0.68       264     0.7555     0.7621    +0.0066
Substance                                 0.29       217     0.8945     0.9091    +0.0146
Time                                      0.08        16     0.2105     0.4762    +0.2657
Unspecified_Gender_or_Neuter              0.67       677     0.8882     0.8919    +0.0036
Vehicle                                   0.15       100     0.9596     0.9652    +0.0056
Web_Location                              0.85        55     0.8807     0.9231    +0.0423

VALIDATION @ 0.5
direct_f1_macro: 0.8548229973728725
direct_f1_micro: 0.8920450364265214
direct_precision_macro: 0.8938653935115516
direct_precision_micro: 0.8960674157303371
direct_recall_macro: 0.8405453619588334
direct_recall_micro: 0.888058608058608
f1_macro: 0.9054300444982428
f1_micro: 0.9383828308504134
precision_macro: 0.9127594423495532
precision_micro: 0.9443077321590467
recall_macro: 0.8992928573621146
recall_micro: 0.9325318155656456

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.87910609789217
direct_f1_micro: 0.8964451313755796
direct_precision_macro: 0.8902506183414877
direct_precision_micro: 0.9006211180124224
direct_recall_macro: 0.87196769964113
direct_recall_micro: 0.8923076923076924
f1_macro: 0.9161175745825025
f1_micro: 0.9397337974153211
precision_macro: 0.9272479489984764
precision_micro: 0.9472128378378378
recall_macro: 0.9065097181817111
recall_micro: 0.9323719383513461

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7818417531946297
direct_f1_micro: 0.8594354655133166
direct_precision_macro: 0.8263369831737426
direct_precision_micro: 0.8632674059677604
direct_recall_macro: 0.7641771428904118
direct_recall_micro: 0.8556373937677054
f1_macro: 0.857320469952785
f1_micro: 0.9143694298620437
precision_macro: 0.877658528137842
precision_micro: 0.9184284102614411
recall_macro: 0.8439190716975594
recall_micro: 0.9103461688059121

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7692268123991772
direct_f1_micro: 0.8566543174693645
direct_precision_macro: 0.8028735506312902
direct_precision_micro: 0.8618119266055045
direct_recall_macro: 0.7552763906390393
direct_recall_micro: 0.851558073654391
f1_macro: 0.8434709855959343
f1_micro: 0.9121527352833191
precision_macro: 0.8763742672942626
precision_micro: 0.9184699561295411
recall_macro: 0.8241735301719267
recall_micro: 0.9059218203033839

====================================================================================================
RUN 7/30 | SEED 107
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 921.27it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.56      1405     0.8971     0.8979    +0.0008
Animal                                    0.53       184     0.9477     0.9503    +0.0026
Animate                                   0.45        13     0.7826     0.8333    +0.0507
Artefact                                  0.36       503     0.9043     0.9089    +0.0046
Body_Part                                 0.31        74     0.9028     0.9189    +0.0161
Comestible                                0.63       157     0.9490     0.9548    +0.0058
Communication                             0.30       534     0.8065     0.8159    +0.0094
Currency                                  0.80        45     0.9890     1.0000    +0.0110
Duration                                  0.19       340     0.8453     0.8524    +0.0071
Elongated                                 0.52       168     0.7837     0.7937    +0.0100
Eventive                                  0.64      1068     0.8805     0.8852    +0.0047
Feminine                                  0.92       204     0.9257     0.9337    +0.0080
Fluid                                     0.50        19     0.8889     0.8889    +0.0000
Garment                                   0.29        17     0.9091     0.9714    +0.0623
Inanimate                                 0.31      1511     0.9307     0.9352    +0.0045
Internal_Control                          0.10        21     0.4828     0.6471    +0.1643
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.57      1209     0.9203     0.9230    +0.0027
Machine                                   0.71       180     0.8701     0.8856    +0.0156
Masculine                                 0.13       671     0.9226     0.9293    +0.0067
Natural                                   0.36        79     0.8645     0.8931    +0.0286
Natural_Force                             0.19        35     0.8358     0.8767    +0.0409
Non_Rigid                                 0.55       335     0.8012     0.8074    +0.0062
Organisation                              0.45      1086     0.8915     0.8926    +0.0011
Plant                                     0.50        15     0.9333     0.9333    +0.0000
Point_in_Time                             0.26       336     0.8571     0.8651    +0.0080
Pointy                                    0.56        20     0.7317     0.7368    +0.0051
Question                                  0.11        33     0.8387     0.8923    +0.0536
Rigid                                     0.39       603     0.8763     0.8837    +0.0074
Solid                                     0.33      1409     0.8856     0.8893    +0.0037
Sound                                     0.75        42     0.7529     0.7848    +0.0319
Statement                                 0.47       264     0.7630     0.7672    +0.0042
Substance                                 0.23       217     0.8800     0.8958    +0.0158
Time                                      0.29        16     0.2400     0.5000    +0.2600
Unspecified_Gender_or_Neuter              0.48       677     0.8860     0.8886    +0.0026
Vehicle                                   0.59       100     0.9596     0.9694    +0.0098
Web_Location                              0.84        55     0.8673     0.9057    +0.0384

VALIDATION @ 0.5
direct_f1_macro: 0.8487282197858982
direct_f1_micro: 0.8874742419782161
direct_precision_macro: 0.8736293373993975
direct_precision_micro: 0.8915422149933462
direct_recall_macro: 0.8331795727239713
direct_recall_micro: 0.8834432234432235
f1_macro: 0.8991020929573955
f1_micro: 0.9351580843330868
precision_macro: 0.9082865173671509
precision_micro: 0.9406949657046719
recall_macro: 0.8908285874921069
recall_micro: 0.929686001151116

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8731667843123213
direct_f1_micro: 0.8928883707373944
direct_precision_macro: 0.8825370541842104
direct_precision_micro: 0.8880997245977678
direct_recall_macro: 0.8687798431617721
direct_recall_micro: 0.8977289377289377
f1_macro: 0.9092311699512947
f1_micro: 0.9382364241803278
precision_macro: 0.9150725590013321
precision_micro: 0.9394998396922091
recall_macro: 0.904644769232724
recall_micro: 0.9369764021231695

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7796425233271007
direct_f1_micro: 0.860276152054094
direct_precision_macro: 0.8088818745734674
direct_precision_micro: 0.8627763847731935
direct_recall_macro: 0.7665443462459105
direct_recall_micro: 0.8577903682719547
f1_macro: 0.8566246899546192
f1_micro: 0.914631468514407
precision_macro: 0.8745058200351522
precision_micro: 0.9179685586953328
recall_macro: 0.8444227881702725
recall_micro: 0.911318553092182

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.778683099432664
direct_f1_micro: 0.8590543655478721
direct_precision_macro: 0.7887465618314388
direct_precision_micro: 0.8524882838652087
direct_recall_macro: 0.7809702986654866
direct_recall_micro: 0.8657223796033995
f1_macro: 0.8551740135044261
f1_micro: 0.9148600422422374
precision_macro: 0.8672453867653552
precision_micro: 0.9136401105561751
recall_macro: 0.8495091446520819
recall_micro: 0.9160832360949047

====================================================================================================
RUN 8/30 | SEED 127
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 975.22it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.35      1405     0.8913     0.8944    +0.0031
Animal                                    0.29       184     0.9363     0.9396    +0.0033
Animate                                   0.11        13     0.8182     0.8800    +0.0618
Artefact                                  0.56       503     0.8984     0.9005    +0.0021
Body_Part                                 0.30        74     0.8951     0.9178    +0.0227
Comestible                                0.51       157     0.9464     0.9494    +0.0030
Communication                             0.54       534     0.8064     0.8065    +0.0001
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.42       340     0.8472     0.8530    +0.0059
Elongated                                 0.53       168     0.7805     0.7901    +0.0096
Eventive                                  0.59      1068     0.8818     0.8845    +0.0027
Feminine                                  0.81       204     0.9298     0.9432    +0.0134
Fluid                                     0.07        19     0.8649     0.9048    +0.0399
Garment                                   0.37        17     0.9697     0.9714    +0.0017
Inanimate                                 0.37      1511     0.9364     0.9371    +0.0007
Internal_Control                          0.16        21     0.5161     0.6667    +0.1505
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.76      1209     0.9140     0.9182    +0.0042
Machine                                   0.35       180     0.9017     0.9086    +0.0068
Masculine                                 0.43       671     0.9335     0.9356    +0.0021
Natural                                   0.57        79     0.8662     0.8718    +0.0056
Natural_Force                             0.65        35     0.8169     0.8529    +0.0360
Non_Rigid                                 0.53       335     0.8065     0.8119    +0.0054
Organisation                              0.27      1086     0.8912     0.8958    +0.0047
Plant                                     0.20        15     0.8571     0.8667    +0.0095
Point_in_Time                             0.29       336     0.8627     0.8759    +0.0132
Pointy                                    0.58        20     0.7500     0.8108    +0.0608
Question                                  0.50        33     0.8571     0.8571    +0.0000
Rigid                                     0.36       603     0.8807     0.8819    +0.0011
Solid                                     0.59      1409     0.8918     0.8941    +0.0023
Sound                                     0.56        42     0.8095     0.8293    +0.0197
Statement                                 0.33       264     0.7665     0.7704    +0.0038
Substance                                 0.44       217     0.8915     0.9000    +0.0085
Time                                      0.22        16     0.3846     0.4848    +0.1002
Unspecified_Gender_or_Neuter              0.75       677     0.8853     0.8869    +0.0016
Vehicle                                   0.76       100     0.9592     0.9691    +0.0099
Web_Location                              0.95        55     0.8829     0.9126    +0.0297

VALIDATION @ 0.5
direct_f1_macro: 0.8574977114244254
direct_f1_micro: 0.8892316732775084
direct_precision_macro: 0.8809649880499888
direct_precision_micro: 0.8915893356900869
direct_recall_macro: 0.8414997478617612
direct_recall_micro: 0.8868864468864469
f1_macro: 0.9021393687658972
f1_micro: 0.9368305940625905
precision_macro: 0.9113031865533233
precision_micro: 0.9423773780251068
recall_macro: 0.8937215102248999
recall_micro: 0.93134872417983

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8749513894780692
direct_f1_micro: 0.893179649071287
direct_precision_macro: 0.8851754808607766
direct_precision_micro: 0.8950853443201884
direct_recall_macro: 0.8673828633976887
direct_recall_micro: 0.8912820512820513
f1_macro: 0.9100891456640053
f1_micro: 0.9376476069598187
precision_macro: 0.9172215867731159
precision_micro: 0.9422648454906519
recall_macro: 0.9044181921872902
recall_micro: 0.9330753980942637

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7924837962684529
direct_f1_micro: 0.861676714821977
direct_precision_macro: 0.813310065265636
direct_precision_micro: 0.8650222678999657
direct_recall_macro: 0.7840589958320162
direct_recall_micro: 0.8583569405099151
f1_macro: 0.8642787664239925
f1_micro: 0.9176189080964938
precision_macro: 0.8727878635686617
precision_micro: 0.9216696095742594
recall_macro: 0.8587216481756743
recall_micro: 0.9136036561649163

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7992490172371642
direct_f1_micro: 0.8601430355318425
direct_precision_macro: 0.8145062702880445
direct_precision_micro: 0.8617081769589446
direct_recall_macro: 0.7939129598069044
direct_recall_micro: 0.8585835694050992
f1_macro: 0.8593568999428319
f1_micro: 0.914829268292683
precision_macro: 0.8706716260868024
precision_micro: 0.9178739232576351
recall_macro: 0.8533624446852363
recall_micro: 0.911804745235317

====================================================================================================
RUN 9/30 | SEED 149
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 954.70it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.80      1405     0.8960     0.8981    +0.0021
Animal                                    0.68       184     0.9474     0.9500    +0.0026
Animate                                   0.15        13     0.7826     0.8571    +0.0745
Artefact                                  0.30       503     0.8913     0.8987    +0.0074
Body_Part                                 0.10        74     0.9028     0.9221    +0.0193
Comestible                                0.49       157     0.9427     0.9460    +0.0034
Communication                             0.40       534     0.8022     0.8055    +0.0032
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.26       340     0.8514     0.8567    +0.0054
Elongated                                 0.44       168     0.7791     0.7868    +0.0076
Eventive                                  0.58      1068     0.8839     0.8867    +0.0028
Feminine                                  0.93       204     0.9510     0.9576    +0.0066
Fluid                                     0.11        19     0.8889     0.9189    +0.0300
Garment                                   0.50        17     0.9697     0.9697    +0.0000
Inanimate                                 0.45      1511     0.9327     0.9343    +0.0015
Internal_Control                          0.10        21     0.3846     0.5263    +0.1417
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.67      1209     0.9259     0.9272    +0.0014
Machine                                   0.73       180     0.8786     0.8876    +0.0090
Masculine                                 0.25       671     0.9286     0.9317    +0.0030
Natural                                   0.51        79     0.8831     0.8889    +0.0058
Natural_Force                             0.66        35     0.8406     0.8615    +0.0210
Non_Rigid                                 0.55       335     0.7965     0.8000    +0.0035
Organisation                              0.53      1086     0.8889     0.8900    +0.0011
Plant                                     0.50        15     0.9333     0.9333    +0.0000
Point_in_Time                             0.24       336     0.8554     0.8687    +0.0133
Pointy                                    0.40        20     0.6047     0.6957    +0.0910
Question                                  0.07        33     0.8197     0.8955    +0.0759
Rigid                                     0.31       603     0.8807     0.8855    +0.0048
Solid                                     0.44      1409     0.8902     0.8919    +0.0016
Sound                                     0.28        42     0.7692     0.8222    +0.0530
Statement                                 0.43       264     0.7505     0.7590    +0.0085
Substance                                 0.18       217     0.8759     0.8879    +0.0121
Time                                      0.11        16     0.3158     0.5500    +0.2342
Unspecified_Gender_or_Neuter              0.50       677     0.8967     0.8967    +0.0000
Vehicle                                   0.50       100     0.9697     0.9697    +0.0000
Web_Location                              0.82        55     0.8649     0.8868    +0.0219

VALIDATION @ 0.5
direct_f1_macro: 0.8479755258185095
direct_f1_micro: 0.8892405063291139
direct_precision_macro: 0.8965147628670946
direct_precision_micro: 0.8933165754842526
direct_recall_macro: 0.829131618586511
direct_recall_micro: 0.8852014652014653
f1_macro: 0.8983960711273712
f1_micro: 0.9353233830845771
precision_macro: 0.909561026523748
precision_micro: 0.941981514512729
recall_macro: 0.8884248810293286
recall_micro: 0.9287587133081793

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8714691994346608
direct_f1_micro: 0.8927161035541904
direct_precision_macro: 0.8686040082967939
direct_precision_micro: 0.8911519929916776
direct_recall_macro: 0.8782984562674461
direct_recall_micro: 0.8942857142857142
f1_macro: 0.9093290000932291
f1_micro: 0.9377435025893444
precision_macro: 0.9088511773314898
precision_micro: 0.9404122584172107
recall_macro: 0.9116765439128514
recall_micro: 0.9350898509944363

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7636387252671427
direct_f1_micro: 0.8633631931057943
direct_precision_macro: 0.7935223244952339
direct_precision_micro: 0.8639509815045955
direct_recall_macro: 0.7501746108759801
direct_recall_micro: 0.8627762039660056
f1_macro: 0.8518185973349518
f1_micro: 0.917580542964371
precision_macro: 0.8729960950706595
precision_micro: 0.9198670966480993
recall_macro: 0.8395674672177023
recall_micro: 0.9153053286658888

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7711139615683226
direct_f1_micro: 0.8611801944381642
direct_precision_macro: 0.7858252875369013
direct_precision_micro: 0.859140633810759
direct_recall_macro: 0.7710758502620388
direct_recall_micro: 0.8632294617563739
f1_macro: 0.8492210902719092
f1_micro: 0.9164047462417465
precision_macro: 0.8661483953026734
precision_micro: 0.9184859584859585
recall_macro: 0.843552869361802
recall_micro: 0.9143329443796189

====================================================================================================
RUN 10/30 | SEED 173
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1013.55it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.59      1405     0.8978     0.8995    +0.0018
Animal                                    0.62       184     0.9396     0.9448    +0.0052
Animate                                   0.68        13     0.7200     0.8182    +0.0982
Artefact                                  0.28       503     0.9061     0.9129    +0.0067
Body_Part                                 0.41        74     0.9231     0.9315    +0.0084
Comestible                                0.52       157     0.9618     0.9649    +0.0031
Communication                             0.38       534     0.8217     0.8245    +0.0028
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.58       340     0.8476     0.8534    +0.0058
Elongated                                 0.50       168     0.7975     0.7975    +0.0000
Eventive                                  0.60      1068     0.8819     0.8858    +0.0040
Feminine                                  0.50       204     0.9507     0.9507    +0.0000
Fluid                                     0.26        19     0.8947     0.9231    +0.0283
Garment                                   0.33        17     0.9412     0.9714    +0.0303
Inanimate                                 0.70      1511     0.9363     0.9385    +0.0022
Internal_Control                          0.05        21     0.3846     0.5263    +0.1417
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.30      1209     0.9178     0.9224    +0.0045
Machine                                   0.69       180     0.8883     0.9006    +0.0123
Masculine                                 0.19       671     0.9333     0.9368    +0.0034
Natural                                   0.29        79     0.8974     0.9068    +0.0094
Natural_Force                             0.50        35     0.8986     0.8986    +0.0000
Non_Rigid                                 0.49       335     0.7983     0.8000    +0.0017
Organisation                              0.53      1086     0.8905     0.8920    +0.0014
Plant                                     0.50        15     0.9333     0.9333    +0.0000
Point_in_Time                             0.40       336     0.8724     0.8798    +0.0074
Pointy                                    0.17        20     0.6829     0.7500    +0.0671
Question                                  0.06        33     0.8333     0.8824    +0.0490
Rigid                                     0.35       603     0.8761     0.8833    +0.0072
Solid                                     0.46      1409     0.8906     0.8923    +0.0016
Sound                                     0.48        42     0.8140     0.8276    +0.0136
Statement                                 0.56       264     0.7704     0.7793    +0.0089
Substance                                 0.17       217     0.8738     0.8991    +0.0253
Time                                      0.18        16     0.4000     0.5714    +0.1714
Unspecified_Gender_or_Neuter              0.64       677     0.8912     0.8950    +0.0038
Vehicle                                   0.66       100     0.9596     0.9694    +0.0098
Web_Location                              0.95        55     0.8807     0.8932    +0.0125

VALIDATION @ 0.5
direct_f1_macro: 0.856951810034165
direct_f1_micro: 0.891832229580574
direct_precision_macro: 0.8975759359914882
direct_precision_micro: 0.8957871396895787
direct_recall_macro: 0.8421007881241327
direct_recall_micro: 0.8879120879120879
f1_macro: 0.9059200296305432
f1_micro: 0.9381592487779778
precision_macro: 0.9137127517178223
precision_micro: 0.9435603855359338
recall_macro: 0.8989569862448079
recall_micro: 0.9328195945513845

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8771953932330065
direct_f1_micro: 0.896041055718475
direct_precision_macro: 0.8809653708463241
direct_precision_micro: 0.8966984592809978
direct_recall_macro: 0.8776318458196997
direct_recall_micro: 0.8953846153846153
f1_macro: 0.914262396336226
f1_micro: 0.940154192097655
precision_macro: 0.9148013005162562
precision_micro: 0.9445233331181824
recall_macro: 0.9156885070373344
recall_micro: 0.9358252861802135

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7831421917867828
direct_f1_micro: 0.8612123974475843
direct_precision_macro: 0.8271303036930773
direct_precision_micro: 0.8660478973301249
direct_recall_macro: 0.7677991613584436
direct_recall_micro: 0.8564305949008498
f1_macro: 0.8599664004764631
f1_micro: 0.9157038520725959
precision_macro: 0.8793674414325465
precision_micro: 0.9201315595699769
recall_macro: 0.8461282693054872
recall_micro: 0.911318553092182

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7920833793480475
direct_f1_micro: 0.8584686774941995
direct_precision_macro: 0.8019524278213495
direct_precision_micro: 0.8574496947773005
direct_recall_macro: 0.7955145018465917
direct_recall_micro: 0.8594900849858357
f1_macro: 0.8668788923620044
f1_micro: 0.9142634260500719
precision_macro: 0.8821677473799645
precision_micro: 0.9168337163252335
recall_macro: 0.8604180594547495
recall_micro: 0.91170750680669

====================================================================================================
RUN 11/30 | SEED 197
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 982.43it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.33      1405     0.8924     0.8953    +0.0028
Animal                                    0.51       184     0.9425     0.9451    +0.0026
Animate                                   0.43        13     0.8000     0.8889    +0.0889
Artefact                                  0.28       503     0.8943     0.9008    +0.0065
Body_Part                                 0.49        74     0.9315     0.9388    +0.0073
Comestible                                0.69       157     0.9494     0.9613    +0.0119
Communication                             0.49       534     0.8089     0.8101    +0.0011
Currency                                  0.63        45     0.9890     1.0000    +0.0110
Duration                                  0.58       340     0.8534     0.8635    +0.0101
Elongated                                 0.69       168     0.7805     0.7948    +0.0143
Eventive                                  0.68      1068     0.8822     0.8855    +0.0033
Feminine                                  0.50       204     0.9487     0.9487    +0.0000
Fluid                                     0.69        19     0.8947     0.9189    +0.0242
Garment                                   0.18        17     0.9032     0.9714    +0.0682
Inanimate                                 0.66      1511     0.9340     0.9357    +0.0017
Internal_Control                          0.12        21     0.3846     0.5946    +0.2100
Language                                  0.68         5     0.8333     1.0000    +0.1667
Location                                  0.43      1209     0.9250     0.9280    +0.0030
Machine                                   0.25       180     0.8889     0.8989    +0.0100
Masculine                                 0.19       671     0.9282     0.9323    +0.0041
Natural                                   0.72        79     0.8718     0.8742    +0.0024
Natural_Force                             0.50        35     0.8732     0.8732    +0.0000
Non_Rigid                                 0.58       335     0.8082     0.8097    +0.0015
Organisation                              0.62      1086     0.8934     0.8976    +0.0042
Plant                                     0.47        15     0.8571     0.8966    +0.0394
Point_in_Time                             0.32       336     0.8759     0.8809    +0.0050
Pointy                                    0.45        20     0.7368     0.7805    +0.0436
Question                                  0.53        33     0.8438     0.8710    +0.0272
Rigid                                     0.35       603     0.8752     0.8848    +0.0096
Solid                                     0.47      1409     0.8907     0.8929    +0.0022
Sound                                     0.67        42     0.7907     0.8395    +0.0488
Statement                                 0.26       264     0.7598     0.7806    +0.0207
Substance                                 0.35       217     0.8858     0.8953    +0.0095
Time                                      0.22        16     0.4545     0.5882    +0.1337
Unspecified_Gender_or_Neuter              0.43       677     0.8817     0.8858    +0.0041
Vehicle                                   0.33       100     0.9592     0.9697    +0.0105
Web_Location                              0.77        55     0.8850     0.9434    +0.0584

VALIDATION @ 0.5
direct_f1_macro: 0.8515618848970998
direct_f1_micro: 0.8901691681039228
direct_precision_macro: 0.8842691851424839
direct_precision_micro: 0.8917726637747224
direct_recall_macro: 0.8405811112405409
direct_recall_micro: 0.8885714285714286
f1_macro: 0.8978631105604362
f1_micro: 0.9364286288055266
precision_macro: 0.9042676172802151
precision_micro: 0.9410093313099351
recall_macro: 0.8939150008259813
recall_micro: 0.9318923067084479

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8804396069417124
direct_f1_micro: 0.8952715047869619
direct_precision_macro: 0.8861804864033668
direct_precision_micro: 0.8931175269757947
direct_recall_macro: 0.8768101151396492
direct_recall_micro: 0.8974358974358975
f1_macro: 0.9149439836460929
f1_micro: 0.9407824094107089
precision_macro: 0.9206032465548478
precision_micro: 0.9430646145937088
recall_macro: 0.9104374985114669
recall_micro: 0.9385112233804438

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7847535671664957
direct_f1_micro: 0.8649661989433619
direct_precision_macro: 0.822689580774715
direct_precision_micro: 0.8672818409660515
direct_recall_macro: 0.7725400481685224
direct_recall_micro: 0.8626628895184136
f1_macro: 0.861802086944757
f1_micro: 0.9183320756554125
precision_macro: 0.8753470084440858
precision_micro: 0.9195632038219665
recall_macro: 0.8543263591504094
recall_micro: 0.9171042395954881

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7840501936054652
direct_f1_micro: 0.8628804163366897
direct_precision_macro: 0.799672154363734
direct_precision_micro: 0.8615158703264431
direct_recall_macro: 0.7780153095455543
direct_recall_micro: 0.8642492917847026
f1_macro: 0.8593761123989001
f1_micro: 0.9187823425086854
precision_macro: 0.8747630744047717
precision_micro: 0.9182246394405866
recall_macro: 0.8515210841888384
recall_micro: 0.9193407234539089

====================================================================================================
RUN 12/30 | SEED 223
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 979.52it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.34      1405     0.8995     0.9028    +0.0034
Animal                                    0.74       184     0.9448     0.9500    +0.0052
Animate                                   0.16        13     0.8696     0.8800    +0.0104
Artefact                                  0.64       503     0.8973     0.9015    +0.0042
Body_Part                                 0.24        74     0.9315     0.9396    +0.0081
Comestible                                0.38       157     0.9518     0.9527    +0.0009
Communication                             0.44       534     0.8105     0.8133    +0.0029
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.49       340     0.8584     0.8601    +0.0017
Elongated                                 0.47       168     0.7844     0.7882    +0.0038
Eventive                                  0.36      1068     0.8879     0.8918    +0.0038
Feminine                                  0.28       204     0.9409     0.9415    +0.0006
Fluid                                     0.82        19     0.8421     0.8889    +0.0468
Garment                                   0.25        17     0.9091     0.9189    +0.0098
Inanimate                                 0.69      1511     0.9322     0.9346    +0.0024
Internal_Control                          0.13        21     0.3704     0.5294    +0.1590
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.62      1209     0.9193     0.9226    +0.0033
Machine                                   0.44       180     0.8895     0.8997    +0.0102
Masculine                                 0.24       671     0.9371     0.9373    +0.0002
Natural                                   0.54        79     0.8790     0.8846    +0.0056
Natural_Force                             0.56        35     0.8451     0.8696    +0.0245
Non_Rigid                                 0.52       335     0.7953     0.7988    +0.0035
Organisation                              0.68      1086     0.8895     0.8952    +0.0057
Plant                                     0.50        15     0.9333     0.9333    +0.0000
Point_in_Time                             0.46       336     0.8726     0.8776    +0.0050
Pointy                                    0.46        20     0.7000     0.7619    +0.0619
Question                                  0.07        33     0.8387     0.8788    +0.0401
Rigid                                     0.39       603     0.8706     0.8747    +0.0041
Solid                                     0.60      1409     0.8909     0.8945    +0.0036
Sound                                     0.85        42     0.8140     0.8421    +0.0282
Statement                                 0.68       264     0.7701     0.7787    +0.0086
Substance                                 0.12       217     0.8677     0.8874    +0.0197
Time                                      0.33        16     0.3636     0.4828    +0.1191
Unspecified_Gender_or_Neuter              0.49       677     0.8918     0.8920    +0.0002
Vehicle                                   0.75       100     0.9552     0.9697    +0.0145
Web_Location                              0.75        55     0.8704     0.9038    +0.0335

VALIDATION @ 0.5
direct_f1_macro: 0.8547001548700398
direct_f1_micro: 0.8907680429427552
direct_precision_macro: 0.8845422515249407
direct_precision_micro: 0.8940881245848402
direct_recall_macro: 0.840269113387988
direct_recall_micro: 0.8874725274725275
f1_macro: 0.9016658901398944
f1_micro: 0.9363659760648565
precision_macro: 0.9086175041689452
precision_micro: 0.9421246844047387
recall_macro: 0.8952069131503351
recall_micro: 0.9306772398797724

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8723904085761431
direct_f1_micro: 0.8950828100326833
direct_precision_macro: 0.884143364205717
direct_precision_micro: 0.8973566011339371
direct_recall_macro: 0.8645955067986232
direct_recall_micro: 0.8928205128205128
f1_macro: 0.9109377026142278
f1_micro: 0.9392661731573866
precision_macro: 0.9173546644208265
precision_micro: 0.9454739843193157
recall_macro: 0.9063186658885326
recall_micro: 0.9331393489799834

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7722465754583229
direct_f1_micro: 0.8627851549199864
direct_precision_macro: 0.8166042260749447
direct_precision_micro: 0.8641582357621916
direct_recall_macro: 0.7581861661556744
direct_recall_micro: 0.8614164305949008
f1_macro: 0.8492059948942776
f1_micro: 0.916321861461325
precision_macro: 0.8685958699202325
precision_micro: 0.9174383468174286
recall_macro: 0.8391673990638185
recall_micro: 0.9152080902372618

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.773574669234764
direct_f1_micro: 0.8623801146359458
direct_precision_macro: 0.8032269987413285
direct_precision_micro: 0.8638017280582083
direct_recall_macro: 0.7600096331792432
direct_recall_micro: 0.8609631728045326
f1_macro: 0.8468681974070833
f1_micro: 0.9162359824475865
precision_macro: 0.8707700694034752
precision_micro: 0.9188343438294543
recall_macro: 0.8348048622583303
recall_micro: 0.9136522753792299

====================================================================================================
RUN 13/30 | SEED 251
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 986.03it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.87      1405     0.8911     0.8979    +0.0068
Animal                                    0.37       184     0.9389     0.9418    +0.0029
Animate                                   0.50        13     0.8696     0.8696    +0.0000
Artefact                                  0.52       503     0.9069     0.9078    +0.0009
Body_Part                                 0.29        74     0.9388     0.9396    +0.0008
Comestible                                0.51       157     0.9560     0.9620    +0.0061
Communication                             0.22       534     0.7951     0.8021    +0.0070
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.91       340     0.8423     0.8531    +0.0108
Elongated                                 0.28       168     0.7673     0.7918    +0.0245
Eventive                                  0.62      1068     0.8883     0.8889    +0.0006
Feminine                                  0.64       204     0.9298     0.9343    +0.0045
Fluid                                     0.78        19     0.9000     0.9474    +0.0474
Garment                                   0.50        17     0.9714     0.9714    +0.0000
Inanimate                                 0.41      1511     0.9374     0.9390    +0.0016
Internal_Control                          0.30        21     0.3846     0.5000    +0.1154
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.43      1209     0.9187     0.9199    +0.0012
Machine                                   0.50       180     0.8914     0.8914    +0.0000
Masculine                                 0.22       671     0.9327     0.9363    +0.0036
Natural                                   0.50        79     0.8987     0.8987    +0.0000
Natural_Force                             0.62        35     0.8732     0.8857    +0.0125
Non_Rigid                                 0.66       335     0.8107     0.8187    +0.0080
Organisation                              0.47      1086     0.9002     0.9008    +0.0006
Plant                                     0.40        15     0.9286     0.9655    +0.0369
Point_in_Time                             0.14       336     0.8649     0.8764    +0.0115
Pointy                                    0.50        20     0.7692     0.7692    +0.0000
Question                                  0.05        33     0.8571     0.8732    +0.0161
Rigid                                     0.63       603     0.8834     0.8852    +0.0018
Solid                                     0.43      1409     0.8961     0.8984    +0.0023
Sound                                     0.67        42     0.7619     0.8000    +0.0381
Statement                                 0.52       264     0.7719     0.7725    +0.0006
Substance                                 0.49       217     0.9041     0.9045    +0.0004
Time                                      0.10        16     0.2857     0.5238    +0.2381
Unspecified_Gender_or_Neuter              0.44       677     0.8968     0.8977    +0.0010
Vehicle                                   0.48       100     0.9645     0.9697    +0.0052
Web_Location                              0.94        55     0.8807     0.9143    +0.0336

VALIDATION @ 0.5
direct_f1_macro: 0.8596803275842725
direct_f1_micro: 0.892813776355006
direct_precision_macro: 0.8939768662250297
direct_precision_micro: 0.8968729208250167
direct_recall_macro: 0.8456110752214864
direct_recall_micro: 0.8887912087912088
f1_macro: 0.9084398959332219
f1_micro: 0.9398400669337581
precision_macro: 0.9156188861716158
precision_micro: 0.9458820481264372
recall_macro: 0.9021476965991193
recall_micro: 0.9338747841657606

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8770016187523443
direct_f1_micro: 0.8962777696042372
direct_precision_macro: 0.8889458797608588
direct_precision_micro: 0.8999852267690944
direct_recall_macro: 0.8720632222969532
direct_recall_micro: 0.8926007326007326
f1_macro: 0.9152901445148361
f1_micro: 0.9405462793166682
precision_macro: 0.9215961178667914
precision_micro: 0.9463615175449954
recall_macro: 0.9102717076466019
recall_micro: 0.9348020720086974

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7833222248140759
direct_f1_micro: 0.8612831732681707
direct_precision_macro: 0.8180071538688037
direct_precision_micro: 0.8638850889192886
direct_recall_macro: 0.7773698400948159
direct_recall_micro: 0.8586968838526913
f1_macro: 0.8594480649879552
f1_micro: 0.9163980857505616
precision_macro: 0.8723917320165109
precision_micro: 0.9204433980773004
recall_macro: 0.8520135347101965
recall_micro: 0.912388175807079

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.776831163555411
direct_f1_micro: 0.8586684844353556
direct_precision_macro: 0.8012344994350368
direct_precision_micro: 0.8609181000113908
direct_recall_macro: 0.7743527199088451
direct_recall_micro: 0.8564305949008498
f1_macro: 0.8548420626240488
f1_micro: 0.9156532546974386
precision_macro: 0.8699135994059011
precision_micro: 0.9179574883948204
recall_macro: 0.8457742349259971
recall_micro: 0.9133605600933489

====================================================================================================
RUN 14/30 | SEED 281
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 980.91it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.81      1405     0.8897     0.8938    +0.0041
Animal                                    0.16       184     0.9477     0.9539    +0.0063
Animate                                   0.43        13     0.8696     0.9167    +0.0471
Artefact                                  0.42       503     0.9071     0.9127    +0.0057
Body_Part                                 0.35        74     0.9178     0.9189    +0.0011
Comestible                                0.33       157     0.9551     0.9590    +0.0039
Communication                             0.39       534     0.7894     0.7956    +0.0062
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.81       340     0.8389     0.8492    +0.0103
Elongated                                 0.52       168     0.7877     0.7926    +0.0049
Eventive                                  0.59      1068     0.8822     0.8840    +0.0018
Feminine                                  0.90       204     0.9291     0.9450    +0.0159
Fluid                                     0.50        19     0.8889     0.8889    +0.0000
Garment                                   0.52        17     0.9714     1.0000    +0.0286
Inanimate                                 0.54      1511     0.9368     0.9383    +0.0015
Internal_Control                          0.06        21     0.3704     0.5556    +0.1852
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.39      1209     0.9186     0.9204    +0.0019
Machine                                   0.51       180     0.9049     0.9075    +0.0026
Masculine                                 0.58       671     0.9365     0.9378    +0.0013
Natural                                   0.50        79     0.8903     0.8903    +0.0000
Natural_Force                             0.26        35     0.8358     0.8571    +0.0213
Non_Rigid                                 0.34       335     0.8053     0.8126    +0.0073
Organisation                              0.55      1086     0.8898     0.8919    +0.0021
Plant                                     0.43        15     0.8966     0.9333    +0.0368
Point_in_Time                             0.22       336     0.8679     0.8754    +0.0075
Pointy                                    0.48        20     0.7222     0.7692    +0.0470
Question                                  0.14        33     0.8387     0.8529    +0.0142
Rigid                                     0.27       603     0.8739     0.8844    +0.0104
Solid                                     0.61      1409     0.8890     0.8902    +0.0013
Sound                                     0.83        42     0.8000     0.8533    +0.0533
Statement                                 0.76       264     0.7519     0.7598    +0.0079
Substance                                 0.36       217     0.8807     0.8933    +0.0126
Time                                      0.12        16     0.2222     0.5238    +0.3016
Unspecified_Gender_or_Neuter              0.56       677     0.8910     0.8934    +0.0023
Vehicle                                   0.72       100     0.9447     0.9588    +0.0140
Web_Location                              0.83        55     0.8624     0.8868    +0.0244

VALIDATION @ 0.5
direct_f1_macro: 0.85146296515728
direct_f1_micro: 0.8888480211858173
direct_precision_macro: 0.898972714594682
direct_precision_micro: 0.8925247451617668
direct_recall_macro: 0.8333670705404895
direct_recall_micro: 0.8852014652014653
f1_macro: 0.9021775526730628
f1_micro: 0.9364063304168811
precision_macro: 0.9131712903597469
precision_micro: 0.9420425862403727
recall_macro: 0.892363719742763
recall_micro: 0.9308371170940718

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8755811864002272
direct_f1_micro: 0.8932296465558545
direct_precision_macro: 0.8886148076802014
direct_precision_micro: 0.8987614032485352
direct_recall_macro: 0.8673033258897797
direct_recall_micro: 0.8877655677655678
f1_macro: 0.9110088203277371
f1_micro: 0.9374143297156956
precision_macro: 0.9225501972309497
precision_micro: 0.9456030191625728
recall_macro: 0.9012169312571311
recall_micro: 0.9293662467225171

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.769027470837671
direct_f1_micro: 0.8603237716557796
direct_precision_macro: 0.8192628078231827
direct_precision_micro: 0.8625284738041002
direct_recall_macro: 0.7518326089539198
direct_recall_micro: 0.8581303116147309
f1_macro: 0.8485124650639377
f1_micro: 0.9168046760837798
precision_macro: 0.8686374627342963
precision_micro: 0.9185047823540894
recall_macro: 0.837225834201615
recall_micro: 0.9151108518086347

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7683645022476048
direct_f1_micro: 0.8580043235863011
direct_precision_macro: 0.7930593988205825
direct_precision_micro: 0.8615331886210442
direct_recall_macro: 0.7594192965146241
direct_recall_micro: 0.8545042492917847
f1_macro: 0.8461434202773207
f1_micro: 0.9142675750250286
precision_macro: 0.8710722608422083
precision_micro: 0.9183713514839342
recall_macro: 0.8326820566797369
recall_micro: 0.9102003111629716

====================================================================================================
RUN 15/30 | SEED 313
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 987.60it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.69      1405     0.8956     0.8981    +0.0025
Animal                                    0.54       184     0.9392     0.9418    +0.0026
Animate                                   0.41        13     0.8696     0.9167    +0.0471
Artefact                                  0.50       503     0.9049     0.9049    +0.0000
Body_Part                                 0.50        74     0.8951     0.8951    +0.0000
Comestible                                0.62       157     0.9585     0.9646    +0.0062
Communication                             0.49       534     0.8146     0.8157    +0.0011
Currency                                  0.67        45     0.9890     1.0000    +0.0110
Duration                                  0.57       340     0.8666     0.8712    +0.0046
Elongated                                 0.65       168     0.7584     0.7767    +0.0183
Eventive                                  0.59      1068     0.8835     0.8848    +0.0013
Feminine                                  0.74       204     0.9369     0.9429    +0.0060
Fluid                                     0.64        19     0.8947     0.9189    +0.0242
Garment                                   0.65        17     0.9714     1.0000    +0.0286
Inanimate                                 0.52      1511     0.9384     0.9390    +0.0006
Internal_Control                          0.13        21     0.3846     0.4865    +0.1019
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.36      1209     0.9255     0.9260    +0.0005
Machine                                   0.52       180     0.8964     0.8989    +0.0025
Masculine                                 0.49       671     0.9357     0.9365    +0.0008
Natural                                   0.60        79     0.8974     0.9032    +0.0058
Natural_Force                             0.61        35     0.8235     0.8615    +0.0380
Non_Rigid                                 0.58       335     0.7947     0.8006    +0.0059
Organisation                              0.44      1086     0.8929     0.8955    +0.0026
Plant                                     0.29        15     0.8667     0.9032    +0.0366
Point_in_Time                             0.36       336     0.8636     0.8689    +0.0054
Pointy                                    0.36        20     0.6286     0.7442    +0.1156
Question                                  0.19        33     0.8197     0.8615    +0.0419
Rigid                                     0.27       603     0.8765     0.8827    +0.0063
Solid                                     0.53      1409     0.8947     0.8954    +0.0007
Sound                                     0.50        42     0.8049     0.8049    +0.0000
Statement                                 0.73       264     0.7558     0.7592    +0.0034
Substance                                 0.23       217     0.8811     0.8980    +0.0169
Time                                      0.38        16     0.4348     0.5185    +0.0837
Unspecified_Gender_or_Neuter              0.26       677     0.8858     0.8903    +0.0046
Vehicle                                   0.54       100     0.9495     0.9592    +0.0097
Web_Location                              0.93        55     0.8571     0.9143    +0.0571

VALIDATION @ 0.5
direct_f1_macro: 0.8536708598818353
direct_f1_micro: 0.8917094644167278
direct_precision_macro: 0.8889008414304079
direct_precision_micro: 0.8930198383541513
direct_recall_macro: 0.837554335694245
direct_recall_micro: 0.8904029304029304
f1_macro: 0.898220501055406
f1_micro: 0.937933470331364
precision_macro: 0.9066416793576965
precision_micro: 0.9418649642097118
recall_macro: 0.8911177867227295
recall_micro: 0.9340346613800601

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8724214975120314
direct_f1_micro: 0.8952192403578237
direct_precision_macro: 0.8871653083898563
direct_precision_micro: 0.8960076324673418
direct_recall_macro: 0.8611983971165932
direct_recall_micro: 0.8944322344322344
f1_macro: 0.9098634826413289
f1_micro: 0.9393915093583102
precision_macro: 0.9174517999701991
precision_micro: 0.9423689545322907
recall_macro: 0.9038948540806637
recall_micro: 0.9364328195945514

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7841256049722491
direct_f1_micro: 0.8611663165067287
direct_precision_macro: 0.8079230268109973
direct_precision_micro: 0.863077623491919
direct_recall_macro: 0.774365110014943
direct_recall_micro: 0.8592634560906516
f1_macro: 0.8593713560659675
f1_micro: 0.9155850492827169
precision_macro: 0.8721967908019229
precision_micro: 0.9189030362389814
recall_macro: 0.8501747616606622
recall_micro: 0.912290937378452

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7821846200446777
direct_f1_micro: 0.8602565557952094
direct_precision_macro: 0.8078685407367473
direct_precision_micro: 0.8618219037871033
direct_recall_macro: 0.7694175571559274
direct_recall_micro: 0.8586968838526913
f1_macro: 0.858580056283752
f1_micro: 0.9154514691920053
precision_macro: 0.8764441599038056
precision_micro: 0.916768248086206
recall_macro: 0.8467817629169142
recall_micro: 0.9141384675223648

====================================================================================================
RUN 16/30 | SEED 347
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 987.63it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.66      1405     0.9005     0.9033    +0.0028
Animal                                    0.20       184     0.9474     0.9505    +0.0032
Animate                                   0.16        13     0.8696     0.9600    +0.0904
Artefact                                  0.37       503     0.8990     0.9096    +0.0106
Body_Part                                 0.10        74     0.9241     0.9467    +0.0225
Comestible                                0.48       157     0.9494     0.9527    +0.0033
Communication                             0.28       534     0.8049     0.8072    +0.0023
Currency                                  0.50        45     0.9890     0.9890    +0.0000
Duration                                  0.71       340     0.8534     0.8537    +0.0003
Elongated                                 0.69       168     0.7616     0.7821    +0.0204
Eventive                                  0.48      1068     0.8858     0.8874    +0.0017
Feminine                                  0.92       204     0.9294     0.9447    +0.0153
Fluid                                     0.12        19     0.8571     0.9231    +0.0659
Garment                                   0.46        17     0.8750     0.9412    +0.0662
Inanimate                                 0.70      1511     0.9376     0.9401    +0.0025
Internal_Control                          0.13        21     0.3846     0.6061    +0.2214
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.63      1209     0.9198     0.9251    +0.0053
Machine                                   0.64       180     0.8989     0.9049    +0.0060
Masculine                                 0.27       671     0.9327     0.9371    +0.0044
Natural                                   0.50        79     0.8947     0.8947    +0.0000
Natural_Force                             0.53        35     0.8824     0.8955    +0.0132
Non_Rigid                                 0.44       335     0.7982     0.8064    +0.0082
Organisation                              0.60      1086     0.8952     0.8974    +0.0022
Plant                                     0.66        15     0.8966     0.9286    +0.0320
Point_in_Time                             0.34       336     0.8619     0.8730    +0.0111
Pointy                                    0.32        20     0.6857     0.7111    +0.0254
Question                                  0.06        33     0.8387     0.9143    +0.0756
Rigid                                     0.54       603     0.8818     0.8823    +0.0005
Solid                                     0.63      1409     0.8938     0.8953    +0.0015
Sound                                     0.34        42     0.8205     0.8395    +0.0190
Statement                                 0.53       264     0.7626     0.7671    +0.0045
Substance                                 0.44       217     0.8909     0.8989    +0.0080
Time                                      0.30        16     0.3636     0.5161    +0.1525
Unspecified_Gender_or_Neuter              0.56       677     0.8931     0.8951    +0.0020
Vehicle                                   0.50       100     0.9645     0.9645    +0.0000
Web_Location                              0.89        55     0.8421     0.9143    +0.0722

VALIDATION @ 0.5
direct_f1_macro: 0.8536768535445455
direct_f1_micro: 0.8921074881446899
direct_precision_macro: 0.896870825852296
direct_precision_micro: 0.8952999335940383
direct_recall_macro: 0.8313245589505537
direct_recall_micro: 0.8889377289377289
f1_macro: 0.9003873437527548
f1_micro: 0.9384098183982371
precision_macro: 0.9154252543091211
precision_micro: 0.9441657226088364
recall_macro: 0.8874428424322678
recall_micro: 0.9327236682228048

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8799620753397306
direct_f1_micro: 0.8966558632881556
direct_precision_macro: 0.8933761999968342
direct_precision_micro: 0.9015701377573693
direct_recall_macro: 0.8712154542938343
direct_recall_micro: 0.8917948717948718
f1_macro: 0.9130237067958052
f1_micro: 0.9404616078911741
precision_macro: 0.9196789311967373
precision_micro: 0.9481637959051024
recall_macro: 0.9080697347143004
recall_micro: 0.9328835454371043

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7823124771785749
direct_f1_micro: 0.86226254607315
direct_precision_macro: 0.818511751871442
direct_precision_micro: 0.8629965947786606
direct_recall_macro: 0.7728103201648538
direct_recall_micro: 0.8615297450424929
f1_macro: 0.8598319711080306
f1_micro: 0.917339841366687
precision_macro: 0.8715776620595216
precision_micro: 0.9209584946341941
recall_macro: 0.8518389008517487
recall_micro: 0.9137495138078569

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7839421285257744
direct_f1_micro: 0.8599612270498347
direct_precision_macro: 0.8066826305379639
direct_precision_micro: 0.8654883507402732
direct_recall_macro: 0.7739884979133318
direct_recall_micro: 0.8545042492917847
f1_macro: 0.8531649006933916
f1_micro: 0.9151220947337452
precision_macro: 0.8708257440386813
precision_micro: 0.9229970326409496
recall_macro: 0.843102365599615
recall_micro: 0.9073803967327888

====================================================================================================
RUN 17/30 | SEED 383
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 972.38it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.43      1405     0.9006     0.9014    +0.0008
Animal                                    0.22       184     0.9454     0.9485    +0.0032
Animate                                   0.50        13     0.8696     0.8696    +0.0000
Artefact                                  0.52       503     0.9028     0.9046    +0.0018
Body_Part                                 0.81        74     0.9054     0.9231    +0.0177
Comestible                                0.49       157     0.9490     0.9524    +0.0033
Communication                             0.42       534     0.8061     0.8115    +0.0055
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.54       340     0.8584     0.8626    +0.0042
Elongated                                 0.62       168     0.7748     0.7900    +0.0152
Eventive                                  0.55      1068     0.8842     0.8863    +0.0021
Feminine                                  0.85       204     0.9461     0.9500    +0.0039
Fluid                                     0.50        19     0.8649     0.8649    +0.0000
Garment                                   0.25        17     0.9412     0.9444    +0.0033
Inanimate                                 0.45      1511     0.9338     0.9349    +0.0011
Internal_Control                          0.15        21     0.4286     0.5641    +0.1355
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.45      1209     0.9260     0.9271    +0.0011
Machine                                   0.54       180     0.8750     0.8818    +0.0068
Masculine                                 0.64       671     0.9314     0.9375    +0.0061
Natural                                   0.65        79     0.8516     0.8800    +0.0284
Natural_Force                             0.50        35     0.8696     0.8696    +0.0000
Non_Rigid                                 0.54       335     0.7853     0.7888    +0.0035
Organisation                              0.71      1086     0.8884     0.8932    +0.0049
Plant                                     0.50        15     0.8966     0.8966    +0.0000
Point_in_Time                             0.26       336     0.8705     0.8770    +0.0065
Pointy                                    0.50        20     0.8000     0.8000    +0.0000
Question                                  0.06        33     0.8387     0.8986    +0.0598
Rigid                                     0.31       603     0.8678     0.8746    +0.0068
Solid                                     0.41      1409     0.8895     0.8907    +0.0012
Sound                                     0.73        42     0.8148     0.8421    +0.0273
Statement                                 0.37       264     0.7742     0.7790    +0.0048
Substance                                 0.19       217     0.8677     0.8835    +0.0158
Time                                      0.20        16     0.4167     0.5333    +0.1167
Unspecified_Gender_or_Neuter              0.30       677     0.8917     0.8966    +0.0049
Vehicle                                   0.60       100     0.9645     0.9694    +0.0049
Web_Location                              0.88        55     0.8727     0.9020    +0.0292

VALIDATION @ 0.5
direct_f1_macro: 0.8595472992292625
direct_f1_micro: 0.8904461402993836
direct_precision_macro: 0.8865661658824224
direct_precision_micro: 0.8918859326767603
direct_recall_macro: 0.8443653622238682
direct_recall_micro: 0.889010989010989
f1_macro: 0.9042060898533285
f1_micro: 0.9364080164439876
precision_macro: 0.9113665859485004
precision_micro: 0.9405768114071875
recall_macro: 0.8975001532599572
recall_micro: 0.9322760120227666

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8737687966634017
direct_f1_micro: 0.894158050491396
direct_precision_macro: 0.8855101928828407
direct_precision_micro: 0.8918446177392318
direct_recall_macro: 0.8651082680906451
direct_recall_micro: 0.8964835164835164
f1_macro: 0.9106039122951944
f1_micro: 0.9387185288595773
precision_macro: 0.9167007185025751
precision_micro: 0.9421807054276051
recall_macro: 0.9062158371851532
recall_micro: 0.9352817036515956

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7781324221743718
direct_f1_micro: 0.861908544196074
direct_precision_macro: 0.8019944329482142
direct_precision_micro: 0.8630837404840359
direct_recall_macro: 0.769743088015643
direct_recall_micro: 0.8607365439093484
f1_macro: 0.8572273751186174
f1_micro: 0.9166829268292683
precision_macro: 0.8686469405892692
precision_micro: 0.9197337509788567
recall_macro: 0.8508409618474219
recall_micro: 0.9136522753792299

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7815518132747205
direct_f1_micro: 0.8596124512739394
direct_precision_macro: 0.7926569371060079
direct_precision_micro: 0.8571428571428571
direct_recall_macro: 0.7797581788294078
direct_recall_micro: 0.8620963172804532
f1_macro: 0.8538868175159317
f1_micro: 0.9157548434263434
precision_macro: 0.8646800642889971
precision_micro: 0.918014364586896
recall_macro: 0.8500561528901386
recall_micro: 0.9135064177362894

====================================================================================================
RUN 18/30 | SEED 421
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1011.32it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.68      1405     0.9010     0.9044    +0.0035
Animal                                    0.50       184     0.9448     0.9448    +0.0000
Animate                                   0.45        13     0.8182     0.8696    +0.0514
Artefact                                  0.38       503     0.9034     0.9064    +0.0030
Body_Part                                 0.07        74     0.9028     0.9241    +0.0213
Comestible                                0.43       157     0.9518     0.9618    +0.0100
Communication                             0.50       534     0.8145     0.8145    +0.0000
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.59       340     0.8538     0.8584    +0.0047
Elongated                                 0.59       168     0.7914     0.8076    +0.0162
Eventive                                  0.54      1068     0.8888     0.8906    +0.0018
Feminine                                  0.50       204     0.9463     0.9463    +0.0000
Fluid                                     0.27        19     0.8421     0.8718    +0.0297
Garment                                   0.17        17     0.9091     0.9444    +0.0354
Inanimate                                 0.42      1511     0.9355     0.9374    +0.0019
Internal_Control                          0.11        21     0.3846     0.4706    +0.0860
Language                                  0.90         5     0.9091     1.0000    +0.0909
Location                                  0.61      1209     0.9279     0.9298    +0.0019
Machine                                   0.42       180     0.8807     0.8876    +0.0070
Masculine                                 0.76       671     0.9379     0.9409    +0.0030
Natural                                   0.47        79     0.8590     0.8734    +0.0144
Natural_Force                             0.50        35     0.8732     0.8732    +0.0000
Non_Rigid                                 0.36       335     0.7882     0.7994    +0.0112
Organisation                              0.36      1086     0.8936     0.8962    +0.0026
Plant                                     0.50        15     0.8966     0.8966    +0.0000
Point_in_Time                             0.29       336     0.8681     0.8748    +0.0067
Pointy                                    0.61        20     0.7895     0.8108    +0.0213
Question                                  0.29        33     0.8333     0.8889    +0.0556
Rigid                                     0.22       603     0.8757     0.8783    +0.0026
Solid                                     0.55      1409     0.8919     0.8939    +0.0020
Sound                                     0.66        42     0.8095     0.8250    +0.0155
Statement                                 0.29       264     0.7452     0.7585    +0.0133
Substance                                 0.22       217     0.8848     0.8961    +0.0113
Time                                      0.49        16     0.5000     0.5600    +0.0600
Unspecified_Gender_or_Neuter              0.42       677     0.8910     0.8940    +0.0029
Vehicle                                   0.43       100     0.9645     0.9697    +0.0052
Web_Location                              0.82        55     0.8889     0.9038    +0.0150

VALIDATION @ 0.5
direct_f1_macro: 0.8566653817018886
direct_f1_micro: 0.8927126994631959
direct_precision_macro: 0.8923760594101053
direct_precision_micro: 0.8960732211396516
direct_recall_macro: 0.8398324077543902
direct_recall_micro: 0.8893772893772893
f1_macro: 0.901724824878066
f1_micro: 0.9380189225719251
precision_macro: 0.9105557099585462
precision_micro: 0.9440953553151519
recall_macro: 0.8941635225659821
recall_micro: 0.9320202084798874

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8730686274402194
direct_f1_micro: 0.8962260697682931
direct_precision_macro: 0.8876611544236174
direct_precision_micro: 0.8956031896993196
direct_recall_macro: 0.8652179145682265
direct_recall_micro: 0.8968498168498168
f1_macro: 0.9122483228345865
f1_micro: 0.9402289648546954
precision_macro: 0.9142086090202602
precision_micro: 0.941631121516308
recall_macro: 0.9120406164154631
recall_micro: 0.9388309778090427

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7835891339269565
direct_f1_micro: 0.860153802335517
direct_precision_macro: 0.8168276561154951
direct_precision_micro: 0.8648339060710195
direct_recall_macro: 0.7678531741640748
direct_recall_micro: 0.8555240793201133
f1_macro: 0.8679613880254956
f1_micro: 0.9158622712054935
precision_macro: 0.886621777921236
precision_micro: 0.9206996511570775
recall_macro: 0.8537312098969946
recall_micro: 0.9110754570206145

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.76977223030724
direct_f1_micro: 0.858942351339083
direct_precision_macro: 0.8081662256985314
direct_precision_micro: 0.8602113876576883
direct_recall_macro: 0.7548137017302133
direct_recall_micro: 0.8576770538243627
f1_macro: 0.8516806019360619
f1_micro: 0.914512438537559
precision_macro: 0.8818749620109116
precision_micro: 0.9157160963244614
recall_macro: 0.8390946656214339
recall_micro: 0.9133119408790354

====================================================================================================
RUN 19/30 | SEED 461
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 962.51it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.78      1405     0.8991     0.9024    +0.0033
Animal                                    0.82       184     0.9415     0.9441    +0.0026
Animate                                   0.23        13     0.7273     0.8000    +0.0727
Artefact                                  0.33       503     0.9032     0.9050    +0.0017
Body_Part                                 0.75        74     0.9067     0.9362    +0.0295
Comestible                                0.33       157     0.9434     0.9470    +0.0036
Communication                             0.53       534     0.8093     0.8101    +0.0008
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.20       340     0.8546     0.8636    +0.0089
Elongated                                 0.59       168     0.7903     0.8013    +0.0110
Eventive                                  0.64      1068     0.8863     0.8884    +0.0021
Feminine                                  0.85       204     0.9161     0.9307    +0.0146
Fluid                                     0.50        19     0.9231     0.9231    +0.0000
Garment                                   0.50        17     0.9412     0.9412    +0.0000
Inanimate                                 0.59      1511     0.9386     0.9394    +0.0007
Internal_Control                          0.43        21     0.4286     0.5806    +0.1521
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.60      1209     0.9240     0.9259    +0.0019
Machine                                   0.39       180     0.8946     0.8989    +0.0043
Masculine                                 0.78       671     0.9302     0.9337    +0.0035
Natural                                   0.48        79     0.8974     0.8987    +0.0013
Natural_Force                             0.54        35     0.8857     0.8986    +0.0128
Non_Rigid                                 0.50       335     0.8113     0.8113    +0.0000
Organisation                              0.61      1086     0.8924     0.8944    +0.0020
Plant                                     0.46        15     0.8966     0.9333    +0.0368
Point_in_Time                             0.26       336     0.8744     0.8784    +0.0040
Pointy                                    0.40        20     0.6667     0.8293    +0.1626
Question                                  0.09        33     0.8387     0.8732    +0.0345
Rigid                                     0.25       603     0.8754     0.8828    +0.0074
Solid                                     0.54      1409     0.8922     0.8945    +0.0022
Sound                                     0.79        42     0.7160     0.8056    +0.0895
Statement                                 0.26       264     0.7456     0.7622    +0.0166
Substance                                 0.22       217     0.8718     0.8879    +0.0161
Time                                      0.17        16     0.2105     0.4571    +0.2466
Unspecified_Gender_or_Neuter              0.26       677     0.8869     0.8958    +0.0089
Vehicle                                   0.50       100     0.9648     0.9648    +0.0000
Web_Location                              0.88        55     0.8649     0.9231    +0.0582

VALIDATION @ 0.5
direct_f1_macro: 0.847281281791123
direct_f1_micro: 0.8913659272339329
direct_precision_macro: 0.8827152636029869
direct_precision_micro: 0.8952190940663564
direct_recall_macro: 0.8319228376477984
direct_recall_micro: 0.8875457875457875
f1_macro: 0.9006131127135242
f1_micro: 0.9379896086348063
precision_macro: 0.9088365179577761
precision_micro: 0.9437736704107726
recall_macro: 0.8933427504353693
recall_micro: 0.9322760120227666

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8746619952779774
direct_f1_micro: 0.8956473829201101
direct_precision_macro: 0.8866724016416209
direct_precision_micro: 0.898121546961326
direct_recall_macro: 0.8702403874991437
direct_recall_micro: 0.8931868131868131
f1_macro: 0.9147075130108271
f1_micro: 0.9401500666784492
precision_macro: 0.9186074277183442
precision_micro: 0.9448409494590667
recall_macro: 0.9134866007182364
recall_micro: 0.9355055317516148

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7706972966281828
direct_f1_micro: 0.8640373342439247
direct_precision_macro: 0.8119395889012272
direct_precision_micro: 0.8679396295449349
direct_recall_macro: 0.7525765890733036
direct_recall_micro: 0.8601699716713881
f1_macro: 0.8498220175779119
f1_micro: 0.918360367402775
precision_macro: 0.874015725826151
precision_micro: 0.9228692065985861
recall_macro: 0.8353224039356578
recall_micro: 0.9138953714507974

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7766021718300526
direct_f1_micro: 0.8624928856004553
direct_precision_macro: 0.8126681293355265
direct_precision_micro: 0.8664379645511721
direct_recall_macro: 0.7684045454146039
direct_recall_micro: 0.8585835694050992
f1_macro: 0.8529755873168261
f1_micro: 0.9165688001565864
precision_macro: 0.8799135201921734
precision_micro: 0.9225275807722616
recall_macro: 0.8393496760097514
recall_micro: 0.9106865033061066

====================================================================================================
RUN 20/30 | SEED 503
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 919.17it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.69      1405     0.8977     0.8998    +0.0021
Animal                                    0.56       184     0.9363     0.9389    +0.0026
Animate                                   0.07        13     0.8182     0.8800    +0.0618
Artefact                                  0.53       503     0.8989     0.9016    +0.0027
Body_Part                                 0.05        74     0.9028     0.9359    +0.0331
Comestible                                0.62       157     0.9434     0.9551    +0.0117
Communication                             0.18       534     0.7897     0.7979    +0.0082
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.29       340     0.8584     0.8620    +0.0036
Elongated                                 0.48       168     0.7900     0.7963    +0.0063
Eventive                                  0.44      1068     0.8853     0.8866    +0.0014
Feminine                                  0.92       204     0.9369     0.9479    +0.0110
Fluid                                     0.19        19     0.8718     0.9000    +0.0282
Garment                                   0.09        17     0.9697     1.0000    +0.0303
Inanimate                                 0.57      1511     0.9369     0.9386    +0.0017
Internal_Control                          0.09        21     0.3704     0.6111    +0.2407
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.51      1209     0.9201     0.9205    +0.0003
Machine                                   0.54       180     0.9060     0.9080    +0.0021
Masculine                                 0.35       671     0.9384     0.9442    +0.0058
Natural                                   0.91        79     0.8645     0.8671    +0.0026
Natural_Force                             0.66        35     0.8060     0.8254    +0.0194
Non_Rigid                                 0.59       335     0.7976     0.8061    +0.0084
Organisation                              0.42      1086     0.8965     0.8967    +0.0003
Plant                                     0.55        15     0.8667     0.8966    +0.0299
Point_in_Time                             0.55       336     0.8769     0.8808    +0.0040
Pointy                                    0.54        20     0.7805     0.8205    +0.0400
Question                                  0.15        33     0.8525     0.8615    +0.0091
Rigid                                     0.25       603     0.8848     0.8898    +0.0050
Solid                                     0.53      1409     0.8949     0.8956    +0.0007
Sound                                     0.82        42     0.8000     0.8169    +0.0169
Statement                                 0.89       264     0.7467     0.7597    +0.0129
Substance                                 0.58       217     0.8858     0.8884    +0.0025
Time                                      0.16        16     0.3000     0.5455    +0.2455
Unspecified_Gender_or_Neuter              0.34       677     0.8987     0.9020    +0.0032
Vehicle                                   0.11       100     0.9543     0.9600    +0.0057
Web_Location                              0.79        55     0.8571     0.8972    +0.0401

VALIDATION @ 0.5
direct_f1_macro: 0.8522781480558732
direct_f1_micro: 0.8920270667843483
direct_precision_macro: 0.8891166106688396
direct_precision_micro: 0.8955841086988628
direct_recall_macro: 0.8359603627490345
direct_recall_micro: 0.8884981684981685
f1_macro: 0.9034437470796002
f1_micro: 0.9387315221412601
precision_macro: 0.9115198536570839
precision_micro: 0.94448939957922
recall_macro: 0.8962655112822648
recall_micro: 0.9330434226514037

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8765993569315382
direct_f1_micro: 0.8958348637331962
direct_precision_macro: 0.8955442217617131
direct_precision_micro: 0.8982763700648203
direct_recall_macro: 0.8628731086129212
direct_recall_micro: 0.8934065934065935
f1_macro: 0.9122061703000492
f1_micro: 0.9408969790362451
precision_macro: 0.9253145568141554
precision_micro: 0.9446879834966477
recall_macro: 0.9024078759291202
recall_micro: 0.9371362793374688

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7706917219588136
direct_f1_micro: 0.8627294946853862
direct_precision_macro: 0.8055047027243701
direct_precision_micro: 0.8655337591240876
direct_recall_macro: 0.755269295325274
direct_recall_micro: 0.859943342776204
f1_macro: 0.8510764990025612
f1_micro: 0.9192443631931749
precision_macro: 0.8745973570502352
precision_micro: 0.9217382802952535
recall_macro: 0.837094285400137
recall_micro: 0.9167639050952937

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7713532365343243
direct_f1_micro: 0.8605785592739649
direct_precision_macro: 0.8020791191361242
direct_precision_micro: 0.8615559341283362
direct_recall_macro: 0.7587925215030863
direct_recall_micro: 0.8596033994334278
f1_macro: 0.8456736277844652
f1_micro: 0.9172789645272736
precision_macro: 0.8731176974408061
precision_micro: 0.9180383753774228
recall_macro: 0.8318036341725994
recall_micro: 0.9165208090237261

====================================================================================================
RUN 21/30 | SEED 547
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 972.36it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.49      1405     0.8995     0.9011    +0.0016
Animal                                    0.52       184     0.9474     0.9500    +0.0026
Animate                                   0.19        13     0.7619     0.9167    +0.1548
Artefact                                  0.56       503     0.8992     0.9015    +0.0023
Body_Part                                 0.21        74     0.9103     0.9342    +0.0239
Comestible                                0.81       157     0.9467     0.9613    +0.0146
Communication                             0.22       534     0.7855     0.8018    +0.0162
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.44       340     0.8571     0.8617    +0.0046
Elongated                                 0.50       168     0.7877     0.7877    +0.0000
Eventive                                  0.46      1068     0.8903     0.8917    +0.0013
Feminine                                  0.92       204     0.9261     0.9421    +0.0160
Fluid                                     0.50        19     0.9189     0.9189    +0.0000
Garment                                   0.42        17     0.9697     1.0000    +0.0303
Inanimate                                 0.46      1511     0.9349     0.9368    +0.0019
Internal_Control                          0.29        21     0.3704     0.6061    +0.2357
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.45      1209     0.9165     0.9175    +0.0010
Machine                                   0.48       180     0.8991     0.9023    +0.0032
Masculine                                 0.25       671     0.9328     0.9363    +0.0034
Natural                                   0.85        79     0.8816     0.8844    +0.0028
Natural_Force                             0.51        35     0.8571     0.8824    +0.0252
Non_Rigid                                 0.51       335     0.8012     0.8024    +0.0012
Organisation                              0.33      1086     0.8923     0.8978    +0.0054
Plant                                     0.39        15     0.8667     0.9032    +0.0366
Point_in_Time                             0.82       336     0.8724     0.8756    +0.0032
Pointy                                    0.36        20     0.6286     0.6977    +0.0691
Question                                  0.36        33     0.8750     0.8923    +0.0173
Rigid                                     0.32       603     0.8788     0.8869    +0.0080
Solid                                     0.47      1409     0.8921     0.8927    +0.0005
Sound                                     0.68        42     0.7674     0.8101    +0.0427
Statement                                 0.44       264     0.7398     0.7518    +0.0120
Substance                                 0.45       217     0.8904     0.8950    +0.0045
Time                                      0.59        16     0.4167     0.4762    +0.0595
Unspecified_Gender_or_Neuter              0.82       677     0.8863     0.8896    +0.0033
Vehicle                                   0.71       100     0.9600     0.9697    +0.0097
Web_Location                              0.90        55     0.8850     0.9174    +0.0325

VALIDATION @ 0.5
direct_f1_macro: 0.8525830349983633
direct_f1_micro: 0.8901244568819501
direct_precision_macro: 0.8858935469673239
direct_precision_micro: 0.8948030796564999
direct_recall_macro: 0.8347542505220763
direct_recall_micro: 0.8854945054945055
f1_macro: 0.9015263914530345
f1_micro: 0.9371097521725137
precision_macro: 0.9100904262809237
precision_micro: 0.9433033110866326
recall_macro: 0.8940771013107479
recall_micro: 0.9309969943083711

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.875470868193484
direct_f1_micro: 0.8943690315026892
direct_precision_macro: 0.9027195044775571
direct_precision_micro: 0.8933557488487683
direct_recall_macro: 0.8623435618251927
direct_recall_micro: 0.8953846153846153
f1_macro: 0.9112050339806652
f1_micro: 0.9384044586498771
precision_macro: 0.9165052206474473
precision_micro: 0.9427501855616871
recall_macro: 0.9068632154317492
recall_micro: 0.9340986122657798

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7742694715026901
direct_f1_micro: 0.864153951263949
direct_precision_macro: 0.8094157092197743
direct_precision_micro: 0.8684059961093946
direct_recall_macro: 0.7558371305047553
direct_recall_micro: 0.859943342776204
f1_macro: 0.8505665182622685
f1_micro: 0.918916280205028
precision_macro: 0.8741492370782762
precision_micro: 0.9226546417017939
recall_macro: 0.8359996054639416
recall_micro: 0.9152080902372618

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.773660168931897
direct_f1_micro: 0.8635615816644919
direct_precision_macro: 0.8043902512816176
direct_precision_micro: 0.8646898432174506
direct_recall_macro: 0.7543777460432617
direct_recall_micro: 0.8624362606232294
f1_macro: 0.8454593920351134
f1_micro: 0.9148192506049422
precision_macro: 0.8708160369985654
precision_micro: 0.9198328827721799
recall_macro: 0.8283179796704702
recall_micro: 0.9098599766627772

====================================================================================================
RUN 22/30 | SEED 593
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 973.74it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.75      1405     0.8932     0.8978    +0.0046
Animal                                    0.50       184     0.9508     0.9508    +0.0000
Animate                                   0.65        13     0.8000     0.8333    +0.0333
Artefact                                  0.48       503     0.9078     0.9091    +0.0013
Body_Part                                 0.12        74     0.9116     0.9231    +0.0115
Comestible                                0.38       157     0.9518     0.9554    +0.0036
Communication                             0.48       534     0.8140     0.8151    +0.0011
Currency                                  0.78        45     0.9783     1.0000    +0.0217
Duration                                  0.88       340     0.8423     0.8571    +0.0149
Elongated                                 0.62       168     0.7761     0.7840    +0.0078
Eventive                                  0.28      1068     0.8853     0.8896    +0.0043
Feminine                                  0.75       204     0.9356     0.9415    +0.0059
Fluid                                     0.12        19     0.8889     0.9500    +0.0611
Garment                                   0.50        17     0.9714     0.9714    +0.0000
Inanimate                                 0.59      1511     0.9395     0.9407    +0.0012
Internal_Control                          0.06        21     0.3846     0.5641    +0.1795
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.44      1209     0.9172     0.9213    +0.0040
Machine                                   0.38       180     0.8991     0.9054    +0.0063
Masculine                                 0.23       671     0.9256     0.9350    +0.0094
Natural                                   0.27        79     0.8535     0.8675    +0.0140
Natural_Force                             0.50        35     0.8571     0.8571    +0.0000
Non_Rigid                                 0.38       335     0.8018     0.8063    +0.0045
Organisation                              0.49      1086     0.8925     0.8935    +0.0010
Plant                                     0.50        15     0.9333     0.9333    +0.0000
Point_in_Time                             0.21       336     0.8658     0.8816    +0.0158
Pointy                                    0.63        20     0.7805     0.7895    +0.0090
Question                                  0.11        33     0.8136     0.8358    +0.0223
Rigid                                     0.38       603     0.8785     0.8826    +0.0042
Solid                                     0.50      1409     0.8914     0.8914    +0.0000
Sound                                     0.27        42     0.7952     0.8182    +0.0230
Statement                                 0.47       264     0.7710     0.7759    +0.0049
Substance                                 0.35       217     0.8953     0.9004    +0.0051
Time                                      0.23        16     0.2727     0.5143    +0.2416
Unspecified_Gender_or_Neuter              0.21       677     0.8839     0.8881    +0.0042
Vehicle                                   0.15       100     0.9442     0.9548    +0.0106
Web_Location                              0.77        55     0.8727     0.9143    +0.0416

VALIDATION @ 0.5
direct_f1_macro: 0.8534062703345612
direct_f1_micro: 0.890433120082359
direct_precision_macro: 0.8819571332284942
direct_precision_micro: 0.8937850605255389
direct_recall_macro: 0.8426120455053175
direct_recall_micro: 0.8871062271062271
f1_macro: 0.9041737221870272
f1_micro: 0.9353400402414487
precision_macro: 0.911110631481785
precision_micro: 0.9417522932806068
recall_macro: 0.8983560517372422
recall_micro: 0.9290145168510584

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.874307664454698
direct_f1_micro: 0.8947888096544158
direct_precision_macro: 0.8727875681868799
direct_precision_micro: 0.8933187294633078
direct_recall_macro: 0.8780569011462854
direct_recall_micro: 0.8962637362637362
f1_macro: 0.9124951304723293
f1_micro: 0.9387343877436791
precision_macro: 0.9102706640353448
precision_micro: 0.9389896663147455
recall_macro: 0.9160178733775012
recall_micro: 0.938479247937584

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7788600142371573
direct_f1_micro: 0.8629910485204402
direct_precision_macro: 0.8247955212129315
direct_precision_micro: 0.8684874913931604
direct_recall_macro: 0.7627354082779271
direct_recall_micro: 0.8575637393767706
f1_macro: 0.8576499801904722
f1_micro: 0.9156478918097851
precision_macro: 0.8770320852019517
precision_micro: 0.9228603881673169
recall_macro: 0.8435854219906285
recall_micro: 0.9085472578763127

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7773784031559349
direct_f1_micro: 0.8605573176257363
direct_precision_macro: 0.787525341156331
direct_precision_micro: 0.8602649756539463
direct_recall_macro: 0.7764124970961439
direct_recall_micro: 0.8608498583569405
f1_macro: 0.853347405246617
f1_micro: 0.9161644634525661
precision_macro: 0.865653376893161
precision_micro: 0.9158083948698018
recall_macro: 0.849016222672881
recall_micro: 0.9165208090237261

====================================================================================================
RUN 23/30 | SEED 641
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1028.41it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.72      1405     0.8976     0.9033    +0.0056
Animal                                    0.86       184     0.9431     0.9500    +0.0069
Animate                                   0.42        13     0.8182     0.8696    +0.0514
Artefact                                  0.53       503     0.8864     0.8909    +0.0045
Body_Part                                 0.59        74     0.8889     0.9078    +0.0189
Comestible                                0.46       157     0.9646     0.9679    +0.0033
Communication                             0.25       534     0.8019     0.8060    +0.0042
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.48       340     0.8613     0.8630    +0.0017
Elongated                                 0.57       168     0.7937     0.8000    +0.0063
Eventive                                  0.42      1068     0.8912     0.8945    +0.0033
Feminine                                  0.72       204     0.9383     0.9500    +0.0117
Fluid                                     0.50        19     0.8889     0.8889    +0.0000
Garment                                   0.41        17     0.9375     0.9697    +0.0322
Inanimate                                 0.21      1511     0.9316     0.9327    +0.0011
Internal_Control                          0.33        21     0.4444     0.5806    +0.1362
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.57      1209     0.9215     0.9238    +0.0023
Machine                                   0.36       180     0.8711     0.8876    +0.0166
Masculine                                 0.42       671     0.9392     0.9409    +0.0017
Natural                                   0.62        79     0.8718     0.8831    +0.0113
Natural_Force                             0.50        35     0.8824     0.8824    +0.0000
Non_Rigid                                 0.42       335     0.8065     0.8134    +0.0069
Organisation                              0.47      1086     0.8945     0.8987    +0.0042
Plant                                     0.53        15     0.8667     0.8966    +0.0299
Point_in_Time                             0.12       336     0.8713     0.8727    +0.0015
Pointy                                    0.45        20     0.7568     0.7895    +0.0327
Question                                  0.45        33     0.8571     0.8750    +0.0179
Rigid                                     0.23       603     0.8749     0.8862    +0.0113
Solid                                     0.61      1409     0.8892     0.8914    +0.0022
Sound                                     0.83        42     0.8101     0.8493    +0.0392
Statement                                 0.36       264     0.7524     0.7704    +0.0179
Substance                                 0.31       217     0.8838     0.8909    +0.0070
Time                                      0.19        16     0.5217     0.5556    +0.0338
Unspecified_Gender_or_Neuter              0.61       677     0.8853     0.8889    +0.0036
Vehicle                                   0.50       100     0.9697     0.9697    +0.0000
Web_Location                              0.93        55     0.8909     0.9057    +0.0148

VALIDATION @ 0.5
direct_f1_macro: 0.8622890074948618
direct_f1_micro: 0.8911124190700412
direct_precision_macro: 0.904340404297854
direct_precision_micro: 0.8949312841731935
direct_recall_macro: 0.8388579436396674
direct_recall_micro: 0.8873260073260073
f1_macro: 0.9058408815908608
f1_micro: 0.9384825810604231
precision_macro: 0.9199662610658842
precision_micro: 0.9446082083508794
recall_macro: 0.8929366785409585
recall_micro: 0.9324358892370659

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8769341082974407
direct_f1_micro: 0.8953216374269006
direct_precision_macro: 0.8995391567398601
direct_precision_micro: 0.8933625091174325
direct_recall_macro: 0.8624703947344868
direct_recall_micro: 0.8972893772893773
f1_macro: 0.9133941313402246
f1_micro: 0.9404542467422141
precision_macro: 0.9257814888540861
precision_micro: 0.9428571428571428
recall_macro: 0.9031973285313947
recall_micro: 0.9380635671804054

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.784312336363433
direct_f1_micro: 0.8608344242700211
direct_precision_macro: 0.8121617065049348
direct_precision_micro: 0.8648215919487648
direct_recall_macro: 0.7716503111638684
direct_recall_micro: 0.8568838526912181
f1_macro: 0.8593612119744529
f1_micro: 0.9174163895951496
precision_macro: 0.8760222621545012
precision_micro: 0.9226494885916601
recall_macro: 0.8475255515088832
recall_micro: 0.9122423181641385

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.781377961837614
direct_f1_micro: 0.8588707398406149
direct_precision_macro: 0.800382670563285
direct_precision_micro: 0.8567884528642309
direct_recall_macro: 0.7753664631034543
direct_recall_micro: 0.8609631728045326
f1_macro: 0.8597135769706927
f1_micro: 0.9159766195811009
precision_macro: 0.8773263686235058
precision_micro: 0.9176751903181729
recall_macro: 0.8497405262978731
recall_micro: 0.9142843251653053

====================================================================================================
RUN 24/30 | SEED 691
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 947.05it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.61      1405     0.8967     0.9004    +0.0037
Animal                                    0.53       184     0.9418     0.9444    +0.0026
Animate                                   0.45        13     0.8182     0.8696    +0.0514
Artefact                                  0.39       503     0.9027     0.9057    +0.0030
Body_Part                                 0.31        74     0.9200     0.9211    +0.0011
Comestible                                0.45       157     0.9527     0.9560    +0.0033
Communication                             0.44       534     0.8140     0.8201    +0.0062
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.26       340     0.8498     0.8560    +0.0062
Elongated                                 0.52       168     0.7660     0.7754    +0.0094
Eventive                                  0.42      1068     0.8843     0.8854    +0.0011
Feminine                                  0.72       204     0.9415     0.9481    +0.0067
Fluid                                     0.63        19     0.9231     0.9474    +0.0243
Garment                                   0.30        17     0.9375     0.9714    +0.0339
Inanimate                                 0.50      1511     0.9382     0.9382    +0.0000
Internal_Control                          0.17        21     0.3846     0.5714    +0.1868
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.62      1209     0.9253     0.9272    +0.0019
Machine                                   0.39       180     0.8934     0.9045    +0.0111
Masculine                                 0.27       671     0.9345     0.9349    +0.0004
Natural                                   0.50        79     0.9045     0.9045    +0.0000
Natural_Force                             0.64        35     0.8732     0.8986    +0.0253
Non_Rigid                                 0.70       335     0.7994     0.8067    +0.0073
Organisation                              0.42      1086     0.8950     0.8971    +0.0021
Plant                                     0.46        15     0.8966     0.9333    +0.0368
Point_in_Time                             0.80       336     0.8537     0.8639    +0.0102
Pointy                                    0.49        20     0.7368     0.8000    +0.0632
Question                                  0.07        33     0.8571     0.8657    +0.0085
Rigid                                     0.21       603     0.8711     0.8867    +0.0157
Solid                                     0.65      1409     0.8930     0.8944    +0.0014
Sound                                     0.78        42     0.8000     0.8312    +0.0312
Statement                                 0.51       264     0.7742     0.7778    +0.0036
Substance                                 0.38       217     0.8787     0.8869    +0.0082
Time                                      0.20        16     0.4000     0.5806    +0.1806
Unspecified_Gender_or_Neuter              0.20       677     0.8948     0.8992    +0.0044
Vehicle                                   0.50       100     0.9700     0.9700    +0.0000
Web_Location                              0.90        55     0.8727     0.9020    +0.0292

VALIDATION @ 0.5
direct_f1_macro: 0.8593252559521124
direct_f1_micro: 0.8924411127034872
direct_precision_macro: 0.9024547078712131
direct_precision_micro: 0.895303398953034
direct_recall_macro: 0.8433213792608456
direct_recall_micro: 0.8895970695970696
f1_macro: 0.905869196514663
f1_micro: 0.9384375452192228
precision_macro: 0.9123107600782228
precision_micro: 0.9437635417003525
recall_macro: 0.9001634982257756
recall_micro: 0.9331713244228432

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.880424983589948
direct_f1_micro: 0.8965972910472415
direct_precision_macro: 0.8925825681047981
direct_precision_micro: 0.8984771573604061
direct_recall_macro: 0.8718125857460945
direct_recall_micro: 0.8947252747252747
f1_macro: 0.91569556344473
f1_micro: 0.942051043786148
precision_macro: 0.9199331534285244
precision_micro: 0.9440323668240054
recall_macro: 0.9128009794826659
recall_micro: 0.9400780200805782

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7824681573884664
direct_f1_micro: 0.8630464480874317
direct_precision_macro: 0.8168159958584498
direct_precision_micro: 0.8670936749399519
direct_recall_macro: 0.7685895532904573
direct_recall_micro: 0.8590368271954674
f1_macro: 0.8566393167247163
f1_micro: 0.9169370380308833
precision_macro: 0.8697904810300583
precision_micro: 0.9201468788249694
recall_macro: 0.8477562462408239
recall_micro: 0.9137495138078569

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7798360148687091
direct_f1_micro: 0.8620493574434209
direct_precision_macro: 0.8048287480711597
direct_precision_micro: 0.8651980367537953
direct_recall_macro: 0.7688537378378727
direct_recall_micro: 0.8589235127478754
f1_macro: 0.8526802370958276
f1_micro: 0.9162671857890254
precision_macro: 0.8703530268325641
precision_micro: 0.9171822477712281
recall_macro: 0.8421731088565437
recall_micro: 0.9153539478802023

====================================================================================================
RUN 25/30 | SEED 743
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1030.71it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.66      1405     0.8972     0.9026    +0.0055
Animal                                    0.32       184     0.9500     0.9560    +0.0060
Animate                                   0.27        13     0.8696     0.9167    +0.0471
Artefact                                  0.69       503     0.9074     0.9119    +0.0044
Body_Part                                 0.75        74     0.8936     0.9065    +0.0129
Comestible                                0.61       157     0.9521     0.9551    +0.0031
Communication                             0.39       534     0.8015     0.8122    +0.0106
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.54       340     0.8546     0.8584    +0.0038
Elongated                                 0.56       168     0.7697     0.7826    +0.0129
Eventive                                  0.28      1068     0.8808     0.8817    +0.0009
Feminine                                  0.92       204     0.9386     0.9500    +0.0114
Fluid                                     0.50        19     0.8889     0.8889    +0.0000
Garment                                   0.22        17     0.9412     0.9714    +0.0303
Inanimate                                 0.68      1511     0.9383     0.9396    +0.0013
Internal_Control                          0.15        21     0.4444     0.5294    +0.0850
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.48      1209     0.9231     0.9240    +0.0010
Machine                                   0.60       180     0.8870     0.8971    +0.0101
Masculine                                 0.18       671     0.9336     0.9373    +0.0036
Natural                                   0.63        79     0.8805     0.8961    +0.0156
Natural_Force                             0.50        35     0.8657     0.8657    +0.0000
Non_Rigid                                 0.42       335     0.7982     0.8000    +0.0018
Organisation                              0.36      1086     0.8955     0.8982    +0.0027
Plant                                     0.50        15     0.8966     0.8966    +0.0000
Point_in_Time                             0.55       336     0.8707     0.8729    +0.0022
Pointy                                    0.50        20     0.8000     0.8000    +0.0000
Question                                  0.44        33     0.8197     0.8571    +0.0375
Rigid                                     0.29       603     0.8855     0.8909    +0.0054
Solid                                     0.51      1409     0.8958     0.8971    +0.0013
Sound                                     0.59        42     0.8471     0.8642    +0.0171
Statement                                 0.38       264     0.7553     0.7672    +0.0119
Substance                                 0.39       217     0.8741     0.8879    +0.0138
Time                                      0.12        16     0.3810     0.5500    +0.1690
Unspecified_Gender_or_Neuter              0.33       677     0.8900     0.8920    +0.0019
Vehicle                                   0.24       100     0.9694     0.9798    +0.0104
Web_Location                              0.95        55     0.8750     0.9159    +0.0409

VALIDATION @ 0.5
direct_f1_macro: 0.8613945302948927
direct_f1_micro: 0.8923959827833573
direct_precision_macro: 0.9002308208003273
direct_precision_micro: 0.8962536023054755
direct_recall_macro: 0.8427733190642493
direct_recall_micro: 0.8885714285714286
f1_macro: 0.9057390581571462
f1_micro: 0.9373731516381559
precision_macro: 0.9165442424771507
precision_micro: 0.944462477278629
recall_macro: 0.8958289194600118
recall_micro: 0.9303894608940334

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8771071705111092
direct_f1_micro: 0.8961532836039199
direct_precision_macro: 0.889458764613134
direct_precision_micro: 0.894583150824938
direct_recall_macro: 0.8691951654800305
direct_recall_micro: 0.8977289377289377
f1_macro: 0.9129529491728595
f1_micro: 0.9412141290952449
precision_macro: 0.9205756203102982
precision_micro: 0.9422245009132566
recall_macro: 0.9063796195550388
recall_micro: 0.9402059218520177

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7939449684292851
direct_f1_micro: 0.8677784734475497
direct_precision_macro: 0.829437290630197
direct_precision_micro: 0.8717978042086002
direct_recall_macro: 0.7790127267062558
direct_recall_micro: 0.8637960339943342
f1_macro: 0.866509774726644
f1_micro: 0.9209831899921814
precision_macro: 0.8825168155278375
precision_micro: 0.9256876227897839
recall_macro: 0.8553316078233965
recall_micro: 0.9163263321664722

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7902564793111804
direct_f1_micro: 0.8640425291256645
direct_precision_macro: 0.8112023886932819
direct_precision_micro: 0.862481652929886
direct_recall_macro: 0.7851250109888984
direct_recall_micro: 0.8656090651558074
f1_macro: 0.8637719092852845
f1_micro: 0.9199222546161322
precision_macro: 0.8791156190533065
precision_micro: 0.9193861693861693
recall_macro: 0.8552187747347236
recall_micro: 0.9204589653831194

====================================================================================================
RUN 26/30 | SEED 797
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 950.75it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.58      1405     0.9013     0.9025    +0.0012
Animal                                    0.86       184     0.9392     0.9441    +0.0049
Animate                                   0.49        13     0.8182     0.8696    +0.0514
Artefact                                  0.54       503     0.9014     0.9028    +0.0014
Body_Part                                 0.35        74     0.9155     0.9241    +0.0086
Comestible                                0.32       157     0.9521     0.9524    +0.0003
Communication                             0.40       534     0.8138     0.8154    +0.0016
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.18       340     0.8509     0.8604    +0.0095
Elongated                                 0.61       168     0.7850     0.8051    +0.0201
Eventive                                  0.59      1068     0.8795     0.8849    +0.0054
Feminine                                  0.84       204     0.9403     0.9442    +0.0039
Fluid                                     0.50        19     0.8947     0.8947    +0.0000
Garment                                   0.24        17     0.9412     0.9714    +0.0303
Inanimate                                 0.34      1511     0.9351     0.9363    +0.0012
Internal_Control                          0.15        21     0.4444     0.5789    +0.1345
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.71      1209     0.9226     0.9260    +0.0035
Machine                                   0.44       180     0.8902     0.8971    +0.0070
Masculine                                 0.23       671     0.9308     0.9382    +0.0074
Natural                                   0.70        79     0.8718     0.8816    +0.0098
Natural_Force                             0.33        35     0.8116     0.8493    +0.0377
Non_Rigid                                 0.61       335     0.7982     0.8006    +0.0024
Organisation                              0.30      1086     0.8925     0.8963    +0.0037
Plant                                     0.50        15     0.8966     0.8966    +0.0000
Point_in_Time                             0.58       336     0.8737     0.8786    +0.0049
Pointy                                    0.50        20     0.7692     0.7692    +0.0000
Question                                  0.13        33     0.8387     0.8696    +0.0309
Rigid                                     0.50       603     0.8787     0.8787    +0.0000
Solid                                     0.49      1409     0.8876     0.8881    +0.0005
Sound                                     0.40        42     0.7750     0.8140    +0.0390
Statement                                 0.69       264     0.7557     0.7692    +0.0135
Substance                                 0.49       217     0.8832     0.8884    +0.0052
Time                                      0.10        16     0.2857     0.5500    +0.2643
Unspecified_Gender_or_Neuter              0.44       677     0.8878     0.8928    +0.0050
Vehicle                                   0.50       100     0.9645     0.9645    +0.0000
Web_Location                              0.76        55     0.8649     0.9057    +0.0408

VALIDATION @ 0.5
direct_f1_macro: 0.8538285318612825
direct_f1_micro: 0.890810094915753
direct_precision_macro: 0.8923877983418578
direct_precision_micro: 0.8946940585279338
direct_recall_macro: 0.8341561843422637
direct_recall_micro: 0.8869597069597069
f1_macro: 0.9022364627355974
f1_micro: 0.9364333097185548
precision_macro: 0.9133401178337661
precision_micro: 0.9431147434650061
recall_macro: 0.8919102536220833
recall_micro: 0.9298458783654153

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8740875265461486
direct_f1_micro: 0.8948199273101068
direct_precision_macro: 0.8836988883275065
direct_precision_micro: 0.89682831702112
direct_recall_macro: 0.868152115235078
direct_recall_micro: 0.8928205128205128
f1_macro: 0.9099535229671277
f1_micro: 0.9390631521494847
precision_macro: 0.9165591734488626
precision_micro: 0.9429078014184397
recall_macro: 0.904512134893445
recall_micro: 0.9352497282087356

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7800022516135824
direct_f1_micro: 0.861702731868007
direct_precision_macro: 0.8094555955654383
direct_precision_micro: 0.8638123434297427
direct_recall_macro: 0.7681919396364161
direct_recall_micro: 0.8596033994334278
f1_macro: 0.8528865804461864
f1_micro: 0.9167318599647957
precision_macro: 0.8689445766266848
precision_micro: 0.9219610542879623
recall_macro: 0.8438783626603266
recall_micro: 0.9115616491637495

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7760278159366365
direct_f1_micro: 0.8606705935659266
direct_precision_macro: 0.790858574916643
direct_precision_micro: 0.8603782131128977
direct_recall_macro: 0.7742134962496593
direct_recall_micro: 0.8609631728045326
f1_macro: 0.8504553297111667
f1_micro: 0.9151253746618905
precision_macro: 0.8679950373908963
precision_micro: 0.9173384141873077
recall_macro: 0.8420491954824999
recall_micro: 0.9129229871645275

====================================================================================================
RUN 27/30 | SEED 853
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1035.72it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.43      1405     0.8974     0.8994    +0.0020
Animal                                    0.85       184     0.9396     0.9497    +0.0102
Animate                                   0.14        13     0.8182     0.9167    +0.0985
Artefact                                  0.67       503     0.9024     0.9069    +0.0045
Body_Part                                 0.11        74     0.9252     0.9290    +0.0039
Comestible                                0.36       157     0.9450     0.9554    +0.0104
Communication                             0.63       534     0.7981     0.8071    +0.0090
Currency                                  0.58        45     0.9890     1.0000    +0.0110
Duration                                  0.60       340     0.8471     0.8499    +0.0029
Elongated                                 0.52       168     0.7850     0.7900    +0.0049
Eventive                                  0.55      1068     0.8820     0.8847    +0.0028
Feminine                                  0.72       204     0.9272     0.9409    +0.0137
Fluid                                     0.22        19     0.8947     0.9231    +0.0283
Garment                                   0.09        17     0.9375     0.9444    +0.0069
Inanimate                                 0.78      1511     0.9337     0.9360    +0.0023
Internal_Control                          0.12        21     0.5333     0.5946    +0.0613
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.74      1209     0.9170     0.9190    +0.0020
Machine                                   0.29       180     0.8761     0.8845    +0.0084
Masculine                                 0.54       671     0.9356     0.9377    +0.0021
Natural                                   0.81        79     0.8645     0.8725    +0.0080
Natural_Force                             0.63        35     0.8451     0.8529    +0.0079
Non_Rigid                                 0.53       335     0.8065     0.8100    +0.0036
Organisation                              0.60      1086     0.8907     0.8946    +0.0039
Plant                                     0.50        15     0.9333     0.9333    +0.0000
Point_in_Time                             0.28       336     0.8744     0.8772    +0.0028
Pointy                                    0.70        20     0.7805     0.7895    +0.0090
Question                                  0.49        33     0.8387     0.8571    +0.0184
Rigid                                     0.21       603     0.8690     0.8806    +0.0115
Solid                                     0.38      1409     0.8853     0.8875    +0.0022
Sound                                     0.72        42     0.7857     0.8108    +0.0251
Statement                                 0.69       264     0.7519     0.7642    +0.0123
Substance                                 0.27       217     0.8684     0.8795    +0.0111
Time                                      0.10        16     0.3636     0.5238    +0.1602
Unspecified_Gender_or_Neuter              0.32       677     0.8854     0.8914    +0.0060
Vehicle                                   0.84       100     0.9447     0.9641    +0.0194
Web_Location                              0.84        55     0.8807     0.8952    +0.0145

VALIDATION @ 0.5
direct_f1_macro: 0.8581774898292123
direct_f1_micro: 0.8881871259134139
direct_precision_macro: 0.8874780374927834
direct_precision_micro: 0.8903776779798277
direct_recall_macro: 0.8417321202596628
direct_recall_micro: 0.886007326007326
f1_macro: 0.9026647994106431
f1_micro: 0.9356916799203174
precision_macro: 0.9103589984575814
precision_micro: 0.9402382720433926
recall_macro: 0.8956745643174188
recall_micro: 0.9311888469655305

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8744146650952022
direct_f1_micro: 0.8927928259031938
direct_precision_macro: 0.8869544133343178
direct_precision_micro: 0.8957887749834058
direct_recall_macro: 0.8669992897531362
direct_recall_micro: 0.8898168498168498
f1_macro: 0.9097225800755411
f1_micro: 0.938881121128843
precision_macro: 0.9196970443206774
precision_micro: 0.9438107854857992
recall_macro: 0.9019717019105704
recall_micro: 0.9340026859372003

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7725718016324382
direct_f1_micro: 0.8613545816733068
direct_precision_macro: 0.8231002560333762
direct_precision_micro: 0.8652944539736993
direct_recall_macro: 0.7486501399099789
direct_recall_micro: 0.8574504249291784
f1_macro: 0.845642702513259
f1_micro: 0.9133095109892799
precision_macro: 0.8751137222553529
precision_micro: 0.9195662888122228
recall_macro: 0.8254728858359681
recall_micro: 0.9071373006612213

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7706385274590613
direct_f1_micro: 0.8585610771951846
direct_precision_macro: 0.8016284825906826
direct_precision_micro: 0.8646288209606987
direct_recall_macro: 0.7580118355858059
direct_recall_micro: 0.8525779036827196
f1_macro: 0.8444912644947795
f1_micro: 0.9129816648691048
precision_macro: 0.8778965085587956
precision_micro: 0.9206545382637927
recall_macro: 0.8231269580929864
recall_micro: 0.9054356281602489

====================================================================================================
RUN 28/30 | SEED 911
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 940.76it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.69      1405     0.8970     0.8996    +0.0026
Animal                                    0.48       184     0.9441     0.9471    +0.0029
Animate                                   0.10        13     0.8182     0.8800    +0.0618
Artefact                                  0.55       503     0.9091     0.9113    +0.0022
Body_Part                                 0.50        74     0.9315     0.9315    +0.0000
Comestible                                0.51       157     0.9524     0.9554    +0.0030
Communication                             0.50       534     0.8170     0.8170    +0.0000
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.88       340     0.8480     0.8517    +0.0038
Elongated                                 0.61       168     0.7890     0.7962    +0.0072
Eventive                                  0.78      1068     0.8766     0.8820    +0.0053
Feminine                                  0.65       204     0.9409     0.9502    +0.0094
Fluid                                     0.56        19     0.8649     0.8889    +0.0240
Garment                                   0.38        17     0.9032     0.9697    +0.0665
Inanimate                                 0.58      1511     0.9376     0.9386    +0.0010
Internal_Control                          0.12        21     0.3077     0.5714    +0.2637
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.54      1209     0.9242     0.9243    +0.0001
Machine                                   0.70       180     0.9060     0.9133    +0.0073
Masculine                                 0.49       671     0.9425     0.9433    +0.0008
Natural                                   0.65        79     0.8718     0.8816    +0.0098
Natural_Force                             0.52        35     0.8286     0.8529    +0.0244
Non_Rigid                                 0.45       335     0.7971     0.8011    +0.0040
Organisation                              0.44      1086     0.8937     0.8947    +0.0010
Plant                                     0.08        15     0.8571     0.9091    +0.0519
Point_in_Time                             0.59       336     0.8722     0.8767    +0.0044
Pointy                                    0.36        20     0.6667     0.8293    +0.1626
Question                                  0.06        33     0.8387     0.8657    +0.0270
Rigid                                     0.31       603     0.8788     0.8832    +0.0044
Solid                                     0.51      1409     0.8967     0.8972    +0.0006
Sound                                     0.52        42     0.7179     0.7368    +0.0189
Statement                                 0.69       264     0.7603     0.7750    +0.0147
Substance                                 0.41       217     0.8874     0.8919    +0.0045
Time                                      0.09        16     0.2105     0.5500    +0.3395
Unspecified_Gender_or_Neuter              0.37       677     0.8931     0.8971    +0.0040
Vehicle                                   0.90       100     0.9600     0.9694    +0.0094
Web_Location                              0.74        55     0.8850     0.9074    +0.0225

VALIDATION @ 0.5
direct_f1_macro: 0.8439317697268968
direct_f1_micro: 0.8926698690917091
direct_precision_macro: 0.8860288253720925
direct_precision_micro: 0.8936201453637765
direct_recall_macro: 0.8253673167033082
direct_recall_micro: 0.8917216117216117
f1_macro: 0.8981940689896479
f1_micro: 0.9382407184668431
precision_macro: 0.90989705168874
precision_micro: 0.9411537595315466
recall_macro: 0.8882563309031227
recall_micro: 0.9353456545373153

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8754249869687124
direct_f1_micro: 0.8962670892139882
direct_precision_macro: 0.8876589136262641
direct_precision_micro: 0.9016831022466079
direct_recall_macro: 0.8677564617050604
direct_recall_micro: 0.8909157509157509
f1_macro: 0.9104415605239539
f1_micro: 0.939147224456959
precision_macro: 0.9202883805292479
precision_micro: 0.9452001554605519
recall_macro: 0.9024404867661266
recall_micro: 0.9331713244228432

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7777721270834714
direct_f1_micro: 0.8620787634255839
direct_precision_macro: 0.8149717809727806
direct_precision_micro: 0.8646830825353398
direct_recall_macro: 0.7602765222332247
direct_recall_micro: 0.8594900849858357
f1_macro: 0.8537668029549278
f1_micro: 0.9166504096761607
precision_macro: 0.871837928681095
precision_micro: 0.9195205479452054
recall_macro: 0.8414170597341866
recall_micro: 0.9137981330221704

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7786170038100412
direct_f1_micro: 0.8610239141601507
direct_precision_macro: 0.7926056741966923
direct_precision_micro: 0.8674103035878565
direct_recall_macro: 0.7747817203802674
direct_recall_micro: 0.8547308781869688
f1_macro: 0.8500130765060985
f1_micro: 0.9158005429067521
precision_macro: 0.8641541498927731
precision_micro: 0.9213206711607538
recall_macro: 0.8424796214293409
recall_micro: 0.9103461688059121

====================================================================================================
RUN 29/30 | SEED 971
====================================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1004.05it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.64      1405     0.8961     0.8983    +0.0022
Animal                                    0.85       184     0.9415     0.9462    +0.0047
Animate                                   0.50        13     0.8696     0.8696    +0.0000
Artefact                                  0.35       503     0.8986     0.9089    +0.0103
Body_Part                                 0.36        74     0.9231     0.9315    +0.0084
Comestible                                0.52       157     0.9590     0.9682    +0.0092
Communication                             0.37       534     0.8088     0.8141    +0.0053
Currency                                  0.50        45     1.0000     1.0000    +0.0000
Duration                                  0.56       340     0.8479     0.8503    +0.0024
Elongated                                 0.46       168     0.8000     0.8085    +0.0085
Eventive                                  0.51      1068     0.8936     0.8948    +0.0011
Feminine                                  0.85       204     0.9386     0.9455    +0.0070
Fluid                                     0.36        19     0.8500     0.8780    +0.0280
Garment                                   0.33        17     0.9091     0.9714    +0.0623
Inanimate                                 0.49      1511     0.9393     0.9400    +0.0007
Internal_Control                          0.13        21     0.4286     0.5641    +0.1355
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.67      1209     0.9203     0.9218    +0.0016
Machine                                   0.47       180     0.9003     0.9070    +0.0068
Masculine                                 0.50       671     0.9310     0.9310    +0.0000
Natural                                   0.50        79     0.8903     0.8903    +0.0000
Natural_Force                             0.67        35     0.8116     0.8438    +0.0322
Non_Rigid                                 0.56       335     0.7970     0.8000    +0.0030
Organisation                              0.52      1086     0.8976     0.8978    +0.0002
Plant                                     0.50        15     0.9333     0.9333    +0.0000
Point_in_Time                             0.86       336     0.8648     0.8771    +0.0124
Pointy                                    0.54        20     0.7619     0.7805    +0.0186
Question                                  0.07        33     0.7931     0.8571    +0.0640
Rigid                                     0.27       603     0.8800     0.8873    +0.0073
Solid                                     0.56      1409     0.8930     0.8943    +0.0012
Sound                                     0.54        42     0.8193     0.8250    +0.0057
Statement                                 0.51       264     0.7569     0.7583    +0.0015
Substance                                 0.38       217     0.8884     0.8978    +0.0094
Time                                      0.22        16     0.4167     0.5294    +0.1127
Unspecified_Gender_or_Neuter              0.68       677     0.8843     0.8871    +0.0027
Vehicle                                   0.40       100     0.9694     0.9746    +0.0052
Web_Location                              0.91        55     0.8545     0.8932    +0.0387

VALIDATION @ 0.5
direct_f1_macro: 0.8585757303260123
direct_f1_micro: 0.8925474055563722
direct_precision_macro: 0.8872562410516327
direct_precision_micro: 0.8954431499778793
direct_recall_macro: 0.8427062843842011
direct_recall_micro: 0.8896703296703297
f1_macro: 0.9024604896884304
f1_micro: 0.9386193369988103
precision_macro: 0.9114242719949263
precision_micro: 0.9438696326952923
recall_macro: 0.894917860783144
recall_micro: 0.9334271279657224

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8750331712794667
direct_f1_micro: 0.8959092750101255
direct_precision_macro: 0.8882144552143988
direct_precision_micro: 0.9005847953216374
direct_recall_macro: 0.8645934764282588
direct_recall_micro: 0.8912820512820513
f1_macro: 0.9110032303605149
f1_micro: 0.938763664506143
precision_macro: 0.9222811898177389
precision_micro: 0.9467932873682842
recall_macro: 0.9013504447171274
recall_micro: 0.9308690925369316

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7755572812348935
direct_f1_micro: 0.8620650443484194
direct_precision_macro: 0.8061542609647487
direct_precision_micro: 0.8651146867511126
direct_recall_macro: 0.7700790773620725
direct_recall_micro: 0.8590368271954674
f1_macro: 0.8525567308304566
f1_micro: 0.9164325671153235
precision_macro: 0.8632584311235468
precision_micro: 0.9209092248023958
recall_macro: 0.8480894494879525
recall_micro: 0.911999222092571

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7781089163668287
direct_f1_micro: 0.8624743209312943
direct_precision_macro: 0.7900550350676052
direct_precision_micro: 0.8687205425911024
direct_recall_macro: 0.777416608369548
direct_recall_micro: 0.8563172804532578
f1_macro: 0.8513057146023986
f1_micro: 0.9133169533169533
precision_macro: 0.867728460873218
precision_micro: 0.9232068348897278
recall_macro: 0.8431495573284743
recall_micro: 0.9036367172306495

====================================================================================================
RUN 30/30 | SEED 1031
====================================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 952.43it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.weight      | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

====================================================================================================
VALIDATION-OPTIMISED THRESHOLDS
====================================================================================================
Feature                              Threshold   Support     F1@0.5     F1 opt     Change
-----------------------------------------------------------------------------------------
Abstract                                  0.73      1405     0.8961     0.8984    +0.0023
Animal                                    0.43       184     0.9503     0.9532    +0.0029
Animate                                   0.50        13     0.9167     0.9167    +0.0000
Artefact                                  0.50       503     0.9049     0.9049    +0.0000
Body_Part                                 0.27        74     0.9103     0.9189    +0.0086
Comestible                                0.35       157     0.9484     0.9590    +0.0106
Communication                             0.37       534     0.8019     0.8095    +0.0076
Currency                                  0.66        45     0.9890     1.0000    +0.0110
Duration                                  0.90       340     0.8375     0.8504    +0.0129
Elongated                                 0.51       168     0.7853     0.7901    +0.0048
Eventive                                  0.46      1068     0.8857     0.8880    +0.0023
Feminine                                  0.70       204     0.9320     0.9363    +0.0042
Fluid                                     0.50        19     0.8947     0.8947    +0.0000
Garment                                   0.08        17     0.9091     0.9444    +0.0354
Inanimate                                 0.53      1511     0.9363     0.9366    +0.0003
Internal_Control                          0.14        21     0.3846     0.5946    +0.2100
Language                                  0.50         5     1.0000     1.0000    +0.0000
Location                                  0.67      1209     0.9236     0.9265    +0.0028
Machine                                   0.57       180     0.8782     0.8832    +0.0050
Masculine                                 0.34       671     0.9312     0.9374    +0.0062
Natural                                   0.34        79     0.8625     0.8780    +0.0155
Natural_Force                             0.50        35     0.8571     0.8571    +0.0000
Non_Rigid                                 0.35       335     0.7864     0.7994    +0.0131
Organisation                              0.56      1086     0.8931     0.8950    +0.0019
Plant                                     0.23        15     0.8571     0.9032    +0.0461
Point_in_Time                             0.77       336     0.8563     0.8669    +0.0106
Pointy                                    0.57        20     0.7000     0.7568    +0.0568
Question                                  0.52        33     0.8571     0.8710    +0.0138
Rigid                                     0.53       603     0.8746     0.8781    +0.0035
Solid                                     0.46      1409     0.8919     0.8933    +0.0015
Sound                                     0.20        42     0.7470     0.7957    +0.0487
Statement                                 0.50       264     0.7689     0.7689    +0.0000
Substance                                 0.51       217     0.9029     0.9050    +0.0020
Time                                      0.14        16     0.3636     0.5238    +0.1602
Unspecified_Gender_or_Neuter              0.31       677     0.8899     0.8952    +0.0053
Vehicle                                   0.66       100     0.9648     0.9746    +0.0098
Web_Location                              0.94        55     0.8571     0.8952    +0.0381

VALIDATION @ 0.5
direct_f1_macro: 0.8526008368548377
direct_f1_micro: 0.8901942068357869
direct_precision_macro: 0.8856245082097839
direct_precision_micro: 0.8921922142909706
direct_recall_macro: 0.8383385155376939
direct_recall_micro: 0.8882051282051282
f1_macro: 0.8987758024317896
f1_micro: 0.9363810381713771
precision_macro: 0.9069283224772857
precision_micro: 0.9421551807852911
recall_macro: 0.8912485071477292
recall_micro: 0.9306772398797724

VALIDATION WITH VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.8729729140888665
direct_f1_micro: 0.894092563320222
direct_precision_macro: 0.8793012392067675
direct_precision_micro: 0.8972921124474286
direct_recall_macro: 0.87117547287713
direct_recall_micro: 0.8909157509157509
f1_macro: 0.9075782199349904
f1_micro: 0.9376610824742269
precision_macro: 0.9152816027051329
precision_micro: 0.9447834837369343
recall_macro: 0.9016841328621538
recall_micro: 0.9306452644369124

TEST @ 0.5 (DIAGNOSTIC)
direct_f1_macro: 0.7737578458884958
direct_f1_micro: 0.8660121446001929
direct_precision_macro: 0.8179179291778617
direct_precision_micro: 0.8674397453387903
direct_recall_macro: 0.759511119834006
direct_recall_micro: 0.8645892351274788
f1_macro: 0.8568531117045212
f1_micro: 0.918007176507921
precision_macro: 0.876731119719527
precision_micro: 0.9218098926417961
recall_macro: 0.8434767218131436
recall_micro: 0.9142357059509918

TEST WITH FROZEN VALIDATION-CALIBRATED THRESHOLDS
direct_f1_macro: 0.7776689085695722
direct_f1_micro: 0.8629880093197704
direct_precision_macro: 0.7983369104632524
direct_precision_micro: 0.865595075239398
direct_recall_macro: 0.7686052502698012
direct_recall_micro: 0.8603966005665722
f1_macro: 0.8535155187904646
f1_micro: 0.9167216641001198
precision_macro: 0.876238436670763
precision_micro: 0.9217912795556211
recall_macro: 0.8386159591309453
recall_micro: 0.91170750680669

====================================================================================================
REPEATED-RUN TEST SUMMARY
====================================================================================================
Metric                          Mean         SD        Min        Max
----------------------------------------------------------------------
precision_micro               0.9185     0.0024     0.9136     0.9232
recall_micro                  0.9129     0.0039     0.9036     0.9205
f1_micro                      0.9157     0.0016     0.9122     0.9199
precision_macro               0.8734     0.0060     0.8642     0.8870
recall_macro                  0.8425     0.0093     0.8231     0.8604
f1_macro                      0.8533     0.0060     0.8435     0.8669

======================================================================================================================
REPEATED-RUN TEST PERFORMANCE BY COMPLETE FEATURE (AFTER INHERITANCE)
======================================================================================================================
Feature                               P mean     P SD   R mean     R SD  F1 mean    F1 SD   F1 min   F1 max  Support
--------------------------------------------------------------------------------------------------------------------
Abstract                              0.9443   0.0042   0.9335   0.0076   0.9388   0.0034   0.9317   0.9442     3091
Animal                                0.8753   0.0432   0.9281   0.0297   0.9000   0.0247   0.8448   0.9623       51
Animate                               0.9588   0.0050   0.9499   0.0088   0.9543   0.0036   0.9440   0.9602     1198
Artefact                              0.9000   0.0128   0.8905   0.0134   0.8951   0.0059   0.8782   0.9025      517
Body_Part                             0.8872   0.0385   0.8869   0.0421   0.8859   0.0245   0.8387   0.9254       33
Comestible                            0.8879   0.0140   0.9604   0.0088   0.9227   0.0076   0.9102   0.9434      155
Communication                         0.8910   0.0127   0.8918   0.0211   0.8912   0.0079   0.8678   0.9040      553
Concrete                              0.9416   0.0044   0.9482   0.0053   0.9449   0.0026   0.9394   0.9503     2216
Currency                              0.9987   0.0073   0.9597   0.0337   0.9785   0.0171   0.9565   1.0000       24
Duration                              0.8453   0.0365   0.8264   0.0624   0.8331   0.0190   0.7942   0.8727      153
Elongated                             0.8169   0.0419   0.5930   0.0424   0.6855   0.0271   0.6275   0.7471       95
Eventive                              0.8490   0.0144   0.8831   0.0143   0.8655   0.0059   0.8546   0.8767      679
Feminine                              0.9357   0.0222   0.8903   0.0223   0.9121   0.0120   0.8834   0.9348      141
Fluid                                 0.9209   0.0490   0.9267   0.0365   0.9223   0.0221   0.8837   0.9744       20
Garment                               0.9967   0.0183   0.8818   0.0424   0.9352   0.0277   0.8571   0.9524       11
Human                                 0.9627   0.0055   0.9532   0.0093   0.9579   0.0036   0.9484   0.9633     1106
Inanimate                             0.9104   0.0108   0.9196   0.0091   0.9149   0.0032   0.9097   0.9238     1005
Internal_Control                      0.9400   0.0057   0.9239   0.0074   0.9318   0.0027   0.9274   0.9376     2336
Language                              0.9778   0.0846   0.7833   0.2520   0.8422   0.1638   0.6667   1.0000        2
Location                              0.9027   0.0143   0.8992   0.0092   0.9008   0.0051   0.8864   0.9072      799
Machine                               0.9167   0.0165   0.8853   0.0246   0.9004   0.0128   0.8730   0.9323      202
Masculine                             0.9044   0.0115   0.9085   0.0137   0.9063   0.0045   0.8979   0.9159      556
Natural                               0.9522   0.0049   0.9443   0.0084   0.9482   0.0036   0.9372   0.9542     1240
Natural_Force                         0.8811   0.0497   0.6167   0.0352   0.7247   0.0329   0.6316   0.7895       22
Non_Rigid                             0.7358   0.0271   0.8118   0.0251   0.7712   0.0099   0.7546   0.7911      217
Organisation                          0.8619   0.0145   0.8536   0.0153   0.8575   0.0049   0.8452   0.8672      911
Plant                                 0.9808   0.0765   0.6889   0.0576   0.8056   0.0404   0.7143   0.9091        6
Point_in_Time                         0.8475   0.0343   0.8939   0.0333   0.8689   0.0094   0.8520   0.8876      174
Pointy                                0.0694   0.1482   0.0515   0.1279   0.0538   0.1209   0.0000   0.4444       11
Question                              0.8537   0.0594   0.9259   0.0266   0.8867   0.0264   0.8293   0.9444       18
Rigid                                 0.8589   0.0182   0.8438   0.0159   0.8510   0.0065   0.8366   0.8628      377
Solid                                 0.9342   0.0063   0.9164   0.0101   0.9252   0.0046   0.9165   0.9348     1393
Sound                                 0.7445   0.0724   0.6699   0.0811   0.6989   0.0421   0.5714   0.7931       31
Statement                             0.7804   0.0557   0.6675   0.0463   0.7163   0.0141   0.6642   0.7410      160
Substance                             0.7968   0.0374   0.9222   0.0306   0.8537   0.0142   0.8238   0.8841      159
Time                                  0.9554   0.0090   0.9509   0.0287   0.9528   0.0118   0.9137   0.9635      337
Unspecified_Gender_or_Neuter          0.8307   0.0282   0.8463   0.0202   0.8379   0.0104   0.8182   0.8582      408
Vehicle                               0.8897   0.0414   0.9117   0.0559   0.8987   0.0282   0.8333   0.9351       37
Web_Location                          0.9261   0.0203   0.7177   0.0496   0.8073   0.0279   0.7379   0.8511      124

======================================================================================================================
REPEATED-RUN TEST PERFORMANCE BY INDEPENDENT NEURAL OUTPUT
======================================================================================================================
Feature                               P mean     P SD   R mean     R SD  F1 mean    F1 SD   F1 min   F1 max  Support
--------------------------------------------------------------------------------------------------------------------
Abstract                              0.8862   0.0177   0.8382   0.0178   0.8612   0.0058   0.8455   0.8708      733
Animal                                0.8753   0.0432   0.9281   0.0297   0.9000   0.0247   0.8448   0.9623       51
Animate                               0.0167   0.0913   0.0167   0.0913   0.0167   0.0913   0.0000   0.5000        2
Artefact                              0.8359   0.0279   0.8500   0.0169   0.8424   0.0106   0.8217   0.8600      304
Body_Part                             0.8872   0.0385   0.8869   0.0421   0.8859   0.0245   0.8387   0.9254       33
Comestible                            0.8879   0.0140   0.9604   0.0088   0.9227   0.0076   0.9102   0.9434      155
Communication                         0.7802   0.0223   0.8550   0.0220   0.8154   0.0077   0.7975   0.8308      375
Currency                              0.9987   0.0073   0.9597   0.0337   0.9785   0.0171   0.9565   1.0000       24
Duration                              0.8453   0.0365   0.8264   0.0624   0.8331   0.0190   0.7942   0.8727      153
Elongated                             0.8169   0.0419   0.5930   0.0424   0.6855   0.0271   0.6275   0.7471       95
Eventive                              0.8490   0.0144   0.8831   0.0143   0.8655   0.0059   0.8546   0.8767      679
Feminine                              0.9357   0.0222   0.8903   0.0223   0.9121   0.0120   0.8834   0.9348      141
Fluid                                 0.9209   0.0490   0.9267   0.0365   0.9223   0.0221   0.8837   0.9744       20
Garment                               0.9967   0.0183   0.8818   0.0424   0.9352   0.0277   0.8571   0.9524       11
Inanimate                             0.9104   0.0108   0.9196   0.0091   0.9149   0.0032   0.9097   0.9238     1005
Internal_Control                      0.4896   0.1412   0.2458   0.0634   0.3144   0.0662   0.2000   0.4348       16
Language                              0.9778   0.0846   0.7833   0.2520   0.8422   0.1638   0.6667   1.0000        2
Location                              0.9027   0.0143   0.8992   0.0092   0.9008   0.0051   0.8864   0.9072      799
Machine                               0.9063   0.0205   0.8675   0.0293   0.8859   0.0134   0.8635   0.9141      165
Masculine                             0.9044   0.0115   0.9085   0.0137   0.9063   0.0045   0.8979   0.9159      556
Natural                               0.7144   0.0281   0.7349   0.0374   0.7235   0.0196   0.6667   0.7711       42
Natural_Force                         0.8811   0.0497   0.6167   0.0352   0.7247   0.0329   0.6316   0.7895       22
Non_Rigid                             0.7358   0.0271   0.8118   0.0251   0.7712   0.0099   0.7546   0.7911      217
Organisation                          0.8619   0.0145   0.8536   0.0153   0.8575   0.0049   0.8452   0.8672      911
Plant                                 0.9808   0.0765   0.6889   0.0576   0.8056   0.0404   0.7143   0.9091        6
Point_in_Time                         0.8475   0.0343   0.8939   0.0333   0.8689   0.0094   0.8520   0.8876      174
Pointy                                0.0694   0.1482   0.0515   0.1279   0.0538   0.1209   0.0000   0.4444       11
Question                              0.8537   0.0594   0.9259   0.0266   0.8867   0.0264   0.8293   0.9444       18
Rigid                                 0.8589   0.0182   0.8438   0.0159   0.8510   0.0065   0.8366   0.8628      377
Solid                                 0.8641   0.0175   0.8400   0.0148   0.8516   0.0053   0.8411   0.8638      799
Sound                                 0.7445   0.0724   0.6699   0.0811   0.6989   0.0421   0.5714   0.7931       31
Statement                             0.7804   0.0557   0.6675   0.0463   0.7163   0.0141   0.6642   0.7410      160
Substance                             0.7968   0.0374   0.9222   0.0306   0.8537   0.0142   0.8238   0.8841      159
Time                                  0.4077   0.0999   0.6267   0.1285   0.4758   0.0616   0.2857   0.5882       10
Unspecified_Gender_or_Neuter          0.8307   0.0282   0.8463   0.0202   0.8379   0.0104   0.8182   0.8582      408
Vehicle                               0.8897   0.0414   0.9117   0.0559   0.8987   0.0282   0.8333   0.9351       37
Web_Location                          0.9261   0.0203   0.7177   0.0496   0.8073   0.0279   0.7379   0.8511      124

====================================================================================================
SENTENCE-CLUSTER BOOTSTRAP ON HELD-OUT TEST SET
====================================================================================================
Bootstrap samples: 1,700
Confidence level : 95.0%
Bootstrap unit   : sentence (all eligible NOUN/PROPN targets from a sampled sentence move together)

Metric                      Run mean     Run SD   95% CI low  95% CI high
------------------------------------------------------------------------------
precision_micro               0.9185     0.0024       0.9118       0.9247
recall_micro                  0.9129     0.0039       0.9060       0.9193
f1_micro                      0.9157     0.0016       0.9097       0.9213
precision_macro               0.8734     0.0060       0.8430       0.8819
recall_macro                  0.8425     0.0093       0.8149       0.8569
f1_macro                      0.8533     0.0060       0.8245       0.8628

====================================================================================================
OUTPUTS
====================================================================================================
Fixed sentence split:
  /home/mark/verbnet-roberta/models/roberta_semantic_features/sentence_split.json
Semantic feature metadata:
  /home/mark/verbnet-roberta/models/roberta_semantic_features/semantic_features.json
Per-run results:
  /home/mark/verbnet-roberta/models/roberta_semantic_features/runs
Repeated-run summary:
  /home/mark/verbnet-roberta/models/roberta_semantic_features/repeated_run_results.json
Test bootstrap confidence intervals:
  /home/mark/verbnet-roberta/models/roberta_semantic_features/test_bootstrap_confidence_intervals.json
Neutral reference model (first predeclared seed; not best-test selected):
  /home/mark/verbnet-roberta/models/roberta_semantic_features/reference_model

<h1>Dataset stats</h1>

In [13]:
#!/usr/bin/env python3
"""
Inspect the TRAIN / VALIDATION / TEST composition used by the RoBERTa
semantic-feature experiment.

Compatible with Python 3.9.21.

Prints:
    - source sentence counts
    - sentence-level exclusions due to having no usable feature-bearing targets
    - retained train / validation / test sentence counts
    - empty-feature NOUN/PROPN records inside each retained split
    - tagged NOUN count
    - tagged PROPN count
    - total tagged NOUN/PROPN count
    - complete feature-frequency breakdown
    - independent-feature frequency breakdown
    - side-by-side feature-frequency comparison

The train/validation split follows the same procedure as the training script:
    1. Exclude training sentences with no non-empty NOUN/PROPN feature target.
    2. Reduce complete feature sets to independent features.
    3. Represent each sentence by independent-feature presence.
    4. Use iterative multilabel stratified splitting at SENTENCE level.
    5. Require every independent feature to retain at least one positive
       token target in the training subset.
    6. Use the untouched eligible official test sentences as the test set.
"""

from __future__ import annotations

import json
from collections import Counter, defaultdict
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, Iterable, List, Sequence, Set, Tuple

import numpy as np

from conllu import parse_incr
from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit


# =============================================================================
# Configuration
# =============================================================================

TRAIN_JSONL_PATH = Path(
    "../data/ewt_train_wordnet_wsd_features_wordnet_fixed.jsonl"
)

TEST_JSONL_PATH = Path(
    "../data/ewt_test_wordnet_wsd_features_wordnet_fixed.jsonl"
)

TRAIN_CONLLU_PATH = Path(
    "../data/UD_English-EWT-master/"
    "UD_English-EWT-master/"
    "en_ewt-ud-train.conllu"
)

TEST_CONLLU_PATH = Path(
    "../data/UD_English-EWT-master/"
    "UD_English-EWT-master/"
    "en_ewt-ud-test.conllu"
)


# Exactly as in the training script.
VALIDATION_FRACTION = 0.20
SPLIT_SEED = 42

MIN_TRAIN_POSITIVES_PER_FEATURE = 1
MAX_STRATIFICATION_ATTEMPTS = 200

TARGET_POS = {"NOUN", "PROPN"}


# Exactly as in the supplied training script.
FEATURE_SWITCHES: Dict[str, bool] = {
    "State": False,
    "State_of_Matter": False,
    "Shape": False,
    "Rigidity": False,
}


# =============================================================================
# Feature hierarchy
# =============================================================================

FEATURE_PARENTS: Dict[str, Set[str]] = {
    "Organisation": {
        "Internal_Control",
        "Abstract",
    },
    "Natural_Force": {
        "Internal_Control",
    },
    "Animate": {
        "Internal_Control",
        "Natural",
    },
    "Human": {
        "Animate",
    },
    "Feminine": {
        "Human",
    },
    "Masculine": {
        "Human",
    },
    "Unspecified_Gender_or_Neuter": {
        "Human",
    },
    "Animal": {
        "Animate",
    },
    "Plant": {
        "Animate",
    },
    "Body_Part": {
        "Animate",
    },
    "Machine": {
        "Internal_Control",
        "Artefact",
    },
    "Vehicle": {
        "Machine",
    },
    "Natural": {
        "Concrete",
    },
    "Artefact": {
        "Concrete",
    },
    "Comestible": {
        "Concrete",
    },
    "Substance": {
        "Concrete",
    },
    "State_of_Matter": {
        "Concrete",
    },
    "Inanimate": {
        "Concrete",
    },
    "Garment": {
        "Artefact",
    },
    "Solid": {
        "State_of_Matter",
    },
    "Fluid": {
        "State_of_Matter",
    },
    "Rigidity": {
        "Solid",
    },
    "Shape": {
        "Solid",
    },
    "Rigid": {
        "Rigidity",
    },
    "Non_Rigid": {
        "Rigidity",
    },
    "Elongated": {
        "Shape",
    },
    "Pointy": {
        "Shape",
    },
    "Point_in_Time": {
        "Time",
    },
    "Duration": {
        "Time",
    },
    "Time": {
        "Abstract",
    },
    "Language": {
        "Abstract",
    },
    "Sound": {
        "Abstract",
    },
    "Communication": {
        "Abstract",
    },
    "Eventive": {
        "Abstract",
    },
    "Statement": {
        "Communication",
    },
    "Question": {
        "Communication",
    },
}


def is_feature_enabled(feature: str) -> bool:
    return bool(FEATURE_SWITCHES.get(feature, True))


@lru_cache(maxsize=None)
def get_feature_ancestors(feature: str) -> frozenset:
    """
    Return all enabled direct and indirect parents.

    Traversal continues through disabled intermediate nodes, matching
    the training script.
    """

    ancestors: Set[str] = set()

    for parent in FEATURE_PARENTS.get(feature, set()):
        if is_feature_enabled(parent):
            ancestors.add(parent)

        ancestors.update(
            get_feature_ancestors(parent)
        )

    return frozenset(ancestors)


def reduce_to_independent_features(
    features: Iterable[str],
) -> Set[str]:
    """
    Remove a feature if it can be deterministically inherited from
    another feature present on the same token.
    """

    feature_set = set(features)

    inherited_from_other_features: Set[str] = set()

    for feature in feature_set:
        inherited_from_other_features.update(
            get_feature_ancestors(feature)
        )

    return feature_set - inherited_from_other_features


# =============================================================================
# Data loading
# =============================================================================

def load_conllu(path: Path) -> List[Any]:
    """Load all CoNLL-U sentences."""

    if not path.exists():
        raise FileNotFoundError(
            f"Could not find CoNLL-U file:\n{path.resolve()}"
        )

    sentences: List[Any] = []

    with path.open("r", encoding="utf-8") as handle:
        for sentence in parse_incr(handle):
            sentences.append(sentence)

    return sentences


def load_tagged_records(
    path: Path,
) -> Dict[int, Dict[int, Dict[str, Any]]]:
    """
    Load NOUN and PROPN records.

    Returns:

        sentence_index
            -> token_id
                -> JSON record
    """

    if not path.exists():
        raise FileNotFoundError(
            f"Could not find tagged JSONL:\n{path.resolve()}"
        )

    records: Dict[
        int,
        Dict[int, Dict[str, Any]]
    ] = defaultdict(dict)

    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):

            line = line.strip()

            if not line:
                continue

            try:
                record = json.loads(line)

            except json.JSONDecodeError as exc:
                print(
                    f"Warning: invalid JSON on line "
                    f"{line_number}: {exc}"
                )
                continue

            if record.get("upos") not in TARGET_POS:
                continue

            sentence_index = record.get("sentence_index")
            token_id = record.get("token_id")

            if not isinstance(sentence_index, int):
                continue

            if not isinstance(token_id, int):
                continue

            records[sentence_index][token_id] = record

    return dict(records)


# =============================================================================
# Feature handling
# =============================================================================

def clean_features(
    record: Dict[str, Any],
) -> List[str]:
    """
    Return unique enabled complete features.

    This deliberately honours FEATURE_SWITCHES exactly as the
    training script does.
    """

    raw = record.get("features", [])

    if not isinstance(raw, list):
        return []

    return sorted(
        {
            str(feature).strip()
            for feature in raw
            if (
                str(feature).strip()
                and is_feature_enabled(
                    str(feature).strip()
                )
            )
        }
    )


def get_independent_record_features(
    record: Dict[str, Any],
) -> List[str]:
    """Return the features used as direct neural targets."""

    return sorted(
        reduce_to_independent_features(
            clean_features(record)
        )
    )


# =============================================================================
# Eligible sentences
# =============================================================================

def get_eligible_sentence_indices(
    sentences: Sequence[Any],
    tagged_records: Dict[
        int,
        Dict[int, Dict[str, Any]]
    ],
) -> List[int]:
    """
    A sentence is eligible when it contains at least one NOUN/PROPN
    target with a non-empty enabled feature set.
    """

    eligible: List[int] = []

    for sentence_index in range(len(sentences)):

        token_records = tagged_records.get(
            sentence_index,
            {},
        )

        valid_records = [
            record
            for record in token_records.values()
            if clean_features(record)
        ]

        if valid_records:
            eligible.append(sentence_index)

    return eligible


# =============================================================================
# Sentence-level multilabel split
# =============================================================================

def get_sentence_independent_feature_counts(
    tagged_records: Dict[
        int,
        Dict[int, Dict[str, Any]]
    ],
    sentence_index: int,
) -> Counter:
    """
    Count independent positive token targets in one sentence.
    """

    counts: Counter = Counter()

    for record in tagged_records.get(
        sentence_index,
        {},
    ).values():

        if not clean_features(record):
            continue

        for feature in get_independent_record_features(
            record
        ):
            counts[feature] += 1

    return counts


def build_sentence_multilabel_matrix(
    eligible_indices: Sequence[int],
    tagged_records: Dict[
        int,
        Dict[int, Dict[str, Any]]
    ],
) -> Tuple[
    np.ndarray,
    List[str],
    Dict[int, Counter],
]:
    """
    Build the sentence-level presence matrix used by the original split.
    """

    sentence_feature_counts: Dict[int, Counter] = {
        sentence_index:
            get_sentence_independent_feature_counts(
                tagged_records,
                sentence_index,
            )
        for sentence_index in eligible_indices
    }

    stratification_labels = sorted(
        {
            feature
            for counts in sentence_feature_counts.values()
            for feature, count in counts.items()
            if count > 0
        }
    )

    if not stratification_labels:
        raise RuntimeError(
            "No independent features found in eligible training sentences."
        )

    label2column = {
        label: column
        for column, label
        in enumerate(stratification_labels)
    }

    matrix = np.zeros(
        (
            len(eligible_indices),
            len(stratification_labels),
        ),
        dtype=np.int8,
    )

    for row, sentence_index in enumerate(
        eligible_indices
    ):
        for feature in sentence_feature_counts[
            sentence_index
        ]:
            matrix[
                row,
                label2column[feature],
            ] = 1

    return (
        matrix,
        stratification_labels,
        sentence_feature_counts,
    )


def sentence_prevalence_error(
    y_all: np.ndarray,
    validation_rows: np.ndarray,
    validation_fraction: float,
) -> float:

    total_support = (
        y_all.sum(axis=0)
        .astype(np.float64)
    )

    validation_support = (
        y_all[validation_rows]
        .sum(axis=0)
        .astype(np.float64)
    )

    target_support = (
        total_support * validation_fraction
    )

    scale = np.maximum(
        target_support,
        1.0,
    )

    return float(
        np.mean(
            np.abs(
                validation_support
                - target_support
            )
            / scale
        )
    )


def make_train_validation_split(
    eligible_indices: Sequence[int],
    tagged_records: Dict[
        int,
        Dict[int, Dict[str, Any]]
    ],
) -> Dict[str, Any]:
    """
    Reproduce the training script's train/validation split.
    """

    eligible_indices = list(
        eligible_indices
    )

    (
        sentence_matrix,
        stratification_labels,
        sentence_feature_counts,
    ) = build_sentence_multilabel_matrix(
        eligible_indices,
        tagged_records,
    )

    all_token_counts: Counter = Counter()

    for counts in sentence_feature_counts.values():
        all_token_counts.update(counts)

    x_dummy = np.zeros(
        (len(eligible_indices), 1),
        dtype=np.int8,
    )

    best_candidate = None
    rejected_for_coverage = 0

    for attempt in range(
        MAX_STRATIFICATION_ATTEMPTS
    ):

        attempt_seed = SPLIT_SEED + attempt

        splitter = (
            MultilabelStratifiedShuffleSplit(
                n_splits=1,
                test_size=VALIDATION_FRACTION,
                random_state=attempt_seed,
            )
        )

        train_rows, validation_rows = next(
            splitter.split(
                x_dummy,
                sentence_matrix,
            )
        )

        train_indices = [
            eligible_indices[int(row)]
            for row in train_rows
        ]

        validation_indices = [
            eligible_indices[int(row)]
            for row in validation_rows
        ]

        train_token_counts: Counter = Counter()

        for sentence_index in train_indices:
            train_token_counts.update(
                sentence_feature_counts[
                    sentence_index
                ]
            )

        missing_or_undercovered = sorted(
            feature
            for feature, total_count
            in all_token_counts.items()
            if (
                total_count > 0
                and train_token_counts[feature]
                < MIN_TRAIN_POSITIVES_PER_FEATURE
            )
        )

        if missing_or_undercovered:
            rejected_for_coverage += 1
            continue

        prevalence_error = (
            sentence_prevalence_error(
                sentence_matrix,
                validation_rows,
                VALIDATION_FRACTION,
            )
        )

        candidate = {
            "train": train_indices,
            "validation": validation_indices,
            "split_seed_used": attempt_seed,
            "attempt": attempt + 1,
            "prevalence_error": prevalence_error,
            "stratification_labels":
                stratification_labels,
        }

        if (
            best_candidate is None
            or prevalence_error
            < best_candidate["prevalence_error"]
        ):
            best_candidate = candidate

        # Matches the supplied training script.
        if rejected_for_coverage == 0:
            break

    if best_candidate is None:
        raise RuntimeError(
            "Could not construct a valid "
            "train/validation split."
        )

    return best_candidate


# =============================================================================
# Split statistics
# =============================================================================

def get_split_statistics(
    tagged_records: Dict[
        int,
        Dict[int, Dict[str, Any]]
    ],
    sentence_indices: Sequence[int],
) -> Dict[str, Any]:

    noun_count = 0
    propn_count = 0

    empty_noun_count = 0
    empty_propn_count = 0

    complete_feature_counts: Counter = Counter()
    independent_feature_counts: Counter = Counter()

    sentences_with_empty_records: Set[int] = set()

    for sentence_index in sentence_indices:

        sentence_records = tagged_records.get(
            sentence_index,
            {},
        )

        for record in sentence_records.values():

            upos = record.get("upos")

            features = clean_features(record)

            if not features:

                sentences_with_empty_records.add(
                    sentence_index
                )

                if upos == "NOUN":
                    empty_noun_count += 1

                elif upos == "PROPN":
                    empty_propn_count += 1

                continue

            # Only count genuinely tagged/usable records here.
            if upos == "NOUN":
                noun_count += 1

            elif upos == "PROPN":
                propn_count += 1

            complete_feature_counts.update(
                features
            )

            independent_feature_counts.update(
                get_independent_record_features(
                    record
                )
            )

    return {
        "sentences": len(sentence_indices),

        "tagged_nouns": noun_count,
        "tagged_proper_nouns": propn_count,

        "tagged_total":
            noun_count + propn_count,

        "empty_feature_nouns":
            empty_noun_count,

        "empty_feature_proper_nouns":
            empty_propn_count,

        "empty_feature_records":
            empty_noun_count
            + empty_propn_count,

        "sentences_containing_empty_records":
            len(sentences_with_empty_records),

        "complete_feature_counts":
            complete_feature_counts,

        "independent_feature_counts":
            independent_feature_counts,
    }


def print_feature_breakdown(
    counts: Counter,
    tagged_token_count: int,
) -> None:

    if not counts:
        print("  No features.")
        return

    print(
        f"  {'Feature':35s}"
        f"{'Count':>10s}"
        f"{'% tokens':>12s}"
    )

    print("  " + "-" * 57)

    for feature in sorted(counts):

        count = counts[feature]

        percentage = (
            100.0 * count / tagged_token_count
            if tagged_token_count
            else 0.0
        )

        print(
            f"  {feature:35s}"
            f"{count:10,d}"
            f"{percentage:11.2f}%"
        )


def print_split(
    name: str,
    statistics: Dict[str, Any],
) -> None:

    print()
    print("=" * 80)
    print(name.upper())
    print("=" * 80)

    print(
        f"Sentences retained                    : "
        f"{statistics['sentences']:,}"
    )

    print(
        f"Tagged NOUN tokens                   : "
        f"{statistics['tagged_nouns']:,}"
    )

    print(
        f"Tagged PROPN tokens                  : "
        f"{statistics['tagged_proper_nouns']:,}"
    )

    print(
        f"Tagged NOUN + PROPN tokens           : "
        f"{statistics['tagged_total']:,}"
    )

    print(
        f"Empty-feature NOUN records excluded  : "
        f"{statistics['empty_feature_nouns']:,}"
    )

    print(
        f"Empty-feature PROPN records excluded : "
        f"{statistics['empty_feature_proper_nouns']:,}"
    )

    print(
        f"All empty-feature records excluded   : "
        f"{statistics['empty_feature_records']:,}"
    )

    print(
        f"Sentences containing ≥1 empty record : "
        f"{statistics['sentences_containing_empty_records']:,}"
    )

    print()
    print("COMPLETE FEATURE FREQUENCIES")
    print()

    print_feature_breakdown(
        statistics["complete_feature_counts"],
        statistics["tagged_total"],
    )

    print()
    print("INDEPENDENT FEATURE FREQUENCIES")
    print()

    print_feature_breakdown(
        statistics[
            "independent_feature_counts"
        ],
        statistics["tagged_total"],
    )


def print_side_by_side_feature_table(
    train_stats: Dict[str, Any],
    validation_stats: Dict[str, Any],
    test_stats: Dict[str, Any],
) -> None:
    """
    Compare complete feature frequencies directly across splits.
    """

    train_counts = train_stats[
        "complete_feature_counts"
    ]

    validation_counts = validation_stats[
        "complete_feature_counts"
    ]

    test_counts = test_stats[
        "complete_feature_counts"
    ]

    all_features = sorted(
        set(train_counts)
        | set(validation_counts)
        | set(test_counts)
    )

    print()
    print("=" * 110)
    print("COMPLETE FEATURE DISTRIBUTION ACROSS SPLITS")
    print("=" * 110)

    print(
        f"{'Feature':32s}"
        f"{'Train':>10s}"
        f"{'Train %':>10s}"
        f"{'Valid':>10s}"
        f"{'Valid %':>10s}"
        f"{'Test':>10s}"
        f"{'Test %':>10s}"
    )

    print("-" * 92)

    train_total = train_stats["tagged_total"]
    validation_total = validation_stats[
        "tagged_total"
    ]
    test_total = test_stats["tagged_total"]

    for feature in all_features:

        train_count = train_counts[feature]
        validation_count = validation_counts[
            feature
        ]
        test_count = test_counts[feature]

        train_pct = (
            100.0 * train_count / train_total
            if train_total
            else 0.0
        )

        validation_pct = (
            100.0
            * validation_count
            / validation_total
            if validation_total
            else 0.0
        )

        test_pct = (
            100.0 * test_count / test_total
            if test_total
            else 0.0
        )

        print(
            f"{feature:32s}"
            f"{train_count:10,d}"
            f"{train_pct:9.2f}%"
            f"{validation_count:10,d}"
            f"{validation_pct:9.2f}%"
            f"{test_count:10,d}"
            f"{test_pct:9.2f}%"
        )


# =============================================================================
# Main
# =============================================================================

def main() -> None:

    # -------------------------------------------------------------------------
    # Load data
    # -------------------------------------------------------------------------

    print("=" * 80)
    print("LOADING DATA")
    print("=" * 80)

    train_sentences = load_conllu(
        TRAIN_CONLLU_PATH
    )

    test_sentences = load_conllu(
        TEST_CONLLU_PATH
    )

    train_tagged_records = load_tagged_records(
        TRAIN_JSONL_PATH
    )

    test_tagged_records = load_tagged_records(
        TEST_JSONL_PATH
    )

    # -------------------------------------------------------------------------
    # Eligibility
    # -------------------------------------------------------------------------

    eligible_train_indices = (
        get_eligible_sentence_indices(
            train_sentences,
            train_tagged_records,
        )
    )

    eligible_test_indices = (
        get_eligible_sentence_indices(
            test_sentences,
            test_tagged_records,
        )
    )

    train_ineligible_indices = sorted(
        set(range(len(train_sentences)))
        - set(eligible_train_indices)
    )

    test_ineligible_indices = sorted(
        set(range(len(test_sentences)))
        - set(eligible_test_indices)
    )

    # -------------------------------------------------------------------------
    # Same train/validation split as training
    # -------------------------------------------------------------------------

    split = make_train_validation_split(
        eligible_train_indices,
        train_tagged_records,
    )

    train_indices = split["train"]
    validation_indices = split["validation"]

    # Official test set is not subdivided.
    test_indices = list(
        eligible_test_indices
    )

    # -------------------------------------------------------------------------
    # Important sentence-level exclusion summary
    # -------------------------------------------------------------------------

    print()
    print("=" * 80)
    print("SENTENCE-LEVEL EXCLUSIONS")
    print("=" * 80)

    print()
    print("TRAINING CORPUS BEFORE TRAIN/VALIDATION SPLIT")
    print(
        f"Total source sentences              : "
        f"{len(train_sentences):,}"
    )
    print(
        f"Eligible sentences                  : "
        f"{len(eligible_train_indices):,}"
    )
    print(
        f"Excluded: no usable features        : "
        f"{len(train_ineligible_indices):,}"
    )
    print(
        f"Exclusion rate                      : "
        f"{100.0 * len(train_ineligible_indices) / len(train_sentences):.2f}%"
    )

    print()
    print("OFFICIAL TEST CORPUS")
    print(
        f"Total source sentences              : "
        f"{len(test_sentences):,}"
    )
    print(
        f"Eligible sentences                  : "
        f"{len(eligible_test_indices):,}"
    )
    print(
        f"Excluded: no usable features        : "
        f"{len(test_ineligible_indices):,}"
    )
    print(
        f"Exclusion rate                      : "
        f"{100.0 * len(test_ineligible_indices) / len(test_sentences):.2f}%"
    )

    print()
    print("TRAIN / VALIDATION SPLIT")
    print(
        f"Training sentences retained         : "
        f"{len(train_indices):,}"
    )
    print(
        f"Validation sentences retained       : "
        f"{len(validation_indices):,}"
    )
    print(
        f"Validation fraction                 : "
        f"{len(validation_indices) / len(eligible_train_indices):.4f}"
    )
    print(
        f"Split seed used                     : "
        f"{split['split_seed_used']}"
    )
    print(
        f"Split attempt                       : "
        f"{split['attempt']}"
    )

    print()
    print(
        "NOTE: the training-corpus sentence exclusions cannot be "
        "separately labelled 'train exclusions' and 'validation exclusions' "
        "because they are removed BEFORE the train/validation split is made."
    )

    # -------------------------------------------------------------------------
    # Detailed retained-split statistics
    # -------------------------------------------------------------------------

    train_stats = get_split_statistics(
        train_tagged_records,
        train_indices,
    )

    validation_stats = get_split_statistics(
        train_tagged_records,
        validation_indices,
    )

    test_stats = get_split_statistics(
        test_tagged_records,
        test_indices,
    )

    print_split(
        "Training",
        train_stats,
    )

    print_split(
        "Validation",
        validation_stats,
    )

    print_split(
        "Test",
        test_stats,
    )

    # -------------------------------------------------------------------------
    # Easy direct comparison
    # -------------------------------------------------------------------------

    print_side_by_side_feature_table(
        train_stats,
        validation_stats,
        test_stats,
    )


if __name__ == "__main__":
    main()

================================================================================
LOADING DATA
================================================================================

================================================================================
SENTENCE-LEVEL EXCLUSIONS
================================================================================

TRAINING CORPUS BEFORE TRAIN/VALIDATION SPLIT
Total source sentences              : 12,544
Eligible sentences                  : 11,198
Excluded: no usable features        : 1,346
Exclusion rate                      : 10.73%

OFFICIAL TEST CORPUS
Total source sentences              : 2,077
Eligible sentences                  : 1,759
Excluded: no usable features        : 318
Exclusion rate                      : 15.31%

TRAIN / VALIDATION SPLIT
Training sentences retained         : 8,885
Validation sentences retained       : 2,313
Validation fraction                 : 0.2066
Split seed used                     : 42
Split attempt                       : 1

NOTE: the training-corpus sentence exclusions cannot be separately labelled 'train exclusions' and 'validation exclusions' because they are removed BEFORE the train/validation split is made.

================================================================================
TRAINING
================================================================================
Sentences retained                    : 8,885
Tagged NOUN tokens                   : 25,277
Tagged PROPN tokens                  : 9,618
Tagged NOUN + PROPN tokens           : 34,895
Empty-feature NOUN records excluded  : 2,251
Empty-feature PROPN records excluded : 435
All empty-feature records excluded   : 2,686
Sentences containing ≥1 empty record : 1,877

COMPLETE FEATURE FREQUENCIES

  Feature                                 Count    % tokens
  ---------------------------------------------------------
  Abstract                               19,625      56.24%
  Animal                                    691       1.98%
  Animate                                 7,500      21.49%
  Artefact                                3,023       8.66%
  Body_Part                                 318       0.91%
  Comestible                                671       1.92%
  Communication                           3,209       9.20%
  Concrete                               13,490      38.66%
  Currency                                  179       0.51%
  Duration                                1,393       3.99%
  Elongated                                 632       1.81%
  Eventive                                4,258      12.20%
  Feminine                                  867       2.48%
  Fluid                                      84       0.24%
  Garment                                    60       0.17%
  Human                                   6,377      18.27%
  Inanimate                               5,851      16.77%
  Internal_Control                       13,148      37.68%
  Language                                   23       0.07%
  Location                                4,733      13.56%
  Machine                                 1,097       3.14%
  Masculine                               2,684       7.69%
  Natural                                 7,807      22.37%
  Natural_Force                             130       0.37%
  Non_Rigid                               1,378       3.95%
  Organisation                            4,425      12.68%
  Plant                                      68       0.19%
  Point_in_Time                           1,257       3.60%
  Pointy                                     78       0.22%
  Question                                  130       0.37%
  Rigid                                   2,165       6.20%
  Solid                                   9,361      26.83%
  Sound                                     169       0.48%
  Statement                               1,038       2.97%
  Substance                                 913       2.62%
  Time                                    2,717       7.79%
  Unspecified_Gender_or_Neuter            2,826       8.10%
  Vehicle                                   359       1.03%
  Web_Location                              222       0.64%

INDEPENDENT FEATURE FREQUENCIES

  Feature                                 Count    % tokens
  ---------------------------------------------------------
  Abstract                                5,754      16.49%
  Animal                                    691       1.98%
  Animate                                    46       0.13%
  Artefact                                1,866       5.35%
  Body_Part                                 318       0.91%
  Comestible                                671       1.92%
  Communication                           2,041       5.85%
  Currency                                  179       0.51%
  Duration                                1,393       3.99%
  Elongated                                 632       1.81%
  Eventive                                4,258      12.20%
  Feminine                                  867       2.48%
  Fluid                                      84       0.24%
  Garment                                    60       0.17%
  Inanimate                               5,851      16.77%
  Internal_Control                           91       0.26%
  Language                                   23       0.07%
  Location                                4,733      13.56%
  Machine                                   738       2.11%
  Masculine                               2,684       7.69%
  Natural                                   307       0.88%
  Natural_Force                             130       0.37%
  Non_Rigid                               1,378       3.95%
  Organisation                            4,425      12.68%
  Plant                                      68       0.19%
  Point_in_Time                           1,257       3.60%
  Pointy                                     78       0.22%
  Question                                  130       0.37%
  Rigid                                   2,165       6.20%
  Solid                                   5,807      16.64%
  Sound                                     169       0.48%
  Statement                               1,038       2.97%
  Substance                                 913       2.62%
  Time                                       67       0.19%
  Unspecified_Gender_or_Neuter            2,826       8.10%
  Vehicle                                   359       1.03%
  Web_Location                              222       0.64%

================================================================================
VALIDATION
================================================================================
Sentences retained                    : 2,313
Tagged NOUN tokens                   : 6,356
Tagged PROPN tokens                  : 2,377
Tagged NOUN + PROPN tokens           : 8,733
Empty-feature NOUN records excluded  : 551
Empty-feature PROPN records excluded : 124
All empty-feature records excluded   : 675
Sentences containing ≥1 empty record : 480

COMPLETE FEATURE FREQUENCIES

  Feature                                 Count    % tokens
  ---------------------------------------------------------
  Abstract                                4,918      56.32%
  Animal                                    184       2.11%
  Animate                                 1,838      21.05%
  Artefact                                  800       9.16%
  Body_Part                                  74       0.85%
  Comestible                                157       1.80%
  Communication                             831       9.52%
  Concrete                                3,370      38.59%
  Currency                                   45       0.52%
  Duration                                  340       3.89%
  Elongated                                 168       1.92%
  Eventive                                1,068      12.23%
  Feminine                                  204       2.34%
  Fluid                                      19       0.22%
  Garment                                    17       0.19%
  Human                                   1,552      17.77%
  Inanimate                               1,511      17.30%
  Internal_Control                        3,234      37.03%
  Language                                    5       0.06%
  Location                                1,209      13.84%
  Machine                                   280       3.21%
  Masculine                                 671       7.68%
  Natural                                 1,917      21.95%
  Natural_Force                              35       0.40%
  Non_Rigid                                 335       3.84%
  Organisation                            1,086      12.44%
  Plant                                      15       0.17%
  Point_in_Time                             336       3.85%
  Pointy                                     20       0.23%
  Question                                   33       0.38%
  Rigid                                     603       6.90%
  Solid                                   2,352      26.93%
  Sound                                      42       0.48%
  Statement                                 264       3.02%
  Substance                                 217       2.48%
  Time                                      692       7.92%
  Unspecified_Gender_or_Neuter              677       7.75%
  Vehicle                                   100       1.15%
  Web_Location                               55       0.63%

INDEPENDENT FEATURE FREQUENCIES

  Feature                                 Count    % tokens
  ---------------------------------------------------------
  Abstract                                1,405      16.09%
  Animal                                    184       2.11%
  Animate                                    13       0.15%
  Artefact                                  503       5.76%
  Body_Part                                  74       0.85%
  Comestible                                157       1.80%
  Communication                             534       6.11%
  Currency                                   45       0.52%
  Duration                                  340       3.89%
  Elongated                                 168       1.92%
  Eventive                                1,068      12.23%
  Feminine                                  204       2.34%
  Fluid                                      19       0.22%
  Garment                                    17       0.19%
  Inanimate                               1,511      17.30%
  Internal_Control                           21       0.24%
  Language                                    5       0.06%
  Location                                1,209      13.84%
  Machine                                   180       2.06%
  Masculine                                 671       7.68%
  Natural                                    79       0.90%
  Natural_Force                              35       0.40%
  Non_Rigid                                 335       3.84%
  Organisation                            1,086      12.44%
  Plant                                      15       0.17%
  Point_in_Time                             336       3.85%
  Pointy                                     20       0.23%
  Question                                   33       0.38%
  Rigid                                     603       6.90%
  Solid                                   1,409      16.13%
  Sound                                      42       0.48%
  Statement                                 264       3.02%
  Substance                                 217       2.48%
  Time                                       16       0.18%
  Unspecified_Gender_or_Neuter              677       7.75%
  Vehicle                                   100       1.15%
  Web_Location                               55       0.63%

================================================================================
TEST
================================================================================
Sentences retained                    : 1,759
Tagged NOUN tokens                   : 3,712
Tagged PROPN tokens                  : 1,992
Tagged NOUN + PROPN tokens           : 5,704
Empty-feature NOUN records excluded  : 350
Empty-feature PROPN records excluded : 73
All empty-feature records excluded   : 423
Sentences containing ≥1 empty record : 281

COMPLETE FEATURE FREQUENCIES

  Feature                                 Count    % tokens
  ---------------------------------------------------------
  Abstract                                3,091      54.19%
  Animal                                     51       0.89%
  Animate                                 1,198      21.00%
  Artefact                                  517       9.06%
  Body_Part                                  33       0.58%
  Comestible                                155       2.72%
  Communication                             553       9.69%
  Concrete                                2,216      38.85%
  Currency                                   24       0.42%
  Duration                                  153       2.68%
  Elongated                                  95       1.67%
  Eventive                                  679      11.90%
  Feminine                                  141       2.47%
  Fluid                                      20       0.35%
  Garment                                    11       0.19%
  Human                                   1,106      19.39%
  Inanimate                               1,005      17.62%
  Internal_Control                        2,336      40.95%
  Language                                    2       0.04%
  Location                                  799      14.01%
  Machine                                   202       3.54%
  Masculine                                 556       9.75%
  Natural                                 1,240      21.74%
  Natural_Force                              22       0.39%
  Non_Rigid                                 217       3.80%
  Organisation                              911      15.97%
  Plant                                       6       0.11%
  Point_in_Time                             174       3.05%
  Pointy                                     11       0.19%
  Question                                   18       0.32%
  Rigid                                     377       6.61%
  Solid                                   1,393      24.42%
  Sound                                      31       0.54%
  Statement                                 160       2.81%
  Substance                                 159       2.79%
  Time                                      337       5.91%
  Unspecified_Gender_or_Neuter              408       7.15%
  Vehicle                                    37       0.65%
  Web_Location                              124       2.17%

INDEPENDENT FEATURE FREQUENCIES

  Feature                                 Count    % tokens
  ---------------------------------------------------------
  Abstract                                  733      12.85%
  Animal                                     51       0.89%
  Animate                                     2       0.04%
  Artefact                                  304       5.33%
  Body_Part                                  33       0.58%
  Comestible                                155       2.72%
  Communication                             375       6.57%
  Currency                                   24       0.42%
  Duration                                  153       2.68%
  Elongated                                  95       1.67%
  Eventive                                  679      11.90%
  Feminine                                  141       2.47%
  Fluid                                      20       0.35%
  Garment                                    11       0.19%
  Human                                       1       0.02%
  Inanimate                               1,005      17.62%
  Internal_Control                           16       0.28%
  Language                                    2       0.04%
  Location                                  799      14.01%
  Machine                                   165       2.89%
  Masculine                                 556       9.75%
  Natural                                    42       0.74%
  Natural_Force                              22       0.39%
  Non_Rigid                                 217       3.80%
  Organisation                              911      15.97%
  Plant                                       6       0.11%
  Point_in_Time                             174       3.05%
  Pointy                                     11       0.19%
  Question                                   18       0.32%
  Rigid                                     377       6.61%
  Solid                                     799      14.01%
  Sound                                      31       0.54%
  Statement                                 160       2.81%
  Substance                                 159       2.79%
  Time                                       10       0.18%
  Unspecified_Gender_or_Neuter              408       7.15%
  Vehicle                                    37       0.65%
  Web_Location                              124       2.17%

==============================================================================================================
COMPLETE FEATURE DISTRIBUTION ACROSS SPLITS
==============================================================================================================
Feature                              Train   Train %     Valid   Valid %      Test    Test %
--------------------------------------------------------------------------------------------
Abstract                            19,625    56.24%     4,918    56.32%     3,091    54.19%
Animal                                 691     1.98%       184     2.11%        51     0.89%
Animate                              7,500    21.49%     1,838    21.05%     1,198    21.00%
Artefact                             3,023     8.66%       800     9.16%       517     9.06%
Body_Part                              318     0.91%        74     0.85%        33     0.58%
Comestible                             671     1.92%       157     1.80%       155     2.72%
Communication                        3,209     9.20%       831     9.52%       553     9.69%
Concrete                            13,490    38.66%     3,370    38.59%     2,216    38.85%
Currency                               179     0.51%        45     0.52%        24     0.42%
Duration                             1,393     3.99%       340     3.89%       153     2.68%
Elongated                              632     1.81%       168     1.92%        95     1.67%
Eventive                             4,258    12.20%     1,068    12.23%       679    11.90%
Feminine                               867     2.48%       204     2.34%       141     2.47%
Fluid                                   84     0.24%        19     0.22%        20     0.35%
Garment                                 60     0.17%        17     0.19%        11     0.19%
Human                                6,377    18.27%     1,552    17.77%     1,106    19.39%
Inanimate                            5,851    16.77%     1,511    17.30%     1,005    17.62%
Internal_Control                    13,148    37.68%     3,234    37.03%     2,336    40.95%
Language                                23     0.07%         5     0.06%         2     0.04%
Location                             4,733    13.56%     1,209    13.84%       799    14.01%
Machine                              1,097     3.14%       280     3.21%       202     3.54%
Masculine                            2,684     7.69%       671     7.68%       556     9.75%

<h1>Hyperparameter tuning</h1>

In [26]:
#!/usr/bin/env python3
"""
Fine-tune RoBERTa for hierarchical multi-label semantic feature tagging of
NOUN/PROPN tokens.

Compatible with Python 3.9.21.

Key design changes
------------------
1. The model is trained only on independent semantic features. For each token,
   any feature that can be inherited from a more specific present feature is
   removed from the neural target. This is a per-token reduction rather than a
   global "terminal leaf only" rule, so features such as Human, Time, Shape,
   Communication, etc. can still be predicted directly when they are the most
   specific available feature for that token.

2. All inherited features are reconstructed deterministically from
   FEATURE_PARENTS for validation, testing, reporting, and later inference.

3. A separate sigmoid threshold is optimised for every neural output using the
   validation split only. The selected thresholds are frozen before the test
   split is evaluated and are saved to prediction_thresholds.json.

4. Train/validation splitting is performed at SENTENCE level with iterative
   multilabel stratification over sentence-level independent-feature presence.
   The split is fixed across repeated fine-tuning runs.

5. A single fixed training seed is used for a validation-only grid search over
   learning rate and effective batch size. This selects a candidate setting
   for the later repeated-seed experiment, not a final performance estimate.

6. The official test corpus is not loaded or evaluated during tuning.

Tagged data:
    Training/validation:
        ewt_train_wordnet_wsd_features_wordnet_fixed.jsonl

Sentence/token sources:
    Training/validation:
        UD_English-EWT-master/
        UD_English-EWT-master/
        en_ewt-ud-train.conllu

The validation split is created only from the training corpus. The official
test corpus remains untouched until final evaluation.

Loss:
    BCEWithLogitsLoss over INDEPENDENT feature labels only.

Headline metrics:
    Computed after deterministic hierarchy expansion, so they describe the
    complete semantic feature sets rather than only the neural outputs.

Requirements:
    python -m pip install torch transformers datasets accelerate conllu scikit-learn iterative-stratification

CUDA is required.
"""

from __future__ import annotations

import csv
import gc
import json
import shutil
from itertools import product
from collections import Counter, defaultdict
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Set, Tuple

import numpy as np
import torch
import torch.nn as nn

from conllu import parse_incr
from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit
from sklearn.metrics import precision_recall_fscore_support
from torch.utils.data import Dataset

from transformers import (
    AutoModelForTokenClassification,
    AutoTokenizer,
    Trainer,
    TrainingArguments,
    set_seed,
)


# =============================================================================
# Configuration
# =============================================================================

TRAIN_JSONL_PATH = Path(
    "../data/ewt_train_wordnet_wsd_features_wordnet_fixed.jsonl"
    #"ewt_train_wordnet_wsd_features_fully_tagged_llm_reviewed.jsonl"
)

TRAIN_CONLLU_PATH = Path(
    "../data/UD_English-EWT-master/"
    "UD_English-EWT-master/"
    "en_ewt-ud-train.conllu"
)

# MODEL_NAME = "FacebookAI/roberta-base"
MODEL_NAME = "FacebookAI/roberta-large"

OUTPUT_DIR = Path("../models/roberta_semantic_features_grid_search")

# Validation is sampled only from eligible training sentences.
VALIDATION_FRACTION = 0.20

# Fixed seed for the sentence-level train/validation split.
SPLIT_SEED = 42

# All grid candidates use the same random seed and split.
TUNING_SEED = 11

# 3 learning rates x 4 batch configurations = 12 training runs.
LEARNING_RATES = [1.5e-5, 2.0e-5, 2.5e-5, 3.0e-5, 3.5e-5, 4.0e-5, 4.5e-5, 5.0e-5]
#LEARNING_RATES = [4.5e-5, 5.0e-5]
LEARNING_RATE_SCHEDULER = "linear"
PER_DEVICE_TRAIN_BATCH_SIZES = [4, 8]
EFFECTIVE_BATCH_SIZES = [16]
WARMUP_STEPS=278
# Gradient accumulation is effective_batch_size // per_device_train_batch_size.
# For a single GPU, the four configurations are (4, 4), (8, 2),
# (4, 8), and (8, 4), where pairs mean (device batch, accumulation).

# The multilabel stratifier is retried with deterministic derived seeds until
# every independent feature still has at least this many positive token targets
# in the TRAIN subset. This prevents a rare direct target from disappearing.
MIN_TRAIN_POSITIVES_PER_FEATURE = 1
MAX_STRATIFICATION_ATTEMPTS = 200

MAX_LENGTH = 256

WEIGHT_DECAY = 0.01

EVAL_BATCH_SIZE = 16

NUM_EPOCHS = 5

# Threshold used during epoch-by-epoch Trainer evaluation. Final thresholds are
# optimised per independent feature on the validation set after training.
DEFAULT_PREDICTION_THRESHOLD = 0.5

# Validation-only threshold search grid.
THRESHOLD_MIN = 0.05
THRESHOLD_MAX = 0.95
THRESHOLD_STEP = 0.01

# Only these POS categories receive feature supervision.
TARGET_POS = {"NOUN", "PROPN"}

# A NOUN/PROPN with no features is considered a failed source annotation rather
# than a valid all-negative target.
EXCLUDE_EMPTY_FEATURE_RECORDS = True

# Optional per-feature switches. Any feature not listed here is enabled.
# Set a feature to False to remove it from:
#   - sentence-level stratification,
#   - neural training targets,
#   - threshold calibration,
#   - hierarchy-expanded gold/predicted feature sets,
#   - per-feature and aggregate evaluation, and
#   - the sentence-cluster bootstrap.
#
# Disabled intermediate hierarchy nodes are skipped but their enabled ancestors
# are still inherited. For example, if Human were disabled, Feminine would still
# inherit Animate/Natural/Concrete/Internal_Control via the hierarchy.
FEATURE_SWITCHES: Dict[str, bool] = {
    "State": False,
    "State_of_Matter": False,
    "Shape": False,
    "Rigidity": False,
}

EVAL_STRATEGY = "epoch"

SPLIT_PATH = OUTPUT_DIR / "sentence_split.json"
LABELS_PATH = OUTPUT_DIR / "semantic_features.json"
GRID_RESULTS_PATH = OUTPUT_DIR / "hyperparameter_grid_results.json"
GRID_CSV_PATH = OUTPUT_DIR / "hyperparameter_grid_results.csv"


# =============================================================================
# Feature hierarchy
# =============================================================================

def is_feature_enabled(feature: str) -> bool:
    """Return whether *feature* participates in this experiment."""

    return bool(FEATURE_SWITCHES.get(feature, True))


def validate_feature_switches(
    train_tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> None:
    """Fail early on misspelled feature-switch names and report disabled labels."""

    observed: Set[str] = set()

    for source in (train_tagged_records,):
        for sentence_records in source.values():
            for record in sentence_records.values():
                raw = record.get("features", [])
                if isinstance(raw, list):
                    observed.update(
                        str(feature).strip()
                        for feature in raw
                        if str(feature).strip()
                    )

    known = set(observed) | set(FEATURE_PARENTS)
    for parents in FEATURE_PARENTS.values():
        known.update(parents)

    unknown = sorted(set(FEATURE_SWITCHES) - known)
    if unknown:
        raise ValueError(
            "FEATURE_SWITCHES contains unknown feature name(s): "
            + ", ".join(unknown)
        )

    disabled = sorted(
        feature for feature, enabled in FEATURE_SWITCHES.items() if not enabled
    )

    print("=" * 80)
    print("FEATURE SWITCHES")
    print("=" * 80)
    if disabled:
        print("Disabled features: " + ", ".join(disabled))
    else:
        print("Disabled features: none")
    print("All unlisted features are enabled.")
    print()


# child -> direct parent(s)
FEATURE_PARENTS: Dict[str, Set[str]] = {
    "Organisation": {
        "Internal_Control",
        "Abstract",
    },
    "Natural_Force": {
        "Internal_Control",
    },
    "Animate": {
        "Internal_Control",
        "Natural",
    },
    "Human": {
        "Animate",
    },
    "Feminine": {
        "Human",
    },
    "Masculine": {
        "Human",
    },
    "Unspecified_Gender_or_Neuter": {
        "Human",
    },
    "Animal": {
        "Animate",
    },
    "Plant": {
        "Animate",
    },
    "Body_Part": {
        "Animate",
    },
    "Machine": {
        "Internal_Control",
        "Artefact",
    },
    "Vehicle": {
        "Machine",
    },
    "Natural": {
        "Concrete",
    },
    "Artefact": {
        "Concrete",
    },
    "Comestible": {
        "Concrete",
    },
    "Substance": {
        "Concrete",
    },
    "State_of_Matter": {
        "Concrete",
    },
    "Inanimate": {
        "Concrete",
    },
    "Garment": {
        "Artefact",
    },
    "Solid": {
        "State_of_Matter",
    },
    "Fluid": {
        "State_of_Matter",
    },
    "Rigidity": {
        "Solid",
    },
    "Shape": {
        "Solid",
    },
    "Rigid": {
        "Rigidity",
    },
    "Non_Rigid": {
        "Rigidity",
    },
    "Elongated": {
        "Shape",
    },
    "Pointy": {
        "Shape",
    },
    "Point_in_Time": {
        "Time",
    },
    "Duration": {
        "Time",
    },
    "Time": {
        "Abstract",
    },
    "Language": {
        "Abstract",
    },
    "Sound": {
        "Abstract",
    },
    "Communication": {
        "Abstract",
    },
    "Eventive": {
        "Abstract",
    },
    "Statement": {
        "Communication",
    },
    "Question": {
        "Communication",
    },
}


def validate_feature_hierarchy() -> None:
    """Fail early if FEATURE_PARENTS contains a cycle or invalid name."""

    all_features: Set[str] = set(FEATURE_PARENTS)

    for parents in FEATURE_PARENTS.values():
        all_features.update(parents)

    for feature in all_features:
        if not isinstance(feature, str) or not feature.strip():
            raise ValueError(
                "FEATURE_PARENTS contains an empty or non-string feature name."
            )

    visiting: Set[str] = set()
    visited: Set[str] = set()

    def visit(feature: str) -> None:
        if feature in visited:
            return

        if feature in visiting:
            raise ValueError(
                f"Cycle detected in FEATURE_PARENTS involving {feature!r}."
            )

        visiting.add(feature)

        for parent in FEATURE_PARENTS.get(feature, set()):
            visit(parent)

        visiting.remove(feature)
        visited.add(feature)

    for feature in sorted(all_features):
        visit(feature)


@lru_cache(maxsize=None)
def get_feature_ancestors(feature: str) -> frozenset:
    """Return every direct and indirect parent of *feature*."""

    ancestors: Set[str] = set()

    for parent in FEATURE_PARENTS.get(feature, set()):
        if is_feature_enabled(parent):
            ancestors.add(parent)
        # Traverse even through a disabled intermediate node so enabled
        # grandparents remain inherited.
        ancestors.update(get_feature_ancestors(parent))

    return frozenset(ancestors)


def expand_feature_hierarchy(features: Iterable[str]) -> Set[str]:
    """Add every deterministic ancestor required by FEATURE_PARENTS."""

    expanded: Set[str] = {
        feature for feature in features if is_feature_enabled(feature)
    }

    for feature in list(expanded):
        expanded.update(get_feature_ancestors(feature))

    return expanded


def reduce_to_independent_features(features: Iterable[str]) -> Set[str]:
    """
    Reduce a complete feature set to the features that must be predicted.

    A feature is redundant when it is an ancestor of another feature present
    for the same token. Such an ancestor can be reconstructed deterministically.

    Examples:
        {Human, Animate, Natural, Concrete, Internal_Control}
            -> {Human}

        {Feminine, Human, Animate, Natural, Concrete, Internal_Control}
            -> {Feminine}

        {Statement, Communication, Abstract, Time}
            -> {Statement, Time}

    This is deliberately PER TOKEN. It is not the same as training only labels
    that are global terminal leaves in the ontology. A generic Human can still
    be a direct neural target if no more specific Human child is present.
    """

    feature_set = set(features)

    inherited_from_other_features: Set[str] = set()

    for feature in feature_set:
        inherited_from_other_features.update(
            get_feature_ancestors(feature)
        )

    return feature_set - inherited_from_other_features


def missing_hierarchy_features(features: Iterable[str]) -> Set[str]:
    """Return ancestors required by the hierarchy but absent from *features*."""

    feature_set = set(features)
    return expand_feature_hierarchy(feature_set) - feature_set


# =============================================================================
# CUDA
# =============================================================================

def check_cuda() -> None:
    """Require CUDA rather than silently falling back to the CPU."""

    if not torch.cuda.is_available():
        raise RuntimeError(
            "CUDA is not available. This script is configured to require "
            "a CUDA-capable GPU."
        )

    print("=" * 80)
    print("CUDA")
    print("=" * 80)
    print(f"PyTorch version: {torch.__version__}")
    print(f"CUDA available: {torch.cuda.is_available()}")
    print(f"CUDA runtime: {torch.version.cuda}")
    print(f"GPU: {torch.cuda.get_device_name(0)}")

    props = torch.cuda.get_device_properties(0)

    print(
        "VRAM: "
        f"{props.total_memory / (1024 ** 3):.2f} GiB"
    )
    print()


# =============================================================================
# Load CoNLL-U
# =============================================================================

def load_conllu(path: Path) -> List[Any]:
    """Load all CoNLL-U sentences."""

    if not path.exists():
        raise FileNotFoundError(
            f"Could not find CoNLL-U file:\n{path.resolve()}"
        )

    sentences: List[Any] = []

    with path.open("r", encoding="utf-8") as handle:
        for sentence in parse_incr(handle):
            sentences.append(sentence)

    return sentences


def get_sentence_words(sentence: Any) -> Tuple[List[str], List[int]]:
    """
    Return ordinary integer-ID tokens and their original CoNLL-U token IDs.

    Multiword-token placeholder rows and empty nodes are excluded.
    """

    words: List[str] = []
    token_ids: List[int] = []

    for token in sentence:
        token_id = token.get("id")

        if not isinstance(token_id, int):
            continue

        form = token.get("form")

        if form is None:
            continue

        words.append(str(form))
        token_ids.append(token_id)

    return words, token_ids


# =============================================================================
# Load tagged JSONL
# =============================================================================

def load_tagged_records(
    path: Path,
) -> Dict[int, Dict[int, Dict[str, Any]]]:
    """
    Return:

        sentence_index
            -> token_id
                -> JSONL record

    Only NOUN and PROPN records are retained.
    """

    if not path.exists():
        raise FileNotFoundError(
            f"Could not find tagged JSONL:\n{path.resolve()}"
        )

    records: Dict[int, Dict[int, Dict[str, Any]]] = defaultdict(dict)

    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            line = line.strip()

            if not line:
                continue

            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                print(
                    "Warning: invalid JSON on line "
                    f"{line_number}: {exc}"
                )
                continue

            if record.get("upos") not in TARGET_POS:
                continue

            sentence_index = record.get("sentence_index")
            token_id = record.get("token_id")

            if not isinstance(sentence_index, int):
                continue

            if not isinstance(token_id, int):
                continue

            records[sentence_index][token_id] = record

    return dict(records)


# =============================================================================
# Labels
# =============================================================================

def clean_features(record: Dict[str, Any]) -> List[str]:
    """Return unique, non-empty COMPLETE feature names from a JSONL record."""

    raw = record.get("features", [])

    if not isinstance(raw, list):
        return []

    return sorted(
        {
            str(feature).strip()
            for feature in raw
            if (
                str(feature).strip()
                and is_feature_enabled(str(feature).strip())
            )
        }
    )


def get_independent_record_features(record: Dict[str, Any]) -> List[str]:
    """Return the per-token minimal feature set that the model must predict."""

    return sorted(
        reduce_to_independent_features(
            clean_features(record)
        )
    )


def build_full_label_vocabulary(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    training_sentence_indices: Sequence[int],
) -> List[str]:
    """
    Build the COMPLETE evaluation vocabulary from training data only.

    Deterministic ancestors are included even if a training record omitted one,
    although hierarchy closure is separately verified and should normally make
    this addition unnecessary.
    """

    labels: Set[str] = set()

    for sentence_index in training_sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            features = clean_features(record)
            labels.update(features)
            labels.update(expand_feature_hierarchy(features))

    if not labels:
        raise RuntimeError(
            "No semantic features were found in the training split."
        )

    return sorted(labels)


def build_prediction_label_vocabulary(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    training_sentence_indices: Sequence[int],
) -> List[str]:
    """Build the neural-output vocabulary from independent training targets."""

    labels: Set[str] = set()

    for sentence_index in training_sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            labels.update(
                get_independent_record_features(record)
            )

    if not labels:
        raise RuntimeError(
            "No independent semantic features were found in the training split."
        )

    return sorted(labels)


# =============================================================================
# Sentence selection and splitting
# =============================================================================

def get_eligible_sentence_indices(
    sentences: Sequence[Any],
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> List[int]:
    """Eligible sentences contain at least one non-empty NOUN/PROPN target."""

    eligible: List[int] = []

    for sentence_index in range(len(sentences)):
        token_records = tagged_records.get(sentence_index, {})

        valid_records = [
            record
            for record in token_records.values()
            if clean_features(record)
        ]

        if valid_records:
            eligible.append(sentence_index)

    return eligible


def get_sentence_independent_feature_counts(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    sentence_index: int,
) -> Counter:
    """Count independent positive token targets in one source sentence."""

    counts: Counter = Counter()

    for record in tagged_records.get(sentence_index, {}).values():
        if not clean_features(record):
            continue

        for feature in get_independent_record_features(record):
            counts[feature] += 1

    return counts


def build_sentence_multilabel_matrix(
    eligible_indices: Sequence[int],
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> Tuple[np.ndarray, List[str], Dict[int, Counter]]:
    """
    Build one multilabel stratification row per SENTENCE.

    y_sentence[sentence, feature] is 1 when at least one eligible NOUN/PROPN
    token in that sentence has the independent feature. Token counts are kept
    separately for the post-split training-coverage constraint.
    """

    sentence_feature_counts: Dict[int, Counter] = {
        sentence_index: get_sentence_independent_feature_counts(
            tagged_records,
            sentence_index,
        )
        for sentence_index in eligible_indices
    }

    stratification_labels = sorted(
        {
            feature
            for counts in sentence_feature_counts.values()
            for feature, count in counts.items()
            if count > 0
        }
    )

    if not stratification_labels:
        raise RuntimeError(
            "No independent semantic features were found in eligible "
            "training sentences."
        )

    label2column = {
        label: column
        for column, label in enumerate(stratification_labels)
    }

    matrix = np.zeros(
        (len(eligible_indices), len(stratification_labels)),
        dtype=np.int8,
    )

    for row, sentence_index in enumerate(eligible_indices):
        for feature in sentence_feature_counts[sentence_index]:
            matrix[row, label2column[feature]] = 1

    return matrix, stratification_labels, sentence_feature_counts


def _sentence_prevalence_error(
    y_all: np.ndarray,
    validation_rows: np.ndarray,
    validation_fraction: float,
) -> float:
    """
    Score how closely validation sentence-level label prevalences match target.

    Lower is better. The score is used only to choose among deterministic
    iterative-stratification attempts that satisfy the training-coverage rule.
    """

    total_support = y_all.sum(axis=0).astype(np.float64)
    validation_support = y_all[validation_rows].sum(axis=0).astype(np.float64)

    target_support = total_support * float(validation_fraction)

    # Scale by at least one expected example so rare and common labels both
    # contribute without allowing extremely common labels to dominate.
    scale = np.maximum(target_support, 1.0)

    return float(
        np.mean(
            np.abs(validation_support - target_support) / scale
        )
    )


def make_train_validation_split(
    eligible_indices: Sequence[int],
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
) -> Dict[str, Any]:
    """
    Create a SENTENCE-LEVEL multilabel-stratified split from TRAINING only.

    Each sentence receives a binary vector indicating which independent feature
    labels occur anywhere among its eligible NOUN/PROPN tokens. Iterative
    multilabel stratification then assigns whole sentences to train/validation.

    The split is retried deterministically when necessary so that every
    independent feature retains at least MIN_TRAIN_POSITIVES_PER_FEATURE
    positive TOKEN targets in the training subset.

    The official test corpus is deliberately not accepted by this function, so
    test labels cannot influence the split.
    """

    if not 0.0 < VALIDATION_FRACTION < 1.0:
        raise ValueError(
            "VALIDATION_FRACTION must be strictly between 0 and 1."
        )

    if MIN_TRAIN_POSITIVES_PER_FEATURE < 1:
        raise ValueError(
            "MIN_TRAIN_POSITIVES_PER_FEATURE must be at least 1."
        )

    if MAX_STRATIFICATION_ATTEMPTS < 1:
        raise ValueError(
            "MAX_STRATIFICATION_ATTEMPTS must be at least 1."
        )

    eligible_indices = list(eligible_indices)

    if len(eligible_indices) < 2:
        raise RuntimeError(
            "Need at least two eligible training sentences to create a "
            "train/validation split."
        )

    (
        sentence_matrix,
        stratification_labels,
        sentence_feature_counts,
    ) = build_sentence_multilabel_matrix(
        eligible_indices,
        tagged_records,
    )

    all_token_counts: Counter = Counter()

    for counts in sentence_feature_counts.values():
        all_token_counts.update(counts)

    x_dummy = np.zeros((len(eligible_indices), 1), dtype=np.int8)

    best_candidate: Optional[Dict[str, Any]] = None
    rejected_for_coverage = 0

    for attempt in range(MAX_STRATIFICATION_ATTEMPTS):
        attempt_seed = SPLIT_SEED + attempt

        splitter = MultilabelStratifiedShuffleSplit(
            n_splits=1,
            test_size=VALIDATION_FRACTION,
            random_state=attempt_seed,
        )

        train_rows, validation_rows = next(
            splitter.split(x_dummy, sentence_matrix)
        )

        train_indices = [
            eligible_indices[int(row)]
            for row in train_rows
        ]
        validation_indices = [
            eligible_indices[int(row)]
            for row in validation_rows
        ]

        train_token_counts: Counter = Counter()

        for sentence_index in train_indices:
            train_token_counts.update(
                sentence_feature_counts[sentence_index]
            )

        missing_or_undercovered = sorted(
            feature
            for feature, total_count in all_token_counts.items()
            if (
                total_count > 0
                and train_token_counts[feature]
                < MIN_TRAIN_POSITIVES_PER_FEATURE
            )
        )

        if missing_or_undercovered:
            rejected_for_coverage += 1
            continue

        prevalence_error = _sentence_prevalence_error(
            sentence_matrix,
            validation_rows,
            VALIDATION_FRACTION,
        )

        candidate = {
            "train": train_indices,
            "validation": validation_indices,
            "split_seed_used": attempt_seed,
            "attempt": attempt + 1,
            "prevalence_error": prevalence_error,
            "stratification_labels": stratification_labels,
        }

        if (
            best_candidate is None
            or prevalence_error < best_candidate["prevalence_error"]
        ):
            best_candidate = candidate

        # Iterative stratification is already designed to balance multilabel
        # prevalence. Once a valid candidate is found, further attempts are not
        # needed unless coverage forced earlier candidates to be rejected.
        if rejected_for_coverage == 0:
            break

    if best_candidate is None:
        raise RuntimeError(
            "Could not create a sentence-level multilabel-stratified "
            "train/validation split that preserved the required training "
            f"support after {MAX_STRATIFICATION_ATTEMPTS} attempts."
        )

    train_indices = best_candidate["train"]
    validation_indices = best_candidate["validation"]

    train_set = set(train_indices)
    validation_set = set(validation_indices)

    if train_set & validation_set:
        raise RuntimeError(
            "Internal split error: at least one sentence occurs in both "
            "training and validation."
        )

    if train_set | validation_set != set(eligible_indices):
        raise RuntimeError(
            "Internal split error: sentence-level split does not exactly cover "
            "the eligible training sentences."
        )

    print()
    print("Sentence-level multilabel-stratified train/validation split:")
    print(
        f"  Eligible training sentences : {len(eligible_indices):,}"
    )
    print(
        f"  Target validation sentences : "
        f"{round(len(eligible_indices) * VALIDATION_FRACTION):,}"
    )
    print(
        f"  Actual validation sentences : {len(validation_indices):,}"
    )
    print(
        f"  Training sentences retained : {len(train_indices):,}"
    )
    print(
        f"  Split seed used             : "
        f"{best_candidate['split_seed_used']}"
    )
    print(
        f"  Stratification labels       : "
        f"{len(stratification_labels):,}"
    )
    print(
        f"  Coverage-rejected attempts  : {rejected_for_coverage:,}"
    )
    print(
        f"  Mean relative prevalence error: "
        f"{best_candidate['prevalence_error']:.6f}"
    )

    # Show sentence-level prevalence agreement, which is the quantity actually
    # controlled by the stratifier.
    validation_fraction_actual = (
        len(validation_indices) / len(eligible_indices)
    )

    label2column = {
        label: column
        for column, label in enumerate(stratification_labels)
    }

    row_by_sentence = {
        sentence_index: row
        for row, sentence_index in enumerate(eligible_indices)
    }

    train_rows_lookup = [
        row_by_sentence[index]
        for index in train_indices
    ]
    validation_rows_lookup = [
        row_by_sentence[index]
        for index in validation_indices
    ]

    print()
    print(
        f"{'Feature':35s} "
        f"{'All sent.':>10s} "
        f"{'Train':>10s} "
        f"{'Valid':>10s} "
        f"{'Valid %':>10s}"
    )
    print("-" * 80)

    for feature in stratification_labels:
        column = label2column[feature]
        all_support = int(sentence_matrix[:, column].sum())
        train_support = int(
            sentence_matrix[train_rows_lookup, column].sum()
        )
        validation_support = int(
            sentence_matrix[validation_rows_lookup, column].sum()
        )

        print(
            f"{feature:35s} "
            f"{all_support:10d} "
            f"{train_support:10d} "
            f"{validation_support:10d} "
            f"{validation_support / max(all_support, 1):10.3f}"
        )

    print(
        f"\nActual validation sentence fraction: "
        f"{validation_fraction_actual:.4f}"
    )
    print()

    return best_candidate


# =============================================================================
# Dataset
# =============================================================================

class SemanticFeatureDataset(Dataset):
    """
    RoBERTa multi-label token-classification dataset.

    IMPORTANT:
        labels contain only INDEPENDENT neural targets.

    Labels have shape:
        [sequence_length, number_of_prediction_features]

    For supervised tokens:
        0 = independent feature absent
        1 = independent feature present

    For ignored tokens:
        -100 across all labels

    Only the first RoBERTa subword corresponding to each source token receives
    supervision.
    """

    def __init__(
        self,
        sentences: Sequence[Any],
        sentence_indices: Sequence[int],
        tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
        tokenizer: Any,
        label2id: Dict[str, int],
        max_length: int,
    ) -> None:
        self.sentences = sentences
        self.sentence_indices = list(sentence_indices)
        self.tagged_records = tagged_records
        self.tokenizer = tokenizer
        self.label2id = label2id
        self.num_labels = len(label2id)
        self.max_length = max_length

    def __len__(self) -> int:
        return len(self.sentence_indices)

    def __getitem__(
        self,
        dataset_index: int,
    ) -> Dict[str, Any]:
        sentence_index = self.sentence_indices[dataset_index]
        sentence = self.sentences[sentence_index]

        words, token_ids = get_sentence_words(sentence)

        encoding = self.tokenizer(
            words,
            is_split_into_words=True,
            truncation=True,
            max_length=self.max_length,
            add_special_tokens=True,
        )

        word_ids = encoding.word_ids()
        labels: List[List[float]] = []
        previous_word_id: Optional[int] = None
        sentence_records = self.tagged_records.get(sentence_index, {})

        for word_id in word_ids:
            if word_id is None:
                labels.append([-100.0] * self.num_labels)
                previous_word_id = word_id
                continue

            # Ignore all but the first subword.
            if word_id == previous_word_id:
                labels.append([-100.0] * self.num_labels)
                continue

            previous_word_id = word_id

            if not 0 <= word_id < len(token_ids):
                labels.append([-100.0] * self.num_labels)
                continue

            conllu_token_id = token_ids[word_id]
            record = sentence_records.get(conllu_token_id)

            if record is None:
                labels.append([-100.0] * self.num_labels)
                continue

            full_features = clean_features(record)

            if not full_features and EXCLUDE_EMPTY_FEATURE_RECORDS:
                labels.append([-100.0] * self.num_labels)
                continue

            independent_features = reduce_to_independent_features(
                full_features
            )

            target = [0.0] * self.num_labels

            for feature in independent_features:
                label_id = self.label2id.get(feature)

                if label_id is not None:
                    target[label_id] = 1.0

            labels.append(target)

        encoding["labels"] = labels
        encoding["sentence_index"] = sentence_index

        return encoding


# =============================================================================
# Data collator
# =============================================================================

class MultiLabelTokenCollator:
    """Dynamically pad inputs and 3-D multi-label token targets."""

    def __init__(
        self,
        tokenizer: Any,
        num_labels: int,
    ) -> None:
        self.tokenizer = tokenizer
        self.num_labels = num_labels

    def __call__(
        self,
        features: List[Dict[str, Any]],
    ) -> Dict[str, torch.Tensor]:
        clean_features_list: List[Dict[str, Any]] = []
        labels_list: List[List[List[float]]] = []

        for item in features:
            item = dict(item)
            item.pop("sentence_index", None)

            labels = item.pop("labels")
            labels_list.append(labels)
            clean_features_list.append(item)

        batch = self.tokenizer.pad(
            clean_features_list,
            padding=True,
            return_tensors="pt",
        )

        batch_size = len(labels_list)
        max_seq_length = batch["input_ids"].shape[1]

        padded_labels = torch.full(
            (
                batch_size,
                max_seq_length,
                self.num_labels,
            ),
            -100.0,
            dtype=torch.float32,
        )

        for batch_index, labels in enumerate(labels_list):
            label_tensor = torch.tensor(
                labels,
                dtype=torch.float32,
            )

            sequence_length = label_tensor.shape[0]

            padded_labels[
                batch_index,
                :sequence_length,
                :,
            ] = label_tensor

        batch["labels"] = padded_labels

        return batch


# =============================================================================
# Model
# =============================================================================

class RobertaMultiLabelModel(nn.Module):
    """RoBERTa token classifier with BCE loss for independent feature labels."""

    def __init__(
        self,
        model_name: str,
        num_labels: int,
        id2label: Dict[int, str],
        label2id: Dict[str, int],
    ) -> None:
        super().__init__()

        self.model = AutoModelForTokenClassification.from_pretrained(
            model_name,
            num_labels=num_labels,
            id2label=id2label,
            label2id=label2id,
        )

        self.config = self.model.config

        self.loss_function = nn.BCEWithLogitsLoss(
            reduction="mean"
        )

    def forward(
        self,
        input_ids=None,
        attention_mask=None,
        labels=None,
        **kwargs,
    ):
        outputs = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            **kwargs,
        )

        logits = outputs.logits
        loss = None

        if labels is not None:
            valid_mask = labels[:, :, 0] != -100.0

            valid_logits = logits[valid_mask]
            valid_labels = labels[valid_mask]

            if valid_logits.numel() == 0:
                loss = logits.sum() * 0.0
            else:
                loss = self.loss_function(
                    valid_logits,
                    valid_labels,
                )

        return {
            "loss": loss,
            "logits": logits,
        }

    def save_pretrained(
        self,
        save_directory,
        **kwargs,
    ):
        return self.model.save_pretrained(
            save_directory,
            **kwargs,
        )


# =============================================================================
# Hierarchy matrices and array helpers
# =============================================================================

def build_hierarchy_expansion_matrix(
    prediction_labels: Sequence[str],
    full_labels: Sequence[str],
) -> np.ndarray:
    """
    Build a boolean matrix mapping neural outputs to complete feature sets.

    Shape:
        [number_of_prediction_features, number_of_full_features]
    """

    full_label2id = {
        label: index
        for index, label in enumerate(full_labels)
    }

    matrix = np.zeros(
        (len(prediction_labels), len(full_labels)),
        dtype=np.int8,
    )

    for prediction_id, feature in enumerate(prediction_labels):
        expanded = expand_feature_hierarchy({feature})

        for expanded_feature in expanded:
            full_id = full_label2id.get(expanded_feature)

            if full_id is None:
                raise RuntimeError(
                    "Hierarchy expansion produced a feature absent from the "
                    f"full vocabulary: {expanded_feature!r}."
                )

            matrix[prediction_id, full_id] = 1

    return matrix


def expand_binary_feature_matrix(
    independent_matrix: np.ndarray,
    hierarchy_matrix: np.ndarray,
) -> np.ndarray:
    """Expand [tokens, independent] binary values to [tokens, complete]."""

    expanded = independent_matrix.astype(np.int32) @ hierarchy_matrix.astype(
        np.int32
    )

    return (expanded > 0).astype(np.int32)


def extract_valid_token_arrays(
    logits: np.ndarray,
    labels: np.ndarray,
) -> Tuple[np.ndarray, np.ndarray]:
    """Return probabilities and true independent labels for supervised tokens."""

    valid_token_mask = labels[:, :, 0] != -100.0

    probabilities = sigmoid_numpy(logits)[
        valid_token_mask
    ]

    true_labels = labels[
        valid_token_mask
    ].astype(np.int32)

    return probabilities, true_labels


# =============================================================================
# Metrics and thresholds
# =============================================================================

def sigmoid_numpy(x: np.ndarray) -> np.ndarray:
    """Numerically stable sigmoid."""

    x = np.clip(x, -50.0, 50.0)
    return 1.0 / (1.0 + np.exp(-x))


def make_threshold_vector(
    prediction_labels: Sequence[str],
    thresholds: Dict[str, float],
) -> np.ndarray:
    """Return thresholds in neural-output column order."""

    return np.asarray(
        [
            float(
                thresholds.get(
                    label,
                    DEFAULT_PREDICTION_THRESHOLD,
                )
            )
            for label in prediction_labels
        ],
        dtype=np.float32,
    )


def threshold_probabilities(
    probabilities: np.ndarray,
    threshold_vector: np.ndarray,
) -> np.ndarray:
    """Apply one threshold per independent feature."""

    return (
        probabilities >= threshold_vector.reshape(1, -1)
    ).astype(np.int32)


def calculate_average_metrics(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    prefix: str = "",
) -> Dict[str, float]:
    """Calculate micro and macro precision/recall/F1."""

    if y_true.shape[0] == 0:
        return {
            f"{prefix}precision_micro": 0.0,
            f"{prefix}recall_micro": 0.0,
            f"{prefix}f1_micro": 0.0,
            f"{prefix}precision_macro": 0.0,
            f"{prefix}recall_macro": 0.0,
            f"{prefix}f1_macro": 0.0,
        }

    (
        precision_micro,
        recall_micro,
        f1_micro,
        _,
    ) = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="micro",
        zero_division=0,
    )

    (
        precision_macro,
        recall_macro,
        f1_macro,
        _,
    ) = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="macro",
        zero_division=0,
    )

    return {
        f"{prefix}precision_micro": float(precision_micro),
        f"{prefix}recall_micro": float(recall_micro),
        f"{prefix}f1_micro": float(f1_micro),
        f"{prefix}precision_macro": float(precision_macro),
        f"{prefix}recall_macro": float(recall_macro),
        f"{prefix}f1_macro": float(f1_macro),
    }


def calculate_hierarchical_metrics_from_probabilities(
    probabilities: np.ndarray,
    y_true_independent: np.ndarray,
    threshold_vector: np.ndarray,
    hierarchy_matrix: np.ndarray,
    y_true_full: Optional[np.ndarray] = None,
) -> Dict[str, float]:
    """
    Report both direct neural-output metrics and complete hierarchy metrics.

    Unprefixed metrics are the COMPLETE hierarchy metrics.  During ordinary
    training/validation, complete truth can be reconstructed from the
    independent targets.  For a genuinely held-out test corpus, ``y_true_full``
    may instead be supplied directly from the source annotations so an unseen
    direct independent label is not silently erased from the gold truth.
    """

    y_pred_independent = threshold_probabilities(
        probabilities,
        threshold_vector,
    )

    if y_true_full is None:
        y_true_full = expand_binary_feature_matrix(
            y_true_independent,
            hierarchy_matrix,
        )

    if y_true_full.shape[0] != y_true_independent.shape[0]:
        raise RuntimeError(
            "Complete and independent truth matrices contain different "
            f"numbers of supervised tokens: {y_true_full.shape[0]} vs "
            f"{y_true_independent.shape[0]}."
        )

    y_pred_full = expand_binary_feature_matrix(
        y_pred_independent,
        hierarchy_matrix,
    )

    metrics = calculate_average_metrics(
        y_true_full,
        y_pred_full,
        prefix="",
    )

    metrics.update(
        calculate_average_metrics(
            y_true_independent,
            y_pred_independent,
            prefix="direct_",
        )
    )

    return metrics


def make_compute_metrics(
    prediction_labels: Sequence[str],
    hierarchy_matrix: np.ndarray,
):
    """Create Trainer metrics using the fixed default 0.5 thresholds."""

    default_thresholds = np.full(
        len(prediction_labels),
        DEFAULT_PREDICTION_THRESHOLD,
        dtype=np.float32,
    )

    def compute_metrics(eval_prediction) -> Dict[str, float]:
        logits, labels = eval_prediction

        probabilities, y_true_independent = extract_valid_token_arrays(
            logits,
            labels,
        )

        return calculate_hierarchical_metrics_from_probabilities(
            probabilities=probabilities,
            y_true_independent=y_true_independent,
            threshold_vector=default_thresholds,
            hierarchy_matrix=hierarchy_matrix,
        )

    return compute_metrics


def build_threshold_grid() -> np.ndarray:
    """Build an inclusive, stable validation threshold search grid."""

    if THRESHOLD_STEP <= 0:
        raise ValueError("THRESHOLD_STEP must be > 0.")

    if not 0.0 < THRESHOLD_MIN < 1.0:
        raise ValueError("THRESHOLD_MIN must be between 0 and 1.")

    if not 0.0 < THRESHOLD_MAX < 1.0:
        raise ValueError("THRESHOLD_MAX must be between 0 and 1.")

    if THRESHOLD_MIN > THRESHOLD_MAX:
        raise ValueError("THRESHOLD_MIN cannot exceed THRESHOLD_MAX.")

    count = int(
        round(
            (THRESHOLD_MAX - THRESHOLD_MIN)
            / THRESHOLD_STEP
        )
    ) + 1

    return np.linspace(
        THRESHOLD_MIN,
        THRESHOLD_MAX,
        count,
        dtype=np.float64,
    )


def binary_metrics_for_column(
    y_true: np.ndarray,
    y_pred: np.ndarray,
) -> Tuple[float, float, float, int]:
    """Return binary precision, recall, F1 and positive support."""

    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true,
        y_pred,
        average="binary",
        zero_division=0,
    )

    support = int(y_true.sum())

    return (
        float(precision),
        float(recall),
        float(f1),
        support,
    )


def optimise_feature_thresholds(
    probabilities: np.ndarray,
    y_true_independent: np.ndarray,
    prediction_labels: Sequence[str],
) -> Tuple[Dict[str, float], Dict[str, Dict[str, float]]]:
    """
    Optimise one sigmoid threshold per independent feature on VALIDATION ONLY.

    Objective:
        maximise that feature's binary F1.

    Stability rules:
    - If validation has no positives or no negatives for a feature, keep 0.5.
    - If several thresholds tie for best F1, choose the one closest to 0.5.
      This avoids unnecessarily extreme thresholds for flat validation curves.
    """

    grid = build_threshold_grid()

    thresholds: Dict[str, float] = {}
    diagnostics: Dict[str, Dict[str, float]] = {}

    for label_id, feature in enumerate(prediction_labels):
        y_true = y_true_independent[:, label_id]
        probs = probabilities[:, label_id]

        positive_support = int(y_true.sum())
        negative_support = int((1 - y_true).sum())

        default_pred = (
            probs >= DEFAULT_PREDICTION_THRESHOLD
        ).astype(np.int32)

        (
            default_precision,
            default_recall,
            default_f1,
            _,
        ) = binary_metrics_for_column(
            y_true,
            default_pred,
        )

        if positive_support == 0 or negative_support == 0:
            best_threshold = DEFAULT_PREDICTION_THRESHOLD
        else:
            best_f1 = -1.0
            best_candidates: List[float] = []

            for threshold in grid:
                y_pred = (probs >= threshold).astype(np.int32)

                _, _, f1, _ = binary_metrics_for_column(
                    y_true,
                    y_pred,
                )

                if f1 > best_f1 + 1e-12:
                    best_f1 = f1
                    best_candidates = [float(threshold)]
                elif abs(f1 - best_f1) <= 1e-12:
                    best_candidates.append(float(threshold))

            best_threshold = min(
                best_candidates,
                key=lambda value: (
                    abs(value - DEFAULT_PREDICTION_THRESHOLD),
                    value,
                ),
            )

        best_pred = (
            probs >= best_threshold
        ).astype(np.int32)

        (
            best_precision,
            best_recall,
            best_f1,
            _,
        ) = binary_metrics_for_column(
            y_true,
            best_pred,
        )

        thresholds[feature] = float(best_threshold)

        diagnostics[feature] = {
            "threshold": float(best_threshold),
            "support": positive_support,
            "negative_support": negative_support,
            "precision_default": default_precision,
            "recall_default": default_recall,
            "f1_default": default_f1,
            "precision_optimised": best_precision,
            "recall_optimised": best_recall,
            "f1_optimised": best_f1,
            "f1_change": best_f1 - default_f1,
        }

    return thresholds, diagnostics


# =============================================================================
# Dataset diagnostics and validation
# =============================================================================

def count_feature_occurrences(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    sentence_indices: Sequence[int],
    independent_only: bool = False,
) -> Counter:
    """Count complete or independent positive labels in a split."""

    counts: Counter = Counter()

    for sentence_index in sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            if independent_only:
                features = get_independent_record_features(record)
            else:
                features = clean_features(record)

            for feature in features:
                counts[feature] += 1

    return counts


def count_empty_records(
    tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    sentence_indices: Sequence[int],
) -> int:
    """Count NOUN/PROPN records having no complete feature tags."""

    count = 0

    for sentence_index in sentence_indices:
        for record in tagged_records.get(sentence_index, {}).values():
            if not clean_features(record):
                count += 1

    return count


def verify_full_label_coverage(
    full_labels: Sequence[str],
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
) -> None:
    """Ensure validation contains no complete label unseen in training."""

    training_labels = set(full_labels)

    for split_name in ("validation",):
        tagged_records, sentence_indices = split_sources[split_name]
        observed: Set[str] = set()

        for sentence_index in sentence_indices:
            for record in tagged_records.get(sentence_index, {}).values():
                observed.update(clean_features(record))

        unknown = observed - training_labels

        if unknown:
            raise RuntimeError(
                f"{split_name} contains full labels unseen in training: "
                f"{sorted(unknown)}"
            )


def verify_prediction_label_coverage(
    prediction_labels: Sequence[str],
    split_sources: Dict[
        str, Tuple[Dict[int, Dict[int, Dict[str, Any]]], Sequence[int]]
    ],
) -> None:
    """Require every validation independent target to occur in training."""

    training_labels = set(prediction_labels)
    records, indices = split_sources["validation"]
    observed = {
        feature
        for sentence_index in indices
        for record in records.get(sentence_index, {}).values()
        for feature in get_independent_record_features(record)
    }
    unknown = observed - training_labels
    if unknown:
        raise RuntimeError(
            "Validation contains independent targets without a training "
            f"output head: {sorted(unknown)}"
        )


def verify_hierarchy_closure(
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
) -> None:
    """
    Ensure source feature sets already contain all ancestors required by the
    hierarchy. This prevents evaluation against inconsistent source targets.
    """

    problems: List[str] = []
    max_examples = 20

    for split_name in ("train", "validation"):
        tagged_records, sentence_indices = split_sources[split_name]
        problem_count = 0

        for sentence_index in sentence_indices:
            for token_id, record in tagged_records.get(
                sentence_index,
                {},
            ).items():
                features = clean_features(record)

                if not features:
                    continue

                missing = missing_hierarchy_features(features)

                if not missing:
                    continue

                problem_count += 1

                if len(problems) < max_examples:
                    problems.append(
                        f"{split_name}: sentence={sentence_index}, "
                        f"token={token_id}, "
                        f"form={record.get('form')!r}, "
                        f"missing={sorted(missing)}"
                    )

        if problem_count:
            print(
                f"Hierarchy closure problems in {split_name}: "
                f"{problem_count:,} token(s)"
            )

    if problems:
        example_text = "\n".join(
            f"  - {problem}"
            for problem in problems
        )

        raise RuntimeError(
            "The input dataset is not hierarchy-closed. Fix the source tags "
            "before training so deterministic reduction/expansion is exact.\n"
            f"Examples:\n{example_text}"
        )


def print_split_statistics(
    split_sources: Dict[
        str,
        Tuple[
            Dict[int, Dict[int, Dict[str, Any]]],
            Sequence[int],
        ],
    ],
) -> None:
    print("=" * 80)
    print("DATASET SPLIT")
    print("=" * 80)

    for split_name in ("train", "validation"):
        tagged_records, indices = split_sources[split_name]

        full_counts = count_feature_occurrences(
            tagged_records,
            indices,
            independent_only=False,
        )

        independent_counts = count_feature_occurrences(
            tagged_records,
            indices,
            independent_only=True,
        )

        empty_count = count_empty_records(
            tagged_records,
            indices,
        )

        noun_count = sum(
            len(tagged_records.get(index, {}))
            for index in indices
        )

        source_name = (
            "training file"
            if split_name in {"train", "validation"}
            else "test file"
        )

        print(
            f"{split_name:12s}: "
            f"{len(indices):,} sentences | "
            f"{noun_count:,} NOUN/PROPN tokens | "
            f"{sum(full_counts.values()):,} complete positives -> "
            f"{sum(independent_counts.values()):,} independent positives | "
            f"{empty_count:,} empty-feature tokens excluded | "
            f"source={source_name}"
        )

    print()


def print_prediction_label_statistics(
    prediction_labels: Sequence[str],
    full_labels: Sequence[str],
    train_tagged_records: Dict[int, Dict[int, Dict[str, Any]]],
    train_sentence_indices: Sequence[int],
) -> None:
    """Show which labels are neural outputs versus deterministic-only parents."""

    train_independent_counts = count_feature_occurrences(
        train_tagged_records,
        train_sentence_indices,
        independent_only=True,
    )

    prediction_set = set(prediction_labels)
    deterministic_only = [
        feature
        for feature in full_labels
        if feature not in prediction_set
    ]

    print("=" * 80)
    print("NEURAL OUTPUT FEATURES")
    print("=" * 80)
    print(
        f"Complete evaluation features: {len(full_labels)}"
    )
    print(
        f"Independent neural outputs: {len(prediction_labels)}"
    )
    print(
        f"Deterministic-only features in this training split: "
        f"{len(deterministic_only)}"
    )
    print()

    print(
        f"{'Feature':35s} "
        f"{'Independent train support':>26s}"
    )
    print("-" * 64)

    for feature in prediction_labels:
        print(
            f"{feature:35s} "
            f"{train_independent_counts[feature]:26d}"
        )

    if deterministic_only:
        print()
        print("Deterministic-only in this split:")

        for feature in deterministic_only:
            print(f"  - {feature}")

    print()


def make_json_serialisable(value: Any) -> Any:
    """Recursively convert NumPy scalars/arrays to ordinary JSON values."""

    if isinstance(value, dict):
        return {
            str(key): make_json_serialisable(item)
            for key, item in value.items()
        }

    if isinstance(value, (list, tuple)):
        return [
            make_json_serialisable(item)
            for item in value
        ]

    if isinstance(value, np.ndarray):
        return value.tolist()

    if isinstance(value, (np.floating, np.integer)):
        return value.item()

    return value


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    validate_feature_hierarchy()
    check_cuda()

    if not LEARNING_RATES or not PER_DEVICE_TRAIN_BATCH_SIZES or not EFFECTIVE_BATCH_SIZES:
        raise ValueError("All hyperparameter grid lists must be non-empty.")
    if any(lr <= 0 for lr in LEARNING_RATES):
        raise ValueError("Learning rates must be positive.")

    n_devices = torch.cuda.device_count()
    if n_devices < 1:
        raise RuntimeError("At least one CUDA device is required.")

    grid = []
    for lr, device_batch, effective_batch in product(
        LEARNING_RATES, PER_DEVICE_TRAIN_BATCH_SIZES, EFFECTIVE_BATCH_SIZES
    ):
        denominator = device_batch * n_devices
        if device_batch <= 0 or effective_batch <= 0 or effective_batch % denominator:
            raise ValueError(
                "Each effective batch size must be a positive multiple of "
                "per-device batch size times the number of CUDA devices: "
                f"device_batch={device_batch}, effective_batch={effective_batch}, "
                f"CUDA devices={n_devices}."
            )
        grid.append((lr, device_batch, effective_batch,
                     effective_batch // denominator))
    if len(grid) != len(set(grid)):
        raise ValueError("The hyperparameter grid contains duplicate configurations.")

    print("=" * 80)
    print("VALIDATION-ONLY HYPERPARAMETER GRID SEARCH")
    print("=" * 80)
    print(f"Configurations: {len(grid)} | fine-tuning seed: {TUNING_SEED}")
    print(f"CUDA devices: {n_devices}")
    print("Selection metric: hierarchy-expanded validation macro F1 at threshold 0.5")
    print("The official test corpus is not read during this search.\n")

    train_sentences = load_conllu(TRAIN_CONLLU_PATH)
    train_tagged_records = load_tagged_records(TRAIN_JSONL_PATH)
    validate_feature_switches(train_tagged_records)

    eligible_indices = get_eligible_sentence_indices(
        train_sentences, train_tagged_records
    )
    split = make_train_validation_split(eligible_indices, train_tagged_records)
    train_indices = split["train"]
    validation_indices = split["validation"]
    sources = {
        "train": (train_tagged_records, train_indices),
        "validation": (train_tagged_records, validation_indices),
    }
    split_document = {
        "split_unit": "sentence",
        "stratification": "iterative_multilabel_sentence_presence",
        "split_seed_requested": SPLIT_SEED,
        "split_seed_used": split["split_seed_used"],
        "split_attempt": split["attempt"],
        "validation_fraction": VALIDATION_FRACTION,
        "feature_switches": dict(sorted(FEATURE_SWITCHES.items())),
        "prevalence_error": split["prevalence_error"],
        "stratification_labels": split["stratification_labels"],
        "train_jsonl": str(TRAIN_JSONL_PATH),
        "train_conllu": str(TRAIN_CONLLU_PATH),
        "index_spaces": {"train": "training corpus", "validation": "training corpus"},
        "train": train_indices,
        "validation": validation_indices,
    }
    with SPLIT_PATH.open("w", encoding="utf-8") as handle:
        json.dump(make_json_serialisable(split_document), handle,
                  ensure_ascii=False, indent=2)

    verify_hierarchy_closure(sources)
    full_labels = build_full_label_vocabulary(train_tagged_records, train_indices)
    prediction_labels = build_prediction_label_vocabulary(
        train_tagged_records, train_indices
    )
    verify_full_label_coverage(full_labels, sources)
    verify_prediction_label_coverage(prediction_labels, sources)

    label2id = {label: index for index, label in enumerate(prediction_labels)}
    id2label = {index: label for label, index in label2id.items()}
    hierarchy_matrix = build_hierarchy_expansion_matrix(
        prediction_labels, full_labels
    )
    label_document = {
        "labels": prediction_labels,
        "label2id": label2id,
        "id2label": {str(key): value for key, value in id2label.items()},
        "prediction_labels": prediction_labels,
        "prediction_label2id": label2id,
        "full_labels": full_labels,
        "full_label2id": {label: index for index, label in enumerate(full_labels)},
        "feature_parents": {
            child: sorted(parents) for child, parents in sorted(FEATURE_PARENTS.items())
        },
        "target_representation": "per_token_independent_features",
        "split_unit": "sentence",
        "feature_switches": dict(sorted(FEATURE_SWITCHES.items())),
        "disabled_features": sorted(
            feature for feature, enabled in FEATURE_SWITCHES.items() if not enabled
        ),
    }
    with LABELS_PATH.open("w", encoding="utf-8") as handle:
        json.dump(label_document, handle, ensure_ascii=False, indent=2)

    print_split_statistics(sources)
    print_prediction_label_statistics(
        prediction_labels, full_labels, train_tagged_records, train_indices
    )

    tokenizer = AutoTokenizer.from_pretrained(
        MODEL_NAME, use_fast=True, add_prefix_space=True
    )
    train_dataset = SemanticFeatureDataset(
        sentences=train_sentences,
        sentence_indices=train_indices,
        tagged_records=train_tagged_records,
        tokenizer=tokenizer,
        label2id=label2id,
        max_length=MAX_LENGTH,
    )
    validation_dataset = SemanticFeatureDataset(
        sentences=train_sentences,
        sentence_indices=validation_indices,
        tagged_records=train_tagged_records,
        tokenizer=tokenizer,
        label2id=label2id,
        max_length=MAX_LENGTH,
    )
    collator = MultiLabelTokenCollator(
        tokenizer=tokenizer, num_labels=len(prediction_labels)
    )
    use_bf16 = torch.cuda.is_bf16_supported()
    results = []
    work_root = OUTPUT_DIR / "_grid_trainer_work"
    work_root.mkdir(parents=True, exist_ok=True)

    def save_results() -> None:
        # A partial result survives a later interrupted or out-of-memory trial.
        ranked = sorted(
            results,
            key=lambda row: (-row["validation_f1_macro_at_0_5"],
                             -row["validation_f1_micro_at_0_5"], row["trial"]),
        )
        document = {
            "model": MODEL_NAME,
            "selection_data": "validation_only",
            "official_test_evaluated": False,
            "selection_metric": "hierarchy_expanded_validation_f1_macro_at_0_5",
            "tie_breaker": "validation_f1_micro_at_0_5_then_grid_order",
            "training_seed": TUNING_SEED,
            "split_seed": split["split_seed_used"],
            "epochs": NUM_EPOCHS,
            "cuda_devices": n_devices,
            "feature_switches": dict(sorted(FEATURE_SWITCHES.items())),
            "grid_size": len(grid),
            "completed_trials": len(results),
            "best": ranked[0] if ranked else None,
            "results_ranked": ranked,
        }
        with GRID_RESULTS_PATH.open("w", encoding="utf-8") as handle:
            json.dump(make_json_serialisable(document), handle,
                      ensure_ascii=False, indent=2)
        columns = [
            "rank", "trial", "learning_rate", "per_device_train_batch_size",
            "gradient_accumulation_steps", "effective_batch_size",
            "training_seed", "best_epoch",
            "best_epoch_validation_f1_macro_at_0_5",
            "validation_f1_macro_at_0_5", "validation_f1_micro_at_0_5",
            "validation_f1_macro_calibrated_diagnostic",
            "validation_f1_micro_calibrated_diagnostic",
        ]
        with GRID_CSV_PATH.open("w", encoding="utf-8", newline="") as handle:
            writer = csv.DictWriter(handle, fieldnames=columns)
            writer.writeheader()
            for rank, row in enumerate(ranked, start=1):
                writer.writerow({name: rank if name == "rank" else row.get(name)
                                 for name in columns})

    for trial, (lr, device_batch, effective_batch, accumulation) in enumerate(
        grid, start=1
    ):
        print("\n" + "=" * 80)
        print(f"TRIAL {trial}/{len(grid)}: LR={lr:g}, device batch={device_batch}, "
              f"accumulation={accumulation}, effective batch={effective_batch}")
        print("=" * 80)
        set_seed(TUNING_SEED)
        work_dir = work_root / f"trial_{trial:02d}"
        if work_dir.exists():
            shutil.rmtree(work_dir)

        model = RobertaMultiLabelModel(
            model_name=MODEL_NAME,
            num_labels=len(prediction_labels),
            id2label=id2label,
            label2id=label2id,
        )
        args = TrainingArguments(
            output_dir=str(work_dir),
            learning_rate=lr,
            lr_scheduler_type=LEARNING_RATE_SCHEDULER,
            weight_decay=WEIGHT_DECAY,
            per_device_train_batch_size=device_batch,
            per_device_eval_batch_size=EVAL_BATCH_SIZE,
            gradient_accumulation_steps=accumulation,
            num_train_epochs=NUM_EPOCHS,
            eval_strategy=EVAL_STRATEGY,
            save_strategy="epoch",
            logging_strategy="steps",
            logging_steps=50,
            load_best_model_at_end=True,
            metric_for_best_model="f1_macro",
            greater_is_better=True,
            save_total_limit=2,
            bf16=use_bf16,
            fp16=not use_bf16,
            dataloader_num_workers=4,
            dataloader_pin_memory=True,
            optim="adamw_torch",
            report_to="none",
            seed=TUNING_SEED,
            data_seed=TUNING_SEED,
            remove_unused_columns=False,
            eval_accumulation_steps=16,
            warmup_steps = WARMUP_STEPS,
        )
        trainer = Trainer(
            model=model,
            args=args,
            train_dataset=train_dataset,
            eval_dataset=validation_dataset,
            processing_class=tokenizer,
            data_collator=collator,
            compute_metrics=make_compute_metrics(
                prediction_labels, hierarchy_matrix
            ),
        )
        trainer.train()
        validation_output = trainer.predict(
            validation_dataset, metric_key_prefix="validation"
        )
        probabilities, true_independent = extract_valid_token_arrays(
            validation_output.predictions, validation_output.label_ids
        )
        default_thresholds = np.full(
            len(prediction_labels), DEFAULT_PREDICTION_THRESHOLD,
            dtype=np.float32,
        )
        default_metrics = calculate_hierarchical_metrics_from_probabilities(
            probabilities=probabilities,
            y_true_independent=true_independent,
            threshold_vector=default_thresholds,
            hierarchy_matrix=hierarchy_matrix,
        )
        calibrated_thresholds, _ = optimise_feature_thresholds(
            probabilities=probabilities,
            y_true_independent=true_independent,
            prediction_labels=prediction_labels,
        )
        calibrated_metrics = calculate_hierarchical_metrics_from_probabilities(
            probabilities=probabilities,
            y_true_independent=true_independent,
            threshold_vector=make_threshold_vector(
                prediction_labels, calibrated_thresholds
            ),
            hierarchy_matrix=hierarchy_matrix,
        )
        best_metric = trainer.state.best_metric
        best_checkpoint = trainer.state.best_model_checkpoint
        best_epoch = None
        if best_checkpoint:
            for entry in trainer.state.log_history:
                if "eval_f1_macro" in entry and "step" in entry:
                    # The best checkpoint's step is encoded in its directory.
                    if best_checkpoint.endswith(f"checkpoint-{entry['step']}"):
                        best_epoch = entry.get("epoch")
                        break

        row = {
            "trial": trial,
            "learning_rate": lr,
            "per_device_train_batch_size": device_batch,
            "gradient_accumulation_steps": accumulation,
            "effective_batch_size": effective_batch,
            "training_seed": TUNING_SEED,
            "best_epoch": best_epoch,
            "best_epoch_validation_f1_macro_at_0_5": best_metric,
            "validation_f1_macro_at_0_5": default_metrics["f1_macro"],
            "validation_f1_micro_at_0_5": default_metrics["f1_micro"],
            "validation_f1_macro_calibrated_diagnostic": calibrated_metrics["f1_macro"],
            "validation_f1_micro_calibrated_diagnostic": calibrated_metrics["f1_micro"],
            "validation_metrics_at_0_5": default_metrics,
            "validation_metrics_calibrated_diagnostic": calibrated_metrics,
            "calibrated_thresholds_diagnostic": calibrated_thresholds,
        }
        results.append(row)
        save_results()
        print(f"Validation macro F1 @ 0.5: {row['validation_f1_macro_at_0_5']:.4f}")
        print(f"Validation micro F1 @ 0.5: {row['validation_f1_micro_at_0_5']:.4f}")
        print(f"Results saved: {GRID_RESULTS_PATH.resolve()}")

        del validation_output, trainer, model
        gc.collect()
        torch.cuda.empty_cache()
        if work_dir.exists():
            shutil.rmtree(work_dir)

    if work_root.exists() and not any(work_root.iterdir()):
        work_root.rmdir()

    print("\n" + "=" * 80)
    print("GRID SEARCH RANKING (VALIDATION ONLY)")
    print("=" * 80)
    ranked = sorted(
        results,
        key=lambda row: (-row["validation_f1_macro_at_0_5"],
                         -row["validation_f1_micro_at_0_5"], row["trial"]),
    )
    print(f"{'Rank':>4} {'LR':>10} {'Device':>7} {'Accum':>7} "
          f"{'Effective':>9} {'Macro F1':>10} {'Micro F1':>10}")
    for rank, row in enumerate(ranked, start=1):
        print(f"{rank:4d} {row['learning_rate']:10.1e} "
              f"{row['per_device_train_batch_size']:7d} "
              f"{row['gradient_accumulation_steps']:7d} "
              f"{row['effective_batch_size']:9d} "
              f"{row['validation_f1_macro_at_0_5']:10.4f} "
              f"{row['validation_f1_micro_at_0_5']:10.4f}")
    print(f"\nBest candidate: LR={ranked[0]['learning_rate']:g}, "
          f"device batch={ranked[0]['per_device_train_batch_size']}, "
          f"accumulation={ranked[0]['gradient_accumulation_steps']}, "
          f"effective batch={ranked[0]['effective_batch_size']}")
    print("Use these settings for the separate 30-seed experiment; "
          "this single-seed ranking is provisional.")
    print(f"JSON: {GRID_RESULTS_PATH.resolve()}")
    print(f"CSV:  {GRID_CSV_PATH.resolve()}")


if __name__ == "__main__":
    main()

================================================================================
CUDA
================================================================================
PyTorch version: 2.13.0+cu130
CUDA available: True
CUDA runtime: 13.0
GPU: NVIDIA GeForce RTX 5070 Ti
VRAM: 15.92 GiB

================================================================================
VALIDATION-ONLY HYPERPARAMETER GRID SEARCH
================================================================================
Configurations: 16 | fine-tuning seed: 11
CUDA devices: 1
Selection metric: hierarchy-expanded validation macro F1 at threshold 0.5
The official test corpus is not read during this search.

================================================================================
FEATURE SWITCHES
================================================================================
Disabled features: Rigidity, Shape, State, State_of_Matter
All unlisted features are enabled.


Sentence-level multilabel-stratified train/validation split:
  Eligible training sentences : 11,198
  Target validation sentences : 2,240
  Actual validation sentences : 2,313
  Training sentences retained : 8,885
  Split seed used             : 42
  Stratification labels       : 37
  Coverage-rejected attempts  : 0
  Mean relative prevalence error: 0.008441

Feature                              All sent.      Train      Valid    Valid %
--------------------------------------------------------------------------------
Abstract                                  4469       3575        894      0.200
Animal                                     621        497        124      0.200
Animate                                     52         42         10      0.192
Artefact                                  1778       1422        356      0.200
Body_Part                                  265        212         53      0.200
Comestible                                 534        427        107      0.200
Communication                             1984       1587        397      0.200
Currency                                   197        158         39      0.198
Duration                                  1338       1070        268      0.200
Elongated                                  649        519        130      0.200
Eventive                                  3749       2999        750      0.200
Feminine                                   733        586        147      0.201
Fluid                                       87         70         17      0.195
Garment                                     62         50         12      0.194
Inanimate                                 4282       3425        857      0.200
Internal_Control                           107         86         21      0.196
Language                                    27         22          5      0.185
Location                                  3232       2585        647      0.200
Machine                                    694        555        139      0.200
Masculine                                 1829       1463        366      0.200
Natural                                    326        261         65      0.199
Natural_Force                              142        114         28      0.197
Non_Rigid                                 1200        960        240      0.200
Organisation                              3003       2402        601      0.200
Plant                                       66         53         13      0.197
Point_in_Time                             1211        969        242      0.200
Pointy                                      82         66         16      0.195
Question                                   161        129         32      0.199
Rigid                                     1965       1572        393      0.200
Solid                                     4618       3694        924      0.200
Sound                                      187        150         37      0.198
Statement                                 1115        892        223      0.200
Substance                                  826        661        165      0.200
Time                                        81         65         16      0.198
Unspecified_Gender_or_Neuter              2592       2074        518      0.200
Vehicle                                    344        275         69      0.201
Web_Location                               252        202         50      0.198

Actual validation sentence fraction: 0.2066

================================================================================
DATASET SPLIT
================================================================================
train       : 8,885 sentences | 37,581 NOUN/PROPN tokens | 124,956 complete positives -> 54,319 independent positives | 2,686 empty-feature tokens excluded | source=training file
validation  : 2,313 sentences | 9,408 NOUN/PROPN tokens | 31,274 complete positives -> 13,650 independent positives | 675 empty-feature tokens excluded | source=training file

================================================================================
NEURAL OUTPUT FEATURES
================================================================================
Complete evaluation features: 39
Independent neural outputs: 37
Deterministic-only features in this training split: 2

Feature                              Independent train support
----------------------------------------------------------------
Abstract                                                  5754
Animal                                                     691
Animate                                                     46
Artefact                                                  1866
Body_Part                                                  318
Comestible                                                 671
Communication                                             2041
Currency                                                   179
Duration                                                  1393
Elongated                                                  632
Eventive                                                  4258
Feminine                                                   867
Fluid                                                       84
Garment                                                     60
Inanimate                                                 5851
Internal_Control                                            91
Language                                                    23
Location                                                  4733
Machine                                                    738
Masculine                                                 2684
Natural                                                    307
Natural_Force                                              130
Non_Rigid                                                 1378
Organisation                                              4425
Plant                                                       68
Point_in_Time                                             1257
Pointy                                                      78
Question                                                   130
Rigid                                                     2165
Solid                                                     5807
Sound                                                      169
Statement                                                 1038
Substance                                                  913
Time                                                        67
Unspecified_Gender_or_Neuter                              2826
Vehicle                                                    359
Web_Location                                               222

Deterministic-only in this split:
  - Concrete
  - Human


================================================================================
TRIAL 1/16: LR=1.5e-05, device batch=4, accumulation=4, effective batch=16
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 975.97it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8683
Validation micro F1 @ 0.5: 0.9280
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 2/16: LR=1.5e-05, device batch=8, accumulation=2, effective batch=16
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 911.55it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8725
Validation micro F1 @ 0.5: 0.9306
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 3/16: LR=2e-05, device batch=4, accumulation=4, effective batch=16
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 929.22it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8835
Validation micro F1 @ 0.5: 0.9319
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 4/16: LR=2e-05, device batch=8, accumulation=2, effective batch=16
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 870.74it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8814
Validation micro F1 @ 0.5: 0.9337
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 5/16: LR=2.5e-05, device batch=4, accumulation=4, effective batch=16
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 903.94it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8834
Validation micro F1 @ 0.5: 0.9336
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 6/16: LR=2.5e-05, device batch=8, accumulation=2, effective batch=16
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 879.35it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8894
Validation micro F1 @ 0.5: 0.9357
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 7/16: LR=3e-05, device batch=4, accumulation=4, effective batch=16
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 906.19it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8960
Validation micro F1 @ 0.5: 0.9355
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 8/16: LR=3e-05, device batch=8, accumulation=2, effective batch=16
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 936.07it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8948
Validation micro F1 @ 0.5: 0.9371
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 9/16: LR=3.5e-05, device batch=4, accumulation=4, effective batch=16
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 982.37it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.9020
Validation micro F1 @ 0.5: 0.9383
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 10/16: LR=3.5e-05, device batch=8, accumulation=2, effective batch=16
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 961.81it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8954
Validation micro F1 @ 0.5: 0.9375
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 11/16: LR=4e-05, device batch=4, accumulation=4, effective batch=16
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 992.34it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.9048
Validation micro F1 @ 0.5: 0.9381
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 12/16: LR=4e-05, device batch=8, accumulation=2, effective batch=16
================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1012.80it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.9015
Validation micro F1 @ 0.5: 0.9388
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 13/16: LR=4.5e-05, device batch=4, accumulation=4, effective batch=16
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 942.88it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.9032
Validation micro F1 @ 0.5: 0.9378
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 14/16: LR=4.5e-05, device batch=8, accumulation=2, effective batch=16
================================================================================

Loading weights: 100%|██████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 1007.99it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.9012
Validation micro F1 @ 0.5: 0.9352
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 15/16: LR=5e-05, device batch=4, accumulation=4, effective batch=16
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 997.87it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8973
Validation micro F1 @ 0.5: 0.9365
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
TRIAL 16/16: LR=5e-05, device batch=8, accumulation=2, effective batch=16
================================================================================

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:00<00:00, 975.58it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
classifier.bias           | MISSING    |
classifier.weight         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Validation macro F1 @ 0.5: 0.8968
Validation micro F1 @ 0.5: 0.9330
Results saved: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json

================================================================================
GRID SEARCH RANKING (VALIDATION ONLY)
================================================================================
Rank         LR  Device   Accum Effective   Macro F1   Micro F1
   1    4.0e-05       4       4        16     0.9048     0.9381
   2    4.5e-05       4       4        16     0.9032     0.9378
   3    3.5e-05       4       4        16     0.9020     0.9383
   4    4.0e-05       8       2        16     0.9015     0.9388
   5    4.5e-05       8       2        16     0.9012     0.9352
   6    5.0e-05       4       4        16     0.8973     0.9365
   7    5.0e-05       8       2        16     0.8968     0.9330
   8    3.0e-05       4       4        16     0.8960     0.9355
   9    3.5e-05       8       2        16     0.8954     0.9375
  10    3.0e-05       8       2        16     0.8948     0.9371
  11    2.5e-05       8       2        16     0.8894     0.9357
  12    2.0e-05       4       4        16     0.8835     0.9319
  13    2.5e-05       4       4        16     0.8834     0.9336
  14    2.0e-05       8       2        16     0.8814     0.9337
  15    1.5e-05       8       2        16     0.8725     0.9306
  16    1.5e-05       4       4        16     0.8683     0.9280

Best candidate: LR=4e-05, device batch=4, accumulation=4, effective batch=16
Use these settings for the separate 30-seed experiment; this single-seed ranking is provisional.
JSON: /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.json
CSV:  /home/mark/verbnet-roberta/models/roberta_semantic_features_grid_search/hyperparameter_grid_results.csv

<h1>Inference</h1>

In [48]:
#!/usr/bin/env python3
"""
Inference script for the fine-tuned RoBERTa semantic-feature tagger.

Compatible with Python 3.9.21.

The script:

1. Loads the saved RoBERTa model.
2. Loads the independent prediction labels from semantic_features.json.
3. Loads the validation-calibrated per-feature thresholds from
   prediction_thresholds.json.
4. Uses spaCy to identify NOUN and PROPN tokens in arbitrary text.
5. Predicts independent semantic features for those tokens.
6. Reconstructs inherited semantic features deterministically using the
   saved feature hierarchy.
7. Prints the tagged sentences.
8. Writes one JSONL record per tagged NOUN/PROPN token.

No input() call is used. Put the text to tag directly in SENTENCES.

Requirements:

    python -m pip install torch transformers spacy safetensors

Install the spaCy English model if necessary:

    python -m spacy download en_core_web_sm
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, Iterable, List, Set

import spacy
import torch

from safetensors.torch import load_file as load_safetensors_file
from transformers import (
    AutoModelForTokenClassification,
    AutoTokenizer,
)


# =============================================================================
# Configuration
# =============================================================================

# The training script saves the first predeclared run here after Trainer has
# restored that run's best validation checkpoint.
MODEL_DIR = Path(
    "../models/roberta_semantic_features/reference_model"
)

# Needed to reconstruct the architecture when Trainer saved the custom wrapper's
# state_dict rather than a directly reloadable Hugging Face model.
BASE_MODEL_NAME = "FacebookAI/roberta-large"

LABELS_PATH = MODEL_DIR / "semantic_features.json"
THRESHOLDS_PATH = MODEL_DIR / "prediction_thresholds.json"

SPACY_MODEL = "en_core_web_sm"

MAX_LENGTH = 256

TARGET_POS = {
    "NOUN",
    "PROPN",
    "PRON",
}

OUTPUT_JSONL = Path("tagged_sentences.jsonl")

# Include the neural-output probabilities in the JSONL output.
INCLUDE_PROBABILITIES = True


# =============================================================================
# Text to tag
# =============================================================================

SENTENCES = """
The old dog slept beside the fireplace.
Microsoft opened a new office in London last year.
The committee discussed the proposal for three hours.
A sharp knife was lying on the wooden table.
The water flowed through the valley.
I poured the water down the drain.
John coiled the wire around the pole.
The snake wound itself around the tree branch.
Steam erupted from the volcanic vents.
I need to buy some orange juice at the supermarket tomorrow.
Pour some olive oil into a small pan before frying the fish.
I am looking forward to attending the party tonight.
Our trip to New York was a lot of fun!
London and Paris have signed a new agreement for closer economic relations.
I read the old diary with difficulty. The ink was smudged in places, making the handwriting hard to decypher.
Harriet prodded the bug with the tip of a rolled-up newspaper.
I know that the Earth orbits the Sun.
John ate the pasta.
John ate the milk.
The ATM ate my bank card.
The cheese smells.
The skunk smells.
The skunk smells the cheese.
The book is in the library.
John gave Mary a present.
John gave a chicken to Mary.
Mary unwrapped her present.
"""

# SENTENCES = """
# John ate the apple.
# John ate.
# John ate from the bowl.
# John ate off the plate.
# John ate out of the box.
# John ate at the cake.
# They ate of the fruit.
# John ate the meat off the bone.
# She ate the berries from the bush.
# He ate the cereal out of the box.
# The goats ate the field bare.
# The children ate the cupboard bare.
# They ate the plate clean.
# John ate himself sick.
# John ate himself full.
# John ate himself into a food coma.
# John ate himself to death.
# The children ate us out of food.
# The guests ate us out of house and home.
# The goats ate the hedge down to stubs.
# He ate the apple down to the core.
# She ate her way through the buffet.
# The caterpillar ate its way through the leaf.
# The caterpillar ate a hole through the leaf.
# The moths ate holes in the jumper.
# This bread eats easily.
# """

# SENTENCES = """
# Mary ate the sandwich.
# The child ate the banana.
# David ate the bread.
# The dog ate the biscuit.
# Sarah ate the carrot.
# The horse ate the apple.
# The students ate the pizza.
# The rabbit ate the lettuce.
# The farmer ate the potato.
# The bear ate the fish.
# The cat ate the chicken.
# The elephant ate the leaves.
# The mouse ate the cheese.
# The woman ate the rice.
# The boy ate the orange.
# The cow ate the grass.
# The monkey ate the mango.
# The wolf ate the meat.
# The girl ate the chocolate.
# The deer ate the berries.
# The chef ate the pasta.
# The goat ate the cabbage.
# The fox ate the egg.
# The duck ate the corn.
# The tourist ate the noodles.
# The squirrel ate the seeds.
# The pig ate the food.
# The lion ate the steak.
# The worker ate the cake.
# The chimpanzee ate the fruit.
# """

# SENTENCES = """
# Susan talked with Rachel.
# David talked with Michael.
# Sarah talked with Emma.
# James talked with Robert.
# Maria talked with Anna.
# Peter talked with Thomas.
# Linda talked with Helen.
# Daniel talked with Sophie.
# Alice talked with George.
# Matthew talked with Laura.
# The teacher talked with the student.
# The doctor talked with the patient.
# The mother talked with the child.
# The father talked with the daughter.
# The boy talked with the girl.
# The woman talked with the man.
# The nurse talked with the surgeon.
# The farmer talked with the neighbour.
# The lawyer talked with the client.
# The manager talked with the employee.
# The professor talked with the researcher.
# The journalist talked with the politician.
# The customer talked with the cashier.
# The passenger talked with the driver.
# The officer talked with the witness.
# The chef talked with the waiter.
# The tourist talked with the guide.
# The athlete talked with the coach.
# The singer talked with the musician.
# The actor talked with the director.
# The scientist talked with the engineer.
# The librarian talked with the reader.
# The student talked with the lecturer.
# The worker talked with the supervisor.
# The shopper talked with the assistant.
# The mechanic talked with the owner.
# The neighbour talked with the visitor.
# The parent talked with the teenager.
# The grandmother talked with the grandson.
# The sister talked with the brother.
# The bride talked with the groom.
# The captain talked with the sailor.
# The judge talked with the lawyer.
# The dentist talked with the receptionist.
# The baker talked with the customer.
# The pilot talked with the passenger.
# The doctor talked with the nurse.
# The child talked with the teacher.
# The employee talked with the manager.
# The researcher talked with the professor.
# """

# SENTENCES = """
# Allison poked the cloth with the needle.
# David poked the balloon with the pin.
# Sarah poked the soil with the stick.
# James poked the cake with the fork.
# Maria poked the cushion with the pencil.
# Peter poked the sand with the rod.
# Linda poked the fabric with the skewer.
# Daniel poked the dough with the spoon.
# Alice poked the sponge with the probe.
# Matthew poked the paper with the pen.
# The child poked the puddle with the stick.
# The doctor poked the skin with the needle.
# The baker poked the pastry with the fork.
# The gardener poked the earth with the trowel.
# The student poked the clay with the pencil.
# The farmer poked the hay with the pole.
# The chef poked the potato with the skewer.
# The tailor poked the cloth with the pin.
# The scientist poked the sample with the probe.
# The mechanic poked the rubber with the screwdriver.
# The boy poked the mud with the stick.
# The girl poked the balloon with the pencil.
# The woman poked the cushion with the needle.
# The man poked the mattress with the rod.
# The nurse poked the arm with the needle.
# The artist poked the canvas with the stylus.
# The potter poked the clay with the tool.
# The cook poked the meat with the fork.
# The camper poked the fire with the stick.
# The fisherman poked the bait with the hook.
# The worker poked the foam with the rod.
# The researcher poked the tissue with the probe.
# The tailor poked the leather with the awl.
# The child poked the jelly with the spoon.
# The baker poked the bread with the skewer.
# The gardener poked the compost with the fork.
# The teacher poked the model with the pointer.
# The sculptor poked the wax with the stylus.
# The technician poked the membrane with the probe.
# The farmer poked the ground with the pole.
# The chef poked the sausage with the fork.
# The camper poked the embers with the stick.
# The student poked the cork with the pencil.
# The mechanic poked the gasket with the screwdriver.
# The scientist poked the gel with the probe.
# The tailor poked the felt with the needle.
# The cook poked the dumpling with the skewer.
# The gardener poked the moss with the stick.
# The nurse poked the finger with the lancet.
# The artist poked the plaster with the stylus.
# """

# =============================================================================
# General helpers
# =============================================================================

def load_json(path: Path) -> Dict[str, Any]:
    """Load a JSON document."""

    if not path.exists():
        raise FileNotFoundError(
            f"Could not find required file:\n{path.resolve()}"
        )

    with path.open("r", encoding="utf-8") as handle:
        document = json.load(handle)

    if not isinstance(document, dict):
        raise ValueError(
            f"Expected a JSON object in:\n{path.resolve()}"
        )

    return document


# =============================================================================
# Load saved label information
# =============================================================================

def load_label_information() -> Dict[str, Any]:
    """
    Load the neural-output vocabulary and hierarchy metadata.

    semantic_features.json contains separate vocabularies for:

        prediction_labels
            Independent features directly predicted by the neural model.

        full_labels
            Complete features used after deterministic hierarchy expansion.
    """

    document = load_json(LABELS_PATH)

    prediction_labels = document.get("prediction_labels")

    # Backwards-compatible fallback.
    if prediction_labels is None:
        prediction_labels = document.get("labels")

    if not isinstance(prediction_labels, list):
        raise ValueError(
            "semantic_features.json does not contain prediction_labels."
        )

    prediction_labels = [
        str(feature)
        for feature in prediction_labels
    ]

    full_labels = document.get("full_labels")

    if not isinstance(full_labels, list):
        raise ValueError(
            "semantic_features.json does not contain full_labels."
        )

    full_labels = [
        str(feature)
        for feature in full_labels
    ]

    raw_feature_parents = document.get("feature_parents")

    if not isinstance(raw_feature_parents, dict):
        raise ValueError(
            "semantic_features.json does not contain feature_parents."
        )

    feature_parents: Dict[str, Set[str]] = {}

    for child, parents in raw_feature_parents.items():

        if not isinstance(parents, list):
            raise ValueError(
                "Invalid feature hierarchy entry for "
                f"{child!r}: expected a list."
            )

        feature_parents[str(child)] = {
            str(parent)
            for parent in parents
        }

    raw_switches = document.get(
        "feature_switches",
        {},
    )

    if not isinstance(raw_switches, dict):
        raise ValueError(
            "feature_switches must be a JSON object."
        )

    feature_switches = {
        str(feature): bool(enabled)
        for feature, enabled in raw_switches.items()
    }

    return {
        "document": document,
        "prediction_labels": prediction_labels,
        "full_labels": full_labels,
        "feature_parents": feature_parents,
        "feature_switches": feature_switches,
    }


# =============================================================================
# Thresholds
# =============================================================================

def load_prediction_thresholds(
    prediction_labels: List[str],
) -> Dict[str, float]:
    """
    Load validation-calibrated thresholds.

    Every neural output should have its own threshold.
    """

    document = load_json(THRESHOLDS_PATH)

    raw_thresholds = document.get("thresholds")

    if not isinstance(raw_thresholds, dict):
        raise ValueError(
            "prediction_thresholds.json does not contain "
            "a 'thresholds' object."
        )

    thresholds: Dict[str, float] = {}

    missing: List[str] = []

    for feature in prediction_labels:

        if feature not in raw_thresholds:
            missing.append(feature)
            continue

        threshold = float(raw_thresholds[feature])

        if not 0.0 <= threshold <= 1.0:
            raise ValueError(
                f"Invalid threshold for {feature!r}: "
                f"{threshold}"
            )

        thresholds[feature] = threshold

    if missing:
        raise ValueError(
            "No calibrated threshold was found for the following "
            "prediction labels:\n"
            + ", ".join(missing)
        )

    return thresholds


# =============================================================================
# Feature hierarchy
# =============================================================================

def make_hierarchy_expander(
    feature_parents: Dict[str, Set[str]],
    feature_switches: Dict[str, bool],
    full_labels: List[str],
):
    """
    Construct hierarchy-expansion functions matching the training script.

    Disabled intermediate nodes are traversed even though they are not returned.

    For example, if an intermediate hierarchy feature were disabled:

        Child -> DisabledParent -> Grandparent

    Child can still inherit Grandparent.
    """

    full_label_set = set(full_labels)

    def is_feature_enabled(feature: str) -> bool:
        return bool(
            feature_switches.get(
                feature,
                True,
            )
        )

    @lru_cache(maxsize=None)
    def get_feature_ancestors(
        feature: str,
    ) -> frozenset:

        ancestors: Set[str] = set()

        for parent in feature_parents.get(
            feature,
            set(),
        ):

            if is_feature_enabled(parent):
                ancestors.add(parent)

            # Always traverse through the node, even when the node itself
            # has been disabled.
            ancestors.update(
                get_feature_ancestors(parent)
            )

        return frozenset(ancestors)

    def expand_feature_hierarchy(
        features: Iterable[str],
    ) -> Set[str]:

        expanded = {
            feature
            for feature in features
            if is_feature_enabled(feature)
        }

        for feature in list(expanded):
            expanded.update(
                get_feature_ancestors(feature)
            )

        # The training-derived full vocabulary determines which features are
        # legitimate final output labels.
        expanded.intersection_update(
            full_label_set
        )

        return expanded

    return expand_feature_hierarchy


# =============================================================================
# Model loading
# =============================================================================

def load_saved_state_dict(
    model_dir: Path,
) -> Dict[str, torch.Tensor]:
    """
    Load weights saved by Hugging Face Trainer.

    The custom training model wraps AutoModelForTokenClassification inside
    self.model. Depending on the Transformers version, Trainer.save_model()
    may therefore save keys such as:

        model.roberta....
        model.classifier....

    rather than:

        roberta....
        classifier....

    This loader handles either representation.
    """

    safetensors_path = (
        model_dir / "model.safetensors"
    )

    pytorch_path = (
        model_dir / "pytorch_model.bin"
    )

    if safetensors_path.exists():

        state_dict = load_safetensors_file(
            str(safetensors_path),
            device="cpu",
        )

    elif pytorch_path.exists():

        loaded = torch.load(
            str(pytorch_path),
            map_location="cpu",
        )

        if (
            isinstance(loaded, dict)
            and "state_dict" in loaded
            and isinstance(
                loaded["state_dict"],
                dict,
            )
        ):
            state_dict = loaded["state_dict"]
        else:
            state_dict = loaded

    else:
        raise FileNotFoundError(
            "Could not find model weights in:\n"
            f"{model_dir.resolve()}\n\n"
            "Expected either:\n"
            "  model.safetensors\n"
            "or:\n"
            "  pytorch_model.bin"
        )

    if not isinstance(state_dict, dict):
        raise RuntimeError(
            "Saved model weights are not a state_dict."
        )

    return state_dict


def normalise_state_dict_keys(
    state_dict: Dict[str, torch.Tensor],
) -> Dict[str, torch.Tensor]:
    """
    Remove wrapper prefixes introduced by the custom training model.
    """

    normalised: Dict[str, torch.Tensor] = {}

    for key, value in state_dict.items():

        new_key = key

        # Common distributed/compiled-model prefixes.
        while new_key.startswith("module."):
            new_key = new_key[len("module."):]

        while new_key.startswith("_orig_mod."):
            new_key = new_key[len("_orig_mod."):]

        # RobertaMultiLabelModel stores the Hugging Face model in self.model.
        if new_key.startswith("model."):
            new_key = new_key[len("model."):]

        normalised[new_key] = value

    return normalised


def load_model(
    prediction_labels: List[str],
    device: torch.device,
):
    """
    Recreate AutoModelForTokenClassification and load the fine-tuned weights.
    """

    label2id = {
        label: index
        for index, label in enumerate(
            prediction_labels
        )
    }

    id2label = {
        index: label
        for label, index in label2id.items()
    }

    print("Loading RoBERTa architecture...")

    model = (
        AutoModelForTokenClassification
        .from_pretrained(
            BASE_MODEL_NAME,
            num_labels=len(prediction_labels),
            id2label=id2label,
            label2id=label2id,

            # The original pretrained model does not have our custom
            # multi-label classifier dimensions.
            ignore_mismatched_sizes=True,
        )
    )

    print("Loading fine-tuned weights...")

    state_dict = load_saved_state_dict(
        MODEL_DIR
    )

    state_dict = normalise_state_dict_keys(
        state_dict
    )

    incompatible = model.load_state_dict(
        state_dict,
        strict=False,
    )

    missing_keys = list(
        incompatible.missing_keys
    )

    unexpected_keys = list(
        incompatible.unexpected_keys
    )

    if missing_keys or unexpected_keys:

        message = []

        if missing_keys:
            message.append(
                "Missing keys:\n  "
                + "\n  ".join(missing_keys)
            )

        if unexpected_keys:
            message.append(
                "Unexpected keys:\n  "
                + "\n  ".join(unexpected_keys)
            )

        raise RuntimeError(
            "The saved weights do not exactly match the "
            "reconstructed RoBERTa model.\n\n"
            + "\n\n".join(message)
        )

    # Ensure the label mapping reflects semantic_features.json rather than any
    # mapping inherited from the original Facebook checkpoint.
    model.config.label2id = label2id
    model.config.id2label = id2label

    model.to(device)
    model.eval()

    return model


# =============================================================================
# Inference
# =============================================================================

def predict_sentence(
    sentence: Any,
    sentence_index: int,
    model: Any,
    tokenizer: Any,
    prediction_labels: List[str],
    thresholds: Dict[str, float],
    expand_feature_hierarchy: Any,
    device: torch.device,
) -> List[Dict[str, Any]]:
    """
    Predict semantic features for NOUN and PROPN tokens in one spaCy sentence.
    """

    tokens = list(sentence)

    if not tokens:
        return []

    words = [
        token.text
        for token in tokens
    ]

    encoding = tokenizer(
        words,
        is_split_into_words=True,
        truncation=True,
        max_length=MAX_LENGTH,
        add_special_tokens=True,
        return_tensors="pt",
    )

    # word_ids maps RoBERTa subwords back to the original spaCy tokens.
    word_ids = encoding.word_ids(
        batch_index=0
    )

    first_subword_position: Dict[int, int] = {}

    for sequence_position, word_id in enumerate(
        word_ids
    ):

        if word_id is None:
            continue

        if word_id not in first_subword_position:
            first_subword_position[
                word_id
            ] = sequence_position

    encoded_word_count = (
        max(first_subword_position) + 1
        if first_subword_position
        else 0
    )

    if encoded_word_count < len(words):

        print(
            f"Warning: sentence {sentence_index + 1} "
            f"was truncated at MAX_LENGTH={MAX_LENGTH}. "
            f"Only {encoded_word_count}/{len(words)} source "
            "tokens were encoded."
        )

    model_inputs = {
        key: value.to(device)
        for key, value in encoding.items()
    }

    with torch.inference_mode():

        outputs = model(
            **model_inputs
        )

        probabilities = torch.sigmoid(
            outputs.logits
        )[0].float().cpu()

    records: List[Dict[str, Any]] = []

    for word_index, token in enumerate(tokens):

        if token.pos_ not in TARGET_POS:
            continue

        sequence_position = (
            first_subword_position.get(
                word_index
            )
        )

        # The token was probably removed by truncation.
        if sequence_position is None:
            continue

        token_probabilities = (
            probabilities[
                sequence_position
            ]
        )

        independent_features: List[str] = []

        probability_document: Dict[
            str,
            float,
        ] = {}

        for label_id, feature in enumerate(
            prediction_labels
        ):

            probability = float(
                token_probabilities[
                    label_id
                ].item()
            )

            threshold = thresholds[
                feature
            ]

            if probability >= threshold:

                independent_features.append(
                    feature
                )

                probability_document[
                    feature
                ] = probability

        independent_features.sort()

        complete_features = sorted(
            expand_feature_hierarchy(
                independent_features
            )
        )

        record: Dict[str, Any] = {
            "sentence_index": sentence_index,
            "token_id": word_index + 1,
            "form": token.text,
            "lemma": token.lemma_,
            "upos": token.pos_,
            "features": complete_features,
            "independent_features": (
                independent_features
            ),
        }

        if INCLUDE_PROBABILITIES:

            record[
                "independent_probabilities"
            ] = {
                feature: round(
                    probability_document[
                        feature
                    ],
                    6,
                )
                for feature in (
                    independent_features
                )
            }

            record[
                "thresholds"
            ] = {
                feature: thresholds[
                    feature
                ]
                for feature in (
                    independent_features
                )
            }

        records.append(record)

    return records


# =============================================================================
# Display
# =============================================================================

def print_sentence_results(
    sentence_index: int,
    sentence_text: str,
    records: List[Dict[str, Any]],
) -> None:
    """Pretty-print predictions for one sentence."""

    print()
    print("=" * 100)
    print(
        f"SENTENCE {sentence_index + 1}"
    )
    print("=" * 100)
    print(sentence_text.strip())
    print()

    if not records:
        print(
            "No NOUN/PROPN tokens were found."
        )
        return

    for record in records:

        form = record["form"]
        upos = record["upos"]

        independent = record[
            "independent_features"
        ]

        complete = record[
            "features"
        ]

        print(
            f"{form!r} [{upos}]"
        )

        print(
            "  Independent : "
            + (
                ", ".join(independent)
                if independent
                else "(none)"
            )
        )

        print(
            "  Complete    : "
            + (
                ", ".join(complete)
                if complete
                else "(none)"
            )
        )

        if (
            INCLUDE_PROBABILITIES
            and independent
        ):

            probability_strings = []

            for feature in independent:

                probability = record[
                    "independent_probabilities"
                ][feature]

                threshold = record[
                    "thresholds"
                ][feature]

                probability_strings.append(
                    f"{feature}="
                    f"{probability:.3f}"
                    f" (threshold {threshold:.2f})"
                )

            print(
                "  Scores      : "
                + "; ".join(
                    probability_strings
                )
            )

        print()


# =============================================================================
# Main
# =============================================================================

def main() -> None:

    if not SENTENCES.strip():
        raise ValueError(
            "SENTENCES is empty. Add the text you want to tag "
            "to the triple-quoted SENTENCES variable."
        )

    if not MODEL_DIR.exists():
        raise FileNotFoundError(
            "Could not find model directory:\n"
            f"{MODEL_DIR.resolve()}"
        )

    # -------------------------------------------------------------------------
    # Device
    # -------------------------------------------------------------------------

    device = torch.device(
        "cuda"
        if torch.cuda.is_available()
        else "cpu"
    )

    print("=" * 100)
    print("DEVICE")
    print("=" * 100)
    print(f"Device: {device}")

    if device.type == "cuda":
        print(
            "GPU: "
            + torch.cuda.get_device_name(0)
        )

    print()

    # -------------------------------------------------------------------------
    # Metadata
    # -------------------------------------------------------------------------

    label_information = (
        load_label_information()
    )

    prediction_labels = (
        label_information[
            "prediction_labels"
        ]
    )

    full_labels = (
        label_information[
            "full_labels"
        ]
    )

    feature_parents = (
        label_information[
            "feature_parents"
        ]
    )

    feature_switches = (
        label_information[
            "feature_switches"
        ]
    )

    thresholds = (
        load_prediction_thresholds(
            prediction_labels
        )
    )

    expand_feature_hierarchy = (
        make_hierarchy_expander(
            feature_parents=feature_parents,
            feature_switches=feature_switches,
            full_labels=full_labels,
        )
    )

    print("=" * 100)
    print("SEMANTIC FEATURE MODEL")
    print("=" * 100)

    print(
        f"Model directory             : "
        f"{MODEL_DIR.resolve()}"
    )

    print(
        f"Independent neural outputs : "
        f"{len(prediction_labels):,}"
    )

    print(
        f"Complete hierarchy features: "
        f"{len(full_labels):,}"
    )

    disabled_features = sorted(
        feature
        for feature, enabled
        in feature_switches.items()
        if not enabled
    )

    print(
        "Disabled hierarchy features: "
        + (
            ", ".join(disabled_features)
            if disabled_features
            else "none"
        )
    )

    print()

    # -------------------------------------------------------------------------
    # Tokeniser
    # -------------------------------------------------------------------------

    print(
        "Loading RoBERTa tokeniser..."
    )

    tokenizer = (
        AutoTokenizer.from_pretrained(
            str(MODEL_DIR),
            use_fast=True,
        )
    )

    if not tokenizer.is_fast:
        raise RuntimeError(
            "A fast Hugging Face tokeniser is required because "
            "inference relies on word_ids() for subword alignment."
        )

    # -------------------------------------------------------------------------
    # Model
    # -------------------------------------------------------------------------

    model = load_model(
        prediction_labels=prediction_labels,
        device=device,
    )

    # -------------------------------------------------------------------------
    # spaCy
    # -------------------------------------------------------------------------

    print(
        f"Loading spaCy model "
        f"{SPACY_MODEL!r}..."
    )

    nlp = spacy.load(
        SPACY_MODEL,
        disable=[
            "ner",
        ],
    )

    print()

    # -------------------------------------------------------------------------
    # Parse supplied text
    # -------------------------------------------------------------------------

    doc = nlp(
        SENTENCES.strip()
    )

    sentences = list(
        doc.sents
    )

    print(
        f"Sentences to tag: "
        f"{len(sentences):,}"
    )

    print()

    # -------------------------------------------------------------------------
    # Inference
    # -------------------------------------------------------------------------

    all_records: List[
        Dict[str, Any]
    ] = []

    for sentence_index, sentence in enumerate(
        sentences
    ):

        records = predict_sentence(
            sentence=sentence,
            sentence_index=sentence_index,
            model=model,
            tokenizer=tokenizer,
            prediction_labels=prediction_labels,
            thresholds=thresholds,
            expand_feature_hierarchy=(
                expand_feature_hierarchy
            ),
            device=device,
        )

        all_records.extend(records)

        print_sentence_results(
            sentence_index=sentence_index,
            sentence_text=sentence.text,
            records=records,
        )

    # -------------------------------------------------------------------------
    # JSONL output
    # -------------------------------------------------------------------------

    with OUTPUT_JSONL.open(
        "w",
        encoding="utf-8",
    ) as handle:

        for record in all_records:

            handle.write(
                json.dumps(
                    record,
                    ensure_ascii=False,
                )
                + "\n"
            )

    print("=" * 100)
    print("COMPLETE")
    print("=" * 100)

    print(
        f"Tagged NOUN/PROPN tokens: "
        f"{len(all_records):,}"
    )

    print(
        "JSONL output:\n"
        f"  {OUTPUT_JSONL.resolve()}"
    )


if __name__ == "__main__":
    main()

====================================================================================================
DEVICE
====================================================================================================
Device: cuda
GPU: NVIDIA GeForce RTX 5070 Ti

====================================================================================================
SEMANTIC FEATURE MODEL
====================================================================================================
Model directory             : /home/mark/verbnet-roberta/models/roberta_semantic_features/reference_model
Independent neural outputs : 37
Complete hierarchy features: 39
Disabled hierarchy features: Rigidity, Shape, State, State_of_Matter

Loading RoBERTa tokeniser...
Loading RoBERTa architecture...

Loading weights: 100%|███████████████████████████████████████████████████████████████| 389/389 [00:01<00:00, 256.20it/s]
[transformers] RobertaForTokenClassification LOAD REPORT from: FacebookAI/roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
classifier.weight         | MISSING    |
classifier.bias           | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Loading fine-tuned weights...
Loading spaCy model 'en_core_web_sm'...

Sentences to tag: 28


====================================================================================================
SENTENCE 1
====================================================================================================
The old dog slept beside the fireplace.

'dog' [NOUN]
  Independent : Animal, Solid
  Complete    : Animal, Animate, Concrete, Internal_Control, Natural, Solid
  Scores      : Animal=0.992 (threshold 0.83); Solid=0.995 (threshold 0.49)

'fireplace' [NOUN]
  Independent : Artefact, Inanimate, Location, Rigid
  Complete    : Artefact, Concrete, Inanimate, Location, Rigid, Solid
  Scores      : Artefact=0.992 (threshold 0.64); Inanimate=0.996 (threshold 0.46); Location=0.805 (threshold 0.41); Rigid=0.993 (threshold 0.16)


====================================================================================================
SENTENCE 2
====================================================================================================
Microsoft opened a new office in London last year.

'Microsoft' [PROPN]
  Independent : Organisation
  Complete    : Abstract, Internal_Control, Organisation
  Scores      : Organisation=0.995 (threshold 0.54)

'office' [NOUN]
  Independent : Artefact, Inanimate, Location, Rigid, Solid
  Complete    : Artefact, Concrete, Inanimate, Location, Rigid, Solid
  Scores      : Artefact=0.990 (threshold 0.64); Inanimate=0.994 (threshold 0.46); Location=0.991 (threshold 0.41); Rigid=0.438 (threshold 0.16); Solid=0.582 (threshold 0.49)

'London' [PROPN]
  Independent : Location
  Complete    : Location
  Scores      : Location=0.998 (threshold 0.41)

'year' [NOUN]
  Independent : Point_in_Time
  Complete    : Abstract, Point_in_Time, Time
  Scores      : Point_in_Time=0.988 (threshold 0.81)


====================================================================================================
SENTENCE 3
====================================================================================================
The committee discussed the proposal for three hours.

'committee' [NOUN]
  Independent : Organisation
  Complete    : Abstract, Internal_Control, Organisation
  Scores      : Organisation=0.998 (threshold 0.54)

'proposal' [NOUN]
  Independent : Communication
  Complete    : Abstract, Communication
  Scores      : Communication=0.988 (threshold 0.48)

'hours' [NOUN]
  Independent : Duration
  Complete    : Abstract, Duration, Time
  Scores      : Duration=0.996 (threshold 0.19)


====================================================================================================
SENTENCE 4
====================================================================================================
A sharp knife was lying on the wooden table.

'knife' [NOUN]
  Independent : Elongated, Inanimate, Machine, Pointy, Rigid
  Complete    : Artefact, Concrete, Elongated, Inanimate, Internal_Control, Machine, Pointy, Rigid, Solid
  Scores      : Elongated=0.990 (threshold 0.50); Inanimate=0.986 (threshold 0.46); Machine=0.473 (threshold 0.47); Pointy=0.920 (threshold 0.48); Rigid=0.995 (threshold 0.16)

'table' [NOUN]
  Independent : Artefact, Inanimate, Rigid
  Complete    : Artefact, Concrete, Inanimate, Rigid, Solid
  Scores      : Artefact=0.989 (threshold 0.64); Inanimate=0.991 (threshold 0.46); Rigid=0.998 (threshold 0.16)


====================================================================================================
SENTENCE 5
====================================================================================================
The water flowed through the valley.

'water' [NOUN]
  Independent : Inanimate, Solid, Substance
  Complete    : Concrete, Inanimate, Solid, Substance
  Scores      : Inanimate=0.996 (threshold 0.46); Solid=0.998 (threshold 0.49); Substance=0.804 (threshold 0.49)

'valley' [NOUN]
  Independent : Elongated, Inanimate, Location, Rigid
  Complete    : Concrete, Elongated, Inanimate, Location, Rigid, Solid
  Scores      : Elongated=0.593 (threshold 0.50); Inanimate=0.978 (threshold 0.46); Location=0.994 (threshold 0.41); Rigid=0.897 (threshold 0.16)


====================================================================================================
SENTENCE 6
====================================================================================================
I poured the water down the drain.

'I' [PRON]
  Independent : Unspecified_Gender_or_Neuter
  Complete    : Animate, Concrete, Human, Internal_Control, Natural, Unspecified_Gender_or_Neuter
  Scores      : Unspecified_Gender_or_Neuter=0.590 (threshold 0.29)

'water' [NOUN]
  Independent : Inanimate, Solid, Substance
  Complete    : Concrete, Inanimate, Solid, Substance
  Scores      : Inanimate=0.996 (threshold 0.46); Solid=0.976 (threshold 0.49); Substance=0.994 (threshold 0.49)

'drain' [NOUN]
  Independent : Artefact, Inanimate, Rigid
  Complete    : Artefact, Concrete, Inanimate, Rigid, Solid
  Scores      : Artefact=0.953 (threshold 0.64); Inanimate=0.995 (threshold 0.46); Rigid=0.875 (threshold 0.16)


====================================================================================================
SENTENCE 7
====================================================================================================
John coiled the wire around the pole.

'John' [PROPN]
  Independent : Masculine
  Complete    : Animate, Concrete, Human, Internal_Control, Masculine, Natural
  Scores      : Masculine=0.996 (threshold 0.33)

'wire' [NOUN]
  Independent : Elongated, Inanimate, Machine, Non_Rigid
  Complete    : Artefact, Concrete, Elongated, Inanimate, Internal_Control, Machine, Non_Rigid, Solid
  Scores      : Elongated=0.980 (threshold 0.50); Inanimate=0.964 (threshold 0.46); Machine=0.945 (threshold 0.47); Non_Rigid=0.988 (threshold 0.42)

'pole' [NOUN]
  Independent : Elongated, Inanimate, Rigid
  Complete    : Concrete, Elongated, Inanimate, Rigid, Solid
  Scores      : Elongated=0.992 (threshold 0.50); Inanimate=0.651 (threshold 0.46); Rigid=0.761 (threshold 0.16)


====================================================================================================
SENTENCE 8
====================================================================================================
The snake wound itself around the tree branch.

'snake' [NOUN]
  Independent : Animal, Solid
  Complete    : Animal, Animate, Concrete, Internal_Control, Natural, Solid
  Scores      : Animal=0.996 (threshold 0.83); Solid=0.992 (threshold 0.49)

'itself' [PRON]
  Independent : Non_Rigid
  Complete    : Concrete, Non_Rigid, Solid
  Scores      : Non_Rigid=0.851 (threshold 0.42)

'tree' [NOUN]
  Independent : Elongated, Plant, Rigid
  Complete    : Animate, Concrete, Elongated, Internal_Control, Natural, Plant, Rigid, Solid
  Scores      : Elongated=0.948 (threshold 0.50); Plant=0.860 (threshold 0.50); Rigid=0.963 (threshold 0.16)

'branch' [NOUN]
  Independent : Elongated, Inanimate, Pointy, Rigid
  Complete    : Concrete, Elongated, Inanimate, Pointy, Rigid, Solid
  Scores      : Elongated=0.992 (threshold 0.50); Inanimate=0.567 (threshold 0.46); Pointy=0.563 (threshold 0.48); Rigid=0.694 (threshold 0.16)


====================================================================================================
SENTENCE 9
====================================================================================================
Steam erupted from the volcanic vents.

'Steam' [PROPN]
  Independent : Inanimate, Solid, Substance
  Complete    : Concrete, Inanimate, Solid, Substance
  Scores      : Inanimate=0.996 (threshold 0.46); Solid=0.995 (threshold 0.49); Substance=0.880 (threshold 0.49)

'vents' [NOUN]
  Independent : Inanimate, Location, Solid
  Complete    : Concrete, Inanimate, Location, Solid
  Scores      : Inanimate=0.995 (threshold 0.46); Location=0.963 (threshold 0.41); Solid=0.898 (threshold 0.49)


====================================================================================================
SENTENCE 10
====================================================================================================
I need to buy some orange juice at the supermarket tomorrow.

'I' [PRON]
  Independent : (none)
  Complete    : (none)

'orange' [NOUN]
  Independent : Comestible, Inanimate, Non_Rigid, Plant
  Complete    : Animate, Comestible, Concrete, Inanimate, Internal_Control, Natural, Non_Rigid, Plant, Solid
  Scores      : Comestible=0.802 (threshold 0.61); Inanimate=0.465 (threshold 0.46); Non_Rigid=0.497 (threshold 0.42); Plant=0.723 (threshold 0.50)

'juice' [NOUN]
  Independent : Comestible, Fluid, Inanimate, Substance
  Complete    : Comestible, Concrete, Fluid, Inanimate, Substance
  Scores      : Comestible=0.983 (threshold 0.61); Fluid=0.781 (threshold 0.48); Inanimate=0.988 (threshold 0.46); Substance=0.995 (threshold 0.49)

'supermarket' [NOUN]
  Independent : Artefact, Inanimate, Location, Rigid
  Complete    : Artefact, Concrete, Inanimate, Location, Rigid, Solid
  Scores      : Artefact=0.989 (threshold 0.64); Inanimate=0.991 (threshold 0.46); Location=0.996 (threshold 0.41); Rigid=0.985 (threshold 0.16)

'tomorrow' [NOUN]
  Independent : Point_in_Time
  Complete    : Abstract, Point_in_Time, Time
  Scores      : Point_in_Time=0.995 (threshold 0.81)


====================================================================================================
SENTENCE 11
====================================================================================================
Pour some olive oil into a small pan before frying the fish.

'oil' [NOUN]
  Independent : Inanimate, Solid, Substance
  Complete    : Concrete, Inanimate, Solid, Substance
  Scores      : Inanimate=0.996 (threshold 0.46); Solid=0.964 (threshold 0.49); Substance=0.996 (threshold 0.49)

'pan' [NOUN]
  Independent : Artefact, Inanimate, Rigid
  Complete    : Artefact, Concrete, Inanimate, Rigid, Solid
  Scores      : Artefact=0.985 (threshold 0.64); Inanimate=0.996 (threshold 0.46); Rigid=0.994 (threshold 0.16)

'fish' [NOUN]
  Independent : Comestible, Inanimate, Non_Rigid
  Complete    : Comestible, Concrete, Inanimate, Non_Rigid, Solid
  Scores      : Comestible=0.989 (threshold 0.61); Inanimate=0.967 (threshold 0.46); Non_Rigid=0.958 (threshold 0.42)


====================================================================================================
SENTENCE 12
====================================================================================================
I am looking forward to attending the party tonight.

'I' [PRON]
  Independent : Unspecified_Gender_or_Neuter
  Complete    : Animate, Concrete, Human, Internal_Control, Natural, Unspecified_Gender_or_Neuter
  Scores      : Unspecified_Gender_or_Neuter=0.690 (threshold 0.29)

'party' [NOUN]
  Independent : Eventive
  Complete    : Abstract, Eventive
  Scores      : Eventive=0.996 (threshold 0.38)

'tonight' [NOUN]
  Independent : Point_in_Time
  Complete    : Abstract, Point_in_Time, Time
  Scores      : Point_in_Time=0.995 (threshold 0.81)


====================================================================================================
SENTENCE 13
====================================================================================================
Our trip to New York was a lot of fun!

'Our' [PRON]
  Independent : Eventive
  Complete    : Abstract, Eventive
  Scores      : Eventive=0.989 (threshold 0.38)

'trip' [NOUN]
  Independent : Eventive
  Complete    : Abstract, Eventive
  Scores      : Eventive=0.998 (threshold 0.38)

'New' [PROPN]
  Independent : Location
  Complete    : Location
  Scores      : Location=0.997 (threshold 0.41)

'York' [PROPN]
  Independent : Location
  Complete    : Location
  Scores      : Location=0.996 (threshold 0.41)

'lot' [NOUN]
  Independent : Abstract
  Complete    : Abstract
  Scores      : Abstract=0.995 (threshold 0.83)

'fun' [NOUN]
  Independent : Eventive
  Complete    : Abstract, Eventive
  Scores      : Eventive=0.997 (threshold 0.38)


====================================================================================================
SENTENCE 14
====================================================================================================
London and Paris have signed a new agreement for closer economic relations.

'London' [PROPN]
  Independent : Organisation
  Complete    : Abstract, Internal_Control, Organisation
  Scores      : Organisation=0.992 (threshold 0.54)

'Paris' [PROPN]
  Independent : Organisation
  Complete    : Abstract, Internal_Control, Organisation
  Scores      : Organisation=0.993 (threshold 0.54)

'agreement' [NOUN]
  Independent : Statement
  Complete    : Abstract, Communication, Statement
  Scores      : Statement=0.969 (threshold 0.65)

'relations' [NOUN]
  Independent : Eventive
  Complete    : Abstract, Eventive
  Scores      : Eventive=0.914 (threshold 0.38)


====================================================================================================
SENTENCE 15
====================================================================================================
I read the old diary with difficulty.

'I' [PRON]
  Independent : (none)
  Complete    : (none)

'diary' [NOUN]
  Independent : Communication, Non_Rigid
  Complete    : Abstract, Communication, Concrete, Non_Rigid, Solid
  Scores      : Communication=0.665 (threshold 0.48); Non_Rigid=0.466 (threshold 0.42)

'difficulty' [NOUN]
  Independent : Eventive
  Complete    : Abstract, Eventive
  Scores      : Eventive=0.941 (threshold 0.38)


====================================================================================================
SENTENCE 16
====================================================================================================
The ink was smudged in places, making the handwriting hard to decypher.

'ink' [NOUN]
  Independent : Inanimate, Solid, Substance
  Complete    : Concrete, Inanimate, Solid, Substance
  Scores      : Inanimate=0.998 (threshold 0.46); Solid=0.889 (threshold 0.49); Substance=0.993 (threshold 0.49)

'places' [NOUN]
  Independent : Inanimate, Location, Solid
  Complete    : Concrete, Inanimate, Location, Solid
  Scores      : Inanimate=0.989 (threshold 0.46); Location=0.995 (threshold 0.41); Solid=0.991 (threshold 0.49)

'handwriting' [NOUN]
  Independent : Communication
  Complete    : Abstract, Communication
  Scores      : Communication=0.987 (threshold 0.48)

'decypher' [PROPN]
  Independent : Communication
  Complete    : Abstract, Communication
  Scores      : Communication=0.810 (threshold 0.48)


====================================================================================================
SENTENCE 17
====================================================================================================
Harriet prodded the bug with the tip of a rolled-up newspaper.

'Harriet' [PROPN]
  Independent : Feminine
  Complete    : Animate, Concrete, Feminine, Human, Internal_Control, Natural
  Scores      : Feminine=0.996 (threshold 0.25)

'bug' [NOUN]
  Independent : Animal, Solid
  Complete    : Animal, Animate, Concrete, Internal_Control, Natural, Solid
  Scores      : Animal=0.959 (threshold 0.83); Solid=0.936 (threshold 0.49)

'tip' [NOUN]
  Independent : Elongated, Inanimate, Rigid
  Complete    : Concrete, Elongated, Inanimate, Rigid, Solid
  Scores      : Elongated=0.572 (threshold 0.50); Inanimate=0.965 (threshold 0.46); Rigid=0.933 (threshold 0.16)

'newspaper' [NOUN]
  Independent : Artefact, Inanimate, Non_Rigid
  Complete    : Artefact, Concrete, Inanimate, Non_Rigid, Solid
  Scores      : Artefact=0.980 (threshold 0.64); Inanimate=0.988 (threshold 0.46); Non_Rigid=0.993 (threshold 0.42)


====================================================================================================
SENTENCE 18
====================================================================================================
I know that the Earth orbits the Sun.

'I' [PRON]
  Independent : Unspecified_Gender_or_Neuter
  Complete    : Animate, Concrete, Human, Internal_Control, Natural, Unspecified_Gender_or_Neuter
  Scores      : Unspecified_Gender_or_Neuter=0.721 (threshold 0.29)

'Earth' [PROPN]
  Independent : Location, Rigid
  Complete    : Concrete, Location, Rigid, Solid
  Scores      : Location=0.927 (threshold 0.41); Rigid=0.691 (threshold 0.16)

'Sun' [PROPN]
  Independent : Inanimate, Location, Natural, Rigid
  Complete    : Concrete, Inanimate, Location, Natural, Rigid, Solid
  Scores      : Inanimate=0.530 (threshold 0.46); Location=0.940 (threshold 0.41); Natural=0.841 (threshold 0.50); Rigid=0.347 (threshold 0.16)


====================================================================================================
SENTENCE 19
====================================================================================================
John ate the pasta.

'John' [PROPN]
  Independent : Masculine
  Complete    : Animate, Concrete, Human, Internal_Control, Masculine, Natural
  Scores      : Masculine=0.995 (threshold 0.33)

'pasta' [NOUN]
  Independent : Comestible, Inanimate, Non_Rigid, Substance
  Complete    : Comestible, Concrete, Inanimate, Non_Rigid, Solid, Substance
  Scores      : Comestible=0.981 (threshold 0.61); Inanimate=0.993 (threshold 0.46); Non_Rigid=0.991 (threshold 0.42); Substance=0.771 (threshold 0.49)


====================================================================================================
SENTENCE 20
====================================================================================================
John ate the milk.

'John' [PROPN]
  Independent : Masculine
  Complete    : Animate, Concrete, Human, Internal_Control, Masculine, Natural
  Scores      : Masculine=0.996 (threshold 0.33)

'milk' [NOUN]
  Independent : Comestible, Fluid, Inanimate, Substance
  Complete    : Comestible, Concrete, Fluid, Inanimate, Substance
  Scores      : Comestible=0.994 (threshold 0.61); Fluid=0.944 (threshold 0.48); Inanimate=0.982 (threshold 0.46); Substance=0.991 (threshold 0.49)


====================================================================================================
SENTENCE 21
====================================================================================================
The ATM ate my bank card.

'ATM' [PROPN]
  Independent : Inanimate, Machine, Rigid
  Complete    : Artefact, Concrete, Inanimate, Internal_Control, Machine, Rigid, Solid
  Scores      : Inanimate=0.976 (threshold 0.46); Machine=0.960 (threshold 0.47); Rigid=0.983 (threshold 0.16)

'my' [PRON]
  Independent : Communication
  Complete    : Abstract, Communication
  Scores      : Communication=0.906 (threshold 0.48)

'bank' [NOUN]
  Independent : Organisation
  Complete    : Abstract, Internal_Control, Organisation
  Scores      : Organisation=0.948 (threshold 0.54)

'card' [NOUN]
  Independent : Communication
  Complete    : Abstract, Communication
  Scores      : Communication=0.952 (threshold 0.48)


====================================================================================================
SENTENCE 22
====================================================================================================
The cheese smells.

'cheese' [NOUN]
  Independent : Comestible, Inanimate, Non_Rigid, Substance
  Complete    : Comestible, Concrete, Inanimate, Non_Rigid, Solid, Substance
  Scores      : Comestible=0.994 (threshold 0.61); Inanimate=0.993 (threshold 0.46); Non_Rigid=0.970 (threshold 0.42); Substance=0.971 (threshold 0.49)


====================================================================================================
SENTENCE 23
====================================================================================================
The skunk smells.

'skunk' [NOUN]
  Independent : Animal, Solid
  Complete    : Animal, Animate, Concrete, Internal_Control, Natural, Solid
  Scores      : Animal=0.989 (threshold 0.83); Solid=0.992 (threshold 0.49)



<h1>Feature distillation</h1>

In [38]:
#!/usr/bin/env python3
"""
Distil semantic restrictions on the arguments of repeated VerbNet-style
frame examples.

Compatible with Python 3.9.21.

The script supports frames of ANY number of arguments.

Examples
--------

Two-argument frame:

    Susan talked with Rachel.

    FRAME_ARGUMENTS = [
        "Speaker",
        "Co_interlocutor",
    ]


Three-argument frame:

    Susan talked about the problem to Rachel.

    FRAME_ARGUMENTS = [
        "Speaker",
        "Topic",
        "Addressee",
    ]


Automatic positional mode:

    FRAME_ARGUMENTS = None

The script will inspect the JSONL data and create:

    Argument_1
    Argument_2
    Argument_3
    ...

Mutually exclusive features are resolved BEFORE threshold filtering.

For example:

    Rigid       9/30
    Non_Rigid  27/30

Both are removed before the 0.70 threshold is applied.

A feature such as Comestible is NOT removed merely because it inherits
from a more frequent feature such as Concrete.
"""

from __future__ import annotations

import json
from collections import Counter, defaultdict
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple


# =============================================================================
# Configuration
# =============================================================================

INPUT_JSONL = Path(
    "tagged_sentences.jsonl"
)

OUTPUT_JSON = Path(
    "distilled_frame_features.json"
)


# =============================================================================
# Frame definition
# =============================================================================

FRAME_NAME = (
     "poke: Agent V Patient with Instrument"
)


# Specify as many arguments as the frame contains.
#
# The order MUST correspond to the order of the tagged arguments in
# each sentence.
#
# Example:
#
#     Susan talked about the problem to Rachel.
#
# Tagged arguments:
#
#     Susan    -> Speaker
#     problem  -> Topic
#     Rachel   -> Addressee
#
FRAME_ARGUMENTS = [
    "Agent",
    "Patient",
    "Instrument",
]


# Alternatively:
#
# FRAME_ARGUMENTS = None
#
# This causes the script to infer the number of arguments from the data
# and generate:
#
#     Argument_1
#     Argument_2
#     ...
#


# =============================================================================
# Feature settings
# =============================================================================

FEATURE_FIELD = "features"


# A feature must occur in MORE THAN 70% of argument fillers.
#
# With 30 examples:
#
#     22/30 = 73.3% -> retained
#     21/30 = 70.0% -> excluded
#
# With 50 examples:
#
#     36/50 = 72.0% -> retained
#     35/50 = 70.0% -> excluded
#
MIN_FEATURE_PROPORTION = 0.70


EPSILON = 1e-9


# =============================================================================
# Feature hierarchy
# =============================================================================

FEATURE_PARENTS: Dict[str, Set[str]] = {

    "Organisation": {
        "Internal_Control",
        "Abstract",
    },

    "Natural_Force": {
        "Internal_Control",
    },

    "Animate": {
        "Internal_Control",
        "Natural",
    },

    "Human": {
        "Animate",
    },

    "Feminine": {
        "Human",
    },

    "Masculine": {
        "Human",
    },

    "Unspecified_Gender_or_Neuter": {
        "Human",
    },

    "Animal": {
        "Animate",
    },

    "Plant": {
        "Animate",
    },

    "Body_Part": {
        "Animate",
    },

    "Machine": {
        "Internal_Control",
        "Artefact",
    },

    "Vehicle": {
        "Machine",
    },

    "Natural": {
        "Concrete",
    },

    "Artefact": {
        "Concrete",
    },

    "Comestible": {
        "Concrete",
    },

    "Substance": {
        "Concrete",
    },

    "State_of_Matter": {
        "Concrete",
    },

    "Inanimate": {
        "Concrete",
    },

    "Garment": {
        "Artefact",
    },

    "Solid": {
        "State_of_Matter",
    },

    "Fluid": {
        "State_of_Matter",
    },

    "Rigidity": {
        "Solid",
    },

    "Shape": {
        "Solid",
    },

    "Rigid": {
        "Rigidity",
    },

    "Non_Rigid": {
        "Rigidity",
    },

    "Elongated": {
        "Shape",
    },

    "Pointy": {
        "Shape",
    },

    "Point_in_Time": {
        "Time",
    },

    "Duration": {
        "Time",
    },

    "Time": {
        "Abstract",
    },

    "Language": {
        "Abstract",
    },

    "Sound": {
        "Abstract",
    },

    "Communication": {
        "Abstract",
    },

    "Eventive": {
        "Abstract",
    },

    "Statement": {
        "Communication",
    },

    "Question": {
        "Communication",
    },
}


# =============================================================================
# Mutually exclusive feature groups
# =============================================================================

MUTUALLY_EXCLUSIVE_GROUPS: List[Set[str]] = [

    {
        "Rigid",
        "Non_Rigid",
    },

    {
        "Solid",
        "Fluid",
    },

    {
        "Feminine",
        "Masculine",
        "Unspecified_Gender_or_Neuter",
    },

    {
        "Point_in_Time",
        "Duration",
    },
]


# =============================================================================
# Hierarchy helpers
# =============================================================================

@lru_cache(maxsize=None)
def get_ancestors(
    feature: str,
) -> frozenset:
    """Return all ancestors of a feature."""

    ancestors: Set[str] = set()

    for parent in FEATURE_PARENTS.get(
        feature,
        set(),
    ):

        ancestors.add(
            parent
        )

        ancestors.update(
            get_ancestors(
                parent
            )
        )

    return frozenset(
        ancestors
    )


def get_descendants(
    ancestor: str,
    available_features: Set[str],
) -> Set[str]:
    """Return observed descendants of an ancestor."""

    return {
        feature
        for feature in available_features
        if (
            feature != ancestor
            and ancestor in get_ancestors(feature)
        )
    }


# =============================================================================
# Loading
# =============================================================================

def load_jsonl(
    path: Path,
) -> List[Dict[str, Any]]:
    """Load inference JSONL."""

    if not path.exists():

        raise FileNotFoundError(
            f"Could not find:\n"
            f"{path.resolve()}"
        )

    records: List[
        Dict[str, Any]
    ] = []

    with path.open(
        "r",
        encoding="utf-8",
    ) as handle:

        for line_number, line in enumerate(
            handle,
            start=1,
        ):

            line = line.strip()

            if not line:
                continue

            try:

                record = json.loads(
                    line
                )

            except json.JSONDecodeError as exc:

                raise ValueError(
                    f"Invalid JSON on line "
                    f"{line_number}"
                ) from exc

            if not isinstance(
                record,
                dict,
            ):

                raise ValueError(
                    f"Line {line_number} is "
                    f"not a JSON object."
                )

            records.append(
                record
            )

    if not records:

        raise ValueError(
            "The input file contains no records."
        )

    return records


# =============================================================================
# Group records by sentence
# =============================================================================

def group_by_sentence(
    records: List[Dict[str, Any]],
) -> Dict[
    int,
    List[Dict[str, Any]],
]:
    """
    Group argument records by sentence.

    Records within each sentence are sorted by token position.
    """

    grouped: Dict[
        int,
        List[Dict[str, Any]],
    ] = defaultdict(list)

    for record in records:

        if "sentence_index" not in record:

            raise ValueError(
                "Record is missing sentence_index."
            )

        if "token_id" not in record:

            raise ValueError(
                "Record is missing token_id."
            )

        sentence_index = int(
            record[
                "sentence_index"
            ]
        )

        grouped[
            sentence_index
        ].append(
            record
        )

    for sentence_index in grouped:

        grouped[
            sentence_index
        ].sort(
            key=lambda record: int(
                record[
                    "token_id"
                ]
            )
        )

    return dict(
        sorted(
            grouped.items()
        )
    )


# =============================================================================
# Determine frame length and role names
# =============================================================================

def resolve_frame_arguments(
    sentences: Dict[
        int,
        List[Dict[str, Any]],
    ],
) -> List[str]:
    """
    Determine the semantic role inventory for this frame.

    The number of tagged arguments is inferred from the data.

    All sentences must contain the same number of tagged arguments.

    If FRAME_ARGUMENTS is None, generic role labels are generated:

        Argument_1
        Argument_2
        ...

    If FRAME_ARGUMENTS is supplied, its length must match the detected
    argument count.
    """

    if not sentences:

        raise ValueError(
            "No frame examples were found."
        )

    # -------------------------------------------------------------------------
    # Count arguments in each sentence
    # -------------------------------------------------------------------------

    argument_counts: Dict[
        int,
        int,
    ] = {
        sentence_index: len(
            records
        )
        for sentence_index, records
        in sentences.items()
    }

    unique_counts = set(
        argument_counts.values()
    )

    # -------------------------------------------------------------------------
    # Every example must instantiate the same frame length
    # -------------------------------------------------------------------------

    if len(unique_counts) != 1:

        details: List[str] = []

        for sentence_index, records in sentences.items():

            forms = [
                str(
                    record.get(
                        "form",
                        "?",
                    )
                )
                for record in records
            ]

            details.append(
                f"Sentence "
                f"{sentence_index + 1}: "
                f"{len(records)} arguments "
                f"{forms}"
            )

        raise ValueError(
            "Frame examples do not all contain "
            "the same number of tagged arguments.\n\n"
            + "\n".join(details)
        )

    detected_count = next(
        iter(
            unique_counts
        )
    )

    if detected_count == 0:

        raise ValueError(
            "No tagged arguments were found."
        )

    # -------------------------------------------------------------------------
    # Automatic role naming
    # -------------------------------------------------------------------------

    if FRAME_ARGUMENTS is None:

        roles = [
            f"Argument_{index + 1}"
            for index in range(
                detected_count
            )
        ]

        print(
            "FRAME_ARGUMENTS is None."
        )

        print(
            f"Automatically detected "
            f"{detected_count} arguments."
        )

        print(
            "Generated roles: "
            + ", ".join(
                roles
            )
        )

        return roles

    # -------------------------------------------------------------------------
    # Explicit role naming
    # -------------------------------------------------------------------------

    roles = [
        str(role)
        for role
        in FRAME_ARGUMENTS
    ]

    if len(roles) != detected_count:

        first_sentence_index = min(
            sentences
        )

        first_forms = [
            str(
                record.get(
                    "form",
                    "?",
                )
            )
            for record
            in sentences[
                first_sentence_index
            ]
        ]

        raise ValueError(
            "FRAME_ARGUMENTS does not match "
            "the frame found in the data.\n\n"
            f"Configured roles : "
            f"{len(roles)}\n"
            f"Detected arguments: "
            f"{detected_count}\n\n"
            f"Configured:\n"
            f"  {roles}\n\n"
            f"First frame instance:\n"
            f"  {first_forms}\n\n"
            "Either update FRAME_ARGUMENTS "
            "to contain one role for every argument, "
            "or set:\n\n"
            "    FRAME_ARGUMENTS = None\n\n"
            "to use automatic positional labels."
        )

    # -------------------------------------------------------------------------
    # Duplicate role names would make the output ambiguous
    # -------------------------------------------------------------------------

    if len(
        set(
            roles
        )
    ) != len(
        roles
    ):

        raise ValueError(
            "FRAME_ARGUMENTS contains duplicate "
            "role names:\n"
            f"{roles}"
        )

    return roles


# =============================================================================
# Assign arguments
# =============================================================================

def assign_arguments(
    sentences: Dict[
        int,
        List[Dict[str, Any]],
    ],
    frame_arguments: List[str],
) -> Dict[
    str,
    List[Dict[str, Any]],
]:
    """
    Assign records to argument positions.

    Works for frames of arbitrary length.
    """

    arguments: Dict[
        str,
        List[Dict[str, Any]],
    ] = {
        role: []
        for role
        in frame_arguments
    }

    expected = len(
        frame_arguments
    )

    for sentence_index, records in sentences.items():

        if len(records) != expected:

            raise ValueError(
                f"Sentence "
                f"{sentence_index + 1} "
                f"contains {len(records)} "
                f"arguments; expected {expected}."
            )

        for role, record in zip(
            frame_arguments,
            records,
        ):

            arguments[
                role
            ].append(
                record
            )

    return arguments


# =============================================================================
# Feature helpers
# =============================================================================

def get_feature_set(
    record: Dict[str, Any],
) -> Set[str]:
    """Return features for one argument filler."""

    raw_features = record.get(
        FEATURE_FIELD,
        [],
    )

    if raw_features is None:

        return set()

    if not isinstance(
        raw_features,
        list,
    ):

        raise ValueError(
            f"{FEATURE_FIELD!r} must "
            f"contain a list."
        )

    return {
        str(feature)
        for feature
        in raw_features
    }


# =============================================================================
# Resolve mutually-exclusive features
# =============================================================================

def resolve_mutual_exclusions(
    observed_features: Set[str],
) -> Tuple[
    Set[str],
    List[Dict[str, Any]],
]:
    """
    Resolve semantic clashes BEFORE frequency thresholding.

    If two or more mutually-exclusive features occur anywhere in the
    argument position, all observed members of that exclusion group
    are removed.

    Example:

        Rigid       9/30
        Non_Rigid  27/30

    Both Rigid and Non_Rigid are removed before the 0.70 threshold
    is applied.
    """

    resolved = set(
        observed_features
    )

    conflicts: List[
        Dict[str, Any]
    ] = []

    for group in MUTUALLY_EXCLUSIVE_GROUPS:

        present = (
            observed_features
            & group
        )

        if len(present) < 2:

            continue

        resolved.difference_update(
            present
        )

        conflicts.append(
            {
                "group": sorted(
                    group
                ),
                "removed": sorted(
                    present
                ),
            }
        )

    return (
        resolved,
        conflicts,
    )


# =============================================================================
# Below-threshold hierarchy diagnostics
# =============================================================================

def analyse_below_threshold_hierarchy(
    counts: Counter,
    total: int,
) -> List[Dict[str, Any]]:
    """
    Examine specific features that fall below the main threshold.

    This is diagnostic only.

    It does NOT remove above-threshold features such as Comestible.

    For example:

        Human   25/50
        Animal  25/50
        Animate 50/50

    can help explain why Animate is strongly supported even though its
    more specific descendants are not.
    """

    available_features = set(
        counts.keys()
    )

    reports: List[
        Dict[str, Any]
    ] = []

    for ancestor in sorted(
        available_features
    ):

        ancestor_count = int(
            counts.get(
                ancestor,
                0,
            )
        )

        ancestor_proportion = (
            ancestor_count
            / total
        )

        descendants = get_descendants(
            ancestor=ancestor,
            available_features=(
                available_features
            ),
        )

        weak_descendants: List[
            Dict[str, Any]
        ] = []

        for descendant in descendants:

            count = int(
                counts[
                    descendant
                ]
            )

            proportion = (
                count
                / total
            )

            if (
                proportion
                <=
                MIN_FEATURE_PROPORTION
                + EPSILON
            ):

                weak_descendants.append(
                    {
                        "feature": (
                            descendant
                        ),
                        "count": (
                            count
                        ),
                        "proportion": (
                            proportion
                        ),
                    }
                )

        if len(
            weak_descendants
        ) < 2:

            continue

        weak_descendants.sort(
            key=lambda item: (
                -item[
                    "proportion"
                ],
                item[
                    "feature"
                ],
            )
        )

        reports.append(
            {
                "ancestor": (
                    ancestor
                ),
                "ancestor_count": (
                    ancestor_count
                ),
                "ancestor_proportion": (
                    ancestor_proportion
                ),
                "below_threshold_descendants": (
                    weak_descendants
                ),
            }
        )

    return reports


# =============================================================================
# Analyse one argument position
# =============================================================================

def analyse_argument(
    records: List[Dict[str, Any]],
) -> Dict[str, Any]:
    """Analyse one argument position across all frame examples."""

    if not records:

        raise ValueError(
            "Cannot analyse an empty "
            "argument set."
        )

    total = len(
        records
    )

    feature_sets = [
        get_feature_set(
            record
        )
        for record
        in records
    ]

    # -------------------------------------------------------------------------
    # Count feature occurrence
    # -------------------------------------------------------------------------

    counts: Counter = Counter()

    for features in feature_sets:

        counts.update(
            features
        )

    proportions: Dict[
        str,
        float,
    ] = {
        feature: (
            count
            / total
        )
        for feature, count
        in counts.items()
    }

    # -------------------------------------------------------------------------
    # All observed features
    # -------------------------------------------------------------------------

    observed_features: Set[str] = set(
        counts.keys()
    )

    # -------------------------------------------------------------------------
    # FIRST: remove mutually-exclusive clashes
    # -------------------------------------------------------------------------

    (
        non_conflicting_features,
        conflicts,
    ) = resolve_mutual_exclusions(
        observed_features=(
            observed_features
        ),
    )

    # -------------------------------------------------------------------------
    # SECOND: apply threshold
    # -------------------------------------------------------------------------

    final_features: Set[str] = {
        feature
        for feature
        in non_conflicting_features
        if (
            proportions[
                feature
            ]
            >
            MIN_FEATURE_PROPORTION
        )
    }

    # -------------------------------------------------------------------------
    # Below-threshold hierarchy diagnostics
    # -------------------------------------------------------------------------

    below_threshold_hierarchy = (
        analyse_below_threshold_hierarchy(
            counts=counts,
            total=total,
        )
    )

    # -------------------------------------------------------------------------
    # Example information
    # -------------------------------------------------------------------------

    examples: List[
        Dict[str, Any]
    ] = []

    for record, features in zip(
        records,
        feature_sets,
    ):

        examples.append(
            {
                "sentence_index": int(
                    record[
                        "sentence_index"
                    ]
                ),
                "token_id": int(
                    record[
                        "token_id"
                    ]
                ),
                "form": str(
                    record.get(
                        "form",
                        "",
                    )
                ),
                "lemma": str(
                    record.get(
                        "lemma",
                        "",
                    )
                ),
                "upos": str(
                    record.get(
                        "upos",
                        "",
                    )
                ),
                "features": sorted(
                    features
                ),
            }
        )

    return {

        "n_examples": (
            total
        ),

        "minimum_feature_proportion": (
            MIN_FEATURE_PROPORTION
        ),

        "observed_features": sorted(
            observed_features
        ),

        "non_conflicting_features": sorted(
            non_conflicting_features
        ),

        "final_features": sorted(
            final_features
        ),

        "mutual_exclusion_conflicts": (
            conflicts
        ),

        "below_threshold_hierarchy": (
            below_threshold_hierarchy
        ),

        "feature_frequencies": {
            feature: {
                "count": int(
                    count
                ),
                "total": (
                    total
                ),
                "proportion": (
                    count
                    / total
                ),
            }
            for feature, count
            in sorted(
                counts.items(),
                key=lambda item: (
                    -item[1],
                    item[0],
                ),
            )
        },

        "examples": (
            examples
        ),
    }


# =============================================================================
# Analyse complete frame
# =============================================================================

def analyse_frame(
    arguments: Dict[
        str,
        List[Dict[str, Any]],
    ],
    frame_arguments: List[str],
) -> Dict[str, Any]:
    """
    Analyse every argument position.

    No assumption is made about frame length.
    """

    return {
        role: analyse_argument(
            arguments[
                role
            ]
        )
        for role
        in frame_arguments
    }


# =============================================================================
# Display one role
# =============================================================================

def print_role_analysis(
    role: str,
    analysis: Dict[str, Any],
) -> None:
    """Display results for one argument position."""

    print()
    print("=" * 100)
    print(
        role.upper()
    )
    print("=" * 100)

    total = analysis[
        "n_examples"
    ]

    print(
        f"Examples          : "
        f"{total}"
    )

    print(
        f"Feature threshold : "
        f"> "
        f"{MIN_FEATURE_PROPORTION:.0%}"
    )

    # -------------------------------------------------------------------------
    # Fillers
    # -------------------------------------------------------------------------

    print()
    print("ARGUMENT FILLERS")
    print("-" * 100)

    print(
        ", ".join(
            example[
                "form"
            ]
            for example
            in analysis[
                "examples"
            ]
        )
    )

    # -------------------------------------------------------------------------
    # Prepare markers
    # -------------------------------------------------------------------------

    final_features = set(
        analysis[
            "final_features"
        ]
    )

    conflicted_features: Set[str] = set()

    for conflict in analysis[
        "mutual_exclusion_conflicts"
    ]:

        conflicted_features.update(
            conflict[
                "removed"
            ]
        )

    # -------------------------------------------------------------------------
    # Frequencies
    # -------------------------------------------------------------------------

    print()
    print("ALL FEATURE FREQUENCIES")
    print("-" * 100)

    frequencies = analysis[
        "feature_frequencies"
    ]

    for feature, information in frequencies.items():

        if feature in conflicted_features:

            marker = "!"

        elif feature in final_features:

            marker = "*"

        else:

            marker = " "

        print(
            f"{marker} "
            f"{feature:<32} "
            f"{information['count']:>3}/"
            f"{information['total']:<3} "
            f"("
            f"{information['proportion']:>6.1%}"
            f")"
        )

    print()

    print(
        "* = retained in final restriction"
    )

    print(
        "! = removed as a mutually-exclusive "
        "clash before thresholding"
    )

    # -------------------------------------------------------------------------
    # Mutual exclusions
    # -------------------------------------------------------------------------

    print()
    print("MUTUAL-EXCLUSION CLASHES")
    print("-" * 100)

    conflicts = analysis[
        "mutual_exclusion_conflicts"
    ]

    if not conflicts:

        print(
            "(none)"
        )

    else:

        for conflict in conflicts:

            print(
                "Removed: "
                + ", ".join(
                    conflict[
                        "removed"
                    ]
                )
            )

            print(
                "Exclusive group: "
                + ", ".join(
                    conflict[
                        "group"
                    ]
                )
            )

            print()

    # -------------------------------------------------------------------------
    # Final restrictions
    # -------------------------------------------------------------------------

    print()
    print("FINAL ARGUMENT RESTRICTION")
    print("-" * 100)

    final_features_list = analysis[
        "final_features"
    ]

    if not final_features_list:

        print(
            "(none)"
        )

    else:

        for feature in final_features_list:

            information = frequencies[
                feature
            ]

            print(
                f"  {feature:<32} "
                f"{information['count']:>3}/"
                f"{information['total']:<3} "
                f"("
                f"{information['proportion']:>6.1%}"
                f")"
            )


# =============================================================================
# Print distilled frame
# =============================================================================

def print_distilled_frame(
    analysis: Dict[str, Any],
    frame_arguments: List[str],
) -> None:
    """Print concise restrictions for every frame argument."""

    print()
    print("=" * 100)
    print("DISTILLED FRAME")
    print("=" * 100)

    print()
    print(
        FRAME_NAME
    )

    print()

    for index, role in enumerate(
        frame_arguments,
        start=1,
    ):

        features = analysis[
            role
        ][
            "final_features"
        ]

        if features:

            feature_string = (
                ", ".join(
                    features
                )
            )

        else:

            feature_string = (
                "(no restriction found)"
            )

        print(
            f"{index:>2}. "
            f"{role:<20} "
            f"{feature_string}"
        )


# =============================================================================
# Save results
# =============================================================================

def save_results(
    analysis: Dict[str, Any],
    frame_arguments: List[str],
) -> None:
    """Write results to JSON."""

    output = {

        "frame_name": (
            FRAME_NAME
        ),

        "argument_count": len(
            frame_arguments
        ),

        "argument_order": (
            frame_arguments
        ),

        "feature_field": (
            FEATURE_FIELD
        ),

        "minimum_feature_proportion": (
            MIN_FEATURE_PROPORTION
        ),

        "processing_order": [
            "count_features",
            "resolve_mutual_exclusions",
            "apply_frequency_threshold",
        ],

        "arguments": (
            analysis
        ),
    }

    with OUTPUT_JSON.open(
        "w",
        encoding="utf-8",
    ) as handle:

        json.dump(
            output,
            handle,
            ensure_ascii=False,
            indent=2,
        )

        handle.write(
            "\n"
        )


# =============================================================================
# Main
# =============================================================================

def main() -> None:

    print("=" * 100)
    print(
        "FRAME FEATURE DISTILLATION"
    )
    print("=" * 100)

    print(
        f"Frame             : "
        f"{FRAME_NAME}"
    )

    print(
        f"Input             : "
        f"{INPUT_JSONL.resolve()}"
    )

    print(
        f"Feature threshold : "
        f"> "
        f"{MIN_FEATURE_PROPORTION:.0%}"
    )

    # -------------------------------------------------------------------------
    # Load inference records
    # -------------------------------------------------------------------------

    records = load_jsonl(
        INPUT_JSONL
    )

    # -------------------------------------------------------------------------
    # Reconstruct sentences
    # -------------------------------------------------------------------------

    sentences = group_by_sentence(
        records
    )

    print(
        f"Frame examples    : "
        f"{len(sentences):,}"
    )

    # -------------------------------------------------------------------------
    # Determine frame length
    # -------------------------------------------------------------------------

    frame_arguments = (
        resolve_frame_arguments(
            sentences
        )
    )

    print(
        f"Arguments detected: "
        f"{len(frame_arguments)}"
    )

    print(
        f"Argument order    : "
        + " -> ".join(
            frame_arguments
        )
    )

    # -------------------------------------------------------------------------
    # Assign positional records to roles
    # -------------------------------------------------------------------------

    arguments = assign_arguments(
        sentences=sentences,
        frame_arguments=(
            frame_arguments
        ),
    )

    # -------------------------------------------------------------------------
    # Analyse
    # -------------------------------------------------------------------------

    analysis = analyse_frame(
        arguments=arguments,
        frame_arguments=(
            frame_arguments
        ),
    )

    # -------------------------------------------------------------------------
    # Detailed results
    # -------------------------------------------------------------------------

    for role in frame_arguments:

        print_role_analysis(
            role=role,
            analysis=analysis[
                role
            ],
        )

    # -------------------------------------------------------------------------
    # Concise frame
    # -------------------------------------------------------------------------

    print_distilled_frame(
        analysis=analysis,
        frame_arguments=(
            frame_arguments
        ),
    )

    # -------------------------------------------------------------------------
    # Save
    # -------------------------------------------------------------------------

    save_results(
        analysis=analysis,
        frame_arguments=(
            frame_arguments
        ),
    )

    print()
    print("=" * 100)
    print("COMPLETE")
    print("=" * 100)

    print(
        "Output:\n"
        f"  {OUTPUT_JSON.resolve()}"
    )


if __name__ == "__main__":
    main()

====================================================================================================
FRAME FEATURE DISTILLATION
====================================================================================================
Frame             : poke: Agent V Patient with Instrument
Input             : /home/mark/verbnet-roberta/notebooks/tagged_sentences.jsonl
Feature threshold : > 70%
Frame examples    : 50
Arguments detected: 3
Argument order    : Agent -> Patient -> Instrument

====================================================================================================
AGENT
====================================================================================================
Examples          : 50
Feature threshold : > 70%

ARGUMENT FILLERS
----------------------------------------------------------------------------------------------------
Allison, David, Sarah, James, Maria, Peter, Linda, Daniel, Alice, Matthew, child, doctor, baker, gardener, student, farmer, chef, tailor, scientist, mechanic, boy, girl, woman, man, nurse, artist, potter, cook, camper, fisherman, worker, researcher, tailor, child, baker, gardener, teacher, sculptor, technician, farmer, chef, camper, student, mechanic, scientist, tailor, cook, gardener, nurse, artist

ALL FEATURE FREQUENCIES
----------------------------------------------------------------------------------------------------
* Animate                           50/50  (100.0%)
* Concrete                          50/50  (100.0%)
* Human                             50/50  (100.0%)
* Internal_Control                  50/50  (100.0%)
* Natural                           50/50  (100.0%)
* Solid                             40/50  ( 80.0%)
! Unspecified_Gender_or_Neuter      37/50  ( 74.0%)
! Masculine                          7/50  ( 14.0%)
! Feminine                           6/50  ( 12.0%)

* = retained in final restriction
! = removed as a mutually-exclusive clash before thresholding

MUTUAL-EXCLUSION CLASHES
----------------------------------------------------------------------------------------------------
Removed: Feminine, Masculine, Unspecified_Gender_or_Neuter
Exclusive group: Feminine, Masculine, Unspecified_Gender_or_Neuter


FINAL ARGUMENT RESTRICTION
----------------------------------------------------------------------------------------------------
  Animate                           50/50  (100.0%)
  Concrete                          50/50  (100.0%)
  Human                             50/50  (100.0%)
  Internal_Control                  50/50  (100.0%)
  Natural                           50/50  (100.0%)
  Solid                             40/50  ( 80.0%)

====================================================================================================
PATIENT
====================================================================================================
Examples          : 50
Feature threshold : > 70%

ARGUMENT FILLERS
----------------------------------------------------------------------------------------------------
cloth, balloon, soil, cake, cushion, sand, fabric, dough, sponge, paper, puddle, skin, pastry, earth, clay, hay, potato, cloth, sample, rubber, mud, balloon, cushion, mattress, arm, canvas, clay, meat, fire, bait, foam, tissue, leather, jelly, bread, compost, model, wax, membrane, ground, sausage, embers, cork, gasket, gel, felt, dumpling, moss, finger, plaster

ALL FEATURE FREQUENCIES
----------------------------------------------------------------------------------------------------
* Concrete                          50/50  (100.0%)
* Solid                             50/50  (100.0%)
* Inanimate                         44/50  ( 88.0%)
! Non_Rigid                         41/50  ( 82.0%)
  Substance                         18/50  ( 36.0%)
! Rigid                             16/50  ( 32.0%)
  Artefact                          12/50  ( 24.0%)
  Comestible                         9/50  ( 18.0%)
  Natural                            9/50  ( 18.0%)
  Internal_Control                   8/50  ( 16.0%)
  Animate                            7/50  ( 14.0%)
  Body_Part                          5/50  ( 10.0%)
  Elongated                          5/50  ( 10.0%)
  Location                           3/50  (  6.0%)
  Human                              1/50  (  2.0%)
  Machine                            1/50  (  2.0%)
  Plant                              1/50  (  2.0%)
  Unspecified_Gender_or_Neuter       1/50  (  2.0%)

* = retained in final restriction
! = removed as a mutually-exclusive clash before thresholding

MUTUAL-EXCLUSION CLASHES
----------------------------------------------------------------------------------------------------
Removed: Non_Rigid, Rigid
Exclusive group: Non_Rigid, Rigid


FINAL ARGUMENT RESTRICTION
----------------------------------------------------------------------------------------------------
  Concrete                          50/50  (100.0%)
  Inanimate                         44/50  ( 88.0%)
  Solid                             50/50  (100.0%)

====================================================================================================
INSTRUMENT
====================================================================================================
Examples          : 50
Feature threshold : > 70%

ARGUMENT FILLERS
----------------------------------------------------------------------------------------------------
needle, pin, stick, fork, pencil, rod, skewer, spoon, probe, pen, stick, needle, fork, trowel, pencil, pole, skewer, pin, probe, screwdriver, stick, pencil, needle, rod, needle, stylus, tool, fork, stick, hook, rod, probe, awl, spoon, skewer, fork, pointer, stylus, probe, pole, fork, stick, pencil, screwdriver, probe, needle, skewer, stick, lancet, stylus

ALL FEATURE FREQUENCIES
----------------------------------------------------------------------------------------------------
* Concrete                          50/50  (100.0%)
* Elongated                         50/50  (100.0%)
* Inanimate                         50/50  (100.0%)
* Rigid                             50/50  (100.0%)
* Solid                             50/50  (100.0%)
* Artefact                          48/50  ( 96.0%)
* Pointy                            43/50  ( 86.0%)
  Internal_Control                  10/50  ( 20.0%)
  Machine                           10/50  ( 20.0%)

* = retained in final restriction
! = removed as a mutually-exclusive clash before thresholding

MUTUAL-EXCLUSION CLASHES
----------------------------------------------------------------------------------------------------
(none)

FINAL ARGUMENT RESTRICTION
----------------------------------------------------------------------------------------------------
  Artefact                          48/50  ( 96.0%)
  Concrete                          50/50  (100.0%)
  Elongated                         50/50  (100.0%)
  Inanimate                         50/50  (100.0%)
  Pointy                            43/50  ( 86.0%)
  Rigid                             50/50  (100.0%)
  Solid                             50/50  (100.0%)

====================================================================================================
DISTILLED FRAME
====================================================================================================

poke: Agent V Patient with Instrument

 1. Agent                Animate, Concrete, Human, Internal_Control, Natural, Solid
 2. Patient              Concrete, Inanimate, Solid
 3. Instrument           Artefact, Concrete, Elongated, Inanimate, Pointy, Rigid, Solid

====================================================================================================
COMPLETE
====================================================================================================
Output:
  /home/mark/verbnet-roberta/notebooks/distilled_frame_features.json